### ISSUE TITLE
Successful tests coming up as ignored

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1003]
![image](https://user-images.githubusercontent.com/743706/65148105-2996d600-d9e5-11e9-9507-da1789fcfbc9.png)

**Comment by sksamuel** [comment]
Then once the failing test passes, they all go green.

![image](https://user-images.githubusercontent.com/743706/65148253-6bc01780-d9e5-11e9-9759-1dc8aecf13f4.png)

**Comment by sksamuel** [comment]
This is a bug in intellij.

**Comment by glasser** [comment]
Is this reported to JetBrains anywhere?
