### ISSUE TITLE
Proposal: Gen.char()

### ISSUE THREAD

**Issue by EarthCitizen** [kotest/kotest#1005]
It would be great if `Gen.char()` existed. Looks like it would be fairly trivial to implement, with `random()` of the `Gen<Char>` returning `Random.nextPrintableChar()`.

**Comment by LeoColman** [comment]
Very true!
If you are interested in this, go for it :D

**Comment by EarthCitizen** [comment]
@Kerooker Which branch should the PR be for?

**Comment by LeoColman** [comment]
You can make it to master
