### ISSUE TITLE
shouldBeCalled assertion

### ISSUE THREAD

**Issue by joni-** [kotest/kotest#1015]
Would it be possible to implement an assertion that asserts that a function is called? We have a use-case where our function takes couple of functions as parameters and based on other parameters it may or may not call the functions. We'd like to test that correct functions are being called.

I've seen these kind of functions implemented in JS & Python test frameworks but didn't find such in Kotlintest.

**Comment by LeoColman** [comment]
I believe this goes more into mocking and spying business than testing itself.

I don't believe this should be supported by KotlinTest

**Comment by LeoColman** [comment]
I don't think there's even a way to verify this without bytecode manipulation, the way `mockk` does, for example

**Comment by sksamuel** [comment]
We could do something like,

someFun.shouldBeInvoked {
 .. some code here that uses "it".
}

It wouldn't be as powerful as mocking, but might be ok for simple scenarios.

**Comment by sksamuel** [comment]
I've added the following matchers to master:

```kotlin
   val fn0 = { println("") }
   fn0.shouldBeInvoked {
      it.invoke()
   }
   val fn1 = { a: String -> println(a) }
   fn1.shouldBeInvoked {
      it.invoke("qwe")
   }
```

Does something like that work for you @joni-

**Comment by LeoColman** [comment]
I think this goes too much into mocking business, doesn't it?

**Comment by sksamuel** [comment]
It's just wrapping a function. I guess you could call it mocking but it
doesn't do any jvm tricks.

**Comment by sksamuel** [comment]
Closing this as no feedback given.
