### ISSUE TITLE
Reproducible property tests

### ISSUE THREAD

**Issue by asm0dey** [kotest/kotest#1018]
If I have some complex behaviour defined by property test I need a way to reproduce it, possibly based on seeds.

For example I can have some chains of action built by input and exception should never be thrown. 
If exception if thrown - test will fail of course, but how can I reproduce it?

**Comment by LeoColman** [comment]
I believe this may be a duplicate of #815? If yes, it's already implemented in #960

**Comment by sksamuel** [comment]
Duplicate of #815. Will be included in release 4.0

**Comment by asm0dey** [comment]
Sorry guys, any ETA for 4.0?

**Comment by sksamuel** [comment]
End of Dec. You can always run from a snapshot 4.0 build as that has seeds already, but no guarantees of stability yet.
