### ISSUE TITLE
Add jsoup matchers

### ISSUE THREAD

**Issue by faogustavo** [kotest/kotest#1028]
skrape{it} is a Kotlin-based HTML/XML testing and web scraping library that can be used seamlessly in Spring-Boot, Ktor, Android or other Kotlin-JVM projects.

They want to add a lot of matchers and support the KotlinTest library (You can see all the expected matchers [in this issue](https://github.com/skrapeit/skrape.it/issues/9)). If you are comfortable with this, I can implement those matchers myself.

Most of them, are matchers from jsoup library and can be added to the project as an extension and be used by other projects, beside the skrape{it}.

**Comment by LeoColman** [comment]
Sure, go ahead!
I believe we can add an assertions module for skrape.it.

The mantainers of the project already said that support can be mantained here (just like we do for Arrow and KTor).

I don't see a reason why not.

**Comment by LeoColman** [comment]
If you need any help configuring the new module, let me know

**Comment by Kerooker** [comment]
If you need any help configuring the new module, let me know

**Comment by faogustavo** [comment]
Alright. Thanks @Kerooker

**Comment by sksamuel** [comment]
I think kotest-assertions-skrape would be a good addition.

**Comment by faogustavo** [comment]
@sksamuel as the lib just wants to add some assertations to jsoup classes, isn't it better to add a `kotest-assertations-jsoup`?

**Comment by sksamuel** [comment]
Yes sorry.

**Comment by LeoColman** [comment]
Oh, I didn't see that. I thought the matchers were for the lib itself. Guess I didn't read it properly =S

**Comment by christian-draeger** [comment]
i think it would be cool to go for `kotest-assertations-skrapeit` because we would have the freedom to add specific assertion on skrape{it}'s [`Result` object](https://github.com/skrapeit/skrape.it/blob/master/src/main/kotlin/it/skrape/core/Result.kt) (beside the document) in the future. in this case i mean assertions regarding the http response (status code, content-type, headers etc)

**Comment by sksamuel** [comment]
We could do both, no reason the jsoup specific ones should live in
a skrapeit module.

**Comment by faogustavo** [comment]
Yeps, my plan is to start with the JSOUP assertations that are more generic and than add some others that are specific from the skrape.it;

I already started the JSOUP and hope to open a PR with some basic matchers soon.

**Comment by faogustavo** [comment]
Hey guys.
Unfortunately, I'm a little bit busy these days and will not be able to add more matchers to jsoup. I just removed the WIP from the PR to merge the initial structure.
Doing this, it's possible for other developers add more matchers and start using it.

**Comment by sksamuel** [comment]
Great thanks for the pr!
