### ISSUE TITLE
New Assertion: shouldHaveSize for map

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1033]
Eg,

`map.shouldHaveSize(10)`

**Comment by raverona** [comment]
Isn't this covered by https://github.com/kotlintest/kotlintest/blob/02b4c84785c35a54ba78a2207283e7c8f9ab245f/kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/collections/matchers.kt#L281 ?

**Comment by LeoColman** [comment]
It isn't covered by `Collection.shouldHaveSize` (map doesn't subclass Collection), but this is a duplicate of #990 which was implemented by #997.

So I'm closing this as a duplicate
