### ISSUE TITLE
Running Kotlintest specs in IntelliJ with SpringAutowireConstructorExtension leads to shared context between specs

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1048]
See https://youtrack.jetbrains.com/issue/KT-34135#comment=27-3747465.

@Kerooker did we fix this already ?

**Comment by LeoColman** [comment]
I don't think we did, no.
But this seems unrelated to KT itself, as running `mvn verify` works. I assume `./gradlew test` works aswell due to that.

Seems like a plugin issue, don't you think?

**Comment by Kerooker** [comment]
I actually never physically seen anybody execute more than one test at a time, unless as a full test suite. I've never seen a `Execute all tests in this package` in my life
