### ISSUE TITLE
Codestyle: fix indentation

### ISSUE THREAD

**Issue by nikitabobko** [kotest/kotest#1049]
For now it's specified that it's 3 spaces in `.editorconfig`. But what I see? It's dutch concert. Somewhere 2 spaces are used and somewhere 3 spaces

**Comment by LeoColman** [comment]
I think Kotlin style guides recommends 4 spaces

**Comment by nikitabobko** [comment]
Whatever number of spaces. For now different indentations are used in different files. And it's not convinient because my IDEA sees `.editorconfig` and uses 3 spaces for indentation but file is indented with 2 spaces so I have to fix indentations my IDE inserts...

**Comment by sksamuel** [comment]
We're moving over to 3. No need to pad out with 4.

**Comment by EarthCitizen** [comment]
The contribution guide still says 2 spaces:

https://github.com/kotlintest/kotlintest/wiki/contribute

> We follow the Kotlin Coding Conventions , except the indentation which is only 2 spaces.

In my opinion, it would be easier for everyone involved if we use the Kotlin standard. But I was unaware of the .editorconfig file. I was submitting code based on the contribution guideline. I should reformat what I submitted 😀

**Comment by sksamuel** [comment]
4 spaces is too many in a language where you can have many levels of nested
blocks (nested functions, nested maps/flatmaps and so on). I don't know why
they picked 4, possibly because that's what Java developers are
most familiar with.
