### ISSUE TITLE
Add "ExecutionContext" object to extensions

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1059]

**Comment by LeoColman** [comment]
Could you elaborate a little bit on this one?

**Comment by sksamuel** [comment]
When you're writing a test extension (not a listener), an ExecutionContext object could be passed in, like JUnit does, with the current state of the engine. Things like: all the discovered specs, the current configuration.

See https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/ExtensionContext.html

**Comment by sksamuel** [comment]
Upon re-visiting it, it seems the extensions have everything they need, so closing.
