### ISSUE TITLE
Type mismatch for haveKey: Map and (Mutable)Map

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#1067]
kotlintest version: 3.4.2
kotlin: 1.3.50

![image](https://user-images.githubusercontent.com/2332528/68070087-89b9bf80-fd7a-11e9-9b46-de53592388c6.png)

**Comment by atmikev** [comment]
I'm not able to reproduce this on the `3.4` branch with kotlin `1.3.50`. I copied the code to `MapMatchersTest.kt` and compiled without the error.

Is anyone else able to reproduce?

**Comment by sksamuel** [comment]
Do you have the new type inference module turned on in intellij?

**Comment by BorzdeG** [comment]
@sksamuel yes. When you turn off the error disappears

![image](https://user-images.githubusercontent.com/2332528/68108628-52255180-fef9-11e9-819e-c7f31bcfffe6.png)

IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.4932.9, built on October 30, 2019

**Comment by sksamuel** [comment]
I've added some more tests for this and it works fine if you use map.shouldContainKey or mutable.shouldContainKey (ie, not the infix versions).

I guess they'll fix the type inference once it goes final as its still in beta at the moment. If it's still broken when they release kotlin 1.4 we can revisit.
