### ISSUE TITLE
for* (forAll etc) should accept supend functions

### ISSUE THREAD

**Issue by jensbaitingerbosch** [kotest/kotest#1068]
when you want to test suspend functions with `forAll`, `forOne`, ... you need to suround it with `runBlocking`:

```
suspend fun functionToTest(n: int) {
   delay(n*10)
}

listOf(1,2,3).forAll {
   runBlocking {
      functionToTest()
   }
}
```

it would be be easier if these method in kotlinTest.Inspectors would accept a supend functions like:

```
fun <T> forAll(col: Collection<T>, fn: suspend (T) -> Unit) {
  //...
}
```

**Comment by LeoColman** [comment]
I think this is a duplicate of #717.

I started the implementation there, but never had time to finish it. It's also probably outdated, but somethings may be reused
