### ISSUE TITLE
Change snapshot pointing to Kotest

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1075]
In effort to move forward to changing our name to Kotest, we already changed the name of all our packages and artifacts to Kotest.

With this, the maven snapshots are outdated, and new snapshots are being published to `io.kotest`. 

To allow more people to test our new things, let's change the `Snapshot` shield to `Kotest`!

**Comment by sksamuel** [comment]
I think we should do an 3.4 release this weekend. Updating the arrow dependencies specifically as 0.10 is not backwards compatible with 0.9 and its breaking things.

**Comment by LeoColman** [comment]
Sure

**Comment by sksamuel** [comment]
the release/3.4 branch has been updated to work with gradle 5.6 and it's upgraded to arrow 0.10.0

**Comment by LeoColman** [comment]
Do we want anything else at 3.4.3?

**Comment by LeoColman** [comment]
There are some easy-to-merge things, but I don't want the branches to get so different that they'll be hard to mantain

**Comment by sksamuel** [comment]
We could put in anything really straightforward.
