### ISSUE TITLE
Gen.take Should Allow Zero for Amount to Take

### ISSUE THREAD

**Issue by EarthCitizen** [kotest/kotest#1077]
`Gen.take()` should allow an amount of zero to be taken.

**Comment by LeoColman** [comment]
Why should it, tho?

Could you provide an use case to where one might want to take 0 values from a `Gen`?

**Comment by sksamuel** [comment]
You might be passing in a random number.
Either way it probably shouldn't error.

**Comment by EarthCitizen** [comment]
The first point is that this will match the behavior of the `take()` functions on Kotlin collections which only throw exceptions if the value is negative. IMO, this is the behavior that end users will probably expect from `Gen.take()` as well.

Where I would like to use this is in  #1078 (implement `Gen.string()` with `Gen.char()`). In this case a string can have a minimum length of 0 (or higher) and a max length. A very easy way to implement this is like the following:

```kotlin
// Where min String length is 0
// Where max String length is 10
val len = <generate Int between 0 and 10>
val str = Gen.char().take(len).joinToString(separator = "")
```

But this is also equally useful when you are generating any collection of generated values in which the collection size can be from 0 to max.

**Comment by LeoColman** [comment]
Sure. We can require >=0.

**Comment by LeoColman** [comment]
Not labelling this as a bug because originally we thought that the intended behavior was to take a specific > 0 amount.
