### ISSUE TITLE
Gen.combine

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1079]
Not sure if we have a method to take one or more gens and then allow us to return a new combined gen.

Gen.combine or Gen.flatMap

**Comment by LeoColman** [comment]
What type should `Gen.combine` be of?

```
Gen A : Foo
Gen B: Foo

Gen<A>.combine(Gen<B>): Gen<Foo>??
```

**Comment by sksamuel** [comment]
Yeah :

```
val genA: Gen<A> = ...
val genB: Gen<B> = ...
val genC: Gen<C> = Gen.combine(genA, genB) { a, b -> ... }
```

**Comment by ashishkujoy** [comment]
> Yeah :
> 
> ```
> val genA: Gen<A> = ...
> val genB: Gen<B> = ...
> val genC: Gen<C> = Gen.combine(genA, genB) { a, b -> ... }
> ```

How that will be different from the existing 
```
Gen.bind(gena: Gen<A>, genb: Gen<B>, createFn: (A, B) -> T)
```

**Comment by LeoColman** [comment]
> Yeah :

Oh, I thought that `combine` would mean merging two `Gen` in a single one. If that's not it, then I believe @ashishkujoy has the method to do it, which is part of our API already

**Comment by sksamuel** [comment]
Already exists so closing.
