### ISSUE TITLE
Compare two strings and show results with diff - which allows to quickly spot the difference

### ISSUE THREAD

**Issue by marisveide** [kotest/kotest#1084]
When comparing two strings with #kotlintest with the test like this:
```kotlin
    "compare two strings" {
      "1: one\n2: two\n3: three".shouldBe("1: one1\n22: two\n3: three")
    }
```

, the output looks like this:

```
expected: "1: one1
22: two
3: three" but was: "1: one
2: two
3: three"
org.opentest4j.AssertionFailedError: expected: "1: one1
22: two
3: three" but was: "1: one
2: two
3: three"
```

Even with such a short string - it's quite hard to spot, what exactly differs between those two strings. And it's much harder if comparing longer strings, or object attributes, as the result becomes just one long horizontally scrollable line.

However - we are all very used to read the "diff" - with its +/- lines, and colors, which instantly allow us to spot the difference.

For example, here's the result of the same assert, when ran by `rspec` (test lib for ruby):

```diff
expected: "1: one\n22: two\n3: three"
     got: "1: one\n2: two\n3: three"

(compared using ==)

Diff:
@@ -1,4 +1,4 @@
 1: one
-22: two
+2: two
 3: three
```

As you can see - it helps me in two ways.
First - it puts both strings right under each other so that I can spot character level differences.
Secondly, it shows nice `diff` with our familiar coloring so that I instantly see what's not different, and what's different.

Is there a way to achieve some test result comparison which would be similar, and give similar benefits to quickly spot the difference?

I tried KotlinTest and JUnit5 - both comparison results are very "horizontally scrollable in one line".

Am I overlooking something obvious here?

**Comment by sksamuel** [comment]
kotest will do the diff if a) you're running on the JVM and b) your string is over 50 lines long.
However you can control that 50 line limit.
If you set `kotest.assertions.multi-line-diff-size=0`  as a system property then it should use diff all the time.

**Comment by holgerbrandl** [comment]
Using a system property here feels like a flawed design. The contract that this kicks in a 50lines is totally unclear to the user. 


Also,  even when setting the property it did not show the diff, so I had to resort to use `kotlin.test.AssertionsKt#assertEquals(T, T, java.lang.String)` instead.

**Comment by sksamuel** [comment]
What about if when the diff kicks in, it also includes a line letting you know what happened and how to disable?
@holgerbrandl

**Comment by holgerbrandl** [comment]
My problem was more the other way round: There was no diff and no indication how to enable it. That's why ended up writing my own extension function (see referenced commit).

So adding some hint why a diff was not reported and how to enable it, would be more useful. A system property is a wrong approach IMHO, because it's a behaviour the user may want to set on a per test basis (or maybe even within a single test function). So a parameter or a different assert* seems better to me.

**Comment by sksamuel** [comment]
assert with diff is a good idea

"qweqwe" shouldBeWtihDiff "rtertert" or something.
