### ISSUE TITLE
Why AbstractFreeSpec.FreeSpecScope String.config test function is not suspend

### ISSUE THREAD

**Issue by YegorBabarykin** [kotest/kotest#1085]
Why AbstractFreeSpec.FreeSpecScope method suspend fun String.config have argument test with type `FreeSpecScope.() -> Unit` not `test: suspend FreeSpecScope.() -> Unit` ?

In current state i can't test suspend functions

**Comment by sksamuel** [comment]
Fixed, will be in 4.0
