### ISSUE TITLE
Property tests size or distribution parameter

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1095]
When generating random values, we probably don't want an even distribution.
For Gen.int we probably want more lower values than values of 4231654543 for example.

**Comment by LeoColman** [comment]
Could you elaborate a little bit on this one?

**Comment by sksamuel** [comment]
Yes once on a computer. I just create the ticket so I don't forget.

**Comment by EarthCitizen** [comment]
This might be interesting ancillary information:

http://hackage.haskell.org/package/hedgehog-1.0.1/docs/Hedgehog-Range.html#t:Range

HedgeHog (a property-based testing library for Haskell), has range, size, and scale. You choose your bounds (range) and type of distribution along the bounds (scale), then in the tests, you can modify the size in the tests or allow the generated size to flow through. In this case, size and distribution are separate things.

Haskell, via monads, has the advantage of being able to provide the size in an implicit context, which makes implementing that fairly seamless.

**Comment by sksamuel** [comment]
Very good information thank you.

So bounds on Gen<Int> might be 0,1000 and with a linear scale we  might
have size 0 10 20 ... 1000 and with scale exponential we might have 0 2 4 8
16 .. 512
