### ISSUE TITLE
Allow referencing the extension

### ISSUE THREAD

**Issue by kboom** [kotest/kotest#1096]
JUnit 5 has a neat extensions functionality which is not compatible with kotlintest even if it runs on JUnit framework. While the simple use cases in which we just need to log something can be handled by the `TestListener`, we cannot handle more advanced cases. In particular, how to interact with the extension (which seems reasonable and extremely useful)? Ideally, I would like to get a hold of the extension so I could query it.

In JUnit5 it would be (one of the options anyway)
```
@ExtendWith(MyExtension.class)
class Something() {

 @MyAnnotation
 MyType myType;

 @Test
 void doSomething() {
    myType.doSomething();
 }

}
```

In JUnit4 it would be even simpler

```
@Rule
MyRule myRule;

@Test
void fun() {
myRule.something();
}
```

This is useful for a variety of reasons:
* Encapsulating resource mocks along with the sets of methods to interact with them (reset etc.)
* Extracting common instantiation tasks hiding complexity from the tests - note that we could have handled it by a simple composition but then we would need to instantiate the object and later plug it into all of the lifecycle methods which is not ideal.
* More

**Comment by LeoColman** [comment]
You can keep a reference to the listener and then pass it to override

**Comment by sksamuel** [comment]
I don't quite understand the use case.

Does what @Kerooker says work?
```
class Test : FunSpec({

   private val listener = ...
   override fun listeners = listOf(listener)

})
```

**Comment by LeoColman** [comment]
> Does what @Kerooker says work?

I've done that in the past.

**Comment by LeoColman** [comment]
The use case is the following:

Suppose we have an embedded database. This database can be operated on, but it also depends on the lifecycle of the tests.

1. At the beggining, create the DB
2. At the end, destroy the DB
3. At any time, execute an operation on the database via this helper

```
val myDatabase = EmbeddedDatabaseHelper()

test("foo") {
    myDatabase.myOperation()
}
```

This database is destroyed after all tests are executed, but I need the reference inside the tests. The Listeners don't exactly support this, as we usually create them inside the `override listeners()` guy, but I've kept a reference to them outside the function and it all works fine.

**Comment by sksamuel** [comment]
I don't know if that's the OP's exact requirement. If it is then what you said would work.

**Comment by kboom** [comment]
Thanks guys, it indeed works fine.
It might not be directly apparent though so I would recommend enhancing the readme to make this pattern absolutely clear.
