### ISSUE TITLE
Eventually should be inline to support suspension

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1098]

**Comment by LeoColman** [comment]
Becareful with inlining everything.
If it's small, then it's ok, but if it calls many internal methods (like the properties functions), it might be dangerous to force the compiler to do all the inlining.

My initial experiments with inlining property testing functions lead to a 2h compile time, and I had to restart everything

**Comment by sksamuel** [comment]
It only inlines that single call. The rest is unchanged.

**Comment by sksamuel** [comment]
Now working in master.
