### ISSUE TITLE
Add support for JUnit 4 again

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1104]
Removing support from JUnit 4 was a mistake.

Android UI tests cannot run without JUnit 4.

Perhaps it's better to implement a Android-runner than the JUnit4 runner? (Although they'll be the same?)

**Comment by sksamuel** [comment]
Yep. It wasn't removed in a release though was it ?

**Comment by LeoColman** [comment]
No, snapshots only

**Comment by sksamuel** [comment]
Do android test still need junit4 with the recent work you've done ?

**Comment by Kerooker** [comment]
Unfortunately, yes.
I believe android will always need JUnit4, at least for 5~6 more years, until current APIs are deprecated

**Comment by Kerooker** [comment]
There are some crazy workaround to execute using JUnit 5
https://www.lordcodes.com/posts/testing-on-android-using-junit-5

But they're not exactly easy to do

**Comment by LeoColman** [comment]
Actually, let me see if there's a way to write tests without big workarounds using JUnit 5.

**Comment by sksamuel** [comment]
But is the issue that things like roboelectric don't work with junit5
rather than android itself.

**Comment by LeoColman** [comment]
No, android itself doesn't work with JUnit5 out-of-the-box, for UI tests

**Comment by tom-jb** [comment]
I'm wanting to use Kotest, but I'm targeting Android, and as far as I know JUnit 5 is not really supported for Android development.

Is it possible for me to use Kotest? If so, how? As far as I can see, JUnit 4 support has gone completely.
