### ISSUE TITLE
Q: What is the idiomatic way to use customer generators?

### ISSUE THREAD

**Issue by marceloverdijk** [kotest/kotest#1110]
How should custom generators be called?

Like:
```
data class Person(val name: String, val age: Int)

class PersonGenerator : Gen<Person> {
    override fun constants() = emptyList<Person>()
    override fun random() = generateSequence {
        Person(Gen.string().random().first(), Gen.int().random().first())
    }
}
```

I can call it like `PersonGenerater().random().first()` to get a single random instance.

But how should this custom generator be used in combination with `forAll` to test edge cases?

**Comment by LeoColman** [comment]
First things first, you're the one who generate edge cases. So for instance, you want a special case for a person which have a `'` on their name. You should add that as a constant, to make sure you're using the edge cases.

To use generators and `forAll`, `assertAll` and other similar function, I usually write a single test that use the values. For example:

```
test("Should save any person to the database") {
    PersonGenerator().assertAll { person: Person ->
        database.save(person)
    }
}
```

This invocation will exhaust all the constants and then start drawing from `random` until it ends. The default value for invocations is `1000`, but that can be changed as you call `assertAll`.

----

As for your Person generator, I'd do something like this:

```
object PersonGenerator : Gen<Person> {
    override fun constants() = listOf(Person("My'Name", 18), Person("Myname, the 1st.", 20))

    override fun random() = generateInfiniteSequence {
        Person(Gen.string().next(), Gen.positiveIntegers().next())
    }
}
```

The `constants` values are always drawn when a property test is used

**Comment by marceloverdijk** [comment]
Thanks for your swift answer 👍 

I missed the `assertAll()` on the generator class, but this explains it.

I initially thought that the generator would register itself in the Gen object somehow, 
making it possible to do something like `Gen.object<Person>().random().first()` in my code..

**Comment by LeoColman** [comment]
Ah, I see.
We don't scan classpaths or anything like that to find your gens, although a `Gen.register(myGen)` wouldn't be absolutely bad

**Comment by LeoColman** [comment]
@marceloverdijk I'll close this issue, ok?
If you still have questions feel free to either ask another one or ask to reopen this
