### ISSUE TITLE
kotlintest shouldMatchJson does not show error

### ISSUE THREAD

**Issue by elennaro** [kotest/kotest#1114]
It just shows java.lang.AssertionError: 
	at **$*(**Test.kt:111)

**Comment by sksamuel** [comment]
I cannot duplicate this and we have tests asserting the output. Can you show us code that recreates this?

**Comment by ashishkujoy** [comment]
> I cannot duplicate this and we have tests asserting the output. Can you show us code that recreates this?

I think this is in general with the output of tests(failed) which are run with gradle  not specific to ```shouldMatchJson```

For example the below screenshot show output for the test
```kotlin
class DemoTest : StringSpec() {
    
    init {
        "a 1 should be 1" {
            1 shouldBe 1
        }

        "a 2 should be 2" {
            2 shouldBe 1
        }
    }
}

```

<img width="709" alt="Screenshot 2020-02-09 19 35 13" src="https://user-images.githubusercontent.com/34642693/74103667-0fb48600-4b74-11ea-830b-725f6b1b016a.png">

**Comment by sksamuel** [comment]
So is this a bug or just a lack of gradle reporting ?
