### ISSUE TITLE
Pitest plugin in Maven

### ISSUE THREAD

**Issue by gigaSproule** [kotest/kotest#1115]
I'm trying to run the pitest plugin via maven, but it's always failing with this error:
```
[ERROR] 1) Error injecting constructor, org.pitest.util.PitError: No implementation title in manifest of plugin jar for class io.kotlintest.plugin.pitest.KotlinTestPluginFactory in file:/C:/Users/ukbsp/.m2/repository/io/kotlintest/kotlintest-plugins-pitest/3.4.0/ko
tlintest-plugins-pitest-3.4.0.jar
```

My pom configuration is:
```
...
<plugin>
    <groupId>org.pitest</groupId>
    <artifactId>pitest-maven</artifactId>
    <version>1.4.10</version>
    <executions>
        <execution>
            <phase>test</phase>
            <goals>
                <goal>mutationCoverage</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>io.kotlintest</groupId>
            <artifactId>kotlintest-plugins-pitest</artifactId>
            <version>${kotlintest.version}</version>
        </dependency>
    </dependencies>
    <configuration>
        <targetClasses><param>de.meindach.leadmanager.*</param></targetClasses>
        <testPlugin>KotlinTest</testPlugin>
        <verbose>true</verbose>
        </configuration>
</plugin>
...
```
The actual command I'm running is `mvn org.pitest:pitest-maven:mutationCoverage`. Is there something that I have missed out?

**Comment by LeoColman** [comment]
Ok, on a preliminary analysis, it seems that Pitest is examining some things from our pom:

https://github.com/hcoles/pitest/blob/41a3aa0d276189d1d21635cb48f052b31dfb8183/pitest-maven/src/main/java/org/pitest/maven/DependencyFilter.java#L46

It's looking for some information specific to Maven: `Implementation-Title` and `Implementation-Vendor`. We currently don't write that to our pom, and probably that's what's necessary to fix.

**Comment by LeoColman** [comment]
@sksamuel 
Could you investigate a little bit on this? I think you're the one that setup our publishing and pom shenanigans

**Comment by vhuc** [comment]
I keep getting the same error after the fix. I'm using the last version of kotest (4.0.1).
Is it possible to check if there is something else missing?
