### ISSUE TITLE
Improve documentation on Listeners and Extensions

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1118]
We have a page called `extensions` that documents both Extensions and Listeners
https://github.com/kotlintest/kotlintest/blob/master/doc/extensions.md

It's not exactly clear what use case is good for listeners, what are our current listeners...

Even our `SpringListener` is listed as `Spring Extension` at our main reference. This is confusing and should be improved.

**Comment by sksamuel** [comment]
I've added comprehensive documentation on the test listener.
