### ISSUE TITLE
New generators

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1120]
Hedgehog has a ton of good gens we could inplement for kotest.

http://hackage.haskell.org/package/hedgehog-1.0.1/docs/Hedgehog-Gen.html

**Comment by EarthCitizen** [comment]
The character-based ones can be churned out pretty quickly once we have the new `Gen.string()` merged.

**Comment by sksamuel** [comment]
Agreed. See my latest ticket on property test discussion too.

**Comment by sksamuel** [comment]
Added shuffle and subsequence.

**Comment by sksamuel** [comment]
Add choice.

**Comment by sksamuel** [comment]
Added element.
I think that's a good set now.
