### ISSUE TITLE
[Q] Is BehaviorSpec Given block executed for each test?

### ISSUE THREAD

**Issue by marceloverdijk** [kotest/kotest#1130]
With:

```
Given("a duck") {

    val duck= Duck()

    When("it quacks") {
        Then("it makes noise") {
            ..
        }
    }

    When("it walks") {
        Then("it moves") {
            ..
        }
    }
}
```

Is the `duck` instance (re-)created for each test? 
I need to create a new instance per test and I wonder it is correct behavior to use the `Given` block instead of the `beforeTest` fun?

**Comment by marceloverdijk** [comment]
It feels unnatural to have to do:

```
class DuckSpec : BehaviorSpec() {

    private lateinit var duck: Duck

    override fun beforeTest(testCase: TestCase) {
        duck = Duck()
    }

    init {

        Given("a duck") {

            When("it quacks") {
                Then("it makes noise") {
                    ..
                }
            }

            When("it walks") {
                Then("it moves") {
                    ..
                }
            }
        }
    }
}
```

**Comment by LeoColman** [comment]
>Is BehaviorSpec Given block executed for each test?

Depends on your `IsolationMode`. Check more documentation [here](https://github.com/kotlintest/kotlintest/blob/master/doc/isolation_mode.md).

What you should do to ensure `Given` is executed each time a test is executed, you should use `IsolationMode.InstancePerTest` or perhaps `IsolationMode.InstancePerLeaf`

**Comment by marceloverdijk** [comment]
Thanks! I missed the parted related to the `IsolationMode`. `IsolationMode.InstancePerLeaf`` is exactly what I was looking for 👍

**Comment by marceloverdijk** [comment]
Btw, could I set this as default behavior in my `ProjectConfig` (extending `AbstractProjectConfig`)?
E.g. via a listener or extension?

**Comment by LeoColman** [comment]
You could, yes, override the `isolationMode` function in `ProjectConfig` and you should be good to go

**Comment by marceloverdijk** [comment]
`AbstractProjectConfig` does not have the `isolationMode` itself, what method should I override best then? Keeping in mind to be able to override it per Spec class if needed..

**Comment by LeoColman** [comment]
https://github.com/kotlintest/kotlintest/blob/7c1fa1bd74c38d71d9e7452f801b37244207d1f9/kotlintest-core/src/main/kotlin/io/kotlintest/AbstractProjectConfig.kt#L59

**Comment by LeoColman** [comment]
And yes, if you override it in the Spec it will be prioritized over default

**Comment by marceloverdijk** [comment]
Thx again. I was on `3.3.2` which not had the `isolationMode` in the `AbstractProjectConfig`.

**Comment by LeoColman** [comment]
Ah, I see xD
So is everything sorted out now?

**Comment by marceloverdijk** [comment]
Yes, thx for your swift replies!
