### ISSUE TITLE
Integration with konform

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1131]
Konform is quite nice. Should we add an assertions module that allows users to assert on the results of a konform validation ?

**Comment by LeoColman** [comment]
I'd say well, why not?

**Comment by sksamuel** [comment]
Cool, I like the library, and it would make testing validations easier.

**Comment by simonenkoi** [comment]
Could you clarify how it should like?
Something like `T.shouldBeValid(Validation<T>)` and `T.shouldBeInvalid(Validation<T>)`?
What about assertions for validation errors?

**Comment by sksamuel** [comment]
I think that's good syntax. Or alternatively, `MyValidation.shouldBeValid(t)` and `MyValidation.shouldBeInvalid(t)`. That way the extension functions are not visible on Any.

For errors we should add some too yes. Any suggestions?

**Comment by simonenkoi** [comment]
It makes sense
I suggest adding `MyValidation.shouldContainError(String)` and use the composite matcher of `shouldBeInvalid` and error check to make it clear what the assertion was.
I'll take this one and submit PR the other day
