### ISSUE TITLE
Can't find test reports for gradle task allTests

### ISSUE THREAD

**Issue by meenakshi-dhanani** [kotest/kotest#1138]
I ran all tests with the following:
./gradlew jvmTest
./gradlew allTests
None of these are creating a test report for all tests.

Could someone please help me run and find reports for all tests using command line?

Please find my machine settings below:
openjdk 11.0.2

**Comment by sksamuel** [comment]
Do you have a test in that module? Can you create a sample project? What happens if you try ./gradlew test or ./gradlew check
