### ISSUE TITLE
Redundant dependency on old kotlin-reflect library

### ISSUE THREAD

**Issue by xsveda** [kotest/kotest#1140]
From version 3.4.0 KotlinTest depends on a very old version of `kotlin-reflect` library, see:
https://mvnrepository.com/artifact/io.kotlintest/kotlintest-assertions/3.4.2

`org.jetbrains.kotlin » kotlin-reflect | 0.11.91.1 (Mar 27, 2015)`

This causes as issues as the old version of `kotlin-reflect` depends on `com.google.protobuf:protobuf-java` which fails the build on project with Firebase SDK that uses `com.google.protobuf:protobuf-lite`:

> java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-java-2.5.0.jar (com.google.protobuf:protobuf-java:2.5.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)

**Comment by sksamuel** [comment]
Checked reflection in master and all is good.
