### ISSUE TITLE
Auto scan for project level extensions / listeners

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1143]
Since we will be scanning anyway for project config, may as well just pick up top level val or object declarations that are project listeners, and apply them.

**Comment by sksamuel** [comment]
Do we just detect any project wide listeners and add them ?
I think that is ok, why would you define a project wide listener if you weren't planning on using it.
Or we could have a marker annotation - @AutoScan
And we'll ignore private classes/objects.

**Comment by sksamuel** [comment]
We have `@AutoScan` on ProjectListeners now. No need to create config.
I think perhaps the same for TestListeners, and any that are autoscanned are applied to every spec. Same for constructor plugins, very useful for spring and koin - just bring it into the classpath and no need to register it at all !

**Comment by sksamuel** [comment]
We now support all extensions as autoscanned.

**Comment by simonenkoi** [comment]
@sksamuel I am out of the context, but is it possible to disable autoscanning for an extension from another package? For example, I've imported some package with autoscannable extension, but want to disable or override its functionality

**Comment by sksamuel** [comment]
Is there a usecase for this? If you had an extension that you didn't want to always be enabled, then you wouldn't mark it as autoscan and just add it manually to the projects that needed it.

**Comment by simonenkoi** [comment]
Just thought about some 3rd-party libraries. In the Spring Boot world, it is a huge pain when you have some auto-discoverable beans in the imported package and the author of this package did not think that users may want to override or disable his beans.
I am not sure that it is applicable for tests and developers of libraries will want to annotate their extension with AutoScan, just curious.

**Comment by sksamuel** [comment]
I suppose there were popular libraries that included extensions you didn't
care about. Any idea on how to stop them being autoscanned ?

**Comment by simonenkoi** [comment]
I've thought about distinction by class hierarchy (that child should replace parent in the list of discovered extensions), but I think that it is a possible case when someone wants to share some code using inheritance.
Does it make sense to add some boolean to ProjectConf to disable all the autoscanning and define extensions manually?
I am still not sure that there is a case we need to worry about and can adjust it later having some real-world scenario

**Comment by LeoColman** [comment]
@sksamuel 
> just bring it into the classpath and no need to register it at all

I don't think that's good.
Not all my tests are spring tests! What about my unit tests that I don't want a spring context? I don't want that to be auto scanned, for example

**Comment by sksamuel** [comment]
The spring context is only used if it's a spring object. It doesn't magically change non spring stuff.

**Comment by sksamuel** [comment]
I like the idea of having config to disable auto scanning. Other than that, I think we're good ? @Kerooker

**Comment by LeoColman** [comment]
Sure, it's a good workaround with not a lot of trouble to implement.

**Comment by sksamuel** [comment]
We now have autoScanEnabled in project config which can be set to false.
We also support autoScanIgnoredClasses to filter out classes which you don't want to be included.

I've also expanded the auto scan to all extensions, filters and listeners, and tidied up the class hierarchy a bit internally.
