### ISSUE TITLE
An empty test name is not being processed correctly.

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#1146]
This test will not be called. And the error about the incorrect test name will not be shown.
In fact, this is a ghost test

My expectations (either):
1) An error about an incorrect name will be generated for such a test
2) for such a test a "random" test name will be generated

```kotlin
import io.kotlintest.shouldBe
import io.kotlintest.specs.FunSpec

class ExampleTest : FunSpec() {
	 init {
		  test("") {
			   1.shouldBe(2)
		  }
	 }
}
```

kotlintest: 3.4.2

**Comment by sksamuel** [comment]
We should throw an error in this case.

**Comment by sksamuel** [comment]
Fixed in master.
