### ISSUE TITLE
Remove Try matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1149]
Try is deprecated in arrow 0.10.
We should remove the matchers for Try from kotest 4.0

**Comment by LeoColman** [comment]
Related to #1090

**Comment by sksamuel** [comment]
Done.

**Comment by LeoColman** [comment]
Was #1090 Done too?

**Comment by sksamuel** [comment]
I've added the replacement Try and upgraded some files as part of the composable specs merge. But there'e still more to be done.
