### ISSUE TITLE
Better formatted error for map comparsion

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1150]
expected: {"test1"=FAILED, "test2"=FAILED, "com.sksamuel.kotest.runner.junit5.JUnitTestRunnerListenerTests"=FAILED, "Kotest"=SUCCESSFUL} but was: {"test2"=FAILED, "test1"=FAILED, "com.sksamuel.kotest.runner.junit5.JUnitTestRunnerListenerTests"=SUCCESSFUL, "Kotest"=SUCCESSFUL}

is awful to read

**Comment by ashishkujoy** [comment]
@sksamuel any thought on this indented error message for map comparison
<img width="910" alt="Screenshot 2020-02-24 23 19 17" src="https://user-images.githubusercontent.com/34642693/75177455-3372f100-575c-11ea-88ae-31c8317f30dd.png">

**Comment by sksamuel** [comment]
Yes i like it.
Perhaps after the two maps we can display something like:
Values differed at keys "test1", "test"2.

And we should limit the map to only 10 entries or something with a ... if
we go over.
