### ISSUE TITLE
Improve Property-based testing documentation

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1152]
Which generators are available? How to use them?

We should have more samples on how to use and implement gens, and an exhaustive list on all the gens we have available (similar to the list we have for matchers)

**Comment by sksamuel** [comment]
I have reworked property testing docs to be far more comprehensive and to use the new arbs and exhaustives.

**Comment by Nimamoh** [comment]
Additionnally, would it be possible to mention to the user that `kotest-property` dependency need to imported?

**Comment by sksamuel** [comment]
Good idea, I've added a quick start section with the module information.
