### ISSUE TITLE
Not clear how to generate a list of arbitrary values

### ISSUE THREAD

**Issue by DannyRyman** [kotest/kotest#1155]
Working on the latest snapshot version, the new property based testing code does not appear to include Gen.list which could be used to create a list of values.

Is there another way to generate a list of values which in turn are generated from one of the arbitrary generator functions i.e. generate a list of random size of random integers?

**Comment by sksamuel** [comment]
I would say if you want to use prop testing you're better off on the existing release verrsion.
The property test code is undergoing a bit re-write. In fact, perhaps you'd like to comment?
https://github.com/kotlintest/kotlintest/issues/1121

**Comment by DannyRyman** [comment]
Thanks for the information. Apart from time, is there any other reason why this hasn't been imported into the new package yet? Has any thought been given to how this might be implemented? For instance, would you expect an implementation for both the arbitrary and progressive generators?

The reason I ask is that we will probably end up implementing this for ourselves. And if our implementation is generic enough, I may be able to submit a PR. So any guidance on this would be helpful.

**Comment by sksamuel** [comment]
All the existing functionality will be ported. I just did the bare minimum to get an implementation out for discussion.

**Comment by sksamuel** [comment]
In the latest snapshot, most of the gens are now converted, including `Arb.list` and you can do `.take(n)` or `.single()`.
