### ISSUE TITLE
Add matchers to Klock

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1156]
Klock is an [MPP Kotlin Library](https://github.com/korlibs/klock) to handle Date and Time in a MPP fashion.

We should add some matchers to their types, similar to the ones we have for `java.time`

**Comment by dragneelfps** [comment]
@Kerooker I would like to work on this. So for starters, we would need to create a separate module `kotest-assertions-kclock`, right?

**Comment by LeoColman** [comment]
Closed as per #1214
