### ISSUE TITLE
Add alias for shouldBeEqualToUsingFields and disallow specifying NO fields

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#1161]
Occasionally, I have to assert value-equality of Java class instances that do not implement `equals()` with kotlintest (also see [this](https://stackoverflow.com/questions/12147297/how-do-i-assert-equality-on-two-classes-without-an-equals-method)). For these cases, it would be nice to have a matcher that iterates over all fields via reflection (recursively) and asserts value equality for each.

**Comment by sksamuel** [comment]
Agreed, and related to #822

**Comment by LeoColman** [comment]
We do have something like that that, I think

Something similar to
`shouldBeEqualToUsingFields ... `

**Comment by sschuberth** [comment]
I skimmed through https://github.com/kotlintest/kotlintest/blob/master/doc/matchers.md before but didn't find anything...

**Comment by sschuberth** [comment]
But it's indeed there, yay!

https://github.com/kotlintest/kotlintest/blob/068148734769f534223be89673639f46e8430ab4/kotest-assertions/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L32

**Comment by LeoColman** [comment]
Hmm...
It's not documented, or it isn't released yet (and therefore not documented due to that), I wonder?

**Comment by sschuberth** [comment]
Looks like it was introduced in f537d7beef9b490efdba893170a41069c001d1c1 as part of working on https://github.com/kotlintest/kotlintest/issues/711 which is included in version 3.3.1.

**Comment by sksamuel** [comment]
Should we add an alias. It's a bit of a long name

**Comment by sschuberth** [comment]
Also, it's only available as an extension function, not as an infix operator.

**Comment by sschuberth** [comment]
Doh, and it does not work at all as I would have expected: When called without a second argument, *no* instead of *all* fields are compared. That function should probably be changed to either require at least one field to be specified, or to compare all fields if none are given.

**Comment by sksamuel** [comment]
Yes that's totally a bug. Let's fix that.

**Comment by LeoColman** [comment]
There's also the `shouldBeEqualToIgnoringFields`, which would fit your use case, IIRC

**Comment by sschuberth** [comment]
I've actually tried it @Kerooker, but it that gave me:

    kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class org.apache.maven.settings.Proxy with modifiers "private"

**Comment by ashishkujoy** [comment]
@sksamuel are we still looking for alias? A part of it has been done in #1176

**Comment by sksamuel** [comment]
I think we just need to fix the bug that @sschuberth put up. Using shouldBeEqualToIgnoringFields gave ```kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class org.apache.maven.settings.Proxy with modifiers "private"```
I imagine its because his class has private field or something.

**Comment by sschuberth** [comment]
> I imagine its because his class has private field or something.

Exactly, it Maven settings' `Proxy.java` which has private fields.

**Comment by ashishkujoy** [comment]
@sschuberth have a look at #1208 that will fix the issue

**Comment by ashishkujoy** [comment]
Done in #1208
