### ISSUE TITLE
Type inference causes shouldBe to act in an unintended matter.

### ISSUE THREAD

**Issue by gabrielshanahan** [kotest/kotest#1163]
Hello everyone,

at first glance, the following code should not compile (in this example, the author forgot to call .toString() on the class instance):

```
class Test {
    override fun toString(): String = "Hello"
}

Test() shouldBe "Hello"
```

However, not only does it compile, it produces the output `Exception in thread "main" org.opentest4j.AssertionFailedError: expected: "Hello" but was: Hello`, which is very confusing.

The reason this happens is that the signature for `io.kotlintest.shouldBe` is `infix fun <T, U : T> T.shouldBe(any: U?)`, and the compiler infers T to be Any, which allows it to compile, and then the toString() method is called when generating the exception message. But this is clearly not the intended behavior. I asked about this [in the Kotlin forums](https://discuss.kotlinlang.org/t/incorrect-type-check-when-using-shouldbe-on-class-with-overloaded-tostring-method/15447/5).

I recently stumbled on a solution: add the @OnlyInputTypes annotation to the type parameter T in the signature of `shouldBe`, which prevents the compiler from raising the type to Any. This annotation is internal, but [there is a way to make it work](https://youtrack.jetbrains.com/issue/KT-13198#focus=streamItem-27-1649043.0-0) (basically by copy-pasting it).

It doesn't seem like that much work to implement this in the various functions in KotlinTest and I wanted to get the teams opinion on this - do you consider it the right thing to do and would you be open to accepting a pull request?

Thanks!

Edit: Just noticed that according to the YouTrack ticket, the annotation is scheduled to be made public in 1.4. If that's the case, it would probably be worth postponing the implementation until then.

**Comment by sksamuel** [comment]
Seems like a good idea. We could implement it now using the work around, and then once 1.4 is out, switch over to the public version.

**Comment by gabrielshanahan** [comment]
Cool! Do you want to work on this internally or should I?

**Comment by sksamuel** [comment]
Please feel free.

**Comment by sksamuel** [comment]
@gabrielshanahan did you get chance to look at this ?

**Comment by gabrielshanahan** [comment]
Hey @sksamuel , sorry not yet, I'm bogged down by real life at the moment. I'll get back to you as soon as I get the chance.

**Comment by sksamuel** [comment]
I might take a look if you don't mind.

**Comment by sksamuel** [comment]
I had a little play about and the compiler complains that the annotation is not public (Even when you copy n paste it).

Also, we use `shouldBe` for both matchers and "values" and then it breaks. If you seperate these out into separate functions it breaks on `a shouldBe null`.

So I got close but not close enough.

**Comment by gabrielshanahan** [comment]
Hey @sksamuel , have a look here for a working example using the annotation: https://github.com/gabrielshanahan/onlyinputtypestest

I did run into a "Only the Kotlin standard library is allowed to use the 'kotlin' package" error at first, but that can suppressed with a compiler arg (https://stackoverflow.com/a/58097520), as per the build.gradle in the repo I linked to.

As for the rest, you lost me O:-) What do you mean by "both matchers and values"?

**Comment by sksamuel** [comment]
Ok, but does the end user require that compiler flag as well ?
I can test that out.

The matchers / values bit is because the should method accepts both a
value, and a matcher. And a Matcher<U> is not compatible with U.

**Comment by gabrielshanahan** [comment]
I did a quick test and managed to get it working by:

1. Adding the annotation to `kotest-core/src/commonMain/kotlin/kotlin/internal/Annotations.kt`
2. Adding the following to `kotest-core/build.gradle.kts`:

```
targets.all {
      compilations.all {
         kotlinOptions {
//            Sidenote: AFAIK, this line never had any effect, as freeCompilerArgs is not modified, but rather a new array is returned
//            freeCompilerArgs + "-Xuse-experimental=kotlin.Experimental"
            freeCompilerArgs += listOf("-Xuse-experimental=kotlin.Experimental", "-Xallow-kotlin-package")

         }
      }
   }
```

3. running the following:

```
class App {
   infix fun <@OnlyInputTypes T, U : T> T.shouldBe(any: U?) {
      AssertionCounter.inc()
      if (this == null && any != null) {
//            ErrorCollector.collectOrThrow(equalsError(any, this))
      } else if (!compare(this, any)) {
//            ErrorCollector.collectOrThrow(equalsError(any, this))
      }
   }

   infix fun <@OnlyInputTypes T, U : Matcher<T>> T.shouldBe(any: U) {
      should(any as Matcher<T>)
   }

   fun withClueEcho(other: String) = object : Matcher<String> {
      override fun test(value: String)= MatcherResult(false,
         "Should have the details of '$value' and $other",
         "Should have the details of '$value' and $other")
   }

   fun doTest() {
      // Compiles & runs, throws exc.
      "1" shouldBe withClueEcho("hello")
      // Compiles & runs, doesn't do anything because ErrorCollector is commented out
      "1" shouldBe null
      // Doesn't compile
//      "1" shouldBe 3
   }
}
```

I wasn't able to explicitly test whether the compiler flag is necessary, however I was able to build the kotest-extensions module, which dependes on kotest-code, without adding a compiler flag to kotest-extensions. Also, when I removed the compiler flag from kotest-core, the kotest-extensions module would not build. It feels like this should imply that clients don't need the flag, but I'm not 100% on that one.

Sorry I can't currently dedicate more time than this.

**Comment by sksamuel** [comment]
That's great. I can continue from there.

**Comment by sksamuel** [comment]
See the commit on this thread.
I've built on your work and got things working.
One downside is you can't do:

`animal shouldBe dog`

and

`dog shouldBe animal`

We can vary the type on one side, but I'm not sure if we can say we want the inferred type to be the max of the two input types but no higher. We can do it on one side, and the right side as the sub type is probably best, as then we can do,

`option shouldBe Some(a)`

**Comment by gabrielshanahan** [comment]
I looked through briefly and pointed out a couple of things that I noticed.

As for the one-sided varying, if that's the case then I agree having the right side as the subtype is preferable, but I would point this out in the docs, since it breaks the reflexivity of shouldBe that one intuitively expects.

**Comment by sksamuel** [comment]
Looks like @OnlyInputTypes is being targeted for 1.5.0
