### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1171]
As we move very close to releasing 4.0 it's time to look at the logo.

We can either go with the familiar with do something funky. Please add your own designs to.

![new_logo1](https://user-images.githubusercontent.com/743706/72764269-f2ac1900-3bac-11ea-82e0-ad454b6fe313.png)
![Screenshot from 2020-01-20 17-35-06](https://user-images.githubusercontent.com/743706/72764271-f63fa000-3bac-11ea-9b6c-85f382860d14.png)
![Screenshot from 2020-01-20 17-36-16](https://user-images.githubusercontent.com/743706/72764273-f6d83680-3bac-11ea-8f34-f8ab75b3d16c.png)

**Comment by LeoColman** [comment]
I like the current logo, so I like the first one

**Comment by LeoColman** [comment]
Altought the last one is funny

**Comment by sksamuel** [comment]
![new_logo2](https://user-images.githubusercontent.com/743706/73327569-1d851580-421c-11ea-8212-6edc2d9fa5ef.png)

@Kerooker

**Comment by EarthCitizen** [comment]
The last one reminds me of the logo for Rust.

**Comment by sksamuel** [comment]
Yeah fair point.

![new_logo3](https://user-images.githubusercontent.com/743706/73467798-743c3d80-4349-11ea-9319-b50f99ee9988.png)

**Comment by sksamuel** [comment]
![logo4](https://user-images.githubusercontent.com/743706/73493572-9ef1ba80-4378-11ea-9329-0ea3039878c6.png)

Or something like this (obviously I would tidy it up nicer).

**Comment by sksamuel** [comment]
![new_logo4](https://user-images.githubusercontent.com/743706/73599602-be205180-450a-11ea-9ae9-590fd2691598.png)

**Comment by sksamuel** [comment]
![new_logo4](https://user-images.githubusercontent.com/743706/73599619-f2940d80-450a-11ea-806c-b5218c48d6d1.png)

**Comment by tibtof** [comment]
![kotlintest](https://user-images.githubusercontent.com/6090010/73800113-6ca0ec80-47c0-11ea-80dc-8546c5aa3301.png)

It’s just a sketch, but if you like the idea I could polish it.

**Comment by sksamuel** [comment]
Oh that's pimp

**Comment by tibtof** [comment]
Some variations:
![kotest1](https://user-images.githubusercontent.com/6090010/73869992-f51c9d00-4853-11ea-8693-e6ec3f8b118a.png)
![kotest2](https://user-images.githubusercontent.com/6090010/73869996-f77ef700-4853-11ea-8152-c5428ce01706.png)
![kotest4](https://user-images.githubusercontent.com/6090010/73870741-45e0c580-4855-11ea-9a3e-38976bfcaeb7.png)

If it's not obvious, the idea is that the green check can also be seen as a T.

**Comment by sksamuel** [comment]
I think the first one is the best where the check/tick is more pronounced.
Are we allowed to use styling like kotlin?

**Comment by tibtof** [comment]
This is what I found in brand usage. In my opinion it is different enough, but my opinion has no legal value. I could use a different colour than blue for the K so that is event more distinctive. Maybe red, to indicate potential errors?
https://kotlinlang.org/foundation/guidelines.html

**Comment by tibtof** [comment]
I found more details here: https://discuss.kotlinlang.org/t/use-of-kotlin-logo-when-referring-to-kotlin-in-a-blog-post/4354/2
I guess I could drop them an email.

**Comment by sksamuel** [comment]
I wonder if they don't want projects using their jetbrains graphics because
its not just kotlin that has that kind of effect.

**Comment by sksamuel** [comment]
@tibtof could you do something with the T effect that wasn't based on jetbrains brand stuff ?

**Comment by tibtof** [comment]
Can do, but I sent an email to jetbrains. Let's wait for an answer and see where to go from there.

**Comment by tibtof** [comment]
Meanwhile, here's a version with just a hint of the K:
![kotest-hint](https://user-images.githubusercontent.com/6090010/74108613-dafcfa80-4b84-11ea-8f47-a8148bf61b79.png)

**Comment by sksamuel** [comment]
Nice, any other variations with the actual text of kotest ?

**Comment by tibtof** [comment]
Let's use this as the K in kotest, give me a minute...

**Comment by tibtof** [comment]
Of the fonts I have installed I like this one, but I'll try to find a better one:
![kotest-text](https://user-images.githubusercontent.com/6090010/74108794-5e6b1b80-4b86-11ea-9580-bb5ee812f9c5.png)

**Comment by sksamuel** [comment]
It might work better if we stick with the original font and incorporate this k.

**Comment by tibtof** [comment]
Sure, what's the name of the font?

**Comment by sksamuel** [comment]
Gotham Black, Medium

**Comment by tibtof** [comment]
Here it is:
![kotest-gotham](https://user-images.githubusercontent.com/6090010/74109042-ab4ff180-4b88-11ea-8a79-5a8c6124abcd.png)
![kotest-black](https://user-images.githubusercontent.com/6090010/74109224-501efe80-4b8a-11ea-9e75-2430275ae265.png)

**Comment by sksamuel** [comment]
Yeah I like it. What about playing about with the colours, the text black
and the green a little darker ?

**Comment by tibtof** [comment]
I think black on the text works better if the K seems to also be black. Here is a try with a black K under a green overlay:
![kotest-black-2](https://user-images.githubusercontent.com/6090010/74134032-71b3d080-4bf2-11ea-9d24-7f36250dc35e.png)
![kotest-black-k](https://user-images.githubusercontent.com/6090010/74147164-5d300200-4c0b-11ea-92f2-d35226083120.png)

**Comment by sksamuel** [comment]
I like this.

**Comment by tibtof** [comment]
Meanwhile I received an answer from jetbrains saying it's ok to use the first logo that I shared. IMO the last one looks best, I would go with that.

**Comment by mechatronik** [comment]
I would merge stylized Kotlin logo (the first one with pronounced tick, maybe in green/black or green/red) with the last text logo. U can then use them both interchangeably. In the last one the K is not that obvious - I can't stop seeing tick and **otest**

**Comment by sksamuel** [comment]
I agree with the tick and otest thing @mechatronik 

![logo6](https://user-images.githubusercontent.com/743706/74597254-b344e100-5021-11ea-8dc8-da76291059e8.png)

**Comment by sksamuel** [comment]
@tibtof can you share that email ?

**Comment by tibtof** [comment]
Sure, but I don't know if it's ok to share it publicly. I have an email at gmail.com, same as my username. Please drop me an email and I will forward it to you.

**Comment by tibtof** [comment]
TBH, I don't think that black K looks very good over the logo. Maybe keep only `otest` in black?
I could try it if you'd like.

**Comment by sksamuel** [comment]
Please feel free to add as many variations as you want.
I don't think the black `otest` and logo `k` gels as well.

**Comment by tibtof** [comment]
Yeah, you're right. But I think it looks better having the logo on the side, same way Kotlin does:
![kotest](https://user-images.githubusercontent.com/6090010/74674156-714ea300-51b9-11ea-9916-e5b406ee21ea.png)

**Comment by tibtof** [comment]
A draw the initial logo mostly by hand, in Procreate, and I don't have a better resolution for it. I created a similar one in photoshop with better proportions and resolution. Here is a version with Kotest and another one with just the logo in a square (it should work better as the organisation logo). If you're using photoshop I can also create a PR with it in docs. I can also do further changes if you'd like. Now it's a lot easier to work on the colours.
![kotest-2](https://user-images.githubusercontent.com/6090010/74678887-fd19fc80-51c4-11ea-9430-7044650110fc.png)
![kotest-logo](https://user-images.githubusercontent.com/6090010/74678891-fee3c000-51c4-11ea-8304-01032d3b804d.png)

**Comment by tibtof** [comment]
Playing around a bit:

![kotest-abstract](https://user-images.githubusercontent.com/6090010/74679682-381d2f80-51c7-11ea-9ce3-450ed6495ce3.png)
-----
![kotest-up](https://user-images.githubusercontent.com/6090010/74680140-65b6a880-51c8-11ea-9b49-93d63048a16a.png)

**Comment by sksamuel** [comment]
I do like the colours a lot, although we could try playing with red for the
blue?

**Comment by tibtof** [comment]
I'll try, but I think it would hurt your eyes 🙂

**Comment by sksamuel** [comment]
lolol

**Comment by tibtof** [comment]
Here it goes:
![kotest-red](https://user-images.githubusercontent.com/6090010/74684344-53426c00-51d4-11ea-8465-d78cf711a9f2.png)
![kotest-logo-red](https://user-images.githubusercontent.com/6090010/74684351-563d5c80-51d4-11ea-8ad6-4074d9a8a33a.png)

**Comment by tibtof** [comment]
Here's one with a bit of orange, the colour that IntelliJ uses for failed tests (or is it yellow?!):
![kotest-orange](https://user-images.githubusercontent.com/6090010/74685074-28591780-51d6-11ea-9069-7a60ab316e64.png)

**Comment by mechatronik** [comment]
I think it serves the purpose well, but it's not the most fortunate set of colours...

**Comment by sksamuel** [comment]
I agree. The blue one is nicer.

**Comment by sksamuel** [comment]
Closing this as we have an awesome new logo now thanks to @tibtof
