### ISSUE TITLE
Blog / Article links for migration

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1185]
Ensure that any links in the following articles continue to point to the project in the right place.

- [x] - https://proandroiddev.com/kotlintest-pro-tips-54ce19c32c68
- [ ] - https://proandroiddev.com/whats-new-in-kotlintest-3-2-and-3-3-affbc1b25e1d
- [x] - https://dev.to/kerooker/testing-koin-applications-with-kotlintest-1iip
- [x] - https://dev.to/kerooker/testing-a-spring-boot-application-with-kotlintest-pgd
- [ ] - http://www.douevencode.com/articles/2018-05/kotlintest-3-release-android/
- [x] - https://levelup.gitconnected.com/on-the-mysteries-of-kotlin-test-444cf094e69f
- [ ] - https://www.zuhaibahmad.com/android-spec-testing/
- [x] - http://www.java-allandsundry.com/2017/07/kotlintest-and-property-based-testing.html
- [ ] - https://phauer.com/2018/best-practices-unit-testing-kotlin/
- [x] - https://proandroiddev.com/data-driven-testing-with-kotlintest-a07ac60e70fc
- [ ] - https://agiledojo.de/2019-12-25-kotlin-test/
- [ ] - https://medium.com/capital-one-tech/blackbox-api-testing-with-kotlin-for-restful-microservices-183adc2b8088
- [ ] - https://medium.com/@herve.darritchon/how-to-begin-with-kotlintest-1bc045906108
- [ ] - https://medium.com/kotlin-lang-notes/selenium-kotlintest-4db1da9811cc
- [ ] - https://medium.com/innovation-development/une-api-rest-kotlin-d%C3%A9velopp%C3%A9e-en-5-minutes-63a189b80809
- [ ] - https://medium.com/@mutebibrian256/testing-koin-applications-with-kotlintest-d2ff9b23fff4
- [ ] - https://medium.com/sodalabs/painless-unit-testing-with-kotlintest-mockk-8854d549b96b
- [ ] - https://proandroiddev.com/introducing-the-kotlintest-intellij-plugin-cf8005e9177a
- [ ] - https://proandroiddev.com/on-kotlin-a-unit-test-conversion-guide-71e0597bb45d

**Comment by ashishkujoy** [comment]
Should we include [awesome-kotlin](https://github.com/mcxiaoke/awesome-kotlin) as well in this list?

**Comment by kortov** [comment]
https://github.com/KotlinBy/awesome-kotlin too

**Comment by sksamuel** [comment]
I have created PRs for both the awesome kotlin pages

**Comment by LeoColman** [comment]
Also in course:
[Rename StackOverflow task to Kotest](https://meta.stackoverflow.com/questions/394005/rename-kotlintest-tag-to-kotest)

**Comment by LeoColman** [comment]
Did we get all of these done?

**Comment by sksamuel** [comment]
Yerp
