### ISSUE TITLE
Is usage of MIN_VALUE for floating point number generators correct?

### ISSUE THREAD

**Issue by MiSikora** [kotest/kotest#1216]
Generators like `numericDoubles` or `numericFloats` use `MIN_VALUE` as the `from` parameter. I wonder if this is correct as `literals` field contains `-1.0` which is then filtered by default as it is not in rage of `MIN_VALUE..MAX_VALUE`?

**Comment by sksamuel** [comment]
It should be max negative number.

**Comment by LeoColman** [comment]
This probably happens for Int and Long generators as well

**Comment by MiSikora** [comment]
I don't think so. `MIN_VALUE` for `Int` and `Long` represents max negative number. It is only with floating point numbers that `MIN_VALUE` represents basically epsilon.

**Comment by sksamuel** [comment]
Yes with double/floats min value is like 0.00000000000000000000000001
rather than -Double.MAX
