### ISSUE TITLE
SpringBootTest not picking up ActiveProfiles

### ISSUE THREAD

**Issue by dragneelfps** [kotest/kotest#1223]
For the following code:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("dev")
class DbTest : StringSpec() {

  override fun listeners() = listOf(SpringListener)

  @Autowired
  lateinit var persistenceDataRepository: PersistenceDataRepository

  //tests....
}
```

I am getting undefined value of `spring.active.profiles` as 
```
env=spring.profiles.active_IS_UNDEFINED
```
Also, `application-dev.yml` is not picked up as app configs.

### Expected

I should get
```
env=dev
```

I have tried with `SpringAutowireConstructorExtension` as well. Same result.

**Comment by LeoColman** [comment]
Hello!

When trying to run a simple example using JUnit4, I failed to get that to work.

We have the following test, that verifies we are getting things from properties correctly:
```
@SpringBootTest(classes = [Components::class])
@ActiveProfiles("test-profile")
class ActiveProfileSpringTest : FunSpec() {

    override fun listeners() = listOf(SpringListener)

    @Value("\${test-foo}")
    lateinit var testFoo: String

    init {
        test("Should load active profile properties correctly") {
            testFoo shouldBe "bar"
        }
    }
}
```
and it passes.

----

Do you have a minimum example of your intended behavior that works with plain JUnit, but doesn't work with Kotest?

**Comment by dragneelfps** [comment]
closing this for now since I dont have time to reproduce it right now. will do it later on and re-open if needed.
