### ISSUE TITLE
`It` should require lambda parameter

### ISSUE THREAD

**Issue by BaloghTamas** [kotest/kotest#1227]
I don't see the benefit of having an `it` block without a lambda. However, forgetting braces could lead to issues, so I think it should be prohibited by the DSL itself.

For instance in this test `It: should be 7` would break, while others will pass.
```kotlin
class CalculatorTest : DescribeSpec({
    describe("Calculator") {
        val calculator = Calculator()

        describe("when add is called with 4 and 3") {
            val result = calculator.add(4, 3)

            it("should be 7") {
                result shouldBe 8
            }

            it("should not be 8") {
                result shouldNotBe 8
            }
        }
    }
})
```

However, forgetting the braces on the same statement, would break `Describe: when add is called with 4 and 3`, which could be misleading for large tests.

```kotlin
class CalculatorTest : DescribeSpec({
    describe("Calculator") {
        val calculator = Calculator()

        describe("when add is called with 4 and 3") {
            val result = calculator.add(4, 3)

            it("should be 7")
                result shouldBe 8

            it("should not be 8") {
                result shouldNotBe 8
            }
        }
    }
})
```

**Comment by sksamuel** [comment]
I'm not sure we can enforce this in the language. `it("should be 7") returns a TestBuilder not there's no way we can enforce you use it at compile time. We could do something at runtime though.

**Comment by lwasyl** [comment]
Could it perhaps just be `internal` for the library? Btw what's the purpose of it, overall? It's not `suspend`able and it's not called anywhere within `AbstractDescribeSpec` 🤔

**Comment by BaloghTamas** [comment]
I see now, that the purpose of this approach is to let configuration of the test cases, like here:
https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-core/src/jvmTest/kotlin/com/sksamuel/kotest/specs/describe/DescribeSpecExample.kt#L59

Still, I believe the case of undefined and unconfigured `it` blocks should be handled, as it has a high probability that the library user unintendedly defined them this way, and can be a source of issues.

**Comment by sksamuel** [comment]
Beta2 is released which will throw an exception when creating tests if you use this kind of syntax.
