### ISSUE TITLE
Make eventually and continually configurable with pollDelay

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1244]
Like [awaitility]( https://github.com/awaitility/awaitility). [process of waiter ](https://github.com/awaitility/awaitility/blob/master/awaitility/src/main/java/org/awaitility/core/ConditionAwaiter.java#L72)
 I want set poll delay, because now in `while` It's look like DOS. For example, I ask server by API call about something for 1 second. Without delay it's more than 10 000 calls. For me enough just 5 or 10 call for second or 2 it doesn't matter but not 10 000.

**Comment by ashishkujoy** [comment]
@crazyk2 @Kerooker  We have [retry](https://github.com/kotest/kotest/blob/master/kotest-assertions/src/commonMain/kotlin/io/kotest/assertions/Retry.kt) that accept the delay between each retry. Hope that suffice the need.

**Comment by crazyk2** [comment]
@ashishkujoy I can work with `retry`. 
1) But this feature is not obvious so I even didn't think about `retry`
2) I don't want to set `maxRetry` count. I should count this number every time - `timeout` / `delay` + 1 = `maxRetry`. Why? I just know timeout and want to set approximate delay
P.S. fix your `retry` url

**Comment by sksamuel** [comment]
I've added poll as an option to eventually and continually. This will be included in 4.0 final.
