### ISSUE TITLE
Generate data class using reflection in property tests

### ISSUE THREAD

**Issue by Mishkun** [kotest/kotest#1245]
Right now, Arb support only a limited set of types it could create. It is really tedious to hook up all different Gen's to create a Gen for any custom class. Although most data classes have at least one constructor and could be created using reflection.

A sample on to how to achieve that can be found here 
https://github.com/serpro69/kotlin-faker/blob/master/src/main/kotlin/io/github/serpro69/kfaker/provider/RandomProvider.kt

So, what do you think about that?

**Comment by sksamuel** [comment]
So you want to be able to say Arb<Foo> and if Foo is data class Foo(a:
String, b: Boolean) then it automatically uses a StringArb and a BooleanArb
to generate Foos.
Seems like a good idea.

**Comment by sksamuel** [comment]
This is now in master and will be included in 4.0.0-BETA3.

**Comment by sksamuel** [comment]
beta3 is now released.
