### ISSUE TITLE
Remove AutoScan from KoinListener

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1246]
KoinListener requires parameters to be constructed

Our AutoScan tries to initialize the listener with no arguments, and then it gets a reflection error. This happens whenever `KoinListener` is added to any project

**Comment by simonenkoi** [comment]
Does it make sense to extend rule and ignore not only KoinListener but any class that doesn't have no args constructor? We can write warns, for example

**Comment by sksamuel** [comment]
Good idea

**Comment by Kerooker** [comment]
It could be part of our test suite, actually.

We already have classgraph to pickup the Autoscans, we could write a test to enforce that every `@AutoScan` class must have a no-arg constructor
