### ISSUE TITLE
Deprecate/remove regex arb that accepts a Regex

### ISSUE THREAD

**Issue by dump247** [kotest/kotest#1252]
[Arb.Companion.regex(Regex)](https://github.com/kotest/kotest/blob/master/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/regex.kt#L18) was very confusing for me initially. I assumed that it would accept any regex, but it only works with a more restricted pattern language from the [mifmif Generex](https://github.com/mifmif/Generex) library. It also drops the regex options (e.g. case insensitive).

I would also suggest renaming [Arb.Companion.regex(String)](https://github.com/kotest/kotest/blob/master/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/regex.kt#L7) to `pattern` so it is more differentiated from a regex.

**Comment by dump247** [comment]
I would be happy to make these changes. I created the issue to get some feedback first.

**Comment by sksamuel** [comment]
I don't think it would be as discoverable if it was called pattern but I'm ok with it being renamed.
