### ISSUE TITLE
Example of property-based testing does not compile in most recent version (3.4.2)

### ISSUE THREAD

**Issue by werner291** [kotest/kotest#1264]
In the main readme, this section of code won't compile with the latest version of the library:

```
class PropertyExample: StringSpec({
  "String size" {
    checkAll<String, String> { a, b ->
      (a + b) should haveLength(a.length + b.length)
    }
  }
})
```

But the version here does work (https://github.com/kotest/kotest/blob/master/doc/property_testing.md):

```
class PropertyExample: StringSpec() {
  init {

    "String size" {
      assertAll({ a: String, b: String ->
        (a + b).length shouldBe a.length + b.length
      })
    }

  }
}
```

**Comment by sksamuel** [comment]
That document is for 4.0 beta. There's a notice at the top of the main
readme.

**Comment by sksamuel** [comment]
Property test docs have now been updated.
