### ISSUE TITLE
Will there be support for Test Retry Gradle Plugin?

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#1265]
https://blog.gradle.org/gradle-flaky-test-retry-plugin

**Comment by sksamuel** [comment]
It should just work out of the box since it's compatible with junit5.

**Comment by jsalinaspolo** [comment]
The `org.gradle.test-retry` plugin has been broken from kotest `5.5.5` to `5.6.0` 

Would anyone be able to review the change that made it break with the JUnit5 Platform?
