### ISSUE TITLE
Path matchers should be implemented without a `toFile()` conversion

### ISSUE THREAD

**Issue by netvl** [kotest/kotest#1272]
At the moment, most of the matchers for `java.nio.file.Path` are implemented using matchers for `java.io.File`:
```kotlin
fun Path.shouldExist() = this.toFile() should exist()
```

This, unfortunately, makes these matchers completely unusable with any file system except the default one. For example, if a given `Path` is obtained from a `ZipFileSystem`, this matcher will fail with `UnsupportedOperationException`.

Ideally matchers for `Path` values should be implemented using native `Path` operations, for example, checking not `path.toFile().exists()` but `java.nio.file.Files.exists(path)`.

**Comment by sksamuel** [comment]
Good points. We'd welcome a PR!

**Comment by sksamuel** [comment]
Added in beta 3.
