### ISSUE TITLE
Allow multiple project configs

### ISSUE THREAD

**Issue by asm0dey** [kotest/kotest#1274]
Say I have suite of integration tests and I need to launch test container with postgres for them to work.

But I don't need it for unit tests.

Currently I can do it with parent class for integration tests and overriding "before project" there. 

But now `beforeProject` is deprecated. What is the correct way to implement it?

**Comment by sksamuel** [comment]
beforeProject exist in ProjectListener's which you can @Autoscan.
Also you can use tags to have some tests run and not othrs.

**Comment by asm0dey** [comment]
Well, I believe I need another thing:

Run all tests, but launch testcontiners only for ancestors of base class of integration tests.

Also I need different sets of test containers for different base classes

**Comment by sksamuel** [comment]
This test container thing you only want to launch once for a bunch of tests?

**Comment by asm0dey** [comment]
Yes. Say I have case class PostgresTests and base class MySqlTests, both inheriting BehaviourSpec. I need different containers for ancestors of these classes

**Comment by sksamuel** [comment]
Can you add a listener to the parent classes to do the setup and teardown?

**Comment by asm0dey** [comment]
What is the supposed way to do so? I can find beforeSpec, but not beforeAll.

**Comment by sksamuel** [comment]
Extend `ProjectListener` and add that to your parent spec(s).

**Comment by asm0dey** [comment]
Well, than it's the same as overriding `beforeProject` in parent class, isn't it?

**Comment by asm0dey** [comment]
BTW it's stated in documentation that there should be only one project listener

**Comment by sksamuel** [comment]
Yes it is the same. But it would do what you want?

**Comment by asm0dey** [comment]
If it works — than I think so. But it shouldn't work according to documentation.

**Comment by sksamuel** [comment]
I've improved the listener documentation. https://github.com/kotest/kotest/blob/master/doc/listeners.md

Does this make things clearer ? Or is there more to add (PR ?)

**Comment by asm0dey** [comment]
LGTM, thanks!
