### ISSUE TITLE
Add binary validator (to avoid methods loosing)

### ISSUE THREAD

**Issue by imanushin** [kotest/kotest#1275]
I found, that String Matchers (such as ```shouldContain```) are inaccessible for current moment at ```4.0.0-BETA2```. 

Suggestion: add [binary-compatibility-validator](https://github.com/Kotlin/binary-compatibility-validator) plugin into gradle build.

**Comment by sksamuel** [comment]
Good idea on the plugin.

What's wrong with shouldContain ?

**Comment by LeoColman** [comment]
It's likely that @imanushin needs to add the assertions manually

**Comment by imanushin** [comment]
@Kerooker , yes, I will try to add this validation into the ```kotest```.

In regarding to ```shouldContain``` - I added ```kotest``` ```4.0.0-BETA2``` as dependency. And IntelliJ Idea couldn't resolve imports for code from sample (please check below). Probably, ```shouldContain``` method was moved out of core scope. And there aren't such matchers [at the target package](https://github.com/kotest/kotest/tree/master/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/string).

Problematic code:
```
"substring".shouldContain("str")
```

**Comment by sksamuel** [comment]
Try adding assertions-core to your build.

**Comment by LeoColman** [comment]
ShouldContain is still on the Assertions module:
https://github.com/kotest/kotest/blob/fd127f0e0d3e382017175f7ee54a4996f4726c6e/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/string/matchers.kt#L139

**Comment by sksamuel** [comment]
Assertions-core

**Comment by imanushin** [comment]
I understand. The issue is with project configuration. The ```kotest-runner-junit5``` references [kotest-assertions-jvm](https://mvnrepository.com/artifact/io.kotest/kotest-assertions-jvm), not [kotest-assertions-**core**-jvm](https://mvnrepository.com/artifact/io.kotest/kotest-assertions-core-jvm).

So issue could be resolved by adding ```kotest-assertions-core-jvm``` dependency manually.

I think it is better to do these references inside the project.

**Comment by sksamuel** [comment]
That's deliberate. We don't want to bring the core dependency in, so that
people can use the kotest framework without necessarily getting the
assertions library.

**Comment by imanushin** [comment]
@sksamuel, yes, this reasonable. However, probably, we can add one more jar package with idea "latest junit all jvm assertions"? It shouldn't have any code, however it could be added as one dependency to cover 90% of cases.
