### ISSUE TITLE
Property tests should report exception of running shrunk input

### ISSUE THREAD

**Issue by themoritz** [kotest/kotest#1279]
During property testing, if an input fails, the `AssertionError` is being rendered as part of the test report. But if the input has successfully shrunk, the exception that failed the shrunk input is ignored.

Ideally the exception that the user sees in the final test report should be the one that the shrunk input failed with. It might also be ok to render both exceptions since also both inputs (original and shrunk) are rendered.

**Comment by jaymoid** [comment]
@themoritz Hi! What version did see this on? (The property based testing framework was re-written for 4.x)

I'm struggling to recreate the issue. If you could provide an example test case that demonstrates this I can look into it.

I've tried a basic property based test, which under failure states both the shrunk input and the original/first input which the property does not hold true for.
```
java.lang.AssertionError: Property failed after 6 attempts

	Arg 0: 2 (shrunk from 36050144)

Caused by AssertionFailedError: expected:<true> but was:<false>
```
where 2 was the shrunken value, 36050144 was the first failing value. If you could help point me in the right direction I'll take another look. Thanks! :)

**Comment by themoritz** [comment]
I have only tested this before the 4.x rewrite, so I can't tell for sure that this is still an issue. One clue that this is still an issue is that in this piece of code

https://github.com/kotest/kotest/blob/5029d98300c9f733ba2d16120c81e5426468249c/kotest-property/src/commonMain/kotlin/io/kotest/property/internal/shrink.kt#L67-L72

the `t: Throwable` is not reported back. So the report can only show the assertion error for the non-shrunk value.

This might help you get started and if I find a little bit more time I can construct a small example.

**Comment by themoritz** [comment]
Here's a small example that can be used to reproduce the issue:

```kotlin
class Shrink : StringSpec({
    "Shrink" {
        assertAll(Gen.Companion.choose(1, 10)) {
            it shouldBe 8
        }
    }
})
```

This prints something like the following:

```
java.lang.AssertionError: Property failed for
Arg 0: 1 (shrunk from 6)
after 1 attempts
Caused by: expected: 8 but was: 6
Expected :8 
Actual   :6
```

Even though the final Arg 0 is `1`, the exception is about the original value of `6`. In this example it's easy to see what's going on, but in more complicated tests this is an issue because I can't see the exception that was thrown for the shrunk value of `1`. Expected behavior would be `Caused by: expected: 8 but was: 1` (and optionally also show the original exception for the unshrunk value).

**Comment by sksamuel** [comment]
It should show both I think.

**Comment by jaymoid** [comment]
@themoritz I'd recommend upgrading to 4.x and seeing if this is an issue. 3.4.2 was the last 3.x release to Kotlintest, so going forwards we'll be focussing on Kotest 4.x issues. In my experiments in 4, you get all of the pre-shrunk and shrunk inputs, in addition to a seed, which allows you to repeat the test with the args which had failed your previous tests making them deterministic.

**Comment by sksamuel** [comment]
Do we get the pre shrunk exception and the post shrunk exception in
addition to the values. I think that is what the ticket is checking for.

**Comment by jaymoid** [comment]
Apologies, I'm with you now. Yes in 4.x we don't get the exception that failed with the shrunk input, only the shrunk input itself. 

It raises a property assertion error and specifies the first (non-shrunk) exception as the cause,  so I'm not sure how it would work if we had two exceptions to specify as there's only the slot for one cause. 

My only thought was if we had a `PropTestConfig` option to determine which exception is specified as the cause, allowing the user to choose from the Shrunk or First exception (given we have the seed now the user could run the test twice if they needed both).  I think the shrunk exception is discarded in `doStep` so would require a bit of wiring to bring it back from the shrinking phase but is possible. Are there some other (better?!) ways this could be achieved?
