### ISSUE TITLE
Robolectric extension with custom Application instance

### ISSUE THREAD

**Issue by xuhaibahmad** [kotest/kotest#1280]
Thanks for providing Robolectric support. I'm using the extension on `4.0.0-BETA2` and normal tests seem to run fine. However, I need to use the test implementation for `Application` class. 

The `@Config` annotation seems to have no effect and the extension's source does not contain any hint about Robolectric configurations.

**Comment by LeoColman** [comment]
I don't think we have that yet.

Do you want to work on this? If you don't I can add this to the Robolectric Extension!

**Comment by xuhaibahmad** [comment]
Oh, I would love to! However, I'll need to dive into the source first to make the sense of the codebase. I'll have a go over the weekend. Hope it's not urgent.

**Comment by xuhaibahmad** [comment]
So I started working on the PR today but ran into some other issues. My goal was to create a sample project and use it as a playground for the changes I make initially.

The sample project contains a very basic setup consisting of a `MainActivity` that calls a getter on custom `Application` instance and displays the value in a `TextView`. I planned on creating a test version of the `Application` class later to test the custom configs.

I first created a test with vanilla Robolectric which ran as expected. However, upon creating the same test with Kotest's Robolectric plugin, the test crashed with coroutine related exception:

```
java.lang.RuntimeException: Can't create handler inside thread Thread[pool-1-thread-1 @coroutine#3,5,main] that has not called Looper.prepare()
```

I think the spec contexts might need some tweaking to be flexible enough to be run on Android-based tests that needs to be run on the main thread. I'm kind of blocked here as I have not dived any deeper for possible solutions for it.

Here is the sample project I'm using:

https://github.com/xuhaibahmad/Kotest-Robolectric-Config


PS: Let me know if this needs an issue of its own.
