### ISSUE TITLE
timeout doesn't actually stop the test

### ISSUE THREAD

**Issue by glasser** [kotest/kotest#1283]
The current implementation of test timeouts makes the test's result be failure but doesn't actually proactively stop the test, so you can't use it to make your tests end in a reasonable amount of time in failure.

For example, this diff applied to `release/3.4` yields a failing test. (The embedded test here spins for a second.)

```
diff --git a/kotlintest-tests/kotlintest-tests-core/src/test/kotlin/com/sksamuel/kotlintest/TestCaseExecutorTest.kt b/kotlintest-tests/kotlintest-tests-core/src/test/kotlin/com/sksamuel/kotlintest/TestCaseExecutorTest.kt
index 51c67410..98f95459 100644
--- a/kotlintest-tests/kotlintest-tests-core/src/test/kotlin/com/sksamuel/kotlintest/TestCaseExecutorTest.kt
+++ b/kotlintest-tests/kotlintest-tests-core/src/test/kotlin/com/sksamuel/kotlintest/TestCaseExecutorTest.kt
@@ -8,6 +8,7 @@ import io.kotlintest.TestCase
 import io.kotlintest.TestCaseConfig
 import io.kotlintest.TestContext
 import io.kotlintest.TestStatus
+import io.kotlintest.matchers.numerics.shouldBeLessThan
 import io.kotlintest.milliseconds
 import io.kotlintest.runner.jvm.TestCaseExecutor
 import io.kotlintest.runner.jvm.TestEngineListener
@@ -258,12 +259,15 @@ class TestCaseExecutorTest : FunSpec() {
         override fun description(): Description = Description.spec("wibble")
       }
 
+      val executorStartTime = currentTimeMillis()
       executor.execute(testCase, context)
+      val executorTotalTimeMillis = currentTimeMillis() - executorStartTime
 
       then(listener).should().exitTestCase(
           argThat { description == Description.spec("wibble") },
           argThat { status == TestStatus.Error && this.error?.message == "Execution of test took longer than 125ms" }
       )
+      executorTotalTimeMillis.shouldBeLessThan(500)
     }
 
     test("test with infinite loop but invocations = 1 should complete with TestStatus.Failure") {
```

The test is commented out on master and the code seems to be pretty rewritten, so maybe this is fixed in 4.0?

**Comment by sksamuel** [comment]
Are you looking for a test to be interrupted after timeout? If so beta3 will do that once it's released. Of course the user code has to be cooperative.

**Comment by glasser** [comment]
As an example, I had a test of a class that manages a background coroutine. I passed the class the TestContext to use as its CoroutineScope. Part of what I wanted to test was that the class cleans up its coro properly, and kotest does enforce that, since the test won't pass if there are outstanding coros in the TestContext scope! But I wanted to make sure the test would fail within a few seconds if it was to fail (eg if it didn't finish the background coro properly), and I expected the timeout to do this... And it didn't. The background coro was in delay() so that seems cooperative enough. 

You're saying 4.0 beta3 will fix this? How much do you recommend the 4.0 betas for serious use?

**Comment by sksamuel** [comment]
Ok so I've expanded the timeout testsuite a bit. I think the test case you're looking for specifically is this: https://github.com/kotest/kotest/blob/c1c180071eb66212890f3f8906770bac6f3c3979/kotest-tests/kotest-tests-timeout/src/jvmTest/kotlin/com/sksamuel/kotest/timeout/TimeoutTest.kt#L27-L29

It tests that any launched coroutines nested in the coroutine of the test lambda is cancelled when the test timeout hits.

As for 4.0, I and several others are using 4.0.0-BETA2 in production. BETA3 will be released today pending feedback on #1291. I'd say the quality of the release is better than 3.4.2 currently. The only reason it's not final is because I wanted to see how some of the new features worked in the wild before locking down their syntax / names / functions. So in other words, you should be ok with beta3 but you might have to rejig things for the final.

**Comment by sksamuel** [comment]
BETA3 has been released.

**Comment by glasser** [comment]
I'm using 4.0.1 now. The following test:

```
		"test timeout".config(timeout = 1.toDuration(SECONDS)) {
			launch {
				delay(10.toDuration(SECONDS))
			}
		}
```

succeeds in 10 seconds rather than failing in 1 second, which seems wrong to me.

**Comment by sksamuel** [comment]
Thanks for the further investigation.
coroutines launched without their own nested scope was the case we weren't testing for, but this is now fixed and will be included in 4.0.2

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/pull/1345

**Comment by sksamuel** [comment]
4.0.2 has been released with this fix.

**Comment by glasser** [comment]
One final question — is timeout supposed to be applied per-"invocation" or overall?

The previous code sorta did both — it had an "overall" timeout around the invocations and also ran each code within the timeout. Now it just applies it overall.

I think it would make sense to only apply to a single invocation — if I'm trying to track down a rare bug I might want to set invocations=10000000 and walk away for an hour, and I feel like I should be able to do that without having to tweak the project/test timeout?  Seems like that would be a major advantage of using invocations instead of just `repeat(n) {}`.  In any case it would be nice if this was explicitly documented one way or the other.

**Comment by sksamuel** [comment]
I agree that the timeout should apply per invocation. We can add another config value to support that.

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/issues/1442
