### ISSUE TITLE
shouldContainInOrder problems with duplicates

### ISSUE THREAD

**Issue by ClaasJG** [kotest/kotest#1285]
Hi,

i am using ' 4.0.0-BETA2 '.

Current behavior:
`"a" should containInOrder("a", "a")` matches but should not.
`"aba" should containInOrder("a", "b", "a")` does not match but should.
`"a" should containInOrder("b")` does match but should not.

Proposed fix:
Rewrite of [kotlin/io/kotest/matchers/string/matchers.kt#L131](https://github.com/kotest/kotest/blob/525df298325779833c1e80919dc43afc963dad04/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/string/matchers.kt#L131)

I am not familiar with the Codebase, but supposed I understood the intended function of `containInOrder` correctly, I am willing to submit a pull request.

And again thanks for kotest

-Claas

**Comment by sksamuel** [comment]
Good find thanks. A PR would be excellent.
