### ISSUE TITLE
Android: Test events were not received

### ISSUE THREAD

**Issue by Cotel** [kotest/kotest#1301]
Hi, I've added latest Kotest to my android project and, when I try to run the gradle task for unit tests, it always says `Test events were not received` or it gets stuck and never finish the task. Currently there is only one test using `StringSpec` and several tests using JUnit4 annotations. 

We are using Gradle 3.6.1 and Kotest 4.0.0-BETA3.

**Comment by sksamuel** [comment]
You would need gradle 6+

**Comment by sksamuel** [comment]
And Kotest 4.0 final is out.

**Comment by Cotel** [comment]
So there is no way to make Kotest work on Android? I think we can't use higher versions for the wrapper as we are limited by the android plugin 🤔 

To be more specific with versions we are using:
* `com.android.tools.build:gradle:3.6.1` - Android Gradle Plugin
* `https\://services.gradle.org/distributions/gradle-5.6.4-all.zip` - Gradle Wrapper

> And Kotest 4.0 final is out.

Congratulations 🎉

**Comment by pawegio** [comment]
with Gradle 6.2.2 doesn't work as well
