### ISSUE TITLE
Annotation tests style function visibility

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1303]
I'm from TestNG\JUnit 5 and I will compare kotest with them. It’s logical that I prefer and am used to using annotations in tests.
Is there reason why only public fun tests are works?
JUnit/testNG support protected/private/public function [link](https://stackoverflow.com/a/55230350/6315556) 
Or you haven't think about it yet?

I've just faced with it and found solution if you don't mind
```kotlin
 private fun KFunction<*>.deriveTestCase(config: TestCaseConfig): TestCase {
      isAccessible = true
      ..............
}
```

**Comment by sksamuel** [comment]
If we can make private/protected functions work easily, I'll happily add it for 4.0.

**Comment by sksamuel** [comment]
Private and protected now supported in 4.0.
