### ISSUE TITLE
Kotest couldn't run tests parallel

### ISSUE THREAD

**Issue by imanushin** [kotest/kotest#1305]
Probably this issue is related to #1257 . Current issue is with ```beta-3``` jvm version.

**Steps to reproduce:**
1. Create project with ~30 subprojects
2. Add tests, etc.
3. Run ```gradlew build --parallel```

**Expected result:**
Tests from different projects are executed in parallel
Tests from the same project are executed simultaneously

**Actual result:**
Looks like, only one test could be executed at the same moment. E.g. event if tests are in different projects, they couldn't be executed in parallel.

**Comment by sksamuel** [comment]
Does --parallel run tests in parallel or run modules in parallel ?

**Comment by imanushin** [comment]
```--parallel``` allows running tasks from different gradle modules in parallel. E.g. all tasks are executed sequentially inside the same module.

I checked - this issue is related to ```4.0.0``` version too (not beta), however there aren't such issues in previous versions.

**Comment by sksamuel** [comment]
It might be the case that gradle uses the same test listener for all the modules in parallel mode. We synchronize reporting so gradle doesn't get confused.
How do you know it's not running the tests in parallel? Are you going by test output or by total time executed?

**Comment by imanushin** [comment]
Hmm, however the same Gradle version worked perfectly with previous version of kotest (e.g. 3.*).

I found this behavior by observing Gradle output: I noticed, then two test task could be executed in parallel, however test counting is never incrementing in parallel. In contrast with this, previously two parallel test tasks could increment tests in parallel.

**Comment by imanushin** [comment]
I coulnd't find correct way of reproducing.
