### ISSUE TITLE
Support config per test in AnnotationSpec

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1307]
For other styles semantic allows you configure each test (enabled, invocations, threads etc) except `AnnotationSpec`. Kotest has only `Ignore` now. 
(as for me I will do it via TestNG's @Test(enabled = false)) or JUnit's	@Disabled(value = "Reason why this test is disabled now!")
I prefer configure test via annotation like TestNG  @Test or create new annotation @Config.
but annotation does't  allow use instants of classes (Duration, Tag) and It will be cut version of Config
```kotlin
   @ExperimentalTime
   annotation class Config(
      val enabled: Boolean = true,
      val invocations: Int = 1,
      val threads: Int = 1,
      val timeout: Long = -1,
      val timeoutUnit: DurationUnit = TimeUnit.SECONDS, //instead of Duration
      //val tags: Array<Tag> = [],
      val listeners: Array<KClass<TestListener>> = [],
      val extensions: Array<KClass<TestCaseExtension>> = []
      //val enabledIf: EnabledIf = { true }
   )
```

**Comment by sksamuel** [comment]
This could be added to AnnotationSpec.

**Comment by crazyk2** [comment]
It's not actual for me because I moved to FunSpec. But maybe for someone
