### ISSUE TITLE
New map error message doesn't include stack trace

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1309]
Eg

java.lang.AssertionError: Expected
{
  "shade" = "VICE"
}
to be equal to
{
  "shade" = "Sheer Streak"
}
Values differed at keys shade

But doesn't include the source point this happens.

@ashishkujoy

**Comment by ashishkujoy** [comment]
@sksamuel 
I have tried out that i can see the stacktrace as well.
Below is screenshot for failure of following test
```kotlin
"map should be map" {
            val a = mapOf("ashish" to "kumar")
            val b = mapOf("ashish" to "joy")

            a shouldBe b
        }
```
<img width="1675" alt="Screenshot 2020-03-26 16 33 42" src="https://user-images.githubusercontent.com/34642693/77640082-c97a8100-6f7f-11ea-9be8-75e2ec5c8be3.png">

**Comment by ashishkujoy** [comment]
This is using kotest 4.0.1
kotlin 1.3.70
gradle-6.2.2
java version "1.8.0_241"
on mac os 10x
