### ISSUE TITLE
Internal test classes not picked up

### ISSUE THREAD

**Issue by GuidoDechamps** [kotest/kotest#1314]
Moving from version 3.4.2 to 4.0.1. our test that were internal no longer get executed. Making the test class "public" fixes this. Is this intentional / by design?

**Comment by sksamuel** [comment]
By design, but we can add a flag to enable internal (as we do this for tests). Would that work ?

**Comment by sksamuel** [comment]
4.0.2 has been released which picks up internal by default.

**Comment by GuidoDechamps** [comment]
Ok. Thanks. I like my code to not public if not needed. But I also like my tests to be executed ;-)
