### ISSUE TITLE
Duplicate class AliasesKt 

### ISSUE THREAD

**Issue by YuriDenison** [kotest/kotest#1329]
When trying to setup an Android Project with Kotest, the following error appears:

> java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class io.kotlintest.AliasesKt found in modules kotest-assertions-jvm-4.0.1.jar (io.kotest:kotest-assertions-jvm:4.0.1) and kotest-core-jvm-4.0.1.jar (io.kotest:kotest-core-jvm:4.0.1)

**Comment by LeoColman** [comment]
This was fixed on #1319. 

Pending release

**Comment by YuriDenison** [comment]
Thanks. Could you please publish 4.0.2? 
We are blocked in our Android project because of these errors and we can't use snapshot versions.

**Comment by sksamuel** [comment]
4.0.2 will go out tomorrow night.
