### ISSUE TITLE
Stacktrace is lost when using forAll and row

### ISSUE THREAD

**Issue by emiliano-tebes** [kotest/kotest#1336]
if you write a test using forAll and row to provide data, and an exception is thrown in tested methods (or any of the inner consumed methods), stacktrace is lost. If not using forAll and row, stacktrace is shown. This makes it difficult to trace errors in your code. Original stacktrace should always be shown.

Steps to reproduce:

1. write a test using forAll and add one or more row
2. invoke any method that throws an exception
3. watch the stacktrace. original stacktrace is lost, and replaced.

I provided an example in this repo, so that you can easily see the difference of behaviour: 
https://github.com/emiliano-tebes/kotest-stacktrace

regards,
Emiliano

**Comment by sksamuel** [comment]
#1347

**Comment by sksamuel** [comment]
Obviously if forAll fails for more than one error we can't show all stacktraces, but we should show the first. This pr does that.

**Comment by emiliano-tebes** [comment]
Excellent! Thanks!

**Comment by sksamuel** [comment]
4.0.2 has been released with this fix.
