### ISSUE TITLE
allow_internal JUnit5 configuration is an undocumented breaking change for 4.x

### ISSUE THREAD

**Issue by jonbarksdale** [kotest/kotest#1337]
I just wasted a few hours trying to migrate to kotest 4.x, and this was a cause of grief.  

Basically, if your tests are `internal` visibility, they cease to work when moving from 3.x to 4.x, and this is not noted anywhere in the documentation, as least that I could find.  I ended up going through all of the JUnit integration code to find it.

Expected: 
1. Should be a documented configuration, especially if intended.  It should absolutely be in the migration guide, and also deserves a section in the main reference documentation
2. Better behavior for your users would have been to have the default value be `true`.

Anyway, now I have to go figure out how to set for my test configuration.

**Comment by sksamuel** [comment]
We're doing to do a 4.0.2 release next day or two which will address this.

**Comment by sksamuel** [comment]
4.0.2 has been released which picks up internal by default.
