### ISSUE TITLE
Tag: Code and docs out of sync

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#1346]
https://github.com/kotest/kotest/blob/c513c8328a371830e838b5ac59aa937d2c44752f/kotest-core/src/commonMain/kotlin/io/kotest/core/Tag.kt#L18-L21

The code and property / class docs are out of sync WRT the name being used for the tag. Should it be the FQN or the simple name?

Note that in Kotlintest it was the simple name, but now it's the FQN, which is a breaking change that should be mentioned in the release notes / a migration guide, if it should stay like this.

**Comment by sksamuel** [comment]
Was always the simple name yes, so this is a bug.

**Comment by sksamuel** [comment]
Fixed in master. 4.0.2 is due tomorrow, will be included in that.

**Comment by sschuberth** [comment]
Thanks for the super fast fix!

**Comment by sksamuel** [comment]
4.0.2 has been released.
