### ISSUE TITLE
Integration with Testcontainers

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#1353]
[Testcontainers](https://www.testcontainers.org/) is a tool that can dynamically spin up docker containers to be used in tests.
This can be useful for spinning up database containers in integration tests for example.
Kotest integration with this tool would be nice.

Thanks.

**Comment by sksamuel** [comment]
@ashishkujoy has opened a PR at testcontainers to add support there alongside spock / junit5.
You could vote on that issue., https://github.com/testcontainers/testcontainers-java/pull/2533

**Comment by sksamuel** [comment]
We've now merged this into kotest itself due to testcontainers having higher priorities.

**Comment by sksamuel** [comment]
Will be included in 4.1

**Comment by dkowis** [comment]
Forgive me, is there documentation for how to actually use this? I found the classes in kotest-extension-testcontainers, but I'm not sure how to actually use it in one of my specs.

Thanks!

EDIT: just found it: https://github.com/kotest/kotest/blob/master/doc/extensions.md#testcontainers
