### ISSUE TITLE
Please provide full example projects, the full javadoc and a guide to the dependencies.

### ISSUE THREAD

**Issue by pascaldornfeld** [kotest/kotest#1358]
I tried your framework and it looks very promising. Data and property is nice and I love how you can use different forms for writing tests. Unfortunately for using it efficiently the structure of the project is not well documented.

I wanted to try it for property testing. I started over with importing _kotest-runner-junit5-jvm_ and _kotest-assertions-core-jvm_. I noticed assertAll was deprecated. It said "use the new classes in 4.0". After checking the documentation I imported "kotest-property-jvm". That's where I stopped. I couldn't find more about how to use the "new classes".

Next I wanted to use _shouldHaveLength_ matcher. There was only shoudl, shouldHave, shouldNotHave, shouldBe and shouldNotBe available. Went to maven repository and looked all the possible dependencies. No clue what is missing.

Can you please include:

- Full example projects, that can be tried without further configuration, including all needed gradle configs.
- A auto-generated javadoc just for convenience and habit.
- A documentation page about all the dependencies that are out there? There are 5 pages of them and most are available in default and jvm form. https://mvnrepository.com/artifact/io.kotest

**Comment by sksamuel** [comment]
The usage guidelines on the front page describe which dependencies you need:
https://github.com/kotest/kotest#use

Then for property testing you can read:
https://github.com/kotest/kotest/blob/master/doc/property_testing.md

**Comment by pascaldornfeld** [comment]
Somehow I managed to find the matchers. I found out that the new "assertAll" is "checkAll".
In the document both methods are used.

My android project is running fine now. I created an idea project too. There I got the same issue as #252 and #1109. #1109 had no answer. #252 said, that we should switch the runner to gradle test runner. In current idea the settings page looks different so this doesn't work anymore.

**Comment by sksamuel** [comment]
I'd like to improve the documentation in areas where it's required but in terms of which dependencies to add, it's right there on the main readme and the reference.doc files. You just need to copy and paste it. I don't know how much clearer it could be.

assertAll vs checkAll  are explained in the property testing doc I linked you to, that's linked from the main readme.

In particular, 

> If we don't want to provide a property that returns a boolean, Kotest allows for checkAll where you can simply execute assertions against the inputs. For example:

**Comment by adamcameron** [comment]
Hi
The original request included "A auto-generated javadoc just for convenience and habit", but follow-up comments focused on other elements of the request.

Try as I might, I can't find the JavaDocs for this project..?
