### ISSUE TITLE
Support tests inside commonTest

### ISSUE THREAD

**Issue by avently** [kotest/kotest#1359]
Hello, Stephen. Is it possible to use commonTest directory from MPP project for tests with Kotest? Or is it not supported yet? For now I can import some things like `shouldBeExactly` but not others like `StringSpec`. Or maybe I just setup wrong artifacts in build.gradle

**Comment by sksamuel** [comment]
You would probably always need to execute the tests against at least one target. The reason is, common is like a virtual state - it's just kotlin code and it needs to be compiled into _something_ in order for it to be tested.

**Comment by avently** [comment]
It's true but I can write and execute test code in commonTest with `kotlin.test`. If it can work why kotest can't?

**Comment by sksamuel** [comment]
Well kotlin.test has special support from the compiler and the IDE. But it must be running your tests in either the JVM or a JS runner. I'll look into it.

**Comment by avently** [comment]
@sksamuel  I probably imported wrong artifact before because I saw some classes from kotest in commonTest but not other classes. 
Now I did this:

1.added
```
test {
    useJUnitPlatform()
}
```
2. inserted into dependencies:
```
kotlin {
    targets {
        fromPreset(presets.jvm, 'jvm')
    }
    sourceSets {
commonTest {
            dependencies {'
                implementation 'io.kotest:kotest-core:4.0.2'
            }
        }

jvmTest {
            dependencies {
                implementation 'io.kotest:kotest-core-jvm:4.0.2'
                implementation 'io.kotest:kotest-runner-junit5:4.0.2'
                implementation 'io.kotest:kotest-assertions-core-jvm:4.0.2'
            }
        }
    }
}
```

I can import kotest code inside commonTest finally. But I receive `No tests found for given includes`. Trying to fix it.

**Comment by sksamuel** [comment]
Try 4.0.6 as well just so you're on the latest.

**Comment by avently** [comment]
Whenever I click on a test class decalaration in IDEA with right mouse button and selecting `Run SsnTest` I'm getting `No tests found for given includes`. Could you please point me into the right direction?
Here is a quick sample project I created:
[KotestSample.zip](https://github.com/kotest/kotest/files/4742643/KotestSample.zip)

**Comment by sksamuel** [comment]
You can't put tests in commonTest with kotest.

**Comment by avently** [comment]
Is it impossible? So how other libs can work then? (I know just one lib and it's kotlin.test)

**Comment by sksamuel** [comment]
kotlin.test has special support from the compiler and the IDE. It's easier to make it work when the author of kotlin, kotlin.test and intellij are all the same company.

As the ecosystem matures I assume they'll expose ways for third party libraries to plugin.

**Comment by avently** [comment]
Ah, ok. Then the issue can be closed. Thank you for your time. Please, reopen it if there will be a way to implement the feature in the future.

**Comment by sksamuel** [comment]
Once we can support it, we will.
