### ISSUE TITLE
Parallel execution test cases in Spec

### ISSUE THREAD

**Issue by SergKhram** [kotest/kotest#1362]
I think this is very good feature to give an opportunity to configurate and execute cases inside spec parallel. For example:
We have Test Spec "Lalala" where two cases - "First test case" {body}  "Second test case" {body}
I want to execute it parallel(or not - for it we need some config for spec)

In 3.4.2 i make it with it:
in class SingleInstanceSpecRunner i rewrite method execute

`override fun execute(spec: Spec, topLevelTests: TopLevelTests): Map<TestCase, TestResult> {
       var listOfCases: List<Deferred<Any>> = ArrayList()

        runBlocking {
            interceptSpec(spec) {
                topLevelTests.tests.forEach { topLevelTest ->
                    // each spec is allocated it's own thread so we can block here safely
                    // allowing us to enter the coroutine world
                    val async = this.async {
                        executor.execute(
                            topLevelTest.testCase,
                            Context(topLevelTest.testCase.description, this.coroutineContext)
                        ) { result -> results[topLevelTest.testCase] = result }
                    }
                    listOfCases = listOfCases + async
                }
                listOfCases.awaitAll()
            }
        }
        return results
    }`

And configure executor before it with config with number of threads (automatic or manual), that i need

Can you make something like that for 4.0 version ? I think it is useful

**Comment by crazyk2** [comment]
@sksamuel I vote for this feature and I thought it already works in this way.
I could parallelize tests in spec (and did it for myself already) but I have several question.
I did it for  `IsolationMode.SingleInstance` easily, but only for `rootTests`. It means that each test and each context with own tests (batch of tests) run parallel but all tests in own context (batch) run consistently.
And how this feature related with this #1369 
Common approach of my solution work for  `IsolationMode.InstancePerTest` and `IsolationMode.InstancePerLeaf` but i don't understand architecture\logic of `InstancePerLeafSpecRunner`.
For example 
```
// the queue contains tests discovered to run next. We always run the tests with the "furthest" path first.
```
Why in this order? What difference?

**Comment by sksamuel** [comment]
We could add parallelization of tests inside a spec, but it would only happen for root tests and only for single instance isolation mode.

**Comment by SergKhram** [comment]
> We could add parallelization of tests inside a spec, but it would only happen for root tests and only for single instance isolation mode.

It would be awesome
