### ISSUE TITLE
Array.shouldContainExactly wraps expected array

### ISSUE THREAD

**Issue by thebrightspark** [kotest/kotest#1364]
I am trying to assert that an `Array<String>` contains exact values, for which I am using `shouldContainExactly`. Here's a basic example:
```kotlin
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.collections.shouldContainExactly

class ArrayContainsTest : StringSpec({
    "array should contain exactly" {
        val array1 = arrayOf("one", "two", "three")
        val array2 = arrayOf("one", "two", "three")
        array1 shouldContainExactly array2
    }
})
```

The above example fails, where I'd expect it to pass. Here's the error logged:
```
java.lang.AssertionError: Collection should be exactly [["one", "two", "three"]] but was ["one", "two", "three"]
```
Is this a bug or is this expected behaviour and there's something different I should be doing?

I did check the equivalent from AssertJ to see how it's used there (as https://github.com/kotest/kotest/pull/360 mentions), and it appears as though `shouldContainExactly` should work as per my example above:
https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/ListAssert.html#containsExactly-ELEMENT...-

For now I'll get around it using a more manual approach:
```kotlin
import io.kotest.assertions.assertSoftly
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class ArrayContainsTest : StringSpec({
    "array should contain exactly" {
        val array1 = arrayOf("one", "two", "three")
        val array2 = arrayOf("one", "two", "three")
        assertSoftly {
            array1.forEachIndexed { index, s ->
                s.shouldBe(array2[index])
            }
        }
    }
})
```

**Comment by thebrightspark** [comment]
Ah, I've just noticed the issue :)

This function:
```kotlin
infix fun <T> Array<T>.shouldContainExactly(expected: Array<T>) = asList().shouldContainExactly(expected)
```
It's passing the `expected` array into a `vararg` param for `shouldContainExactly` - this one:
```kotlin
fun <T, C : Collection<T>> C?.shouldContainExactly(vararg expected: T) = this should containExactly(*expected)
```
So it's automatically getting wrapped into another array.

**Comment by sksamuel** [comment]
Nice spot. Do you want to prepare a quick PR ?

**Comment by thebrightspark** [comment]
Yep was just trying to prepare that now!

**Comment by ashishkujoy** [comment]
Closing this, as it is fixed via [PR](https://github.com/kotest/kotest/pull/1367)
