### ISSUE TITLE
Missing pom informations in Pitest Maven plugin

### ISSUE THREAD

**Issue by vhuc** [kotest/kotest#1365]
Hello

My problem is the same as the one described in error  #1115

`[ERROR] 1) Error injecting constructor, org.pitest.util.PitError: No implementation title in manifest of plugin jar for class io.kotest.plugin.pitest.KotestPluginFactory in file:/home/xxxxx/.m2/repository/io/kotest/kotest-plugins-pitest-jvm/4.0.2/kotest-plugins-pitest-jvm-4.0.2.jar`

The fix related to that issue didn't make a difference. I'm using Kotest 4.0.2.
Is it possible to check if there is something else missing?

**Comment by aalaura** [comment]
Is there any way we can reopen this issue? I am having the same issue trying to use the kotest-plugins-pitest maven plugin with kotest. It looks like there is already a fix - https://github.com/kotest/kotest/commit/4629622464595a59ea61be038963c02505b6f06c. Thanks
