### ISSUE TITLE
ShouldSpec does not isolate tests prefixed with f: if not in top level scope

### ISSUE THREAD

**Issue by daenius** [kotest/kotest#1371]
Consider the following test code

```
init {
    “Top level test scope” {
        should(“Test 1”) {
            // Test code
        }
        should(“f:Test 2“) {
            // Test code too
        }
    }
}
```

The `f:` in front of `Test 2` should isolate that test and only run that particular test.
It currently runs both tests

**Comment by sksamuel** [comment]
Focus mode only works at the "Top level" because nested tests are not
discovered until later in the test lifecycle.

https://github.com/kotest/kotest/blob/master/doc/conditional_evaluation.md
