### ISSUE TITLE
Non-deterministic function eventually() does not retry assertion until time out

### ISSUE THREAD

**Issue by daenius** [kotest/kotest#1372]
Suppose I have `someObject` that updates a value periodically and I would like to test that after T amount of time, calling `getValue()` on `someObject` should return an expected value. I have the following test code:

```
eventually(50.milliseconds) {
    someObject.getValue() shouldBe expectedValue
}
```
That test would still fail immediately because assertion failures are not ignored by eventually() and the code therefore does not get retried until time out.

I currently use the following workaround to force eventually() to retry:

```
eventually(50.milliseconds) {
    if (someObject.getValue() != expectedValue) {
        throw IllegalStateException(“Value not updated yet, keep waiting")
    }
    someObject.getValue() shouldBe expectedValue
}
```

**Comment by sksamuel** [comment]
Assertion failures should be ignored, it's the other way around. If a
normal exception is thrown then it would fail.
Let me try to recreate.

**Comment by daenius** [comment]
Thanks for looking at this so quickly!

If it helps, here's more of what my setup looks like with the workaround:

```
internal class TestClass : ShouldSpec() {
    init {
        "Top Level Scope 1" {
            "Scope 1 Subscope"{
                should("Test 1") {
                    // Test Code
                }
                should("Test 2") {
                    // More Test Code
                    eventually(50.milliseconds) {
                        if (someObject.getValue() != expectedValue) {
                            throw IllegalStateException(“Value not updated yet, keep waiting")
                        }
                        someObject.getValue() shouldBe expectedValue
                    }
                }
            }
        }
    }
}
```

Ideally I'd want to do this

```
internal class TestClass : ShouldSpec() {
    init {
        "Top Level Scope 1" {
            "Scope 1 Subscope"{
                should("Test 1") {
                    // Test Code
                }
                should("Test 2") {
                    // More Test Code
                    eventually(50.milliseconds) {
                        someObject.getValue() shouldBe expectedValue
                    }
                }
            }
        }
    }
}
```

**Comment by sksamuel** [comment]
You're on 4.0.2 just to check

**Comment by daenius** [comment]
Correct

**Comment by ashishkujoy** [comment]
@daenius I have tried writing the test as you have mentioned and for me the test is working fine(i-e ignoring the assertion errors). 
Please have look at [my test](https://github.com/ashishkujoy/kotest-playground/blob/master/src/test/kotlin/org/playground/AnotherEventualTest.kt)

**Comment by daenius** [comment]
Thanks for all the help!

I've discovered a build problem on my end that caused the tests to be built and run using an old version. Fixed the problem and now `eventually()` works exactly as expected.

Sorry for the false alarm!
