### ISSUE TITLE
io.kotest:kotest-runner-junit5 artifact empty?

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [kotest/kotest#1377]
I've been trying to use v 4.0.2 in an Android project
```   
    def koTestVersion = "4.0.2"
    testImplementation "io.kotest:kotest-runner-junit5:$koTestVersion"
    testImplementation "io.kotest:kotest-assertions-core-jvm:$koTestVersion"
```
Gradle syncs ok, no errors however the dependency isn't in my external libraries and no Kotest classes can be used. 

It looks like the artifacts exists: 
- https://repo1.maven.org/maven2/io/kotest/kotest-runner-junit5/4.0.2/
- https://repo1.maven.org/maven2/io/kotest/kotest-assertions-core-jvm/4.0.2/

However the kotest-runner-junit5 doesn't seem to have a jar, which would explain why its not appearing. 

As a side note, the `-jvm` suffixed version looks ok and i can import this: https://repo1.maven.org/maven2/io/kotest/kotest-runner-junit5-jvm/4.0.2/

However the setup instructions suggest using the non -jvm version for Android projects. 

Is this just a simple renaming and the docs need updating or is there a difference between the -jvm and none -jvm suffixed versions?

**Comment by daividssilverio** [comment]
Oh... that explains why our tests weren't being found 🤔here https://github.com/toggl/android/pull/154
Adding the `-jvm` suffixed dependency runner makes the tests discoverable.    
```
testImplementation 'io.kotest:kotest-runner-junit5-jvm:4.0.2'
```

**Comment by sksamuel** [comment]
You need to use the -jvm version yes. Where do the docs say otherwise, I'll correct them.

**Comment by OliverCulleyDeLange** [comment]
It's just in the main readme :
```
Android Project (Groovy)

android.testOptions {
    unitTests.all {
        useJUnitPlatform()
    }
}

dependencies {
    testImplementation 'io.kotest:kotest-runner-junit5:<version>' //
for kotest framework
    testImplementation
'io.kotest:kotest-assertions-core-jvm:<version>' // for kotest core
jvm assertions
}

```

**Comment by sksamuel** [comment]
Thank you, the others were correct and this one was missed!
Corrected now.
