### ISSUE TITLE
Test results are wrong

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [kotest/kotest#1378]
I was changing the test to fail, then to succeed, then to fail again etc, and i noticed that the first time you run the test after making the changes, the result would be as if you didn't make the changes. 

For example:
```
class PathCaptureSpec : FreeSpec() {
    init {
        "Test something"{
            "a" shouldBe "a"
        }
    }
}
```

Run 1: Success.
Change the assertion so it will fail.
Run 2: Still success.
Run 3: Fails as it should. 

KoTest 4.0.2, gradle 6.3 (although same happened on 5.6.4)

**Comment by sksamuel** [comment]
Do you have gradle cache enabled ?

**Comment by OliverCulleyDeLange** [comment]
Not that i'm aware of, the [default](https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable) seems to be 'off' and i haven't explicitly turned it on anywhere

**Comment by sksamuel** [comment]
And if you do a clean first?
I've seen similar things myself where gradle thinks the code hasn't changed
and doesn't rerun the test.
Try putting an exception in the middle of the test.

**Comment by OliverCulleyDeLange** [comment]
It fails straight away if i clean before i re-run

**Comment by sksamuel** [comment]
So sounds like that scenario wher gradle is caching or remembering which
modules have changed and it doesn't work properly.

**Comment by OliverCulleyDeLange** [comment]
Indeed, however i just tested with JUnit 5 and that seems to pick up the changes to the test straight away

**Comment by sksamuel** [comment]
That is odd. Kotest isn't doing anything clever with sources or anything
like that. Gradle just invokes the Discovery class which finds classes
subclassing Spec.

**Comment by OliverCulleyDeLange** [comment]
Well after some further testing, this seems to have gone away. I swapped my JDK to jdk8 from 11, and restarted Android Studio, and one of those things did something. I put my JDK back and its still fine so i'm a bit lost for conclusion. Feel free to close under 'users environment is broken' :)

**Comment by sksamuel** [comment]
Glad its working!
