### ISSUE TITLE
Add Line Breaks and Indents in the Failure Messages of Collection Matchers

### ISSUE THREAD

**Issue by phauer** [kotest/kotest#1380]
Hi,

first of all, I really like Kotest's matchers and consider to move from AssertJ to them. 

But I noticed that AssertJ adds useful line breaks after each element in the failure message of the collection matches. Here is an example:

AssertJ:

```kotlin
assertThat(actualDesigns).containsExactly(
    Design(id = 1, userId = 9, name = "Cat", dateCreated = Instant.ofEpochSecond(1518278198)),
    Design(id = 2, userId = 4, name = "Dogggg", dateCreated = Instant.ofEpochSecond(1518279000))
)
```
 
AssertJ's message:

```
java.lang.AssertionError:
Expecting:
  <[Design(id=1, userId=9, name=Cat, dateCreated=2018-02-10T15:56:38Z),
    Design(id=2, userId=4, name=Dog, dateCreated=2018-02-10T16:10:00Z)]>
to contain exactly (and in same order):
  <[Design(id=1, userId=9, name=Cat, dateCreated=2018-02-10T15:56:38Z),
    Design(id=2, userId=4, name=Dogggg, dateCreated=2018-02-10T16:10:00Z)]>
but some elements were not found:
  <[Design(id=2, userId=4, name=Dogggg, dateCreated=2018-02-10T16:10:00Z)]>
and others were not expected:
  <[Design(id=2, userId=4, name=Dog, dateCreated=2018-02-10T16:10:00Z)]>
```

Kotest 4.0.2:

```kotlin
actualDesigns.shouldContainExactly(
    Design(id = 1, userId = 9, name = "Cat", dateCreated = Instant.ofEpochSecond(1518278198)),
    Design(id = 2, userId = 4, name = "Dogggg", dateCreated = Instant.ofEpochSecond(1518279000))
)
```

Kotest's message:

```
java.lang.AssertionError: Collection should be exactly [Design(id=1, userId=9, name=Cat, dateCreated=2018-02-10T15:56:38Z), Design(id=2, userId=4, name=Dogggg, dateCreated=2018-02-10T16:10:00Z)] but was [Design(id=1, userId=9, name=Cat, dateCreated=2018-02-10T15:56:38Z), Design(id=2, userId=4, name=Dog, dateCreated=2018-02-10T16:10:00Z)]
```

One the one hand, AssertJ outputs more details (like the missing elements or elements that were not expected). On the other hand, AssertJ adds line breaks and indents which improves the readability. I believe that improving at least the last point would have a good effort-benefit ratio.

Kind Regards,
Philipp

**Comment by sksamuel** [comment]
Agreed good idea.

**Comment by sksamuel** [comment]
As part of the 4.0.3 release, `col.shouldContainExactly(col2)` now does exactly this:

```kotlin
Expecting: [
  Blonde(a=woo, b=true, c=97821, t=1970-08-04 01:19:55.621)
] but was: [
  Blonde(a=foo, b=true, c=23423, t=1970-05-23 07:06:31.293),
  Blonde(a=hoo, b=true, c=96915, t=1970-05-23 15:43:11.293)
]
Some elements were missing: [
  Blonde(a=woo, b=true, c=97821, t=1970-08-04 01:19:55.621)
] and some elements were unexpected: [
  Blonde(a=foo, b=true, c=23423, t=1970-05-23 07:06:31.293),
  Blonde(a=hoo, b=true, c=96915, t=1970-05-23 15:43:11.293)
]
```
The rest will be updated over the next few weeks to do the same thing.

**Comment by phauer** [comment]
That looks great! Thank you so much. :-)

**Comment by sksamuel** [comment]
I just updated some remaining collections matchers with the better messages. I think I can close this now.

**Comment by krichter722** [comment]
Those are great changes, but they apparently never have been released or are not the default/hidden behind a setting in 5.9.1 since `shouldContainExactly` still prints output that requires formatting in two steps, in some cases only ChatGPT can handle it.

**Comment by red-avtovo** [comment]
I still wonder if that will ever be released. Visually asserting 2 lists is close to impossible
