### ISSUE TITLE
IsolationMode.InstancePerLeaf and IsolationMode.InstancePerTest register too much project listeners

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1386]
This [test](https://github.com/kotest/kotest/blob/7f08d2fc5a4d540e7deb9e53044cfee2bcce2307/kotest-tests/kotest-tests-core/src/jvmTest/kotlin/com/sksamuel/kotest/specs/isolation/leaf/BehaviorSpecInstancePerLeafTest.kt#L9) and similar work too bad.
As `IsolationMode.InstancePerLeaf` and `IsolationMode.InstancePerTest` `createInstance` for each test then each iteration create a new lists of `_extensions` and `_listeners` but this rule don't work for 
`afterProject`. As `Project` is object\Singleton all callbacks are collected and then invoked.
As for me it is question to discus.
On the one hand 'afterProject' should be invoked only once for all project and I expect this behavior from its name and sketchy(lightweight) code reading , but on the other hand `afterProject` can capture variables in the closure and these variables may be different for each Instance of Spec.
I think this is a subtle point that not every programmer will understand and remember, let alone QA

**Comment by sksamuel** [comment]
I would register a ProjectListener using @Autoscan.

**Comment by crazyk2** [comment]
As I said afterProject may capture variables from concrete test for final assertion as you do [here](https://github.com/kotest/kotest/blob/7f08d2fc5a4d540e7deb9e53044cfee2bcce2307/kotest-tests/kotest-tests-core/src/jvmTest/kotlin/com/sksamuel/kotest/specs/isolation/leaf/BehaviorSpecInstancePerLeafTest.kt#L16)
Or fix this behavior or forbid register afterProject from spec.

**Comment by crazyk2** [comment]
My opinion and feature request is add names for callbacks for register failed as test as you did with failed after\beforeProject in `JUnitTestEngineListener` `engineFinished` and instead of static names `AfterAllCallback` and `BeforeAllCallback` use user names for better readability and report generation.
If this feature will be implemented you could add afterProject callback in collection with filtered name (for example map)

**Comment by crazyk2** [comment]
I am from TestNG and all before\afterTest before\afterClass are shown in IDEA Run\Debug window and in reports with their names (function name or user defined).

**Comment by sksamuel** [comment]
Now that we have multiple exceptions like `afterproject_1` etc, do we still need this ?

**Comment by crazyk2** [comment]
Still need improved docs

**Comment by sksamuel** [comment]
Feel free to submit a PR.
