### ISSUE TITLE
[Feature] Add config option alwaysRun to callback

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1388]
I want add a feature to discuss
As I said I used TestNG and there is one feature. You can add option `alwaysRun` to callback.
Now this parameter is indefined  in Kotest.
`afterTest` and  `afterProject` will be invoked even if `beforeTest` and `beforeProject` are failed.
And opposite situation with `beforeSpec` and `afterSpec`. if `beforeSpec` is failed then `afterSpec` will not be invoked.

But what if I don't want to execute `afterTest` if `beforeTest` is failed. For example I connect to Specific DB in `beforeTest` and release connect in `afterTest`. If 1 step is failed I don't want to run final step.
Of course I can add condition in afterTest `if (connection != null && connection.areOpen()) connection.close()`.
But user have to have choice or the same behavior or clear documentation

**Comment by sksamuel** [comment]
The signature of the callback methods will not change now after 4.0 has been released. We could possibly add a configuration value into ProjectConfig to allow you to always/never run callbacks if something fails ?

**Comment by crazyk2** [comment]
For different callbacks in the same project I would want to have different behavior. but ProjectConfig applied to all project.
And if [this](https://github.com/kotest/kotest/issues/1386#issuecomment-614176133) feature could be implement I don't see barrier to implement `alwaysRun` feature with default value.  I think it is not so hard work and `Interface`'s defaults help with it.
Just a brief that print `beforeTest` callback names
```kotlin
TestConfiguration{
    abstract fun beforeTest(name:String = "default", f: BeforeTest)
  }
Spec{
   override fun beforeTest( name:String, f: BeforeTest) {
      listener(object : TestListener {
         override val name = if (name == "default") "beforeTest " + this@Spec::class.description().name else name
         override suspend fun beforeTest(testCase: TestCase) {
            f(testCase)
         }
      })
   }
}
interface TestListener : Listener {
   val name : String
   get() = "default"
}

//callbacks.kt
suspend fun TestCase.invokeBeforeTest(): Try<TestCase> = Try {
   val listeners = spec.resolvedTestListeners() + Project.testListeners()
   listeners.forEach {
      println(it.name)
      it.beforeTest(this)
   }
   this
}
abstract class TestFactoryConfiguration : TestConfiguration() {
   override fun beforeTest(name :String, f: BeforeTest) {
      beforeTests = beforeTests + f
   }
}
class ExampleTest : FunSpec({

   beforeTest("should print it") {
      "void"
   }

   test("test") {
    "void"
   }
```

**Comment by crazyk2** [comment]
@sksamuel Please open these issue because question is open if you give me your thoughts about feature and green light to implement it I'll do it.

**Comment by sksamuel** [comment]
You can add a project configuration option to skip afterXX callbacks if the beforeXX fails.

**Comment by crazyk2** [comment]
Problem is more complicated because different level callbacks have different behavior. I mean beforeInvocation/Test/Spec/Project/ For example afterProject will be work always with my [help](https://github.com/kotest/kotest/issues/1387). I can spread these behavior without flag for rest of callbacks but code will be look ugly like this
```kotlin
   suspend fun execute() {
      notifyTestEngineListener()
         .flatMap { Project.listeners().beforeProject() }
         .fold(
            { error ->
               // any exception here is swallowed, as we already have an exception to report
               Project.listeners().afterProject().fold(
                  { end(listOf(error, it)) },
                  {
                     end(it + error)
                  }
               )
               return
            },
            { errors ->
               if (errors.isNotEmpty()) {
                  Project.listeners().afterProject().fold(
                     { end(errors + listOf(it)) },
                     { end(errors + it) }
                  )
                  return
               }


            }
         )

      Try { submitAll() }
         .fold(
            { error ->
               Project.listeners().afterProject().fold(
                  { end(listOf(error, it)) },
                  { end(it + error) }
               )
            },
            {
               // any exception here is used to notify the listener
               Project.listeners().afterProject().fold(
                  { end(listOf(it)) },
                  { end(it) }
               )

            }
         )
   }
```
flatMap fold flatMap fold and etc,
With flag I think will be the same situation

**Comment by sksamuel** [comment]
I don't think there is much alternative to having a flat at each level?
You could have a single flag "alwaysCallAfterCallbacks"

**Comment by crazyk2** [comment]
What do you think about ability to set config option for each after listener execute or not one during fail situation with default value as is now.
As for me it's better approach than Project config because it's more agile. 
I have 2 `beforeSpec` and 2 `afterSpec` listeners. Just as example
```kotlin
class TestListenerAfterParentTest22 : FunSpec() {
   lateinit var mainJdbcTemplate: JdbcTemplate
   init {
      beforeSpec {
         throw RuntimeException("Ooops")
         mainJdbcTemplate = DbFactory.createconnection()
      }

      afterSpec.config(alwaysRun = true) {
         if (mainJdbcTemplate != null) {
            mainJdbcTemplate.dataSource?.connection?.close()
         }
      }
   }
}

class TestListenerAfterParentTest22 : FunSpec() {
   init {
      beforeSpec {
         throw RuntimeException("Ooops")
         println("Spec started")
      }
         
      afterSpec.config(alwaysRun = false /*default*/) {
         println("${it.javaClass.name} was executed")
      }
   }
}
```
And I would add listener name to this new config for example `ListenerConfig`

**Comment by sksamuel** [comment]
Why is adding another config option better than just wrapping your after
callback in an if statement ?

**Comment by crazyk2** [comment]
> Why is adding another config option better than just wrapping your after callback in an if statement ?


I don't understand

**Comment by sksamuel** [comment]
I'm just wondering why a config option is simpler than doing `if (xx) { }` inside the callback ?
