### ISSUE TITLE
Issues with classloader when using Roboeletric Extension

### ISSUE THREAD

**Issue by asm0dey** [kotest/kotest#1394]
I'm trying to migrate [this class](https://github.com/mtotschnig/MyExpenses/blob/master/myExpenses/src/test/java/org/totschnig/myexpenses/util/UiUtilsDateModeTest.java) to kotest using the simplest available technic:

1. Create new class
2. extend it from `AnnotationSpec`
3. Add `RoboelectricExtension` to it
4. Add `Roboelectric` annotation to this class
5. Copy-paste code from source class with automatic conversion to kotlin
6. Fixing some minor syntax issues

Result is as following:

```kotlin
package org.totschnig.myexpenses.util

import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.experimental.robolectric.RobolectricExtension
import io.kotest.experimental.robolectric.RobolectricTest
import junit.framework.Assert
import org.mockito.ArgumentMatchers
import org.mockito.Mockito
import org.totschnig.myexpenses.model.Account
import org.totschnig.myexpenses.model.AccountType.BANK
import org.totschnig.myexpenses.model.AccountType.CASH
import org.totschnig.myexpenses.preference.PrefHandler
import org.totschnig.myexpenses.preference.PrefKey
import org.totschnig.myexpenses.preference.PrefKey.TRANSACTION_WITH_TIME
import org.totschnig.myexpenses.preference.PrefKey.TRANSACTION_WITH_VALUE_DATE
import org.totschnig.myexpenses.util.UiUtils.DateMode

@RobolectricTest
class UiUtilsDateModeKTest : AnnotationSpec() {
    private lateinit var cashAccount: Account
    private lateinit var bankAcount: Account
    private lateinit var prefHandler: PrefHandler

    init {
        extensions(RobolectricExtension())
    }

    @Before
    fun setup() {
        cashAccount = Mockito.mock(Account::class.java)
        bankAcount = Mockito.mock(Account::class.java)
        Mockito.`when`(cashAccount.getType()).thenReturn(CASH)
        Mockito.`when`(bankAcount.getType()).thenReturn(BANK)
        prefHandler = Mockito.mock(PrefHandler::class.java)
    }

    private fun mockPref(prefKey: PrefKey, value: Boolean) {
        Mockito.`when`(prefHandler!!.getBoolean(ArgumentMatchers.eq(prefKey), ArgumentMatchers.anyBoolean())).thenReturn(value)
    }

    @Test
    fun withTimeAndWithValueDate() {
        mockPref(TRANSACTION_WITH_TIME, true)
        mockPref(TRANSACTION_WITH_VALUE_DATE, true)
        Assert.assertEquals(DateMode.DATE_TIME, dateMode(cashAccount))
        Assert.assertEquals(DateMode.BOOKING_VALUE, dateMode(bankAcount))
    }

    @Test
    fun withTimeAndWithoutValueDate() {
        mockPref(TRANSACTION_WITH_TIME, true)
        mockPref(TRANSACTION_WITH_VALUE_DATE, false)
        Assert.assertEquals(DateMode.DATE_TIME, dateMode(cashAccount))
        Assert.assertEquals(DateMode.DATE_TIME, dateMode(bankAcount))
    }


    @Test
    fun withoutTimeAndWithValueDate() {
        mockPref(TRANSACTION_WITH_TIME, false)
        mockPref(TRANSACTION_WITH_VALUE_DATE, true)
        Assert.assertEquals(DateMode.DATE, dateMode(cashAccount))
        Assert.assertEquals(DateMode.BOOKING_VALUE, dateMode(bankAcount))
    }

    @Test
    fun withoutTimeAndWithoutValueDate() {
        mockPref(TRANSACTION_WITH_TIME, false)
        mockPref(TRANSACTION_WITH_VALUE_DATE, false)
        Assert.assertEquals(DateMode.DATE, dateMode(cashAccount))
        Assert.assertEquals(DateMode.DATE, dateMode(bankAcount))
    }

    private fun dateMode(account: Account?): DateMode? {
        return UiUtils.getDateMode(account!!.type, prefHandler)
    }

}
```

When I'm trying to run this test I'm getting very strange errors like

```
ClassCastException occurred while creating the mockito mock :
  class to mock : 'org.totschnig.myexpenses.model.Account', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@18b4aac2'
  created class : 'org.totschnig.myexpenses.model.Account$MockitoMock$705451427', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@762afe37'
  proxy instance class : 'org.totschnig.myexpenses.model.Account$MockitoMock$705451427', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@762afe37'
  instance creation by : ObjenesisInstantiator
```

It looks like smth wrong happening in extension, but I don't know what

**Comment by asm0dey** [comment]
Moreover, if I change Mockito to mockk I'm getting weird situation when sometimes self reference in MyApplication class is null and sometimes i's something

**Comment by LeoColman** [comment]
Hi, @asm0dey! Thanks for the thorough report!

Could you try this for me?

1. Create a [project level configuration class](https://github.com/kotest/kotest/blob/master/doc/project_config.md) (Basically, create any class extending AbstractProjectConfig)
2. Add the `RobolectricExtension` as an extension in that project config
3. Run your tests again

**Comment by asm0dey** [comment]
@Kerooker That worked, awesome! Definitely should be added to readme. Do you need any help with it?

**Comment by sksamuel** [comment]
Yes, any help on docs is always welcome.

**Comment by LeoColman** [comment]
> That worked, awesome
Great! It makes sense, we change how to class is created, and I think it doesn't work if you add it as an extension to the class (as when you discover how to instantiate, it's already instantiated xD)

> Do you need any help with it
I think we don't have any documentation on Robolectric yet :sweat_smile:
Do you want to try to add it somewhere that makes sense?

**Comment by asm0dey** [comment]
Please review PR with small ducumentation improvements. Thx :)

On 20/04/21 08:16AM, Leonardo Colman Lopes wrote:
> > That worked, awesome
> Great! It makes sense, we change how to class is created, and I think it doesn't work if you add it as an extension to the class (as when you discover how to instantiate, it's already instantiated xD)
> 
> > Do you need any help with it
> I think we don't have any documentation on Robolectric yet :sweat_smile:
> Do you want to try to add it somewhere that makes sense?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kotest/kotest/issues/1394#issuecomment-617245090

-- 
Regards,
Pasha

Big Data Tools @ JetBrains

**Comment by asm0dey** [comment]
@Kerooker but now another tests don't run :(

**Comment by LeoColman** [comment]
Which version are you using?

**Comment by asm0dey** [comment]
4.0.1

**Comment by asm0dey** [comment]
My config is as following:
```kotlin
class MyProjectLevelConfig : AbstractProjectConfig() {
    override fun extensions(): List<Extension> = super.extensions() + RobolectricExtension()
}
```

**Comment by LeoColman** [comment]
Ah, here's the thing:

There's an Annotation called `@RobolectricTest`, which is necessary to detect which classes are to be run in Robolectric.

I'm sorry, details are not very clear yet

**Comment by asm0dey** [comment]
I know, but I don't want other non robolectric tests to be ran with robolectric. Actually I've even written in PR about it

**Comment by asm0dey** [comment]
But I have other tests than Robolectric ones and they're just ignored

**Comment by asm0dey** [comment]
Oh, I know! 

Code should be like following:

```kotlin
   override suspend fun intercept(testCase: TestCase, execute: suspend (TestCase) -> TestResult): TestResult {

      if (testCase.spec::class.isNotRobolectricClass()) {
         return execute(test)
      }

      val containedRobolectricRunner = ContainedRobolectricRunner()

      beforeTest(containedRobolectricRunner)
      val result = execute(testCase)
      afterTest(containedRobolectricRunner)
      return result
   }
```

**Comment by asm0dey** [comment]
Also, it makes sense to convert `RobolectricExtension` from class to object. We really need only one instance of it per project

**Comment by asm0dey** [comment]
If you could make `io.kotest.experimental.robolectric.RobolectricExtension` non-final I could override only one method. For now, I should copy-paste whole class to change behavior of the only method

**Comment by LeoColman** [comment]
Yeah, I think this is actually more of a bug. You should be able to execute tests outside of that extension.

I'll fix it for the next snapshot and next version.

**Comment by asm0dey** [comment]
Thank you!

**Comment by asm0dey** [comment]
@Kerooker BTW shouldn't it be the chain of responsibility? What if I want to have two extensions which should add something around spec? For example some extension over Robolectric test. Currently — it won't work because Robolectric test executes test itself.

**Comment by LeoColman** [comment]
If you  have two extensions that should add something around the spec, you should use a [Listener](https://github.com/kotest/kotest/blob/master/doc/reference.md#listeners).

If you have two extensions that override how the spec is instanced, then I think there's nothing we can do. You can't load it in two classloaders, for example

**Comment by asm0dey** [comment]
Oh, I see, thanks!
