### ISSUE TITLE
gradle wrapper version

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1396]
Should be 
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
instead of 
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3 **.0** -all.zip
https://github.com/kotest/kotest/pull/1392/files#diff-fd9d61e37d939c941e7a62077f38d62dL3

**Comment by LeoColman** [comment]
https://gradle.org/install/

> The current Gradle release is 6.3.

Fixed
