### ISSUE TITLE
Property testing docs need updating?

### ISSUE THREAD

**Issue by Jestar342** [kotest/kotest#1399]
Hi, 

Kotlin beginner here so go easy please :)

Trying to do some property testing, following this doc: https://github.com/kotest/kotest/blob/master/doc/property_testing.md

But using kotest-property-jvm:4.0.3 and the API in the doc just doesn't seem to match what IntelliJ is telling me is in the actual lib. 

For example, `Exhaustive.int` doesn't exist, I can only find `Exhaustive.ints` (plural), and the following spec:
```
import io.kotest.core.spec.style.StringSpec
import io.kotest.properties.assertAll
import io.kotest.property.Exhaustive
import io.kotest.property.exhaustive.ints

class Blah : StringSpec({
    "It should do something with the numbers" {
        assertAll(Exhaustive.ints(1..10)) { n -> n < 11 }
    }
})
```

gives a compile/intellij error with 
```
None of the following functions can be called with the arguments supplied.
assertAll(Gen<TypeVariable(A)>, PropertyContext.(a: TypeVariable(A)) → Unit)   where A = TypeVariable(A) for    fun <A> assertAll(gena: Gen<A>, fn: PropertyContext.(a: A) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A)) → Unit)   where A = TypeVariable(A) for    inline fun <reified A> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A), b: TypeVariable(B)) → Unit)   where A = TypeVariable(A), B = TypeVariable(B) for    inline fun <reified A, reified B> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A, b: B) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A), b: TypeVariable(B), c: TypeVariable(C)) → Unit)   where A = TypeVariable(A), B = TypeVariable(B), C = TypeVariable(C) for    inline fun <reified A, reified B, reified C> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A, b: B, c: C) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A), b: TypeVariable(B), c: TypeVariable(C), TypeVariable(D)) → Unit)   where A = TypeVariable(A), B = TypeVariable(B), C = TypeVariable(C), D = TypeVariable(D) for    inline fun <reified A, reified B, reified C, reified D> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A, b: B, c: C, D) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A), b: TypeVariable(B), c: TypeVariable(C), d: TypeVariable(D), e: TypeVariable(E)) → Unit)   where A = TypeVariable(A), B = TypeVariable(B), C = TypeVariable(C), D = TypeVariable(D), E = TypeVariable(E) for    inline fun <reified A, reified B, reified C, reified D, reified E> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A, b: B, c: C, d: D, e: E) → Unit): Unit defined in io.kotest.properties
assertAll(Int, PropertyContext.(a: TypeVariable(A), b: TypeVariable(B), c: TypeVariable(C), d: TypeVariable(D), e: TypeVariable(E), f: TypeVariable(F)) → Unit)   where A = TypeVariable(A), B = TypeVariable(B), C = TypeVariable(C), D = TypeVariable(D), E = TypeVariable(E), F = TypeVariable(F) for    inline fun <reified A, reified B, reified C, reified D, reified E, reified F> assertAll(iterations: Int, noinline fn: PropertyContext.(a: A, b: B, c: C, d: D, e: E, f: F) → Unit): Unit defined in io.kotest.properties
```

**Comment by sksamuel** [comment]
import io.kotest.properties.assertAll should be import
io.kotest.property.assertAll I think.

It's confusing because there's the old and new property test stuff.

**Comment by rackdon** [comment]
I've copied the example of the docs and when try to compile, I've received the same error as @Jestar342

**Comment by sksamuel** [comment]
I've added a note to the documentation that explains that
io.kotest.property are the imports to use.

**Comment by c089** [comment]
@sksamuel thank you for the update on documentaten. I just stumbled over the same confusion, and It seems the it comes from the documentation being a bit ahead of reality: The current package doesn't expose `assertAll` under the `io.kotest.property` package (it does have `checkAll` as documented) in the latest published version `4.0.4`. Looking at the source, it seems all  references to `assertAll` in kotest itself are either using the `io.kotest.properties` package, or are just [disabled](https://github.com/kotest/kotest/blob/12236c5aae7b807162b2648256549713a62196e1/kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/properties/PropertyAssertAllTest.kt) since 12236c5aae7b807162b2648256549713a62196e1

**Comment by sksamuel** [comment]
I must have been drunk when writing these docs because the function you
want is not assertAll, but forAll. assertAll has been deprecated and
renamed to checkAll.
No wonder there was confusion.
I've updated the docs to correct this stupid mistake!

**Comment by LeoColman** [comment]
So perhaps we can close this?

**Comment by Jestar342** [comment]
Thanks guys, it was indeed `forAll` that I needed to use.
