### ISSUE TITLE
Add support for Quarkus

### ISSUE THREAD

**Issue by bnjns** [kotest/kotest#1401]
We've been using kotest for a while now and are loving how much easier testing is with it. We've also recently moved from Spring to Quarkus, which is another framework which follows the microprofile spec similar to Micronaut.

It makes us very sad that for any tests which need dependency injection we have to fall back to the classic JUnit tests, as we make use of BDD heavily everywhere else.

Would it be possible add an extension that supports Quarkus? I'm hoping it would be similar to Spring/Micronaut.

**Comment by sksamuel** [comment]
We could add one. Any chance you could guide this ?

**Comment by bnjns** [comment]
I'm not very familiar with how the extensions work in kotest, but I am more than happy to help where I can :)

**Comment by sksamuel** [comment]
It's the quarkus bit that would new to us. Do you basically instantiate the
class via a special way

**Comment by bnjns** [comment]
Ah yeah. They have a `@QuarkusTest` annotation that you add to the class, which uses the following with the JUnit `@ExtendWith` annotation: https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java

You then inject annotations normally using `@Inject` on a `lateinit var` or in the constructor, if you're using constructor injection.

**Comment by sksamuel** [comment]
So @QuarkusTest populates fields or parameters using @Inject. Is it doing
anything else beside that? Like are the dependencies it injects just
regular deps like outside of a test?

Would you make a PR that sets up a new module in here using quarkus:
https://github.com/kotest/kotest/tree/master/kotest-extensions

In this module if you can make a sample app that has a unit test that you'd
like to work, if we had quarkus support, then I will add to the PR with
quarkus integration ?
So like the spring one.
https://github.com/kotest/kotest/tree/master/kotest-extensions/kotest-extensions-spring/src/jvmTest/kotlin/com/sksamuel/kt/spring

The test can be anything, just injecting some services via constructor and
fields.

**Comment by bnjns** [comment]
Apologies for the late reply.

Yeah dependencies are regular dependencies you inject with `@Inject`.

Happy to set up a PR with a new module, but I'm struggling to get it to import - Gradle keeps giving me 

```
Cause: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$1.remove(Collections.java:4714)
	at java.base/java.util.AbstractSet.removeAll(AbstractSet.java:176)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolverUtil.doBuildDependencies(GradleProjectResolverUtil.java:646)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolverUtil.buildDependencies(GradleProjectResolverUtil.java:565)
	at org.jetbrains.kotlin.idea.configuration.KotlinMPPGradleProjectResolver$Companion$populateModuleDependencies$1.invoke(KotlinMPPGradleProjectResolver.kt:543)
	at org.jetbrains.kotlin.idea.configuration.KotlinMPPGradleProjectResolver$Companion$populateModuleDependencies$1.invoke(KotlinMPPGradleProjectResolver.kt:185)
    ...
```

Any ideas?

**Comment by ashishkujoy** [comment]
@bnjns  If you are using intellij idea 2020.1 edition. Then that has a bug with kotlin multiplatform that cause this problem

**Comment by bnjns** [comment]
@ashishkujoy Of course it does ... :joy:

**Comment by ashishkujoy** [comment]
@bnjns Try with any 2019 intellij edition

**Comment by bnjns** [comment]
@ashishkujoy Yeah just downgraded to 2019.3.1 and it's all good - thanks!

**Comment by bnjns** [comment]
I think I've got a module set up, with some example tests for a few injection use-cases. Where would be best to put this that would let you guys then add the integration?

**Comment by sksamuel** [comment]
Can you create a PR and tick the box that allows other people to edit it ?
We can work on that PR.

**Comment by bnjns** [comment]
Created https://github.com/kotest/kotest/pull/1424 with what I think is enough? Happy to continue to help however possible :slightly_smiling_face:

**Comment by LeoColman** [comment]
I left just a comment to your DSL.
I'm not sure if you want to pitch in with some ideas in that regard

**Comment by LeoColman** [comment]
Ah, I see it's not applicable to local variables. Forget that :sweat_smile:

**Comment by LeoColman** [comment]
Hey, @bnjns!
I couldn't create a hello-world quarkus + test project to study it. Could you guide me how to do it?

- Just a simple hello application
- Integrated with Gradle
- With a simple JUnit test

**Comment by bnjns** [comment]
Hi @Kerooker, should just be a case of going to https://code.quarkus.io, selecting `Gradle (Preview)` as the Build Tool and adding the `Kotlin (Preview)` extension. I believe Quarkus automatically add JUnit 5 support.

You just need to ensure that your test class is annotated with `@QuarkusTest` if you want to inject something :)

**Comment by xmlking** [comment]
any update on this?
can't wait on my testing passing :)
https://github.com/xmlking/micro-apps/blob/develop/apps/greeting-quarkus/src/test/kotlin/micro/apps/greeting/FruitResourceTest.kt

**Comment by sksamuel** [comment]
So I spent some time on this... and it's very hard. The way quarkus works with its compile time generation... I struggled to get anywhere. You can see the complexity by looking at the JUnit implementation they've done. 

So a different approach maybe to add support for JUnitExtensions to Kotest. As a quick glance it looks like we could support their ExtensionContext API and then we could piggy back on the Quarkus support for JUnit.

**Comment by bnjns** [comment]
@sksamuel That's annoying, but I am sadly not surprised that Quarkus have built an implementation that's complex :disappointed: 

Is there anything I can possible lend a hand with?

**Comment by sksamuel** [comment]
We need to basically implement the JUnit ExtensionContext interface and
fill it with Kotest values.

That's not Quarkus specific, but with that we should be able to hook into
Quarkus easily?

**Comment by LeoColman** [comment]
> We need to basically implement the JUnit ExtensionContext interface and
fill it with Kotest values.

I believe that we have that with the JUnit extension

**Comment by sksamuel** [comment]
We need to support one more callback - the InvocationInterceptor

**Comment by bnjns** [comment]
@sksamuel have you guys managed to get any further? :slightly_smiling_face:

**Comment by sksamuel** [comment]
Yes, we need to finish implementing the JUnit 5 extension adapter, and then the Quarkus Junit 5 extension will just work with Kotest. It's mostly done.

**Comment by snowe2010** [comment]
@sksamuel which ticket on the roadmap is for implementing the adapter? I'd like to help push this along, as we're ramping up our Quarkus usage and Kotest is extremely valuable for the things we're doing (decision tables).

**Comment by sksamuel** [comment]
We need to test that the JUnit adapter in kotest has enough support so that the JUnit rule for quarkus can be used as is.

This extension from Quarkus is for JUnit 5. 
https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java

But all it's doing is managing the lifecycle based on the extension points in JUnit5. Now our compatiblity layer for JUnit5 maps those extension points to Kotest lifecycle callbacks.

https://github.com/kotest/kotest/blob/master/kotest-extensions/kotest-extensions-junit5/src/jvmMain/kotlin/io/kotest/extensions/junit5/KotestExtension.kt

The remaining step is to test this in a quarkus project, and fix up if something doesn't work. I think the `InvocationInterceptor` support might be all that's left.

**Comment by sksamuel** [comment]
Example project can be setup here so we have a reference for future tests/compatibility: https://github.com/kotest/kotest-examples-quarkus

**Comment by snowe2010** [comment]
If you make that project, I'll make PRs to it. I'm already investigating the KotestExtension. Initially thought it was already pushed to maven central but that appears to just be a pom.

**Comment by sksamuel** [comment]
The project is there.

**Comment by snowe2010** [comment]
Hm. I get 404s trying to access. Guessing it's private?

**Comment by Solido** [comment]
Hi !

Is there still an effort on this task or a timeframe for the coming months ?
After reviewing all solutions it looks like Kotest matcher would be a very good fit but the integration is not trivial at all ...

Many thanks

**Comment by sksamuel** [comment]
Matchers should work without any changes because they work with any
framework.
Kotest test framework with Quarkus is still planned for 4.4.

**Comment by Solido** [comment]
Hi @sksamuel  !
Thanks you for the quick feedback glad to hear it is still on the table.

Added on 1.10.3.Final

```
implementation("io.kotest:kotest-framework-api-jvm:4.2.5")
implementation("io.kotest:kotest-framework-engine-jvm:4.2.5")
```

Failed with 

```
lateinit property layout has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property layout has not been initialized
```

on basic test

```
@QuarkusTest
class QuarkusMockTest : FunSpec() {

    @Inject
    lateinit var layout: BoardLayoutService

    init {
        test("Should inject the mocked bean") {
            layout.gen()
        }
    }
}
```

Should I wait for future release ?

**Comment by snowe2010** [comment]
I wanted to work on this, but was unable to ever get kotest to compile correctly on my machine. I can give it another go sometime this week.

**Comment by snowe2010** [comment]
don't close pls. I've started to look into it again, but keep getting pulled off for other work.

**Comment by snowe2010** [comment]
I created the example for quarkus, but was told more work would be done on it to get the example working. Where are we with that? Is that something I can help with? https://github.com/kotest/kotest-examples-quarkus

**Comment by GavinRay97** [comment]
I'm willing to try to help out here too, time permitting. Have some experience authoring Quarkus extensions + familiarity with Quarkus codebase. (Not sure how useful that is for this particular scenario but maybe better than nothing? 😅)

- https://github.com/quarkiverse/quarkus-scala3
- https://github.com/quarkusio/quarkus/issues/2720#issuecomment-881139430

Have started by updating the example repo to confirm it's still broken (since there's been a major version change in Quarkus since then) 👍 
https://github.com/kotest/kotest-examples-quarkus/pull/2

**Comment by sybarite1** [comment]
Hi,
I am more than happy to help in this. I have been working extensively with Quarkus and Kotlin.
And would love to move to kotest from JUnit 5.
Let me know where you want me to begin.
Best regards.

**Comment by sksamuel** [comment]
Best bet is to chat on slack. @sybarite1

**Comment by sksamuel** [comment]
There's been no change in adding a test agnostic set of interfaces to Quarkus. It appears the team would rather stay tied into Junit, which is understandable given the work required to change it and how ubiquitous and popular junit is in the core target market of Java.

We can re-open this in the future if Quarkus abstracts out the test mechanism.

**Comment by GavinRay97** [comment]
A bummer, but understandable

**Comment by snowe2010** [comment]
dang. I will work on pushing them on it, but it seems that one of us is going to have to do the work ourselves if we want it in quarkus. very frustrating.

**Comment by ygyg70** [comment]
Just landed on this thread. Is anyone using kotest with Quarkus?

**Comment by piu130** [comment]
We are using `io.kotest:kotest-assertions-core-jvm` and `io.kotest:kotest-property-jvm` but not the runner.

**Comment by Obirah** [comment]
> We are using `io.kotest:kotest-assertions-core-jvm` and `io.kotest:kotest-property-jvm` but not the runner.

Similar for us: we separated a `test` and an `integrationTest` source set. In the `test` source set we're running kotest "fully" and in `integrationTest` we're using piu130's approach as well.

**Comment by bnjns** [comment]
> > We are using `io.kotest:kotest-assertions-core-jvm` and `io.kotest:kotest-property-jvm` but not the runner.
> 
> Similar for us: we separated a `test` and an `integrationTest` source set. In the `test` source set we're running kotest "fully" and in `integrationTest` we're using piu130's approach as well.

This is what we ended up doing too

**Comment by rgmz** [comment]
Revisiting this several years later, I've managed to create an extension (with Claude's assistance) that seems to work with a real production application.

It isn't necessarily _good_ but it gives me hope that a proper solution is possible.
https://github.com/rgmz/quarkus-kotest
