### ISSUE TITLE
Number generators have wrong edge cases

### ISSUE THREAD

**Issue by paralainer** [kotest/kotest#1405]
Number generators (like `Arb.long()`, `Arb.int()`) accept a range as a parameter but using `MAX_VALUE`, `MIN_VALUE` as edgecases.

I guess more correct approach is to use `range.start` and `range.endInclusive` as edgecases.

https://github.com/kotest/kotest/blob/d03c9c9f0525071ac85ffdb3b8067acf24d75da6/kotest-property/src/commonMain/kotlin/io/kotest/property/arbitrary/longs.kt#L11

This part should look like:
```
fun Arb.Companion.long(range: LongRange = Long.MIN_VALUE..Long.MAX_VALUE): Arb<Long> {
   val edgecases = listOf(0, range.start, range.endInclusive)
   return arb(LongShrinker, edgecases) { it.random.nextLong(range) }
}
```

**Comment by paralainer** [comment]
Actually `0` should be included only if it's a part of the range too.

**Comment by LeoColman** [comment]
Agreed, makes a lot of sense!
Do you want to work on this?
