### ISSUE TITLE
Provide support for adding config at higher level in case of nested test

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#1410]
[This question](https://stackoverflow.com/questions/61057335/setting-tags-at-the-class-level-or-container-level) has been asked on stackoverflow.

As of now we can add config to the lowest level/leaf test of nested test for example 

```kotlin
class MyTest : FreeSpec({
 "high level container with multiple tests" - {
    "always failing test".config(enabled: false) { // config at lowest level or leaf
        fail("Should not get called")
    }

   "another always failing test".config(enabled: false){ // config at lowest level or leaf
        fail("Should not get called")
    }
  }
})
```

we should have ability to provide config at higher level/container  as well for example

```kotlin
class MyTest : FreeSpec({
 "high level container with multiple tests".config(enabled: false) - { // config at top level/container
    "always failing test" {
        fail("Should not get called")
    }

   "another always failing test" {
        fail("Should not get called")
    }
  }
})
```

**Comment by sksamuel** [comment]
Maybe, but it would have to be a cut down version of config - without invocations / threads.
So we could have ContainerTestConfig which has enabled, enabledIf, tags.

**Comment by sksamuel** [comment]
```
data class ContainerTestConfig constructor(
   val enabled: Boolean = true,
   val timeout: Duration? = null,
   val tags: Set<Tag> = emptySet(),
   val enabledIf: EnabledIf = { true }
)
```

We should also add 

```
data class DefaultTestConfig constructor(
   val enabled: Boolean = true,
   val timeout: Duration? = null,
   val tags: Set<Tag> = emptySet(),
   val listeners: List<TestListener> = emptyList(),
   val extensions: List<TestCaseExtension> = emptyList(),
   val enabledIf: EnabledIf = { true }
)
```

Which we use in the specs, because the default allows you to specify invocations and threads at the moment which then fail.

**Comment by sksamuel** [comment]
That second point will address this: https://github.com/kotest/kotest/issues/1370

**Comment by sksamuel** [comment]
We can now use timeouts at a higher level.
We can disable using ! at a higher level.
And tags have always been supported at a higher level.
I think this is good to close.
