### ISSUE TITLE
Make the arb.choice function take derived classes

### ISSUE THREAD

**Issue by ataronet** [kotest/kotest#1422]
I am using the new Arb.choice function (Kotest version 4.0.5) and when I use derived classes I need to cast them. For example
```
    Arb.choice(
        Arb.constant(RuntimeException(message)) as Arb<Exception>,
        Arb.constant(Exception(message)),
        Arb.constant(IllegalArgumentException(message)) as Arb<Exception>,
        Arb.constant(IllegalStateException(message)) as Arb<Exception>
    )
```
I would like to know if it is possible to declare their types internally as anything that derive from T so I won't need to cast them.
Thank you.

**Comment by sksamuel** [comment]
Yes that makes sense. do you want to prepare a PR ?

**Comment by ataronet** [comment]
Happy too but I will only get to it on the weekend.
Here is the fix that I am now testing for my code 
`fun <A> Arb.Companion.choice(vararg arbs: Arb<out A>): Arb<A> = arb(arbs.flatMap(Arb<out A>::edgecases))` 
I just changed the signature of your implementation to add `out`

**Comment by jaymoid** [comment]
Ah this is my fault/bug, I prepared a fix, but don't want to step on any toes if you wanted to raise a PR (https://github.com/kotest/kotest/compare/master...jaymoid:arbVarianceFix)

**Comment by sksamuel** [comment]
If you're ready with it james make sense to take yours.

**Comment by sksamuel** [comment]
Can you try the latest snapshot as this should be fixed.

**Comment by ataronet** [comment]
I will! 
btw spent few hours trying to set up my environment and it is failing to build. I think it'd be great to have instructions on "how to set up your env" and how to run tests etc.
I was hoping to fix it myself but maybe next time.
Will let you know if your fix works

**Comment by ataronet** [comment]
let me know which snapshot you want me to try. I could not find any newer version after 4.0.5 which I have

**Comment by sksamuel** [comment]
Snapshots are 4.1.x and are linked on github main page.

**Comment by ataronet** [comment]
Can you be more specific about the main page? I wasn't able to find any snapshot on this page https://github.com/kotest/kotest, and not in here: https://github.com/kotest/kotest/releases. what is the link to the snapshots?

**Comment by sksamuel** [comment]
Badge at the top under the logo.

**Comment by ataronet** [comment]
👍 Thank you, it works!!
