### ISSUE TITLE
Compilation error when using kotest-assertions-core-jvm without kotest runner dependency 

### ISSUE THREAD

**Issue by akowal** [kotest/kotest#1425]
According to the docs, to use assertions library it should be enough to add one dependency `io.kotest:kotest-assertions-core-jvm:<version>`. Unfortunately this doesn't work, some matchers cannot be resolved and compilation fails. Here's a minimal project that reproduces the problem: https://github.com/akowal/kotest-deps-issue/

**Comment by ashishkujoy** [comment]
Another observation, running test using intellij test runner works fine however with gradle it fails to resolve the import statement.

**Comment by sksamuel** [comment]
I don't know why it doesn't work because 

```
         // this is api because we want to expose `shouldBe` etc
            api(project(Projects.AssertionsShared))
```

**Comment by TheNumberOne** [comment]
I'm getting the same problem lol

**Comment by TheNumberOne** [comment]
When I use the latest snapshot, this problem doesn't exist anymore. Here is a copy of @akowal's  repository that uses the latest snapshot: https://github.com/TheNumberOne/kotest-deps-issue

**Comment by jazzinpark** [comment]
I was also having a same issue, and following @TheNumberOne's suggestion to use the latest snapshot (kotest-assertions-core-jvm:4.1.0.291-SNAPSHOT) solved the problem for now.

**Comment by ejhobbs** [comment]
I've also just run into this issue, exact same configuration as OP and moving to snapshot as per @TheNumberOne has fixed it.

**Comment by sksamuel** [comment]
I think its because in 4.0.x the dependency is implementation(project(":kotest-assertions"))
In master its api.
I'll release 4.0.6 with this fix and some others.

**Comment by sksamuel** [comment]
4.0.6 has been released which fixes this.
