### ISSUE TITLE
Add `arb(edgecase, ...)` for a single edge case

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1431]
Currently, we have the following syntax for arbs:

```
arb(
    edgeCases = listOf(1, 2, 3)
) { ... }
```

When adding a single edgecase, that function requires the creation of a list, and thus is more verbose:

```
arb(
edgeCases = listOf(1)
) { ... }
```

We can add a shorter syntax for a single edgecase, just as sugar for our user:

```
arb(
    edgecase = 1
) { ... }
```

And then
```
arb(1) { ... }
```
instead of
```
arb(listOf(1)) { ... }
```

**Comment by sksamuel** [comment]
I had a go at this and the signatures clash.
I think we should just close this unless you can find a way to do it.

**Comment by LeoColman** [comment]
I'll take a look

**Comment by LeoColman** [comment]
Yeah, couldn't find a quick way to solve it.
If I ever think on something that addresses this I'll include it again.
