### ISSUE TITLE
Test only one function

### ISSUE THREAD

**Issue by neelkamath** [kotest/kotest#1432]
In regular JUnit tests, I can test only one function in a class like `gradle test --tests ClassName.functionName`. How can I do this in Kotest, using `StringSpec()` in particular?

**Comment by LeoColman** [comment]
While the Kotest plugin for IntelliJ isn't released, you can execute a single test by using a Focus on the top level test.

Please see more documentation [here](https://github.com/kotest/kotest/blob/84d0d6f7d1086a53342ecc3ca49039c2cc477227/doc/conditional_evaluation.md)

**Comment by neelkamath** [comment]
Thanks. I'll use Focus.

Regarding the IntelliJ plugin, I don't think that would be helpful in my case, since I just run Gradle test commands in IntelliJ's terminal directly. My program runs in a Docker container, and editing Run configs in the IDE to enable testing via buttons would take more time than simply running whichever command I need at the particular time by hand.

It would be helpful for Gradle to filter tests written using Kotest the way it does for JUnit so that one needn't find the test case, edit the code, and wait for a test source set recompile. But if this functionality isn't feasible to implement, it's OK because Kotest is still very much worth it because of the time it saves in all the other aspects.

**Comment by sksamuel** [comment]
We would need gradle to understand that not all test frameworks are class /
method based.
Unfortunately I can't see that happening anytime soon.
We have started work on a kotest gradle plugin though, but that might take
the rest of 2020 to complete depending on schedules.
