### ISSUE TITLE
Add property test global config with before / after prop test callbacks

### ISSUE THREAD

**Issue by ataronet** [kotest/kotest#1435]
I am using the `checkAll` function with some `Arb` and a lambda for the test. I need something like `beforeTest` but for every iteration of the `checkAll`. Thank you.

**Comment by sksamuel** [comment]
Can't you just put it inside the check all functions ?

**Comment by ataronet** [comment]
Of course but when someone adds a new test they will have to remember to add the setup cleanup stage as well.
I can try to add the functionality if it is not available but I might need some help to set up the environment. Last time I could not build the project on my laptop.

**Comment by sksamuel** [comment]
Oh so something before every single prop test.

**Comment by ataronet** [comment]
Yes. Exactly! We only use prop tests and normally we need to clean things in between their iterations.

**Comment by sksamuel** [comment]
The quick fix is to write your own checkAll which delegates to the built in
one. You'd need to write them for all arities though.
The long term fix is to add some property test project wide configuration
that allows you to specify a beforePropertyTest and afterPropertyTest
callbacks.

**Comment by ataronet** [comment]
@sksamuel @Kerooker I have a fix for that but I don't have the permission to push my changes. Please advise how I can commit my code so I can create a PR. I created a dedicated branch but still can't push my changes.

**Comment by ashishkujoy** [comment]
@ataronet You need to fork kotest, push to that fork and then create a PR from the fork.
