### ISSUE TITLE
More flexible listener/extension mechanism

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1438]
If compare JUnit, TestNG and Kotest on extension points then Kotest will be last and worst.
1) JUnit and TestNG cook testPlan/testRun before running and then filtered, mapped and etc. Kotest works only with discovered classes and has one extension point `afterScan` You may create instance of this classes and cast to `Spec` and found root tests but rest of nested tests will be handled only during running tests. This difference isn't bad just only for note but it could be useful have all testPlan before start. But we have what we have.
2) JUnit and TestNG works with annotations. These annotated methods are called configuration methods and prepare test fixture (create DB/MQ/network connections, prepare test data, do common work, clear test state, release resources and many many other things). They have separated ways to control test run flow by Listeners and Extensions. One more time, config methods and listeners are separated things. Kotest has only listeners and extensions `SpecListener`, `TestListener`, `SpecExtension`, `TestCaseExtension` and several specific extensions and use these listeners/extensions as configuration methods. The problem is I can't sort the buyers from the spyers.
Your Allure integration is not work properly. And I try to write it from scratch by myself but I need more flexible extension (or flow control) mechanism. For example, If I write some code for container creation in `BeforeSpec` listener's method and I want to write all preparing test fixture steps who give me guarantee that all steps in other BeforeSpec listeneres will be recorded? For this purpose my Allure listener must be first in `listener list`. Let's go further. Ok,  if some step in `BeforeSpec` `BeforeTest` will fail what happen then? And how it handle? How to know that particular config method is failed but not the `testCase`? Ok, `Before` methods and `testCase` are passed but what about `After` methods and their results.

I think that should be separated config methods and listeners that could intercept these config methods and their results.
Look at TestNG Listener interfaces (not codebase because its ugly but the idea)
[IConfigurationListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IConfigurationListener.java)
[IClassListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IClassListener.java)
[IMethodInterceptor](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IMethodInterceptor.java)
[IInvokedMethodListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IInvokedMethodListener.java)
[ISuiteListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/ISuiteListener.java)
[ITestListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/ITestListener.java)

JUnit 5 has power flow control mechanism too.

It useful not only for Allure integration but and for some test case management system too
I can't do such big things by myself  because it isn't my framework and maybe this feature is not needed at all

**Comment by sksamuel** [comment]
You can achieve a lot with the Extension classes. They allow you to override which tests are executed and even the results of those tests.

As for having a fully inflated test plan, that's not possible.

```kotlin
outertest { 
   innertest {
   }
}
```

The only way to get a handle to inner test is to execute outer test. In things like JUnit it's all annotations and methods so it's functions.

Perhaps if you have an example usecase we can design something to work.

**Comment by crazyk2** [comment]
`They allow you to override which tests are executed and even the results of those tests.
`Key word is test. But I want to know result of each step (preconditions, configuration methods, setup methods, call it whatever you want) and I want to control flow of these methods. Please read carefully my first message. And look at [InvocationInterceptor](https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/InvocationInterceptor.java), [TestExecutionListener](https://github.com/junit-team/junit5/blob/master/junit-platform-launcher/src/main/java/org/junit/platform/launcher/TestExecutionListener.java). 
Config methods and Listeners/Extensions are different things in TestNG and JUnit5. Kotest doesn't have a way to control config methods because Listeners are config methods by itself

**Comment by sksamuel** [comment]
So it sounds like a we could add a LifecycleExtension which allows you to
intercept before / after test / all methods.

**Comment by crazyk2** [comment]
Exactly.
```kotlin
interceptBeforeSpec(spec: Spec, beforeSpec: BeforeSpec) {
//do something before  BeforeSpec will be invoked
println("BeforeSpec will be invoked right now for spec ${spec::class}")
val result = beforeSpec(spec)
//do something after BeforeSpec was invoked
println("BeforeSpec was invoked and result is ${result.type}")
}
```
Where `BeforeSpec` need change 
from
```Kotlin
typealias BeforeSpec = suspend (Spec) -> Unit
```
to
```Kotlin
typealias BeforeSpec = suspend (Spec) -> SomeResultOfListenerCall
```
In the same way
`interceptAfterSpec`
`interceptBeforeTest`
`interceptAfterTest`
`interceptBeforeInvocation`
`interceptAfterInvocation`

**Comment by sksamuel** [comment]
This can all be done in a single LifecycleExtension point. We could add
this for 4.1 or 4.2

**Comment by sksamuel** [comment]
As a first step I have split all the listeners out into separate interfaces.
Next step is to add more interceptors.
