### ISSUE TITLE
MockServer (and HTTP) extension documentation missing

### ISSUE THREAD

**Issue by rainx0r** [kotest/kotest#1446]
I am trying to use MockServer with Kotest and noticed you have an extension for it but its usage is not documented in the doc/extensions.md document.

Could you provide a quick example? I did look into the extension myself and it seems to be a listener you can add to a spec but how would I go about doing further setup of MockServer to set up the responses I want to mock? Or assert that a request was made how I would expect it to be? From what I can find online, this functionality seems to usually be done through accessing the and modifying the MockServer object returned by MockServer's startClientAndServer(), but this object is private in MockServerListener.kt.

As a result I am rather confused of what the Kotest extension is meant to do in this case. Some documentation or examples would be appreciated!

Likewise I noticed that your http extension also has no documentation in extensions.md

**Comment by sksamuel** [comment]
In 4.2.1 the var is public so you can fetch it and register mock methods.
I will add full docs soon.

**Comment by sksamuel** [comment]
Documentation added.
