### ISSUE TITLE
checkAll(Gen) for Exhaustive with large lists does not work

### ISSUE THREAD

**Issue by Loomie** [kotest/kotest#1456]
**Which version of Kotest are you using**
4.0.5

I got an exception that I didn't understand when using `.exhaustive()` of a list with 2500 elements.
```
java.lang.IllegalArgumentException: Require at least 1000 iterations to cover requirements
```
After debugging I found that this check is in [proptest.kt](https://github.com/kotest/kotest/blob/master/kotest-property/src/commonMain/kotlin/io/kotest/property/internal/proptest.kt#L17). I think the message contains the wrong value: The "at least" number shown should be the result of `genA.minIterations()`. Or the text must be changed to "at most iterations". That's the bug I wanted to report.

As a workaround I just pass the size of the list to `checkAll(Int, Gen)`, so this is not a blocker.

But I also would like to suggest that `io.kotest.property.checkAll(Gen)` does not use `PropertyTesting.defaultIterationCount` but at least the minimum of that and `genA.minIterations()`. For exhaustive generators the full set may be iterated multiple times but I think that is often not useful, so exactly the size of the generator is what I expect from `checkAll`.

Another thing for me is the missing KDoc. It is hard for me to understand what the parameter `iterations` means for a generator. Maybe it should be named `generations`.

**Comment by LeoColman** [comment]
Thanks for the report. I'll work on this
