### ISSUE TITLE
Allow case control in test's reports

### ISSUE THREAD

**Issue by jaguililla** [kotest/kotest#1458]
When you use a test method, case is not handled. I.e.: `should("Happen something")` will be rendered as `should Happen something`.

The proposed feature is to allow case control on reports by using a report setting. This could be something like: `case = AS_IS | SENTENCE | LOWERCASE`

Being rendered in the reports this way:

* AS_IS: `should Happen something`
* SENTENCE: `Should happen something`
* LOWERCASE: `should happen something`

This setting should only affect the firsts letter of the test text and the first letter of the test method.

**Comment by jaguililla** [comment]
If time is not a concern, I would like to work on this. Could you please assign it to me? Thanks!

**Comment by sksamuel** [comment]
Assigned.

I would like to see another enum added. TITLE_CASE where you end up with "Should Happen Something"

**Comment by LeoColman** [comment]
One thing to watch out for is for something like

```
test("my HTML file should ..")
```
How would something like HTML, URI, URL, ... be transformed with these cases?

**Comment by jaguililla** [comment]
I was thinking on handling only the case of the work implied by the function name (i.e.: `test`, `should`...) and the first letter (or maybe word if the first word is all uppercase) leaving the rest of the test title intact.

Would that make sense?

**Comment by sksamuel** [comment]
Yes that makes sense and my suggestion of Title Case should be ignored.
