### ISSUE TITLE
Add Missing documentations

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#1463]
Below are few features for which we don't have documentations.

- [x] PropTestListener #1452 
- [x] ShouldTimeout for async call. #1448 
- [x] variable.assertSoftly #1429 
- [x] isEqual for ZonedDateTime #1417 

Lets keeping here any other features for which documentation is missing.

**Comment by LeoColman** [comment]
`variable.assertSoftly` is already documented at the[ assertion softly docs](https://github.com/kotest/kotest/blob/master/doc/reference.md#soft-assertions)
