### ISSUE TITLE
callback order execution and inheritance

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1469]
**Which version of Kotest are you using**
master
I use inheritance with my test instead composition and faced with problem of order execution.
```kotlin
open class BaseDbTest : FunSpec() {

    protected lateinit var mainJdbcTemplate: JdbcTemplate
    protected lateinit var virtualJdbcTemplate: JdbcTemplate

    init{
        val pg = ServiceContainer("pg", ".*database system is ready to accept connections.*")

        beforeSpec{
            println("beforeSpec pg.start()")

            pg.start()
            mainJdbcTemplate = DbFactory.create(mainConfig)
            virtualJdbcTemplate = DbFactory.create(virtualConfig)
        }
        afterSpec {
            println("afterSpec pg.stop()")
            pg.stop()
        }
    }
}

class VersionTest : BaseDbTest() {

    init {

        val importer = ServiceContainer("info-importer", ".*Start executing ImportHostedService.*")

        afterTest {
            println("importer.stop()")
            importer.stop()
        }

        afterSpec {
            println("afterSpec clearDB()")
            clearDB()
        }
       
       test("1"){
         "some test"
      }
}
    fun clearDB() =
            mainJdbcTemplate.update(
                    "DELETE FROM public.\"Chains\";\n" +
                            "DELETE FROM public.\"Exchanges\";" 
            )
```
As known the class start initialization from parents to class itself and all listeners are stored in list and execution of listeners are 
```kotlin
suspend fun Spec.invokeAfterSpec(): Try<Spec> = Try {
   log("invokeAfterSpec $this")

   autoCloseables.forEach { it.close() }

   val listeners = resolvedTestListeners() + Project.testListeners()
   listeners.forEach { it.afterSpec(this) }
   this
}
```
so their order in list are important. And now situation is  parents add all listeners then child add all listener. 
So my `clearDB` function will be called after `pg.stop()` and DB won't be cleared

For test
```kotlin
open class Parent : FunSpec() {
    init {
        beforeSpec {
            println("parent beforeSpec")
        }
        beforeTest {
            println("parent beforeTest")
        }
        afterTest {
            println("parent afterTest")
        }
        afterSpec {
            println("parent afterSpec")
        }
    }
}

class Child : Parent() {
    init {
        beforeSpec {
            println("child beforeSpec")
        }
        beforeTest {
            println("child beforeTest")
        }
        afterTest {
            println("child afterTest")
        }
        afterSpec {
            println("child afterSpec")
        }
        test("1"){}
    }
}
```
And order will be
ParentBeforeSpec
ChildBeforeSpec
ParentBeforeTest
ChildBeforeTest

ParentAfterTest
ChildAfterTest
ParentAfterSpec
ChildAfterSpec

But order should be 

ChildAfterTest
ParentAfterTest
ChildAfterSpec
ParentAfterSpec

JUnit, TestNG guarantee right order

**Comment by sksamuel** [comment]
I'm not sure that it's possible to know that a method invoked in a parent has also been invoked in a child. After the init{} block runs in the parent, you want the init{} block in the child to have before* methods be registered after, but after* methods be registered before. I suppose we could run the after* callbacks in reverse order.

**Comment by crazyk2** [comment]
> I suppose we could run the after* callbacks in reverse order.

Exactly what I want right now in master))

```kotlin
suspend fun TestCase.invokeAfterTest(result: TestResult): Try<TestCase> = Try {
   val listeners = this.config.listeners + spec.resolvedTestListeners() + Project.testListeners()
   listeners
      .asReversed()
      .forEach { it.afterTest(this, result) }
   this
}
suspend fun TestCase.invokeAfterInvocation(k: Int) {
   val listeners = spec.resolvedTestListeners() + Project.testListeners()
   listeners
      .asReversed()
      .forEach { it.afterInvocation(this, k) }
}
suspend fun Spec.invokeAfterSpec(): Try<Spec> = Try {
   log("invokeAfterSpec $this")

   autoCloseables.forEach { it.close() }

   val listeners = resolvedTestListeners() + Project.testListeners()
   listeners
      .asReversed()
      .forEach { it.afterSpec(this) }
   this
}

```

**Comment by sksamuel** [comment]
Ok if you PR and test it I'll merge :)

**Comment by crazyk2** [comment]
No problem.
But there is one failed test in master `SpringTestExecutionListenerTest`. I won't fix it

**Comment by sksamuel** [comment]
Is it disabled? Because all enabled tests are passing on CI

**Comment by ashishkujoy** [comment]
@crazyk2 That spec has two test and both are passing. Screenshot of lastest ci report.
<img width="1336" alt="Screenshot 2020-06-02 21 01 59" src="https://user-images.githubusercontent.com/34642693/83539242-6b848f80-a514-11ea-9d6a-1fe8dd192716.png">

**Comment by crazyk2** [comment]
![image](https://user-images.githubusercontent.com/12140191/83539591-e2fbf400-a4ff-11ea-99cb-91c725b0b7ca.png)

**Comment by crazyk2** [comment]
![image](https://user-images.githubusercontent.com/12140191/83540128-9238cb00-a500-11ea-9ce9-ab6da17a2f6d.png)

**Comment by ashishkujoy** [comment]
These test failure are not happening on master. There might be some change in your code that is causing this.

**Comment by crazyk2** [comment]
> These test failure are not happening on master. There might be some change in your code that is causing this.

Nope.
It was before my changes. and it's flacky

**Comment by ashishkujoy** [comment]
The problem here is that your changes reverse the order of listeners. In that particular spec we have some assertion in afterSpec that needs to be run after  ```afterTestClass``` method of ```DummyTestExecutionListener``` used in 
```@TestExecutionListeners``` but here reversing the listener orders cause assertion to be run before that.

https://github.com/kotest/kotest/blob/5d8f6333e9dcb0766a671faf2c73340b0d416d26/kotest-extensions/kotest-extensions-spring/src/jvmTest/kotlin/com/sksamuel/kt/spring/SpringTestExecutionListenerTest.kt#L14

https://github.com/kotest/kotest/blob/5d8f6333e9dcb0766a671faf2c73340b0d416d26/kotest-extensions/kotest-extensions-spring/src/jvmTest/kotlin/com/sksamuel/kt/spring/SpringTestExecutionListenerTest.kt#L35-L42

https://github.com/kotest/kotest/blob/5d8f6333e9dcb0766a671faf2c73340b0d416d26/kotest-extensions/kotest-extensions-spring/src/jvmTest/kotlin/com/sksamuel/kt/spring/SpringTestExecutionListenerTest.kt#L46

**Comment by ashishkujoy** [comment]
One way to fix this is create an instance of TestLIstener do this assertion in afterSpec of that.
```kotlin
object AfterSpecAssertionListener : TestListener {
   override suspend fun afterSpec(spec: Spec) {
      DummyTestExecutionListener.beforeTestClass shouldBe 1
      DummyTestExecutionListener.beforeTestMethod shouldBe 2
      DummyTestExecutionListener.beforeTestExecution shouldBe 2
      DummyTestExecutionListener.prepareTestInstance shouldBe 1
      DummyTestExecutionListener.afterTestExecution shouldBe 2
      DummyTestExecutionListener.afterTestmethod shouldBe 2
      DummyTestExecutionListener.afterTestClass shouldBe 1
   }
}
```
And then register that along with SpringListener.
```kotlin
override fun listeners(): List<TestListener> {
    return listOf(AfterSpecAssertionListener, SpringListener)
  }
```
This hack will work, **But my only worry is that reversed execution of listener for some callbacks, might create confusion for user**.

**Comment by crazyk2** [comment]
I think that order is not problem for current users because there are no issues with such theme (i mean order of test listeners execution).
And if you use Listeners with `@AutoScan` you can't control it at all.
If you use listeners like this
``` kotlin
class Test : FunSpec(){
 init{
        listener(object : TestListener {})
//or
        listener(MyTestListener, MyTestListener2)
  }
}
object MyTestListener : TestListener {
}
object MyTestListener2 : TestListener {
}
```
you can change order `listener(MyTestListener2, MyTestListener)`
But If you use inheritance you can do nothing

**Comment by crazyk2** [comment]
@ashishkujoy I made changes in more elegant way

**Comment by sksamuel** [comment]
The more I think about this the more I agree with @ashishkujoy that we shouldn't be making any guarantees on the execution order of callbacks of the same type.
There's @Autoscan, there's ones registered at in project conf, we have callbacks supported at many levels.
I would just say, pull your listener code out of the parent class into a standalone class, and then it doesn't matter.

**Comment by crazyk2** [comment]
If you don't guarantee then what the difference between reverse order and vice versa? Just merge my PR and it would be nice for me. Order for rest users is not guaranteed))) By the way all tests are passed that mean I don't break behavior

**Comment by sksamuel** [comment]
I can't just merge a PR because it's good for one person :)

**Comment by sksamuel** [comment]
I'd be happy to add a flag to project config that reverses the order. A flag that is false by default, but you can change to true to get the behavior you want.

**Comment by crazyk2** [comment]
> I'd be happy to add a flag to project config that reverses the order. A flag that is false by default, but you can change to true to get the behavior you want.

Do you think it's good idea?
It would be compromise for me because add separate listener object in each class isn't best idea.

**Comment by sksamuel** [comment]
I think that's a good way to do it.
