### ISSUE TITLE
redundant call of *Spec callbacks and inheritance

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1482]
**Which version of Kotest are you using**
Master
```kotlin
private val accum: StringBuilder = StringBuilder()

open class TestListenerAfterParentTest : FunSpec() {
   init {
      beforeSpec {
         accum.append("a")
      }

      afterSpec {
         accum.append("d")
      }
   }
}

class TestListenerAfterChildTest2 : TestListenerAfterParentTest() {
   init {
      beforeSpec {
         accum.append("b")
      }

      afterSpec {
         accum.append("c")
      }

      afterProject {
         accum.toString() shouldBe "abcd"
      }

      test("order of after* callbacks execution should be from child to parent") { }
   }
}
```

```
Expected :"abcd"
Actual   :"abcdad"
```
Parent do not have tests but still run listener.
If made change 
```
      var results: Try<Map<TestCase, TestResult>> = emptyMap<TestCase, TestResult>().success()
      if (spec.rootTests().isEmpty()) return results
```
then TestListener won't run

**Comment by sksamuel** [comment]
Is this really a bug?
What if you want a common superclass that executes some logic, like starts up a database, that you want all the child specs to inherit ?

**Comment by crazyk2** [comment]
> What if you want a common superclass that executes some logic, like starts up a database, that you want all the child specs to inherit ?

And where is a problem?
All works fine for me and all tests passed.

**Comment by sksamuel** [comment]
Because spec.rootTests will be empty in the parent, but you still want the
parent's listeners to execute.

**Comment by crazyk2** [comment]
Listeners will be executed because Child initialized after Parent initialized.
And if you have code in `init{}` block it will be executed. If you have code outside `init` block for example `override fun defaultTestCaseConfig()` child has this `override` too if not override by itself.
I don't see problem. Maybe you give me example or highlights

**Comment by sksamuel** [comment]
I see, you don't want the parents being executed twice.
Change the parent class to abstract.

**Comment by crazyk2** [comment]
> I see, you don't want the parents being executed twice.
> Change the parent class to abstract.

It will work but i don't have a abstract member of class. 
Not everyone will guess to do like you said. 
And if compare with JUnit and TestNG you can do like I do without `abstract` parent class and listeners won't be called twice

**Comment by sksamuel** [comment]
JUnit is method based so not applicable here.

The behavior you're seeing is the right behavior. You have two test classes, they're both being instantiated. The listeners run in one, they run in the other.

If you don't want that, you simply change the parent spec to be abstract, which makes sense, as the parent class is not a test suite for you.

**Comment by crazyk2** [comment]
> JUnit is method based so not applicable here.

Maybe you are right. But you cannot avoid comparison with JUnit in java\kotlin world from developers and TestNG from QA Automators.

JUnit and others try to create standart in tests (you know about it because use opentest4j) so I think it would be nice and less confusing if kotes will be similar with known tools much more as possible especially if it costs nothing and  break nothing in Kotest

**Comment by sksamuel** [comment]
I don't agree that it costs nothing.
If a user **wants** the behavior you're currently seeing, and we change it, how do they then do it?

In other words, if you don't want the parent callbacks, use abstract. If you do want them, they leave it as it is.

If we change the behavior, and you want the parent callbacks, you can't do it anymore.

**Comment by crazyk2** [comment]
Ok. Then docs should be updated with this case. I think we should create docs with all unobvious cases

**Comment by crazyk2** [comment]
Close this issue or label with docs and close pull request

**Comment by sksamuel** [comment]
Like the other thread, I would be happy with a flag, `executeCallbacksOnEmptySpec` default to true. Set it to false, and you get the behavior you want.

**Comment by reevn** [comment]
Edit: I've moved my comment into a separate issue, as it's a different issue that is only vaguely related to this issue.

https://github.com/kotest/kotest/issues/1584

**Comment by crazyk2** [comment]
@sksamuel So finally you do exactly I want if spec (including parent spec) doesn't have test (in your terms _active_ tests) we return from function 
```kotlin
   private suspend fun runTestsIfAtLeastOneActive(spec: Spec): Try<Map<TestCase, TestResult>> {
      val roots = spec.rootTests()
      val active = roots.any { it.testCase.isActive() }
      return if (active) runTests(spec) else emptyMap<TestCase, TestResult>().success()
   }
```
4f97e78758b7fa65a3a8fa3bfc88d08e6cc754b5
Now there is no need to use `abstract` for parent spec/
Please close issue

**Comment by OndraZizka** [comment]
I'm facing the same issue. Kotest 5.8.1 executes the callbacks even for an `abstract` class.

```kotlin
abstract class IntegrationSpec: StringSpec() {
    init {

        beforeSpec {
            localEnv.start(useFixedPorts = false)
            ...
        }
        afterSpec {
            localEnv.close()
        }

        afterTest { ... }
```

Based on what you stated above, this is a bug?

> If you don't want that, you simply change the parent spec to be `abstract`.


The problem is that it the run of the abstract class fails on `lateinit` var usage. Either Kotest doesn't run the `beforeSpec()`, or a race condition after an upgrade of Testcontainers.

```
kotlin.UninitializedPropertyAccessException: lateinit property measurementBundleKafkaProducer has not been initialized
	at com.nexxiot.kbpoc.ingress.IntegrationSpec.getMeasurementBundleKafkaProducer(IntegrationSpec.kt:43)
	at com.nexxiot.kbpoc.ingress.IntegrationSpec$2.invokeSuspend(IntegrationSpec.kt:62)
	at com.nexxiot.kbpoc.ingress.IntegrationSpec$2.invoke(IntegrationSpec.kt)
	at com.nexxiot.kbpoc.ingress.IntegrationSpec$2.invoke(IntegrationSpec.kt)
	at io.kotest.core.spec.Spec$afterSpec$2.afterSpec(Spec.kt:399)
	at io.kotest.engine.spec.SpecExtensions.afterSpec-gIAlu-s(SpecExtensions.kt:78)
	at io.kotest.engine.spec.interceptor.instance.AfterSpecCallbackInterceptor.intercept-0E7RQCE(AfterSpecCallbackInterceptor.kt:26)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invokeSuspend(SpecInterceptorPipeline.kt:47)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke(SpecInterceptorPipeline.kt)
	at 
```

**Comment by OndraZizka** [comment]
As a workaround, I added:

```
    beforeSpec { spec ->
          if (!anyTestEnabled(spec)) { return@beforeSpec }

    // Same for afterSpec

    private fun anyTestEnabled(spec: Spec): Boolean {
        val active = spec.rootTests().any { it.config?.enabled == true }
        return active
    }
```
