### ISSUE TITLE
Nested tests hierarchy or parent name in gradle report

### ISSUE THREAD

**Issue by razvn** [kotest/kotest#1483]
In 4.0.6 when using nested tests like:

ex: FreeSpec
```kotlin
class FreeSpecTest : FreeSpec() {
    init {
        "A" - {
            "a-1" {
                true shouldBe true
            }
            "a-2" {
                true shouldBe true
            }
            "a-3" {
                true shouldBe true
            }
        }
        "B" - {
            "C" - {

                "c-1" {
                    true shouldBe true
                }
                "c-2" {
                    true shouldBe true
                }
            }
            "b-1" {
                true shouldBe true
            }
        }
    }
}
```
It shows nice in IntelliJ
![Kotest-IntelliJHierachy](https://user-images.githubusercontent.com/745873/83570677-c4f5ba00-a526-11ea-8daf-57848e7c3191.png)
But the gradle report is bad as it does not contain not hierarchy 
![KoTest-Freespec-gradlereport](https://user-images.githubusercontent.com/745873/83570760-e787d300-a526-11ea-8d45-bf4cc6320637.png)

Same thing happens with others types that supports nested (WordSpec, FeatureSpec).

Same test in JUnit

```kotlin
lass JunitTest {

    @Nested
    inner class A {
        @Test
        fun `a-1`() {
            assertTrue(true)
        }
        @Test
        fun `a-2`() {
            assertTrue(true)
        }
        @Test
        fun `a-3`() {
            assertTrue(true)
        }
    }

    @Nested
    inner class B {
        @Nested
        inner class C {
            @Test
            fun `c-1`() {
                assertTrue(true)
            }
            @Test
            fun `c-2`() {
                assertTrue(true)
            }
        }

        @Test
        fun `b-1`() {
            assertTrue(true)
        }
    }
}
````
Gives a view of different classes:
![KoTest-junit-report](https://user-images.githubusercontent.com/745873/83571029-536a3b80-a527-11ea-9009-7fc292628618.png)
and have to enter in each one to see each one's tests:
![kotest-junit-report-detail](https://user-images.githubusercontent.com/745873/83571087-6b41bf80-a527-11ea-96c7-83f71e43168b.png)

I don't know if Kotest can implement same hierarchy but it should at least have the name of the parent name as prefix like: "A-a-1" otherwise it loses the interest as in each test name you have to copy the parent name to know what you are testing.Imagine in FeatureSpec if you only have the scenario without knowing to which Feature it releates, it's messy.

Same go for Junit Testsuite xml report (well I guess they are linked).

**Comment by sksamuel** [comment]
The issue is gradle doesn't support hierarchical reports (been open tickets for 2 years). We can't include the parent name in the child test because then in intellij you're going to see the parent name repeated at every level.

We might be able to do something if we could detect we were running inside intellij or not and alter the behavior.

**Comment by razvn** [comment]
Ok, I have to move back to Junit as the team is not happy with the drawbacks. we are using the html report in our GitLab Pages and the xml in our Merge Requests. Without the proper structure they are useless. I'll keep the kotest asertions as they are great. Thanks for the great work.

**Comment by sksamuel** [comment]
You don't have to nest your tests. If you use FunSpec, ShouldSpec or StringSpec the tests are top level and work like junit. You still benefit from all the other things kotest has to offer. I personally always use FunSpec.

**Comment by mitasov-ra** [comment]
@sksamuel
FYI
Right now I can see in `afterTest` callback in Gradle information about whole test hierarchy.
The info about test hierarchy stored in `TestDescriptor.parent` property.

I'm going to go deeper and check, is there needed info in Gradle test report generators or not.

My Gradle version is 6.8.1

P.S. Anyway, Gradle holds test hierarchy now, so theoretically making some kind of plugin for report generation is now possible.

**Comment by sksamuel** [comment]
@mitasov-ra let me know what you find 👍🏼
