### ISSUE TITLE
Arb.bind<T>() calls the incorrect constructor

### ISSUE THREAD

**Issue by sgarfinkel** [kotest/kotest#1487]
**Which version of Kotest are you using**
4.0.6

**Description**
Kotest's `Arb.bind<T>()` calls the incorrect constructor here: https://github.com/kotest/kotest/blob/befa71c81135a7afb66db5330d1a3b4fd367c0f1/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/jvmbind.kt#L20

The first constructor returned _might_ be the primaryConstructor, but may not be. Also the set of inputs is derived directly from the primaryConstructor in the code before it. This bug is particularly irritating when mixing Kotest and kotlinx.serialization, because kotlinx.serialization adds a secondary constructor.

**Solution**
Replace the above line with `kclass.primaryConstructor!!.call(*values.toTypeArray())` and add some documentation stating that `Arb.bind<T>()` requires `T` to be a class (the code checks if it's a data class but technically this is not required) with a primaryConstructor, and that this method will _always_ call the primaryConstructor.

**Comment by sksamuel** [comment]
Fixed in master.
