### ISSUE TITLE
Merge to an Exhausive of a superclass

### ISSUE THREAD

**Issue by Octogonapus** [kotest/kotest#1497]
I want to `merge()` two `Exhaustive` gens into one with the common supertype of the two instances I am merging. For example, If I have one `Exhaustive` of type `B : A` and another of type `C : A`, I'd like to be able to merge them into one with type `A`.

I have been using this function to accomplish this:
```kotlin
fun <A, B : A, C : A> Exhaustive<B>.merge(other: Exhaustive<C>): Exhaustive<A> =
        object : Exhaustive<A>() {
    override val values: List<A> = this@merge.values.zip(other.values)
            .flatMap { listOf(it.first, it.second) }
}
```

Then I can use it like so:
```kotlin
internal val allLongs = listOf(
        Operand.LongType.ConstLong(0),
        Operand.LongType.ConstLong(1),
        Operand.LongType.RuntimeLong
).exhaustive()

internal val allDoubles = listOf(
        Operand.DoubleType.ConstDouble(0.0),
        Operand.DoubleType.ConstDouble(1.0),
        Operand.DoubleType.RuntimeDouble
).exhaustive()

internal val allCategory2Values = allLongs.merge(allDoubles)
```

The Kotlin compiler can infer the common supertype. Should I make a PR for this addition?

**Comment by sksamuel** [comment]
Yes please. We can include this in the forth coming 4.1 release.
