### ISSUE TITLE
JSON matchers should match on nullable strings

### ISSUE THREAD

**Issue by klesniewski** [kotest/kotest#1504]
I am really happy you have added JSON matchers - they are really useful! However, I found the interface a bit clumsy when my JSON field is nullable and I would like to make a small change to improve it.

Currently, testing nullable JSON fields looks as follows:
```kotlin
val json: String? = getJson()
json shouldNotBe null
json!! shouldMatchJson """{"hello":"world"}"""
```
If changing the matcher and its infix functions to match on nullable string, it would be more concise:
```kotlin
val json: String? = getJson()
json shouldMatchJson """{"hello":"world"}"""
```
In my view, it is a small, non-breaking change, but would make Kotest a bit nicer to use. What do you think?

**Comment by sksamuel** [comment]
I think that's a good change, the matcher can check for both nullability
and equality at the same time.

**Comment by klesniewski** [comment]
Seems like it is being addressed with https://github.com/kotest/kotest/pull/1318. I will add some comments to the PR.

**Comment by LeoColman** [comment]
If this is already addressed, can we close this issue?

**Comment by klesniewski** [comment]
Not sure what is the approach in your project, but for me it would be normal to close it only once changes are released or at least merged to master. This is not the case and the mentioned PR does not even implement it fully yet.

**Comment by SerVB** [comment]
By the way, instead of

```kt
val json: String? = getJson()
json shouldNotBe null
json!! shouldMatchJson """{"hello":"world"}"""
```

you can use

```kt
val json: String? = getJson()
json.shouldNotBeNull()
json shouldMatchJson """{"hello":"world"}"""
```

`shouldNotBeNull` has a contract so after it `json` will be smart-casted to a `String`.

**Comment by klesniewski** [comment]
Hey @SerVB, thank you very much for implementing this! Also thank you for the tip on `shouldNotBeNull()`. I didn't know about it before and it will surely help me to make some tests more elegant ;) Unfortunately, it does not work in all the cases. If class is defined in another module, then Kotlin refuses to smart-cast with message

> Smart cast to 'MyClass' is impossible, because 'myProperty' is a public API property declared in different module

That's why I am happy for the changes you have implemented :)
