### ISSUE TITLE
Focus not working in WordSpec

### ISSUE THREAD

**Issue by patelm5** [kotest/kotest#1515]
**Which version of Kotest are you using**
4.0.5 

Related to: [1376](https://github.com/kotest/kotest/issues/1376), I believe the same issue is present in WordSpec.

**Comment by sksamuel** [comment]
I've added a test for word spec focus and it looks fine. Can you provide a concrete example that fails.

**Comment by patelm5** [comment]
I was able to reproduce your results, so it must be a mistake on my side with versions. Thanks for the reply. Closing.
