### ISSUE TITLE
Filtering tests by tag happens after beforeSpec method is invoked

### ISSUE THREAD

**Issue by dgm90** [kotest/kotest#1516]
Original:
I use tags to filter tests when running on CI. My problem is that if a test is derived from a BaseTest class, that has an overridden `beforeSpec` method (aka setup for all tests), then this method is invoked even if the test itself is filtered out by tag. Is it possible to filter out tests firstly and only then run the `beforeSpec` method? I've failed to find an answer in documentation.

Update:
After discussion with @sksamuel, I've tried to use `io.kotest.core.annotation.Tags` and this is the result:

1. It works good if you explicitly exclude a tag (kotest.tags.exclude=Tag_A) in the test run. In this case the whole spec with @Tags("Tag_A") is skipped and beforeSpec is not executed.
2. However, if you run with kotest.tags.include=Tag_B, then:
    2.a for test with no @Tags annotation, the test itself will be ignored, but the beforeSpec will be executed.
    2.b the test with @Tags("some_other_tag") will be ignored and its beforeSpec won't be executed.

Seems like 2.a case is a bug and should be fixed.

**Comment by sksamuel** [comment]
Fixed in master. Will be included in 4.1.0 final.

**Comment by sschuberth** [comment]
I'm seeing the 2.a case happening again with Kotest 5.1.0, is there a regression?
