### ISSUE TITLE
IntelliJ Idea doesn't detect tests after upgrading to 4.1.0

### ISSUE THREAD

**Issue by imanushin** [kotest/kotest#1524]
Kotlin: 1.3.72
Kotest: 4.1.0

After kotest upgrading from ```4.0.6``` to ```4.1.0```, IntelliJ Idea doesn't show ```Run Test``` hint near the class word at the text editor. Moreover, even if I do right click on file at the Project panel, the menu items for test runs are missing there.

However right click on Java package can start all tests in the package, which can be temporary workaround.

**Comment by ashishkujoy** [comment]
@imanushin This change is intentional. Please here https://github.com/kotest/kotest/blob/master/blog/release_4.1.md
