### ISSUE TITLE
The incorrect count of tests in allure

### ISSUE THREAD

**Issue by SergKhram** [kotest/kotest#1527]
When i use AllureListener for many test cases - after executing i see less count then it need to be
for example I execute 12 test cases ( 2 Spec classes, where i have tables with 6 rows - each row is the test case)
But in allure i see only 11 test cases
When I debug it I see, that when I'm in afterTest's function - some cases(in this situation only one is absent) don't in Allure storage - why?

![Capture](https://user-images.githubusercontent.com/49818537/85827300-ae8df780-b78e-11ea-8ce2-4b8cbf91ef15.PNG)
![Capture2](https://user-images.githubusercontent.com/49818537/85827384-df6e2c80-b78e-11ea-971b-02355be1450e.PNG)

And in target folder i see only 11 files of cases
![Capture3](https://user-images.githubusercontent.com/49818537/85827572-34aa3e00-b78f-11ea-9311-e2175c979cbc.PNG)

**Comment by SergKhram** [comment]
I see my case in uuids val, but there is not in AllureStorage - you can see on screen
![Capture5](https://user-images.githubusercontent.com/49818537/85828589-6e7c4400-b791-11ea-8208-e7d19ddf18d8.PNG)

**Comment by SergKhram** [comment]
the more threads we use, the more tests disappear from the report

**Comment by sksamuel** [comment]
I wonder if the allure extension is not thread safe.

**Comment by SergKhram** [comment]
@sksamuel i don’t think so, because I use allure2 with kotlintest 3.4.2 and don’t have these problems ( never) and with clear junit 5 we don’t have these problems

**Comment by SergKhram** [comment]
Сheck this bug, please

**Comment by SergKhram** [comment]
@sksamuel  @Kerooker ping

**Comment by SergKhram** [comment]
@sksamuel @LeoColman  ping. Please check the bug, we can't see some failed tests and it is a very big problem

**Comment by sksamuel** [comment]
You can always make a PR to fix the issue if you are urgently needing this. Open source projects are community efforts.

**Comment by sksamuel** [comment]
Which isolation mode are you using ?

**Comment by SergKhram** [comment]
@sksamuel SingleInstance

**Comment by SergKhram** [comment]
@sksamuel ping

**Comment by sksamuel** [comment]
I think we can add a setting to the allure plugin, which allows you to control whether you want to include containers as tests.

**Comment by sksamuel** [comment]
See https://github.com/kotest/kotest/pull/1619

**Comment by sksamuel** [comment]
In master, you now need to add the `AllureTestReporter` manually as a listener, but you can configure it to ignore container level tests (which is what you want).

Will be included in 4.2.0
