### ISSUE TITLE
DescribeSpec isn't working as intended with the plugin

### ISSUE THREAD

**Issue by PedroDBFlores** [kotest/kotest#1528]
### Steps to reproduce

1. Have Kotest 4.1.0 and Kotest IntelliJ plugin version 1.0.2
2. Have the class described in the block below
3. On the gutters, try to run a specific it from any of the describes, or even any of the describes

```
class CantRunSpecificItTest: DescribeSpec({
    describe("A") {
        it("1") {
            println(1)
        }
        it("2") {
            println(2)
        }
    }
    describe("B") {
        it("4") {
            println(4)
        }
        it("5") {
            println(5)
        }
    }
    describe("C"){
        it("should fail"){
            fail("OOPS")
        }
    }
})
```

### Expected
To see the value `1, 2, 4 or 5` printed on my console, indicating that only that specific test or describe block has been run separately.

### Actual
No output of values occurs on the console, even on the `C` describe when running individually it doesn't fail.

Thanks for your attention, if more information is needed I'm here to help.

**Comment by sksamuel** [comment]
Fixed in master. Will be released as 4.1.1
