### ISSUE TITLE
Data driven tests should utilise data classes and automatically register test names (ala rollup)

### ISSUE THREAD

**Issue by zeitlinger** [kotest/kotest#1537]
inspired by the common practice in [go](https://github.com/golang/go/wiki/TableDrivenTests) - I would like to suggest to use data classes as the recommended way for data/table driven tests: 

It is already possible to do manually 

1. but a short helper method would make the code more concise (see below)
2. I'd also suggest to change the description to use this pattern as the default
3. by using the helper method it's hopefully also possible to create gutter icons in the intellij plugin to run an individual row

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.core.spec.style.scopes.FreeScope
import io.kotest.core.test.TestContext
import io.kotest.matchers.shouldBe

class DataDrivenDataClass : FreeSpec({
    "the very manual way" - {
        data class TestCase(val a: String)
        listOf(
            TestCase("a"),
            TestCase("b")
        ).forEach {
            it.a - {
                it.a.length shouldBe 2
            }
        }
    }

    "nicer" - {
        data class TestCase(val a: String)
        forAll(listOf(
            TestCase("a"),
            TestCase("b")
        ), TestCase::a) {
            it.a.length shouldBe 2
        }
    }
})

suspend fun <T> FreeScope.forAll(testCases: List<T>, name: (T) -> String, body: (TestContext).(T) -> Unit) {
    testCases.forEach { tc ->
        val name1 = name(tc)
        name1 {
            body(this, tc)
        }
    }
}
```

**Comment by zeitlinger** [comment]
I think I like this option even better

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.core.spec.style.scopes.FreeScope
import io.kotest.core.test.TestContext
import io.kotest.matchers.shouldBe

class DataDrivenDataClass : FreeSpec({
    "with HasName interface" - {
        data class TestCase(override val name: String, val str: String, val expectedLength: Int) : HasName
        forAll(listOf(
            TestCase(
                name = "first test",
                str = "a",
                expectedLength = 1
            ),
            TestCase(
                name = "second test",
                str = "bb",
                expectedLength = 2
            )
        )) {
            it.str.length shouldBe it.expectedLength
        }
    }
})

interface HasName {
    val name: String
}

suspend fun <T : HasName> FreeScope.forAll(testCases: List<T>, body: (TestContext).(T) -> Unit) {
    testCases.forEach { tc ->
        tc.name {
            body(this, tc)
        }
    }
}
```

**Comment by zeitlinger** [comment]
this one is even better

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.core.spec.style.scopes.FreeScope
import io.kotest.matchers.shouldBe

class FreeSpecTest : FreeSpec() {

    init {
        "for all" - {
            data class TestCase(val string: String, val length: Int)
            forAll(mapOf(
                "zero" to TestCase(string = "", length = 0),
                "fail" to TestCase(string = "a", length = 1)
            )) {
                it.string.length shouldBe it.length

                "sub" - {
                    "a" shouldBe "a"
                }
            }
        }
    }
}

suspend fun <T> FreeScope.forAll(testCases: Map<String, T>, body: suspend (FreeScope).(T) -> Unit) {
    testCases.forEach { entry ->
        entry.key - {
            body(this, entry.value)
        }
    }
}

```

**Comment by sksamuel** [comment]
I'm not keen on adding a feature that's limited to one spec style only. So far all specs are functionally equivalent and if we start diverging from that, you'll have some features in one, some in another and so on.

You are looking for two things here. One - using data classes rather than "rows" in table testing, and an easy way to have data driven tests be registered as separate test cases.

The former we need to find a way for this to work in all specs. By nesting it inside a test itself as you have done here, you need to give the outer test a name, which is maybe redundant (maybe not).

One approach would be to add an extension method on Spec that uses the registerRootTest method to add the test names at the top level, this would then work for all specs.

**Comment by zeitlinger** [comment]
> I'm not keen on adding a feature that's limited to one spec style only. 

Yes, this is understandable. I can just say from my experience with go that having data tests as nested tests is very useful.
My naive suggestion would be to allow nested tests for all specs - but I don't know what complications that would bring.

> using data classes rather than "rows" in table testing

correct - to take advantage of named and default parameters. It's also more readable, because test case definitions very often span several lines

> and an easy way to have data driven tests be registered as separate test cases.

- it makes it easier to see which test is failing (a clue would also do that)
- to debug exactly the failing test case

> you need to give the outer test a name, which is maybe redundant (maybe not).

the outer test is usually the test subject method (the method you want to test) - so it's both natural and useful

> One approach would be to add an extension method on Spec that uses the registerRootTest method to add the test names at the top level, this would then work for all specs.

I would consider this a workaround if it's not possible to allow nested tests everywhere

**Comment by sksamuel** [comment]
Just thinking out loud. Each nested test context already has a distinct type. We could add an interfaced `NestedContext` or something, which defines a method `registerNestedTest` which tooling (like an enhanced data driven testing that uses data classes) can use to register a test at any level in a spec style agnostic way. Each test context can implement this interface, and then the data driven testing is defined as an extension on that.

**Comment by zeitlinger** [comment]
> Just thinking out loud. Each nested test context already has a distinct type. We could add an interfaced `NestedContext` or something, which defines a method `registerNestedTest` which tooling (like an enhanced data driven testing that uses data classes) can use to register a test at any level in a spec style agnostic way. Each test context can implement this interface, and then the data driven testing is defined as an extension on that.

Sounds good.
Would the user code be the same as in my PR?

**Comment by sksamuel** [comment]
What was the reason for the map? I think the map makes it a bit clunky tbh.

**Comment by zeitlinger** [comment]
The reason for the map: give the test a name

Alternatives
1. Let the data class implement an interface, e.g. Named test case
2. Use reflection to get the name property, falling back to toString

**Comment by sksamuel** [comment]
I'm not sure it warrants support in the framework when you can create the
test name yourself inside the data test loop.

I like the idea of data classes though.

**Comment by zeitlinger** [comment]
That's a question of how opinionated you want to be.
IIRC, you also said that some test styles don't allow nested scopes, so the
test cases would have to be added at the top - this could clutter the code.
BTW, go has taken the approach to just have a convention for table tests,
without any framework support - also works well, because nested tests are
possible anywhere.

**Comment by sksamuel** [comment]
How does it look in go ?

**Comment by zeitlinger** [comment]
https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

**Comment by sksamuel** [comment]
I don't understand that, it's too heavy on the Go syntax for me to
understand it. What's the tl'dr?

**Comment by zeitlinger** [comment]
the tl'dr:

translated to kotlin, it would look like my first example in the issue:

```kotlin
    "the very manual way" - {
        data class TestCase(val a: String)
        listOf(
            TestCase("a"),
            TestCase("b")
        ).forEach {
            it.a - {
                it.a.length shouldBe 2
            }
        }
    }
```

**Comment by sksamuel** [comment]
So the only part that I haven't got an immediate answer for, is the syntax for registering the test in a simple way.

Something like this perhaps ?

```
    "the very manual way" - {
        data class TestCase(val a: String)
        listOf(
            TestCase("a"),
            TestCase("b")
        ).forEach {
            it.a.testCase {
                it.a.length shouldBe 2
            }
        }
    }
```

Or

```
    "the very manual way" - {
        data class TestCase(val a: String)
        listOf(
            TestCase("a"),
            TestCase("b")
        ).forEach {
            test(it.a) {
                it.a.length shouldBe 2
            }
        }
    }
```

**Comment by sksamuel** [comment]
The map would be sufficent, as in

```
    "the very manual way" - {
        data class TestCase(val a: String)
        mapOf(
            "test 1" to TestCase("a"),
            "test 2" to TestCase("b")
        ).dataTest {
           it.a.length shouldBe 2
        }
    }
```

The `dataTest` method would know to use the key to register a test at the current scope. The name could be forAll possibly, if there's no clash with anything else on a map.

**Comment by zeitlinger** [comment]
> The `dataTest` method would know to use the key to register a test at the current scope. 

I like the idea - it's easy to understand.

> The name could be forAll possibly, if there's no clash with anything else on a map.

It wouldn't (just checked) - but it could be confused with `forEach`

**Comment by sksamuel** [comment]
Yeah I suppose it could be, do you have a suggestion for another name?
forRows ?
forValues?
SomethingElseCompeltey.

**Comment by zeitlinger** [comment]
Something that has "test" in the name, such as tableTest or dataTest.

**Comment by sksamuel** [comment]
In the branch feature/dd I have this working:


```kotlin

class FreeSpecDataTest : FreeSpec() {
   init {
      data class PythagTriple(val a: Int, val b: Int, val c: Int)

      "nested data test happy path" - {
         rollup(
            PythagTriple(3, 4, 5),
            PythagTriple(6, 8, 10),
            PythagTriple(9, 12, 15),
         ) { (a, b, c) ->
            a * a + b * b shouldBe c * c
         }
      }

      "nested data test with failure" - {
         rollup(
            PythagTriple(9, 12, 12),
         ) { (a, b, c) ->
            shouldThrowAny {
               a * a + b * b shouldBe c * c
            }
         }
      }
   }
}
```

Using the name rollup (can be anything), it will register each data class as a separate test (using the to string output of the data class).

![image](https://user-images.githubusercontent.com/743706/92316518-bfdb5780-efba-11ea-9373-6b776b4476dc.png)

**Comment by zeitlinger** [comment]
I like the design :+1: 

1. it starts with what you're trying to do (`rollup` - a data test) instead of an extension method
2. I like that you can now decide if you want to give the test a name - it has proven to be very valuable for maintainable code, but people should decide for themselves
3. with this design, it should be possible to use `forAll`, as in the other data tests (not exactly sure about the overloads here)
4. maybe rename `addTest` to `run` (as in go)

**Comment by sksamuel** [comment]
The problem with using forAll is that this method accepts a T and so
literally accepts any type. It might clash with prop tests.

Rollup or something like that indicates you want each object to be
generated as a separate test.

Perhaps two names. One for adding each obj as a test and one for not.

As for addTest. That's just an internal thing that the user won't see.

**Comment by zeitlinger** [comment]
Just tried it out on the branch.

`forAll` works for both - if you use both in the same method, it looks like this:

```kotlin
       "nested data test happy path" - {
         io.kotest.data.forAll(row("a")) { a ->
            a shouldBe "a"
         }
         forAll(
            PythagTriple(3, 4, 5),
            PythagTriple(6, 8, 10),
            PythagTriple(9, 12, 15),
         ) { (a, b, c) ->
            a * a + b * b shouldBe c * c
         }
      }
```

Still, `forAll` is my favorite, something like `dataTeest` second. I don't think `rollup` is intuitive.

Also don't like to have different names - only makes it harder to understand.

**Comment by sksamuel** [comment]
I agree forAll is better. We can use that. Need some way of doing it
without adding in the test names though.

**Comment by sksamuel** [comment]
I have renamed to `forAll`, added `forNone` and added support for the other nested specs, and added tests.
Please review the PR here: https://github.com/kotest/kotest/pull/1721

**Comment by zeitlinger** [comment]
@sksamuel just saw that the Go plugin has just extended support for table driven tests to add gutter icons for each test: https://youtrack.jetbrains.com/issue/GO-4811

If you give me some hints, I'd try to add the same functionality for kotest.

**Comment by sksamuel** [comment]
Might be hard, as you only have the method names to go by. You could look
for "forAll" inside a test case, and then make the assumption that's a data
test. But any other forAll usage would be affected to.
I think for this to work it needs to have it's own unique method name, like
dataTestForAll or something not as wordy as that.
