### ISSUE TITLE
Complex structures deep comparison

### ISSUE THREAD

**Issue by ov7a** [kotest/kotest#1543]
I'm using kotest 4.1.1.

I think it would be nice to have deep recursive comparison in `eq` assertion by default. It is already checking for type and doing a smart comparison for upper lever. I think the same should be done for nested elements as well.

Consider this code snippet:
```
arrayOf(1,2,3) shouldBe arrayOf(1,2,3) //works fine
mapOf("1" to arrayOf(1,2,3)) shouldBe mapOf("1" to arrayOf(1,2,3)) //fails
```
Two arrays are equal, but if we wrap them in a map, they suddenly don't. That happens because `eq` checks for type, and compares `actual` and `expected` as Maps by simple `==`. In case of two arrays, the `DefaultEq` with `makeComparable` are used (BTW, why `makeComparable` instead of calling `contentEquals` for arrays?). 

That behaviour is a bit counter-intuitive. I think that can be solved if smart comparisons will be used for all container elements. As a bonus, a more detailed assertion message can be generated. Consider this code snippet:
```
val actual = mapOf(
    "1" to mapOf(
        "2" to mapOf(
            "3" to mapOf(
                "4" to "value"
            )
        )
    )
)

val expected = mapOf("1" to mapOf("2" to mapOf("3" to mapOf("4" to "value2"))))
actual shouldBe expected
```
It fails with `Values differed at keys 1`. With recursive comparison it can be changed to full path like `Values differed at key 1.2.3.4`. It would also be very very handy when two jsons are compared:
```
val actual = """{"1": {"2": {"3":{"4":"value"}}}}"""
val expected = """{"1": {"2": {"3":{"4":"value2"}}}}"""
actual shouldMatchJson expected
```
Right now it fails with no details at all.

**Comment by ashishkujoy** [comment]
Fixed in release/4.1.x branch, will be released with 4.1.3

**Comment by ashishkujoy** [comment]
Released with 4.1.3

**Comment by ov7a** [comment]
@ashishkujoy Wow, thank you!

Unfortunately, it seems like there is a bug related to nulls:
```
val mapWithNull = mapOf("null" to null)
val mapWithNullCopy = mapOf("null" to null)
mapWithNull shouldBe mapWithNullCopy //fails with "null cannot be cast to non-null type kotlin.Any"
```

I also have [a more complex testCase](https://github.com/ov7a/kotlin-asserts-comparison/blob/master/src/test/kotlin/common/TestData.kt#L34):
```
val complexStructure = mapOf(
    "array" to arrayOf(1, 2),
    "list" to listOf(1, 2, 3),
    "bytearray" to byteArrayOf(1, 2, 3, 4),
    "int" to 2,
    "string" to "sss",
    "map" to mapOf(
        "2" to 2,
        "lissst" to listOf("1", 2, "5", null, mapOf("1" to byteArrayOf(1, 2, 3, 5)), setOf(listOf(1, 2, 3))),
        "bytearray" to byteArrayOf(1, 2, 3, 5)
    ),
    "null" to null
)

//Copy-paste to avoid compare by reference
val complexStructureCopy = mapOf(
    "array" to arrayOf(1, 2),
    "list" to listOf(1, 2, 3),
    "bytearray" to byteArrayOf(1, 2, 3, 4),
    "int" to 2,
    "string" to "sss",
    "map" to mapOf(
        "2" to 2,
        "lissst" to listOf("1", 2, "5", null, mapOf("1" to byteArrayOf(1, 2, 3, 5)), setOf(listOf(1, 2, 3))),
        "bytearray" to byteArrayOf(1, 2, 3, 5)
    ),
    "null" to null
)

complexStructure shouldBe complexStructureCopy
```
which fails with Kotest 4.1.3 due to absent null and bytearray `eq` overrides. 

I think this type of comparison should be supported for all collections, arrays, iterables, etc. With Kotest 4.1.3 
```
val actual = listOf(arrayOf(1,2,3))
val expected = listOf(arrayOf(1,2,3))
actual shouldBe expected
```
also fails, however it almost the same case as map of arrays.

What about full path for different keys I mentioned in the first post? Should I create a separate issue for that?

**Comment by jalagar** [comment]
@ashishkujoy I am getting a flaky comparison when having deeply nested dictionaries with a combination of various types. It does not happen when using https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-equals.html

The shape of the map looks something like:
```
mapOf(
      "id" to "123",
      "from" to "abc",
      "to" to null,
      "price" to mapOf("usd" to 123, "native" to mapOf("unit" to 123))
  ),
```
with randomized strings for each of the values
