### ISSUE TITLE
Option to strip whitespace from test names

### ISSUE THREAD

**Issue by lgtout** [kotest/kotest#1545]
This feature idea arises from the limitations of StringSpec style.  And I don't think what's described below is already covered by any other existing styles.

The motivation is this:

The developer doesn't want to nest tests in a tree, because understanding such tests can require much visual scanning up and down through the tree of nested tests, paying very close attention to indentation, in order to figure out what the state of the SUT is when the test's action is finally performed.

However, the developer likes the readability of long test names (only the name) being broken into multiple nested segments in the IDE, each segment on a separate line immediately after the previous segment.  The same is desired for appearance in the IntelliJ plugin tool window, and in the run output window.

In the IDE it might boil down to something like this:

```
"Given blah blah blah blah blah blah" +
    "When blah blah blah" +
        "Then blah blah blah"  {
    TODO()
}
"Given blah blah blah blah blah blah" +
    "When blah blah blah" +
        "Then shake shake shake" {
    TODO()
}
```

Note how the second test name differs only in the third line/segment.
Also, note that my using the "Given/When/Then" words in the segments is irrelevant to the style.  The style would be insensitive to the actual content of each segment.

In the plugin/run tool window it might look like this:

```
Given blah blah blah blah blah blah 
    When blah blah blah
        Then blah blah blah
Given blah blah blah blah blah blah 
    When blah blah blah
        Then shake shake shake
```

Or, like this:

```
Given blah blah blah blah blah blah 
    When blah blah blah
        Then blah blah blah
        Then shake shake shake
```

Even with the latter/second display structure, understanding the state of the SUT at any point within it is much easier than when reading the actual test code, despite the nesting, because one doesn't have the problem of a large spread-out tree with nested code separating name segments.

I know little about how Kotest is implemented, but I imagine this style would require it to  understand that the unique name of a test is a combination of all its name "segment"s.  It should not conclude, for example, that two names map to the same test because the first segment of both are the same.

**Comment by sksamuel** [comment]
The problem with this is that the inner tests do not exist until the lambdas execute at runtime, so there's no way to know the final layout until all tests have finished.

If this was added as an option, the framework would need to execute all tests in a spec before showing any output. Whether that is important or not depends on whether you care about seeing the tests appear in intellij/gradle as they are executing, or whether you're only really interested in the final output.

**Comment by sksamuel** [comment]
Another problem to solve would be if, if your example, the 2nd given block failed, but the first passed. Do you just show the error? What about if both failed, do you just show one error. But I guess that's probably isomorphic to the current situation.

**Comment by lgtout** [comment]
TBH, I'd be happy with just being able to break the test name up on separate lines and have both the plugin and the StringSpec style understand that it's a single test:
```
"Given blah blah blah blah blah blah" +
    "When blah blah blah" +
        "Then blah blah blah"  {
    TODO()
}
```

Last I checked, StringSpec doesn't like the `+`.

If the run output window displays the test as a single line, that's fine.  Also fine if the plugin does the same.

**Comment by sksamuel** [comment]
What's going to happen with that is that the  { will associate first, and
so what you're getting is "given" + (test case).

**Comment by sksamuel** [comment]
You can do what you want with multiline string """.
Eg see this test.
https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/spec/multilinename/StringSpecMultilineNameTest.kt

**Comment by ashishkujoy** [comment]
@sksamuel should we close this issue now?

**Comment by lgtout** [comment]
@sksamuel As the test you referred to shows, special treatment is required at each test on each test name in order to prevent the extra spaces from showing up in the test output.  Is there a way to do this in one location, for all tests that use multiline string?  I was unable to find one.

**Comment by sksamuel** [comment]
I see. So what about combining the multi string test names, with an opt in feature that will collapse white space inside test names?
Then if you do 

```kotlin
"""my test                
                     is really long""" { }
```

It would be trimmed to `"my test is really long"`

**Comment by lgtout** [comment]
@sksamuel That would be great!

**Comment by lgtout** [comment]
@sksamuel What do you mean by `combining the multi string test names`?  Are you referring to nested test names?  Or just combining the separate lines of each multi string test name?

**Comment by sksamuel** [comment]
I just meant stripping excess whitespace from the middle of names when using the multi line style.

**Comment by lgtout** [comment]
Got it.  Yup, that would be great!

**Comment by sksamuel** [comment]
Merged into master.
