### ISSUE TITLE
checkAll and forAll with empty list as Exhaustive hang forever

### ISSUE THREAD

**Issue by cleidiano** [kotest/kotest#1548]
**Kotest Version: 4.0.3**

How to reproduce?

```kotlin
checkAll(emptyList<String>().exhaustive()) { a ->
    println("Some string $a")
}
````
I have been explore the code base and the problem is that `proptest` will `take(n)` on a sequence generator that always produce empty sequence as it itens, it will never materialize the sequence.

Change `Gen.generate` as below solve the problem:
```kotlin
fun generate(rs: RandomSource): Sequence<Sample<A>> = when (this) {
      is Arb -> this.edgecases().asSequence().map { Sample(it) } + this.values(rs)
      is Exhaustive ->
         if (this.values.isEmpty()) emptySequence()
         else generateSequence { this.values.map { Sample(it) } }.flatten()
}
```
Let me know if I could open up a pull request.

**Comment by sksamuel** [comment]
Can you try the latest release 4.0.7 or 4.1.1 ?

**Comment by cleidiano** [comment]
The version 4.0.7 and 4.1.1 have the same behavior

**Comment by LeoColman** [comment]
I think that you can make that PR and submit the change, however I don't see a lot of value in this.

That check all is an empty statement, it's very unlikely that you need to generate more than one empty list.

I suggest making a pull request so that the test doesn't hang forever, but instead crashes due to an empty collection being used somewhere it shouldn't.

**Comment by cleidiano** [comment]
Suppose I would like to validate the comments in post if it exists, like example below:
```kotlin
data class Comment(val author: String)
data class Post(val id: Int, val comments: List<Comment>)

test("comments in a post should have author") {
         val post = random<Post>()
         checkAll(post.commnets.exhaustive()) { commnet ->
              //Validate comment if has at least one
    }
}
```
Should this test fail if the comments collection is empty? I think it doesn't.

**Comment by LeoColman** [comment]
Ok, now I understand what you're trying to do.

Generators are not the right tool for this job. We usually use generators when we want to create data, and not when we want to assert over existing data. We use generators (being an Exhaustive or an Arbitrary) for property based testing. You can check how this works [in this article](https://medium.com/criteo-labs/introduction-to-property-based-testing-f5236229d237).

Now, for your specific usecase you might want to use [inspectors](https://github.com/kotest/kotest/blob/master/doc/inspectors.md). I'd write something like this:

```
val post = random<Post>()
post.comments.forAtLeastOne {
    it.author shouldBe "Leonardo Colman"
}
```
This will try to verify that at least one element from the collection contains that comment. I would also assert that the collection isn't empty
```
val post = random<Post>()
post.comments.shouldNotBeEmpty()
```

**Comment by LeoColman** [comment]
Do you think this cover your usecase?

**Comment by cleidiano** [comment]
Yes, I think so.
For solve the hang forever do you think that `List.exhaustive()` should validate that list isn't empty, it this approach better then previous one?

**Comment by sksamuel** [comment]
I think exhaustive should throw if it's empty yes.

**Comment by LeoColman** [comment]
I'm with Sam. One should never use an exhaustive or arb for an empty collection. It's more likely to be a bug than what the user intended

**Comment by sksamuel** [comment]
We should throw an exception on EmptyList.exhaustive()

**Comment by LeoColman** [comment]
I'm with Sam. One should never use an exhaustive or arb for an empty collection. It's more likely to be a bug than what the user intended

**Comment by LeoColman** [comment]
Do you want to tackle this, @Cleidiano?

**Comment by cleidiano** [comment]
Yes, I will give a try.
