### ISSUE TITLE
Junit4 doesn't discover Specs anymore

### ISSUE THREAD

**Issue by diklimchuk** [kotest/kotest#1550]
Currently using kotest 4.1.1
On kotlintest version 3.4.2 all specs were annotated with @RunWith(KotlinTestRunner::class). This annotation is not available in 4.1.1 which requires all tests to be annotated manually.
Is it possible to add this annotation back to support junit4? (We currently use it in our android app)

**Comment by sksamuel** [comment]
Have you tried KotestTestRunner ?

**Comment by diklimchuk** [comment]
Yes, maybe it's not clear in the issue. Kotest 4 requires adding this annotation manually to all specs, which wasn't required before 4th version

**Comment by sksamuel** [comment]
But you said,

On kotlintest version 3.4.2 all specs were annotated with @RunWith
<https://github.com/RunWith>(KotlinTestRunner::class)

Isn't the same as now, except you do

On kotlintest version 3.4.2 all specs were annotated with @RunWith
<https://github.com/RunWith>(KotestRunner::class)

?

**Comment by diklimchuk** [comment]
Yes, it's not the same, maybe it wasn't clear from the message. I was intending to say all _Specs, provided by kotest library_, like BehaviorSpec and FunSpec. Now they are not annotated

**Comment by sksamuel** [comment]
I see what you mean.
The specs are multiplatform now so the runner cannot be added directly on
the specs.
Let me see if we can do some trick.
Worst case is we subclass the specs with junit4 specific names, so you
would import io.kotest.junit4.FunSpec rather than the other FunSpec - that
would work.

**Comment by diklimchuk** [comment]
Ok, thanks. That will work for now

**Comment by sksamuel** [comment]
If you use 4.2.2 then there are versions of each spec in the junit4 namespace, which has this annotation pre-applied.
