### ISSUE TITLE
Kotest plugin requires console dependency in build

### ISSUE THREAD

**Issue by jonbarksdale** [kotest/kotest#1552]
**Which version of Kotest are you using**
4.1.1

An IDE plugin should not require my build to change, as my build doesn't depend on the console dependency.  I can still run my tests fine with JUnit via gradle.

Instead, it should either be packaged with a working version of the console jar, or offer to download and cache an appropriate version.

**Comment by sksamuel** [comment]
Junit has the benefit of being built into the ide. Maybe jetbrains will
build in kotest at some point.

**Comment by jonbarksdale** [comment]
That would certainly be nice.  I don't think "gosh, jetbrains should just do it for us" is a great answer though.  It doesn't solve the problem.

Isn't the plugin published by kotest? If not, happy to move this issue to the plugin owner.

If you are the owner, then there a few paths forward that are reasonably friendly to users.  

1. Already mentioned, but package the dependencies you need.  Seems like the most common way to solve this problem
2. Offer to download the required jars for customer - also already mentioned
3. Allow running of kotest tests with JUnit if console is not present for any reason.  Really, this should be done no matter what, even if you ignore 1 & 2.  As is, if I have the kotest plugin with no console jar, I can't run the tests from the IDE without creating a custom run config to run them through gradle.  By default, clicking the green run button just fails.

**Comment by jonbarksdale** [comment]
Ah - if nothing else, I see this is the wrong repository.   I'll move it over to the other one, sorry for the distraction.

**Comment by jonbarksdale** [comment]
Issue moved to https://github.com/kotest/kotest/issues/5494
