### ISSUE TITLE
Add gen for date formats

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1564]
And maybe dates formatted in different ways.

My usecase is that I might receive or parse "randomly" formatted dates, and they should all be parseable and saved to the db in a specific format.

Testing broadly for multiple possible formatted dates would be ideal.

This could be done to the JVM as it has it's own DateTimeFormatter, but other platforms might also use this.

**Comment by sksamuel** [comment]
So a Gen that returns DateFormatter ?

**Comment by LeoColman** [comment]
Or maybe the String if we want to support mpp

**Comment by ninadingole** [comment]
@LeoColman you want date generated in a random format like `dd/MM/yyyy`, `yyyy/MM/dd` and some with time also etc. and then use this generated date in your code to see if it parses all the different combinations properly and stores to DB, right?

**Comment by LeoColman** [comment]
Yes, something like that.
I thought of an `arb<DateTimeFormatter>` or something like that. If you have ideas on how this implementation could be and want to give it a try, feel free :D

**Comment by ninadingole** [comment]
I was thinking to implement the `arb` but if you need DateTimeFormatter of different patterns, there are only some standard options that we can use like given in the [docs](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#predefined) but do you really see any advantage of providing a random DateTimeFormatter? I just want to understand your requirement properly before starting to work on it.

**Comment by sksamuel** [comment]
I think what @LeoColman is trying to do, is have an Arb that generates things like:

`10th Sept 2010`, `10/09/2010`, `10 Sept 2010`, `Sept 10 2010, `10-sep-10`

So the same date, but entered in different ways, so that people can test their date parse logic.

**Comment by ninadingole** [comment]
@sksamuel yeah I will write a Gen to generate date formatted string in the given formats 😄

**Comment by ninadingole** [comment]
This is taking time sorry, I will add this over the weekend.

**Comment by LeoColman** [comment]
No worries, we have plenty of time :)

**Comment by sksamuel** [comment]
I will close this. Feel free to reopen if you want to add it.
