### ISSUE TITLE
Where are the changelogs of versions 4.1.0 and 4.1.1, and github release of versions 4+?

### ISSUE THREAD

**Issue by LouisCAD** [kotest/kotest#1569]
For future reference, here's the permalink of the state of the main branch at the time of writing, 20 days after 4.1.1 release: https://github.com/kotest/kotest/tree/1c41070a265bb9f3739c344a704355dda8cae4b2

**Comment by sksamuel** [comment]
Thanks, changelog updated to be current.

Github releases are up to date: https://github.com/kotest/kotest/releases

**Comment by LouisCAD** [comment]
Ah, I see, you're just publishing tags for GitHub releases, I got misled by the "latest release" aside on repo homepage that directs to the last "proper" GitHub release: https://github.com/kotest/kotest/releases/tag/v3.4.2

Thanks for updating the CHANGELOG.md! Tip for next releases: Have a `RELEASING.md` file in the repo with steps for a proper release (personally, that's what I've been doing before I took the time to setup a script for semi-automation, it's good enough IMO).
