### ISSUE TITLE
Allow to disable SpringListener on final class warning

### ISSUE THREAD

**Issue by fauscik** [kotest/kotest#1573]
Hi,

I would like to be able to disable _Using SpringListener on a final class. If any Spring annotation fails to work, try making this class open._ warning which appears quite often in console logs and causes unnecessary noise in the output.
Currently it's printed using _println_ so I'm unable to disable it. Would it be possible to log it using some logger or allow to disable this warning?

Thanks

**Comment by sksamuel** [comment]
To clarify, you have the *SpringListener *in a spec, and you are using it
with a normal final class and it works, you just don't want the warning?

**Comment by fauscik** [comment]
Yes, simple as that.

**Comment by sksamuel** [comment]
The simplest way would be to add

var ignoreWarning: Boolean = false

Then you can do SpringListener.ignoreWarning = true

Or change the object to be a class, so you can do

listener(SpringListener(false))

**Comment by fauscik** [comment]
Ok, thanks for advice @sksamuel . If you don't mind, I'll go with some PR then.

**Comment by sksamuel** [comment]
Yes a PR would be welcome.
