### ISSUE TITLE
Move all system properties to a single object

### ISSUE THREAD

**Issue by Inego** [kotest/kotest#1583]
Is there any list of Kotest's supported system properties?

A side question. Is it possible to define the isolation mode for the project via a system property?

**Comment by sksamuel** [comment]
It is not, but that seems like a reasonable thing to add.

**Comment by sksamuel** [comment]
#1588

**Comment by sksamuel** [comment]
Added to master. See https://github.com/kotest/kotest/blob/master/kotest-core/src/commonMain/kotlin/io/kotest/core/engine/KotestFrameworkSystemProperties.kt
