### ISSUE TITLE
shouldBeEqualToIgnoringFields behaviour is not consistent with shouldBe (equals)

### ISSUE THREAD

**Issue by slowikps** [kotest/kotest#1585]
Hi All, I really like `kotest` library and its impact on the syntax of my tests. 

Recently, I found an inconsistency between `shouldBeEqualToIgnoringFields` and any other assertions that are using class `equals` function. 
Please consider the following example: 
```
import io.kotest.matchers.equality.shouldNotBeEqualToIgnoringFields
import io.kotest.matchers.shouldNotBe

fun main() {
    Person(1,"Pawel", "Surname") shouldNotBe  Person(2,"Pawel", "Surname")

    Person(1,"Pawel", "Surname")
        .shouldNotBeEqualToIgnoringFields(Person(2,"Pawel", "Don't care"), Person::surname)
}

data class Person(
    private val id: Int?,
    val name: String,
    val surname: String
)
```

I think the above test should successfully pass. Unfortunately, `shouldBeEqualToIgnoringFields` is ignoring private fields, so the test is failing. 
It might be a bit unusual to have private fields in the data class. It is still possible, though, and I found a couple of use cases where it is handy to have them.

**Comment by ashishkujoy** [comment]
In that case we can provide a variant of `shouldNotBeEqualToIgnoringFields` that can let user decide on whether to ignore private field or not.

```kotlin
fun <T : Any> T.shouldNotBeEqualToIgnoringFields(other: T, ignorePrivateFields: Boolean, vararg properties: KProperty<*>)
```

@slowikps would that suffice yours need?

**Comment by slowikps** [comment]
Hi, yes that should work. 
Are you going to change a default behaviour not to ignore private fields too?

**Comment by ashishkujoy** [comment]
@slowikps No default behaviour will remain same
