### ISSUE TITLE
Improved error message for map should contain when key present

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1587]
`mapOf(1 to "a", 2 to "b").shouldContain(1, "c")`

should show a better error when the map _does_ contain the key, but just with a different value.

**Comment by ninadingole** [comment]
I would like to work on this issue:

`Map should contain mapping 1=c but was 1=a` this looks good? and in case of _no key_ found entire map should be printed.

**Comment by LeoColman** [comment]
Go ahead, @ninadingole !

**Comment by ninadingole** [comment]
#1606 raised for this issue
