### ISSUE TITLE
Update diff utils to latest

### ISSUE THREAD

**Issue by I-Vargas** [kotest/kotest#1599]
Please update your dependencies. You can look up renovatebot, see if it makes sense for you.

I was using `io.kotlintest:kotlintest-runner-junit5:3.4.0` and was having a problem with versions. It depends on `kotlintest-assertions` that depends on `com.github.wumpz:diffutils`.

You guys are using `com.github.wumpz:diffutils:2.2` (from Libs.kt), that's from 2017. after that there's a 3.0, after that wumpz changed the package name and is now `java-diff-utils` and is in version 4.7.

- https://mvnrepository.com/artifact/io.github.java-diff-utils/java-diff-utils
- https://mvnrepository.com/artifact/io.github.java-diff-utils/java-diff-utils-jgit
- https://github.com/java-diff-utils/java-diff-utils

**Comment by sksamuel** [comment]
Updated in master.
