### ISSUE TITLE
Kotest + MockK = java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory

### ISSUE THREAD

**Issue by carterhudson** [kotest/kotest#1603]
https://github.com/mockk/mockk/issues/467
https://github.com/mockk/mockk/issues/459

```
    testImplementation 'io.kotest:kotest-runner-junit5-jvm:4.1.0' // for kotest framework
    testImplementation 'io.kotest:kotest-assertions-core-jvm:4.1.0' // for kotest core jvm assertions
    testImplementation 'io.kotest:kotest-property-jvm:4.1.0' // for kotest property test
    testImplementation 'io.kotest:kotest-runner-console-jvm:4.1.0' //for gutter |> icons w/ kotest plugin
```

Just wanted to put these on your radar in case the issue is with Kotest and not MockK.
I can run the tests fine using `./gradlew test ...`, but when I run using the Kotest plugin via Android Studio's gutter icons, the above issues happen. Can't test with the newest version because of https://github.com/kotest/kotest/issues/1601

**Comment by sksamuel** [comment]
Which version of android studio and kotest ?

**Comment by carterhudson** [comment]
Android Studio 4.0.1, Kotest 4.1.0, Kotest Plugin 1.0.5

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip](https://github.com/kotest/kotest/files/5003925/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip)

Feel free to try this pending-release plugin. I've not finished testing it yet, but some other guys on slack say it works. It might help with your issue (not sure).

**Comment by carterhudson** [comment]
It works! Thank you so much!

**Comment by sksamuel** [comment]
Awesome

**Comment by pawegio** [comment]
It seems to fail for Kotest + MockK again:
- kotest-runner-junit5-jvm: `4.4.3`
- kotest plugin: `1.1.30-IC-2020.3`
- mockK: `1.11.0`
- android studio: `Arctic Fox 2020.3.1 Canary 10`

(all recent versions)

`java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory` 

Only tests without any mockk declared run without the issue.

**Comment by THEAccess** [comment]
This issue should be opened again. I'm having the same issue with the latest releases:

- kotest-runner-junit5-jvm: `4.5.0`
- kotest plugin: `1.1.36-IC-2020.3`
- mockK: `1.11.0`

Stacktrace:
```
Caused by: java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:185)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:173)
	at [,..]*.BillingClientOfflineTest$1.invoke(BillingClientOfflineTest.kt:69)
```

**Comment by sksamuel** [comment]
If this an issue with using Kotlin 1.5? Are you using Kotlin 1.5?

**Comment by pawegio** [comment]
For me it fails with Kotlin `1.4.32`. I can't check it with 1.5 as I use Jetpack Compose.

**Comment by sksamuel** [comment]
Ok so it's not 1.5
I don't think its anything to do with kotest, it's throwing the class not found on mockk.

**Comment by THEAccess** [comment]
[They say it's a kotest plugin issue ](https://github.com/mockk/mockk/issues/459)

**Comment by pawegio** [comment]
> [They say it's a kotest plugin issue ](https://github.com/mockk/mockk/issues/459)

I think so too. Running tests without kotest plugin, with gradle test task works fine.

**Comment by DerekBeam** [comment]
This seems to still be an issue for me

**Comment by pablobaldez** [comment]
I'm also facing this issue
kotest 5.6.2
kotlin 1.9.0

tests are working when run from gradle so it looks like a plugin issue
