### ISSUE TITLE
Consider publishing a BOM for kotest

### ISSUE THREAD

**Issue by grodin** [kotest/kotest#1605]
For projects that produce multiple artifacts, it's really useful to publish a BOM alongside so that you don't have to worry about using incompatible versions of individual artifacts.

There's a gradle [Java platform plugin][1] which seems fairly straightforward to use. 

Any interest?

[1]: https://docs.gradle.org/current/userguide/java_platform_plugin.html

**Comment by sksamuel** [comment]
Seems like a good idea. Do you want to raise a PR ?

**Comment by grodin** [comment]
I'm intending to try to work on this next week, but will probably need some guidance about some of the details of the build process. I had a quick look yesterday but I wasn't certain if just adding a `kotest-bom` subproject with the Java platform plugin would work. I strongly suspect some reorganizing of the build process might be necessary.

**Comment by sksamuel** [comment]
Any questions you can shoot them to me, or ask in the #kotest-dev slack

**Comment by grodin** [comment]
This is much harder than anticipated. 

The Kotlin Multiplatform Gradle plugin performs some magic rewriting of dependencies between gradle projects which means that the Java Platform plugin won't "just work". 

For example, the `kotest-property` project declares a dependency on the `kotest-common` project, which by default in gradle would translate to a dependency looking like `io.kotest:kotest-common:$version` in the published POM, but the Multiplatform plugin rewrites the dependencies so that the POM for `kotest-property-jvm` actually depends on `io.kotest:kotest-common-jvm:$version` and the POM for `kotest-property-js` depends on `io.kotest:kotest-common-js:$version` and so on.

In order to produce a BOM in a reliable way, a pretty good understanding of the internals of the Kotlin Multiplatform plugin will be necessary, and something equivalent to the Java Platform plugin will need to be written for Kotlin Multiplatform, multi-project gradle builds, more or less from scratch. That's pretty obviously beyond the scope of Kotest, though if anything like that does get built, Kotest would be a great candidate for using it/testing it.

I think this is still a useful feature request, even if it's probably not going to get implemented for now, so I'll leave the issue open, but feel free to close it if you'd rather not have it cluttering up the tracker.

**Comment by sksamuel** [comment]
Thanks for looking into this.
I'll close this as I don't like to leave tickets languishing, but as soon as jetbrains or gradle release something that supports this, we'll integrate it.

**Comment by sksamuel** [comment]
As a follow up it seems coroutines have a BOM. https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-bom/build.gradle

**Comment by grodin** [comment]
That's interesting! I'll give it a look and see what I can do along the
same lines.

**Comment by grodin** [comment]
@sksamuel 

I've got generation of the BOM working. It only lists the base artifacts (`kotest-assertions-core` instead of `kotest-assertions-core-jvm`, `kotest-assertions-core-js`, etc.) but the gradle module files that are published alongside translate these automatically to the correct artifact depending on what target you're building for, no matter whether you're using Kotlin multiplatform, or JVM, or Android, etc. This works fine, and is the intended method when using gradle.

I haven't yet been able to test how well this works if you're consuming the BOM from maven, but I will try to get to that before I open a PR.

The main question I've got now is about the publishing. The way publishing works in Kotest seems to be that there's a common gradle script which is applied from any subproject which should be published, but that won't work for the BOM: you can't apply both the `java` plugin (or `java-library`) and the `java-platform` plugin in the same project (there's a check in the `java-platform` plugin which prevents it). On top of that, there's no javadoc/dokka to generate. 

So the question is, should I refactor the publishing script, so I can apply it from the BOM `build.gradle.kts` and avoid duplication of logic or should I just copy and paste? If it were my own project I'd definitely refactor, but I don't want to make any assumptions when contributing to someone else's.

As a total side issue, I think I could do some refactoring on the gradle files in general; there are some places where things can be simplified and made more maintainable (IMHO). That's obviously a separate issue. Are you interested in issues/PRs like that?

**Comment by LeoColman** [comment]
> As a total side issue, I think I could do some refactoring on the gradle files in general; there are some places where things can be simplified and made more maintainable (IMHO). That's obviously a separate issue. Are you interested in issues/PRs like that?

Yep! Go for it. Improving maintainability is always good :D

**Comment by sksamuel** [comment]
I agree with @LeoColman , any improvements are welcome.

As for the initial question, I would do the refactor there as well.
