### ISSUE TITLE
Sequence is empty error when using Arb.byteArrays

### ISSUE THREAD

**Issue by tlusk** [kotest/kotest#1608]
Using Arb.bytesArrays() throws a `java.util.NoSuchElementException`: Sequence is empty.

It looks like the cause is this line:
https://github.com/kotest/kotest/blob/aa26b494dbb80294a728ee422ea3a9da615b5c98/kotest-property/src/commonMain/kotlin/io/kotest/property/arbitrary/bytearrays.kt#L16

It should be `generateSequence` instead of `sequence`.

**Comment by LeoColman** [comment]
Nice catch!
Do you want to work on this?

**Comment by tlusk** [comment]
Yeah I can take care of it and submit a pull request.
