### ISSUE TITLE
IsolationMode.InstancePerLeaf in the Project Level Config

### ISSUE THREAD

**Issue by StragaSevera** [kotest/kotest#1612]
It would be great to have the ability to set an isolation mode one time for a whole project and not manually each time in each file, with the ugly `init` double indentation.
Also, it would be great to have the ability to set an isolation mode as a constructor argument or in some other way that does not require the `init` syntax.

**Comment by sksamuel** [comment]
You can do

```kotlin
class MyTest : FunSpec({ 
  isolation = ...
  test("foo") {
  }
})

**Comment by LeoColman** [comment]
Which is also configurable in the ProjectConfig

**Comment by StragaSevera** [comment]
> Which is also configurable in the ProjectConfig

Well, the documentation does not say anything about it. Could you give an example? =-)

**Comment by sksamuel** [comment]
This page details how you can use project config. https://github.com/kotest/kotest/blob/master/doc/project_config.md

Isolation mode is not mentioned on there but that is one of the parameters available.

**Comment by sksamuel** [comment]
Docs have been updated.
