### ISSUE TITLE
TestListener not intercepting spec constructor

### ISSUE THREAD

**Issue by diklimchuk** [kotest/kotest#1625]
Kotest 4.1.1

Currently, using LocaleTestListener for example, doesn't work when used to init something outside of the test scope.
It happens because locale could be used inside Spec constructor which is not intercepted by the extension.
Is this a bug or there is a recommended way of handling this?

Sample:
```
object LocaleSpec : BehaviorSpec({
   val locale = Locale.getDefault()
   Given("a locale interceptor") {
       When("the test is executed") {
            Then("It has the wrong locale") {
                locale.shouleBe Locale.GERMAN // fails
            }
       }
   }
})  {
     override val listeners() = listOf(LocaleTestListener(Locale.GERMAN))
}
```

**Comment by sksamuel** [comment]
You could put the listener at the project level.

**Comment by diklimchuk** [comment]
Yes, but i need to override locale for one specific test. If i put a listener at the project level, it would override locale for all tests

**Comment by LeoColman** [comment]
Try

```
object LocaleSpec : BehaviorSpec({
    listeners(LocaleTestListener(Locale.GERMAN)
   val locale by lazy { Locale.getDefault() }
   Given("a locale interceptor") {
       When("the test is executed") {
            Then("It has the wrong locale") {
                locale.shouleBe Locale.GERMAN // fails
            }
       }
   }
})
```

**Comment by LeoColman** [comment]
I don't think it's possible to execute t he spec before running its `init` block, which is where your tests get registered. This way I'm trying to setup t he listener before the test has a chance to obtain the locale

**Comment by diklimchuk** [comment]
Yeap, thanks. Lazy should work here.
