### ISSUE TITLE
Pulling Kotest 4.2.0-RC2 from Central complains about missing dependencies

### ISSUE THREAD

**Issue by DanySK** [kotest/kotest#1630]
**4.2.0-RC2**

Relevant `build.gradle.kts`:

```kotlin
repositories {
    mavenCentral()
}
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    testImplementation("io.kotest:kotest-runner-junit5:4.2.0-RC2")
    testImplementation("io.kotest:kotest-assertions-core-jvm:4.2.0-RC2")
}

```

Gradle's complaint:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> Could not resolve all files for configuration ':testRuntimeClasspath'.
   > Could not find com.soywiz.korlibs.klock:klock:1.11.14.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock/1.11.14/klock-1.11.14.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > io.kotest:kotest-runner-junit5:4.2.0.RC1 > io.kotest:kotest-runner-junit5-jvm:4.2.0.RC1 > io.kotest:kotest-core:4.2.0.RC1 > io.kotest:kotest-core-jvm:4.2.0.RC1
```

Apparently `com.soywiz.korlibs:klock` is not being released on Maven Central.

**Comment by LeoColman** [comment]
Just out of curiosity, why can't you use jcenter along with maven central?

**Comment by DanySK** [comment]
@LeoColman because I've got some software that needs to work pointing to Central alone. I could add jcenter for the test packages, but AFAIK there is no easy way to link repositories to configurations in Gradle, hence I'd be at risk of including compile/runtime dependencies that are not hosted on Central.

Anyway, I think that it is reasonable that packages distributed on Central only depend on other packages hosted on Central (that's basically also the reason why I opened this bug report).

By the way I also opened korlibs/klock/issues/138, I guess this bug depends on that.

**Comment by sksamuel** [comment]
Please try 4.2.0.RC3

**Comment by sksamuel** [comment]
4.2.0 final has been released. You should be good to go, klock is a not a dependency @DanySK

**Comment by DanySK** [comment]
I confirm the issue is gone.
Contextually, I want to amend my previous post, in fact *there is* a way in Gradle to filter repository use by configuration:
```kotlin
repositories {
  jcenter {
    content {
      onlyForConfiguration("testCompileClasspath", "testRuntimeClasspath")
    }
  }
}
```
I have not tried on an older version of Kotest to se if it works in this case, but it does for Dokka and Detekt.

Thanks
