### ISSUE TITLE
Add Gen.forNone

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1636]
We currently have `Gen.forAll { it == true }`. If we want to invert it, it's ok to write `Gen.forAll { !(it == true) } `.

It would be syntactically pleasant to write `Gen.forNone` instead, like:

```
test("Random string shouldn't be a valid email") {
     Arb.string().forNone { it.isEmail() }` 
}
```

vs

```
test("Random string shouldn't be a valid email") {
    Arb.string().forAll { !it.isEmail() } ` 
}
```

**Comment by ninadingole** [comment]
Will be happy to work on this.

**Comment by LeoColman** [comment]
Feel free, @ninadingole! If you have any doubts, please let us know ;)

**Comment by sksamuel** [comment]
You know, if you did

```
test("Random string shouldn't be a valid email") {
     Arb.string().forNone { it.isEmail() }` 
}
```

Then eventually, you would actually generate a valid email :joy:
