### ISSUE TITLE
TestContainers Extention and Spring boot startup timing

### ISSUE THREAD

**Issue by joelhess** [kotest/kotest#1649]
With the new test containers extension, I've declared a couple of containers, and they start up just fine before the spec is ran, but I need to be able to take properties from the started containers (like a port mapping or the hostname) and update config for my spring boot application. I added `@SpringBootTest` on my spec, but BeforeSpec doesn't appear to run before the spring boot application gets started. Where is the appropriate hook to update my config between the containers getting started and the spring app getting started?

Using Kotest 4.2 with Kotlin 1.4.

**Comment by LeoColman** [comment]
I believe project level or `beforeSpecClass` might guarantee it

**Comment by sksamuel** [comment]
How does the annotation get processed?

**Comment by sksamuel** [comment]
Can you provide a dummy example of how you are taking the properties from the container and passing them to the spring boot application, so I can see how the lifecycle needs to work.  @joelhess

**Comment by benkuly** [comment]
An example, how Spring works with TestContainers and properties:

```
import org.springframework.boot.test.autoconfigure.data.neo4j.DataNeo4jTest;

import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import org.testcontainers.containers.Neo4jContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
@DataNeo4jTest
class ExampleTest {

    @Container
    private static Neo4jContainer<?> neo4jContainer = new Neo4jContainer<>("neo4j:4.0");

    @DynamicPropertySource
    static void neo4jProperties(DynamicPropertyRegistry registry) {
        registry.add("org.neo4j.driver.uri", neo4jContainer::getBoltUrl);
        registry.add("org.neo4j.driver.authentication.username", () -> "neo4j");
        registry.add("org.neo4j.driver.authentication.password", neo4jContainer::getAdminPassword);
    }
}
```
From: https://docs.spring.io/spring-data/neo4j/docs/6.0.0-M2/reference/html/#dataneo4jtest

It would be awesome if something like this is possible with kotest.

**Comment by sksamuel** [comment]
Can you explain dynamic property source briefly ? I'm not super
familiar with spring.

**Comment by benkuly** [comment]
[@DynamicPropertySource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/DynamicPropertySource.html) is an annotation, which allows you to inject properties for spring at runtime. In the example above the driver-uri, which is needed to connect to the neo4j database isn't known when the test started but after the neo4j database container started.

**Comment by sksamuel** [comment]
I think we can make this work.

What I'd need to see is an example of where the dynamic property source values are used.

I understand that the container needs to start first, then the dynamic source is processed to add the container properties to the test context properties. Where are those values then used? In other fields?

**Comment by benkuly** [comment]
The property values can be used everywhere in the code. Mostly spring auto-configuration projects use it internally. For example a database can be simply integrated to your spring application by adding a dependency and a few properties to a properties-file. Because in tests with TestContainers they are not static, they need to provided at test-runtime.

Here is an example-project, where this is used:
https://github.com/neo4j/sdn-rx/tree/master/examples/kotlin/src
under `main/resources` there are the static properties for the production build
and under `test/kotlin/org/neo4j/springframework/example/kotlin/KotlinReactiveWebApplicationTest.kt` there are the dynamically loaded properties.

Do you need more? :)

**Comment by sksamuel** [comment]
This makes sense.
So what's happening in that example, is they are using a companion object to create the container, so it will run before the test class is instantiated.

In the example you posted, the container is in the test class itself, so will always be created after the test class initializer has run.
You would need to move it out into a companion object like they did in their example.

**Comment by ashishkujoy** [comment]
@benkuly, I am assuming the problem you are facing here is that when container starts it starts on some random available port on  your machine and you have a fix port added in your application yaml file. And you want to change that port property to the port on which container is serving request.

Is that assumption is right?

**Comment by sksamuel** [comment]
The random port on the container needs to be passed to spring beans so it can connect.
So if you have a web server being started up, that random port needs to be passed to the http client.
This is just a problem of initialization order - the container must be created before the test class is instantiated.

The simplest way is to just create the container outside of any test class and then it's properties can be used. That's how the example @benkuly linked to does it in Java.

Another way is like this https://akobor.me/posts/using-testcontainers-with-micronaut-and-kotest

**Comment by benkuly** [comment]
Thank you, that worked :)

**Comment by brizzbuzz** [comment]
Know this is closed, but others may find this helpful :)

There is a special jdbc uri syntax that test containers has (that spring can accept) that means you don't need to follow the abstract class pattern.  

If you have an `application.yml` like the following 

```yml
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:13:///test_db # <--- Secret Sauce
    username: test_user
    password: test_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
```

Then test containers can intercept this and your test will work as expected (only verified this on Postgres 13)

With this setup, you can create a helper function like so 

```kotlin
object Util {
    private val POSTGRES_IMAGE: DockerImageName = DockerImageName.parse("postgres:13")
    fun DescribeSpec.attachBasicPostgresContainer(): PostgreSQLContainer<Nothing> {

        val postgresContainer = PostgreSQLContainer<Nothing>(POSTGRES_IMAGE).apply {
            withDatabaseName("test_db")
            withUsername("test_user")
            withPassword("test_password")
        }

        listener(postgresContainer.perSpec())
        return postgresContainer
    }
}
```

and then attach your postgres container like you would in a non-spring world

```kotlin
@SpringBootTest
class AccountRepositoryIntegrationTest : DescribeSpec() {

    val postgresContainer = attachBasicPostgresContainer()

    @Autowired
    private lateinit var repository: AccountRepository

    init {
        register(SpringExtension)

    // actual tests go here ...
```
