### ISSUE TITLE
Add Gen.lazy

### ISSUE THREAD

**Issue by swachter** [kotest/kotest#1651]
It is not clear what the recommended way is for defining recursive generators. Should `Arb.create` be used?

**Comment by sksamuel** [comment]
Can you give me an example of what you're trying to do?

**Comment by swachter** [comment]
I want to generate an arbitrary JSON structure (using Jackson). JSON arrays/objects can contain JSON arrays/objects.

Background: Microsoft Azure Device Twins do not support arrays and object keys must not contain certain characters. Arbitrary JSON has to be encoded (converting arrays into objects and encoding object keys) and decoded again. That is a perfect fit for properties based testing.

**Comment by swachter** [comment]
I finally implemented my generator as shown below. Generators are now eagerly instantiated which is not a problem because I limited the maximum nesting. In case of much deeper probable nestings, though, a lot more generators would be instantiated eventually yielding to out of memory exceptions.

Maybe that could be avoided by using 

```
fun nodeGen(nest: Int) = Arb.create {
        if (nest > 0) { // restrict maximum nesting
            Arb.choose(3 to primitiveGen, 1 to arrayGen(nest - 1), 1 to objGen(nest - 1)).next(it)
        } else {
            primitiveGen.next(it)
        }
}
```

A set of generators for arbitrary JSON structures:

```
    private val mapper = jacksonObjectMapper()

    private val keyGen = Arb.string(1..5, Arb.int(32..126).map { Codepoint(it) }).filter { it != ARRAY_MARKER }

    // generates primitive values with equal probability
    private val primitiveGen: Arb<JsonNode> = Arb.choice(
            Arb.of(BooleanNode.TRUE, BooleanNode.FALSE),
            Arb.choice(
                    Arb.int(0..9).map { IntNode(it) },
                    Arb.numericDoubles(-1.0, +1.0).map { DoubleNode(it) },
            ),
            Arb.string(0..5, Arb.ascii()).map { TextNode(it) },
            Arb.constant(NullNode.instance)
    )

    // generates arrays with varying sizes and arbitrary items
    private fun arrayGen(nest: Int): Arb<JsonNode> =
        Arb.list(nodeGen(nest - 1), 0..5).map {
            val a = mapper.createArrayNode()
            it.forEach { a.add(it) }
            a as JsonNode
        }

    // generates objects with varying sizes and arbitrary members
    private fun objGen(nest: Int): Arb<JsonNode> =
        Arb.list(Arb.pair(keyGen, nodeGen(nest - 1)), 0..5).map {
            val o = mapper.createObjectNode()
            it.forEach { (k, v) -> o.set<JsonNode>(k, v) }
            o as JsonNode
        }

    // generates arbitrary nodes
    private fun nodeGen(nest: Int): Arb<JsonNode> =
        if (nest > 0) { // restrict maximum nesting
            Arb.choose(3 to primitiveGen, 1 to arrayGen(nest - 1), 1 to objGen(nest - 1))
        } else {
            primitiveGen
        }
```

**Comment by sksamuel** [comment]
Feel free to close this if you're happy with your solution.

**Comment by swachter** [comment]
I am happy with my solution. However, I wonder if some documentation would be helpful. It took me several hours figuring out and I am still unsure, if ˋArb.createˋ would have been the right path for more deeply nested structures.

**Comment by LeoColman** [comment]
If ypu could write this on the docs, I don't see any problems with it.

If you want to, create a dummy use case and go for it :)

/open

**Comment by swachter** [comment]
Scala check provides a [`Gen.lzy`](https://github.com/typelevel/scalacheck/blob/master/src/main/scala/org/scalacheck/Gen.scala#L564) combinator that helps to construct recursive generators. Maybe kotest could also provide one.

**Comment by Megamiun** [comment]
Hello, just confirming, this would be a Generator which receives a function that creates other generators on demand and uses them to generate values?

**Comment by sksamuel** [comment]
Yep. It should only generate the generator once and memoize it.

**Comment by ashishkujoy** [comment]
Fixed in master
