### ISSUE TITLE
Add documentation for retry

### ISSUE THREAD

**Issue by phanimahesh** [kotest/kotest#1652]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

Useful for writing tests that deal with network, etc, where it may ocassionally fail.

I know that kotest is a unit testing library and this use case should not occour in unit tests, but I use kotest to write some integration tests for the client libraries I publish, and this would be very useful there.

I can currently mimic this with `eventually`, but it would be nicer to be able to provide number of attempts rather than a time limit.

**Comment by sksamuel** [comment]
So something like `attempt(n) { ...}` (or another name)

**Comment by sksamuel** [comment]
`retry` is what you want, I forgot we had that. I've updated the docs to explain. 
https://github.com/kotest/kotest/blob/master/doc/nondeterministic.md

**Comment by phanimahesh** [comment]
@sksamuel Thanks!
