### ISSUE TITLE
Allow flaky tests that ignore failures

### ISSUE THREAD

**Issue by phanimahesh** [kotest/kotest#1668]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

I have a test that fails quite frequently. I would still like to run it every time, but not fail my test suite if it fails. I don't think there's a way to implement this currently in kotest.

**Comment by LeoColman** [comment]
Some thing like

```
class MyClass : FunSpec({

    test("Flaky").config(allowedToFail = true) {
        if(Random.nextInt() > 30) throw RuntimeException()
    }

})
```

should lead to a successful execution?

**Comment by phanimahesh** [comment]
Yes, that is exactly what I'm suggesting.

**Comment by LeoColman** [comment]
I think it can be a little bit confusing.
If the execution result is a failure, should we mark the test as Ignored? Should we mark it as Successful?

And when looking at a test report, would a success mean it passed or failed? I'm not completely sure how this could work

**Comment by phanimahesh** [comment]
The test should be marked as successful if it succeeded, or ignored if it
failed.

This way, a success would mean it was successful, and ignored can be
interpreted as "ignored due to allowed failure"

**Comment by sksamuel** [comment]
What's the use in a test that if it fails it will just be ignored anyway.

I would say fix the flakiness or use retry so that it will pass.

**Comment by LeoColman** [comment]
An alternative is to create an extension that will set the status to ignore if it fails.
I would like to discuss whether this is something we trully want to support, as it can become messy

**Comment by LeoColman** [comment]
In Kotest we have an extension that does exactly that
```
val expectFailureExtension: TestCaseExtensionFn = { (testCase, execute) ->
   val result = execute(testCase)
   when (result.status) {
      TestStatus.Failure, TestStatus.Error -> TestResult.success(0)
      else -> AssertionError("${testCase.description.name.name} passed but should fail").toTestResult(0)
   }
}
```
but we use it to assert that specs fail as we intended

**Comment by LeoColman** [comment]
> What's the use in a test that if it fails it will just be ignored anyway.

I think that something like:

1. It's an integration test that pings a specific and real service
2. The service returns an error, but we didn't touch our implementation to call it

In that case, it's ok for the test to fail.

But idk, it's not a good enough usecase to justify this feature

**Comment by sksamuel** [comment]
I understand why a test might sometimes fail but if you're going to let the
test plan pass anyway what's the point.

**Comment by phanimahesh** [comment]
The idea is to keep it running rather than completely disabling it. If I
disable the test it will not run at all, and it may get completely ignored
by the developer as well. If I mark it as flaky (possibly with an exception
whitelist), then the tests do get run, are visible to anyone looking at the
logs, and the executions provide data on how flaky the test is, and can
help in fixing that up properly.

**Comment by sksamuel** [comment]
The developer can ignore it if it runs and the build doesn't fail. I see your point but I don't think it is core functionality in Kotest.

You can achieve this by adding a TestCaseExtension that converts a Failure with a certain exception type into another result type. As leo says, we do this ourselves in Kotest's own test suite.

**Comment by phanimahesh** [comment]
that sounds reasonable. I'm doing something similar to your test suite to
ignore some exceptions entirely.

Thanks, this can be closed.
