### ISSUE TITLE
Comma?

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1673]
https://github.com/kotest/kotest/blob/ae23fbeff7529c7666b0d83035221d67b32bcf1b/kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/JUnitTestEngineListener.kt#L71

**Comment by sksamuel** [comment]
What about it ?

**Comment by LeoColman** [comment]
It's ok, @crazyk2.
That seems odd because [until kotlin 1.4.0](https://kotlinlang.org/docs/reference/whatsnew14.html#trailing-comma) trailling commas weren't available.

The code compiles fine :)

**Comment by crazyk2** [comment]
Ok and compiles but why?

**Comment by sksamuel** [comment]
https://kotlinlang.org/docs/reference/whatsnew14.html#trailing-comma

**Comment by crazyk2** [comment]
I read this but there only two parameters and I don't think that size will increase.

If it was a data class with 3+ parameters, that would be appropriate

**Comment by sksamuel** [comment]
I don't think it matters.
