### ISSUE TITLE
New map assertions

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1697]
Map.shouldContainAnyKeyOf(a,b,...) // contains one of more of the keys
Map.shouldContainAnyValueOf(a, b, ...) // contains one or more of the values

**Comment by RajatVaryani** [comment]
I would like to work on it.

**Comment by sksamuel** [comment]
Please do.

**Comment by vjgarciag96** [comment]
Are you still willing to work on this one @RajatVaryani? 

If not, I'd be glad to help with it, it looks like a good issue to start contributing to this repository
