### ISSUE TITLE
Arb.distinct() does not resolve for take(n) where n > number of distinct items

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest#1701]
because internally it calls sequence.distinct on an Arbitrary which is guaranteed to yield an infinite sequence.

**Comment by sksamuel** [comment]
This ?

```kotlin
fun <A, B> Arb<A>.distinctBy(selector: (A) -> B) = object : Arb<A>() {
   override fun edgecases(): List<A> = this@distinctBy.edgecases().distinctBy(selector)

   override fun values(rs: RandomSource): Sequence<Sample<A>> {
      return this@distinctBy.values(rs).distinctBy { selector(it.value) }
   }

   override fun sample(rs: RandomSource): Sample<A> =
      samples(rs).distinctBy { selector(it.value) }.first()
}
```

Returns another sequence from the source sequence.

**Comment by myuwono** [comment]
yeah that's correct. The minimal code to reproduce this are:

```kotlin
val arbBoolean = Arb.create { it.random.nextBoolean() }
println(arbBoolean.distinct().take(1).toList()) // [true]
println(arbBoolean.distinct().take(2).toList()) // [true, false]
println(arbBoolean.distinct().take(3).toList()) // hangs
```

and 
```kotlin
val arbOneOf = Arb.of("foo", "bar", "baz")
println(arbOneOf.distinct().take(1).toList()) // ["foo"]
println(arbOneOf.distinct().take(2).toList()) // ["foo", "bar"]
println(arbOneOf.distinct().take(3).toList()) // ["foo", "bar", "baz"]
println(arbOneOf.distinct().take(4).toList()) // hangs
```

**Comment by myuwono** [comment]
under the hood, `Sequence<A>.distinct()` has this `while(iterator.hasNext())` condition, which will always return true for infinite sequence.  https://github.com/JetBrains/kotlin/blob/36984009e908b923548098ba887a230fc6885965/libraries/stdlib/src/kotlin/collections/Sequences.kt#L570 

which mean the only way we can safely use `distinct()` is when we know the number of distincts a-priori.

**Comment by sksamuel** [comment]
With take after distinct yes, but that's expected and documented. This will do the same:

```kotlin
fun main() {
   generateSequence { 1 }.distinct().take(2).toList()
}
```

**Comment by myuwono** [comment]
I'm wondering if that behaviour is expected for Arbs?

**Comment by sksamuel** [comment]
It's not ideal, but I guess if the std lib suffers from the same issue, what can do we.

**Comment by myuwono** [comment]
We will be deprecating distinct. closing this issue as won't fix
