### ISSUE TITLE
Automatic documentation for the matchers

### ISSUE THREAD

**Issue by Lunchee** [kotest/kotest#1714]
Hello!

I have a proposal about documenting the matchers in the sources (using KDoc) in addition to the documentation given on the [full list of matchers](https://github.com/kotest/kotest/blob/master/doc/matchers.md) page.

The reason is that as a user of Kotest I would like to quickly access the documentation right from the IDE rather than opening a documentation webpage on GitHub. I believe it would be more comfortable and faster for developers. Moreover, documented code inspires confidence.

Let's say I want to use the `shouldContainExactly` function on a collection, but I'm not sure if it matches elements in a given order. The function does not contain documentation, and I will need three hops inside the sources to get to the `containExactly` function that has documentation. What I would like to see is that all the visited functions (`shouldContainExactly(vararg expected: T)`, `containExactly(vararg expected: T)` and `containExactly(expected: C)`) contain the same (or similar) piece of documentation. That way I won't need to spend time on drilling down into sources or searching for documentation on the GitHub page.

As a next step, I would suggest generating the [full list of matchers](https://github.com/kotest/kotest/blob/master/doc/matchers.md) page automatically from the latest build to keep a single source of truth of documentation.

What do you think, should we go for it?

**Comment by sksamuel** [comment]
Totally agree. And if you can figure out a way to generate the matchers programatically, that isn't horrible like javadoc, then I think that would be awesome.

**Comment by Lunchee** [comment]
Great!
Then I'll start with documenting functions in the `containExactly` file if you don't mind. I'll prepare a quick pull request soon to understand if I'm moving in the right direction.
Meanwhile, will try to find out how to extract the documentation to the `matchers.md` file automatically.

**Comment by sksamuel** [comment]
Sounds great. Note, we want the docs/ folder not the doc/ folder as the
latter is going away, and the former is the new microsite via mkdocs.

**Comment by sksamuel** [comment]
If we added a custom file processor that looked inside .kt files for a certain layout of comments, we could use that to generate matcher docs.

Just off the top of my head, like:

```kotlin
/**
* This is a comment
* _begin_matcher_
* Whatever is in here goes into a .md file
* @name maybe we support tags for things like name or platform
* @jvmmatcher
* _end_matcher_
/*
fun mymatcher ....
```
