### ISSUE TITLE
Configure Junit5 report to exclude ContainerScope "tests"

### ISSUE THREAD

**Issue by almozavr** [kotest/kotest#1716]
## Context
Using `ContainerScope` (e.g. Given/When) and `isolationMode = IsolationMode.InstancePerLeaf` I often want to assert/verify  only `TestContext`s (e.g. Then) while containers are served as pre-configuration blocks which I find quite comfortable to read as a developer.

## Issue
Junit report contains empty "container tests" which are misleading at e.g. CI level.

```kotlin
class SampleTest : BehaviorSpec({
    isolationMode = IsolationMode.InstancePerLeaf
    Given("counter") {
        var counter: Int
        When("increment from 0") {
            counter = 0
            Then("initially 0") {
                counter shouldBe 0
            }
            Then("+2 = 2") {
                counter += 2
                counter shouldBe 2
            }
        }
    }
})
```

![image](https://user-images.githubusercontent.com/780153/92914012-4faa5700-f43c-11ea-81cc-a90aa2b615c6.png)

## Request
Configure `Spec` to exclude it's containers from the report but inject container names to the test names or group concrete tests by the containers instead the same as Inellij plugin does (aka Junit's `@Nested`).

![image](https://user-images.githubusercontent.com/780153/92915035-3eae1580-f43d-11ea-9927-0c01d8c52b08.png)

**Comment by sksamuel** [comment]
It's a lack of functionality in the junit report format.
We have this to help:
https://kotest.io/extensions/junit_xml/

**Comment by almozavr** [comment]
@sksamuel thanks! it looks just fine ⭐️

**Comment by almozavr** [comment]
@sksamuel quick questions: `JunitXmlReporter` uses hardcoded `outputDir` which creates duplicate for the default task-driven test results – is it an issue or we could do nothing with it?
![image](https://user-images.githubusercontent.com/780153/92943267-9fe8df80-f463-11ea-9a83-5678753c9fa9.png)
![image](https://user-images.githubusercontent.com/780153/92943577-00781c80-f464-11ea-88c6-2097455e7810.png)
I also found the `JunitXmlReporter` to write `test-results` only if there is at least 1 failing test 🤔

**Comment by sksamuel** [comment]
You can pass in the value you want for outputDir or is that not what you
are looking for?

**Comment by almozavr** [comment]
@sksamuel I can't see the option to pass `outputDir` param, only the `build` folder param is accepted by the class, which doesn't help, so we end up having 2 separate folder at `test-results` (in case of Android project).

**Comment by almozavr** [comment]
I also found the JunitXmlReporter to write test-results only if there is at least 1 failing test 🤔

**Comment by sksamuel** [comment]
It should always write out, I will check that bug.
I don't understand what you're looking for the output. Can you give me an example of the directory structure you are looking for?

**Comment by almozavr** [comment]
@sksamuel by default, android test-task creates `test-results` folder with the name related to the flavour/buildType name, e.g. `"test${Flavour}${BuildType}UnitTest"` -> `testDebugUnitTest`. I'd like `JunitXmlReporter ` to use the same folder to write it's version of the report so it overrides the default's junit version. Is it possible? If so, we need a way to say to `JunitXmlReporter` the output folder name.

**Comment by sksamuel** [comment]
I see ok.

I suspect gradle passes this into the junit one because gradle is tightly
coupled with junit.
The way is probably to change this line:

systemProperty("gradle.build.dir", project.buildDir)

to reference the configuration name as well.

**Comment by almozavr** [comment]
@sksamuel oh, I was blind to see `outputDir` is a constructor argument 👀 anyway, it seems like there is no way to override the default junit's folder (`testDebugUnitTest` on android) – I suppose, junit reporter overtakes the control here. So, I think `JunitXmlReporter` is an extra but not a first class option :(

**Comment by sksamuel** [comment]
Kotest's junit reporter is like an add on that mimics what junit/gradle do.
So you can turn off the report gradle generates for you (since it has the
incorrect output) and then use kotest's to work.
You can set systemProperty("gradle.build.dir", project.buildDir) to include
the test-results/testDebugUnitTest path
and then in the constructor for the reporter, set outputDir to just ""

**Comment by almozavr** [comment]
@sksamuel thanks for the help and the details 🙏

**Comment by sksamuel** [comment]
Absolutely, let me know if it's still not working.
And if you can get the syntax right to include the test configuration name,
then I can add that to the docs.
