### ISSUE TITLE
Allow listeners to be tagged with tags

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1717]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by ashishkujoy** [comment]
What will be the use of tagging a listener?

**Comment by sksamuel** [comment]
So we can run a listener against multiple specs but not all.
An annotation would work too @Extension(Foo::class)

**Comment by ashishkujoy** [comment]
@sksamuel Did you mean when we add listener through project config having tag on listener will help to run it only when that particular tag is active and the spec is also tagged with same tag?

**Comment by sksamuel** [comment]
Yeah basically. I'm thinking of extension authors who might want an easy way to enable a listener automatically for multiple tests. Perhaps a Spring extension only needs to be active in certain scenarios. JUnit achieves this by making you add @Extension to the class. 

So we can either 
- Add support for `@Extension(Foo::class)` like JUnit
- Add some kind of `install(tag1, tag2, listener)` inside project config
- Add some callback that allows extensions / listeners to decide if they are active or not. JUnit sort of achieves this by passing in an `ExtensionContext` to each callback so the extension itself knows if it should run. We could add further test extension classes, like BeforeAllExtension that has `process(context)` method, in a similar fashion.
- Some other idea
- Do nothing.
