### ISSUE TITLE
Coroutine context from extensions is not propagated to tests

### ISSUE THREAD

**Issue by tkrullmann** [kotest/kotest#1725]
**Which version of Kotest are you using**
4.2.5

I am trying to use a custom extension or `aroundTest` call that surrounds the test execution with a `withContext(...)`, augmenting the coroutine context.

Expected: the added coroutine context is accessible from the tests and other setup logic that is invoked as `suspend`

Actual: the coroutine context is not propagated to the test, somewhere on the call stack it gets replaced with a different context

It seems that `ExecutorExecutionContext` is the place where this replacement happens. It seems to me that the call to `runBlocking`:

https://github.com/kotest/kotest/blob/24769598e4158afbbcbd57a28443cf8ff94cdf36/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/ExecutorExecutionContext.kt#L44-L46

should actually pass the `CoroutineContext` from the `Continuation`:

```kotlin
runBlocking(cont.context.minusKey(ContinuationInterceptor)) {
    ...
```

It seems prudent to remove the `ContinuationInterceptor` (i.e. the `CoroutineDispatcher`) from the context, because the documentation for `runBlocking` states that otherwise it would just continue the coroutine on the given dispatcher and block the thread until it's done, but the purpose of this class seems to be that we want to interrupt the thread if a test ends up in an endless loop.

**Example Code:**

```kotlin
class FooContext(val value: Any) : AbstractCoroutineContextElement(Key) {
    companion object Key : CoroutineContext.Key<FooContext>
}

/** Gets the contextual foo value from a test */
suspend fun foo(): Any? = coroutineContext[FooContext]?.value

class FooContextSpec : FreeSpec({
    aroundTest { (testCase, execute) -> 
        val fooValue = 42
        withContext(FooContext(fooValue)) {
            execute(testCase)
        }
    }
    
    "should have contextual value" - {
        foo().shouldNotBeNull()
    }
})
```

**Background:**

I often create extensions that produce contextual objects around a scope (spec / container / test), which then need to be accessed in individual tests or before/after callbacks.

For example, consider an extension that launches and tears down an embedded database around some test scope. The tests need some handle to that DB, which might be a randomly allocated TCP port or some object from the DB's client library.

In simple cases, such scenarios can be addressed similar to kotest's `tempfile()`: a simple function that is called directly from the spec, which does the setup immediately and registers an `afterSpec` callback to do the cleanup. However, doing this in an extension and making the value available via some sort of context would improve composability and reduce boilerplate.

Many test frameworks have a facility for these contextual values. In JUnit 5, there is the `ExtensionStore` which can be used to resolve test method parameters. In Spek, there is `memoized`. Since kotest is using coroutines throughout, I thought that a custom coroutine context element would be the intended way to pass these contextual values.

**Comment by sksamuel** [comment]
We could probably use the context from an extension for the context the test runs. It might get complex though with the fact a test can run multiple times, in parallel and so on.

Perhaps just a better extension setup would be preferable. Something akin the extension context from JUnit 5.

**Comment by tkrullmann** [comment]
Well, I think the coroutine context would already be a great equivalent / replacement for JUnit's `ExtensionContext.Store`, and has the advantage that it's already familiar to developers. And the other features `ExtensionContext` offers (querying the current test class or test instance) don't really apply to kotest because it's functional in nature. Moreover, we already have `TestContext` which offers some metadata about the currently executing test.

As for parallelism, that's really the strong suit of coroutines, so I don't see a problem there. Of course context elements should be immutable, but that always applies to using coroutines.

As for running one test multiple times, I can't think of a case where that could become a problem, but if that level of control is desired, how about adding a new hook similar to `aroundTest` which is called around the whole such group of test "clones"?

**Comment by sksamuel** [comment]
So we can just use the inherited context when creating the new context, and your values should be propagated down.
