### ISSUE TITLE
Migration path for consumers using kotlintest-core version 3.4.2

### ISSUE THREAD

**Issue by Poorva17** [kotest/kotest#1726]
Hi,

We are currently using `"io.kotlintest"         % "kotlintest-core"         % "3.4.2"` in our project. We have already upgraded kotlin version to `1.4.10`. Now we want to upgrade `kotlintest-core` dependency. We saw in [change logs](https://kotest.io/changelog/) that packaging and module names have changes in major release 4.0.0. We upgraded dependency to `"io.kotest"             % "kotest-core"             % "4.2.0.RC2"`.

Note: https://github.com/kotest/kotest/issues/1600 This says that 4.2.0 final release is done. But we are unable to find it on maven.

Can you please redirect us where we can get some help to migrate from `kotlintest-core` version `3.4.2` to `kotest-core` version `4.2.0` ?

**Comment by sksamuel** [comment]
You want kotest-runner-junit5 4.2.5. You don't need to depend on core.

**Comment by sksamuel** [comment]
Did you manage to get this working ?

**Comment by Poorva17** [comment]
Yes it worked for us. 👍🙂
