### ISSUE TITLE
containExactlyInAnyOrder relies on hashCode

### ISSUE THREAD

**Issue by U1F984** [kotest/kotest#1728]
**Which version of Kotest are you using**
4.2.5

If I compare a collection containing objects that overwrite `hashCode` incorrectly by `containExactlyInAnyOrder`, it will fail, even though the collection content might be equal. If this is not considered a bug it should at least be documented in the KDocs for the method.

**Comment by LeoColman** [comment]
How could we verify if two objects are equal if their hashcode is implemented incorrectly?

**Comment by U1F984** [comment]
To clarify: the `equals` method is implemented correctly, the `hashCode` simply does not fulfill the implicit contract that if `a.equals(b)` then `a.hashCode() == b.hashCode()` since it incorrectly calls `Object.hashCode()`. So equality can be tested via `equals`.

**Comment by sksamuel** [comment]
According to the java docs for hashcode:

_If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result._

So I think the best course of action is to highlight this in the docs for containExactlyInAnyOrder.
