### ISSUE TITLE
"Command line is too long" error

### ISSUE THREAD

**Issue by qw0c** [kotest/kotest#1739]
When I try to run tests I get the error: "_Error running [TestName]': Command line is too long. Shorten command line for [TestName] or also for Kotest default configuration._" 

For JUnit I can solve this problem with standard command line shortener, but unfortunately this feature is not available for Kotest configuration 😢

<img src="https://user-images.githubusercontent.com/62946723/94600258-53dacf00-029a-11eb-8689-f84a0e5cf5ca.png" width=48%> <img src="https://user-images.githubusercontent.com/62946723/94600264-56d5bf80-029a-11eb-9edd-067049e6988b.png" width=48%>

**Environment:**
Kotest 4.2.5
Kotest Plugin 1.1.16-IC-2019.3
Windows 10
Android Studio 4.0.1

**Comment by sksamuel** [comment]
It's in the latest build. 
[Uploading kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip…]()

It just hasn't been released to the plugin store yet.

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip](https://github.com/kotest/kotest/files/5308104/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip)
See attached.

**Comment by qw0c** [comment]
Oh, my bad, I didn't think to search for similar issue in repository of kotest _plugin_:
https://github.com/kotest/kotest/issues/5479

Sorry for the duplicate.
And thank you for responding so quickly!
