### ISSUE TITLE
No option to run on-demand spec initialization in TestListener

### ISSUE THREAD

**Issue by alexfacciorusso** [kotest/kotest#1740]
## Example

Currently, it is not possible to run a test like that:
```
class MyTest : BehaviorSpec({
    listeners(
        MyListener
    )

    // [I need the listener to initialise something internal here, otherwise `MyClassUnderTest` initialiser will crash]

    val myClassUnderTest = MyClassUnderTest(...)

    Given("Something") {...}
    Given("Something else") {...}
})
```

Let's imagine `MyClassUnderTest` depends on an action performed before its creation.

That means there is no method in `MyListener` that gets called immediately or on demand, unless we use workarounds like putting the action we need to be performed immediately in the listener's `init` block, which is although not possible if the listener is an object instead of a class.

## Suggestions

I suggest a system to be able to mark in the spek if we want a listener to run a method immediately.
For example, it might be possible to add a boolean parameter in the `listener` method to immediately execute `prepareSpec` on that listener:

```
class MyTest : BehaviorSpec({
    listener(MyListener, immediatelyCallPrepareSpec=true)
    // here `prepareSpec` gets called

    val myClassUnderTest = MyClassUnderTest(...)

    // rest of the test, but prepareSpec doesn't get called anymore
})
```

Or another possibility could be marking the point where we want to call the `prepareSpec` in the spec itself:

```
class MyTest : BehaviorSpec({
    listeners(MyListener, ...)

    prepareSpec() // here all the listeners' `prepareSpec` functions get called

    val myClassUnderTest = MyClassUnderTest(...)

    // rest of the test, but `prepareSpec` doesn't get called anymore
})
```

I am aware that we could use `lateinit`s there but I think the code in the suggestions would look way cleaner with no separate declaration of the variables of the test and initialisation in a different block.

**Comment by sksamuel** [comment]
This can be solved by just using a class for the listener, and having code in the init block as you mentioned.

Isn't that exactly what the init block is for ?

**Comment by alexfacciorusso** [comment]
Definitely we can use the init for setting up the test, but it feels weird to have side effects in a constructor. 

I will add a more significant example later, and if we think having the "before" part of the test in the `init` block of the listener we could close this issue and maybe add an example in the documentation to make the approach clearer, especially because it affects Android-related unit tests.

**Comment by alexfacciorusso** [comment]
Here it is a better example.

```
object UtilObject {
    var string: String? = null

    fun printStringIfNotNull() = println(requireNotNull(string))
}

class ClassToTest {
    fun doSomething() {
        UtilObject.printStringIfNotNull()
    }
}

class MyListener: TestListener  {
    init {
        UtilObject.string = "SomethingNotNull"
    }

    override suspend fun afterSpec(spec: Spec) {
        super.afterSpec(spec)
        UtilObject.string = null
    }
}

class DashboardViewModelTest : BehaviorSpec({
    listener(MyListener())

    val classUnderTest = ClassToTest()

    Given("Something"){
        Then("The class prints"){
            classUnderTest.doSomething()
        }
    }
})
```

Imagining that `ClassToTest` and `UtilObject` are part of the Android framework, which we can't change, otherwise by using inversion of dependencies instead of an object there would solve the problem (and many others).

Is that the solution you're suggesting @sksamuel?

**Comment by sksamuel** [comment]
Having a var inside an object is pretty horrible to start with.

What about adding some kind of initializer and finalize methods to the test listener interfaces?

Then when you call listener or register it runs the initialize method.
And the finalize method can be called when the spec is complete, or when the engine completes.

**Comment by sksamuel** [comment]
You may be able to accomplish this already by just having your listener implement ProjectListener as well.

**Comment by alexfacciorusso** [comment]
> Having a var inside an object is pretty horrible to start with.

Yes I agree, that was just a simplification over what is happening with the `LiveData` `TaskExecutor` in Android, in reality is not as bad but the behaviour is similar.

> You may be able to accomplish this already by just having your listener implement ProjectListener as well.

but then I would have to assign the project listener to the whole project configuration to make it be called I suppose, which is not something a dev might want.

>What about adding some kind of initializer and finalize methods to the test listener interfaces?
>
>Then when you call listener or register it runs the initialize method.
>And the finalize method can be called when the spec is complete, or when the engine completes.

Yeah this is what I was thinking, something like that, adding a method to the interface and then calling it as soon as the listener is registered.
I wonder if the finalize method is actually needed, since I think that `finalizeSpec` or `afterSpec` might be enough for most usecases?

**Comment by sksamuel** [comment]
So if we introduce a new extension point, `interface RegistrationExtension` or something, you could extend this interface, and be notified whenever someone has added it to a spec.

It would differ from beforeSpec, as beforeSpec is called after all the initialization of a class has taken place.
