### ISSUE TITLE
Kotlin/Native support

### ISSUE THREAD

**Issue by GlassBricks** [kotest/kotest#1743]
Kotest currently works with Kotlin JVM and JS (#242). Are there any plans to also support Kotlin/Native as well (framework api + runner)?

This would allow Kotest to be used with multiplaform projects/libraries/mobile, as well as with Kotlin/Native target itself.

**Comment by GlassBricks** [comment]
Also, currently, in a multiplatform project with native target, putting a Kotest Spec in commonTest fails when trying to compile/run native test (`> Could not resolve io.kotest:kotest-framework-api:4.2.5.`)

**Comment by sksamuel** [comment]
It needs someone with knowledge of native to pick it up and build it out.

**Comment by GlassBricks** [comment]
I did some investigation into this, and here is some of what I found:
- Kotlin Native test discovery is handled by the [_compiler_](https://github.com/JetBrains/kotlin-native/blob/v1.4.10/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/TestProcessor.kt), which generates top-level initializers to register/process test classes. The tests are run using a test executable, with a [custom `main`](https://github.com/JetBrains/kotlin-native/tree/v1.4.10/runtime/src/main/kotlin/kotlin/native/internal/test). Test filters are passed in through the command line.
- Another kotlin testing library, [Spek](https://github.com/spekframework/spek/), also supports Kotlin/native tests, which might provide some inspiration. It has:
  - A compiler plugin for test discovery, similar to Kotlin/Native tests
  - A runtime library with a custom `main`
  - A gradle plugin which integrates the compiler plugin, and brings a gradle task which compiles and runs the custom executable
- It might be possible, instead of creating a custom compilation, to have a compiler plugin integrate/hack into Kotlin native's current test system, as all the related classes are public; but this will depend on (public visibility) api in the conspicuously named `internal` package. The advantage is that Kotest tests can then run alongside "normal" kotlin native tests. Perhaps we should ask Jetbrains/the kotlin team if there is a stable way to integrate 3rd party test runtimes.

**Comment by quenio** [comment]
Both Kotest and its plugin do not support multi-platform libraries / apps. It is not possible to put tests in the commonTest directory, nor execute the tests from IntelliJ when you put the tests on jvmTest.

**Comment by piotrhermanowicz-silvair** [comment]
Still not working for iOS. After adding library and simple test `"name" shouldBe "name"` in common folder, android works just fine but iOS throws error.

```e: Compilation failed: Backend Internal error: Exception during IR lowering
File being compiled: /Users/runner/work/kotest/kotest/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/decreasing.kt
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)
 * Source files: 
 * Compiler version info: Konan: 1.4.30 / Kotlin: 1.4.30
 * Output kind: STATIC_CACHE
 ```

Edit: After some tests it turns out that this was fixed in kotlin 1.4.31 :)

**Comment by charleskorn** [comment]
Are there any plans to support native ARM targets such as `linuxArm64` or `macosArm64`? (Happy to open a separate issue for this if you'd prefer.)

**Comment by sksamuel** [comment]
We will support anything we can - if you could open a PR adding those targets we can merge in (doesn't have to be all modules).

**Comment by charleskorn** [comment]
> We will support anything we can - if you could open a PR adding those targets we can merge in (doesn't have to be all modules).

Done: #2449 

This is a draft until a [new version of kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines/pull/2904) is published with macOS ARM targets.
