### ISSUE TITLE
Arb should generate a single value

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1754]
Epic issue for the work @myuwono has been doing to: 
update Arbs to return only a single value rather than a sequence.
deprecate old arb builders, add new arb builders
fix flat map on arbs
deprecate distinct

**Comment by sksamuel** [comment]
I am thinking of releasing 4.3RC this week.
@myuwono do you think the arbs work is ready to go, or would we want to change edgecases too first ?

**Comment by myuwono** [comment]
@sksamuel sounds good! i think we should be good with the arbs work. Let's discuss edgecases separately after 4.3
