### ISSUE TITLE
VS Code support

### ISSUE THREAD

**Issue by izhangzhihao** [kotest/kotest#1770]
It would be great if we could have VSC support, related to https://github.com/microsoft/vscode-java-test/issues/975

**Comment by sksamuel** [comment]
If someone wants to create a plugin that would be great, but it's unlikely to be something the core kotest team tackles.

**Comment by BorzdeG** [comment]
Maybe not close the issue, but mark it as waiting for contributors?

**Comment by jschneidereit** [comment]
Bloop, I have interest in taking a look at this in the next month or two

**Comment by cjpoulsen** [comment]
@jschneidereit had any luck getting it off the ground?

**Comment by jschneidereit** [comment]
Let's try that again, totally dropped off my radar! 😂

**Comment by cjpoulsen** [comment]
I will be eagerly waiting to test a pre-alpha prerelease lol!

**Comment by jschneidereit** [comment]
@cjpoulsen do you recommend any plugins for debugging kotlin in vscode?

**Comment by cjpoulsen** [comment]
> @cjpoulsen do you recommend any plugins for debugging kotlin in vscode?

Have you tried the Debugger for Java￼ extension?

**Comment by joaosouza-dev** [comment]
any updates on this?
