### ISSUE TITLE
Add utility overload functions for creating Tuples with various number of fields

### ISSUE THREAD

**Issue by driver733** [kotest/kotest#1780]
Since the resolution of the issue #1773 it has become possible to use the `forAll` function with more than seven params. However, a specific variant of a Tuple class that corresponds to the number of parameters has to be specified. This is not convenient: the specified variant of a Tuple class needs to be changed every time the number of params is changed in a test.
This problem can easily be solved by adding the following overload functions that will create a variant of a Tuple class that corresponds to the number of params. In addition, it will also improve the readability of the tests that use the `forAll` function with `Tuple`s.

```
fun <A> tuple(a: A) = Tuple1(a)
fun <A, B> tuple(a: A, b: B) = Tuple2(a, b)
fun <A, B, C> tuple(a: A, b: B, c: C) = Tuple3(a, b, c)
...
fun <A, ..., Z> tuple(a: A, ... ,z: Z) = Tuple22(a, ... , z)
```

That would allow using the `Tuple` classes more conveniently:

```
forAll(
  tuple("a")
)

forAll(
  tuple("a", "b")
)

forAll(
  tuple("a", "b", "c")
)
```

instead of

```
forAll(
  Tuple1("a")
)

forAll(
  Tuple2("a", "b")
)

forAll(
  Tuple3("a", "b", "c")
)
```

**Comment by ashishkujoy** [comment]
Done
