### ISSUE TITLE
Spring test annotation @Sql does not apply the given fixture

### ISSUE THREAD

**Issue by Partyschaum** [kotest/kotest#1782]
**Which version of Kotest are you using**

I use 4.2.6.

**The problem**

When I annotate the test case of `AnnotationSpec` with `@Sql` it seems that it's not recognized:

```
    @Test
    @Sql("/de.shinythings.hexagon.adapter.persistence/ActivityRepositoryTest.sql")
    fun `test this`() {
        val depositBalance = activityRepository.depositBalanceUntil(
                accountId = 1,
                until = LocalDateTime.now()
        )

        depositBalance shouldBe 2000
    }
```

You can find the full example [here](https://github.com/Partyschaum/kotlin-spring-boot-multi-project/blob/kotest-sql-annotation-issue/adapters/persistence/src/test/kotlin/de/shinythings/hexagon/adapter/persistence/ActivityRepositoryKoTest.kt)

When I write the [same test using JUnit5](https://github.com/Partyschaum/kotlin-spring-boot-multi-project/blob/kotest-sql-annotation-issue/adapters/persistence/src/test/kotlin/de/shinythings/hexagon/adapter/persistence/ActivityRepositoryTest.kt) it works and in the debug log output I see _Executing SQL scripts: [class path resource [de.shinythings.hexagon.adapter.persistence/ActivityRepositoryTest.sql]]_. In the log output during a test run with the `AnnotationSpec` I can't see a message like this.

**Expected behavior**

The `@Sql` annotation is evaluated and the fixture is loaded into the db.

Bonus question: I prefer using the `DescribeSpec` but I had no clue how to apply annotations there. Is this even possible?

**Comment by sksamuel** [comment]
You need to use the spring extension with kotest.
Adding the annotation is not sufficient.
Take a look at https://kotest.io/docs/framework/extensions.html#spring
