### ISSUE TITLE
Flow assertions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [kotest/kotest#1785]
Similar to https://github.com/kotest/kotest/pull/1783, should be great to have assertions for `Flow`

**Comment by JavierSegoviaCordoba** [comment]
@LeoColman I think this should be reopened

**Comment by dalewking** [comment]
There is a good library for testing flows: https://github.com/cashapp/turbine

**Comment by sksamuel** [comment]
Closing this as turbine fills this need perfectly.
