### ISSUE TITLE
shouldContainJsonKeyValue does not work as expected with Number's

### ISSUE THREAD

**Issue by tekener** [kotest/kotest#1790]
**Which version of Kotest are you using**
4.3.0

**Descripton:**
The problem is that containJsonKeyValue is comparing by `JsonPath.read<T>(value, path) == t`. What is in this case a `Int == Long`
```
import io.kotest.assertions.json.shouldContainJsonKeyValue
 """{"version":1}""".shouldContainJsonKeyValue("$.version", 1L)

/ /java.lang.AssertionError: {"version":1} should contain the element $.version = 1
```

**Comment by tekener** [comment]
Will create a PR with the fix in the next days

**Comment by ashishkujoy** [comment]
Fixed in master

**Comment by tekener** [comment]
@ashishkujoy thank you for fixing that, had no time for that in the last weeks
