### ISSUE TITLE
Add matchers for Atomic Booleans

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1791]
AtomicBoolean(false).shouldBeTrue()

AtomicInteger(123).shouldBeLessThan(555)

And so on.

**Comment by simonenkoi** [comment]
@sksamuel I see possible problems with the maintainability of such a feature. For example, if we add a new assertion on the type, it will be expected to have the same one for the atomic type.
Do we need to support all the assertions defined on the `V` type accessible from `AtomicReference<V>,` not only predefined `AtomicBoolean,` `AtomicInteger,` etc.?
`AtomicBoolean(false).get().shouldBeTrue()` syntax looks clear from my point of view, and, as a user, I guess it will confuse more than help. Please, share your thoughts.

**Comment by sksamuel** [comment]
Yes, that's a good point.
Maybe just one for the booleans would be sufficient. I was using atomics this morning, and `atomic.get().shouldBeTrue()` was more verbose than I wanted, when `atomic.shouldBeTrue()` would have been a tiny bit nicer.

**Comment by Megamiun** [comment]
Is anyone working on it? If not, I can do it. Should we just make `shouldBeTrue` and `shouldBeFalse`?

**Comment by sksamuel** [comment]
Please feel free to pick this up. and yes those two matchers.
