### ISSUE TITLE
FeatureSpec support for Gherkin feature files

### ISSUE THREAD

**Issue by abayibrayev1** [kotest/kotest#1806]
Is it possible to connect my existing Gherkin scenarios and provide BDD steps using Kotest syntax? Does **FeatureSpec** supports or gonna support in future this approach? 

Couldn't find info in docs, so I guess framework doesn't have this feature. 

Thanks in advance!

**Comment by LeoColman** [comment]
We had this discussion a long, long time ago at https://github.com/kotest/kotest/issues/561

Maybe we should bring it up again?

**Comment by sksamuel** [comment]
Wow I was quite passionate in #561 lol

**Comment by sksamuel** [comment]
Is this comment about having a different layout for specs or wanting to read from files like cucumber does @abayibrayev1

**Comment by abayibrayev1** [comment]
Hi thanks for the answer! I actually want to read from .feature files, like cucumber it does. 

Am i right, that kotest doesn't support it? 
Do u have any plans to support it in future? 
And may be u could suggest another way to impl bdd specs to separate non-technical layer from tests?

Thanks in advance!!👍

**Comment by LeoColman** [comment]
> Am i right, that kotest doesn't support it?

You're correct, Kotest doesn't support it at the moment.

>  Do u have any plans to support it in future?

At this moment we don't have any plans. We currently believe that BehaviorSpec, Data Testing and Property Testing all do a better job than translating a feature file.

If you could propose a way on how things should look like, maybe we can look into it for a `GherkinSpec` of some sort!

**Comment by abayibrayev1** [comment]
> If you could propose a way on how things should look like, maybe we can look into it for a `GherkinSpec` of some sort!

I'm not sure if I can draw how things should work for kotest + gherkin, sorry. And thanks for u fast replies!  
(If u don't mind I will close feature request, cuz I'm not able to suggest comprehensive flow for this feature)
