### ISSUE TITLE
Update documentation for logging

### ISSUE THREAD

**Issue by KeremAslan** [kotest/kotest#1812]
I noticed the documentation lacks a description on how to enable logging. I had to dig through the code and GH issues to find it. 

Something like this at the appropriate place in the documentation should do:

> Enable logging by passing KOTEST_DEBUG=true as a VM argument. 

I can submit an MR, but not sure what the appropriate place would be.

**Comment by ashishkujoy** [comment]
I think we should create a dedicated page to include all system properties which kotest looks for and their purpose.

For example [these](https://github.com/kotest/kotest/blob/2395311f0f317c09c545cb728e5e23e7d29fa6d3/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/internal/KotestEngineSystemProperties.kt) are various system properties to control some kotest engine features. Having a dedicate page will sure help user to understand what all things are possible to tweak.

**Comment by sksamuel** [comment]
Good idea @ashishkujoy

**Comment by frikit** [comment]
@sksamuel and @ashishkujoy maybe will be better to generate a markdown at gradle build phase from kotlin file(Like a code snippet to include full kotlin file as is and javadoc will serve as documentation in this case)?? What do you think?

**Comment by sksamuel** [comment]
I like that idea @frikit

**Comment by frikit** [comment]
@sksamuel Can I work in this issue?

**Comment by sksamuel** [comment]
Absolutely.

**Comment by frikit** [comment]
took me forever but finally got couple of hours in the evening and make a quick implementation in PR https://github.com/kotest/kotest/pull/1881

**Comment by frikit** [comment]
As the changes are merged, should we close the issue now? @sksamuel ?
