### ISSUE TITLE
[DescribeSpec] Add functionality to use 'it' without surrounding 'describe'

### ISSUE THREAD

**Issue by huehnerlady** [kotest/kotest#1827]
Hi,

It is great to have the functionality to add nesting int he test classes. The describe is a big help.
But sometimes you have just a couple of tests in a class and there the describe block does not make sense per se.

So I would suggest that the describe spec is enhanced so the test starting with `it` can be used without a surrounding describe block.

**Comment by ashishkujoy** [comment]
Added in master
