### ISSUE TITLE
Using a symbol or Japanese etc in the test name will change the behavior

### ISSUE THREAD

**Issue by matsudamper** [kotest/kotest#1828]
**Which version of Kotest are you using**
4.3.1

# Problem
I confirmed the same problem with BehaviorSpec.

execute "c". "a" beforeEach is not called.
execute "♬". "☆" beforeEach is called.
```kotlin
class SuccessDescribeSpec : DescribeSpec({
    context("a") {
        beforeEach {
            // not call
            throw IllegalStateException("")
        }
    }

    context("b") {
        it("c") {
        }
    }
})

class FailDescribeSpec : DescribeSpec({
    context("☆") {
        beforeEach {
            // called
            throw IllegalStateException("")
        }
    }

    context("♪") {
        it("♬") {
        }
    }
})
```

**Comment by matsudamper** [comment]
Information seems to disappear here
Is there any reason why it should be within the range?
https://github.com/kotest/kotest/blob/c83b3d791905b445b951786f4b6435349f68bdcc/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/test/Description.kt#L16
https://github.com/kotest/kotest/blob/c83b3d791905b445b951786f4b6435349f68bdcc/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/test/Description.kt#L142-L146

test breaks silently
```kotlin
class SuccessDescribeSpec: DescribeSpec({
   var count = 0

   context("one_two") {
      beforeEach {
         count++
      }
   }

   context("one two") {
      it("count is 1") {
         assert(count == 1)
      }
   }

   context("one two!") {
      it("count is 2") {
         assert(count == 2)
      }
   }
})
```

**Comment by sksamuel** [comment]
Good find thanks. The id can be changed to be a uuid then it will work.

**Comment by matsudamper** [comment]
It seems that the description is not only generated once.
Therefore, the name could have been used.
Would it be better to generate a UUID based on the name?

https://github.com/kotest/kotest/blob/c83b3d791905b445b951786f4b6435349f68bdcc/kotest-common/src/commonMain/kotlin/io/kotest/mpp/uuid.kt#L1-L6

add
```kotlin
expect fun uniqueId(fromName: String): String 
```

**Comment by sksamuel** [comment]
Some integrations don't like certain characters.

**Comment by aids61517** [comment]
It's also happened when using Chinese in test name.
