### ISSUE TITLE
unexpected java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by christophsturm** [kotest/kotest#1830]
this is with kotest 4.3.1 but also happens with 4.4 snapshot

this test case:
```package r2dbcfun
import io.kotest.core.spec.style.FunSpec
import java.io.StringReader
import kotlin.reflect.full.declaredMemberProperties
class Ko2Test : FunSpec({
    listOf(1).forEach {
        context("ctx") {
            autoClose(StringReader("blah"))
            data class K(val name: String)
            K::class.declaredMemberProperties
        }
    }
})
```
throws a java.lang.NoClassDefFoundError: r2dbcfun/Ko2Test$1$1$1 in the K::class.declaredMemberProperties line.

if I change the ´forEach´ to ´forAll´ it works.

**Comment by sksamuel** [comment]
Moving the data class up a level works, as does swapping around the order of the list and the context call. It must be something to do with the managed classname that is used for classes declared in lambdas.

**Comment by sksamuel** [comment]
Bizarrely, removing the autoclose fixes it too.
