### ISSUE TITLE
Unexpected ToleranceMatcher behavior at infinite doubles

### ISSUE THREAD

**Issue by sielenk-yara** [kotest/kotest#1832]
**Which version of Kotest are you using**
4.3.1

Mathematically I would expect

    checkAll(Arb.positiveDoubles()) { eps ->
      Double.NEGATIVE_INFINITY shouldBe (Double.NEGATIVE_INFINITY plusOrMinus eps)
      Double.POSITIVE_INFINITY shouldBe (Double.POSITIVE_INFINITY plusOrMinus eps)
    }

to succeed. But Kotest fails with

    Property test failed for inputs

    0) 1.0

    Caused by java.lang.AssertionError: -Infinity should be equal to -Infinity within tolerance of 1.0 (lowest acceptable value is -Infinity; highest acceptable value is -Infinity) at
	[...]
	io.kotest.property.internal.ProptestKt$proptest$$inlined$forEach$lambda$1.invokeSuspend(proptest.kt:32)
	io.kotest.property.internal.ProptestKt$proptest$$inlined$forEach$lambda$1.invoke(proptest.kt)

**Comment by sksamuel** [comment]
4.3.2 is released with this fix.
