### ISSUE TITLE
Add inline version of instanceOf to simplify usage

### ISSUE THREAD

**Issue by dmstocking** [kotest/kotest#1836]
I would like to add a version of instanceOf that looks like

    inline fun <reified T: Any> instanceOf(): Matcher<Any?> = instanceOf(T::class)

So that the call site goes from

    instanceOf(SomeType::class)
    // to
    instanceOf<SomeType>()

It is a minor addition and would just remove the need for `::class`. This is already done `beInstanceOf` and `beOfType`. This would just do the same thing for the `instanceOf` alias.

**Comment by sksamuel** [comment]
Sounds good.
