### ISSUE TITLE
Test a multiplatform module

### ISSUE THREAD

**Issue by Savrov** [kotest/kotest#1837]
Hello, I have a question. 
First of all, thank you for a wonderful tool. I like to use it in all my projects, even in multiplatform. So the question if there will be full support of Kotlin MPP? I know, that now I can write code in `mainTest`, then write tests for it in `jvmTest` and run it. 
But as I do understand, it won't trigger test in my CI/CD pipeline for Linux project. 
Wish to know if you have in plans full multiplatform support? And if Yes, when we can expect it?
Thank you.

**Comment by sksamuel** [comment]
I'm confused by your question because we use MPP on kotest itself. You can see in the github actions file that we run builds for windows, mac and linux, for java / javascript and native. Was there something specific you needed? Or are you referring to native support on the test engine?

**Comment by Savrov** [comment]
Sorry, I just did know that it is available. Now it's clear after checking out your Actions. Thanks

**Comment by sksamuel** [comment]
Great.
