### ISSUE TITLE
Kotlin API Version changed to 1.4 in 4.3.1

### ISSUE THREAD

**Issue by U1F984** [kotest/kotest#1840]
When upgrading from version 4.3.0 to 4.3.1 our tests broke because of #1801: in `kotest-assertions/kotest-assertions-shared/build.gradle.kts` the `apiVersion` was changed to 1.4. While kotest 4.4 will require Kotlin 1.4 anyway, upgrading to Kotlin 1.4 in a minor release seems like an accident (especially since it is not mentioned in the changelog).

**Comment by sksamuel** [comment]
Yes an accident. Wasn't planned until 4.4 will released 4.3.2 with this
change reverted.

**Comment by sksamuel** [comment]
4.3.2 is out with 1.3 compatibility.
