### ISSUE TITLE
kotest.parallelism System Property not Working

### ISSUE THREAD

**Issue by piacenti** [kotest/kotest#1841]
**Which version of Kotest are you using**
4.3.1

I have the following on my gradle config 
```
test {
    useJUnitPlatform()
    systemProperties["kotest.parallelism"] = 4
}
```
However it doesn't seem to be picked up
```
-> Parallelization factor: 1
-> Default test timeout: 600000ms
-> Default test order: Sequential
-> Default isolation mode: SingleInstance...
```
If I use the code configuration option it works fine but I have a shared gradle config that is used by 3 modules that I would rather use than adding a config code block in each one of those projects and keeping them in sync.

Also while debugging tests and checking system properties kotest.parallelism is not even set at all. I'm I supposed to pass the property to the kotest runner in a different way?

**Comment by ashishkujoy** [comment]
@piacenti the system property for controlling parallelism is `kotest.framework.parallelism`

**Comment by ashishkujoy** [comment]
It seems to a typo in doc, will correct that.

**Comment by piacenti** [comment]
@ashishkujoy I actually tried `kotest.framework.parallelism` since I found it mentioned in the source code but found no mention of the one from the docs. It hadn't worked for me in the test properties but I tried it again. As part of the test properties it doesn't do anything, however, if I run gradle with that VM property in the IDE then it works correctly. So I take it that the runner engine doesn't read properties passed to tests just properties passed to gradle. I'm using gradle `6.6.1`

**Comment by piacenti** [comment]
@ashishkujoy Ok I think I found the issue I was having. Clicking on the gutter play button to run individual tests from the IDE with the kotest plugin it uses the runner directly bypassing gradle so any properties set there are just ignored. If I run a test or check task in gradle then it properly read the properties
