### ISSUE TITLE
Global timeouts not applied to JS tests

### ISSUE THREAD

**Issue by Noctiflore** [kotest/kotest#1848]
Using Kotest 4.3.1 & Kotlin Multiplatform 1.4.10, I added the following to build.gradle.kts to set timeouts:
```kotlin
tasks.withType<Test> {
    systemProperty("kotest.framework.timeout", 20)
    systemProperty("kotest.framework.invocation.timeout", 10)
}
```
(I've chosen small values for testing only).

Timeouts set this way are enforced in JVM tests, but not in JS tests.
Is there another (global) option to set it for JS tests?

**Comment by ashishkujoy** [comment]
no for js platform we cannot use system properties.

**Comment by sksamuel** [comment]
You can set the global timeout using the config object.

So somewhere in your code, you will need to call `configuration.timeout = foo`
