### ISSUE TITLE
Add shouldContainOneWhere

### ISSUE THREAD

**Issue by saibotma** [kotest/kotest#1852]
Checks that an iterable contains just one element that matches a condition.

**Comment by ashishkujoy** [comment]
you can use `shouldHaveSingleElement`

https://github.com/kotest/kotest/blob/3dac78ddea7785386d4f1f700969f9e6070fa251/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/matchers.kt#L39
