### ISSUE TITLE
withClue does not work for third-party-assertions

### ISSUE THREAD

**Issue by enolive** [kotest/kotest#1853]
I am using Kotest 4.3.1. I noticed that `withClue` seems only to work for kotest assertions, for example shouldBe. It does not work for matchers from other assertion libraries. 

For instance, Spring Webflux brings some nice assertions to verify the response of a web client call:

```kotlin
withClue("Won't be shown") {
  response.expectStatus().isEqualTo(HttpStatus.I_AM_A_TEAPOT)
  // this obviously works as it uses the kotest assertions. might be a custom matcher extension?
  // response.exectStatus().value { it shouldBe HttpStatus.I_AM_A_TEAPOT.value() }
}
```
or the verify assertions from mockk:

```kotlin
withClue("Won't be shown") {
  verify(exactly = 42) { service.call() }
  // no idea how to circumvent this problem here
}
```

Is it supposed to work on other assertion libraries as well? (I could imagine that it might catch common assertion errors and enrich them with additional information).

If not, I'd suggest to put the same warning into the documentation as in the Assertion Mode section.

**Comment by sksamuel** [comment]
It should work with anything that throws an assertion error.

**Comment by enolive** [comment]
I'll upload a little demo project for reproduction purposes to my github repo later

**Comment by enolive** [comment]
here is my little reproduction project:

https://github.com/enolive/kotest-clue-repro/blob/master/src/test/kotlin/de/welcz/kotestcluerepro/ApplicationTests.kt

As you can see, there are everal test cases defined that all fail for some reason (such as 404 returned instead of 200). Don't bother about the first smoke test. The only test that actually shows the clue in case of a failure is the second one.

**Comment by sksamuel** [comment]
Thanks.

I've had a play and it's not trivial to make this work outside of kotest.

It could work without nested clue support, but that means removing a feature.

The best we could do is introduce another set of clues that work with non-kotest assertions?

**Comment by enolive** [comment]
Thanks for your Feedback! Honestly I was just curious if it is supposed to work because I could not find any information in the docs stating otherwise. The only use case I could actually think of for using clues for different assertion libs would be to better document my test assertions like in groovy spock without a nested structure like in BehaviourSpec:

```groovy
def "todo can be created"() {
    given: "a todo to be saved"
    def toSave = new Todo(title: "Plz save me")

    when: "todo is saved"
    def result = sut.save(toSave).block()

    then: "result has expected properties"
    result != null
    result.id != null
    result.title == toSave.title
    and: "todo can be queried"
    sut.findById(result.id).block() == result
  }
```

complete code (inside a direct comparison repo between reactive programming style in kotlin and java):

https://github.com/enolive/kotlin-coroutines/blob/master/todos-java/src/test/groovy/de/welcz/todosjava/TodosRepositoryTest.groovy

The naive implementation of a similar assertion error aware wrapper seems to be quite easy:

```kotlin
fun Error.enrichMessageWithReason(reason: String) = AssertionFailedError(
    "$reason\n$message",
    this
  )

  suspend fun becauseOf(reason: String, block: suspend () -> Unit) {
    try {
      block()
    } catch (error: Error) {
      when (error) {
        is AssertionError, is AssertionFailedError -> throw error.enrichMessageWithReason(reason)
        else                                       -> throw error
      }
    }
  }

test("fail with clue using webTestClient assertion") {
    val response = webTestClient
      .get()
      .uri("/notexisting")
      .exchange()

    becauseOf("The response status needs to be successful") {
      response.expectStatus().isOk
    }
  }
```

but I am having some headaches how to fit it beside kotest clues without inventing new terminology or having serious naming conflicts

**Comment by sksamuel** [comment]
I guess with clues you are still identing though? But I see what you want to do.

Perhaps you want some clue that you can add without an ident block.

```
test("fail with clue using webTestClient assertion") {

    val response = webTestClient
      .get()
      .uri("/notexisting")
      .exchange()

    withStep("foo")
    response.expectStatus().isOk

    withStep("bar")
    response.expectStatus().isOk
  }
```

**Comment by sksamuel** [comment]
I've updated the docs page to make it clear it requires kotest test framework / assertions.

**Comment by vojtapol** [comment]
@sksamuel Was this the note you added to documentation?

![image](https://user-images.githubusercontent.com/7419355/103910591-dc4ae600-50b9-11eb-98cb-0ae5b8baa432.png)


If that is the case I believe it might be misleading unless I am misunderstanding something. I am using just the assertion library (not the test framework) together with JUnit 4 and the clues work perfectly. Maybe the note should be reworded?

As a new user who is only interested in Kotest's assertions the note would turn me off using this library at all.

**Comment by sksamuel** [comment]
You wouldn't use an assertions library if the clues wasn't supported?

I think it's nested clues that doesn't work outside of kotest.

**Comment by vojtapol** [comment]
> You wouldn't use an assertions library if the clues wasn't supported?

Correct. We are currently using `Kluent` and looking to switch to `kotest-assertions` only because of the clues feature. We are still happy with JUnit though so that would stay.

**Comment by sksamuel** [comment]
Yes makes sense.
