### ISSUE TITLE
Styles in commonTest package

### ISSUE THREAD

**Issue by Savrov** [kotest/kotest#1856]
Hello,
As I do understand, **kotest** and **kotlintest** are the same projects with different packages. Now, I have found a [repository with a sample](https://github.com/kotlintest/kotlintest-example-multiplatform/blob/master/src/commonTest/kotlin/io/kotlintest/example/mpp/FibBehaviorTest.kt) for **kotlintest** and there I noticed, that "styles" can be used in `commonTest` package. But this feature is not available now, its only available for `jvmTest` and `jsTest`. Could you please roll this feature back?

**Comment by sksamuel** [comment]
You can use a test style in commonTest if you have a target of jvmTest or jsTest for that module.

**Comment by Savrov** [comment]
I had a bad setup. Now it works, can u pls verify that my Gradle now is correct and does not contain useless/redundant dependencies:
```
kotlin {
    jvm()

    sourceSets {
        val commonMain by getting {
            dependencies {
                // some dependeinces
            }
        }
        val commonTest by getting {
            dependencies {
                implementation("io.kotest:kotest-framework-api:4.2.5")
                implementation("io.kotest:kotest-assertions-core:4.2.5")
            }
        }
        val jvmTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(kotlin("test-junit"))
                implementation("io.kotest:kotest-runner-junit5-jvm:4.2.5")
                implementation("io.kotest:kotest-property-jvm:4.2.5")
            }
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```

**Comment by sksamuel** [comment]
Looks good to me.
