### ISSUE TITLE
BehaviorSpec Then assertion shows green in Intellij but should show red

### ISSUE THREAD

**Issue by HoffiMuc** [kotest/kotest#1857]
I am using kotlin 1.4.10 ;  micronaut-bom:2.1.3 ; micronaut-test-kotest:2.2.1 and kotest-runner-junit5-jvm:4.2.5

running this most simple BehaviorSpec:

```kotlin
@MicronautTest
class DummySpec(
) : BehaviorSpec({

    Given("dummy test") {
        When("dummy test is executed") {
            Then("dummy test just should fail") {
                1 shouldBe 2
                "x" shouldBe "y"
            }
        }
    }
})
```

EDIT:
I updated to kotlin 1.4.20 and micronaut 
even though the overall Test fails, in Intellij (with kotest plugin 1.1.20-IC-2020.2)<br/>
the `Then` part shows green (see screenshot)

<img width="980" alt="Screenshot" src="https://user-images.githubusercontent.com/3447236/99902531-c1b1de80-2cbe-11eb-80eb-0db773c12838.png">

I have the following ProjectConfig:

```kotlin
package io.micronaut.test.kotest

import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.spec.IsolationMode
import io.micronaut.test.extensions.kotest.MicronautKotestExtension

object ProjectConfig : AbstractProjectConfig() {
    override val isolationMode = IsolationMode.SingleInstance
    override val globalAssertSoftly = true

    override fun listeners() = listOf(MicronautKotestExtension)
    override fun extensions() = listOf(MicronautKotestExtension)

    override fun beforeAll() {
        println("ProjectConfig beforeAll Tests:")
        println(String.format("    isolationMode = %s\n    globalAssertSoftly = %b", isolationMode.name, globalAssertSoftly))
    }

    override fun afterAll() {
        println("ProjectConfig afterAll Tests:")
        println(String.format("    isolationMode = %s\n    globalAssertSoftly = %b", isolationMode.name, globalAssertSoftly))
    }
}
```

is this a bug, or am I missing something here?

EDIT: I updated to kotlin 1.4.20 and micronaut 2.2.0 ... still the same

**Comment by sksamuel** [comment]
I get this:

![image](https://user-images.githubusercontent.com/743706/102225434-d5f78e80-3eac-11eb-991d-77da30238d40.png)


Can you try that dummy test but removing the @MicronautTest annotation ?
Just to see where the error might be.

**Comment by HoffiMuc** [comment]
same result without `@io.micronaut.test.extensions.kotest.annotation.MicronautTest` again.

`Given` failed, but `When` and `Then` are still green!

(did this using most recent IntelliJ kotlin and kotest plugin)

Do you also have the ProjectConfig set to:

```
object ProjectConfig : AbstractProjectConfig() {
    override val isolationMode = IsolationMode.SingleInstance
    override val globalAssertSoftly = true
```

??

**Comment by sksamuel** [comment]
I get a similar error with global assert softly.

![image](https://user-images.githubusercontent.com/743706/102875549-8e6f8600-4409-11eb-9031-5f77cc61b926.png)

So is probably related to that.
