### ISSUE TITLE
Question: Is having code outside of the Style's functions bad practice?

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#1858]
Hi guys,

we are using Kotest in our project for a long time, but I am still not sure, whether the following style is allowed:
```kt
class KotestDemoTest : StringSpec({

    // not constant; will be generated by code
    val myCommonValue = (1..100).first { it == 42 }  // <-- allowed?

    "test 1: exact" {
        myCommonValue shouldBe 42
    }

    val inbetweenValue = 4711 // <-- allowed?

    "test 2: odd" {
        myCommonValue shouldBe beEven()
    }

    "test 3: inbetween value" {
        inbetweenValue shouldBeGreaterThan 4000
    }
})
```
The manual section about [Styles](https://kotest.io/styles/) has a huge amount of examples, but in every one, only the Style's predefined functions for container/test are used. I did not find any example in the manual, looking like my above code example.

Often we have the situation, where some data is used by all of the tests inside the spec. The `beforeXXX()` methods however cannot return a value. Using them and a global variable would require `lateinit`, which I don't like.

The above code works as intended. But I am not sure, whether you explicitly allow this. I don't want to have hundreds of broken tests, if Kotest makes a change and afterwards this style doesn't work anymore.

Can you give my an answer to this question?
I would suggest, you also include the answer and such an example into the manual.

Thanks.

**Comment by sksamuel** [comment]
That's absolutely fine. In fact that's the reason Kotest doesn't have test fixtures, because you can just sprinkle local vals about, as you would any other function.

This will always be supported.

**Comment by theHacker** [comment]
Nice! Thank you for your reply.

Please add this to the manual, and let everybody know 👍
