### ISSUE TITLE
"until" missing in documentation under nondeterministic_testing

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#1859]
This section https://kotest.io/nondeterministic_testing I found super interesting, however, I would think "until" also belongs in that section, yet it isn't there.

**Comment by sksamuel** [comment]
Yes, good shout. Would you be able to create a PR ?

**Comment by sksamuel** [comment]
@jschneidereit if you wanted to start something :)

**Comment by jschneidereit** [comment]
I'll see what I can do! 👍

**Comment by sksamuel** [comment]
We're going to close this as we are going to revamp eventually for 4.4
