### ISSUE TITLE
Helper for temporary directory creation

### ISSUE THREAD

**Issue by dragneelfps** [kotest/kotest#1862]
Currently, we can create a temp file using `tempfile()`(https://github.com/kotest/kotest/issues/326) . But for directories there is not method.
I propose we add a new but similar extension function for temp directories.
Sample code: 
```
fun TestConfiguration.tempDir(): File {
    val dir = Files.createTempDir()
    afterSpec {
        dir.delete()
    }
    return dir
}
```

**Comment by sksamuel** [comment]
Sounds good. If you want to make the PR.
