### ISSUE TITLE
AssertionMode.Error doesn't work on FeatureSpec

### ISSUE THREAD

**Issue by aids61517** [kotest/kotest#1864]
version: io.kotest:kotest-runner-junit5:4.3.1
kotlin version: 1.4.10
Android Studio version: 4.1.1

assertion mode doesn't work on FeatureSpec, and `Tests passed` always equal to 0 even if I do assertion

```
class FeatureSpecTest : FeatureSpec({
  assertions = Error

  feature("Test feature") {
    scenario("test scenario") {
    }
  }
})
```

![image](https://user-images.githubusercontent.com/15688437/100196007-2b3a2300-2f33-11eb-9a25-c8763fc2c8e9.png)

In do assertion case: 

```
class FeatureSpecTest : FeatureSpec({
  assertions = Error

  feature("Test feature") {
    scenario("test scenario") {
      val a = 1
      a shouldBe 1
    }
  }
})
```
`Tests passed` still equal to 0
![image](https://user-images.githubusercontent.com/15688437/100196494-e4006200-2f33-11eb-8edd-d83975995bdc.png)

**Comment by ashishkujoy** [comment]
Fixed in master

**Comment by sksamuel** [comment]
4.3.2 is released with this fix.
