### ISSUE TITLE
"Quickstart" content for Android inconsistent with Sample App content

### ISSUE THREAD

**Issue by iainism** [kotest/kotest#1866]
Using 4.3.1 in Android Studio.  I have found that the dependencies needed in my app-level build.gradle are of the form:

```
dependencies {
    testImplementation("io.kotest:kotest-runner-junit5-jvm:<version>")
    androidTestImplementation("io.kotest:kotest-runner-junit5-jvm:<version>") {
        exclude(module: "objenesis")
    }
    androidTestImplementation("io.kotest:kotest-assertions-core-jvm:<version>")
```

As given in the sample app at https://github.com/kotest/kotest-android-samples/blob/master/app/build.gradle

Referring to those shown at https://kotest.io/quick_start/#gradle there are a few key differences:

```
dependencies {
    testImplementation 'io.kotest:kotest-runner-junit5:<version>' // for kotest framework
    testImplementation 'io.kotest:kotest-assertions-core:<version>' // for kotest core jvm assertions
    testImplementation 'io.kotest:kotest-property:<version>' // for kotest property test
}
```

Note that the sample-app dependencies work, those in the docs do not.

i.e. the suffix `-jvm` is required, and in some cases `androidTestImplementation` is required rather than `testImplementation`.  I'm new to testing and Android and this wasn't obvious to me, so apologies if this is something that someone more experienced would have worked out at a glance!

**Comment by sksamuel** [comment]
I don't know a lot about android, but is the difference between androidTestImplementation and testImplementation whether it is unit vs instrumented tests? Perhaps @alexfacciorusso could offer some guidance.

**Comment by alexfacciorusso** [comment]
Long story short: Android instrumented testing support for Kotest is not completely ready, and the sample you mentioned works but with many drawbacks. We are working on the support for Android Instrumented tests and when that will be definitely functioning properly, very probably a section specifically for Android will be added to the documentation.

The current Kotest documentation explains the configuration of **JVM** tests, which are the tests you can create in the `src/test` folder, and they should be configurable via the examples in the doc itself.

I will have a double check to ensure that's the case, maybe a suggestion might be to add a note to the documentation that the Android support is experimental as per now and that configuration is related to pure JVM tests.

**Comment by sksamuel** [comment]
I can add that to the docs if you can give me the sentence to write.
