### ISSUE TITLE
Problems with the double generator (Arb.Companion.double).

### ISSUE THREAD

**Issue by sielenk-yara** [kotest/kotest#1869]
**Which version of Kotest are you using**
4.3.1

The edge cases are incomplete:
Missing values are `-0.0` (negative zero), `-Double.MIN_VALUE`, `-Double.MAX_VALUE` and, since `1e300` is there, maybe also `-1e300`.

The random values are far from exhaustive:
They are generated with `nextDouble()` and are therefore ["[...] uniformly distributed between 0 (inclusive) and 1 (exclusive)"](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.random/-random/next-double.html).
A better choice would be `nextDouble(-Double.MAX_VALUE, Double.MAX_VALUE)`.

This in turn leads to problems with `Arb.Companion.negativeDoubles()` since, at the moment, there are exactly two values that can pass the filter `{ it < 0.0 }`. And trying to get 1000 values from that generator freezes the tests.

More details about what a nasty piece of work floating point numbers are can be found in 
- the [Java specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2.3) or
- the [IEEE 754 Standard for Floating-Point Arithmetic](https://en.wikipedia.org/wiki/IEEE_754)

See also #530, #1216

**Comment by sksamuel** [comment]
4.3.2 is released with this fix.
