### ISSUE TITLE
Release for watch os 32

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1884]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by sksamuel** [comment]
Watch/os 32 is now added to the build matrix.
It will be released with 4.3.2

**Comment by PaulWoitaschek** [comment]
Thanks!
It seems to appear only in the 4.4.x snapshot builds. Is this an oversight?
https://oss.sonatype.org/content/repositories/snapshots/io/kotest/kotest-assertions-core-watchosarm32/

**Comment by sksamuel** [comment]
Once 4.3.2 is released there will be a full build for it.

**Comment by sksamuel** [comment]
https://search.maven.org/artifact/io.kotest/kotest-assertions-core-watchosarm32/4.3.2/klib

**Comment by PaulWoitaschek** [comment]
Wonderful, thank you!
