### ISSUE TITLE
Android Instrumentation Tests

### ISSUE THREAD

**Issue by yousuf-haque** [kotest/kotest#189]
I was looking at the source for `KTestJUnitRunner` and it seems like a fairly simple subclass of `Runner`

`AndroidJUnit4Runner` and `RobolectricTestRunner` both ultimately extend from `Runner`  - would it be possible to make a version of the various specs that are compatible with either of these two use cases?

**Comment by sksamuel** [comment]
I don't do android development, but I assume from your issue that the runner must extend from either of those classes or it won't work. Is that because they add some extra setup, like a virtual device or something?

**Comment by michalbrz** [comment]
I have no problem running my tests made in kotlintest as Android Instrumented Test - I just don't annotate them with AndroidJUnit4Runner.

**Comment by JustinTullgren** [comment]
Hi,

I would like to have this feature available as well.

@sksamuel The `RobolectricTestRunner` simulates the Android runtime which isn't a normal JVM implementation and hooks up application manifests.  It allows for testing without the need for an actual or emulated android phone(runtime) and for other things like picking the runtime between Android SDK versions (Lollipop, nougat, kitkat, etc).

The main benefit of robolectric is the speed for tests is much faster as a phone is not needed.  

It would be nice to be able to have a consistent testing style across android projects (apk/aar) and java/kotlin jars.  Thats why I am requesting this be investigated if possible.

**Comment by sksamuel** [comment]
Is there a sample android project somewhere with one or more tests that use roboelectric. Then I can clone that project and get it working with kotlintest.

**Comment by sksamuel** [comment]
I guess this is what I want. https://github.com/robolectric/robolectric-samples

**Comment by michalbrz** [comment]
Just for the record, currently Android Instrumented Tests don't work. 
Just including runner for junit5 breaks building test apk with different exceptions about using Java 8 features or `java.lang.TypeNotPresentException: Type java.lang.module.ModuleReference not present`. But that's totally understandable.
Runner for junit4 goes further but then fails at runtime with `java.lang.ClassNotFoundException: Didn't find class "java.time.Duration"`

**Comment by Kerooker** [comment]
This is very necessary!

**Comment by AHarazim** [comment]
Any further updates here?

**Comment by Kerooker** [comment]
Ok, I'll try to work on this on the following weeks. It would be an amazing feature for KotlinTest to support Android Instrumentation tests.

Meanwhile, Unit Tests can be run correctly with KotlinTest, as they don't use Android Platform at all. I'll first try to focus on Robolectric, and maybe later in Instrumentation tests.

**Comment by sksamuel** [comment]
Roboelectric ties quite heavily into junit using the junit runnner. I looked at it and it seems a lot of work to separate the Roboelectric code from the junit stuff. We should see if they can do that so that other libraries can re-use robo.

What exactly is an "Android Instrumentation Test"? Is that different to just running tests inside Android Studio?

My efforts have never been very good. I can't even get the android sdk to work properly via the CLI.

**Comment by Kerooker** [comment]
@sksamuel 

There are some different kinds of android tests.

- We have Unit Tests, which will run on the JVM correctly, and no changes on our side are needed (I already Unit Test android using KotlinTest)
- We have Android Tests/Android Integration Tests/Instrumented tests, which will run on an Android Device. They run using an [AndroidJUnitRunner](https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner). This runner must be adapted for KotlinTest execution
- And one last possible test execution, which is [Robolectric](http://robolectric.org/). It runs using `RobolectricTestRunner`. Robolectric is between Unit Tests and Android Tests. It simulates the Android Device responses (note that it's a simulation, it doesn't emulate the device) so you can unit test similarly to IntegrationTest. This one also needs an adaptation for KotlinTest

**Comment by sksamuel** [comment]
@Kerooker Since you are an Android developer - when you write an android instrument test, you just annotate the test class with AndroidJUnitRunner and then write your tests normally using junit? Or do you have to extend a class ?

What would be great is if you could make a simple hello world example of an android instrument test. It doesn't matter if I can run it, as long as you tell me it works. And I'll use it to work out how it hooks into Junit and how hard it would be to migrate to KT.

**Comment by Kerooker** [comment]
Your assumption is correct, I usually only add the `@RunWith` annotation. However, I think some special attention will be needed to `@Rule`. I'm unsure on how to execute a Rule on KT, I believe it would be to execute the code inside the rule instead of actually using a defined rule

We usually use [Espresso test framework](https://developer.android.com/training/testing/ui-testing/espresso-testing) for everything, if you can take a look. It's the usual way to test.

In the linked page, there's a clear example on how things work:

```
package com.example.android.testing.espresso.BasicSample

import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

import androidx.test.rule.ActivityTestRule
import androidx.test.runner.AndroidJUnit4

@RunWith(AndroidJUnit4::class)
@LargeTest
class ChangeTextBehaviorTest {

    private lateinit var stringToBetyped: String

    @get:Rule
    var activityRule: ActivityTestRule<MainActivity>
            = ActivityTestRule(MainActivity::class.java)

    @Before
    fun initValidString() {
        // Specify a valid string.
        stringToBetyped = "Espresso"
    }

    @Test
    fun changeText_sameActivity() {
        // Type text and then press the button.
        onView(withId(R.id.editTextUserInput))
                .perform(typeText(stringToBetyped), closeSoftKeyboard())
        onView(withId(R.id.changeTextBt)).perform(click())

        // Check that the text was changed.
        onView(withId(R.id.textToBeChanged))
                .check(matches(withText(stringToBetyped)))
    }
}
```

**Comment by sksamuel** [comment]
Where is the onView method coming from here ?

**Comment by Kerooker** [comment]
The `onView` comes from `Espresso`, it's just used to find a View (for example, an Image) on the screen. I don't believe it's important right now, but it's a matcher/finder for views.

This `onView` can probably be used outside of AndroidJUnit4 runner

**Comment by sksamuel** [comment]
Ok, so the test class does not need to extend anything. But AndroidJUnit4 must add special support for the "instrumentation" - how does your test or test framework get a handle to it? Static fields or something?

**Comment by sksamuel** [comment]
Can you make a repo with a standalone example that runs from gradle and
I'll make it work with kotlintest. Or at least I'll try :)

**Comment by Kerooker** [comment]
Sure. Sorry for the long time to answer this.
I'll get something cooked up for you by tomorrow. I'll create a script to execute everything (from downloading the dependencies to executing the emulator to executing the code). Let's see if you'll be able to run Android that way

**Comment by Kerooker** [comment]
Here you go:
https://github.com/Kerooker/BasicExecutableProject

**Comment by LeoColman** [comment]
Ok, so we just added Robolectric experimental support. Please take a look at the snapshot builds and help us test it!

**Comment by svenjacobs** [comment]
I searched the documentation and internet but didn't find a solution: With the current version 5.2.3 of Kotest, is it possible to run Kotest tests as **plain** Android instrumentation tests (in the `androidTest` folder)? I don't mean Roboletric, just plain Android tests.

**Comment by Kolyall** [comment]
> I searched the documentation and internet but didn't find a solution: With the current version 5.2.3 of Kotest, is it possible to run Kotest tests as **plain** Android instrumentation tests (in the `androidTest` folder)? I don't mean Roboletric, just plain Android tests.

Seems it is this one https://github.com/kotest/kotest-android/blob/master/kotest-tests/kotest-tests-android/build.gradle.kts ... but the repo is archived

**Comment by LeoColman** [comment]
I've tried many times to implement Kotest + Android support. So far it's been impossible to decouple how Android works with JUnit to plug it into Kotest.
I'm currently waiting for new developments on Jetpack Compose. Perhaps that will be possible.
Absolutely no due date for this.

We currently officially support property testing and assertions in android, but not the framework for tests.

**Comment by irgaly** [comment]
For visitors to this issue, here is my workaround:

https://github.com/irgaly/kfswatch/blob/9d584f0bc3f378030efc8a638d64172747076f12/kfswatch/src/androidInstrumentedTest/kotlin/io/github/irgaly/kfswatch/AndroidTest.kt

* This is a workaround for Android Emulator Test (= Android Instrumented Test).
* Steps:
    * Set up kotest for multiplatform and add Kotest Spec classes in commonTest.
    * Set up android-junit5 https://github.com/mannodermaus/android-junit5
    * Set up android instrumented test normally.
    * Add an JUnit Android Test Class ( https://github.com/irgaly/kfswatch/blob/9d584f0bc3f378030efc8a638d64172747076f12/kfswatch/src/androidInstrumentedTest/kotlin/io/github/irgaly/kfswatch/AndroidTest.kt )
        * This class launches Kotest TestEngine, then run your Kotest Spec classes in commonTest.
    * Run Android Instrumented Test
        * `./gradlew :your_project:connectedDebugAndroidTest` or `./gradlew :your_project:allDevicesDebugAndroidTest` with Gradle Managed Device. 

case in success:

![image](https://user-images.githubusercontent.com/1311446/228455782-f2a142bf-5524-4400-a602-5cf1ff58c7fe.png)

case in failure:

![image](https://user-images.githubusercontent.com/1311446/228456916-4d336f4f-0357-455b-bd69-d6a9ec2d350b.png)

**Comment by LeoColman** [comment]
That's an incredible workaround!

I tried implementing Android tests 4 times over the years. Your workaround will make me invest a 5th time in it. 

Good work @irgaly

**Comment by LeoColman** [comment]
@irgaly Inspired by your work on this I created https://github.com/LeoColman/kotest-android with a specific Android Runner.

I ended up going a completely different way tho.
Thanks for showing me it's possible :D

**Comment by irgaly** [comment]
@LeoColman
Great! It seems it has seemless JUnit integration by custom Runner and JUnit RunNotifier. It's very cool. Thanks for your great work 🎉

**Comment by JesusMcCloud** [comment]
> For visitors to this issue, here is my workaround:
> 
> https://github.com/irgaly/kfswatch/blob/9d584f0bc3f378030efc8a638d64172747076f12/kfswatch/src/androidInstrumentedTest/kotlin/io/github/irgaly/kfswatch/AndroidTest.kt
> 
>     * This is a workaround for Android Emulator Test (= Android Instrumented Test).
> 
>     * Steps:
>       
>       * Set up kotest for multiplatform and add Kotest Spec classes in commonTest.
>       * Set up android-junit5 https://github.com/mannodermaus/android-junit5
>       * Set up android instrumented test normally.
>       * Add an JUnit Android Test Class ( https://github.com/irgaly/kfswatch/blob/9d584f0bc3f378030efc8a638d64172747076f12/kfswatch/src/androidInstrumentedTest/kotlin/io/github/irgaly/kfswatch/AndroidTest.kt )
>         
>         * This class launches Kotest TestEngine, then run your Kotest Spec classes in commonTest.
>       * Run Android Instrumented Test
>         
>         * `./gradlew :your_project:connectedDebugAndroidTest` or `./gradlew :your_project:allDevicesDebugAndroidTest` with Gradle Managed Device.
> 
> 
> case in success:
> 
> ![image](https://user-images.githubusercontent.com/1311446/228455782-f2a142bf-5524-4400-a602-5cf1ff58c7fe.png)
> 
> case in failure:
> 
> ![image](https://user-images.githubusercontent.com/1311446/228456916-4d336f4f-0357-455b-bd69-d6a9ec2d350b.png)

THIS! The approach works as a last resort even in projects where @LeoColman's plugin does not.
