### ISSUE TITLE
Update property test docs for global configs

### ISSUE THREAD

**Issue by DeafLight** [kotest/kotest#1893]
Hi,

Maybe I missed something, but I was unable to define the number of iterations I would like to run when doing property testing at the project level. Of course, I can define it on each call to `checkAll`, but that's tedious.

Is it possible to have this kind of property in the `ProjectConfig` class ? Is there another way to configure that ?

Thanks, and congrats for this great lib !

**Comment by sksamuel** [comment]
Seems like a good idea.

**Comment by sksamuel** [comment]
Just realized we already have this.

Do `PropertyTesting.defaultIterationCount = 1234`

I'll update the docs.

**Comment by sksamuel** [comment]
https://kotest.io/docs/proptest/property-test-global-config.html

**Comment by DeafLight** [comment]
Great, thanks a lot!
