### ISSUE TITLE
Discussion: Top level syntax support (ie no classes)

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1899]
What do we think about introducing support for syntax like this:

![image](https://user-images.githubusercontent.com/743706/101989489-3f399080-3c66-11eb-9c8e-fb4c4c708905.png)

**Comment by ajalt** [comment]
The idea seems interesting. I assume this is only for kts files?

Your screenshot looks similar to the c++ [catch2](https://github.com/catchorg/Catch2/blob/devel/examples/010-TestCase.cpp) library. You might also be interested in how [py.test](https://docs.pytest.org/en/stable/) configures fixtures.

The top level magic `val`s for configuration wouldn't support IDE autocomplete, and would be vulnerable to typos (if I accidentally declared `val asertionMode = Warn`, it would be difficult to notice why that didn't do anything). 

You might do a function call for configuration instead. Maybe something like this:


```kotlin
// The annotation indicates that this isn't a test. The function name can be anything.
@KotestSetup
fun testConfiguration() = configureTests {
    assertionMode = Warn
}

test("my test") {
    1 + 1 shouldBe 2
}
```

Or even less magical:

```kotlin
private val suite = configureTests {
    assertionMode = Warn
}

suite.test("my test") {
    1 + 1 shouldBe 2
}
```

**Comment by sksamuel** [comment]
Yes this would be .kts files only.

I was thinking for the configuration values, the names wouldn't matter, I would look for the type of the val instead. Eg,
`val whatever = AssertionMode.Warn` I can infer its the assertion mode setting from the val type.

However, I like your idea better. And we can take it further by having config be a function invocation rather than a function declaration. 

![image](https://user-images.githubusercontent.com/743706/101991776-7b73ed80-3c74-11eb-9015-7c570a6c4f07.png)

There is power in your second suggestion. Create a config object and have tests build off it, but you could also just create another file.

**Comment by christophsturm** [comment]
The second suggestion would also work in a main method, and require no class path scanning for discovery.

**Comment by sksamuel** [comment]
Wouldn't they both work in a main method? And outside of a main method, both would require classpath scanning.

**Comment by sksamuel** [comment]
Some issues / caveats.
* You wouldn't be able to navigate from class name to test inside intellij, because that works by looking for classes that match the format YourClass / YourClassTest
* We would need to either invoke all *.kts files inside the test folder, or we'd have to try to work out which *.kts files contain tests (by looking at the byte code for invocations of test functions).
* Global config might be tricky, as we wouldn't know which .kts file to invoke first. We could work around that by requiring a certain name, eg `project_config.kts`
* I don't know how this would play with JS yet.
