### ISSUE TITLE
README.md quick start link leads to page not found error page

### ISSUE THREAD

**Issue by opatry** [kotest/kotest#1900]
Clicking on `quick start guide.` leads to https://kotest.io/quick_start/ which is 

> **Page Not Found**
> We could not find what you were looking for.
> 
> Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

The correct link seems to be https://kotest.io/docs/quickstart/

I can repair the `README.md` but maybe an HTTP redirection should be put in place to avoid old links being broken?

**Comment by opatry** [comment]
Same is for changelog link but a redirection seems to operate after a while for this one.

**Comment by opatry** [comment]
Relates to #1890

**Comment by sksamuel** [comment]
I've added a redirect for quick start. There was one in place for changelog already.
