### ISSUE TITLE
Kotest plugin doesn't run JUnit4 tests if run them for directory/package from Android Studio

### ISSUE THREAD

**Issue by yaroslav-shlapak** [kotest/kotest#1911]
Kotest version: 4.2.5
### Given
1. Kotest IIntelliJ IDEA plugin version 1.1.22-IC-2020.1 installed and enabled
2. A multimodule Android project with the module which has both JUnit4 and Kotest tests
2. The module has Kotest configured like this (gradle.kts with correct kotest dependencies, here as constants):
  ```
  android {
      tasks.withType<Test>().all {
          useJUnitPlatform()
      }
  }
  ...
  testImplementation(kotestJunit5Runner)
  testImplementation(kotestAssertions)
  testImplementation(kotestProperty)
  testRuntimeOnly(junitVintage)
  ``` 
### When 
running tests using Android Studio via right-click on a package with tests -> select **Run 'Tests in 'package''**
### Then
Only Kotests tests are executed, JUnit4 tests are not executed
### Expected result
Both Kotest and JUnit4 tests are executed
### Additional info
1. This issue doesn't occur when running tests with Gradle
2. This issue doesn't occur when running tests with Kotest IIntelliJ IDEA plugin disabled/uninstalled
3. When running a single JUtni4 test from file using play button near the test class name it works without issues even with Kotest plugin enabled

**Comment by roman-tikonov** [comment]
I have a similar project setup and experience exactly the same issue. 

Kotest: 4.3.2
Android Studio: 4.1.1
Kotest IDE plugin: 1.1.22-IC-2020.1

**Comment by yaroslav-shlapak** [comment]
Hey, any plans to address this issue?

**Comment by sksamuel** [comment]
Can you make a standalone project that exhibits this behavior that can be imported directly into intellij ?

**Comment by yaroslav-shlapak** [comment]
@sksamuel can I use AS and android modules to try to replicate this issue on the test project? Not sure if it's related to this, but the modules on which I reproduced this issue were `com.android.library`

**Comment by sksamuel** [comment]
Yes please.

**Comment by yaroslav-shlapak** [comment]
Sorry for the delay @sksamuel 
Here is the project https://github.com/yaroslav-shlapak/KotestPluginDoesntRunJUnit4Tests. Also, I've confirmed that the same issue exists with the newer `4.4.2` Kotest version and `1.1.30-IC-2020.1` Kotest Plugin version.
Here is how to run tests from the package, only Kotest tests are being executed as a result:
<img width="658" alt="Screenshot 2021-03-22 at 14 11 55" src="https://user-images.githubusercontent.com/3373419/111988007-962dec00-8b18-11eb-8852-02ebb6a936b7.png">

**Comment by yaroslav-shlapak** [comment]
I'm closing this issue as it no longer occurs after dependencies update on Android Studio 2020.3.1 Patch 4 both in production and for test project https://github.com/yaroslav-shlapak/KotestPluginDoesntRunJUnit4Tests

**Comment by yaroslav-shlapak** [comment]
I'm closing this issue as it no longer occurs after dependencies update on Android Studio 2020.3.1 Patch 4 both in production and for test project https://github.com/yaroslav-shlapak/KotestPluginDoesntRunJUnit4Tests
