### ISSUE TITLE
Allow null clues

### ISSUE THREAD

**Issue by glasser** [kotest/kotest#1939]
Clues are declared as `Any` rather than `Any?`. I'm not sure why this is helpful.

Notably, I find myself wanting to write `foo.asClue { foo.shouldBeNull() }` sometimes. Is there a better way to do this? `foo?.asClue { foo.shouldBeNull() }` skips the assertion, and `foo!!.asClue { foo.shouldBeNull() }` moves the failure to `!!` itself.

**Comment by sksamuel** [comment]
Seems reasonable to me. Would you like to make the PR ?

**Comment by glasser** [comment]
If you're motivated to do so I wouldn't complain, but I can try to find some time soon!

**Comment by glasser** [comment]
Yay, #1940. Although part of me wonders if the bug report should instead have been "`x.shouldBeNull()` should show x on failure"

**Comment by sksamuel** [comment]
You want it to show the variable name? If so, we plan a compiler plugin for
that.

**Comment by glasser** [comment]
Nah, the value -- I expected something to be null, it's not, so the natural question is what is it...

**Comment by sksamuel** [comment]
Does it not do that? That seems poor. Should be like "foo should be null".

**Comment by glasser** [comment]
You'd think so, but: https://github.com/kotest/kotest/blob/757529896b9d117240b281e69926953022d6ca9d/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/nulls/matchers.kt#L104

**Comment by sksamuel** [comment]
@glasser https://github.com/kotest/kotest/issues/1942
