### ISSUE TITLE
Add more configurations to Email Generator

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#1941]
The current email generator doesn't allow customization of domain and TLD. Sometimes it's desirable, as for example, you want to test that people from a "bad domain" will be denied to register in your website.

We should support more customization in that sense, and deprecate the non-customizable approach.

**Comment by sksamuel** [comment]
@LeoColman do you want to make a PR before 4.4 is released?

**Comment by LeoColman** [comment]
Yes
