### ISSUE TITLE
not null matcher should show the value that was meant to be null

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1942]
https://github.com/kotest/kotest/blob/757529896b9d117240b281e69926953022d6ca9d/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/nulls/matchers.kt#L104

**Comment by sksamuel** [comment]
a.shouldBeNull()

should show what a was if it wasn't null

**Comment by glasser** [comment]
I think the issue title here is a bit off — the "not null" matcher doesn't need any context (since the answer on failure is always `null`), just the "null" matcher.

**Comment by sksamuel** [comment]
Yes, thanks, updated.
