### ISSUE TITLE
Documentation on test ordering

### ISSUE THREAD

**Issue by vsigler** [kotest/kotest#1975]
I've found the following issue: https://github.com/kotest/kotest/issues/439

Not sure if it did not get merged or was deleted at some point, however, I did not find information how to control test execution ordering.

The reference contains the following

> Note: Test cases inside each spec will always run in a certain order (either in definition order, or in a random order, see documentation on test ordering).

However, the "documentation" links to a non-existent file, resulting in 404.

**Comment by sksamuel** [comment]
Is this what you're looking for: https://kotest.io/docs/framework/test-ordering.html

**Comment by vsigler** [comment]
Ah, thanks, I was looking at the wrong place! What is the point of this then: https://github.com/kotest/kotest/tree/master/doc :)

**Comment by sksamuel** [comment]
It's the old docs.
