### ISSUE TITLE
intelliJ unable to run tests with interpolated names

### ISSUE THREAD

**Issue by joelhess** [kotest/kotest#1978]
Using kotest 4.3.2, plugin 1.1.24-IC-2020.3, intelliJ 2020.3

Using a String Spec, or ShouldSpec,  if the test name contains an interpolated string the plugin says that it can't run it. Tests work fine via gradle or running form a higher level (like the whole spec). I'm fairly certain this used to work?

example
`context("$recommenderName Tests") {}`
<img width="524" alt="image" src="https://user-images.githubusercontent.com/9028374/103934823-43cd5980-50eb-11eb-8a92-1dd04a140175.png">

**Comment by sksamuel** [comment]
This has always been the case. It's because tests are launched by name, but it doesn't know the name without running the code, since the interpolation can have arbitrary complexity.
You can still run the entire class file.

**Comment by joelhess** [comment]
Ok. Thanks for the response. I must have remember it incorrectly.
