### ISSUE TITLE
Problem with Spring extension documentation

### ISSUE THREAD

**Issue by StragaSevera** [kotest/kotest#1982]
The example that is posted on the site does not work, because there is no object with the name `SpringExtension`:
```kotlin
class ProjectConfig : AbstractProjectConfig() {
   override fun extensions() = listOf(SpringExtension)
}
```

What works for me is the different configuration:
```kotlin
class ProjectConfig : AbstractProjectConfig() {
    override fun extensions() = listOf(SpringAutowireConstructorExtension)
}
```

Is this the correct way to initialize the Spring extension? If so, then the documentation on the website is not correct. If it is not the right way to use Spring extension, then how do I make the example from website work? =-)

**Comment by sksamuel** [comment]
The documentation refers to the 4.4 release (currently RC1).
You can use the example I pasted in your other ticket (spring listener).

**Comment by StragaSevera** [comment]
Got it. I think the documentation would benefit from specifying the way to do it in stable release (until 4.4 becomes stable).

**Comment by sksamuel** [comment]
I'll release 4.4 tomorrow.

**Comment by StragaSevera** [comment]
Well, then this issue is kinda obsolete :-)
