### ISSUE TITLE
TestContext should have a logging interface

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#1992]
Since kotest supports parallelism, logging within tests shows up out of order and is confusing. I think kotest could probably have the usual log methods on `TestContext` so users can append their logs to the report printed at the end of a test run that happens to be in parallel.

**Comment by jschneidereit** [comment]
After working on #2172 It feels like `TestCase` should have the logger and the runner passes the contents of the logger to the `TestResult`

**Comment by sksamuel** [comment]
Adding this to 4.6
We can add a log interface to TestContext
