### ISSUE TITLE
Odd results formatting with context() - false positive?

### ISSUE THREAD

**Issue by iainism** [kotest/kotest#1996]
**With Kotest 4.3.2**

Within a funspec I have a context, that contains two tests:

```
context("Repo settings tests") {
    test("Api settings are applied on init") {
        val repo = Repository.getInstance(
            pvApiService,
            expectedSettings,
            ProjectConfig.testDispatcherProvider
        )
        repo.userUID shouldBe expectedUid
        repo.userPWD shouldBe expectedPwd
        repo.userRole shouldBe expectedRole
        repo.repositorySettingsOK shouldBe true
    }

    test("Incomplete API settings are detected") {
        val repo = Repository.getInstance(
            pvApiService,
            expectedSettings,
            ProjectConfig.testDispatcherProvider
        )
        repo.userPWD shouldBe expectedPwd
        repo.userRole shouldBe expectedRole
        repo.repositorySettingsOK shouldBe false
    }
}
```

In my TDD flow, I am at the point where `"Incomplete API settings are detected"` should fail, and I spotted that the output in Android Studio appears to show a false positive for this test:
![image](https://user-images.githubusercontent.com/8614139/104428113-f84bfd00-557b-11eb-883d-2222526267d7.png)

I don't understand why there is a pass mark for the test, and then additionally a fail for `<init>`.  The fail for `<init>` is the expected failure for `"Incomplete API settings are detected"`, i.e.:
`org.opentest4j.AssertionFailedError: expected:<false> but was:<true>`

Shouldn't there just be one passing and one failing test shown under the context of `"Repo settings tests"`?

**Comment by sksamuel** [comment]
You are corecet. That's what should be happening.

The init is added when the class fails setup or teardown

**Comment by iainism** [comment]
Thanks for the fast response!  The `<init>` failure makes sense now. :-)

I still don't understand the 'pass' indication for the failing test though?

**Comment by sksamuel** [comment]
Does this happen if you take out the test code itself and just have the test structure ?

**Comment by sksamuel** [comment]
Are you still having this issue? If so, do you have a standalone example we can use as a test case.

**Comment by iainism** [comment]
Sorry - I missed your follow-up, somehow.

We haven't yet updated our deps to 4.4.1.  I'll see if I can get this done tomorrow, and come back to you.
