### ISSUE TITLE
Output plain String diff

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#1999]
**Which version of Kotest are you using**
4.3.2

<img width="1831" alt="image" src="https://user-images.githubusercontent.com/13354331/104615485-937ec880-5689-11eb-8a76-14a19ec86346.png">
Apparently, there is some special handling for Intellij. Unfortunately that doesn't change the fact that this type of diff is not very helpful...

Is there some way for a simple `shouldBe` Matcher to return the plain Strings?

**Comment by xeruf** [comment]
@sksamuel would appreciate help here, this is a major blocker for my use of Kotest. Maybe there is simply something I have missed?

**Comment by sksamuel** [comment]
This should only be happening for big multi line strings. 
Can you try setting a system property of `kotest.assertions.multi-line-diff` to `simple`.

**Comment by xeruf** [comment]
Thanks! Setting it in my global ProjectConfig, like this, worked:
```kt
object KotestConfig: AbstractProjectConfig() {
    override val isolationMode = IsolationMode.InstancePerLeaf
    override val testCaseOrder = TestCaseOrder.Random
    override val parallelism = Runtime.getRuntime().availableProcessors()
    init {
        System.setProperty("kotest.assertions.multi-line-diff", "simple")
    }
}
```

Now it would be great if, like you adjust the output specifically for Intellij, I could set this so it is only done for Intellij. I actually believe this should be the default, as Intellij can diff nicely by itself.

**Comment by sksamuel** [comment]
Are you seeing a nice diff even on multi line strings in intellij ?

**Comment by xeruf** [comment]
Yes, Intellij has the compare function, which you can see in the right of my screenshot. But that only works well with the original strings, not pre-diffed ones.

**Comment by sksamuel** [comment]
I think `kotest.assertions.multi-line-diff` could default to `simple` if we can detect we are running inside intellij.

**Comment by sksamuel** [comment]
5.0 detects intellij mode and sets this.
