### ISSUE TITLE
Replace jackson and js native with kotlinx-serialization json parsing in kotest-assertions

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#2004]
The kotlinx-serialization library can do [arbitrary json parsing](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#subtypes-of-json-elements) and is a cross platform project by default. Replacing Jackson with kotlinx-serialization would make [kotest-assertions](https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-json/build.gradle.kts) a cross platform module by default.

**Comment by jschneidereit** [comment]
Might be blocked by https://github.com/Kotlin/kotlinx.serialization/issues/204 unless we're ok with temporarily reading resources right into memory `this.javaClass.getResourceAsStream(resource)` see `io.kotest.assertions.json.resources.kt`

**Comment by sksamuel** [comment]
I don't think a test needs to be streaming. Loading into memory seems fine ?

**Comment by jschneidereit** [comment]
Fixed in #2006
