### ISSUE TITLE
Generate HTML reports from JUnit XML

### ISSUE THREAD

**Issue by caramelomartins** [kotest/kotest#2011]
When using JUnit XML, we can generate XML results from tests that are able to produce output with nested tests. If we use Kotest/JUnit XML with Gradle, then we can disable the XML results from Gradle and keep _only_  the results from JUnit XML. Unfortunately, Gradle generates its HTML reports with the results it has in-memory, which can't don't support nested tests, and it doesn't seem to be able to fetch results from a different XML. It has a `TestReport` task that is able to generate HTML reports from binary results, supposedly, but not from XML results.

With this in mind, I believe it would be interesting to offer a listener, similar to what JUnit XML does, that would generate HTML reports based on XML results produced by JUnit XML. In this way, we could have custom HTML reports for Kotest that would support nested tests based on the XML generated by JUnit XML.

**Comment by sksamuel** [comment]
Would you like to make a start on it, and then we can all contribute to improving it ?

**Comment by caramelomartins** [comment]
Hey @sksamuel. Yes, I'd like to make a start of it (at least the HTML, even if it doesn't have much styling at first). I'm going to try to use some spare time this week on this. :crossed_fingers:

**Comment by sksamuel** [comment]
Awesome.

**Comment by caramelomartins** [comment]
Hey! Just wanted to get back to you on this. I've got some minor progress:

![image](https://user-images.githubusercontent.com/2028058/108105192-36a97000-7084-11eb-96b3-e5fc67d2bdaa.png)

Not pretty or particularly useful yet but it does produce something. :smile:

**Comment by caramelomartins** [comment]
We can now go from having a summary of all the test classes to seeing tests in each of the test classes. Still without any styles.

![image](https://user-images.githubusercontent.com/2028058/108606713-899c6380-73b3-11eb-9f90-c5e77ffe959b.png)

![image](https://user-images.githubusercontent.com/2028058/108606727-a3d64180-73b3-11eb-8b3b-2974cdacb89c.png)

I've noticed something odd which is that none of the test results have any duration in the XML of `JunitXmlReporter`. Is this expected?

**Comment by sksamuel** [comment]
Looking good so far.

No, the durations should be set, assuming they take longer than 1ms

**Comment by sksamuel** [comment]
We could expand the junit XML too, since the format is kind of limiting.

**Comment by caramelomartins** [comment]
> We could expand the junit XML too, since the format is kind of limiting.

Definitely but I'd say that, for now, it would be good enough. It can obviously be expanded further in the future but it would be interesting to have both of them (XML and HTML) evolve together.

**Comment by sksamuel** [comment]
This will be included in 4.5
