### ISSUE TITLE
All lists generated by Arb.list begin with edge cases

### ISSUE THREAD

**Issue by shwaka** [kotest/kotest#2012]
**Which version of Kotest are you using**
`4.3.2`

If I understand correctly, `Arb.list` should generate "random" lists. But it always generates lists begining with fixed values (edge cases?).

## Current behavior
Generated lists always begin with fixed values (edge cases?).

## Expected behavior
Generated lists should begin with random values.

## Steps to reproduce
```kotlin
class KotestArbListTest : StringSpec({
    "foo" {
        val intArb = Arb.int()
        val n = 8
        val listArb = Arb.list(intArb, n..n)
        println(listArb.next())
        println(listArb.next())
        println(listArb.next())
        checkAll(listArb) { list ->
            list[0] shouldBe 0
            list[1] shouldBe 1
            list[2] shouldBe -1
            list[3] shouldBe Int.MAX_VALUE
            list[4] shouldBe Int.MIN_VALUE
        }
    }
})
```

Three lines of `println` print something like:

```
[0, 1, -1, 2147483647, -2147483648, 646549837, 280811815, -1806550440]
[0, 1, -1, 2147483647, -2147483648, 700817989, -433278774, 1871373119]
[0, 1, -1, 2147483647, -2147483648, 1513269275, -1743996880, -511171751]
```

Hence the above `checkAll` passes (wrongly).

**Comment by sksamuel** [comment]
They are designed to return edge cases first.
I just looked at the docs and they are sparse in this area, the old docs were better.
I will update the docs with the rationale behind this.

**Comment by sksamuel** [comment]
I've updated the property test documentation to make this clear.
