### ISSUE TITLE
shouldBe does not work correctly when using custom exception classes

### ISSUE THREAD

**Issue by pallavijoshi44** [kotest/kotest#2016]
**Kotest version : 4.3.1**

'shouldBe' does not validate the data inside the data class if the data class is extended from Exception class. It only checks the type of the data class. However, it works perfectly when the data class does not extend the Exception class. 

In the sample below, the test should fail as the data inside the CustomException does not match and fail assertion ("abc" is not equal to "test". But, the test unfortunately passes. If CustomException does not extend the Exception, the test fails correctly.

```
package com.bnppf.easybanking.psd2.ais.api

import io.kotest.matchers.shouldBe
import io.kotest.runner.junit4.StringSpec

class Test : StringSpec() {

    init {
        val expectedResult = TestExecution().test()

        "should return custom exception with correct data "{
            expectedResult shouldBe CustomException("abc")
        }
    }
}

class TestExecution {

    fun test(): CustomException {
        return CustomException("test")
    }
}

data class CustomException(private val value: String) : Exception()

``` 

This seems to be a bug. Can you let me know if this will be fixed in near future? 

[test.txt](https://github.com/kotest/kotest/files/5873398/test.txt)

**Comment by ashishkujoy** [comment]
@pallavijoshi44 
For throwable Kotest check message field of throwable and actual class of expected and actual value. In your case while extending from Exception you are not passing any message field to `Exception` constructor and Kotest is finding null value for both actual and expected message field while doing assertion. 
As a quick fix you can change `CustomException` defination to this.
```kotlin
data class CustomException(private val value: String) : Exception(value)
```
That will solve your problem. 
Will try to fix this from our end as soon as possible.

**Comment by ashishkujoy** [comment]
Fixed in master.

**Comment by pallavijoshi44** [comment]
Thank you for fixing so fast!
