### ISSUE TITLE
Deprecate until and move its features to eventually

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#2019]
- [ ] function arguments should be suspending
- [ ] `eventually` should accept a type argument to catch exceptions of type until time runs out
- [ ] new functionality should be documented in [nondeterministic.md](https://github.com/kotest/kotest/blob/master/doc/nondeterministic.md)

**Comment by sksamuel** [comment]
the exception should be optional, in case you just want to wait for "no exceptions" and variations should accept a predicate.

**Comment by jschneidereit** [comment]
@sksamuel I pushed my work from lunch break and will work on the docs tonight
