### ISSUE TITLE
Is there a way to use Kotest without importing Assertions?

### ISSUE THREAD

**Issue by StragaSevera** [kotest/kotest#2033]
I'm using a different assertions library, and I would be glad to have just the spec functionality without assertions - so my IDE would not give me options of using functions like `shouldBe` on each and every object.

**Comment by sksamuel** [comment]
It's only shouldBe that comes in by default right?

We could move it to it's own module so you can just exclude that.
In the meantime, if you exclude the `kotest-assertions-shared` module it will go away.

**Comment by StragaSevera** [comment]
As far as I remember, there were some collection assertions too.

Sorry for my inexperience, but how do I exclude it? Is it something in the build.gradle file?

**Comment by sksamuel** [comment]
Make sure you don't have `kotest-assertions-core` on your build. That's what brings in the collection assertions.
`kotest-assertions-shared` is added by default and brings in forAll and things on collections. 
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

**Comment by sksamuel** [comment]
Did my instructions help ?

**Comment by StragaSevera** [comment]
Sorry for my newbieness, but this way it does not work:
```kotest
    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion") {
        exclude(group = "kotest-assertions-core", module = "kotest-assertions-core")
    }
```
How do I do it in this case?

**Comment by sksamuel** [comment]
Try this

```
   testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion") {
        exclude(group = "io.kotest", module = "kotest-assertions-shared")
    }
```

or

```
   testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion") {
        exclude(group = "io.kotest", module = "kotest-assertions-shared-jvm")
    }
```

**Comment by StragaSevera** [comment]
Thank you! When I excluded only `kotest-assertions-shared`, it still had some `shouldNotNull`-type things. But when I used this:
```kotlin
    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion") {
        exclude(group = "io.kotest", module = "kotest-assertions-shared")
        exclude(group = "io.kotest", module = "kotest-assertions-core")
    }
```
- it worked flawlessly. Thanks!

**Comment by sksamuel** [comment]
Great.
