### ISSUE TITLE
Use IR (both) for JS builds

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2037]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by hpehl** [comment]
Any updates?
Is both mode supported? If so which version does it support?

**Comment by sksamuel** [comment]
There were some bugs that hopefully 1.4.31 has fixed. Then 4.4.2 will be
completely ir enabled

**Comment by hpehl** [comment]
Thanks @sksamuel for the info

**Comment by sksamuel** [comment]
4.4.2 is released which has IR support.
