### ISSUE TITLE
Changelog for 4.4.0 incomplete

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#2043]
It lists changes like `Removed superfluous whitespaces in freeSpec.kt #1819` (what the heck is that doing in the changelog? Why would anyone care about that?) but important changes like the deprecation of until and revamp of eventually (#2022) aren't mentioned at all?

**Comment by sksamuel** [comment]
It's nice to include everyone's contributions I guess.

There will be a blog post out lining some of the major changes.

**Comment by xeruf** [comment]
nah, contributions are listed in the git log. Changelogs are for humans (https://keepachangelog.com)

**Comment by sksamuel** [comment]
Changelogs are up to date.
