### ISSUE TITLE
Improvements on Eventually given Until deprecation

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#2044]
@xerus2000 pointed out some issues with my changes made in #2022  and those should be fixed:

- [x] `EventuallyPredicate` should be a `typealias` instead of a `fun interface`
- [x] Differentiate between a failure of the predicate and an exception in `eventually`
- [x] Add an overload that has no `f` for eventually so you can use `eventually` like you could use `until` (and fix the deprecation replace message)

**Comment by xeruf** [comment]
I think we shouldn't have normal predicates, just matchers and a good way for handling them, because then we can leverage their elaborate error message generation.

**Comment by xeruf** [comment]
By changing to soft assertion mode within the eventually block I think we can catch these more gracefully.

**Comment by jschneidereit** [comment]
I'll look at switching to soft, but I think that probably should be up to the tester to opt in to. What if they don't want every assertion to run if one fails? 

I also think the predicate is fine, consider a producer that returns a kotlin `Result` type and I want to gate on `.isSuccess`

**Comment by xeruf** [comment]
> I also think the predicate is fine, consider a producer that returns a kotlin `Result` type and I want to gate on `.isSuccess`

Totally easy with matchers: `result.isSuccess shouldBe true`
