### ISSUE TITLE
KMP Native: Backend Internal error: Exception during IR lowering

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [kotest/kotest#2047]
Kotlin 1.4.30 and Kotest 4.4.0

It works with JVM, Android, Linux and Windows targets. But with some Apple targets it is failing. The project only have a `shouldDo` function.

Stacktrace:

```
> Task :lib:linkDebugTestIosX64 FAILED
e: Compilation failed: Backend Internal error: Exception during IR lowering
File being compiled: /Users/runner/work/kotest/kotest/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/decreasing.kt
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)

 * Source files: 
 * Compiler version info: Konan: 1.4.30 / Kotlin: 1.4.30
 * Output kind: STATIC_CACHE

e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /Users/runner/work/kotest/kotest/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/decreasing.kt
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.fakeOverrideMember(IrOverridingUtil.kt:43)
```

**Comment by PaulWoitaschek** [comment]
This is a compiler bug. I narrowed it down to:

```kotlin
fun a() {
    b<Int> { _, _ -> 0 }
}

fun <T> b(c: Comparator<in T>) {
}
```

And reported it upstream: https://youtrack.jetbrains.com/issue/KT-44928

**Comment by sksamuel** [comment]
Nice job.

**Comment by PaulWoitaschek** [comment]
This can be worked around by adding:
`kotlin.native.cacheKind=none` to your `gradle.properties`. As this is an upstream issue I think this can be closed. Maybe add a note to the release notes @sksamuel

**Comment by sksamuel** [comment]
Can you clarify the circumstances upon which you need that property. Is it
anyone using 1.4.30 ?

**Comment by PaulWoitaschek** [comment]
Apparently the workaround doesn't work. https://youtrack.jetbrains.com/issue/KT-44826

I'll try later if we can modify kotest to not trigger that error.

**Comment by sksamuel** [comment]
I hope they'll release 1.4.31 with a fix soon then.

**Comment by headsvk** [comment]
I came across this issue in our multiplatform mobile project when updating to Kotlin 1.4.30. However, with the recent Kotlin 1.4.31 update, I can confirm iOS tests work again with Kotest 4.4.1 🙂

**Comment by sksamuel** [comment]
Great.  Marking as closed

**Comment by JavierSegoviaCordoba** [comment]
Nice, I was going to check it today :)
