### ISSUE TITLE
How to configure in testing styles other than StringSpec?

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#2049]
https://kotest.io/docs/framework/testing-styles.html documents that I can use `.config(...)` for StringSpec - but what about all the other styles? Particularly, I have no idea how this could work in WordSpec.

**Comment by sksamuel** [comment]
you put .config on the inner test case. I will update the docs soon to show config examples for every spec style.

We are also going to expand the config a bit too for 4.5

**Comment by sksamuel** [comment]
Related to https://github.com/kotest/kotest/issues/1370 and https://github.com/kotest/kotest/issues/2050

**Comment by xeruf** [comment]
now in https://kotest.io/docs/framework/testcaseconfig.html, for reference
