### ISSUE TITLE
test config is not recognized on tests run within a context

### ISSUE THREAD

**Issue by ghost** [kotest/kotest#2050]
In the code here https://gist.github.com/slathropSR/f9c420c666b1cb3c0279e6f2afc38a1e the test running in the context will not execute unless the line with a default config is un commented.

It looks like the test config on a test defined within a context is not being honored.

**Comment by sksamuel** [comment]
Ok I see the problem. The context block does not have tags, so will not be picked up as you say.
The solution is to allow config at all levels, which is planned for 4.5

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/issues/1370

**Comment by sksamuel** [comment]
Workaround for now is spec level tags (the line you commented).
