### ISSUE TITLE
Generation of larger sets via Arb.set now throws an exception

### ISSUE THREAD

**Issue by shichimitogarashi** [kotest/kotest#2051]
Starting with Kotest 4.4.0, generation of larger sets now fails. This appears related to https://github.com/kotest/kotest/issues/1931

With the change to termination, `Arb.set` now gives up after 1,000 loops. This means that, even when given a generator with sufficient cardinality, passing in a range that generates desired sizes of greater than 1,000 elements will fail.

**Comment by myuwono** [comment]
👍 thanks for raising this. yeah i think we should only increment when the set size does not change on subsequent sampling. i'll raise a fix.

**Comment by sksamuel** [comment]
Fix incoming :)

**Comment by sksamuel** [comment]
@myuwono I had already started a fix before you posted, if you would be so kind as to review the PR. https://github.com/kotest/kotest/pull/2054

**Comment by myuwono** [comment]
awesome!

**Comment by sksamuel** [comment]
Fixed in master. Will be in 4.4.1
