### ISSUE TITLE
Expanding config - style discussion

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2065]
As part of #2049 #2050 #1370 I want to expand config to parent tests.

Currently, we add config to a test like this:

```
test("this test has config").config(timeout = 412.milliseconds, enabled = true) {
  // test here
}
```

We don't support this syntax on parent tests. So our options are:

1. Expand same style to parents:

```kotlin
  context("this context should support config").config(timeout = 65.milliseconds, tags = setOf(linuxTag)) {
     test("this test inherits config") {
     }
  }
```

The pro is that it works like it does currently, the con is that not all specs can support this (eg word spec) due to limitations in kotlin's DSL support and we can't share config.

2. Introduce config objects that tests can use as a receiver:

```kotlin
      val config = TestConfig(timeout = 412.milliseconds, tags = setOf(linuxTag))
      config.context("this context is defined on the config object") {
         test("this test inherits config") {
         }
         config2.test("this test uses another config receiver that would override the first") { 
         }
      }
```

The big pro here is that config can be defined and then re-used and the spec level config looks the same. The con is that it perhaps looks a bit uglier and harder to read with the config coming first (??)

3.  Similar to two, but define config as lambas:

```kotlin
      config(timeout = 412.milliseconds, tags = setOf(linuxTag)) {
         context("this context gets its config from the surrounding closure") {
            test("this test inherits config") {
            }
            config(invocations = 4) {
              test("this test overrides some config") {
              }            
            }
         }
      }
```

I think this looks nice and is clear when nesting and overriding, but you couldn't define it and reuse it (well you could make a custom function yourself).

4. Your proposal here...

**Comment by ghost** [comment]
Of the three options you mentioned I like option 2 best due to the reusability.

I don't know if it's possible but could what about combining the reusable config with the test declaration.
This might be more confusing if it's even possible but could address your concern about the config tag being unclear that's it's a test.

Could look something like this:
```      
val shortLinuxTest = TestConfig(timeout = 412.milliseconds, tags = setOf(linuxTag))
    shortLinuxTest.context("this context is defined on the config object") {
         test("this test inherits config") {
         }
         LongLinuxTest("this test uses another config receiver that would override the first") { 
         }
      }
```

**Comment by jschneidereit** [comment]
I'm partial to re-usability (see the controversial `EventuallyConfig`) but I think we might be able to get away with the object as well as overriding invoke for the lambda style as well. I can play around with it tonight.

**Comment by sksamuel** [comment]
It's an interesting idea, but my gut feeling is that it would become very complex to support.

@slathropSR @jschneidereit  both say reusability is important, and I agree. Lukasz on slack had the idea of allowing the .config postfix style, but with an overload to accept a pre-confused test object.

That might give us the best of all worlds.

**Comment by LeoColman** [comment]
We once talked about having 'inline' configs instead of having `x.config`:

```
context("A") {
  retry(3) {
    test("B") {}
    test("C") {}
  }
}
```

And similar things to timeout, tags and etc. Having more than one of these will get too cumbersome, so having a bigger `config` object is better for these cases. But I think it's more often to use one or two configs than to use all available at `testConfig`, so I see benefits on what I proposed above

**Comment by sksamuel** [comment]
> We once talked about having 'inline' configs instead of having `x.config`:
> 
> ```
> context("A") {
>   retry(3) {
>     test("B") {}
>     test("C") {}
>   }
> }
> ```

The drawback to this is that the nesting for things like tags and timeouts would go above the tests pushing indentation out further again, one indent per "thing".

The benefit is it reads quite nicely in the DSL style of Kotest if you don't have too many.

**Comment by LeoColman** [comment]
We could have both. One option with more configs

**Comment by lwasyl** [comment]
Just for completness, my idea was to have two overloads for config: one with many parameters, which would delegate to one with a builder lambda:

```kotlin
// inline usage
context("foo").config(timeout = 500.milliseconds, tags = setOf(linuxTag)) { }

// with reusing
val testConfig: TestConfig = testConfig { 
  timeout = 500.milliseconds
  tags = setOf(linuxTag)
}
context("foo").config(testConfig)
```

where the first `.config` declaration would be roughly
```kotlin
fun config(timeout: Duration, tags: Set...) = config(testConfig { this.timeout = timeout; this.tags = tags })
```

But now that I think of it, there's no need for lambdas even. Just having two `config` overloads, one with parameters and one with an object would be the same. The one with many parameters would create a TestConfig object and delegate to the one with single config parameter.
