### ISSUE TITLE
Wiremock Integration

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2071]
https://github.com/tomakehurst/wiremock

**Comment by LeoColman** [comment]
Probably better to use a listener

**Comment by pinwheel101** [comment]
@LeoColman Could you tell me why listener can be a better option compare to extension. Actually I cannot use kotest becuase of the absence of @ClassRule annotation so I don't know how can I use wiremock in kotest.

If someone give me an example how to use Wiremock with kotest, it would be really helpful to use kotest

**Comment by pinwheel101** [comment]
@sksamuel I am looking foward to release the wiremock extension 👍

**Comment by sksamuel** [comment]
> @LeoColman Could you tell me why listener can be a better option compare to extension. Actually I cannot use kotest becuase of the absence of @ClassRule annotation so I don't know how can I use wiremock in kotest.

A TestListener in kotest is read only, a TestExtension can modify tests.
This particular "extension" only needs to listen to test lifecycle events, so @LeoColman is write, I should have said listener.

**Comment by pinwheel101** [comment]
@sksamuel Thank you for the explanation. I understand now. Listener means TestLinstner in Kotest :)
