### ISSUE TITLE
Should I write a description only in English?

### ISSUE THREAD

**Issue by henry-jo** [kotest/kotest#2079]
**With kotest 4.3.2**
**With kotlin 1.3.72**

I made testcode by using Korean for writing the description. 
See blow. There are 4 testcases. (BehaviorSpec)
```
Given("한글설명"){
   When...
      Then...
   When...
      Then...
}
Given("한글설명"){
   When...
      Then...
   When...
      Then...
}
```
In `SingleInstance` mode, every test works. 
But in the `InstancePerLeaf` and `InstancePerTest` mode, only some of them works.

When I modified the Korean written description to Enlgish written one, the testcase works well in any mode.

Could you explain the reason?.. Do I have to use only English for writing description?

**Comment by sksamuel** [comment]
It should work for everything.

Can you make a full example with Korean for all the parts.

**Comment by henry-jo** [comment]
**With kotest 4.3.2
With kotlin 1.3.72**

@sksamuel 
Simple examples
```kotlin
class KotestExample : BehaviorSpec({
    isolationMode = IsolationMode.InstancePerLeaf

    Given("코테스트 코테스트 코테스트") {
        And("A가 1이고 B가 2일 때") {
            val a = 1
            val b = 2
            When("함수를 실행하면") {
                val result = sum(a, b)
                Then("결과값이 3") {
                    result shouldBe 3
                }
            }
        }
        And("A가 2이고 B가 3일 때") {
            val a = 2
            val b = 3
            When("함수를 실행하면") {
                val result = sum(a, b)
                Then("결과값이 5") {
                    result shouldBe 5
                }
            }
        }
    }
    Given("테스트 테스트 테스트") {
        And("B가 3일 때") {
            val b = 3
            When("함수를 실행하면") {
                val result = sum(b = b)
                Then("결과값이 3") {
                    result shouldBe 3
                }
            }
        }
        And("B가 4일 때") {
            val b = 4
            When("함수를 실행하면") {
                val result = sum(b = b)
                Then("결과값이 4") {
                    result shouldBe 4
                }
            }
        }
    }
})
```
- All 4 testcases works in `SingleInstance` mode, whereas only three of them works in `InstancePerLeaf` mode
- When second Given description changes to `테스트 테스트`, all 4 testcases works well even in `InstancePerLeaf`
- Typing in Korean sometimes made a problem. I guess a particular circumstance makes a problem.
- Korean words/sentences are meaningless in ’Given Description’. I made up meaningless Korean for reenacting the error.

Is it just me or something like bug?

**Comment by sksamuel** [comment]
Sounds like a bug. I think easy fix for 4.4.2.

**Comment by henry-jo** [comment]
Okay, thanks :)

**Comment by sksamuel** [comment]
I cannot duplicate this error.

![image](https://user-images.githubusercontent.com/743706/108606280-d44fb880-737e-11eb-9e15-40b255e03d87.png)

I added a test here: https://github.com/kotest/kotest/commit/407351dba6b8a93805709aec836a46b51fe915a4

Did I copy the test case correctly ?

**Comment by henry-jo** [comment]
@sksamuel 
Correct.

I tested it again in the latest version. Works well.

I mentioned above, I did the test on 4.3.2.
On 4.4.1, all tests are working well. 
What changes are there between previous and new version?

**Comment by sksamuel** [comment]
In 4.4.0 the way test names were stored was tweaked to support non-ascii. So that probably fixed this too.
I think we can close this now ?

**Comment by henry-jo** [comment]
Yes, Thanks for your help.
