### ISSUE TITLE
assertSoftly breaks eventually

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#2083]
**Which version of Kotest are you using**
4.4.1

```kt
@ExperimentalTime
class SimpleTest: StringSpec({
    "eventually a second passes" {
        val target = System.currentTimeMillis() + 1000
        eventually(2.seconds) {
            System.currentTimeMillis() shouldBeGreaterThan target
        }
    }
    "softly, no second passes eventually" {
        val target = System.currentTimeMillis() + 1000
        assertSoftly {
            eventually(2.seconds) {
                System.currentTimeMillis() shouldBeGreaterThan target
            }
        }
    }
})
```
both tests should pass, but the second doesn't: Due to the soft assert mode, the exception isn't propagated to any catch block but instead rethrown at some later point.

I think soft assertions should use some sort of scope that is overriden by the eventually instead of the special handling by the Matchers they get currently.

**Comment by sksamuel** [comment]
You can move the assertSoftly inside the eventually and it will work.

And we can think of a long term solution.

**Comment by xeruf** [comment]
I didn't even mean to use an `assertSoftly` there, it was a leftover that puzzled me for a while since I did not expect the respective test to fail.

**Comment by sksamuel** [comment]
assertSoftly activates a flag that tells the matchers not to throw exceptions but to collect them. So eventually isn't seeing the exceptions to know to loop.

I think we could have eventually opt into this mechanism too so it knows to ignore that setting.
