### ISSUE TITLE
Kotest dependencies include kotlin standard library as dependencies but should make them as provided

### ISSUE THREAD

**Issue by piyushmor** [kotest/kotest#2084]
**Which version of Kotest are you using** 4.4.1

currently when kotest dependency is added to a project the kotlin stdlib for the version on which it was built it also included as a dependency. I think the kotlin standard libraries should be something that we count as provided.

**Comment by sksamuel** [comment]
Are you using maven ?

**Comment by piyushmor** [comment]
yes, talking about the repo `zalando/opentracing-toolbox`

**Comment by sksamuel** [comment]
Maven is getting confused by gradle's "implementation" configuration I think.
I'll try removing the stdlib definitions from as many things as possible.
