### ISSUE TITLE
Eventually sometimes only checks a single time despite short  scheduled intervals

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#2089]
**Which version of Kotest are you using**
4.4.1

```java
java.lang.AssertionError: Eventually block failed after 200ms; attempted 1 time(s); FibonacciInterval(base=20.0ms, offset=0, max=120m) delay between attempts
```
I regularly encountered this now. Per se it isn't a big problem if the intervals aren't followed exactly, if the tests keep my processors busy it doesn't really matter. However, the eventually should definitely do at least a second check at the end of its interval.

**Comment by sksamuel** [comment]
If I do `eventually(1.seconds, 10.seconds)` would you expect it to run once or twice?
I like the thinking behind this, but also if your test is expensive then running it again as you exit the loop might be unexpected.

**Comment by xeruf** [comment]
I would expect it to run twice, yes. Imo, regardless of the interval, there should be a check at the end of the duration. How can such a test be that expensive that that would be a problem?

Either way, in the above case, it should definitely run more than once - if the coroutines are all busy and there are only two checks with one at the end of the duration, fine, but that second check needs to come through then.

**Comment by jschneidereit** [comment]
Personally, I've got some pretty expensive tests and risk of being throttled will cause other problems. We should think about this carefully...

**Comment by sksamuel** [comment]
I don't see why you would always want the test to run again after the duration is over?
I mean you're explicitly saying, please run this for 5 seconds, not 5 seconds + another go.
I'm open to being convinced though :)

**Comment by xeruf** [comment]
Okay, whether this should always happen is debatable, but this is not:

> Either way, in the above case, it should definitely run more than once - if the coroutines are all busy and there are only two checks with one at the end of the duration, fine, but a second check needs to happen for sure.

**Comment by jschneidereit** [comment]
If the second check doesn't happen, doesn't that just mean your duration was too short or your delay too long?

**Comment by sksamuel** [comment]
I think the problem can be solved. When we exit the eventually loop, we check the time from the last run. If _that_ time is > interval, then we run one more time.

This solves the problem whereby a dispatcher is not free to run the eventually and it never runs before the delay expires.

What do you think @jschneidereit @xerus2000

**Comment by xeruf** [comment]
Yes, that was exactly what I wanted :)

**Comment by xeruf** [comment]
> If the second check doesn't happen, doesn't that just mean your duration was too short or your delay too long?

No, coroutines are queued, and sometimes they are delayed a bit more if other busy coroutines are still working. Please read the error in my first comment carefully.

**Comment by sksamuel** [comment]
Do you want to make the PR or shall I? @xerus2000

**Comment by xeruf** [comment]
Would be nice if you did @sksamuel :)

**Comment by sksamuel** [comment]
Ok I'll pick it up tonight or tomorrow.
