### ISSUE TITLE
Merge FunSpec and ShouldSpec?

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#2093]
Is there any architectural reason to not have a single style where both `test` and `should` can be used? I actually have tests where that could be convenient.

**Comment by sksamuel** [comment]
No reason why you couldn't combine a bunch of them really.
I guess history.
Could have a new one that replaces them both, and the other two are discouraged.

**Comment by sksamuel** [comment]
Or what you say, add should support into fun spec.

**Comment by sksamuel** [comment]
Closing this as this won't happen before 5.0 which is probably a year or two away.
