### ISSUE TITLE
Unable to use non suspend version of forAll

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#2123]
Currently both suspend and non-suspend version of forAll are in same package as result if I try to use non-suspend version of forAll, kotlin automatically try to infer that suspend version of forAll is getting used and shows error. 
<img width="1135" alt="Screenshot 2021-02-22 at 7 15 09 AM" src="https://user-images.githubusercontent.com/34642693/108647061-b51b6d00-74dd-11eb-9773-3c003493c8cd.png">

```
Suspend function 'forAll' should be called only from a coroutine or another suspend function
```

We should keep the them in separate package to avoid this ambiguity.

**Comment by sksamuel** [comment]
Is this data testing for all, or property testing for all ?

**Comment by ashishkujoy** [comment]
Property testing forAll

**Comment by sksamuel** [comment]
We should move the non-suspend to a `io.kotest.....blocking` package then ?

**Comment by ashishkujoy** [comment]
> We should move the non-suspend to a `io.kotest.....blocking` package then ?

Yes, changing package is the only option I can see.

**Comment by ashishkujoy** [comment]
@sksamuel I just realised that we already have non-suspend version of forAll  in `io.kotest.data.blocking` package.

```kotlin
fun <A> forAll(vararg rows: Row1<A>, testfn: (A) -> Unit)
```

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/data/blocking/forAll1.kt

The other non-suspending forAll in `io.kotest.data` is
```kotlin
inline fun <A> forAll(table: Table1<A>, testfn: (A) -> Unit)
```
https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/data/forAll1.kt

My IDE was for some unknown reason not giving import suggestion for `io.kotest.data.blocking`

Closing this issue.
