### ISSUE TITLE
Project Config should have option for failing if no tests were executed

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#2127]
- config for failing project if there are no tests that match tag expression
- `declaredTags()` should be accessible from `ProjectListener`

**Comment by jschneidereit** [comment]
Maybe in `runTestsIfAtLeastOneActive`

**Comment by sksamuel** [comment]
Shall we do this for 4.6 ?

**Comment by jschneidereit** [comment]
I'll take a look at it tomorrow to see if it's doable in the short term

**Comment by sksamuel** [comment]
This actually should just be a check if any tests ran or not. Doesn't matter if it was caused by a tag, test filter, just having no tests, or whatever.
