### ISSUE TITLE
Temporary files / directories should give a clue about which test / spec created them

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#2136]
Looking at

https://github.com/kotest/kotest/blob/62012f30d12ac44d639883189d0e6a11e7c65265/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/tempfile.kt#L7

and

https://github.com/kotest/kotest/blob/62012f30d12ac44d639883189d0e6a11e7c65265/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/spec/tempdir.kt#L6

I wonder whether we could apply a smarter default value for `prefix` which gives a clue about which test / spec created them, so that for any left-over files / dirs one could easily inspect the test (which then probably crashed the hard way).

**Comment by sksamuel** [comment]
Excellent idea.

**Comment by sschuberth** [comment]
But does the `TestConfiguration` have any knowledge about the test / spec name? After a quick look I don't think that's the case. So where could we get that information from?

**Comment by sksamuel** [comment]
Test name no, but it could get it's classname.
