### ISSUE TITLE
Arrow matchers with fn are missing in lots of places

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#2137]
When looking and using the Either / Validated assertion function, you can use

shouldBeValid { ... } to give more assertions to the encapsulated valid T.

BUT: when you need a matcher, you only got beValid() and beValid(e: T) - the corresponding function lambda assertion is simply missing.

This applies to basically all types mentioned above.

Is there a reason for this lack of matcher? It is absolutely necessary to also be able to should beValid { ... } 

Thanks!

**Comment by sksamuel** [comment]
I think the original idea was we'd have smart cast contracts by now for higher kinded types, but that doesn't seem to be coming.

If you had the time to add lambda versions that would be great.

**Comment by sksamuel** [comment]
The arrow matchers have been completely overhauled thanks to work by @i-walker 
Now they can do smart casting and should do exactly what you need.

For example.

```kotlin
val valid = Valid(v)
valid shouldBeValid v
// smart cast test
valid.value shouldBe v
```

See: 
https://github.com/kotest/kotest-extensions-arrow/blob/master/src/commonTest/kotlin/io/kotest/assertions/arrow/core/ValidatedMatchers.kt#L33-L36

**Comment by sksamuel** [comment]
Closing this as the new arrow matchers do everything that's requested in this ticket.
