### ISSUE TITLE
Easy way to check collection against a collection of matchers

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#2144]
Here's the problem.
I have a collection of elements `Collection<E>` that I want to test using a collection of Matchers / functions `Collection<Matcher<E>>`.

I cannot test using `shouldBe listOf(...,...,...)` or even any of the `shouldContain` variants - because all of them require concrete instances of E to be checked against, not inspections.

What I need is inspection - but none of the inspector methods `forExactly` (and the others) do the trick to actually take a collection of matchers / functions and assure there's a match between every element E and a corresponding matcher.

My current way around this is awkward.

```
val actual: Collection<E> = ...
val checks: Collection<(E)->Unit> = ...
withClue("size differs") {
    actual.size shouldBe checks.size
}
checks.forEach { check ->
    actual.forOne(check)
}
```

This is also opening problems if the checks "overlap" as I do not really check there's a 1:1 relationship between a check and an actual value.

What is really needed is: 
Is each given check matching exactly one distinct and unique item of the actual elements?

(In my case order does not matter, but of course that might also be useful!)

**Comment by sksamuel** [comment]
So if I understand, if you have a collection of size 5 and 5 matchers, each matcher should work on a single element, and each element should work on a single matcher.

**Comment by Zordid** [comment]
Correct. In a very concrete situation now, I have 10 strings in a list. But I only know that they must contain certain substrings "1 of 10", "2 of 10", "3 of 10", etc.

I simply do not know how to test that in kotest.

In Hamcrest, I created a list of matchers, each being "`containsString`" and then checked `hasItems(matchers)`.

Any ideas?

**Comment by sksamuel** [comment]
Can you link me to the hamcrest stuff.

**Comment by Zordid** [comment]
One missing way that Hamcrest offers as an example is to check a collection/iterable agains a set of matchers where the logic is that all matchers must "find" a corresponding item.
http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/CoreMatchers.html#hasItems-org.hamcrest.Matcher...-

If I try that with Kotest, I am out of luck. You can only check against concrete items, but not against matchers / predicates.
