### ISSUE TITLE
Why does shouldHaveSingleElement and other Collection "shoulds" have predicate instead of block for assertions?

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#2145]
What I do not really get is: when does your library want predicates (T)->Boolean and when does it require a function block that itself can do multiple assertions using matchers and should constructs?

I.e.:
```
list.shouldHaveSingleElement {
   it.name == "Bob"
}
```

vs. (not the case)
```
list.shouldHaveSingleElement {
  it.name shouldBe "Bob"
}
```

I've stumbled across both ways, but the simple predicate one is used for collections - and I do not like it at all, because the error messages don't reveal any reason for failing the match whereas the latter one could state that something was expected to be "Bob" but is "Alice" for example.

Is there a reason behind this that I cannot see?

**Comment by sksamuel** [comment]
It's probably just because the project is large and we have a smaller number of regular committers so there will be some areas that miss functionality like this. If you want to make a PR that would be great, or if you have a list of matchers you want the block for we'll add them.

**Comment by Kantis** [comment]
@sksamuel maybe we should deprecate these with 5.0 and remove in 6.0? For this particular case, I think the proper method to use would be

```kotlin
list.forOne {
  it.name shouldBe "bob"
}
```

**Comment by sksamuel** [comment]
Yeah the inspectors are what is meant to be used.

We should rename the first one to include the word predicate in it. That
indicates its boolean.

**Comment by sksamuel** [comment]
Let's deprecate any block that is essentially doing the same as the inspectors.
But we should keep blocks that have a predicate, as it's nice for one liners, but maybe converge on the name shouldExist ?
`list.shouldExist { it.age == 90 }`

**Comment by Kantis** [comment]
I was wrong about replacing with `forOne`, sadly 

`forOne` asserts there's one, and only one, element in the collection that matches the block.
`singleElement` checks that the subject is a collection with a single item, and that the single item matches the predicate.

So the usage would not be equivalent. 


On top of that, I found these matchers which accept predicates.
`existInOrder` checks that, given a list of predicates, they are fulfillfed in the correct order.
`exist` checks that any item fulfills the predicate. 


Suggest we proceed with:

- [x] Deprecate `exist`, in favor of `forAny`
- [x] ~Add `singleElement` matcher which accepts a block, and deprecate predicate version~
- [x] Add `forSingle` inspector
- [x] Add `existInOrder` matcher which accepts a list of blocks, and deprecate predicate version

After doing this, there will be no remaining matchers which accepts predicates.

**Comment by sksamuel** [comment]
Could we come up with an inspector for singleElement so it aligns nicely ?
`forOnly` ?
`forSingle` ?

**Comment by Kantis** [comment]
`forSingle` and `forOne` feels like they would get mixed up.

I vote for `forOnly` in that case. It feels "different" enough to distinguish it a bit.

**Comment by sksamuel** [comment]
The std lib has the method .single() to extract only a single element from a list, and throw if the list does not have size 1.

**Comment by Kantis** [comment]
Should we do `existInOrder` as an inspector as well? `forInOrder { }`?

**Comment by sksamuel** [comment]
How would that work?

**Comment by Kantis** [comment]
Here's the predicate version: 
```kotlin
fun <T> existInOrder(vararg ps: (T) -> Boolean): Matcher<Collection<T>?> = existInOrder(ps.asList())

/**
 * Assert that a collections contains a subsequence that matches the given subsequence of predicates, possibly with
 * values in between.
 */
fun <T> existInOrder(predicates: List<(T) -> Boolean>): Matcher<Collection<T>?> = neverNullMatcher { actual ->
   require(predicates.isNotEmpty()) { "predicates must not be empty" }

   var subsequenceIndex = 0
   val actualIterator = actual.iterator()

   while (actualIterator.hasNext() && subsequenceIndex < predicates.size) {
      if (predicates[subsequenceIndex](actualIterator.next())) subsequenceIndex += 1
   }

   MatcherResult(
      subsequenceIndex == predicates.size,
      { "${actual.print().value} did not match the predicates ${predicates.print().value} in order" },
      { "${actual.print().value} should not match the predicates ${predicates.print().value} in order" }
   )
}
```

I suppose the inspector version would be:

```kotlin
/**
 * Assert that a collection contains a subsequence that matches the given subsequence of [assertions], possibly with
 * values in between.
 */
fun <T, C : Collection<T>> C.forInOrder(assertions: List<(T) -> Unit>): C {
  TODO()
}
```

**Comment by sksamuel** [comment]
I think the difference here, is that they are single predicates. So each predicate is executed in turn on the next element of the list.

With inspectors, everything in the block is executed every each element, and the counts then compared to the requirements.
