### ISSUE TITLE
System Exit Extension: Test fails though it should pass

### ISSUE THREAD

**Issue by deining** [kotest/kotest#2156]
**Kotest 4.4.2**

I encountered strange behaviour when using the `System Exit Extension`:

Minimum working example:

```
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.extensions.system.*
import io.kotest.matchers.shouldBe
import picocli.CommandLine
import picocli.CommandLine.Command
import java.util.concurrent.Callable
import kotlin.system.exitProcess

class SystemExitTest : StringSpec() {

    override fun listeners() = listOf(SpecSystemExitListener)

    init {
        "Test passes as expected" {
            shouldThrow<SystemExitException> {
                exitProcess(CommandLine(PicocliApp()).execute())
            }.exitCode shouldBe 42
        }

        "Test fails though it should pass" {
            shouldThrow<SystemExitException> {
                CommandLine(PicocliApp2()).execute()
            }.exitCode shouldBe 42
        }
    }
}

@Command
class PicocliApp : Callable<Int> {
    override fun call(): Int {
        return 42
    }
}

@Command
class PicocliApp2 : Callable<Int> {
    override fun call(): Int {
        exitProcess(42)
    }
}
```

I'm testing a command line application based on the [https://picocli.info](picocli) framework.

**First test:** PicocliApp app is called, returns an exit code, top level process exits with returned code. Everything is fine here.

**Second test:** PicocliApp app is called, app exits inside the overriden `call` function. Test fails though it should pass.

I tested the both same tests using Stefan Birkner's [System rules](https://stefanbirkner.github.io/system-rules/index.html). **Result:** both tests pass (as expected).

I admit that it is a bit unusual to exit from the `call` function of a command. Certainly the better way of coding is following the convention to return an exit code and call System.exit from the main method with the return value of the `execute` method. Nonetheless, test 2 contains valid code which should be handled correctly from the test framework.

Thanks for investigating!

**Comment by sksamuel** [comment]
If you do something like this:

```kotlin
class SystemExitTest : StringSpec() {

  override fun listeners() = listOf(SpecSystemExitListener)

  init {

    "System.exit should throw an exception and not exit when the listener is added" {
      shouldThrow<SystemExitException> {
         exitProcess(PicocliApp2().call())
      }.exitCode shouldBe 42
    }
  }
}

class PicocliApp2 : Callable<Int> {
   override fun call(): Int {
      exitProcess(42)
   }
}
```

It works fine.
So the picocli app must be doing something inside the CommandLine constructor or execute method.

**Comment by sksamuel** [comment]
This is a guess, but if execute forks, then the exitProcess inside App2 is just going to exit the forked JVM and therefore cannot be intercepted by the kotest security manager.

**Comment by LeoColman** [comment]
```
CommandLine(PicocliApp2()).execute()
```
doesn't throw an exception. 

It instead executes your code and calculates an exit code based on what was executed. The exception is never rethrown, and for such reason you can't catch it with `shouldThrow`.

It has nothing to do with forking the JVM. It's just that the exception won't fall through.

What we can do is improve the listener to record every caught `System.exit` and then people can assert the exits in other ways.

**Comment by LeoColman** [comment]
The line that won't rethrow the exception is 

in this class, line 2090~ 

https://github.com/remkop/picocli/blob/e5aa2d88a5cbe12a66da639233a4e9169b8fd528/src/main/java/picocli/CommandLine.java

**Comment by sksamuel** [comment]
Oh nice find

**Comment by LeoColman** [comment]
I don't think that would be very used, but it also isn't that hard to implement and won't be too confusing. I'm not against it :D

**Comment by sksamuel** [comment]
I guess its easy enough for SpecSystemExitListener to store the last return code so it can be inspected. That's how the Java one works.

**Comment by sksamuel** [comment]
What do you think about something like this https://github.com/kotest/kotest/pull/2157 @LeoColman

**Comment by deining** [comment]
> What we can do is improve the listener to record every caught `System.exit`

Doesn't that make sense?

I see it from a test user perspective: I called `System.exit` and want to test for this, but the test fails.
Like said, other test systems perform different (=better) when confronted with my second test case.

You may also have a look at the [perspective](https://github.com/remkop/picocli/issues/1341#issuecomment-792678217) from the author of picocli.

**Comment by remkop** [comment]
An alternative would be to throw a Throwable from the security manager instead of Exception, because my guess is that libraries and applications are less likely to catch all Throwables (and cause the same issue with the test). However, "less likely" is not zero. :-)

The approach suggested by @sksamuel to store the last return code so it can be inspected is more robust. 

Thanks all for raising this and the analysis!
And nice work with the kotest library! :-)
