### ISSUE TITLE
shoud(Not)BeEmpty for maps is missing

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#2160]
Maps can also be verified to be empty. Currently only 

`map shouldHaveSize 0`

is offered, but for `shouldBeEmpty` this is needed:

`map.toList().shouldeBeEmpty()`

**Comment by sksamuel** [comment]
Is this not working for you

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/maps/matchers.kt#L56-L57

**Comment by Zordid** [comment]
So sorry! Was on 4.4.1... did not update until just 5 minutes ago where I also found a bug you already fixed. My mistake! Thanks! Need to get to contribute to your project soon, currently very busy trying to port everything to kotest...
