### ISSUE TITLE
Assert softly on target ?

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2162]
Perhaps,

```
a.b.c.assertSoftly {
  this.shouldStartWith("a")
  this.shouldHaveLength(4)
}
```

**Comment by ashishkujoy** [comment]
how will it be different from the existing.

```kotlin
assertSoftly(a.b.c) {
  it.shouldStartWith("a")
  it.shouldHaveLength(4)
}
```

**Comment by LeoColman** [comment]
https://github.com/kotest/kotest/issues/1427

**Comment by LeoColman** [comment]
We removed it because it went bananas with the current syntax

**Comment by LeoColman** [comment]
https://github.com/kotest/kotest/pull/1557

**Comment by LeoColman** [comment]
https://kotlinlang.slack.com/archives/CSYLDDZUY/p1594489972146700

**Comment by sksamuel** [comment]
Ahh that's right.
Silly me.
