### ISSUE TITLE
Support JS/IR in Framework

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#2163]
snapshot:  4.6.0.166-SNAPSHOT.

Sample code for reproducing the issue: https://github.com/ashishkujoy/kotlin-js-jvm-library

**Comment by sksamuel** [comment]
Running your project:

![image](https://user-images.githubusercontent.com/743706/119258637-2aa3e180-bb90-11eb-981c-a6007f6c5537.png)


Did you use gradle check?
Because gradle test doesn't do anything with JS tests.

**Comment by ashishkujoy** [comment]
Yes I was using gradle check , but I don't think kotest is running that test, because in js module that test should have failed with assertion error, unless you have modified something after cloning it.

**Comment by sksamuel** [comment]
Yes you're right, I see now.

**Comment by sksamuel** [comment]
So the issue is setFrameworkAdapter seems to do nothing in IR mode.

**Comment by SebastianAigner** [comment]
Unfortunately, this is a limitation in the current version of the JS IR backend. You can track the progress of supporting switching test adapters here: https://youtrack.jetbrains.com/issue/KT-42283

**Comment by sksamuel** [comment]
Compiler plugin added to execute kotest specs in a similar way to how the kotlin compiler does it for kotlin.test tests.
See PR at https://github.com/kotest/kotest/pull/2345

@SebastianAigner would you be able to confirm that this is a good approach? The basic logic is: for each Kotest test class detected by the compiler plugin, we add a top level property like `val _kotest_my_test_class = runSpec(MyTestClass())`
This relies on the fact that top level vals are added to the "main" body of the generated JS file.

**Comment by Pitel** [comment]
It's not working for me. I tried latest 5.0.0 snapshot (310), and it look like now no tests are run.

* My jsTest testing test which should always fails is not failing.
* No report is generated bby Gradle.

JVM is still working fine, btw.

**Comment by sksamuel** [comment]
@Pitel We're a little bit early for people to test with yet. We need to publish the gradle plugin which is required for compiler plugins to work, and there are a couple of tweaks. I'll come back in a few days with full details on how you can help us test 5.0!

**Comment by anton-bannykh** [comment]
> @SebastianAigner would you be able to confirm that this is a good approach? The basic logic is: for each Kotest test class detected by the compiler plugin, we add a top level property like `val _kotest_my_test_class = runSpec(MyTestClass())`
> This relies on the fact that top level vals are added to the "main" body of the generated JS file.

Should be fine for now. AFAIK we don't have a better solution for plugins at the moment.

P.S. Make sure `-Xir-property-lazy-initialization` is disabled (https://github.com/JetBrains/kotlin/blob/ff26a471b42707144ebd28778695f06ccf934821/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JSCompilerArguments.kt#L142). I don't think it will be enabled by default, until there is a good way to force side-effects for use-cases similar to yours. But this is a potential gotcha nevertheless.

**Comment by sksamuel** [comment]
Thanks @anton-bannykh. Should that flag by added by users since they're generating the final JS files ?

**Comment by sksamuel** [comment]
5.0.0.M1 has been released which has the first support for JS/IR.
Docs on usage is available here: https://kotest.io/docs/framework/multiplatform.html

**Comment by Pitel** [comment]
Still does not work for me.

It says  `BUILD SUCCESSFUL`, but there is a test which should fail (`false.shouldBeTrue()`).

```
import org.jetbrains.kotlin.gradle.dsl.KotlinCompile
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension
import org.jetbrains.kotlin.gradle.tasks.Kotlin2JsCompile

plugins {
	val kotlinVersion = "1.5.30-RC"
	kotlin("js") version kotlinVersion
	kotlin("plugin.serialization") version kotlinVersion
	id("io.kotest.multiplatform") version "5.0.0.5"
}

repositories {
	mavenCentral()
}

kotlin {
	js(IR) {
		//useCommonJs()
		browser {
			runTask {
				devServer = devServer?.copy(
					proxy = mutableMapOf(
						"/apiIs2" to mapOf(
							"target" to "https://x.x.x:8088",
							"secure" to false
						)
					)
				)
			}
			commonWebpackConfig {
				cssSupport.enabled = true
			}
		}
		binaries.executable()
	}
}

tasks.withType<KotlinCompile<*>>().configureEach {
	kotlinOptions {
		freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
	}
}

tasks.withType<Kotlin2JsCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xir-property-lazy-initialization"
	}
}

// https://youtrack.jetbrains.com/issue/KT-48273
afterEvaluate {
	extensions.configure<NodeJsRootExtension> {
		versions.webpackDevServer.version = "4.0.0"
	}
}

dependencies {
	val wrapper = "pre.214-kotlin-1.5.20" // Newer breaks Muirwik!
	implementation("org.jetbrains.kotlin-wrappers:kotlin-react-router-dom:5.2.0-$wrapper")
	implementation("org.jetbrains.kotlin-wrappers:kotlin-react-redux:7.2.4-$wrapper")
	implementation("org.jetbrains.kotlin-wrappers:kotlin-redux:4.1.0-pre.234-kotlin-1.5.21")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1")
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2")
	implementation("com.soywiz.korlibs.klock:klock:2.3.1")

	implementation("com.ccfraser.muirwik:muirwik-components:0.8.2")
	implementation("org.jetbrains.kotlin-wrappers:kotlin-styled:5.3.0-$wrapper")
	implementation(npm("@material-ui/core", "4.11.4"))
	implementation(npm("@material-ui/lab", "4.0.0-alpha.60"))
	implementation(npm("@material-ui/pickers", "3.3.10"))
	implementation(npm("date-fns", "2.23.0"))
	implementation(npm("@date-io/date-fns", "1.3.13")) // 2.x breaks pickers!

	implementation(npm("highcharts", "9.2.1"))
	implementation(npm("highcharts-react-official", "3.0.0"))

	implementation(npm("@uiw/react-codemirror", "3.1.0"))

	testImplementation("io.kotest:kotest-framework-engine:5.0.0.M1")
	testImplementation("io.kotest:kotest-assertions-core:5.0.0.M1")
	testImplementation("io.kotest:kotest-property:5.0.0.M1")
}
```

**Comment by sksamuel** [comment]
`freeCompilerArgs += "-Xir-property-lazy-initialization"` should be removed

**Comment by Pitel** [comment]
For some reason, my webapp refused to worked without the flag. So I've managed to disable it conditionaly:
```kotlin
tasks.withType<Kotlin2JsCompile> {
    if (!name.contains("Test")) {
        kotlinOptions {
            freeCompilerArgs += "-Xir-property-lazy-initialization"
        }
    }
}
```

**Comment by bashor** [comment]
JFYI starting from 1.6.20 it's possible to provide own adapter from JS without using compiler plugin, like described [here](https://youtrack.jetbrains.com/issue/KT-42283#focus=Comments-27-5994631.0-0). If you you have any question feel free to ask in the issue ([KT-42283](https://youtrack.jetbrains.com/issue/KT-42283)).

cc @sksamuel

**Comment by sksamuel** [comment]
Thanks for the update @bashor
