### ISSUE TITLE
Is it possible to smart cast when using `shouldBe` and `shouldNotBe` ?

### ISSUE THREAD

**Issue by basshelal** [kotest/kotest#2175]
I know there exists the `shouldBeNull()` and `shouldNotBeNull()` which allow for smart casts, but is it possible to allow the more generic `shouldBe` and `shouldNotBe` have the same?

For example:

```kotlin

"test" {
    var myBool = true
    val myString: String? = if (myBool) "true" else null

    myString shouldNotBe null

    myString.length // Error: Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?

    myString.shouldNotBeNull()
        
    myString.length // Smart cast to kotlin.String
        
}

```

I know in order to implement this you would have to use the Kotlin contracts DSL as is shown in the implementation of `shouldNotBeNull()` and `shouldBeNull()`.

I'm not sure if this is even possible since I don't know how the contracts DSL can even tell the difference between `null` as a value as I use it above and nullable types in general, especially if they are mutable, for example:

```kotlin

"test" {
    var myNull: String? = null
    var myBool = true
    var myString: String? = if (myBool) "true" else null

    myString shouldNotBe myNull
        
    // Cannot infer runtime value of `myNull` so no smart casts? Unsure...

}

```

Clearly I'm not knowledgeable about any of this jazz but I wanted to bring it up anyway in case it was possible to at least explore since it would be a nice to have.

The ideal situation would be:

```kotlin

"test" {
    var myBool = true
    val myString: String? = if (myBool) "true" else null

    myString shouldNotBe null
        
    myString.length // Smart cast to kotlin.String
        
}


```

Many thanks

**Comment by sksamuel** [comment]
Contracts don't support this at the moment.
As you say, the `.shouldNotBeNull()` matchers will smart cast.
