### ISSUE TITLE
upgrade `kotest-assertions-arrow` to work with Arrow 0.13.1

### ISSUE THREAD

**Issue by jwalrus** [kotest/kotest#2187]
Upgrade the `kotest-assertions-arrow` assertions to work with Arrow 0.13.1. A number of things have changed, for example, `Either.Right.b` and `Either.Left.a` are now simply `Either.Right.value` and `Either.Left.value`

**Comment by jwalrus** [comment]
I am really interested in contributing to this project and kotest more generally. Let me know if you'd like discuss how you see this set of matchers evolving, for example, `Eq`, `Order`, etc are being deprecated in Arrow `0.12.0` and removed in `0.13.1`.   Really, most of the higher-kinded stuff is begin removed.

**Comment by cldfzn** [comment]
I've made changes to at least compile and pass tests with the latest arrow:
https://github.com/kotest/kotest-assertions-arrow/pull/1

**Comment by jwalrus** [comment]
thanks @cldfzn. FWIW, thanks to Arrow's strategy of deprecating everything in 0.12.0, it appears one can upgrade Arrow to 0.12.0 and everything works just fine with the current version of the library. However, we need @cldfzn changes before upgrading to 0.13.1

**Comment by sksamuel** [comment]
One of the reasons I moved this to a top level repo was so that we can iterate much faster compared to the main repo.
I think we can keep this in line with the current arrow release whenever that changes.

**Comment by ReaktorDTR** [comment]
Hi. I noticed changes related to migrating to the new version of the Arrow library. 
In merge request was used a new way of creating NonEmptyList using constructor `NonEmptyList(1, listOf(2, 3, 4, 5))`. But I found a better way to do it using function `nonEmptyListOf(1, 2, 3, 4, 5)`. 
I tried to make a pull request to the repo but I don't have access to create a branch.

It's a minor thing, you can just ignore this message and close the issue.

**Comment by sksamuel** [comment]
@ReaktorDTR feel free to open a PR if you wish.
Closing this ticket as the latest kotest arrow release is on 0.13.x
