### ISSUE TITLE
Failing kotest assertion seems to not be correctly propagated to test results in IntelliJ

### ISSUE THREAD

**Issue by bjpe** [kotest/kotest#2192]
Hi everyone, 

we a have project with Java and Kotlin code, and both have JUnit and kotest tests (we are migrating from Java to Kotlin). When we execute all tests in IntelliJ using the context menu action Run 'All Tests', we observed the following irritating behaviour:
* Both JUnit and kotest tests are executed (good)
* A failing JUnit assertion marks the test class and the entire test executed as failed (good)
* A failing kotest assertion does not mark the test class and the entire test executed as failed (bad)

I just created https://github.com/bjpe/kotest-bug as an example code base, and the test execution results looks as follows:
![image](https://user-images.githubusercontent.com/449704/113974537-5ec07e80-983e-11eb-8aa7-8fff7a6094e3.png)

What we would expect is that kotest.FailingKotestTest is marked as failed as well. Strangely, if I open the same result via the "Test History" option, the result is as expected:
![image](https://user-images.githubusercontent.com/449704/113974786-c8d92380-983e-11eb-915c-9ff650c30295.png)

I'm using IntelliJ 2021.1 with kotest plugin 1.1.30-IC-211-EAP-SNAPSHOT. If you need more details, please give me a hint.

Kind Regards,
Björn

**Comment by bjpe** [comment]
Hi everyone,

in case this is the wrong project I also reported it as https://github.com/kotest/kotest/issues/5450.

**Comment by sksamuel** [comment]
So the issue is that you want the entire tree to be marked failed if a child test fails ?

If so, I don't think this is a bug. The junit spec says this:

	 * <p>The {@link TestExecutionResult} describes the result of the execution
	 * for the supplied {@code testDescriptor}. The result does not include or
	 * aggregate the results of its children. For example, a container with a
	 * failing test must be reported as {@link Status#SUCCESSFUL SUCCESSFUL} even
	 * if one or more of its children are reported as {@link Status#FAILED FAILED}.

And that's what Kotest is doing. If you change your test so that the failure is one nested level higher, then it works as you expect.

```kotlin
class FailingKotestTest : DescribeSpec({
    describe("addition") {
        1 + 1 shouldBe 1
        it("should add two numbers") {
        }
    }
})
```

![image](https://user-images.githubusercontent.com/743706/119284764-1d293e80-bc06-11eb-8e8c-762b5ba6f542.png)

What we could do is add an option so that a failure in a child marks the entire tree as failed ?
