### ISSUE TITLE
assertSoftly non-inline version

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2196]
assertSoftly is inline, so debugging doesn't work in intellij.
We can make this not-inline but then you can't use suspend functions inside it, unless we make this suspend too. Which is fine for kotest, but wouldn't be great for other frameworks like junit.

Perhaps we add a kotest specific version that is suspend ?

**Comment by LeoColman** [comment]
Didn't the new Kotlin plugin theoretically solve the issue with inline and debugging?

I remember reading something like this in the latest patch notes

**Comment by sksamuel** [comment]
I've not tried it with 1.5 M2 but the you track tickets I read  are not marked as fixed or even with a targetted version

**Comment by sksamuel** [comment]
@jschneidereit  your new all { } is not inline right ?

**Comment by jschneidereit** [comment]
Yep! `all` is suspending and not inline

**Comment by sksamuel** [comment]
Ok so we have a solution already then.
