### ISSUE TITLE
Option.shouldBeNone() is defined with non-nullable Any

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#2203]
**Which version of Kotest are you using**
4.4.3

I have an Option<Any?> that I need to test against being none.
I was quite surprised, `x.shouldBeNone()` did not compile... Turns out, that `shouldBeNone()` is defined like this:
```
public fun arrow.core.Option<kotlin.Any>.shouldBeNone(): kotlin.Unit { /* compiled code */ }
```

To correct that, add a ?:
```
public fun arrow.core.Option<kotlin.Any?>.shouldBeNone(): kotlin.Unit { /* compiled code */ }
```

would also work. Same applies for `shouldNotBeNone` of course and `beNone`.

In fact - one of the few reasons why anybody would use Option instead of a nullable type in Kotlin is, that the contained type is in fact nullable!

So this is definitely a hard bug...

**Comment by sksamuel** [comment]
For anyone reading in the future, this has been completed in the kotest arrow repo:
https://github.com/kotest/kotest-assertions-arrow
