### ISSUE TITLE
Add watchos support back for x86

### ISSUE THREAD

**Issue by PaulWoitaschek** [kotest/kotest#2204]
As watchos support was removed for x86, we're stuck with kotest 4.4.0.

There are [arm32](https://mvnrepository.com/artifact/io.kotest/kotest-common-watchosarm32) libraries for 4.4.3 but [x86](https://mvnrepository.com/artifact/io.kotest/kotest-common-watchosx86) is still at 4.4.0

**Comment by sksamuel** [comment]
Aren't we waiting on coroutines to support it ?
Or did that happen already ?

**Comment by PaulWoitaschek** [comment]
No, it's the old target that has been removed from the watchos shortcut but is still in use for us.

**Comment by sksamuel** [comment]
And wasn't that removed from latest coroutines? So 1.4.3 doesn't have either ?

**Comment by PaulWoitaschek** [comment]
Nope
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-watchosx86/1.4.3

**Comment by sksamuel** [comment]
So I don't know a lot about watchos (I don't use apple stuff). So I've looked at this:
https://kotlinlang.org/docs/mpp-supported-platforms.html
There are four watchos targets.

And I can't see coroutines published for kotlinx-coroutines-watchosx64 seems to be an open ticket too:
https://github.com/Kotlin/kotlinx.coroutines/issues/2524

So we can publish for arm32 arm64 and watchx86 right ?

**Comment by sksamuel** [comment]
I will play around in this PR: https://github.com/kotest/kotest/pull/2212

**Comment by PaulWoitaschek** [comment]
Correctly. The pr implementation seems correct.

**Comment by sksamuel** [comment]
@PaulWoitaschek do you know what this means:

Task 'watchosArm32Test' is ambiguous in root project 'kotest'. Candidates are: 'watchosArm32TestBinaries', 'watchosArm32TestKlibrary', 'watchosArm32TestProcessResources'.

Is the watchos test task different to the others ?

**Comment by sksamuel** [comment]
It's now publishing again in the snapshots.
We'll be releasing 4.5 in the next couple of days and that will include all watchos targets.

**Comment by PaulWoitaschek** [comment]
Great! Did you figure out or should I investigate?

**Comment by sksamuel** [comment]
This is all working properly now, the snapshots are back for watchosArm32 watchosArm64 and watchosX86.
4.5 will be released tomorrow or Friday.

**Comment by sksamuel** [comment]
watchosX64 is released now as part of 4.6
