### ISSUE TITLE
JunitXmlReporter XML output files are being overwritten

### ISSUE THREAD

**Issue by mjstrasser** [kotest/kotest#2208]
**Kotest version 4.4.3**

I have specified [JUnit XML Format Reporter](https://kotest.io/docs/extensions/junit_xml.html) so my test names include the nested paths. 

But if the XML report files are written to the standard directory `build/test-results/test` directory, they are overwritten by some other reporting action. I demonstrated that by debugging in IntelliJ with breakpoints in `JunitXmlReporter.kt` and seeing the long names written to the files, before the files are later overwritten.

A workaround is to specify
```Kotlin
    systemProperty("gradle.build.dir", project.buildDir)
```
in `build.gradle.kts` and a different value for `outputDir` in my project configuration, e.g.:
```Kotlin
class ProjectConfig : AbstractProjectConfig() {
    override fun listeners() = listOf(
        JunitXmlReporter(
            includeContainers = true,
            useTestPathAsName = true,
            outputDir = "test-results/kotest"
        )
    )
}
```
Note: [`outputDir` is ignored if the Gradle system property is not set](https://github.com/kotest/kotest/blob/0ba14983d485b1b1caef0e5a2cd7402ba47e34d2/kotest-extensions/kotest-extensions-junitxml/src/jvmMain/kotlin/io/kotest/extensions/junitxml/JunitXmlReporter.kt#L59).

I can’t figure out which Gradle action is overwriting these files. Any ideas?

**Comment by mjstrasser** [comment]
I found a clue from running Gradle with `--debug`.

`2021-04-17T22:57:06.399+1000 [INFO] [org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator] Finished generating test XML results (0.021 secs) into: /Users/michael/dev/kotlin/ktor-features-zipkin/build/test-results/test
`

Is there a way to stop generating those XML files when using `JunitXmlReporter`?

**Comment by sksamuel** [comment]
Can you do something like:

```groovy
test {
    useJUnitPlatform()
    reports {
        junitXml.enabled = true
        html.enabled = false
    }
}
```

**Comment by mjstrasser** [comment]
Thanks @sksamuel for your suggestion (and sorry for the tardy reply).

The Gradle Kotlin sytax that worked for me is:

```kotlin
tasks.test {
    useJUnitPlatform {
        reports {
            junitXml.isEnabled = true
            html.isEnabled = false
        }
    }
}
```

But unfortunately it didn’t help. I can’t remember the details, have a workaround and am not too worried about it.
