### ISSUE TITLE
Add docs for HTML Report

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2211]
As added here: https://github.com/kotest/kotest/issues/2011

**Comment by caramelomartins** [comment]
I could maybe help out with this one if you'd like.

**Comment by sksamuel** [comment]
Awesome please do

**Comment by caramelomartins** [comment]
I haven't had any time to work on this but I'm commenting just so that the stale bot doesn't close the issue.

**Comment by sksamuel** [comment]
I've pinned it so it won't set it stale.
If you have time to do this that's cool @caramelomartins it not I will try to get to it.

**Comment by caramelomartins** [comment]
@sksamuel I'll have some time this week to do this. Thanks!
