### ISSUE TITLE
Allow clues to be added to timeouts

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#2230]
It would be nice if there was a way to also give a clue when a timeout occurs (configured either via `withTimeout()` or the test configuration). A use-case would be tests that call external programs. Such programs might run interactive prompts, blocking the test, which then runs into a timeout. In such cases *stdout* could be shown as a clue, which would help to identify the interactive prompt.

**Comment by sschuberth** [comment]
This has just recently been referred to, so I believe it should stay open.

**Comment by sksamuel** [comment]
It's in the roadmap. I've marked it as pinned.

**Comment by sksamuel** [comment]
How do you see this working?
If I have a test that I set a timeout for 10 seconds and it times out - it will throw a timeout exception so you know why it failed. What extra information would you like in there ?

**Comment by sschuberth** [comment]
> What extra information would you like in there ?

See above (at the example of a CLI program that causes a timeout due to waiting for *stdin*): "In such cases *stdout* could be shown as a clue, which would help to identify the interactive prompt."

**Comment by sksamuel** [comment]
Right, so this is specific to stdin in timeouts.
Kotest would have to capture stdout _in case_ the test times out.

I wonder if another construct makes sense.

withStdOutClue { }

Which captures std out and emits it as a clue if the test fails.

**Comment by sschuberth** [comment]
I wasn't meaning to suggest such a specific change to be done to Kotest. But as some one who writes test with Kotest, I'd like to be able to "manually" pass any clue that I see fit to `withTimeout()`. At the time I filed this issue, I could not see a way to do that (e.g. by nesting `withTimeout()` inside `withClue()`).

**Comment by sksamuel** [comment]
ohhh I see.

Right, that sounds like a really good idea.

**Comment by sksamuel** [comment]
You can now next withTimeout inside a withClue,

```kotlin
  withClue("timey timey") {
     withTimeout(2) {
        delay(1000)
     }
  }
```
