### ISSUE TITLE
Add tolerance matcher to Float, Int and Long

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#2232]
We only have tolerance matcher for Double at the moment.
We could probably use the fact that all numbers extend from `Number`

**Comment by sksamuel** [comment]
Float we should (don't we already?) but int and long can be compared exactly.

**Comment by LeoColman** [comment]
They can.
My specific use-case includes non-deterministic data generation. So, for example, I want to generate property `name` with 90% of chance for it to be `Leo`. When I generate 1.000, I expect that about 900 will be called Leo, but not exactly 900 usually.

So I go
```
myGenerateList.filter { it.name == "Leo" } shouldBe 900 plusOrMinus 10.percent
```

Do you see a way to solve this that is better?

**Comment by sksamuel** [comment]
`myGenerateList.filter { it.name == "Leo" }.size.shouldBeBetween(800, 1000)`

Your 800 and 1000 can be driven by whatever your input is ?

**Comment by sksamuel** [comment]
^^^ Did my suggestion do what you want ?

**Comment by LeoColman** [comment]
It does, yes, although being 800 to 1000 is relatively easy to remember. 
On dynamic tests or tests with not enough precision it might be a little bit weird to write `shouldBeBetween(763, 1237)`.

I do have a real case for this, when working with generators or randomly generated data; although I admit it is not that much of a need 😅

**Comment by sksamuel** [comment]
What about `it.shouldBeWithinPercentageOf(1000, 0.2)`

**Comment by LeoColman** [comment]
I think it's ok!
However, should we use `0.2` to represent 20% or `20.0`? I think I like the latter more. AssertJ does it that way for their `withinPercentage`

**Comment by sksamuel** [comment]
Yes that makes sense 20.0
