### ISSUE TITLE
Compiler plugin to allow for better assertion matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2241]
See https://twitter.com/JavierSegoviaCo/status/1390450131691098115

**Comment by JavierSegoviaCordoba** [comment]
Are there docs about this?

**Comment by sksamuel** [comment]
It hasn't been started yet - as I focused on the compiler plugins for MPP support which I think is more important for 5.0

But now that that is done, and I have some understanding of compiler plugins, this could be tackled soon.
