### ISSUE TITLE
Fail fast for a container test

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2243]
```
context("a context").config(failfast = true) {
  test("test 1") {
  }
  test("test 2") {
    // this test is skipped if test 1 fails
  }
}
```

**Comment by jschneidereit** [comment]
Would be really nice if we can get a descriptive reason too

**Comment by sksamuel** [comment]
failfastIf ?

**Comment by jschneidereit** [comment]
Oh no I just mean if fail fast is set then the reason why the rest of the tests are skipped should be a message that references the name of the failed test

**Comment by sksamuel** [comment]
Ah yeah, good idea. I'll put this on 4.6.

**Comment by ghost** [comment]
@sksamuel thanks for the great work! Is fail-fast working on all types of specs or only some? In particular, wondering about FreeSpec. Thanks!

**Comment by sksamuel** [comment]
Should work on all, if you try a 5.0.0 milestone build.
It will apply to any tests nested within that context.

**Comment by ghost** [comment]
Thanks for the super fast answer @sksamuel !
Not sure, if I'm using it wrong for `FreeSpec` but in M2 milestone `failfast` is not available there (checked for `FunSpec` and its available there :)). Here is a sample code:
```
 import io.kotest.core.spec.style.FreeSpec
 import io.kotest.matchers.string.shouldHaveLength
 
 class Experiment : FreeSpec({
     "Grandparent".config(failfast = true) - {
         "Parent" - {
             "First child" {
                 "s" shouldHaveLength 3
             }
             "Second child" {
                 "s" shouldHaveLength 1
             }
         }
     }
 })
```

**Comment by sksamuel** [comment]
Ah I see.

Freespec doesn't support config on parent tests because the DSL doesn't quite work.
Let me see if I can support that and then add fail fast support.

**Comment by sksamuel** [comment]
This is now in master.

**Comment by sksamuel** [comment]
5.0.0.M3 is out now.

**Comment by ghost** [comment]
Bravo @sksamuel 🎉  Going to test it tomorrow 😄

**Comment by ghost** [comment]
I tried it out unfortunately only weeks after, i'm sorry about that. For the following code, with `failfast = true`, despite that the first child test fails, second child is still running, and the third one. Is it unexpected or expected behaviour @sksamuel ?
Here is the snippet:

```kotlin
 import io.kotest.core.spec.style.FreeSpec
 import io.kotest.matchers.string.shouldHaveLength
 
 class Experiment : FreeSpec({
     "Grandparent".config(failfast = true) - {
         "Parent" - {
             "First child" {
                 "s" shouldHaveLength 3
             }
             "Second child" {
                 "s" shouldHaveLength 1
             }
             "Third child" {
                 "s" shouldHaveLength 2
             }
         }
     }
 })
```
and here are the execution results:
![image](https://user-images.githubusercontent.com/208134/141194296-ab8919e9-5eef-497f-aaf7-5a0c7d572f9a.png)

**Comment by sksamuel** [comment]
Can you confirm the version of kotest ?

**Comment by ghost** [comment]
@sksamuel yeah, it is latest **5.0.0.M3**. I just tried again to be sure: and yes, as described above, the second and third child run despite that first child fails. Expected behaviour is that second and third child don't run if the first child fails. Please correct me if i'm wrong. And thank you very much for checking.

**Comment by sksamuel** [comment]
I think I see the issue. You have two levels here - and you're putting fail fast on the grandparent, not the immediate parent.

So the question is, should fail fast filter down. I guess it should.

**Comment by sksamuel** [comment]
Ok in master now:

![image](https://user-images.githubusercontent.com/743706/141887872-3999cdf9-5a34-4280-8b4b-0fa80f484029.png)

"f" is skipped/ignored because e failed.

![image](https://user-images.githubusercontent.com/743706/141887906-23efc655-5d7c-4854-bc83-e7c0136dc3c5.png)

**Comment by ghost** [comment]
Hello, I'm back :)

Just tested Kotest version **5.0.3** with the following modified FreeSpec test from the [styles](https://kotest.io/docs/framework/testing-styles.html#free-spec) page:

```
 import io.kotest.core.spec.style.FreeSpec
 import io.kotest.matchers.shouldBe
 
 class MyTests : FreeSpec({
     "my upper level test".config(failfast = true) - {
         "my intermediate test" - {
             1 + 1 shouldBe 2
 
             "leaf test" {
                 1 + 1 shouldBe 3 // Here it should fail.
             }
         }
 
         "containers can be nested as deep as you want" - {
             "and so we nest another container" - {
                 "yet another container" - {
                     "finally a real test" {
                         1 + 1 shouldBe 2
                     }
                 }
             }
         }
     }
 })
```

and when I ran it with `failfast = true`, despite the "leaf test" is failing, another test "containers can be nested as deep as you want" still runs:

![image](https://user-images.githubusercontent.com/208134/148660330-9835478b-7cac-4247-8360-af394556b54d.png)

I suppose that the other test should not run after any failure (no matter how deep the failure occurred), or WDYT @sksamuel 

Thanks!

**Comment by sksamuel** [comment]
Created issue to track this https://github.com/kotest/kotest/issues/2773
