### ISSUE TITLE
Uniform way of providing test names for data-driven tests

### ISSUE THREAD

**Issue by apankowski** [kotest/kotest#2247]
### Problem statement

I use data-driven tests quite extensively and I prefer to have nice, human-readable test names whenever possible. With Kotest I often use test case data classes and `forAll` construct described [here](https://kotest.io/docs/framework/data-driven-testing.html). It has two flavors, each having some caveats.

1. `forAll` taking multiple `Pair<String, T>` allows specifying nice test names, but is less compact and requires repeating values from the data class in the test name.

2. `forAll` taking multiple `T`s generates test names automatically using `T.toString()` but only for types that are considered stable. This excludes data classes containing e.g. `List` or `KClass`. Also in some cases it's desirable to process the values in order to have a more concise & readable test names, e.g.: `"persists invoice with ${status::class.simpleName}"`.

I think that a testing framework should allow specifying names of data-driven tests in an easy way. Moreover, in my opinion it's quite beneficial to have the names close to the test case data classes themselves.

### Proposal

We could introduce something like `interface WithTestName { fun testName(): String }` that objects stuffed to `forAll` could implement voluntarily, making Kotest know about desired name of the test case: `io.kotest.core.datatest.Identifiers#stableIdentifier` could first check if the `T` implements `WithTestName` and know the name right away.

We would be able to write data-driven tests with elegant & customizable names, e.g.:

```kotlin
data class SupportedTypeTestCase(val type: KClass<*>, val isSupported: Boolean) : WithTestName {
  override fun testName() = "${if (isSupported) "supports" else "doesn't support"} argument of type ${type.simpleName}"
}

forAll(
  SupportedTypeTestCase(Command::class, true),
  SupportedTypeTestCase(String::class, false),
  SupportedTypeTestCase(Int::class, false),
  SupportedTypeTestCase(Any::class, false),
  SupportedTypeTestCase(ArrayList::class, false),
) { (type, isSupported) ->
  // ...
}
```

### Possible variations
- `val testName: String` instead of `fun`. Personally I prefer the `fun`, probably because it's a nice distinction from data class' `val`s.
- Conventional `fun testName(): String` without the need for the interface. To me this seems like too much magic; also IDE will complain about unused function.

I'm open to any opinions about this idea (including "that's stupid, let's not do this"). I can also prepare a PR implementing this proposal.

**Comment by sksamuel** [comment]
It is a great idea to have better naming.
We have a new datatest module (basically like the old one but with really good nested test support). We can include this there.

I like your idea of an interface. Another option is a typeclass.

```kotlin
with (typeclass) {
  forAll(
    Foo(a, b),
    Foo(c, d),
    ) { a,b ->
   }
}
```

**Comment by sksamuel** [comment]
@ashishkujoy In addition to the PR you added yesterday for this, what about this as well:

```kotlin
withDataTestName({ data -> "SecurityLevel $data should be reflexive"}) {
   withData(levels) { level ->
   }
}
```

So a function which is passed the current value in order to generate the test name.

**Comment by ashishkujoy** [comment]
> @ashishkujoy In addition to the PR you added yesterday for this, what about this as well:
> 
> ```kotlin
> withDataTestName({ data -> "SecurityLevel $data should be reflexive"}) {
>    withData(levels) { level ->
>    }
> }
> ```
> 
> So a function which is passed the current value in order to generate the test name.

This also looks a nice idea, this way user won't need to annotated or extend anything just for getting some test name changes.
