### ISSUE TITLE
Support matching elements in arrays ignoring fields

### ISSUE THREAD

**Issue by pelletier197** [kotest/kotest#2249]
Hello Kotest developers!

I was wondering if you were planning on developing a feature for assertions to match list elements by ignoring fields. Here is a sample of that kind of assertings with `assertJ`

```kotlin
assertThat(underTest.findAll())
    .usingElementComparatorIgnoringFields(ConfiguredTask::id.name)
    .containsExactlyInAnyOrderElementsOf(expectedTasks)
```

Maybe something similar could be implemented in Kotest? 

Thank you!

**Comment by sksamuel** [comment]
So it compares the list from underTest with the expected list, only using the id.name field ?

**Comment by pelletier197** [comment]
You can actually do both. Include only fields or exclude fields. The example I shown would compare all fields except the field "Id"

**Comment by sksamuel** [comment]
We have similar matchers for object equality already, so I think this would be a good addition.

**Comment by pareekdevanshu** [comment]
Hi,
 what is the update on this request?

**Comment by pelletier197** [comment]
The issue was closed for inactivity I think, but it was never implemented. Should we re-open it?

**Comment by sksamuel** [comment]
I'm not quite sure of the use case. Do you have example syntax you'd like to see

**Comment by pelletier197** [comment]
I have an idea of how it could work. Right now, Kotest has a few matchers with long names. So to follow library naming, the function should be something like 
```kotlin
fun <T, C : Collection<T>> C?.shouldContainExactlyInAnyOrderIgnoringFields(expected: C, ignorePrivateFields: Boolean,    property: KProperty<*>, vararg others: KProperty<*>)
````

That said this becomes really hard to read, and you need to provide overloads for the different configurations (one without `ignorePrivateFiels` for instance. 

What could be great is to pass an optional object `comparor`. The default comparator would simply do an object equality, which is the current behaviour (using `==`). 

Something like this:

 ```kotlin
fun <T, C : Collection<T>> C?.shouldContainExactlyInAnyOrder(expected: C, comparator: ObjectComparator = ObjectComparator.equality()) 
```

You could therefore, if you want to verify the same thing ignoring fields, do something like this:
```kotlin
actual.shouldContainExactlyInAnyOrder(expected, comparator = ObjectComparator.ignoringFields(ConfiguredTask::id))
// All other equality configuration could be done in chain, making this easy to configure and super readable.
// Example: ObjectComparator.ignoringFields(ConfiguredTask::id, ConfiguredTask::name).ignoringPrivateFields(true)
``` 

I understand this is a rather complex concept to implement, and that it should probably not be part of a single merge request to implement this feature, but this is the best way I personally see this could be implemented. 

Also, this approach could maybe help reduce the number of functions in the library and allow for more powerful matching. 

Let me know what you think about the idea :smiley:

**Comment by sksamuel** [comment]
I think this is an excellent idea.
And we can provide a few comparators out of the box.

**Comment by pelletier197** [comment]
Yes! And it would even be easy for users of the library to implement their own.

**Comment by sksamuel** [comment]
Do you want to craft a pr? No rush on it.

**Comment by pelletier197** [comment]
Yes, I could do that when I get some free time!

**Comment by andrewliles** [comment]
In Kotest version 5.6.0, this feature has been implemented:

```
collection.shouldContainAllIgnoringFields(other, fields...)
```

In this PR: https://github.com/kotest/kotest/pull/3394
