### ISSUE TITLE
Enable the Kotlin JS IR backend

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#2251]
Hello,
My project https://github.com/jmfayard/kotlin-cli-starter depends on both ktor-client and CliKt
- ktor-client is only available with the IR backend for JavaScript
- CliKt is only available with the legacy backend

CliKt can't use the IR backend because it depends on kotest who is only available with the legacy backend.

https://github.com/ajalt/clikt/pull/291

So I'm stuck

**Please describe the feature you'd like to see including any solutions in mind if you have any**

```properties
# gradle.properties
# Enable consumers to use IR JS backend https://kotlinlang.org/docs/js-ir-compiler.html
kotlin.js.compiler=both
```

**Comment by sksamuel** [comment]
Kotest is IR enabled already unless I've missed it somewhere ?

**Comment by LouisCAD** [comment]
JS IR is not the default yet, unlike JVM IR in Kotlin 1.5. For libraries, it's currently best to publish in "both" mode.

**Comment by sksamuel** [comment]
I thought that's what adding js(BOTH) did. Should two different artifacts be published ?

**Comment by sksamuel** [comment]
Looks like clikt is on 4.3.1 which is 6 months old. We switched over to IR both in 4.4.x if I remember correctly (assuming adding js(BOTH) is sufficient to able it, as I thought it was).

**Comment by jmfayard** [comment]
I can confirm that upgrading to 4.5.0 fixed the issuee, thanks Samuel!
