### ISSUE TITLE
For the kotest-assertions-kotlinx-time module, version 4.5.0 has not been published 

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#2254]
https://search.maven.org/artifact/io.kotest/kotest-assertions-kotlinx-time

**Comment by ashishkujoy** [comment]
This is now a separate module and now getting release under separate release cycle. 
https://github.com/kotest/kotest-assertions-kotlinx-datetime
Please check 4.5.0 changelog :  https://kotest.io/docs/changelog.html#450-may-2021

Current latest version: https://search.maven.org/search?q=kotest-assertions-kotlinx-datetime
