### ISSUE TITLE
Downloaded version is incompatible with the current IDE

### ISSUE THREAD

**Issue by paulohms** [kotest/kotest#2256]
Plugin "Kotest" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'Kotest' (version '1.1.36-IC-2020.1') is not compatible with the current version of the IDE, because it requires build 201.* or older but the current build is IU-211.7142.45

**Comment by sksamuel** [comment]
Does this help https://github.com/kotest/kotest/issues/5445

**Comment by sksamuel** [comment]
Did you get this fixed @paulohms
