### ISSUE TITLE
Make Kotest Configuration dump to output configurable in JUnit platform

### ISSUE THREAD

**Issue by nlochschmidt** [kotest/kotest#2266]
I rarely need to look at the configuration of Kotest but it is quite big and always dumped when using the JUnit5 runner. 

It would be nice if this could be configurable or maybe in the case of Gradle even automatic based on whether `--info` flag is set or not. Not sure if that is possible.

I guess this is the starting point to investigate:

https://github.com/kotest/kotest/blob/767eb57fd7332abd3c44ab1c6943009f11a95379/kotest-runner/kotest-runner-junit5/src/jvmMain/kotlin/io/kotest/runner/junit/platform/KotestJunitPlatformTestEngine.kt#L77-L79

**Comment by sksamuel** [comment]
`--info` is a good idea but I'm not sure if that's passed into the runner.
It could certainly be optional. Perhaps in 5.0 we default to off.
