### ISSUE TITLE
Deprecated beforeTest

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2268]
From slack:

What are your thoughts on consolidating `beforeTest` / `beforeAny` in the major version?
What was there before:
`beforeTest`: runs before any leaf test or container
What was added in 4.2:
`beforeEach`: runs before any leaf test
`beforeContainer`: runs before any container
`beforeAny`: runs before any leaf test or contaner, same as `beforeTest`
The name `beforeEach` was chosen because it's standard naming for it in many other testing frameworks and because `beforeTest` was taken, but it is a bit confusing that both still exist.

https://kotlinlang.slack.com/archives/CSYLDDZUY/p1621511960000800?thread_ts=1621439178.000700&cid=CSYLDDZUY

**Comment by ashishkujoy** [comment]
Yes, I think we should be good to deprecate `beforeTest`.  Since `beforeEach`, `beforeContainer` and `beforeAny` gives much better control to user.

**Comment by sksamuel** [comment]
deprecated in 5.0
