### ISSUE TITLE
@DoNotParallelize not working when used in composed annotation 

### ISSUE THREAD

**Issue by nlochschmidt** [kotest/kotest#2269]
**Which version of Kotest are you using**
4.6.0

This is from a Kotest+Spring use-case but the issue is more general I think. 

Given a composed annotation such as

```kotlin
@DoNotParallelize
@Tag(Slow, Spring)
@MockBeans(classes = [MyService::class])
annotation class MySpringKotest
```

I would expect two specs annotated with `@MySpringKotest` to be run sequentially. Instead they run in parallel.

> Btw, it's important to run Spring tests that use `@MockBeans` sequentially, because otherwise the configuration of mocks inside the tests are quick to cause race conditions 😞

**Comment by sksamuel** [comment]
When you say composed, you mean multiple annotations on a test class ?

**Comment by nlochschmidt** [comment]
No I mean an inherited annotation that combines other annotations:

```kotlin
​@DoNotParallelize
@Tags(​Slow​, ​Spring​)
@MockBeans(classes ​=​ [​MyService​::​class​])
​annotation​ ​class​ ​MySpringKotest //composed annotation

// annotating the test class
@MySpringKotest
class MySpec : FunSpec({...})
```

**Comment by sksamuel** [comment]
Oh yes I see now. Does kotlin support that. I'll check it out.

**Comment by nlochschmidt** [comment]
Nice! Thanks a lot!

**Comment by sksamuel** [comment]
I'll include this in 4.6.1 as well as 5.0

**Comment by nlochschmidt** [comment]
Do you happen to have an ETA for `4.6.1`?

**Comment by sksamuel** [comment]
4.6.1 has been released.
