### ISSUE TITLE
Use refreshVersions?

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#2275]
Hello, I'm the author of refreshVersions, a Gradle plugin whose mission is to make adding and updating dependencies faster, more convenient and less error-prone

See https://jmfayard.github.io/refreshVersions/

I'm currently working on improving how we migrate existing projects.
Would you be interested in having a pull request adding refreshVersions to kotest?

**Comment by sksamuel** [comment]
What does it involve on the kotest side ?

**Comment by jmfayard** [comment]
Nothing will change in the project, the same dependencies versions will be used.

But when you will decide to update your dependencies it will be easier
https://jmfayard.github.io/refreshVersions/update-dependencies/

**Comment by sksamuel** [comment]
Ok lets try it out.

**Comment by sksamuel** [comment]
This is great!
