### ISSUE TITLE
ScriptSpec should not appear in output.

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2288]
**Which version of Kotest are you using**

**Comment by rezammalik** [comment]
I was using 4.4.3. I tried moving up to 4.6.0 but noticed the spec issue in that as well. Another point not related to this but worth mentioning is the kotest-allure extension page lists this `io.kotest.extensions:kotest-extensions-allure:${kotest.version}` which isn't available for kotest version 4.6.0.

**Comment by sksamuel** [comment]
Duplicate of https://github.com/kotest/kotest/issues/2308
