### ISSUE TITLE
Deprecate Arb.nats

### ISSUE THREAD

**Issue by BartvHelvert** [kotest/kotest#2292]
Currently `Arb.nats` does the same thing as `Arb.positiveInts` which can lead to confusion.
There is also no generally accepted definition of the natural numbers. In some definitions 0 is included and in others it isn't.

**Comment by LeoColman** [comment]
Not skipping the importance of this discussion, I believe that 0 is always considered a natural number.
https://en.wikipedia.org/wiki/Natural_number

So there's this difference between `positiveInts` and `nats`

**Comment by sksamuel** [comment]
I do think that `nats` is not 100% clear, whereas `positiveInts` is totally clear.
I'd be in favour of deprecating nats in favour of positive ints.

**Comment by BartvHelvert** [comment]
> Not skipping the importance of this discussion, I believe that 0 is always considered a natural number.
> https://en.wikipedia.org/wiki/Natural_number
> 
> So there's this difference between `positiveInts` and `nats`

From that wikipedia page: "Some definitions, including the standard ISO 80000-2, begin the natural numbers with 0, corresponding to the non-negative integers 0, 1, 2, 3, ..., whereas others start with 1, corresponding to the positive integers 1, 2, 3, ...".

Maybe we can introduce `Ab.nonPositiveInts` and `Arb.nonNegativeInts` to cover the cases where 0 is included.

**Comment by LeoColman** [comment]
@Bartvhelvert 
I stand corrected.
I thought that removing 0 always required you to explicitly say that. You're right, it's ambiguous
