### ISSUE TITLE
Allow withData to specify leaf mode

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2296]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by dave08** [comment]
For me, I think it's fine the way it is... I use `it` inside `withData`... but for those that use `withData` as the test container itself, how could you distinguish between the containing `withData` when nesting them?

**Comment by sksamuel** [comment]
thinking out loud that `withData(data, leaf = true)` would not allow nested tests.
