### ISSUE TITLE
Improve Arb naming consistency

### ISSUE THREAD

**Issue by BartvHelvert** [kotest/kotest#2297]
Currently the naming scheme for Arb utility methods is inconsistent, e.g. `Arb.int` (singular) vs `Arb.positiveInts` (plural).
I suggest using singular form for all methods. The following changes can be changed without deprecation warning:

- `Arb.positiveBytes` -> `Arb.positiveByte`
- `Arb.negativeBytes` -> `Arb.negativeByte`
- `Arb.positiveShorts` -> `Arb.positiveShort`
- `Arb.negativeShorts` -> `Arb.negativeShort`
- `Arb.nonNegativeInts` -> `Arb.nonNegativeInt`
- `Arb.nonPositiveInts` -> `Arb.nonPositiveInt`

The following methods can be changed but there should be a deprecation warning:
- `Arb.positiveInts` -> `Arb.positiveInt`
- `Arb.negativeInts` -> `Arb.negativeInt`
- `Arb.multiples` -> `Arb.multiple`
- `Arb.factors` -> `Arb.factor`
- `Arb.positiveDoubles` -> `Arb.positiveDouble`
- `Arb.negativeDoubles` -> `Arb.negativeDouble`
- `Arb.numericDoubles` -> `Arb.numericDouble`
- `Arb.numericFloats` -> `Arb.numericFloat` 
- `Arb.byteArrays` -> `Arb.byteArray`

**Comment by sksamuel** [comment]
Agreed.
