### ISSUE TITLE
Exception trapping does not work

### ISSUE THREAD

**Issue by russel** [kotest/kotest#23]
``` kotlin
shouldThrow<StackOverflowError> { … }
```

and

``` kotlin
expecting(StackOverflowError::class){ … }
```

appear not to catch `StackOverflowError` it propagates out to the runner.

cf. the KotlinTest test in https://github.com/russel/Factorial/tree/master/Kotlin

**Comment by sksamuel** [comment]
This was just fixed actually earlier today. All not-Exception throwables
have this issue. Be in release 1.2.0 which will be Tuesday.

**Comment by russel** [comment]
Sponditious. I assume the release will be to JCenter and Maven Central.

**Comment by sksamuel** [comment]
Yep

**Comment by russel** [comment]
That's great. In which case I wil be using KotlinTest in my /dev/summer 2016 (http://devcycles.net/2016/summer/sessions/index.php?session=5) session on Kotlin and Ceylon.

**Comment by sksamuel** [comment]
Awesome.
