### ISSUE TITLE
MPP/JS: withData nameFn return value must not end with ".json"

### ISSUE THREAD

**Issue by JesusMcCloud** [kotest/kotest#2302]
Kotest 4.6.0 MPP/JS

I have a test case in commonTest and everything works nicely, except the test name on JS.
my _withData_ input is a map, whose key is the filename of the JSON-encoded test input.
The issue is with the map's keys ending in ".json":
![image](https://user-images.githubusercontent.com/5648377/120072241-1e89b980-c093-11eb-8aae-8f9859379289.png)

I have worked around this issue by replacing ".json" with "·json", which results in correct displaying of the test-input's name:
![image](https://user-images.githubusercontent.com/5648377/120072204-e5e9e000-c092-11eb-8860-a601380e0825.png)

When inspecting the generated HTML test report, it seems as though a space is inserted right before ".json".
It works perfectly fine for the JVM target though…

**Comment by sksamuel** [comment]
Ok, so the reason this happens is intellij considers a dot to be a package name separator.
So foo.json is test class foo with method name json (it's very class / method centric).
I will see if we can escape it.

**Comment by sksamuel** [comment]
https://www.jetbrains.com/help/teamcity/service-messages.html#Interpreting+test+names

Looks like its not possible.
I guess we could replace a period with another unicode character.

**Comment by sksamuel** [comment]
Gone with replacing dot with space.
This is better than having just the suffix after the dot appearing.
