### ISSUE TITLE
Improve Arb naming

### ISSUE THREAD

**Issue by BartvHelvert** [kotest/kotest#2305]
I want to propose 2 naming changes:

1.  `Arb.bool` -> `Arb.boolean`, `Arb.boolArray` -> `Arb.booleanArray`.
This makes more sense because it matched the Kotlin standard library naming convention. Requires deprecation of `Arb.bool`.

2. `Arb.uint` -> `Arb.uInt` (and similar for all other unsigned types)
Current naming scheme doesn't follow proper lower camelcase convention which is almost always used in Kotlin. Requires deprecation of `Arb.ushort`.

**Comment by sksamuel** [comment]
1. Yes makes sense
2. Do you have an example in the kotlin std lib where they use this style ?

**Comment by BartvHelvert** [comment]
> 2. Do you have an example in the kotlin std lib where they use this style ?

It would make more sense to write it as `uInt` because it stands for "Unsigned Int" which is 2 separate words. The class name itself also capitalizes the I (`kotlin.UInt`), similarly there are functions like `Int#toUInt` in the standard library.

**Comment by sksamuel** [comment]
Ok thanks :)
