### ISSUE TITLE
Non-suspend version of shouldCompleteWithin should return the result of the function block

### ISSUE THREAD

**Issue by IgorTs2004** [kotest/kotest#2307]
Currently the **non-suspend** version of shouldCompleteWithin do not return the result of computation which can be further asserted like this:
```
val result = shouldCompleteWithin(1000, TimeUnit.MILLISECONDS) {
  computeSomeValue()
}

result shouldBe "some value"
```

P.S. I have a PR with the fix of this issue. Shall I publish it?

**Comment by sksamuel** [comment]
Please do.

**Comment by IgorTs2004** [comment]
Done.

**Comment by IgorTs2004** [comment]
@sksamuel 
Could you take a look into the PR? (it's small and easy to review)

**Comment by sksamuel** [comment]
Sorry for delay in reviewing.  Merged now.
