### ISSUE TITLE
Getting unexpected `io.kotest.core.script.ScriptSpec` in the test results when running tests from AS

### ISSUE THREAD

**Issue by yaroslav-shlapak** [kotest/kotest#2308]
Kotest version: 4.4.2

This issue might be related to https://github.com/kotest/kotest/issues/1912

### Given
1. An Android project with the next structure of modules:
  +-`primary`
  +-`secondary`
2. The `secondary` module has Kotest configured like this (gradle.kts with correct kotest dependencies, here as constants):
  ```
  android {
      tasks.withType<Test>().all {
          useJUnitPlatform()
      }
  }
  ...
  testImplementation(kotestJunit5Runner)
  testImplementation(kotestAssertions)
  testImplementation(kotestProperty)
  testRuntimeOnly(junitVintage)
  ``` 
3. the `primary` module has the `secondary` module added as a dependency like this (gradle.kts):
   `implementation(project(secondary))`
4. The `primary` gradle.kts file contains this line to workaround the issue from https://github.com/kotest/kotest/issues/1912
`testRuntimeOnly(junitVintage)`
### When 
running tests using Android Studio via right-click on the `primary` module package with tests -> select **Run 'Tests in 'primary''**
## Then
The tests are built and passed but results contains unopenable `io.kotest.core.script.ScriptSpec`
<img width="505" alt="Screenshot 2021-06-02 at 13 01 27-pixelized" src="https://user-images.githubusercontent.com/3373419/120466469-c8c15400-c3a7-11eb-82b1-0d253444c05a.png">

## Expected result
The results must contain only the tests from the module
### Additional info
If running tests using Gradle it works without issues

**Comment by sksamuel** [comment]
This is fixed in master for 5.0 release.
