### ISSUE TITLE
Add class name to test results for Behavior spec

### ISSUE THREAD

**Issue by dragneelfps** [kotest/kotest#2314]
I would prefer if I can see the class name before Given clause.
(note: This might be applicable to other specs as well)

![image](https://user-images.githubusercontent.com/23515791/120913435-d2530080-c6b4-11eb-94e4-57703867871d.png)

Also, the file name in the generated folder for the test result is the same as given clause.
It would be better all the given clauses written in same file are under a single folder with the name of the class

**Comment by sksamuel** [comment]
I've been trying to do this and I can't get the class name to display. JUnit only allows for a "descriptor" and putting the class name in plays havoc, so I will have to close this as unsupportable.
