### ISSUE TITLE
Replace Generex with RgxGen

### ISSUE THREAD

**Issue by toddobryan** [kotest/kotest#2323]
Generex https://github.com/mifmif/Generex seems to be moribund. The last commit was over 4 years ago. It has problems--for example, it treats `^` and `$` as literals, so it thinks `"^abc$"` is a string that matches the pattern `^[a-z]{3}$`. (It's not.)

RgxGen https://github.com/curious-odd-man/RgxGen seems to be still under development, handles `^` and `$` and character classes like `\w`, `\S`, and other things, and claims to be faster than Generex and Xeger.

RgxGen can also generate non-examples, if that's ever useful.

**Comment by sksamuel** [comment]
I like. We should do this.

**Comment by sksamuel** [comment]
Now merged in master.
