### ISSUE TITLE
Do not report specs which have no matching tests

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2324]
Eg, when using a tag, we should not include the classname if all the tests were filtered out.

**Comment by sksamuel** [comment]
Maybe show the spec as ignored rather than completey missing ?

**Comment by rezammalik** [comment]
If there are like 40 test specs then having each one listed as ignored may be too much? Maybe a total of specs ignored instead of listing them out? My main concern was having the actual run output etc getting lost in the middle of all the specs listed as not run currently.

**Comment by sksamuel** [comment]
This is done in master.
