### ISSUE TITLE
shouldMatchJson doesn't work with a JSON containing array

### ISSUE THREAD

**Issue by kkarmakul** [kotest/kotest#2325]
Kotest version - 4.6.0
From documentation: 
> This matcher will consider two json strings matched if they have the same key-values pairs, regardless of order.

I attach output from my test. Data is the same, order is different.
[shouldMatchJson.output.log](https://github.com/kotest/kotest/files/6669904/shouldMatchJson.output.log)

**Comment by ashishkujoy** [comment]
@kkarmakul In your case value of `uxs` is an array(not a key-value pair object/map) and order of element in that array is different. So as far as my understanding assertion failure is correct.

**Comment by kkarmakul** [comment]
The API and the docs doesn't give a hint about how to use the lib with arrays. So from client side it simply "doesn't work". I switched to Lukáš Křečan's [JsonUnit](https://github.com/lukas-krecan/JsonUnit)
