### ISSUE TITLE
Specify SDK and Application in Robolectric extension

### ISSUE THREAD

**Issue by matsudamper** [kotest/kotest#2328]
Is there a way to specify these for each test?

I use this one.
https://github.com/kotest/kotest-extensions-robolectric/pull/1

**Comment by LeoColman** [comment]
There isn't a way currently, no.

Thanks for the PR! I'll review it ASAP.

**Comment by matsudamper** [comment]
Thanks to the plugin method, I currently have no trouble using it myself.

**Comment by LeoColman** [comment]
Implemented by https://github.com/kotest/kotest-extensions-robolectric/pull/1.
