### ISSUE TITLE
Grouping test with Tags is not working

### ISSUE THREAD

**Issue by Poorva17** [kotest/kotest#2337]
**Version**
Kotest : 4.1.3

**Steps to reproduce:** 
1. Write test with appropriate tag
```kotlin
import io.kotest.core.annotation.Tags
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

@Tags("Foo")
class FooTest : StringSpec() {
    init {
        "should run foo test" {
            1 shouldBe 1
        }
    }
}
```
2. run test `./gradlew test -Dkotest.tags.include="Foo"` 
(I tried `./gradlew test -Dkotest.tags="Foo"` as well. This also runs entire test suit.) 

**Expected outcome**
Test having tag `Foo` should run. Other tests should be excluded.

**Actual outcome**
All tests run. 

**Note:** I also checked in system properties. `kotest.tags.include` is getting set in `system.properties`

Am I missing anything?

**Comment by ashishkujoy** [comment]
Hi @Poorva17 please refer to this [doc](https://kotest.io/docs/framework/tags.html#gradle) for gradle test tasks configuration for passing system properties to tests.

**Comment by Poorva17** [comment]
@ashishkujoy Thanks for quick response. I am referring this document only. As mentioned in doc, I verified that in test task I am getting system properties set as expected. Despite of this, entire test suit is running in my case.

**Comment by ashishkujoy** [comment]
@Poorva17 just check looks like there was some bug in 4.1.3, can u try upgrading kotest version, I tried with 4.2.2 and latest 4.6.0 its working fine. So the issue seems to be resolve in 4.2.2

**Comment by ashishkujoy** [comment]
@Poorva17 does upgrading Kotest worked for you?
