### ISSUE TITLE
docs: typo on `Eventually` section

### ISSUE THREAD

**Issue by gszzzzzz** [kotest/kotest#2338]
https://kotest.io/docs/framework/concurrency/eventually.html

The header says:

Starting with Kotest 4.6, a new experimental module has been added which contains improved utilities for testing concurrent, asynchronous, or non-deterministic code. This module is kotest-framework-concurrency and is intended as a long term **_replaement_** for the previous module. The previous utilities are still available as part of the core framework.

It should be **_replacement_**.

**Comment by sksamuel** [comment]
Thanks, fixed.
