### ISSUE TITLE
use of whenReady 

### ISSUE THREAD

**Issue by huyngo-dd** [kotest/kotest#2341]
**Which version of Kotest are you using**: 4.6.0

Hi there,

I am trying to leverage `whenReady` to test futures, which has been documented in https://github.com/kotest/kotest/blob/master/doc/reference.md, but I can't seem to find the proper package to bring in. I'm not sure if the method has just been discontinued or I just can't find the right one to import.

I've got the following dependencies brought in:
testImplementation "io.kotest:kotest-runner-junit5-jvm:4.6.0"
testImplementation "io.kotest:kotest-assertions-core-jvm:4.6.0"
testImplementation "io.kotest:kotest-property-jvm:4.6.0"

Thanks in advance and sorry if it is really obvious.

**Comment by ashishkujoy** [comment]
It's no longer present in Kotest codebase. Is it being rename or removed from kotest?
@sksamuel

**Comment by sksamuel** [comment]
kotlin provides the same thing now.
https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-jdk8

Add that module to your build and then you can call .await() on your future, and it will suspend.
