### ISSUE TITLE
HTMLReporter - css not loading (`href` of the file is absolute, not relative)

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#2342]
**Which version of Kotest are you using** `4.6.0`

I'm using macOS, IntelliJ, Gradle 7.1.1, java 11.

### Report

When I enable the HtmlReporter...

```kotlin
class KotestConfig : AbstractProjectConfig() {
  override fun listeners(): List<Listener> = listOf(
    JunitXmlReporter(
      includeContainers = false,
      useTestPathAsName = true,
    ),
    HtmlReporter()
  )
}
```

And in `build.gradle.kts`

```kotlin
tasks.test {
  useJUnitPlatform()
  testLogging {
    events("passed", "skipped", "failed")
  }
  reports {
    html.required.set(false)
    junitXml.required.set(true)
  }
  systemProperty("gradle.build.dir", project.buildDir)
}
```

When I run `gradle build`, a report is generated in `build/reports/tests/test/index.html`, but the CSS doesn't load.

![image](https://user-images.githubusercontent.com/897017/124921820-19f0e300-dff9-11eb-869b-69b178ea2236.png)

### investigation

I think this is because it's using an absolute path.

https://github.com/kotest/kotest/blob/ab98db108a5ae31d88c8835195e1b2960f5afd42/kotest-extensions/kotest-extensions-htmlreporter/src/jvmMain/kotlin/io.kotest.extensions.htmlreporter/HtmlReporter.kt#L75

https://github.com/kotest/kotest/blob/ab98db108a5ae31d88c8835195e1b2960f5afd42/kotest-extensions/kotest-extensions-htmlreporter/src/jvmMain/kotlin/io.kotest.extensions.htmlreporter/HtmlReporter.kt#L81

This results in the following HTML

```html
  <head>
    <link rel="stylesheet" href="/Users/adam/projects/adam/myproject/build/reports/tests/test/css/style.css" />
  </head>
```

### suggested fix

If I manually edit the HTML to use a relative path, the CSS loads.

```html 
  <head>
    <link rel="stylesheet" href="./css/style.css" />
  </head>
```

![image](https://user-images.githubusercontent.com/897017/124921896-342ac100-dff9-11eb-9e04-93e3a90dbe1e.png)

**Comment by sksamuel** [comment]
Fixed in master, will be in 4.6.1
