### ISSUE TITLE
`tempdir` is not documented

### ISSUE THREAD

**Issue by Marcono1234** [kotest/kotest#2350]
**Which version of Kotest are you using**
Commit 3881baffab4b62d75dcf400674c5b6a196af4aa3

**Description**
The `tempdir` function is not documented, this was raised in https://github.com/kotest/kotest/pull/1867#issuecomment-734385797, but apparently not addressed yet.

For reference, `tempfile` is mentioned both in [`doc/reference.md`](https://github.com/kotest/kotest/blob/master/doc/reference.md#temporary-file) and its own documentation file [`documentation/docs/framework/tempfile.md`](https://github.com/kotest/kotest/blob/master/documentation/docs/framework/tempfile.md).

**Comment by sksamuel** [comment]
Updated, thanks.

https://kotest.io/docs/framework/temporary-files/

**Comment by Marcono1234** [comment]
Thanks! Should `reference.md` mention it as well, or is this not worth it?

**Comment by sksamuel** [comment]
Reference. Md is deprecated and slowly being replaced with the micro site
