### ISSUE TITLE
Move "Contributing" documentation from wiki to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Marcono1234** [kotest/kotest#2352]
**Please describe the feature you'd like to see including any solutions in mind if you have any**
Currently the [wiki](https://github.com/kotest/kotest/wiki/contribute) describes how to contribute to this project.
It might be better to instead use a `CONTRIBUTING.md` file for this. This way GitHub notices this file and shows it when creating issues and pull requests, see also [GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).

**Comment by sksamuel** [comment]
Thank you for the suggestion, I've created CONTRIBUTING.md

**Comment by Marcono1234** [comment]
Thanks! Should the README "Contribute" link be updated to point to that file?
(And should the wiki page be removed then?)

**Comment by sksamuel** [comment]
Yeah good call on both.
