### ISSUE TITLE
Publish Maven relocation artifacts

### ISSUE THREAD

**Issue by Marcono1234** [kotest/kotest#2354]
**Please describe the feature you'd like to see including any solutions in mind if you have any**
The `groupId` of this project and its subprojects have changed in the past (from `io.kotlintest` to `io.kotest`, and recently for extensions to `io.kotest.extensions`). Additionally for a few extension projects the `artifactId` seems to have changed as well, e.g. `kotest-plugins-pitest`.

Maven has a, probably not well known, feature called [relocation](https://maven.apache.org/guides/mini/guide-relocation.html). This allows you to publish a relocation artifact as "new" version for the old groupId, which points the user and build tools to the new coordinates. An example for this is [`ant:ant`](https://mvnrepository.com/artifact/ant/ant).
Such relocation information makes it easier for the user to understand why there are appear to be no new releases.

If I understand it correctly the normal process is:
1. You change the coordinates of the project, e.g. `groupId` or `artifactId`, and at the same time add information to your build tool configuration (Maven or Gradle) for publishing a relocation artifact pointing from the old coordinates to the new ones
2. You publish the new artifacts and the relocation artifacts
3. You remove the relocation information from your build tool configuration again (because publishing a relocation artifact once suffices)

A demo project showcasing this can be found at https://github.com/Marcono1234/gradle-relocation-test (have a look at the commits and the published Maven artifacts on the right).

Even though the relocation has already happened for Kotest, you can probably still retroactively publish the relocation artifacts.
If you have any questions or want feedback, I am happy to help.

**Comment by sksamuel** [comment]
Does this still work if the versions have changed as well ?
so io.kotest.foo:kotest-foo becomes io.kotest.foo2:kotest-foo2 but with new version, is that supported?
And what about if the version is earlier than the previous one (as in our case).

**Comment by Marcono1234** [comment]
Yes version changes are possible as well, the version can also be "lower", like it is the case for the extension projects here whose version numbering started at 1.0.0 again.
For example, I used the following test configuration:
```kotlin
publishing {
    publications {
        create<MavenPublication>("relocation") {
            pom {
                // Old artifact coordinates
                groupId = "com.example"
                artifactId = "lib"
                version = "1.5.0"

                distributionManagement {
                    relocation {
                        groupId.set("com.google.code.gson")
                        artifactId.set("gson")
                        version.set("1.1")
                        message.set("some message")
                    }
                }
            }
        }
    }
}
```

You can also test this locally by running `gradlew publishToMavenLocal` and then creating demo projects depending on the relocation artifact (here `com.example:lib:1.5.0`).

**Comment by Marcono1234** [comment]
I am not completely sure what the best practices are (or if there even exist best practices), but I think for your case it would make sense to continue numbering for the old artifact and then point to the new artifact corresponding to that version (instead of pointing to the latest version) to make it easier for users to first switch to the corresponding renamed artifact and then upgrade that. For example:
<code>io.kotlintest:kotlintest-assertions:<b>4.0.0</b></code> → `io.kotest:kotest-assertions-core-jvm:4.0.0`
(not sure if this is the correct upgrade path)

Though, the changes to the project structure here in the past are rather complex, so maybe relocation artifacts do not make sense for some of the subprojects, e.g. when a project has been split into multiple separate ones.

Feel free to ask others for additional feedback though to make sure the relocation artifacts are as useful as possible.
