### ISSUE TITLE
Incompatibility with kotlinx.serialization

### ISSUE THREAD

**Issue by benkuly** [kotest/kotest#2364]
**Which version of Kotest are you using**
4.6.1

**Bug**
I'm getting the following error, when I want to build my project:
```
Module not found: Error: Can't resolve 'kotlinx-serialization-kotlinx-serialization-core-jsLegacy' in './build/js/node_modules/kotest-kotest-assertions-json-js-legacy'
Module not found: Error: Can't resolve 'kotlinx-serialization-kotlinx-serialization-json-jsLegacy' in './build/js/node_modules/kotest-kotest-assertions-json-js-legacy'
  Error: Cannot find module 'kotlinx-serialization-kotlinx-serialization-json-jsLegacy'
```

~~It seems that ktor below 1.6.0 is not compatible with the current kotilnx.serialization version: https://youtrack.jetbrains.com/issue/KT-43237
So upgrading ktor within kotest should fix it.~~

**Comment by sksamuel** [comment]
Are you using the latest release from the https://github.com/kotest/kotest-assertions-ktor project ?

**Comment by benkuly** [comment]
I just saw, that I don't use `kotest-assertions-ktor ` at all.

**Comment by sksamuel** [comment]
Ok so its not ktor its the json stuff. We can bump that.

**Comment by sksamuel** [comment]
Is this using the json matchers ?

**Comment by benkuly** [comment]
> Is this using the json matchers ?

It think so, but I cannot reproduce it at the moment, because I disbaled JS due to a bug of kotlinx.serialization

**Comment by sksamuel** [comment]
I have bumped the versions of kotlinx.serialization to the latest 1.3 for our 5.0 release.
If you still have issues please reopen.
