### ISSUE TITLE
WARN: Duplicated test name io.kotest.data.Row1... ???

### ISSUE THREAD

**Issue by coachroebuck** [kotest/kotest#2366]
I'm currently working with this version of kotest: 
```
testImplementation "io.kotest:kotest-runner-junit5:4.6.0"
```

and am trying to eliminate this warning that appears when I execute my unit tests:
```
WARN: Duplicated test name io.kotest.data.Row1. To disable this message, set DuplicateTestNameMode to None.
```

I decided to create this very simple unit tests. Perhaps my own tests were written incorrectly:
```
internal class SimpleTestTest : BehaviorSpec() {
init {
        given("Some Component") {
            `when`("someMethod()") {
                and("some input") {
                    forAll(
                        row(1),
                        row(2),
                        row(3),
                        row(4),
                        row(5)
                    ) { input ->

                    }
                }
            }
        }
   }
}
```
That ☝️ still produces those warnings.

What is going on here?

**Comment by sksamuel** [comment]
I'm not sure of the issue ( can dig deeper if required ) but I would look at the newer data test support in 4.6 that will become the preferred choice in 5.0

https://kotest.io/docs/framework/datatesting/data-driven-testing.html

**Comment by coachroebuck** [comment]
This time, I followed the data driven testing, as provided in the link you have provided, and recorded my progress.

[If you are able to access this video](https://drive.google.com/file/d/1R5h-ZlP6ujpDJ7aMXNqbB6QdThdpZUEx/view?usp=sharing)

The latest version of Android Studio (provided in the video) apparently is unable to identify that unit test, which is a shame given the large number of unit tests I have written up to this point in the manner described in that page.

Interestingly, this type of unit test isn't getting picked up, neither:
```
@Test
    fun dummyTest() { assertTrue(true) }
```
Which makes me wonder if the problem is Android Studio itself.

Do you have any ideas?

**Comment by coachroebuck** [comment]
My sincere apologies. I'm an idiot. In my case, a regression error had been introduced. Those errors were revealed in the RUN panel.

My bad!

**Comment by sksamuel** [comment]
So what was the issue mike ?

**Comment by coachroebuck** [comment]
The original message:
```
WARN: Duplicated test name io.kotest.data.Row1. To disable this message, set DuplicateTestNameMode to None.
```
I am now using Android Studio Arctic Fox 2020.3.1, and no longer see that warning anywhere, or at least I haven't been paying attention.

The most recent post: We had a situation in which we actually changed the code base, but failed to update our unit tests accordingly. 🤷 

It was weird that Android Studio decided to even make an attempt to run the unit tests in spite of the errors the compiler found. 

Bizarre, but in any event, I have everything under control now.

Thank you and have a great day!
