### ISSUE TITLE
Junit @Nested annotation doesn't work with Kotest AnnotationSpec()

### ISSUE THREAD

**Issue by AlexLi-Monster** [kotest/kotest#2367]
**Which version of Kotest are you using**
Kotest version: 4.4.3

Have following test:
```
import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Nested

class MyTest : AnnotationSpec() {

    @Nested
    inner class TestA {

        @Test
        fun `A-1`() {
            true shouldBe true
        }

        @Test
        fun `A-2`() {
            true shouldBe true
        }
    }


    @Test
    fun `B`() {
        true shouldBe true
    }
}
```
only B is run, and when you run class `TestA` it says no tests found:
```
Execution failed for task ':test'.
> No tests found for given includes: [io.test.MyTest$TestA](filter.includeTestsMatching)
```

Have to change the @Test import from JUnit to make the `TestA` class run. Maybe Kotest should have its own @Nested annotation for it?

**Comment by sksamuel** [comment]
Yes, Kotest is not Junit so Junit annotations have no meaning here. 
We could add @Nested but why not move to one of the other styles that allows for richer nesting ?

**Comment by AlexLi-Monster** [comment]
Yeah, I saw some other styles like ExpectSpec and DescribeSpec has explicit support for nesting tests, but need to stick with the AnnotationSpec which is the team feel most comfortable with.

**Comment by sksamuel** [comment]
I'm not sure Kotest offers much over JUnit if you're using AnnotationSpec. The idea behind AnnotationSpec is to allow you to upgrade your junit tests bit by bit rather than being used for new tests.

But that being said, I'm totally open to adding @NestedTest to Kotest. So we can add that to the 5.0 release.
