### ISSUE TITLE
Kotest 4.6.1 pulls kotlin version up to 1.5.0

### ISSUE THREAD

**Issue by adecker89** [kotest/kotest#2368]
Hi, I read this bit in your release notes where you wanted to support multiple kotlin versions:

> The kotlin stdlib dependencies are now marked as compileOnly, meaning the version in your build will be used. Kotest tries to maintain compatibility across multiple versions by not relying on features only available in the latest releases.

But on trying it I noticed that I was still getting a dependency on kotlin 1.5.0 libraries.

Specifically I see that 
`io.kotest:kotest-runner-junit5-jvm:4.6.1` has an api dependency on `org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.0` which in turn pulls in the 1.5.0 stdlib

**Comment by sksamuel** [comment]
Ok yes I would consider this a bug. We shall release 4.6.2 with this reverted.
Thanks for letting us know.

**Comment by sksamuel** [comment]
So just looking into this today and yes it was a conscious decision to bump to 1.5 for 4.6 but the API level is still set to 1.4
So there should not be any code in kotest that _requires_ 1.5 at runtime.
Are you seeing different behavior ?

**Comment by adecker89** [comment]
This would be mostly about the standard library. I noticed my test builds were linking against the 1.5 stdlib. My actual application currently uses the 1.4 compiler and stdlib. Just the linking to the 1.5 stdlib was enough to cause issues in our tests and prevent us from upgrading.
I could most likely add an override rule in gradle to force my test targets to use 1.4 as well, but I didn't think this was the intention when those release notes were written.

**Comment by sksamuel** [comment]
Yeah it wasn't the intention. The intention was to make sure it compiles against 1.5 without requiring 1.5 necessarily to run.
The API version is set to 1.4 so I wonder if we can just set the stdlib to an older version and still compile it with 1.5 compiler.
