### ISSUE TITLE
testcontainers extension seems to require Java 11

### ISSUE THREAD

**Issue by maxwell-carbon** [kotest/kotest#2372]
**Which version of Kotest are you using**
`io.kotest.extensions:kotest-extensions-testcontainers:1.0.0`

When declaring a dependency on the above package, our (Java 8 + Gradle 7.1.1) build fails with:

```
> Could not resolve all files for configuration ':integrationTestCompileClasspath'.
   > Could not resolve io.kotest.extensions:kotest-extensions-testcontainers:1.0.0.
     Required by:
         project :
      > No matching variant of io.kotest.extensions:kotest-extensions-testcontainers:1.0.0 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability io.kotest.extensions:kotest-extensions-testcontainers:1.0.0 declares an API of a library, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
```

> Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

Given the rest of kotest seems happy with JDK8, can we fix the extension?

**Comment by sksamuel** [comment]
The test containers extension and test containers itself are defined with 1.8 API.
If you grab the latest jar from maven, and extract one of the files you can see they are indeed compiled with 1.8.

```
➜  /home/sam/development xxd StartablePerProjectListener.class | head
00000000: cafe babe 0000 0034 00dc 0100 3f69 6f2f  .......4....?io/
```

`cafe babe` is the  java magic bytes
`0000 0034` is [classfile version 34 aka 1.8](https://en.wikipedia.org/wiki/Java_class_file)

So I think there must be something else in your build making it fail ?

**Comment by sksamuel** [comment]
Did you fix this ?

**Comment by sksamuel** [comment]
A new version of the extension has been released - do you want to try that ?
`io.kotest.extensions:kotest-extensions-testcontainers:1.0.1`
