### ISSUE TITLE
AutoWired not work when use SpringExtension and IsolationMode.InstancePer(Test | Leaf)

### ISSUE THREAD

**Issue by HunJeong** [kotest/kotest#2373]
**Which version of Kotest are you using**
4.6.1

**version of kotest-extension-spring**
1.0.0

If I change IsolationMode to something that is not SingleInstance, the test will not work

But SpringListener works

ex) in [kotest-extensions-spring](https://github.com/kotest/kotest-extensions-spring) test
```kotlin
...
@ContextConfiguration(classes = [(Components::class)])
class SpringExtensionTest : WordSpec() {
   override fun isolationMode() = IsolationMode.InstancePerTest // or InstancePerLeaf
   override fun extensions() = listOf(SpringExtension)
   @Autowired
   private var service: UserService? = null
   init {
      "SpringExtension" should {
         "have autowired the service" {
            service?.repository?.findUser()?.name shouldBe "system_user"
         }
...
```
‘have autowired the service’ test is broken

**Comment by sksamuel** [comment]
This will require 5.0 to be released first, as we require a new extension mount to support this use case.

**Comment by sksamuel** [comment]
Now that 5.0.0.RC has been released, the latest snapshot of the spring extension has fixed this issue.
