### ISSUE TITLE
Improvement of equality.reflection assertions 

### ISSUE THREAD

**Issue by Burtan** [kotest/kotest#2375]
Hi,

I've played around with some reflect assertions and I think there should be made some changes.

- shouldBeEqualToComparingFields should have an option to skip computed properties (or make skip default and option to add)
- the actually comparing function checkEqualityOfFields could respect some special cases
  - Arrays
  - Others?

If a pull request is welcomed changing these things, I'm willing to provide some code :-)

**Comment by sksamuel** [comment]
For your first point, yes I think we should ignore any properties that are `synthetic` or `bridge`.
Point two, I think arrays is the type that mainly fails equals. We could override to use deep equals, perhaps enabled by a parameter. 
Would love to see a PR if you have time.
