### ISSUE TITLE
Proposal for a better DoubleShrinker.

### ISSUE THREAD

**Issue by sielenk-yara** [kotest/kotest#2378]
The Kotest 4.6.1 `DoubleShrinker` does not produce values I would consider "simpler" than the input:

```
val f = 785040.1538306947
val x = DoubleShrinker.shrink(f)
println(f)
println("------")
x.forEach { println(it) }
```
produces
```
785040.1538306947
------
0.0
1.0
-1.0
785040.1538306947
261680.05127689824
392520.07691534737
785035.1538306947
785036.1538306947
785037.1538306947
785038.1538306947
785039.1538306947
785040.0
```
where the first three values are covered by the normal edge cases and most of the rest I would consider about as complicated as the input. 

I propose something like this
```
fun shrink(value: Double): List<Double> {
  if (!value.isFinite())
    return emptyList()
  val (mantissa, exponent) = "%+.17e".format(Locale.ROOT, value).split('e')
  val trimmedMantissa = mantissa.trimEnd('0')
  val shrunkStrings = (3 until trimmedMantissa.length).reversed()
    .map { "${trimmedMantissa.substring(0, it)}e$exponent" }
  return shrunkStrings.map { it.toDouble() }
}
```
which produces
```
785040.1538306947
------
785040.153830694
785040.15383069
785040.1538306
785040.15383
785040.15383
785040.1538
785040.153
785040.15
785040.1
785040.0
785040.0
785000.0
785000.0
780000.0
700000.0
```
I would find this more helpful when looking for "simpler" values.

The same applies to the `FloatShrinker`.

**Comment by sielenk-yara** [comment]
I just tried to create a pull request for this and found that this only works on the JVM platform!

Maybe I can come up with a non-string based solution for this...

**Comment by sielenk-yara** [comment]
I think I misunderstood the `Shrinker` interface:
`shrink` should not return the whole list of simpler numbers, but only the next one: `shrink(785040.15) shouldBe listOf(785040.1)`.

**Comment by sksamuel** [comment]
Did you get any further with this @sielenk

**Comment by sielenk** [comment]
Sadly no, not yet.
And missed the 5.0 deadline ...

**Comment by sksamuel** [comment]
No 5.0 is still in flight.

**Comment by sielenk** [comment]
Hm. So I dug up [Correctly Rounded Binary-Decimal and Decimal-Binary Conversions](https://ampl.com/REFS/rounding.pdf) and started an implementation of that. But this feels overpowered for the use case, esp. given the fact that each platform has something like that already implemented for turning doubles into strings.
I think I will try something along the lines of the code above with added handling for different ways to format doubles to strings (exponential vs. plain).
