### ISSUE TITLE
Problem with shrinking filter

### ISSUE THREAD

**Issue by lidonis** [kotest/kotest#2380]
**Which version of Kotest are you using** 4.6.1

I tried to do property based testing but got a wrong shrinking number with filter
I got 1 as a result of the shrinking but it should not be a result according to the filter

```
class ShrinkTest : WordSpec(  {
    "Arb int with filter even should not have 1 with shrink" should {
        checkAll(Arb.int().filter { it % 2 == 0 }) { a ->
            a shouldBe 0
        }
    }
})
```

**Comment by sielenk** [comment]
This is a problem in the implementation of Arb.filter (kotest-property/src/commonMain/kotlin/io/kotest/property/arbitrary/filter.kt).
It only filters the generated values, not the shrinkers.
