### ISSUE TITLE
Js tests are allways passing 

### ISSUE THREAD

**Issue by JimeFuture** [kotest/kotest#2382]
Im in a mulitplatform project. Setup was done like discibed in the "get started" section.
The jvmTests are working as aspected.

The jsTests are always passing, even it not could pass at all:
```
class Main : FunSpec({
                         test("File") {
                             2 shouldBeGreaterThan 15
                         }
                     })
```
Is there any additional setup must be done?

**Comment by sksamuel** [comment]
IR mode ?

**Comment by JimeFuture** [comment]
Yes jvm and js complier both set to IR

**Comment by ashishkujoy** [comment]
This is getting track here: #2163

**Comment by sksamuel** [comment]
Yep duplicate of https://github.com/kotest/kotest/issues/2163
