### ISSUE TITLE
Should error when Container tests do not contain a nested test

### ISSUE THREAD

**Issue by miguelbaldi** [kotest/kotest#2383]
**Which version of Kotest are you using**
4.6.1

I've noticed the following behavior when I've upgrade Gradle from 6.6.1 to 7.1.1.
When using WordSpec style, if we write the tests with `When` and `should`, without one more nested level, test class does not show on JUnit HTML report.
I was able to observe that the tests were running when a test fail, this way, the test is shown but without class name and package (default-package name instead). If we add one more level nested inside `should`, the tests are shown correctely.
Dependencies versions:
```
    testImplementation 'io.kotest:kotest-runner-junit5:4.6.1'
    testImplementation 'io.kotest:kotest-assertions-core:4.6.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.2'
```
Compile but does not produce correct JUnit HTML report:
```kotlin
class NotWorkingTests : WordSpec({
    "Hello" When {
        "asked for length" should {
            "Hello".length shouldBe 5 // If we set wrong value here, test is shown on HTML report with wrong package(default-package)
        }
        "appended to Bob" should {
            "Hello " + "Bob" shouldBe "Hello Bob"
        }
    }
})
```
Compile and does show on JUnit HTML report:
```kotlin
class WorkingTests : WordSpec({
    "Hello" When {
        "asked for length" should {
            "working with gradle 7" {
                "Hello".length shouldBe 5
            }
        }
        "appended to Bob" should {
            "working with gradle 7"{
                "Hello " + "Bob" shouldBe "Hello Bob"
            }
        }
    }
})
```

Is this a bug? Why this works on Gradle 6.6.1?
I've made an example project to show this behaviour:

[Sample project](https://github.com/miguelbaldi/gradle-7-kotlin-kotest)

UPDATE

Actually, the way the reports are shown, has fundamentally changed:
Gradle 6
![2021-07-26-15:07:17_1920x1080](https://user-images.githubusercontent.com/30936/127037938-12b3aa19-c2a5-45b9-bf48-2d4a3eb3afc4.png)
Gradle 7
![2021-07-26-15:08:12_1920x1080](https://user-images.githubusercontent.com/30936/127037981-04ae3522-3d9a-47e8-81de-50280081911b.png)

**Comment by sksamuel** [comment]
It's because you haven't "completed" the test.
In WordSpec the test after "should" is the outer test and should always be included.
I think for 5.0 we can make the test framework let you know if you don't complete the test properly.

**Comment by miguelbaldi** [comment]
Thanks for the response, @sksamuel !

And what about the way the tests are shown on Gradle 7, they are pretty different, is that the intended behaviour?

**Comment by sksamuel** [comment]
Gradle doesn't understand nested tests.
Some open bugs at gradle for several years. I wouldn't count on them being fixed anytime soon.

**Comment by sksamuel** [comment]
Added in master for 5.0 release
