### ISSUE TITLE
autoClose breaks Lazy

### ISSUE THREAD

**Issue by nomisRev** [kotest/kotest#2388]
**Which version of Kotest are you using**

1.4.6

[Here](kotest/core/TestConfiguration.kt#L118) Lazy is immediately invoked which initializes the Lazy value, to then pass it to the immediate autoClose function which rewraps in Lazy [here](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/TestConfiguration.kt#L110).

If delegation happens to other way around, meaning `fun <T : AutoCloseable> autoClose(closeable: T): T` uses `fun <T : AutoCloseable> autoClose(closeable: Lazy<T>): Lazy<T>` than Lazy'ness can be preserved.

When closing the `AutoCloseable` in `invokeAfterSpec` you can check `Lazy#isInitialised` before calling `lazy.value.close()` to avoid initializing values that are not used, and thus don't need to be closed.

**Comment by nomisRev** [comment]
Causing following issue:

Integration tests with Docker hosted Postgres, and `HikariDataSource`.

i.e:

```
class IntegrationTest : StringSpec({
  val container = PostgressContainer().apply { ... }
  listeners(container.perSpec())
  val dataSource by autoClose(lazy { dataSource(container, ...) })
})
```

Since `autoClose` breaks `Lazy` it will try to initialize itself immediately which means it doesn't respect the lifecycle of `container` which was should be started before `autoClose` is used for the first time.

**Comment by nomisRev** [comment]
Happy to open a PR for this 👍

**Comment by sksamuel** [comment]
Please do !
