### ISSUE TITLE
Add configuration option to set minimum execution time in property tests

### ISSUE THREAD

**Issue by YSakhno** [kotest/kotest#2401]
I'd like to see an option to specify the minimum _amount of time_ (as opposed to iteration count) that is required for execution of each test function for property-based testing. So for example if time is set to 1 second, then the test function gets as many iterations as required to make 1 second.

If there are both the time, and the number of iterations configured, then whichever is _greater_ should be considered for each test function. In other words, if the minimum time runs out _before_ the iteration count is exhausted, then the particular test continues to be executed until all iterations "run out". This guarantees at least _n_ iterations run on slower machines, where _n_ would be a configured number set either via `PropertyTesting.defaultIterationCount` or via the explicit argument of the `checkAll` / `forAll` functions. On the other hand, faster machines would have more iterations, which I think would improve coverage.

Optionally, there could be a possibility to specify whether the "greater" or "lesser" of the two configuration options is chosen when both are specified, but if this feature request is implemented with just the "greater" strategy, that should be fine too.

As an advanced feature (for the future), there could probably be an ability to specify custom (i.e. programmatic) stopping strategies. This is just an idea, but not in scope of this feature request.

**Comment by sksamuel** [comment]
Some great ideas in there. I think we should include this in 5.0
