### ISSUE TITLE
Include range's first and last values as edge cases in Arb.int()

### ISSUE THREAD

**Issue by YSakhno** [kotest/kotest#2406]
When an arbitrary integer generator is created with a custom range, that range's first and last values should be automatically included as edge cases. With the default rage (`Int.MIN_VALUE..Int.MAX_VALUE`) this comes 'for free', but if integers are requested for a custom range (say, `Arb.int(10..100)`), then all default edge cases are effectively filtered out by the range. I think it makes sense to include `range.first` and `range.last` (which would be `10` and `100` in the previous example) to the list of edge cases.

The same principle may be applied to generators of other numeric types (`Long`, `Short`, etc., as well as the unsigned counterparts). (Well, generator for shorts does not allow specifying limits for some reason...)

**Comment by sksamuel** [comment]
Good idea.

**Comment by YSakhno** [comment]
Actually, I found this text in documentation for `Arb`:

> Not all arbitraries will utilize edge cases. For example, if you define an integer generator using a subset of the number space - say from 100 to 200 - then no edge cases would be provided.

So it seems the current behavior is known and was chosen consciously at some time in the past. Not sure why, as I think having edge cases at the ends (i.e. _edges_) of the range would be beneficial.

**Comment by sksamuel** [comment]
Yes, so while the current implementation isn't wrong according to our docs, I think it could be improved by adding these edge cases.

**Comment by sksamuel** [comment]
The edgecases are already included actually.
This is the implementation:

```
fun Arb.Companion.int(range: IntRange = Int.MIN_VALUE..Int.MAX_VALUE): Arb<Int> {
   val edgeCases = intArrayOf(range.first, -1, 0, 1, range.last).filter { it in range }.distinct()
   return arbitrary(edgeCases, IntShrinker(range)) { it.random.nextInt(range) }
}
```

So looks like docs are just incorrect.

**Comment by YSakhno** [comment]
OK, I see. This code is not in the version I currently use (4.6.1) for some reason, so I did not know that it was already implemented.

Did you check generators for other types (longs, shorts, bytes, etc.) as well? Possibly also floating point ones...

**Comment by sksamuel** [comment]
I have checked the other types and updated docs were appropriate.
