### ISSUE TITLE
Sequence.containExactly should work for single pass sequences

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2412]
**Which version of Kotest are you using**

**Comment by sschuberth** [comment]
We're using version 4.6.1, also see [this discussion](https://github.com/oss-review-toolkit/ort/pull/4244#discussion_r687414896):

> The sequence matcher, however, first determines the count of the sequence (which requires a traversal) and afterwards checks the elements (another traversal). This second traversal no longer returns the full sequence, causing the comparison to fail.

**Comment by sksamuel** [comment]
@sschuberth do you need a fix for 4.6.x or are you ok to wait for 5.0 ?

**Comment by sschuberth** [comment]
Thanks for asking. While I have no idea for when 5.0 is planned, I guess it's fine to wait as we can live with the `toList()` work-around for now.

**Comment by sksamuel** [comment]
4 weeks

**Comment by sksamuel** [comment]
Released in 4.6.2

**Comment by sschuberth** [comment]
Thanks a lot!
