### ISSUE TITLE
Provide more powerful way of registering extensions

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2417]
Currently, we can do something like:

```
class MyTest : FunSpec({
  listener(embeddedKafkaListener)
})
```

But there's no way to get back a materialized value (to steal akka streams nomenclature). when the listener is created. In the kafka example we re-use the listener as the control too.

It would be good to something like:

```
class MyTest : FunSpec({
  val kafka = install(embeddedKafkaListener)
})
```

Then we can offer things like:

```
class MyTest : FunSpec({
  val db = install(EmbeddedDatabase)
})
```

We can use the word `install` or anything else that might be more appropriate.

**Comment by LeoColman** [comment]
Can't we do
```
val myListener: KafkaListener = listener(KafkaListener)
```
already?

**Comment by sksamuel** [comment]
Yep, but that just returns the instance you pass in.
I should have been clearer, I'm imagining that there's some kind of "setup" callback on the instance you pass in, and the return of that is what you get back.
That's how the akka streams materialized value thing works.
