### ISSUE TITLE
Property Module: PropTestConfig's `iterations` parameter is not respected.

### ISSUE THREAD

**Issue by nicorichard** [kotest/kotest#2428]
**Which version of Kotest are you using**

4.6.1

**Description**

The PropTest/PropTestConfig data structures [described here](https://kotest.io/docs/proptest/property-test-config.html) contain a value `iterations` which is not respected by `checkAll`, `forAll`, or the underlying internal `proptest` functions.

**Steps to Reproduce**

Test code:
```kotlin
@Test
fun test_checkAll_iterations() = runBlockingTest {
    val expectedIterations = 10
    
    var iterationCounter = 0
    checkAll(PropTestConfig(iterations = expectedIterations), Arb.int()) {
        iterationCounter++
    }
    
    assertEquals(expectedIterations, iterationCounter)
}
```

Result:
```
expected:<10> but was:<1000>
```

**Comment by sksamuel** [comment]
Released in 4.6.2
