### ISSUE TITLE
Run tests in single Spec in parallel ini kotest

### ISSUE THREAD

**Issue by Ankit-Laddha** [kotest/kotest#2433]
How can one run tests in single Spec in parallel in kotest? I have asked same question here: https://stackoverflow.com/questions/68865079/run-tests-in-single-spec-in-parallel-ini-kotest

Spec Style: FunSpec

**Comment by sksamuel** [comment]
So, like

```kotlin
class MySpec : FunSpec({
   test("1") { }
   test("2") { }
}
```

You want 1 and 2 to run in parallel ?

**Comment by Ankit-Laddha** [comment]
@sksamuel yes. Because I'm using kotest as an e2e framework. Each test itself is independent test journey hence I want to leverage running them in parallel.

**Comment by sksamuel** [comment]
Inside your spec you can set concurrency = x

```
class MySpec : FunSpec({
  concurrency = 10
   test("1") { }
   test("2") { }
}
```
