### ISSUE TITLE
How to add new attachment to the allure report

### ISSUE THREAD

**Issue by Ankit-Laddha** [kotest/kotest#2436]
Kotest: 4.6.2

I'm trying to take a screenshot of HTML page and attach that as a screenshot in Allure Test Report in the Listener AfterTest method

```
Allure.addAttachment(
            "Page Screenshot",
            "image/png",
            ((driver as TakesScreenshot).getScreenshotAs(OutputType.BYTES)).toString(),
            ".png"
        )

```

1. I see the .png file in the Allure folder but it does not have the same name "Page Screenshot" which I have passed. Rather it is named as `<uuid>-attachment.png` 
2. But the final Allure report still doesn't show the screenshot. I believe that is because write to add attachment is already closed. How do I add attachments then?

**Comment by sksamuel** [comment]
Where are you adding that Allure.addAttachment block ?

**Comment by Ankit-Laddha** [comment]
If there was an exception during test case run, i'm checking that in afterTest method of my listener and then want to take a screenshot of my browser and add that to allure report.
We also don't have various other events like onFailure, onSkipped etc like we have in TestNG or do we?

**Comment by sksamuel** [comment]
There are many lifecycle events you can tap into. You can look at TestListener and look at afterTest and that contains the status of the test.

So what I would do is this - create your own allure listener by wrapping ours.
Then in afterTest you can add the attachment.

```
class AnkitAllureTestReporter(private val reporter: AllureTestReporter) : TestListener, SpecInstantiationListener {

   override suspend fun beforeTest(testCase: TestCase) {
      reporter.beforeTest(testCase)
   }

   override suspend fun afterTest(testCase: TestCase, result: TestResult) {
      reporter.afterTest(testCase, result)
      if (result.status == TestStatus.Error || result.status == TestStatus.Failure) {
         Allure.addAttachment(
            "Page Screenshot",
            "image/png",
            ((driver as TakesScreenshot).getScreenshotAs(OutputType.BYTES)).toString(),
            ".png"
         )
      }
   }

   override fun specInstantiationError(kclass: KClass<out Spec>, t: Throwable) {
      reporter.specInstantiationError(kclass, t)
   }
}

```

**Comment by sksamuel** [comment]
Please reopen if my solution does not work
