### ISSUE TITLE
Arrow Extension requires Java 11

### ISSUE THREAD

**Issue by kieranipalmer** [kotest/kotest#2437]
**Which version of Kotest are you using**
`io.kotest.extensions:kotest-assertions-arrow:1.0.3`

Our Gradle Builds are failing after changing to use the extension packages. It appears that the Arrow extension requires Java 11

```
Required by:
         project :server
      > Unable to find a matching variant of io.kotest.extensions:kotest-assertions-arrow:1.0.3:
          - Variant 'apiElements' capability io.kotest.extensions:kotest-assertions-arrow:1.0.3:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'
```

I believe there was a similar issue with TestContainers: https://github.com/kotest/kotest/issues/2372
Can we update the Arrow extension to work on Java 8?

**Comment by sksamuel** [comment]
@i-walker Does arrow need 11 ?
If not I will change the release process to use 8.

**Comment by i-walker** [comment]
No it works on 8, 9, 11, and higher. 
I will look into it

**Comment by pitagoras3** [comment]
Hi, I've looked into it, and in my simple test case everything works:

**Dependencies:**
```
implementation "io.arrow-kt:arrow-core:1.0.0"
testImplementation 'io.kotest:kotest-runner-junit5:4.6.3'
testImplementation 'io.kotest.extensions:kotest-assertions-arrow:1.0.3'
```

**Code:**
```kotlin
import arrow.core.Option
import arrow.core.none
import io.kotest.assertions.arrow.core.shouldBeNone
import org.junit.jupiter.api.Test

internal class KotestArrow {

    @Test
    fun testOption() {
        val emptyValue: Option<String> = none()
        emptyValue.shouldBeNone()
    }
}
```

**Execution:**
```shell
$ java --version                                                                                                                                                                                                                                                                            
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

$ ./gradlew build                                                                                                                                                                                                                                                                           

BUILD SUCCESSFUL in 2s
5 actionable tasks: 3 executed, 2 up-to-date
$ ./gradlew test

BUILD SUCCESSFUL in 628ms
5 actionable tasks: 5 up-to-date
```

Maybe issue is somewhere else? I've googled parts of your error message and found that someone else had similar problem here: https://discuss.gradle.org/t/composite-build-fails-because-of-jvm-versions-how-to-fix/34501

**Comment by MiSikora** [comment]
@pitagoras3 This isn't the issue. You ran a project against Java 11, and it will compile without any problem. The point is the compatibility with Java 8.

You can see it in this sample project. https://github.com/MiSikora/arrow-extensions-compatibility

A simple project builds on all versions of Java above 10. https://github.com/MiSikora/arrow-extensions-compatibility/actions/runs/1346497312

The same project, when targeting Java 8, does not build at all. https://github.com/MiSikora/arrow-extensions-compatibility/actions/runs/1346503224

You can skip builds for Java 9 and 10 where there are issues with Java certificates.

**Comment by sksamuel** [comment]
I believe what happend was github actions changed their default jdk to 11 and so after that all our builds were built using that.
I've been explicitly specifying jdk 8 since, and we just need to release another arrow build.

**Comment by i-walker** [comment]
I am working on the next build, sorry I was not able to proceed on this issue, but once we fix the CI build I can PR an update to that sample project in @MiSikora

**Comment by i-walker** [comment]
As of [this](https://oss.sonatype.org/content/repositories/snapshots/io/kotest/extensions/kotest-assertions-arrow/1.0.0.36-SNAPSHOT/) release, this issue is fixed. In the following days we can release a `1.0.4` version with that fix and I try to make it binary compatible as possible

**Comment by sksamuel** [comment]
1.1.0 has been released which restores JDK 8 compatibility.
@MiSikora @kieranipalmer
