### ISSUE TITLE
Property Module: Mutation of global PropertyTesting configuration throws InvalidMutabilityException in Kotlin/Native

### ISSUE THREAD

**Issue by nicorichard** [kotest/kotest#2440]
**Which version of Kotest are you using**
4.6.2

**Steps to reproduce**

Simply attempt to modify the global `PropertyTesting` configuration from a test running in Native (I'm using iosX64)

```
@Test
fun test_changing_property_testing_global_config() {
    PropertyTesting.defaultIterationCount = 100
}
```

```
kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen io.kotest.property.PropertyTesting@6bc211d8
```

**More Information**

We are attempting to upgrade to kotest 4.x property testing into a Kotlin Multiplatform Mobile (android + ios) project. 
Previously we were using a barebones internal framework with a similar generator concept.

With Kotlin/Native we find that tests take 2-3x longer than on JVM with much more expensive CI infrastructure so we took the approach of having different default iteration amounts per platform.

e.g. Android checks more business logic running 1000 iterations and iOS confirms that there are not unexpected differences with a more modest 500 iterations. Saving 1/2 the macOS CI time.

**Comment by sksamuel** [comment]
I think we just need to freeze the PropertyTesting object.

**Comment by nicorichard** [comment]
A frozen object becomes immutable which should mean that we can no longer modify the configuration.

I have been experimenting with a solution based on patterns we use on our apps, running into some issues from the JVM side now but [the commit is here if you're curious](https://github.com/CityTransit/kotest/commit/04206eb512884a74cfee83d0331528876063841b).

**Comment by sksamuel** [comment]
Ah yes of course if it's frozen.

**Comment by sksamuel** [comment]
I guess moving it out to the container object fixes that issue.
Might be a good approach to revisit this for 5.0.0 that we're looking to release soon.

**Comment by sksamuel** [comment]
Isn't @ThreadLocal supposed to avoid this issue on native ?

**Comment by nicorichard** [comment]
> Isn't @ThreadLocal supposed to avoid this issue on native ?

`@ThreadLocal` is most likely doing its job of providing copies for different threads. The issue is that in K/N an Object definition is frozen by default, making the reference immutable and subject to `InvalidMutabilityException`.

Proof:
```kotlin
object SomeObject

@Test
fun `Objects are frozen by default`() {
    assertTrue { SomeObject.isFrozen }
}
```

It's not so clear that we would even want this object to be Thread Local at any rate. It might be quite confusing to modify the _global_ configuration and only see the result on a single thread.

**Comment by sksamuel** [comment]
@ThreadLocal turns off immutability but it doesn't help us if global config
is not global.
