### ISSUE TITLE
Rename "assertSoftly" to "assertGroup"

### ISSUE THREAD

**Issue by Dignig** [kotest/kotest#2442]
Unfortunately, the name of the method "assertSoftly" doesn't reflect entirely it's behaviour and confuses. It is desirable to rename the method to "assertGroup". Or add "assertGroup" and make "assertSoftly" deprecated.

**Comment by sksamuel** [comment]
We have any { } as well. Perhaps assertAny or assertAll is better.

**Comment by jschneidereit** [comment]
Please use`io.kotest.assertions.all { }` , it is the new and improved `assertSoftly` as of #2233
