### ISSUE TITLE
withClue() fails with EmptyStackException if a coroutine switches threads

### ISSUE THREAD

**Issue by OliverO2** [kotest/kotest#2447]
Version: `kotest-assertions-core:4.6.2`

As described in the [coroutine docs on thread-local data](https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#thread-local-data), a coroutine may switch threads at suspension points.

`withClue()` relies on thread-local data via `ThreadLocalErrorCollector`, without taking coroutine thread-switching into account. It fails if its block contains a coroutine resuming on a different thread.

#### Example
```kotlin
import io.kotest.assertions.withClue
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test

class TestCase {
    @Test
    fun `coroutine changing threads`() = runBlocking(Dispatchers.Unconfined) {
        withClue("Hello") {
            Thread.currentThread().run { println("withClue() block begins on $name, id $id") }
            delay(10)  // First suspension makes the Unconfined dispatcher resume on a different thread
            Thread.currentThread().run { println("withClue() block ends   on $name, id $id") }
        }
    }
}
```
##### Build script
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.5.30"
    application
}

group = "me.oliver"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1")
    testImplementation(kotlin("test"))
    testImplementation("io.kotest:kotest-assertions-core:4.6.2")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}

application {
    mainClass.set("MainKt")
}
```

##### Result
```
> Task :test FAILED
withClue() block begins on Test worker @coroutine#1, id 12
withClue() block ends   on kotlinx.coroutines.DefaultExecutor @coroutine#1, id 15

java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:102)
	at java.base/java.util.Stack.pop(Stack.java:84)
	at io.kotest.assertions.ThreadLocalErrorCollector.popClue(ErrorCollector.kt:32)
	at TestCase$coroutine changing threads$1.invokeSuspend(TestCase.kt:23)
```

**Comment by jschneidereit** [comment]
I have a feeling at least part of this solution might be to revamp the error collector to be a coroutine context element as well as making suspending `withClue` implementations that know about a `CoroutineContext`

**Comment by OliverO2** [comment]
I agree.

**Comment by sksamuel** [comment]
Yes we've mullled over this jim and also doing the same for soft assertions mode

**Comment by jschneidereit** [comment]
Excellent 😈

**Comment by sksamuel** [comment]
@jschneidereit we might want to consider https://github.com/kotest/kotest/issues/2230 too

**Comment by OliverO2** [comment]
[Here is a prototype implementation](https://gist.github.com/OliverO2/e9a9cc962f5b4bc5210a3797b6c46a34) for a coroutine-safe `ErrorCollector`.

After some experimentation, it seems that a `ThreadLocal` context element must be explicitly inserted into newly created coroutine contexts, i.e. those, that do not inherit from other contexts.

In the prototype implementation, this is done via `runBlocking(ErrorCollector.contextElement)`.

**Comment by sksamuel** [comment]
runBlocking won't be available on JS unfortunately.
We should be able to do this purely though coroutine contexts, by adding the clue into the context, and then pulling it out after the block runs.

**Comment by OliverO2** [comment]
`runBlocking` just serves as an example for a place where a top-level coroutine context is created. In my prototype implementation, it would be the Kotest user's responsibility to insert the required `ErrorCollector.contextElement` into each top-level context.

Ideally, there would be an injection opportunity for the Kotest library to specify a set of default context elements, which are automatically added everywhere a top-level context is created. Unfortunately, I am not aware of any such mechanism.

**Comment by sksamuel** [comment]
Right.

Thinking about this, any reason we can't do

```kotlin
inline fun <T> withClue(clue: String, f: () -> T): T {
   return try { f() } catch (e: Exception) { rethrow e with clue here }
}
```

**Comment by OliverO2** [comment]
Yes, that should work for clues.

I'm not too familiar with soft assertions. Does it seem feasible to come up with a solution for those which avoids accessing an `ErrorCollector`?

**Comment by sksamuel** [comment]
The error collecting is the mechanism by which we collect errors as they happen. We're kinda stuck a bit there as the Matcher interface is not suspending and that can't be changed.

Inside matcher, when an assertion throws, it checks to see if there's a thread local error collector and if so, adds to that rather than hard throwing.

What would be better is if matcher was suspendable, we could look for a context element that contains a collector. But like I say, matcher is stuck being non suspending now.

If you can think of a way to square that circle that would be great...

As for clue - it doesn't need to use error collector at all. The current impl is that the clue is added to the assertion, but we can invert that - just catch any throwable and rethrow with the clue added. Super simple.

**Comment by sksamuel** [comment]
We can prob do a trick where each time a coroutine is suspended and resumed
we swap out the thread local copy.

**Comment by OliverO2** [comment]
The swapping is exactly what my above prototype implementation makes the coroutines library do via the `ErrorCollector.contextElement`.

It should work for soft assertions as well. If we had some way to hook into top-level context setup, we'd be covered. The place would probably be this function in `kotlinx.coroutines`, but the API is not there (yet): 
```kotlin
fun CoroutineScope.newCoroutineContext(context: CoroutineContext): CoroutineContext
```

If we could make the Kotest user remember to use some Kotest-provided mechanism when creating top-level contexts in test cases, we should be fine. The question remains, could there be an easier way out?

I'm just trying to verify some assumptions about soft assertion mode...

**Comment by sksamuel** [comment]
You could insert it via a test execution interceptor.

See latest code in master.

**Comment by sksamuel** [comment]
I'm not sure yours works if the thread changes.

**Comment by sksamuel** [comment]
Take a look at the CoroutineStatus element in 4.6.x branch. That has the trickery we need.

**Comment by OliverO2** [comment]
I see. `CoroutineStatus` is part of the engine, so it does not solve the problem for those using matchers with JUnit, right?

This one and mine seem to do about the same. Both require a specially set-up context.

And yes, mine works when switching threads. That's what it is all about, right? See the [test cases provided along with the output below those](https://gist.github.com/OliverO2/e9a9cc962f5b4bc5210a3797b6c46a34) where the thread id changes from 12 to 15 and back.

**Comment by OliverO2** [comment]
If I got it correctly, it looks like this:

* The solution you suggested for `withClue` seems viable: It directly receives an exception and passes it along with its clue back up the call stack. Thereby it eliminates the clue stack in `ErrorCollector`. All fine and simpler than before.
* `assertSoftly` cannot follow that route as it does not directly receive exceptions. So it would have to pass an error-collecting context to matchers. That context would have to be a coroutine-local variable (a thread-local adjusted for coroutine thread hopping).
* For `assertSoftly` the need to have a coroutine-local error collector remains, and it seems like the `ThreadLocal<T>.asContextElement()` from `kotlinx.coroutines` is the easiest way to solve this for the JVM.
* The required `CoroutineContext.Element` can easily be inserted via Kotest's own test engine, but not for other test frameworks.

**Comment by sksamuel** [comment]
Yes that aligns with my thinking.

And following on it still works for junit because they're typically just
sticky on one thread.

And if you're using junit and coroutines and bouncing around threads well
that's a niche edge case we won't support.... and just upgrade to Kotest
already :)

**Comment by OliverO2** [comment]
Been there. Unfortunately, the all-in-one-function style used be the Kotest framework did not integrate well with IDE support (e.g. IntelliJ's structure view) and I've been observing stability issues with the Kotest IDE plugin. So I moved to JUnit 5 but kept the matchers. I'm using coroutines extensively with complex multi-threaded tests.

**Comment by sksamuel** [comment]
Hmm interesting. How long ago was this.

**Comment by OliverO2** [comment]
Sometime between mid-April and mid-May.

**Comment by sksamuel** [comment]
I know that Kotlin 1.3.x and maybe early versions of 1.4 had some slowdowns in IintellJ for DSLs that used many lambdas, but since like 1.4.30 and 1.5 for sure, it's been very fast in the IDE. Also there's the Kotest structure view which gives you a nested layout for tests and allows you to jump around and see callbacks.

**Comment by OliverO2** [comment]
I could try the plugin again. That might take some time but I'll report back if I find something of interest.

Even with the Kotest engine, one might want to use custom coroutine contexts or `runBlockingTest`.

I think it would be a good idea to
* implement the solution suggested above for `assertSoftly`,
* set the ThreadLocal-`CoroutineContext.Element` in the engine, and
* make the ThreadLocal-`CoroutineContext.Element` publicly availabe to cover scenarios beyond the engine's control.

**Comment by sksamuel** [comment]
I agree with those steps.

**Comment by OliverO2** [comment]
The issue is currently assigned to @jschneidereit. Should I provide a PR nonetheless?

**Comment by sksamuel** [comment]
I don't think Jim has started on this yet, I was only chatting with him about it late Friday, so you could do a PR yeah.

**Comment by OliverO2** [comment]
OK, will do.

**Comment by jschneidereit** [comment]
Sorry, I had some things come up. I can provide code review though.

**Comment by sksamuel** [comment]
What about if the functions were suspendable then they could install the element and it would work on everything

**Comment by OliverO2** [comment]
Yes, we had that in our slack discussion. Ideally, we'd have a suspending version installing the context and a non-suspending one not doing so. However, the compiler does not like type inference based on suspend differences alone. The example is for `withClue`, which can be solved by other means, but will be the same for `assertSoftly`:

```kotlin
suspend fun <R> withClue(clue: Any?, thunk: suspend () -> R): R

fun <R> withClue(clue: Any?, thunk: () -> R): R
``` 

In this case, it would complain on the non-suspending call site:
> Overload resolution ambiguity
 
This is https://youtrack.jetbrains.com/issue/KT-23610.

**Comment by sksamuel** [comment]
Could put in different packages although the user will need to pick.

Another alternative is a compiler plugin.
