### ISSUE TITLE
Support for nested tests on Kotlin/Native

### ISSUE THREAD

**Issue by charleskorn** [kotest/kotest#2453]
At the moment, attempting to use any kind of nested test fails on Kotlin/Native targets with an exception:

```
kotlin.IllegalStateException: Spec styles that support nested tests are disallowed in kotest-js and kotest-native due to restrictions in the platforms. Please use FunSpec, StringSpec, or ShouldSpec and ensure that nested contexts are not used.
```

Being able to nest tests is one of the compelling features of kotest over the built-in kotlin.test framework. What would it take to support this?

**Comment by sksamuel** [comment]
On native, it will be included in 5.0 if possible, it shouldn't be difficult.
On JS it's not possible without changing Kotest in breaking ways.

**Comment by sksamuel** [comment]
@charleskorn try snapshot 471.
The output isn't amazing because the intellij format lacks real nested support but it works.

**Comment by charleskorn** [comment]
Awesome, thanks @sksamuel
