### ISSUE TITLE
Does the bind() function of property testing support shrinking?

### ISSUE THREAD

**Issue by YSakhno** [kotest/kotest#2461]
Reading the source code for **v4.6.2**, I don't see anything related to shrinking support by [the `bind()` function](https://kotest.io/docs/proptest/generator-operations.html#bind). So even if the individual generators used in binding support shrinking, we have to forego shrinking, it seems. Am I misreading the source code and missing the point somehow?

**Comment by sksamuel** [comment]
You're correct.
We could update bind to defer to component shrinkers.
PR ?
