### ISSUE TITLE
Failing withData-test doesn't show up properly in IntelliJ when executing tests with gradle

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2491]
**Which version of Kotest are you using**
4.6.2

**When IntelliJ is configured to run tests with Gradle (default):**
Running a spec with a `context` containing `withData` inside it, where one of the `withData` tests results in the `context` being entirely removed from the test report. See here:
![bild](https://user-images.githubusercontent.com/316857/132899025-e658e828-30ef-49b9-87de-67b149dd3b2f.png)

For comparison, re-configuring IntelliJ to `Run tests using: IntelliJ` makes the tests show up properly. 
![bild](https://user-images.githubusercontent.com/316857/132899124-4c106bb2-dcd4-4bcc-9766-23806e664305.png)

Reproduction sample available in: https://github.com/Kantis/kotest-repro/tree/withData-gradle

**Comment by sksamuel** [comment]
FYI works in 5.0.0.M1 so something fixed it between 4.6.x and now.

**Comment by Kantis** [comment]
Awesome, I'll close this. 💯
