### ISSUE TITLE
Spring extension documentation - Mimicking behaviour of a controller - Integration Testing

### ISSUE THREAD

**Issue by tomgardiner-retailx** [kotest/kotest#2505]
1) Trying to create an integration test for a spring controller
2) This controller will have the annotation @Controller
3) Wanting to asset that when /greeting endpoint is hit with request, that this request is returned (expected behaviour)

How do I do the following integration tests as shown on spring's website?

https://spring.io/guides/gs/testing-web/

I have tried following the documentation on: https://kotest.io/docs/extensions/spring.html but am confused on how I should do this.

With the example given, I have changed it to a FunSpec - with the following files.

My questions:
1) What do I need to put for for the 'Components' import (Components::class) - there are no suggestions for importing in IDE
2) What should my test look like?
3) How do I fix all of the errors your extensions-spring dependency has introduced so that I can use it?
```
//Controller.kt

@Controller
class GreetingController(private val service: GreetingService) {

  @RequestMapping("/greeting")
  @ResponseBody
  fun greeting(@RequestBody request: String): ResponseEntity<String> {
    val response: String = service.greet(request)
    return ResponseEntity<String>(response, HttpStatus.OK)
  }
}
```

```
//Service.kt

@Service
class GreetingService {
  fun greet(greeting: String): String {
    return greeting
  }
}
```

```
//IntegrationTest.kt

//This import fails. What should I be importing for components?
@ContextConfiguration(classes = [(Components::class)])
class IntegrationTest : FunSpec({
  
  test("returns greeting when hitting the /greeting endpoint") {
    // What goes here?
  }
})
```

edit: I also get error: "No TestContextManager defined in this coroutine context"

when trying to do this:

```
//IntegrationTest.kt

class IntegrationTest : FunSpec({

  test("returns greeting when hitting the /greeting endpoint") {
    // What goes here?
    println("The context is " + testContextManager().testContext)
  }
})
```

edit2: I'm also getting a whole bunch of errors like the below when adding the dependency of your spring extensions.
```
Unresolved reference: mockk
Unresolved reference: every
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public fun <T> Array<out TypeVariable(T)>.any(): Boolean defined in kotlin.collections
public inline fun <T> Array<out TypeVariable(T)>.any(predicate: (TypeVariable(T)) -> Boolean): Boolean defined in kotlin.collections
public fun BooleanArray.any(): Boolean defined in kotlin.collections
public inline fun BooleanArray.any(predicate: (Boolean) -> Boolean): Boolean defined in kotlin.collections
public fun ByteArray.any(): Boolean defined in kotlin.collections
public inline fun ByteArray.any(predicate: (Byte) -> Boolean): Boolean defined in kotlin.collections
public fun CharArray.any(): Boolean defined in kotlin.collections
public inline fun CharArray.any(predicate: (Char) -> Boolean): Boolean defined in kotlin.collections
public fun CharSequence.any(): Boolean defined in kotlin.text
public inline fun CharSequence.any(predicate: (Char) -> Boolean): Boolean defined in kotlin.text
public fun DoubleArray.any(): Boolean defined in kotlin.collections
public inline fun DoubleArray.any(predicate: (Double) -> Boolean): Boolean defined in kotlin.collections
public fun FloatArray.any(): Boolean defined in kotlin.collections
public inline fun FloatArray.any(predicate: (Float) -> Boolean): Boolean defined in kotlin.collections
public fun IntArray.any(): Boolean defined in kotlin.collections
public inline fun IntArray.any(predicate: (Int) -> Boolean): Boolean defined in kotlin.collections
public fun LongArray.any(): Boolean defined in kotlin.collections
public inline fun LongArray.any(predicate: (Long) -> Boolean): Boolean defined in kotlin.collections
public fun ShortArray.any(): Boolean defined in kotlin.collections
public inline fun ShortArray.any(predicate: (Short) -> Boolean): Boolean defined in kotlin.collections
public inline fun UByteArray.any(): Boolean defined in kotlin.collections
public inline fun UByteArray.any(predicate: (UByte) -> Boolean): Boolean defined in kotlin.collections
public inline fun UIntArray.any(): Boolean defined in kotlin.collections
public inline fun UIntArray.any(predicate: (UInt) -> Boolean): Boolean defined in kotlin.collections
public inline fun ULongArray.any(): Boolean defined in kotlin.collections
public inline fun ULongArray.any(predicate: (ULong) -> Boolean): Boolean defined in kotlin.collections
public inline fun UShortArray.any(): Boolean defined in kotlin.collections
public inline fun UShortArray.any(predicate: (UShort) -> Boolean): Boolean defined in kotlin.collections
public fun <T> Iterable<TypeVariable(T)>.any(): Boolean defined in kotlin.collections
```

**Comment by sksamuel** [comment]
It doesn't look like you added the kotest spring extension which is the first step in the docs.

**Comment by tomgardiner-retailx** [comment]
@sksamuel I definitely have added this
edit: it's after I add this that I'm getting all of the errors....

**Comment by sksamuel** [comment]
I need to see a complete build. For instance where are you adding the spring listener as it's not in your sample code. And your gradle file.

**Comment by tomgardiner-retailx** [comment]
Sorry what do you mean by spring listener? I'm fairly new to spring as an FYI. I can't share the build file with you as it's company code unfortunately. What info would you like?
edit: the main issue I'd like to solve is how to write integration tests using your extension, the dependency issue I can resolve on my own

**Comment by tomgardiner-retailx** [comment]
as an FYI, my gradle setup looks something like this, and I'm still having troubles:

```
//top level gradle file:

apply from: './gradle/dependencies.gradle'
apply from: './gradle/sources.gradle'

test {
    useJUnitPlatform()
}
```

```
//deps gradle file
ext {
    kotestVersion = "4.6.2"
    kotestExtensionSpringVersion = "1.0.1"
}
dependencies {
testCompile("io.kotest:kotest-runner-junit5:${kotestVersion}")
    testCompile("io.kotest:kotest-assertions-core:${kotestVersion}")
    testCompile("io.kotest:kotest-property:${kotestVersion}")
    testCompile("io.kotest.extensions:kotest-extensions-spring:${kotestExtensionSpringVersion}")
    }
````

```
//sources gradle file - which is what the error is referencing (compileTestKotlin is what is failing when running gradlew test)
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

**Comment by tomgardiner-retailx** [comment]
update: managed to fix error messages - didn't realise that I also had to import the mockk library separately. 

back to the original question:

how do I use the spring extensions library to mimic the testing behaviour I want outlined above?

**Comment by ashishkujoy** [comment]
Please check if this helps,
 https://github.com/kotest/kotest/tree/master/kotest-examples/kotest-examples-spring-webflux @tomgardiner-retailx

**Comment by tomgardiner-retailx** [comment]
@ashishkujoy thanks man. Are there any other examples I could reference?

**Comment by ashishkujoy** [comment]
I am not aware if there is any other example.

**Comment by sksamuel** [comment]
> What do I need to put for for the 'Components' import (Components::class) - there are no suggestions for importing in IDE

This is your file that defines your beans, you might not call it components in your project as you can call it anything you want. If you are working on an existing project you will need to ask someone where the file is.

In the sample project you can see its like this:

```kotlin
@Configuration
open class Components {

  @Bean
  open fun userService(repo: DefaultRepository) = UserService(repo)

  @Bean
  open fun userRepository() = DefaultRepository()
}
```

> What should my test look like?

The test you pasted looks fine, other than you didn't include the SpringExtension anywhere which I mentioned before.
Honestly, the https://github.com/kotest/kotest/tree/master/kotest-examples/kotest-examples-spring-webflux is a great resource.

> How do I fix all of the errors your extensions-spring dependency has introduced so that I can use it?

The errors you pasted up earlier were because of the missing mockk dependency which you said you've fixed now. If you have further errors, can you paste those up too.

**Comment by Kantis** [comment]
@tomgardiner-retailx I have a sample repo you can have a look in if you'd like. https://github.com/Kantis/kotest-mockk-demo

If you feel something is missing I'd be glad to add more samples.

**Comment by tomgardiner-retailx** [comment]
@sksamuel thanks for that, yeah I added the spring extension class and it's all good. I'm not getting any more errors. Do you think it's worth adding this to the documentation? This would be for both configuration file, as well as some more thorough examples.


Yes that link you shared is OKAY, however, it doesn't help explain clearly where each annotation should be used, what tests should be using said annotations etc. I know this is spring's responsibility, but because you're offering an extension - the least I would expect is a link to some further documentation. Something I found useful for the differences in config and spring annotations was: https://reflectoring.io/spring-boot-test/ .Providing examples of how to use this in conjunction with kotest can be useful for people in a similar position to me - new to spring, new to kotest, but familiar with kotlin. 


You should also make it explicitly clear in the documentation that you need to import the mockk dependency, as I looked at old posts on here and there have been a few people with exactly the same errors/issue I stumbled across. Because of the fact that you used mockk in your examples, I just assumed (fairly) that it was included with your dep

@Kantis thanks man will take a look at some stage in the next few days. I'll let you know if there's anything else I'd add

**Comment by sksamuel** [comment]
The kotest spring documentation clearly states right at the top you need the spring extension.
https://kotest.io/docs/extensions/spring.html

That's why my first comment was "you're missing the spring extension which is the first step in the docs"
