### ISSUE TITLE
Tag should have an interface it inherits and testcase config should have tagsFn 

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#2508]
A super interface for Tag would allow people to make more interesting type hierarchies with their tags. 
Also, Test case config should have a tagsFn that passes the tags from defaultTestCaseConfig and allows each test case to override.

```kotlin
typealias TagsFn = (Set<Tag>) -> Set<Tag>

val a = Tag("a")
val b = Tag("b")

test("foo").config(tagsFn = { prev -> prev - a + b })
```

**Comment by jschneidereit** [comment]
```kotlin

sealed interface MutexTag : SuperTag

fun replace(prev: Set<SuperTag>, tag: MutexTag): Set<SuperTag> {
  val old = prev..singleOrNull { it is MutexTag }
  
  if (old != null) {
    return prev - old + tag
  }
  
  return prev + tag
```

**Comment by sksamuel** [comment]
SuperTag is an awful name.
Could consider a breaking change here. If people are subclassing NamedTag as recommended then there's no break to them, and if not, it's trivial to just switch out : Tag() for : Tag

**Comment by jschneidereit** [comment]
SuperTag was just for illustrative purposes 🤣

**Comment by sksamuel** [comment]
What's the use case for the tag function?
Like when would you put tags on a parent then just override them anyway ?

**Comment by jschneidereit** [comment]
When you (soon) have a tags hierarchy and would want a test case config to override what has been placed on the tags for the class. E.g.: 

```kotlin
sealed class S : Tag // ignore name
data class A : S()
data class B : S()

// Tags per test case should only have the most recent instance of S
```

**Comment by sksamuel** [comment]
I think we can just use EngineExtensions for this now.

**Comment by sksamuel** [comment]
As for the interface, changing Tag to an interface will break things (like the toString). So I think we might just be stuck.
If you need inheritence, you could have a value inside your tag that is a sealed type.
