### ISSUE TITLE
Kotlin/Native tests print many blank lines when run through Gradle

### ISSUE THREAD

**Issue by charleskorn** [kotest/kotest#2540]
**Which version of Kotest are you using**
5.0.0.M1

When running tests with Kotlin/Native through Gradle, I see a large number of blank lines in the output, for example:

```
> Task :client:macosX64Test


























Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 52s
14 actionable tasks: 6 executed, 8 up-to-date
```

The same tests, when run with Kotlin/JVM (eg. `./gradlew jvmTest`) do not produce blank lines like this.

The number of blank lines produced seems to correlate with the number of tests - as I add more tests, I get more and more blank lines.

**Comment by sksamuel** [comment]
Fixed in master.
