### ISSUE TITLE
XML output reports not working

### ISSUE THREAD

**Issue by tomgardiner-retailx** [kotest/kotest#2544]
**Which version of Kotest are you using**
Kotest:
kotest - 4.6.2
junit-xml-extension - 4.6.2

Gradle - 6.4.1

When running a single file through intellij, using intellij's own version (not using gradle) - the output of the XML works fine. The directory contains:
```
test-results/

test-results/binary/
test-results/binary/output.bin
test-results/binary/output.bin.dx
test-results/binary/results.bin

test-result/BasicTest.xml
```

However, when running through gradle - the BasicText.xml file is not being generated. And the folder structure looks like:
```
test-results/

test-results/binary/
test-results/binary/output.bin
test-results/binary/output.bin.dx
test-results/binary/results.bin
```
Note: BasicTest.xml is no longer here

My config file is:

```
import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.listeners.Listener
import io.kotest.extensions.junitxml.JunitXmlReporter
import io.kotest.extensions.spring.SpringExtension

class FunctionalTestConfig : AbstractProjectConfig() {
  override fun extensions() = listOf(SpringExtension)
  override fun listeners(): List<Listener> = listOf(
    JunitXmlReporter(
      includeContainers = false,
      useTestPathAsName = true,
    )
  )
}
```

Troubleshooting I have tried:
1) Debugged code to confirm no exception is being thrown
2) Setting gradle config to (as suggested in related issue here: https://github.com/kotest/kotest/issues/2208):

```
reports {
        junitXml.enabled = true
        html.enabled = false
    }
```
3) Confirmed it's something specific about an action/task in gradle - due to intellij's version of gradle working correctly. I have tried using gradle on the command line AND also through intellij (using specifically gradle, rather than intellij's own version of it) with the exact same issue. 
4) Confirmed that the config is being loaded properly when it fails, as seen in output:

```
-> Extensions
  - io.kotest.extensions.spring.SpringTestExtension
  - io.kotest.spring.SpringAutowireConstructorExtension
  - io.kotest.engine.extensions.SystemPropertyTagExtension
  - io.kotest.core.extensions.RuntimeTagExtension
  - io.kotest.engine.extensions.RuntimeTagExpressionExtension
  - io.kotest.engine.extensions.SpecifiedTagsTagExtension
-> Listeners
  - io.kotest.extensions.junitxml.JunitXmlReporter
  - beforeAfterAllListener$1
```
5) Added the following to gradle config:
```
tasks.withType(Test) {
    useJUnitPlatform()
    systemProperty("gradle.build.dir", buildDir)
 }
 ```

Possible causes

1) Seems like something in gradle is overriding/locking the directory
2) This has been confirmed due to using intellij's version of gradle instead

Tagging @sksamuel

**Comment by sksamuel** [comment]
@tomgardiner-retailx did you make a typo in those paths?
They should be something like
`test-results/test/TEST-abc.xml`

When you run from intellij and it works, does it include the TEST bit ?

**Comment by sksamuel** [comment]
Closing until new information is added.
