### ISSUE TITLE
Free spec nested tests are not displaying as nested in output

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2568]
```
      "an outer context" - {
         "inner" { }
      }
```

![image](https://user-images.githubusercontent.com/743706/137139530-d1dcbe55-edae-4b69-a26e-a9eaebc4fe4a.png)

**Comment by AleksanderBrzozowski** [comment]
@sksamuel is this bug in intellij plugin or in kotest package? :)

**Comment by sksamuel** [comment]
In kotest itself. Fixed in 5.0.0.M3 and was only introduced in 5.0.0.M1.
