### ISSUE TITLE
[Discussion] Property testing ergonomics improvements

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest#2574]
### Context
Property testing in kotest relies on upfront commitment of arbs in `checkAll`, which needs to be put inside of a test. The `checkAll` function internally calls the `arb.generate` function on a given seed which is immensely useful to track down the root cause of failures. It also orchestrates shrinking, classifications, before / after prop, etc. 

While that current mechanism is simple to understand and useful, I do notice that there are still gaps when it comes to tests requiring dependent arbitraries.

A use case that I often see is the need of additional test setups which require using various arbs based on those generated values in `checkAll`. There are multiple ways that developers would do this, but one of the more popular one seemed to involve calling `arb.single()` without random seed. Note: I observed some users that are aware of the importance of random seed would figure out a way to recompute random seeds or proxy it via `arbitrary { rs -> rs }` and propagate them to these dependent setups manually. 

In https://github.com/kotest/kotest/issues/2493 Kotest 5.x enables setting up additional suspend setups via `generateArbitrary`. however, that doesn't change the fact that one would have to still install that arb inside a `checkAll` upfront.

Caveats:
- We've established that at a very high level these are already possible. There are some intricate detail that still doesn't quite work, e.g. shrinking because the dynamic nature of the lambdas.

in a nutshell:
```kotlin
// currently 
test("should test something") {
  // observe primarily the upfront commitment of arbs
  checkAll(PropTestConfig(...), arbA, arbB, arbC) { a, b, c ->
     val expected = ...
     fn(a, b, c) shouldBe expected
  }
}

// what we sort-of expected to be able to do
proptest("should test something") {  // this: PropContext 
  // prop context carries a random seed in the coroutine context
  // devs can call .value() on an arb inside of a prop context
  val result = fn(
    arbA.value()
    arbB.value()
    arbC.value()
  )
  result shouldBe ...
}

interface PropContext {
  suspend fun <A> Arb<A>.value(): A
  suspend fun randomSource(): RandomSource // this is available in the coroutine context
}
```

in addition inside of `proptest(...) { ... }` you'd also have some additional functions to configure the test itself i.e.
```kotlin
interface PropTestContext : PropContext {
  suspend fun beforeProperty(suspend fn: () -> Unit): Unit
  suspend fun afterProperty(suspend fn: () -> Unit): Unit
  suspend fun configure(suspend fn: () -> PropTestConfig): Unit
}
```

If we have this we also enable a seed-propagation via the coroutine context. This means developer all of a sudden can do something like this:
```kotlin
proptest("should propagate property-test-context") { // this: PropContext 
  val state = setup(arbParamA.value(), arbParamB.value()) 
  val expected = ...
  sut(state).doSomething() shouldBe expected
}

suspend fun setup(params...): TestState = propContext { 
  // this: PropContext - the random seed and value syntax is available here
  TestState(
    fooInStore = Arb.list(arbFoo, 1..10).value(),
    somethingElseStateful = arbXyz.value()
  )
} 
```
This is a very powerful feature because all of a sudden devs are able to do more complex aspects of property tests while still keeping those repeatable because of the propagated random seed.

### Why
We'd wish to free developers from the upfront commitment of arbs in `checkAll` and allow them to call `.value()` from within their test codes. This solves various requirements as described in the context above.

`arb.next()` and `arb.single()` are useful but unfortunately also very easy to misuse. I observe developers that weren't familiar with property testing best practices increasingly got frustrated because prop test made their tests flakey and they can't figure out why. Often times the blame was put on the test framework instead. They're not exactly wrong, kotest does "allow" users to do that. `arb.next()` is a feature that is both useful and a footgun at the same time. 

How might we find ways to make the framework assist developers to do the right thing and also make the ergonomics better? One possible alternative that comes to mind is to treat `single()` / `next()` with a warning. A rather more heavy-handed one is to only expose the non-argumented one to be called within the `propertyContext`..

Initial discussions and PR: #2529

**Comment by sksamuel** [comment]
I think that without requiring a lambda from the user, that has a specified number of inputs, we can't make shrinking work. So right now that's the final argument to checkAll. 

Without requiring this, the code path can vary, and there's no way for us to inject shrunk values into the code.

**Comment by sksamuel** [comment]
My motive for the play around code from last night was to support before and after easily for a property test, and less about new syntax for arbs. I think that having the Arb interface is useful for things like edgecases and shrinks, and so trying to skirt around that by having the .value() means you might as well just not bother with the arb strucutre at all. Just use a function that returns random values.

**Comment by myuwono** [comment]
@sksamuel yeah that's right, i know that unfortunately shrinking won't work because of the dynamic nature of the test lambda. I've noted that down in the bottom, I'll move it up to the top of the description to better highlight this.

While it is definitely not ideal, an alternative we may/may not take is to acknowledge that shrinking is not possible in dynamic prop tests, and that failure is seed-based only.

**Comment by myuwono** [comment]
The idea with `.value()` is that edgecases would also work. This is because `.value()` can call `.generate(coroutineContext[rs])`, i.e with the random seed that is propagated through.

The problem with `.next()` and `.single()` are they are very easy to misuse..

**Comment by myuwono** [comment]
On before/after property. It is currently exposed as a test listener. I think that is already great because it encourages better test structures.

**Comment by sksamuel** [comment]
> On before/after property. It is currently exposed as a test listener. I think that is already great because it encourages better test structures.

Agreed, and also the inline version I think can be useful for little shortcuts.

**Comment by sksamuel** [comment]
Here is why we always need the test function to be provided with explicit arb instances.

```kotlin
checkAll {
   val a = Arb.int().value
   val b = if (a == 0) Arb.int().value else -100
   val c = Arb.int.value()
   a + b + c shouldBe c + b + a 
}
```

In this example, when we first run it, we might just generate two arbs (a and c). Then when we shrink we might get to a point where we start to exceute a== 0 and thus use another arb. But we wouldn't know if the two shrinks we have available would be for a and b or a and c.

I don't think we'll be able to make a comprehension expression work with arbs. But we might be able to come up with something that improves the experience in another way.

**Comment by sksamuel** [comment]
@myuwono do you have a real world example of an "ugly" property test, that we can use as a motivating case to try and come up with something more elegant.

**Comment by myuwono** [comment]
@sksamuel I crafted a toy example which I believe can help illustrate some of the pain points. Note that this is not yet the worst one, but is definitely close to the slightly clunkier side of the spectrum. As you can probably see from the pattern in here, we have to test a function that has interconnected moving parts and that some parts of the expectation depends on the parameter of either the input arb(s) or the intermediate arb(s) and/or intermediate setups.  

here i "cheated" a little bit by passing through the random seed

```kotlin
checkAll(
  // create a pair of users with different ids and different userTypes
  Arb.pair(arbUser, arbUser).filter { it.first.userType != it.second.userType }, 
  arbitrary { it } // pass through the random seed so that we can call single(rs) within checkAll
) { (firstUser, secondUser), rs ->
  // given:
  
  // two separate group where the two users are located
  val firstGroup: Group = arbGroup.single(rs).copy(users = users + listOf(firstUser.id))
  val secondGroup: Group = arbGroup.single(rs).copy(users = users + listOf(secondUser.id))

  // and an arbitrary association between the two users where the directionality shouldn't matter
  val association: Association = arbAssociation(firstUser.userType, secondUser.userType)
    .single(rs)
    .copy(link = firstUser.id to secondUser.id)
  
  // when we compute the graph:
  val edges: List<Edge> = sut.computeUserGraph(
    listOf(firstUser, secondUser) + Arb.list(arbUser).single(rs), 
    listOf(firstGroup, secondGroup) + Arb.list(arbGroup).single(rs), 
    listOf(association) + Arb.list(arbAssociation(arbUserType, arbUserType)).single(rs)
  ).edges

  // then:
  // there must be two directed edges with exactly the expected modifier
  // the algorithm should compute weight as expected
  // association directionality should not matter
  edges shouldContainAll listOf(
    DirectedEdge(
      link = firstUser.id to secondUser.id,
      modifier = expectedModifier(firstUser.userType, secondUser.contributionFactor), 
      weight =  (firstGroup.size + secondGroup.size) / association.score 
    ),
    DirectedEdge(
      link = secondUser.id to firstUser.id,
      modifier = expectedModifier(secondUser.userType, firstUser.contributionFactor), 
      weight = (firstGroup.size + secondGroup.size) / association.score 
    )
  )
}

private fun expectedModifier(
  firstUserType: UserType, 
  secondUserContributionFactor: ContributionFactor
): Double = when(firstUserType) {
  UserType.Foo -> 0.7 * secondUserContributionFactor.value
  UserType.Bar -> 0.85 * secondUserContributionFactor.value
  UserType.Baz -> 0.99 * secondUserContributionFactor.value
}
```

**Comment by sksamuel** [comment]
So to summarize, here you want to flatMap over the users (so you can use the users to add them to arbGroup) but flatMap wouldn't work because you want access to the original arb as well (although I guess you could return Pair from the flapMap).

If that's correctly summarizing your example, then yeah the ergonomics are not great.
