### ISSUE TITLE
Make them clue less cheeky. Cheers!

### ISSUE THREAD

**Issue by amirabiri** [kotest/kotest#2610]
Oi! @sksamuel you cheeky wanker! Good to see you switched to Kotlin! I knew you were a smart one after all...

So we've been using your sodding `shouldBe` here for a while now, and we think it's brilliant.

Except for those damn clues. Clues give us eye pain. We don't use them. But not using them is also painful.

We was wondering if it be possible to do something 'tis like -

Instead of that bloated clue of yours

```
withClue("Name should be present") {
    user.name shouldNotBe null // Yes I changed you blasphemous 2-space indentation there and converted
                               // it to her majesty's proper 4 space indentation as God intended you infidel!
}
```

How about this?

```
user.name shouldNotBe null clue("Name should be present")
```

I believe this can be done by defining `clue` as another `infix fun` that returns a `Matcher<*>` or something equally fun. I did a quick test and Kotlin generally is fine with this bollocks. But for it to actually be workin' there needs be done something   in kotest internals like.

Nice lib BTW you twat.

And You still owe me a pint. San-Miguel please. Cheers mate!

**Comment by sksamuel** [comment]
Hey how you doing matey :)

I wish we could use 2 spaces, I use 3 on this project just to be even stranger. 4 is awful, way too much white space :)

So your syntax is nice, but the shouldNotBe (and other should*** functions) are executed first, kotlin will execute them left to right, so the exception is generated and thrown before the clue infix function would be invoked.

So 
`(user.name shouldNotBe null) <== throws before (clue("Name should be present") is executed)`

But essentially, you're just after some nicer syntax for clues....

**Comment by sksamuel** [comment]
You could do this:

`user.name shouldNotBe (null withClue "Name should be present")`

Note the parens around the rhs parameter to shouldNotBe.

**Comment by sksamuel** [comment]
Another alternative is this: https://github.com/kotest/kotest/issues/2241

Which I can get to work for nulls pretty easy. And it's nulls that are the worst right? Because currently it just says "null should not be null" or something useless.

**Comment by amirabiri** [comment]
Blimey you're right I thought infix fun is right to left.

Well in that case the solution is simple I think:

```
clue("Name should be present") user.name shouldNotBe null
```

No ?

**Comment by amirabiri** [comment]
I guess all we're doing here is removing the curly braces. Because currently we can already do this no?

```
clue("Name should be present") { user.name shouldNotBe null }
```

But you know. Some of us hate those curly braces. Don't know why. It's not rational. Humans are weird.

**Comment by amirabiri** [comment]
Oh wait you can't do that either since the RHS isn't something executable-y.

:-(

Defeat.

**Comment by sksamuel** [comment]
> I guess all we're doing here is removing the curly braces. Because currently we can already do this no?
> 
> ```
> clue("Name should be present") { user.name shouldNotBe null }
> ```
> 
> But you know. Some of us hate those curly braces. Don't know why. It's not rational. Humans are weird.

This is the best you'll get (which is just renaming withClue to clue).

I'm not sure anything can be made better here without a compiler plugin.

**Comment by amirabiri** [comment]
I think what bothered the team is that they were missing their `assert...(..., ">> message <<")` and `withClue` didn't click that it's exactly that or it just smells odd.

In the end the team opted out of `kotest` back to the `assert*(...)` family 😕 . I gave them a direct order to use `kotest` but they told me to piss off. I'm not sure they remember that I recruited all of them and that I manage this team... 😶 .

Perhaps all this is about is renaming `withClue` to `test("...") { ... }` or `assert("...") { ... }`...

**Comment by sksamuel** [comment]
The advantage of the current syntax is that a) it stacks 

```kotlin
withClue("foo") {
  // intermediate assertions
  withClue("bar") {
    // more assertions
  }
}
```

and b) it works for any assertion, not just `shouldBe`.

```kotlin
withClue("list should only contain only contain one person called amir") {
  list.forOne {
     it.name shouldBe "amir"
  }
}
```

So yeah, while `assert(a == b, "oops")` is nicer for that particular use case, you have to add that parameter to every single assertion method.
