### ISSUE TITLE
JSON Matchers Documentation Incorrect

### ISSUE THREAD

**Issue by busches** [kotest/kotest#2616]
New options were added with #2523 for JSON Matchers, which look to be a great improvement over what currently exists. The issue is that the documentation, https://kotest.io/docs/assertions/json-matchers.html, makes it look like all of these options are available, but they are not.

As someone who is fairly new to using Kotest, this was super confusing to us, until we found the above PR and realized the documentation is ahead of the released product.

1) Can we get this feature updated so the documentation is accurate
2) How can we avoid this in the future?

**Comment by sksamuel** [comment]
Should be two separate PRs, one for docs, one for feature, like you see here: https://github.com/kotest/kotest/pulls Contributors might not realize that at first, mistakes happen. Blame me for merging.

**Comment by busches** [comment]
@sksamuel that makes sense, any eta on when the next release is coming? Right now if we go forward using the old matchers, once the new version is released, we'll have a bunch of deprecated code.

**Comment by sksamuel** [comment]
You can use a 5.0 preview but 5.0 is going to be 1.6 only as it needs IR compiler plugins for JS and Native, so once 1.6 is released we're ready to release too.

We might look to release a 4.7 with some cherry pickings depending on how many people can't upgrade to 1.6.

**Comment by busches** [comment]
Ah, didn't realize `master` was 5.0 now.

**Comment by busches** [comment]
In the meantime, do we want to revert the documentation changes then?

**Comment by sksamuel** [comment]
Yes, I can revert docs unless you wanna do a PR.

**Comment by busches** [comment]
> Yes, I can revert docs unless you wanna do a PR.

I won't be able to get to it quickly, so if you can, please do. Thanks for the prompt response.
