### ISSUE TITLE
JSON Matchers does not offer "Click to see difference"

### ISSUE THREAD

**Issue by busches** [kotest/kotest#2620]
When using a JSON matcher and the assertion fails, there is no "Click to see difference" option in IntelliJ to quickly compare them.

Working example:
`401 shouldBe 402`
![image](https://user-images.githubusercontent.com/857700/140092553-1d6ecfea-9375-4522-bd2e-c8b43aaae5d8.png)

JSON Example:
`"""{"a":1}""" shouldMatchJson """{"a":2}"""`
![image](https://user-images.githubusercontent.com/857700/140092659-8cd4d4c4-c71a-480c-b32f-c96f980a75e5.png)

This is very useful when comparing larger JSON objects.

Comparing the output, it looks like the JSON example values need to be wrapped in `<X>`.

**Comment by busches** [comment]
Any chance to fix the output in 4.7 to register with intellij? The linked issue, while ideal, is a much larger lift.

**Comment by Kantis** [comment]
I'm not sure what kind of changes warrants a cherry-picked 4.7 release at this point. 5.0 is honestly not _that_ far away from what I can tell, unless JetBrains run into issues with shipping Kotlin 1.6. I guess it's up to @sksamuel 🙂

See the [milestone issue](https://github.com/kotest/kotest/issues/2226), all tagged issues are done.

**Comment by sksamuel** [comment]
1.6 rc2 doesn't seem to work either.  But I'm away til Sunday so will check
properly then.

Happy to release 4.7 with some new features from 5 or 4.6.4 with bug fixes.

**Comment by sksamuel** [comment]
Now that 5.0 is out, where are we with this issue ?

**Comment by sksamuel** [comment]
Related to https://github.com/kotest/kotest/issues/1106 ?

**Comment by busches** [comment]
@sksamuel still broken in 5.0.

![image](https://user-images.githubusercontent.com/857700/143892385-c59b7511-1eba-4344-899a-43ba12ef6ead.png)

Also broken using `"""{"a":1}""".shouldEqualJson("""{"a":2}""")`
![image](https://user-images.githubusercontent.com/857700/143892515-e5c04b65-19bf-4d74-a2ad-bed9cee265ce.png)

The json is now formatted so a bit easier to paste into a diff, but same issue of it not going automatically into intellij's diff.

**Comment by sksamuel** [comment]
@Kantis do you think the recent JSON changes broke this?

**Comment by Kantis** [comment]
Looks like it's been this way for a long while, from what I can tell.. Working on fix

**Comment by sksamuel** [comment]
@busches wanna try 5.0.1 ?

**Comment by busches** [comment]
@sksamuel still broken
![image](https://user-images.githubusercontent.com/857700/144452590-abcca70a-5672-4684-b712-1cf05937140f.png)

Also still fails on much larger compares, but thankfully it's formatted so it's not as annoying.

**Comment by Kantis** [comment]
I see what I did wrong.. new fix OTW :)
