### ISSUE TITLE
`beOneOf` doesn't tell you what value it was.

### ISSUE THREAD

**Issue by busches** [kotest/kotest#2624]
When using `beOneOf`, it doesn't tell you what it was if it's (not) in the collection.

Example:
`1 shouldBeOneOf listOf(2, 3)`

Error:
`Collection should contain the instance of value, but doesn't.`

Suggested output:
`<Value> was expected to be in the collection of <Collection>, but wasn't.`
`<Value> was not expected to be in the collection of <Collection>, but was.`

Tested against 4.6.3, but from looking at master, looks like it hasn't been changed in 5.x - https://github.com/kotest/kotest/blob/375c1a643c8b64dcec58e7db974a1c5197c395f7/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/oneof.kt#L84-L96

**Comment by busches** [comment]
Well, I think this is more my mistake as I wanted to use `beIn` at the end, which does have the nice error messages. I'll leave it up to you if you still think this makes sense.

**Comment by sksamuel** [comment]
Thanks for the idea. Updated in main branch.
