### ISSUE TITLE
BDD implies Isolation mode different from existing ones

### ISSUE THREAD

**Issue by grv87** [kotest/kotest#2629]
It's expected that `BehaviorSpec` would be isolated on `when` level:

* `given`  — an object
* `when` — an action. Since the given object could be mutable, and actions may have side effects, each of these actions should use its own object instance
* `then` — a check for the object state or the action results. Each check is free of side effects, so, no isolation is required

Current isolation modes:
* `SingleInstance` doesn't isolate anything and so can't be used
* `InstancePerLeaf` isolates `then`. So, `when` action is repeated several times, unnecessary increasing testing time
* `InstancePerTest` isolates separately `when` and each `then` and increased testing time too

So, we need another isolation mode for BDD.

**Comment by grv87** [comment]
* In Should and Expect specs `should` and `expect` are checks. So, implied isolation is on the `context` block (now missing)
* In Feature spec `scenario` is an action. `scenario` is a leaf, this style doesn't have a separate block for a check. So, `InstancePerLeaf` works correctly
* In Describe spec `it` could be both a (side effect) action or a simple check
* For free spec styles, it's maybe better to have a separate method e.g. `isolate { ... }` to specify that this block should be run isolated

**Comment by sksamuel** [comment]
The terminology that kotest uses is container and test, where container is a "parent" test, and test is a "leaf" test. This is borrowed from JUnit's terminology.

Isolation modes isolate either everything (InstancePerTest) or just leaf tests (InstancePerTest).

In BehaviorSpec, `then` is the leaf.

**Comment by grv87** [comment]
@sksamuel, let's forget about terminology for now. Does my use case look correct to you?

If not, maybe I don't understand the purpose of isolation modes?

**Comment by sksamuel** [comment]
Your use case is fine, but it just isn't the way Kotest works. I think whether something is an action or a check (using your terms) is arbitrary and I outlined how Kotest has been designed. It won't change now, as it would break everyone's code.

So to recap:

* test are nested
* leaf tests are called TestType.Test
* containers are called TestType.Container
* isolation mode either re-creates just tests, both, or neither.
