### ISSUE TITLE
Sponsorship question

### ISSUE THREAD

**Issue by gonmmarques** [kotest/kotest#2639]
Hello,

Your project is really awesome are you considering having GitHub Sponsors enabled?

Thanks in advance.

**Comment by sksamuel** [comment]
That's very generous to ask @GonMMarques but the steps required for an org make it a bit restrictive. We could setup an open source collective account, which cover expenses, but we don't have any expenses really.

Maybe make a $5 donation to a charity that means something to me. https://www.hki.org/
