### ISSUE TITLE
Arb.zip

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2644]
@myuwono do you think it's worth adding zip for Arbs ?

**Comment by myuwono** [comment]
sounds like a good idea! so am i right to think of zip similarly to `Arb.bind`? i.e. `arbA.zip(arbB, arbC, arbD) { a, b, c, d -> ... }`?

**Comment by sksamuel** [comment]
I must have been drinking because I forgot about bind.
Maybe zip is an alias for bind, I tend to think of zip as more common

**Comment by myuwono** [comment]
zip is indeed more common
