### ISSUE TITLE
Arb.string shrinking simplest character is always 'a' regardless of codepoint

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest#2646]
The offending code: https://github.com/kotest/kotest/blob/master/kotest-property/src/commonMain/kotlin/io/kotest/property/arbitrary/strings.kt#L35

but I can't really think of any deterministic way to fix it, because the lowest codepoint isn't known upfront :(

we can collect the sampled codepoints in a mutable set after the fact but it will incur a pretty noticeable runtime cost.

test to replicate this:
```kotlin
test("string shrinking should honor codepoints") {
  val arbNumeric = Arb.of(('0'..'9').map { Codepoint(it.code) })
  val samples = Arb.string(1..5, arbNumeric).generate(RandomSource.seeded(1234L))
  samples.take(1).first().shrinks.children.value.map { it.value() }.forAll { value ->
    value.shouldContainOnlyDigits()
  }
}
```

fails with:
```
The following elements passed:
519
83
1983
5198

The following elements failed:
"a1983" => "a1983" should contain only digits
"5198a" => "5198a" should contain only digits
```

**Comment by sksamuel** [comment]
We could introduce a new interface for codepoint that exposes the lowest
value ?

**Comment by sksamuel** [comment]
So I think the only way to solve this is to have:

```kotlin
interface Alphabet {
   val codepoints: List<Codepoint>
}
```

And the lowest can be the first element of that list.

(Alphabet could be replaced with CodepointSet or something).

**Comment by myuwono** [comment]
sounds good, would that be something like `Arb.string(1..20, Codepoints.alphaNumeric())` where that uses the new `Codepoints` or `Alphabet` interface? - would that be a breaking change? or should we plan through a deprecation cycle for `Arb.string(...)`?

**Comment by sksamuel** [comment]
We could deprecate one or keep both. If we do this today or tomorrow it can make 5.0

**Comment by aSemy** [comment]
Hi, I don't think the simplest codepoint has to be a specific codepoint for a given set of codepoints - one can be randomly selected when the shrinker is created.

```kotlin

/**
 * Shrinks a string. Shrunk variants will be shorter (reduced in length, until they are [minLength] in length),
 * and simplified (characters will be replaced by [simplestChar]).
 *
 * Note: by default [simplestChar] is the character "`a`". If shrinking an `Arb<String>` that does not include "`a`",
 * either provide a suitable alternative, or use the secondary constructor and provide a suitable [Codepoint] [Arb],
 * and a suitable character will be randomly selected.
 */
class StringShrinkerWithMin(
   private val minLength: Int = 0,
   private val simplestChar: Char = 'a',
) : Shrinker<String> {

   /**
    * @see StringShrinkerWithMin
    * @param[codepoints] Variants will be simplified using a random [Char] from this [Arb].
    * @param[rs] Selects an arbitrary 'simplestChar' from [codepoints] - must be seeded for repeatability
    */
   constructor(
      minLength: Int = 0,
      codepoints: Arb<Codepoint>,
      rs: RandomSource = RandomSource.seeded(minLength.toLong())
   ) : this(minLength, codepoints.next(rs).value.toChar())

// ...
```

I'm working on a PR :)
