### ISSUE TITLE
Pre-release version of Kotlin

### ISSUE THREAD

**Issue by pambrose** [kotest/kotest#2652]
When using Kotlin 1.6.0, I am getting:
`Class 'io.kotest.inspectors.InspectorsKt' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
`

**Comment by sksamuel** [comment]
You're using a 5.0 milestone ?
You need an updated kotest (which we're working on publishing, as 1.6 only just came out).

**Comment by Kantis** [comment]
I had the same issue with 5.0.0.M4, had to downgrade to 5.0.0.M3

**Comment by pambrose** [comment]
I am sorry, I am using 5.0.0.M4. 

Thanks @Kantis. I downgraded to 5.0.0.M3 and that got rid of the error.

**Comment by pambrose** [comment]
Works fine with 5.0.0.RC. 

Thanks for your efforts with kotest. It is an awesome library.

**Comment by sksamuel** [comment]
Thank you for the kind words :)
