### ISSUE TITLE
Add mutable test clock

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2655]
Would be nice if we had a fixed clock but that could be advanced manually.

**Comment by pientaa** [comment]
I can take that issue, too

**Comment by sksamuel** [comment]
Great!

**Comment by sksamuel** [comment]
its the java.time.Clock that we want to implement.

**Comment by sksamuel** [comment]
@pientaa did you still intend to do this ?

**Comment by pientaa** [comment]
@sksamuel yes, I'm sorry, I was busy recently

**Comment by sksamuel** [comment]
No problem, just wondering :)

**Comment by pientaa** [comment]
@sksamuel after looking at `java.time.Clock` I noticed that there are already implemented such classes: `OffsetClock` and `TickClock`. And they seem to be exactly what you asked for. Or maybe there is something that I missed or misunderstood?

**Comment by sksamuel** [comment]
You can't set an arbitrary value on them after creation. Unless i missed it.
