### ISSUE TITLE
kotest-assertions-klock has not been released with latest changes

### ISSUE THREAD

**Issue by dalewking** [kotest/kotest#2659]
Back in February there were a couple of PRs to klock assertions that were merged (#2116 and #2124) and shortly thereafter it was moved to its own top level repo. It does not look like those changes ever got released. I see 4.4.3 released on March 7th, the same time it was pushed to a top level repo but that does not seem to have those PRs in it.

**Comment by sksamuel** [comment]
So just coming to release this, and it looks like they've removed the ios targets from klock in the later releases.

**Comment by dalewking** [comment]
We're using the latest release 2.4.6 and it supports iOS. Why do you think it doesn't support iOS. They probably used to tell you to do a dependency in iosMain for it but it now uses the support in Kotlin 1.4 that you only have to specify the dependency in common (https://kotlinlang.org/docs/whatsnew14.html#specifying-dependencies-only-once)

**Comment by sksamuel** [comment]
Klock doesn't publish all builds on maven. You're right, ios is there. Watchos isn't or tvos. I've published all the possible targets klock supports. Let me know if I missed anything.

PS. the group is now io.kotest.extensions and the version has been reset to 1.0.0 like the other top level repos.
