### ISSUE TITLE
Snapshot badge is broken on website

### ISSUE THREAD

**Issue by TWiStErRob** [kotest/kotest#2660]
![image](https://user-images.githubusercontent.com/2906988/142736033-30c3a3df-b53a-4b6a-b5ac-d0e12144eb56.png)

I found this snippet creating it:
https://github.com/kotest/kotest/blob/5eb9b165d4588bd59952f3afc79df4d007676d6d/documentation/src/pages/index.js#L139-L143

The interesting thing is that the artifact is there:
https://oss.sonatype.org/content/repositories/snapshots/io/kotest/kotest-framework-engine/

**Comment by TWiStErRob** [comment]
Raised upstream, I think it's on their side: https://github.com/badges/shields/issues/7305

**Comment by sksamuel** [comment]
Thanks for raising the bug with them.

**Comment by sksamuel** [comment]
I've fixed the home page now.

**Comment by TWiStErRob** [comment]
For ref https://github.com/kotest/kotest/commit/f538018ee0f34c9e9719d2fef9669bc482c161fd#diff-caf9f906b16a91cb0160c50abdac8bd6db9a283fa9751f9801ef991554b46a8a

Interesting, did the URL contract change?

**Comment by sksamuel** [comment]
Not sure, just played about until it worked :)
