### ISSUE TITLE
Custom classpath is invalid

### ISSUE THREAD

**Issue by minoism** [kotest/kotest#2661]
**Which version of Kotest are you using** 4.6.3
```kotlin
  // Add the jar built by 'shadowJar' to classpath
  test {
    dependsOn(shadowJar)
    classpath += shadowJar.get().outputs.files
  }
```

It is expected that the classpath run by test should have shadowJar, but unfortunately it failed, or does kotest have another method to customize the classpath?

> I am writing a Kotlin Compiler Plugin test, for the particularity of the kotlin-compiler-embedable and kotlin-compiler, I need to redirect some package name at runtime.

**Comment by sksamuel** [comment]
Kotest should just use the classpath as configured by gradle. Gradle is launching the tests engine.

**Comment by minoism** [comment]
Sorry, I don't have a good understanding you mean, do you mean this can't do it? But I have to clarify to you that if I run with Gradle testing, everything is normal, but if I test with the IntelliJ plugin provided by Kotest, it fails.

SUCCESS:
![image](https://user-images.githubusercontent.com/58068445/142752149-31d2c5c0-6abb-47d2-b85b-0a86bb00cbd4.png)
FAILED:
![image](https://user-images.githubusercontent.com/58068445/142752161-aac4ec1f-6d6b-4dda-be8f-5547485d1573.png)

**Comment by sksamuel** [comment]
Intellij won't understand custom gradle classpaths.
Try switching execution to always use gradle.

![image](https://user-images.githubusercontent.com/743706/142785633-8ae7129c-f0af-4ab0-b9d9-e2c4341b97dc.png)

**Comment by minoism** [comment]
Yes, I'm sure this option always use Gradle. But the problem is, I run the Kotest test test here:
![image](https://user-images.githubusercontent.com/58068445/142874779-17f61a27-435e-411f-84b6-cdf4791ec333.png)
![image](https://user-images.githubusercontent.com/58068445/142874813-ff99bc46-ec18-4900-bcad-d454c927a43a.png)
They will run through Kotest's IDE Plugin

**Comment by sksamuel** [comment]
Those will always run via intellij. The green arrow at the class level
should run via gradle.

**Comment by minoism** [comment]
You are right, but it's not good to run the whole class every time, maybe there is any way to solve this special case?

**Comment by sksamuel** [comment]
Possibly make the plugin use gradle even for nested tests but that isn't
something that will be done in the short term (unless you wanted to
contribute a PR).

**Comment by minoism** [comment]
It seems interesting! I will take time to study kotest, and wait for your work. Praise!
