### ISSUE TITLE
JUnitXmlReporter gradle dependency missing

### ISSUE THREAD

**Issue by davidmoshal** [kotest/kotest#2667]
Please describe here what you would like to see documented.
The documentation alludes to using the JUnitXmlReporter:
- https://kotest.io/docs/extensions/junit_xml.html

However the dependency name for the junit and html extensions are not in the documentation

Took a bit of searching but these appear to be them:
```
io.kotest:kotest-extensions-junitxml
io.kotest:kotest-extensions-htmlreporter
```

Would be nice to put the dependencies in the documentation, actually for all gradle examples

**Comment by sksamuel** [comment]
Yeah you need `kotest-extensions:kotest-extensions-junitxml`.
I'll update docs.

**Comment by sksamuel** [comment]
Docs updated. Thanks for the heads up.
