### ISSUE TITLE
Have YAML matchers in addition to JSON matchers

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#2668]
Just like [Json Matchers](https://kotest.io/docs/assertions/json-matchers.html), we should have *Yaml* Matchers, too. While I'm aware that [kotlinx.serialization has no built-in support for YAML](https://github.com/Kotlin/kotlinx.serialization/issues/4), there is the multi-platform https://github.com/him188/yamlkt add-on for kotlinx.serialization which we could probably use.

**Comment by pientaa** [comment]
@sschuberth are you sure that using the library you mentioned is the good idea? It looks like not being supported recently. 

The alternative could be https://github.com/charleskorn/kaml, but it works only on JVM. However there is an open issue https://github.com/charleskorn/kaml/issues/232 to add other targets, too. So, wouldn't it be better to wait until that issue is done?

**Comment by sksamuel** [comment]
Let's ask @charleskorn since he uses Kotest :)

**Comment by charleskorn** [comment]
If anyone is interested in contributing support for other targets to kaml, I'd be keen to help out, but it's not high on my list of priorities at the moment unfortunately.

**Comment by sschuberth** [comment]
> @sschuberth are you sure that using the library you mentioned is the good idea?

Of course I cannot tell for *sure*. But personally I strongly prefer multiplatform Kotlin code over something that just wraps existing Java libraries.

> It looks like not being supported recently.

I'm not sure what you mean by "supported". It's open source, so if you feel that something needs to be improved, you should contribute. We cannot expect @him188 to do all the work for us.

Also, https://github.com/him188/yamlkt does not look unmaintained to me just because the last release is from August 2021; there were still commits in the last month.

**Comment by Him188** [comment]
Yes, yamlkt is indeed in support. YAML is complex to implement from the beginning, and requires a lot of work. I will continue working on it, and I appreciate anyone who wants to contribute to yamlkt.

A remind: yamlkt is still in pre-release stage. API is subject to change in the future, and yamlkt currently doesn't support all the features, like anchors. Unfortunately, I cannot guarante a specific timeline for them.

**Comment by sksamuel** [comment]
This is part of the upcoming 6.0
