### ISSUE TITLE
NoSuchMethodException eq with Arrow Assertion Extension

### ISSUE THREAD

**Issue by kieranipalmer** [kotest/kotest#2670]
**Which version of Kotest are you using**
Kotest: 5.0.0
Kotest Arrow Assertions: 1.1.0
Kotlin: 1.6.0

When using version `1.1.0` or above of `kotest-assertions-arrow`, the infix `shouldBeRight` and `shouldBeLeft` throw 
`java.lang.NoSuchMethodError: 'java.lang.Throwable io.kotest.assertions.eq.EqKt.eq$default(java.lang.Object, java.lang.Object, boolean, int, java.lang.Object)'`

**Comment by ashishkujoy** [comment]
Fix added in https://github.com/kotest/kotest-extensions-arrow/pull/98

**Comment by i-walker** [comment]
Can you check if you have this in your classpath "io.kotest:kotest-assertions-shared:5.0.0"
if not you could add it like this:
```
implementation("io.kotest:kotest-assertions-shared:5.0.0")
```

**Comment by ashishkujoy** [comment]
Even with implementation("io.kotest:kotest-assertions-shared:5.0.0") is happening.

**Comment by ashishkujoy** [comment]
@sksamuel We can release arrow assertion with this fix.

**Comment by sksamuel** [comment]
Yeah releasing 1.2.0

**Comment by i-walker** [comment]
1.2.0 is out now Thanks @sksamuel and @ashishkujoy 🙌🏾

**Comment by ashishkujoy** [comment]
Thanks @sksamuel
