### ISSUE TITLE
JS browser - Executing tests which take a long time causes Karma to time out

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#2697]
**Which version of Kotest are you using**
5.0.1

I'm getting this when running tests that take a lot of time on JS browser:

> Task :jsBrowserTest
Disconnected (0 times) reconnect failed before timeout of 2000ms (ping timeout)
java.lang.IllegalStateException: command '/home/joonas/.gradle/nodejs/node-v14.17.0-linux-x64/bin/node' exited with errors (exit code: 1)

I could just try to increase the timeout, but I think I shouldn't have to make the timeout as long as the total runtime of all my tests?

It's most likely caused by this: [https://karma-runner.github.io/5.0/config/configuration-file.html#browserdisconnecttimeout](https://karma-runner.github.io/5.0/config/configuration-file.html#browserdisconnecttimeout)

This might also be related: [https://discuss.kotlinlang.org/t/configuring-timeouts-when-running-mocha-based-tests-in-mpp-or-js-projects/16567](https://discuss.kotlinlang.org/t/configuring-timeouts-when-running-mocha-based-tests-in-mpp-or-js-projects/16567)

**Comment by sksamuel** [comment]
Kotest is supposed to be setting this timeout for you.

https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-js/src/jsTest/kotlin/io/kotest/engine/js/TimeoutTest.kt

So need to figure out why it's not working for you.

**Comment by JoonasC** [comment]
The tests which are causing this issue don't have any delays, but instead are property tests with many nested `checkAll` functions.
For example:
```kotlin
checkAll(Exhaustive.boolean()) { negateParenthesisBlock ->
            checkAll(
                Arb.shuffle(allowedCharsInOperandNames),
                Arb.shuffle(allowedCharsInOperandNames)
            ) { firstVariableNameChars, parenthesisBlockNameChars ->
                checkAll(Exhaustive.ints(1..100)) { amountOfVariablesInParenthesisBlock ->
```

**Comment by sksamuel** [comment]
Interesting, I wonder if data tests aren't resolving config correctly.
That's quite likely.

**Comment by sksamuel** [comment]
withData is picking up the defaults.
Added another test that passes.
How long are your data tests taking ? The default is 60 seconds.

**Comment by JoonasC** [comment]
The longest one takes 2 min 30s on my machine on JVM

**Comment by JoonasC** [comment]
I manually set the Karma timeout to 30 minutes using [https://kotlinlang.org/docs/js-project-setup.html#karma-configuration](https://kotlinlang.org/docs/js-project-setup.html#karma-configuration), but it didn't seem like the tests were completing and the Firefox process was taking more and more RAM as time went on

**Comment by JoonasC** [comment]
Which is weird because the tests complete on JVM.

**Comment by sksamuel** [comment]
Do you have a reproducer ?

**Comment by JoonasC** [comment]
Here's the reproducer from #2682 which I have modified so it reproduces this issue: [kotest-repro.zip](https://github.com/kotest/kotest/files/7629246/kotest-repro.zip)

**Comment by sksamuel** [comment]
Changing your test to simply:

```kotlin
   "t2" {
      while (true) {
      }
   }
```

and removing JVM exhibits the same behavior. After 37 seconds you get:
Disconnected (0 times) reconnect failed before timeout of 2000ms (ping timeout)

So I guess its something to do with karma. I googled and it seems to happy when using JS directly too.

https://github.com/karma-runner/karma-chrome-launcher/issues/218
https://github.com/karma-runner/karma-chrome-launcher/issues/196

**Comment by sksamuel** [comment]
When using mocha it will time out properly.

**Comment by JoonasC** [comment]
What do you mean with "when using mocha", to my knowledge Kotlin uses mocha by default for JS?

**Comment by sksamuel** [comment]
You were setting it to useKarma.

Try

js(IR) {
    browser {
        testTask {
           useMocha()
        }
    }
}


But Mocha doesn't give you the browser integrations perhaps.

**Comment by JoonasC** [comment]
Thanks, I'll try that

**Comment by JoonasC** [comment]
Ok, that seems to have worked. It looks like I'll have to use Mocha only then.

Should I close this or do you want to keep this open?

**Comment by sksamuel** [comment]
I guess we can close as it's not a Kotest thing.

**Comment by sksamuel** [comment]
Added these and can't seem to duplicate
https://github.com/kotest/kotest-examples-javascript/blob/master/src/jsTest/kotlin/io/kotest/examples/js/PropertyTests.kt

What happens if you run those ?
