### ISSUE TITLE
Allow setting the seed used for randomizing spec order

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2698]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by edgarvonk** [comment]
Very nice feature. I noticed this is not mentioned on https://kotest.io/docs/framework/spec-ordering.html so it's a bit hard to find it. Is it an idea to briefly document it there?

**Comment by sksamuel** [comment]
Thanks, good spot. I've updated the docs to include both random seed and custom ordering implementations
