### ISSUE TITLE
Provide a way to configure database container instance with pre-applied migration to run the tests

### ISSUE THREAD

**Issue by swanandvk** [kotest/kotest#2699]
**Example**

```
import io.kotest.core.spec.style.FunSpec
import io.kotest.extensions.testcontainers.perTest
import org.testcontainers.containers.GenericContainer

class DatabaseRepositoryTest : FunSpec({
   val redisContainer = GenericContainer<Nothing>("redis:5.0.3-alpine")
   listener(redisContainer.perTest()) //converts container to listener and registering it with Kotest.

   test("some test which assume to have redis container running") {
      //
   }
})
```

Provide a way to configure database container instance with pre-applied migration to run the tests
Each Spec can run the tests against its own individual container where the redundant migration and clean up wont be required.

**Comment by sksamuel** [comment]
Are you asking for a way to do a beforeTest on the container itself ?

**Comment by swanandvk** [comment]
> Are you asking for a way to do a beforeTest on the container itself ?
> […](#)

@sksamuel  I am thinking if we could allow defining default type of test container on parent spec via some configuration
so that container will be by default initialized when the test spec execution starts.
That will solve problem of re-defining the db container in all tests and will help in achieving parallelism.
