### ISSUE TITLE
LocalDateTime arb should accept localdatetimes as min and max

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#2704]
https://github.com/kotest/kotest/blob/a1399074597304d1bcf7e91a80469772e9cdac9f/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt#L87

The arbs for both `localDate` and `localTime` have an equal type as parameter. LocalDateTime doesn't. As a LocalDateTime is a LocalDate + LocalTime, this should not be an issue.

To fix this:
1. Deprecate `Arb.localDateTime(minYear: Int, maxYear: Int)`
2. Add `Arb.localDateTime(minLocalDateTime: LocalDateTime, maxLocalDateTime: LocalDateTime)`
3. Add tests to the new function

**Comment by pientaa** [comment]
I'd like to take that issue

**Comment by LeoColman** [comment]
Absolutely!
Don't hesitate to ask for help if you need any :)

**Comment by sksamuel** [comment]
We can keep the old one as well as the new one if we want, since it's much simpler to use if you aren't too fussy on the values.

**Comment by LeoColman** [comment]
I suggested deprecating it. Maybe keep it not deprecated?
