### ISSUE TITLE
FunSpec contexts disable all tests with test-case config in 5.0.1

### ISSUE THREAD

**Issue by Jadarma** [kotest/kotest#2710]
**Kotest 5.0.1**

When using `FunSpec` in `5.0.1`, any test that uses the `.config` within a context will be disabled, regardless of passed `enabled` parameter.
I tired to test the same behaviour with `ShouldSpec`, but it does not manifest itself there.
Reverting the Kotest version to `4.6.3` fixes this issue, perhaps it is a regression?

Minimum steps to reproduce:
```kotlin
class DisabledTest : FunSpec({
    test("Will be enabled") {}
    test("Will be enabled also").config {}
    test("Will be correctly disabled").config(enabled = false) {}
    context("A context will disable tests using test.config") {
        test("Will be enabled") {}
        test("Will be disabled, but shouldn't").config {}
        test("Will be disabled also, but shouldn't").config(enabled = true) {}
        test("Will be disabled but might be coincidental").config(enabled = false) {}
    }
})
```

**Comment by sksamuel** [comment]
Thanks for bug report, we'll get 5.0.2 out next day or so.

**Comment by sksamuel** [comment]
(Fixed in master)
