### ISSUE TITLE
Kotest-robolectric doesn't work with IsolationMode.InstancePerLeaf

### ISSUE THREAD

**Issue by SumeraMartin** [kotest/kotest#2716]
I'm using kotest version 5.0.1

When I tried to use kotest-robolectric-extensions then I've got an error from Robolectric with the following message `this method should only be called by Robolectric`. I found out that this was caused by multiple executions of the intercept method inside RobolectricExtension. Setting isolationMode to SingleInstance fixed this issue.

**Comment by sksamuel** [comment]
@LeoColman do you have any ideas ?

**Comment by LeoColman** [comment]
Definitely a bug.
I'm not completely sure if we can support anything too different from JUnit tho, as our integration with robolectric is very macgyverish and very dependant on some Robolectric's internals which are very specific to some JUnit internals.

We might support InstancePerTest and SingleInstance atm
