### ISSUE TITLE
Kotest-robolectric doesn't work locally in my project

### ISSUE THREAD

**Issue by SumeraMartin** [kotest/kotest#2717]
I'm using kotest version 5.0.1

When I tried to use kotest-robolectric-extension then I've got an error `java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.` which was caused by noninitialized Robolectric instance. I tried to copy the robolectric-extension project and run tests but everything was working fine there. I tried to change the project as much as possible to simulate my project (targetSdk, dependencies, gradle version, different module types....). Everything was still working fine in the robolectric-extension project. Then I copied `RobolectricExtension` and `ContainedRobolectricRunner` to my project and I found out that the line `spec::class.findAnnotation<RobolectricTest>()` from intercept method in the RobolectricExtension is returning a null value. When I replaced the original code with the following code then it started to work correctly. I'm not sure what's the exact problem here since I didn't have much time to examine it more.
```
val hasRobolectricAnnotation = spec::class.annotations.any { annotation ->
    annotation.annotationClass.qualifiedName == RobolectricTest::class.qualifiedName
}
if (!hasRobolectricAnnotation) {
    return execute(spec)
}
```

**Comment by jkasten2** [comment]
@SumeraMartin I tried your code above and it does solve the issue where tests would fail if `@RobolectricTest` was missing however I am seeing a different problem now.

The problem is only the first test class with `@RobolectricTest` will run, any other tests classes with this annotation are skipped silently! 
```kotlin
@RobolectricTest
@RunWith(KotestTestRunner::class)
```

After some debugging I changed the code to this to find out the root cause:
```kotlin
    fun containedBefore() {
        Thread.currentThread().contextClassLoader = sdkEnvironment.robolectricClassLoader
        try {
            super.beforeTest(sdkEnvironment, placeHolderMethod, bootStrapMethod)
        } catch (t: Throwable) {
            t.printStackTrace()
        }
    }
```

Which then showed the tests as skipped (instead of being totally missing in the test report) and gave me this stack trace:
```java
java.lang.IllegalStateException: The main Looper has already been prepared.
   at android.os.Looper.prepareMainLooper(Looper.java:93) <3 internal lines>
   at org.robolectric.shadows.ShadowPausedLooper$LooperReflector$$Reflector0.prepareMainLooper(Unknown Source)
   at org.robolectric.shadows.ShadowPausedLooper.prepareMainLooper(ShadowPausedLooper.java:272)
   at android.os.Looper.prepareMainLooper(Looper.java)
   at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:167)
   at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
   at io.kotest.extensions.robolectric.ContainedRobolectricRunner.containedBefore(ContainedRobolectricRunner.kt:31)
   at io.kotest.extensions.robolectric.RobolectricExtension.intercept(RobolectricExtension.kt:77) <17 internal lines>
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) <4 internal lines>
```

Any idea how to fix this `java.lang.IllegalStateException: The main Looper has already been prepared.` error being thrown from Robolectric?

**Comment by SumeraMartin** [comment]
I no longer use Kotest, so I can't help you with that.

**Comment by jkasten2** [comment]
I was able to fix the `java.lang.IllegalStateException: The main Looper has already been prepared.` error I was having by wrapping the `containedBefore()`, `execute(testCase)`, and `containedAfter()` in `sdkEnvironment.runOnMainThread` .
* This was something I saw [Robolectric's `SandboxTestRunner`](https://github.com/robolectric/robolectric/blob/robolectric-4.11.1/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L251) was doing but `kotest-robolectric-extension` was not.

Here are the full set of changes I made to get things working for those who might find it useful:
```kotlin
    override suspend fun intercept(
        testCase: TestCase,
        execute: suspend (TestCase) -> TestResult,
    ): TestResult {
        return try {
            runTest(testCase, execute)
        } catch (t: Throwable) {
            // Without this the whole test class will be silently be skipped
            // if something throws
            TestResult.Error(Duration.ZERO, t)
        }
    }

    private suspend fun runTest(
        testCase: TestCase,
        execute: suspend (TestCase) -> TestResult,
    ): TestResult {
        val hasRobolectricAnnotation =
            testCase.spec::class.annotations.any { annotation ->
                annotation.annotationClass.qualifiedName == RobolectricTest::class.qualifiedName
            }

        return if (hasRobolectricAnnotation) {
            runTestRobolectric(testCase, execute)
        } else {
            execute(testCase)
        }
    }

    private suspend fun runTestRobolectric(
        testCase: TestCase,
        execute: suspend (TestCase) -> TestResult,
    ): TestResult {
        val containedRobolectricRunner =
            ContainedRobolectricRunner(testCase.spec::class.getConfig())
        // sdkEnvironment.runOnMainThread is important to ensure Robolectric's
        // looper state doesn't carry over to the next test class.
        return containedRobolectricRunner.sdkEnvironment.runOnMainThread(
            Callable {
                containedRobolectricRunner.containedBefore()
                val result = runBlocking { execute(testCase) }
                containedRobolectricRunner.containedAfter()
                result
            },
        )
    }
```
