### ISSUE TITLE
Clues don't get reported for some assertions

### ISSUE THREAD

**Issue by cuchaz** [kotest/kotest#2720]
**Which version of Kotest are you using**
4.5.0

Hello,

Some assertions don't collect clue information before being thrown, so the clue information never shows up in the failure reports.

Specifically, I noticed these null-handling functions seem to bypass the clue system in my tests:

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/eq/Eq.kt#L56

I've only just glanced at the source code, but It looks like throwing Assertions directly, rather than calling the failure function, doesn't collect the clue information before it gets popped off the stack?

Those are instances I know of so far, but maybe other assertion functions that throw raw Errors could cause the same problem?

Btw, I'm a longtime Kotest user. Love your project! =D

**Comment by sksamuel** [comment]
Can you try 4.6.4 as the 4.6.x branch had some clue related fixes.

**Comment by cuchaz** [comment]
I just upgraded to 4.6.4. The problem still happens.

Thanks for looking into it.

**Comment by sksamuel** [comment]
Ok we'll take a look.

**Comment by sksamuel** [comment]
Fixed in 5.0.2
