### ISSUE TITLE
Test path filter vs whitespace in test names

### ISSUE THREAD

**Issue by iainism** [kotest/kotest#2725]
With Kotest 5.0.1 and the Kotest Plugin 1.1.49-IC-2020.3 in Android Studio, I've spotted that the test path filter fails to hit if a test name has leading or trailing whitespace.

e.g. with:
```
test(" SettingViewModel is initialised correctly") { // leading space
  // ...
}
```

If I try to execute this via the widget in the gutter (or via [ctrl]+[shift]+[F10]), I get no execution, rather, the message:

`SettingViewModel is initialised correctly is excluded by test filter: Exclude(reason=Excluded by test path filter: ' SettingViewModel is initialised correctly')`

I don't know whether this is a documentation (or Lint?) issue, or a restriction of the Kotest plugin?

**Comment by sksamuel** [comment]
My guess is something somewhere is stripping, and something else isn't.
