### ISSUE TITLE
Gradle test logging settings not respected for native targets

### ISSUE THREAD

**Issue by charleskorn** [kotest/kotest#2740]
**Which version of Kotest are you using**
5.0.3

This might just be a misunderstanding on my part... I've configured my project like this:

```kotlin
tasks.withType<Test>() {
    testLogging {
        events(TestLogEvent.FAILED, TestLogEvent.SKIPPED, TestLogEvent.PASSED, TestLogEvent.STANDARD_OUT, TestLogEvent.STANDARD_ERROR)
        showExceptions = true
        showStackTraces = true
        showCauses = true
        exceptionFormat = TestExceptionFormat.FULL
    }
}
```

If I then run [this sample project](https://github.com/charleskorn/kotest-gradle-event-logging-issue)'s tests on the JVM, I get the output I expect, with output for the passing test, failing test and output to stdout:

```
> Task :jvmTest FAILED

MyTests[jvm] > test with no output[jvm] PASSED

MyTests[jvm] > test with stdout[jvm] STANDARD_OUT
    Hello stdout

MyTests[jvm] > test with stdout[jvm] PASSED

MyTests[jvm] > test that fails[jvm] FAILED
    io.kotest.assertions.AssertionFailedError: expected:<true> but was:<false>
        at app//MyTests$1$3.invokeSuspend(Test.kt:14)
        at app//MyTests$1$3.invoke(Test.kt)
        at app//MyTests$1$3.invoke(Test.kt)

3 tests completed, 1 failed

FAILURE: Build failed with an exception.
```

However, if I run the same tests with Kotlin/Native, I only see the failing test, with no mention of the passing test and the output to stdout isn't printed:

```
> Task :macosArm64Test FAILED

MyTests.test that fails FAILED
    io.kotest.assertions.AssertionFailedError at /opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24

3 tests completed, 1 failed

FAILURE: Build failed with an exception.
```

I've confirmed that running the native executable (`./build/bin/macosArm64/debugTest/test.kexe` in my case) prints the output to stdout.

Is this not the correct way to configure this? Or is this a bug?

**Comment by sksamuel** [comment]
The testLogging is a JUnit thing, so won't have any bearing on native.
The native tests all output in the "team city" format which is picked up by intellij.
We could adapt ti to print general information too.

**Comment by charleskorn** [comment]
Interesting, I just assumed that was handled by Gradle.

If it helps, the information is definitely getting to Gradle - Gradle's HTML test report still captures the individual tests and the output in both cases, although in both cases it doesn't link the output to stdout to particular tests.

**Comment by sksamuel** [comment]
I think the kotlin gradle plugin intercepts and generates that.
It's definitely not junit platform.

**Comment by charleskorn** [comment]
Turns out this does actually work as expected - I was just configuring it wrong 🤦 

Instead of configuring all `Test` tasks, you need to configure all `AbstractTestTask` tasks:

```diff
-tasks.withType<Test>() {
+tasks.withType<AbstractTestTask>() {
```

This then works flawlessly.

**Comment by sksamuel** [comment]
Might be worth starting a FAQ page for this stuff.
