### ISSUE TITLE
Not work `js{}` and `js(BOTH){}` - only `js(IR) {}`

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#2741]
kotest: 5.0.3
Kotlin: 1.6.10
Gradle: 7.3.2

`Could not resolve io.kotest:kotest-framework-api:5.0.3`

**Comment by sksamuel** [comment]
Yes that's as expected.

From the docs:

![image](https://user-images.githubusercontent.com/743706/146681711-f8ad7cfd-47dc-4b7a-a7d8-a0f0fbe95d0b.png)

**Comment by BorzdeG** [comment]
Why? What is the reason for blocking Legacy in tests? it's just a compilation: https://kotlinlang.org/docs/js-ir-compiler.html#authoring-libraries-for-the-ir-compiler-with-backwards-compatibility

**Comment by sksamuel** [comment]
The compiler plugin uses IR specific generation:
https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-multiplatform-plugin-js/src/jvmMain/kotlin/io/kotest/framework/multiplatform/js/SpecIrGenerationExtension.kt
