### ISSUE TITLE
Test fails because lhs of shouldBe is List, and rhs is a home-grown Iterable

### ISSUE THREAD

**Issue by inquiribus** [kotest/kotest#2746]
Kotest 5.0.3

This is the continuation of [this discussion](https://app.slack.com/client/T09229ZC6/CT0G9SD7Z) started on the `Kotest` slack community

Summary: `lsh` and `rhs` of `shouldBe` for `Iterable<*>` should recognize, in addition to `Collection` and superclasses, also barebone `Iterable` implementations.

There is ambiguity as to how address type equality.  

Presently `shouldBe` makes a special case for `Set`, which is `Collection` but is not universally guaranteed to be ordered (in `Kotlin`; Set as large has no ordering guarantee whatsoever).  Other `Collection` subclasses in Kotlin are strictly ordered. From the slack thread:

> should include whatever is feasible whilst bearing in mind that you might not want this to pass:
```
listOf(1,2,3) shouldBe myIterable(1,2,3) // false
```
> [ neither this should pass ]
```
listOf(1,2,3) shouldBe setOf(1,2,3)  // false
```
The intent is, therefore, to allow
```
myIterable(1,2,3) shouldBe myOtherIterable(1,2,3) // true
```
to succeed, with as little disruption as possible to the current state of affairs, maintaining backward compatibility at large, but also introducing the privileged treatment for `Set` which should not test equal to other non-Set `Collection`

I'm preparing a pull request to address the above

**Comment by sschuberth** [comment]
~Hmm. The fix for this also seems to make `listOf(1, 2, 3) should containExactly(1, 2, 3)` fail. Is this expected?~

*Edit:* Scratch that, I cannot reproduce this anymore.

**Comment by inquiribus** [comment]
I just saw this.  Looking.

**Comment by sschuberth** [comment]
Please see my edit, I don't think anymore that there's an issue.
