### ISSUE TITLE
kotest with spring jpa insert error - Incorrect string value

### ISSUE THREAD

**Issue by jiwhunkim** [kotest/kotest#2748]
```
it("test") {
    var data = entity("가")
    entityRepository.save(data).shouldNotBeNull()
}
```
kotlin 1.6.1
kotest 4.6.4
spring extension 1.0.0

result
working properly (insert sucess)

kotlin 1.6.1
kotest 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4
spring extension 1.0.0 1.1.0

result
SQL State  : 22007
Error Code : 1366
Message    : (conn=9) **Incorrect string value**: '\xEC\xA3\xBC)\xEC\x9A...' for column 'value' at row 5

```
it("test") {
    var data = entity("a")
    entityRepository.save(data).shouldNotBeNull()
}
```

this working property 
kotest 4.6.4 ~ 5.0.4

I tried to find a solution to solve this problem but couldn't find it
There seems to be an encoding problem

**Comment by sksamuel** [comment]
This looks like you have an SQL issue, not a Kotest issue:

```
SQL State : 22007
Error Code : 1366
Message : (conn=9) Incorrect string value: '\xEC\xA3\xBC)\xEC\x9A...' for column 'value' at row 5
```

**Comment by jiwhunkim** [comment]
@sksamuel 
yes I also think sql issue but I only changed kotest version 4.6.4 -> 5.0.1 ~ 5.0.3

**Comment by sksamuel** [comment]
I wonder if the test wasn't being executed before for whatever reason?
The underlying issue looks like a unicode encoding thing with the non-ascii
chars.

**Comment by jiwhunkim** [comment]
@sksamuel 
I found a workaround.
I solved this problem by specifying the default characterset of the table.
kotest was not the problem.
We apologize for any inconvenience.
thank you.

**Comment by sksamuel** [comment]
Glad you were able to fix it.
