### ISSUE TITLE
Test Containers 4.x broken link

### ISSUE THREAD

**Issue by maxwell-carbon** [kotest/kotest#2750]
On https://kotest.io/docs/extensions/test_containers.html there's a note at the top that says:

> This documentation is for the latest release of the test containers module and is compatible with Kotest 5.0+. For earlier versions see docs **here**

which links to http://https//kotest.io/docs/extensions/test_containers_46x.html which fails. Even if you fix the obviously malformed link to https://kotest.io/docs/extensions/test_containers_46x.html that also 404s.

**Comment by sksamuel** [comment]
Thanks, fixed.
