### ISSUE TITLE
[Question] Property test Exhaustive.collection redundant due to data tests?

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#2751]
I've recently noticed that data tests and features of property tests such as `Exhaustive.collection` and `listOf().exhaustive()` do essentially the same thing.

Is there a preferred use case for both of these, or is the property test feature redundant?

**Comment by sksamuel** [comment]
You might want to use enums/other exhaustive collections in places where an arb is expected.
For example, you might want to use Arb.bind to create an instance of a data class, so you could so something like

```kotlin
Arb.bind(Arb.string, Arb.int, Exhaustive.enum<Foo>) { a,b,c -> MyDataClass(a,b,c) }
```

**Comment by JoonasC** [comment]
Ok.

Would you also advocate for mixing property and data tests, for example:
```kotlin
checkAll {
    ...
    withData() {
        ...
    }
}
```

**Comment by JoonasC** [comment]
@sksamuel ?

**Comment by sksamuel** [comment]
If you have a bunch of data, you can easily wrap it in an exhaustive, and then pass it all to the check all.

So like, `checkAll(Arb.string, listOf("mydata").exhaustive()) { a,b -> }`

**Comment by JoonasC** [comment]
Ok
