### ISSUE TITLE
Why test retries after failed result? 

### ISSUE THREAD

**Issue by Kolyall** [kotest/kotest#2754]
Config
```
@ExperimentalTime
object ProjectConfig : AbstractProjectConfig() {
    override val parallelism = 1
    override val timeout = 100.milliseconds
    override val invocationTimeout = 100.milliseconds.inWholeMilliseconds
}
```

My test failed because of "Test '#1 should...' did not complete within 100ms"
But why the test retries after failed result 6 times? 
![image](https://user-images.githubusercontent.com/3495165/147937340-53e22695-4ef4-4a8f-a1f7-3c2b768012e5.png)

**Comment by sksamuel** [comment]
What version of Kotest ?

**Comment by sksamuel** [comment]
And JVM or ... ?

**Comment by Kolyall** [comment]
kotest:5.0.3
...

classpath 'com.android.tools.build:gradle:7.0.4'

...
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

**Comment by Kolyall** [comment]
Sorry it not depends of "timeout".
It each time runs 6 times.
I do this: `Gradle-> Tasks-> verification-> Double click on "test" to run the task `

**Comment by sksamuel** [comment]
Can you upgrade to 5.0.3.
There was a race condition in earlier versions which may cause this.

**Comment by Kolyall** [comment]
I upgrade to 5.0.3.
Reproduced the same behaviour.

**Comment by Kolyall** [comment]
@sksamuel maybe you have any other suggestions?

**Comment by sksamuel** [comment]
Can you make a reproducer?
A standalone project with two dummy test that I can clone and see this behavior.

**Comment by Kolyall** [comment]
I found that:
Tests run 6 times if I run the task "test"
But If I run task "testDebugUnitTest" then Tests run 1 time correctly

**Comment by sksamuel** [comment]
If you can make the reproducer I can try to fix.

**Comment by Kolyall** [comment]
Oh.. I get it. 
Task "test" runs all test from all buildTypes : testDebugUnitTest, testReleaseUnitTest

**Comment by sksamuel** [comment]
Ahhh ok, glad you figured it out.

**Comment by Kolyall** [comment]
Oh.. I get it. 
Task "test" runs all test from all buildTypes : testDebugUnitTest, testReleaseUnitTest
