### ISSUE TITLE
Publish missing kotest-assertions-compiler binaries

### ISSUE THREAD

**Issue by bendb-instacart** [kotest/kotest#2786]
I'm attempting to use kotest 5.1.0, upgrading from 4.4.1, and building my project fails because it can't resolve `io.kotest:kotest-assertions-compiler:5.1.0`.  [Searching Maven Central](https://mvnrepository.com/artifact/io.kotest/kotest-assertions-compiler) shows that the most recent version of this artifact appears to be 5.0.0.M3.

Is this an intentional change?  If not, and it's merely an omission, would you please consider releasing up-to-date artifacts?  Thanks.

**Comment by ashishkujoy** [comment]
Hi @bendb-instacart compiler assertion and other extension like arrow, testcontainers etc are now separate code base having release cycle independent of kotest.  Below is the link for latest version of compiler assertion extension. We will update the doc with correct artifact id.

https://search.maven.org/artifact/io.kotest.extensions/kotest-assertions-compiler/1.0.0/jar

**Comment by bendb-instacart** [comment]
Heh, glad to know it's user error and I just missed the move.  Thanks for the pointer!

**Comment by ashishkujoy** [comment]
The updated document can be found here. https://kotest.io/docs/assertions/compiler-matchers.html
