### ISSUE TITLE
Add option to automatically advance time

### ISSUE THREAD

**Issue by ghasemdev** [kotest/kotest#2797]
Hi, I wanted to know if there is a way to use `config` method or `AbstractProjectConfig` for skip delay in test, such as the `runTest` function that currently exists in Kotlin 1.6.0 and replaced for `runBlockingTest` , and runs tests quickly.

```Kotiln
describe("score") {
    it("start as zero") {
        delay(5.hours) // This test run in 5 hours 😂
    }
}
```

```Kotiln
describe("score") {
    it("start as zero") {
        runTest {
            delay(5.hours) // Run without consider delay
        }
    }
}
```
**I like this way and `runTest` behavior exist in `it` function**
```Kotiln
describe("score") {
    it("start as zero") {
        delay(5.hours)
    }
}
```

**Comment by sksamuel** [comment]
Is this what you're looking for ? https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html

**Comment by ghasemdev** [comment]
> Is this what you're looking for ? https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html

I try that but doesn't work. also I enabled testCoroutineDispatcher in AbstractProjectConfig

```kotlin
object Kotest : AbstractProjectConfig() {

    override var testCoroutineDispatcher = true
    override val coroutineDebugProbes = true

    override fun extensions(): List<Extension> = listOf(TimerListener)
}
```
My dependencies

```kotlin
// Kotest
testImplementation("io.kotest:kotest-assertions-core:5.1.0")
testImplementation("io.kotest:kotest-property:5.1.0")
testImplementation("io.kotest:kotest-runner-junit5:5.1.0")

// Reflection
testImplementation("org.jetbrains.kotlin:kotlin-reflect:1.6.10")
```

and my test

```kotlin
class MyTests : DescribeSpec({

    beforeEach { println("Hello from $it") }
    afterEach { println("Goodbye from $it") }

    describe("score") {
        it("start as zero") {
            delay(5.hours)
        }

        describe("with a strike") {
            it("adds ten") {}
            it("carries strike to the next frame") {}
        }

        describe("for the opposite team") {
            it("Should negate one score") {}
        }
    }
})
```
But no skip behavior for delay

**Comment by sksamuel** [comment]
Where are you using the advance methods in that example ?

**Comment by sksamuel** [comment]
@ghasemdev Can you reply - you need to call the advance methods to make 5.hours skip.

**Comment by ghasemdev** [comment]
> @ghasemdev Can you reply - you need to call the advance methods to make 5.hours skip.

Which one? I can't find or use them.

**Comment by sksamuel** [comment]
I've refreshed the docs. https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html
And this might help https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/
You have to call advanceTimeBy to move the clock on. It won't just skip delays automatically.

**Comment by ghasemdev** [comment]
> I've refreshed the docs. https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html
> And this might help https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/
> You have to call advanceTimeBy to move the clock on. It won't just skip delays automatically.

Thanks, but I mean `run Test` use under the hood is better way to skip delays automatically. Because usually we test suspend method and we can't use `advanced TimeBy`.

**Comment by sksamuel** [comment]
I see. Then we need another option that provides this automatic "skip all delays" like what runTest is doing.

**Comment by lgtout** [comment]
@sksamuel @ghasemdev 
Is a change to Kotest necessary?
After all, this has the same effect:
(Using StringSpec)
```
"""myTest""" {
    runTest {
        val elapsed = TimeSource.Monotonic.measureTime {
            val deferred = async {
                delay(5_000) // will be skipped
            }
            deferred.await()
        }
        println(elapsed) // about 15ms on my machine
    }
}
```

**Comment by sksamuel** [comment]
What is `runTest` in this case ? @lgtout

**Comment by lgtout** [comment]
@sksamuel It's [this](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html) - provides virtual time when testing coroutines.
