### ISSUE TITLE
Kotest should respect engine name in junit platform launcher

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2806]
_I have a test suite that uses multiple junit engines, and when i run tests by uniqueId kotest also runs tests even when the uniqueId clearly states a different engine than kotest. [engine:failgood]/[class:...]/[class:...]
I think kotest should just run no tests when the uniqueid selector is used with a different engine._

https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1643716624167609

**Comment by christophsturm** [comment]
thanks for creating this ticket!
we are currently using 4.6.3 because we haven't upgraded to kotlin 1.6 yet.
