### ISSUE TITLE
kotest-assertions-arrow > 1.0.3 import with Maven

### ISSUE THREAD

**Issue by brunoteo** [kotest/kotest#2808]
**Which version of Kotest are you using**
Kotest: 5.1.0
Kotlin: 1.6.10
Arrow: 1.0.0

Hi,
when I try to upgrade kotest-assertions-arrow from 1.0.3 to one of the next releases with Maven, I can't find anymore the package from kotest-assertions-arrow.

Here what I have with 1.0.3 into the Maven Dependency Tree:
![image](https://user-images.githubusercontent.com/7426747/152010392-fed0b619-e486-4d4d-a572-ef4ab8a935e0.png)

Here what I have if I tried one of the next release:
![image (1)](https://user-images.githubusercontent.com/7426747/152010474-5df0ac6a-59c9-4045-b5e5-caf1c2453d54.png)

I've tried to setup a project with Gradle and it works.

Can you help me?

Thanks

**Comment by sksamuel** [comment]
Can you show the maven snippet for that dependency.

**Comment by brunoteo** [comment]
Here the snippet. I have created a small project to reproduce the problem

```
<dependencies>
        <dependency>
            <groupId>io.kotest.extensions</groupId>
            <artifactId>kotest-assertions-arrow</artifactId>
            <version>1.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-runner-junit5-jvm</artifactId>
            <version>5.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-assertions-core-jvm</artifactId>
            <version>5.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.6.10</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>1.6.10</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

Looking at the library I have only that metadata:
![image (2)](https://user-images.githubusercontent.com/7426747/152012004-0b027c4e-5099-47e0-b730-fef5f8a95721.png)

**Comment by sksamuel** [comment]
You might need to use kotest-assertions-arrow-jvm since it is now a multiplatform project and maven doesn't understand that.

**Comment by brunoteo** [comment]
ok thank you it works! I didn't find anywhere that part for the new releases.

Have a good day!
