### ISSUE TITLE
The latest versions of Kotest and kotest-extensions-pitest don't work together

### ISSUE THREAD

**Issue by RusticFlare** [kotest/kotest#2810]
**Which version of Kotest are you using**
5.1.0

I've made https://github.com/kotest/kotest-extensions-pitest/pull/1 to hopefully help

**Comment by sksamuel** [comment]
Thanks, I've added some comments on how to get the tests to pass.

**Comment by RusticFlare** [comment]
Thank you! Tests are passing 😄

**Comment by sksamuel** [comment]
1.1.0 released of the pitest plugin.
