### ISSUE TITLE
kotest-assertions-ktor and ktor 2.0

### ISSUE THREAD

**Issue by pbit** [kotest/kotest#2813]
I am preparing a project for the comming ktor version 2.0 and want to update ktor-assertions-ktor.

While the matchers are easy to migrate there are some questions about the project.

One of the main changes is the restructuring of module and packages. 
So the change is not just an update, its a new extension.
Both versions should be independent available for the user to choose.   

- kotest-assertions-ktor
- kotest-assertions-ktor2

This can be handled in the existing repository using subprojects.

Using subprojects would allow more specialized artifacts and matchers to choose from (like kotest-extensions-arrow)

- http
- client
- server
- ...

The repository name is kotest-assertions-ktor, other repositories use the kotest-extenion-* pattern.
Are there some rules for the naming or is it just 'historical' stuff?  

If you want contributions for this I coud work on it.

**Comment by sksamuel** [comment]
I think the name is partly historical, partly because kotest-extensions is used for things that aren't purely assertions.

Is ktor changing significantly that we need a new package? I ask partly because of kotest and partly because I use ktor extensively at work.

**Comment by pbit** [comment]
They did a heavy cleanup on artifacts and packages.
For example ktor-client-* and ktor-server-* use bot ktor-http-* 
This makes it much easier to write shared code used on client and server.

see: [Migrating from 1.6.x to 2.0.0](https://ktor.io/docs/eap/migrating-2.html)

I expect that many projects will stay on ktor-1 some may even use both versions while migrating.
Having two artifacts would allow you to choose one - or even both to test the migration.

**Comment by sksamuel** [comment]
I think a separate extensions project makes sense. 

kotest-extensions-ktor2

**Comment by pbit** [comment]
Ok, I will try to setup a project over the weekend
