### ISSUE TITLE
5.02 hides console output during test.

### ISSUE THREAD

**Issue by hemfridsvagen25** [kotest/kotest#2820]
Kotlin version 1.6.10
Starting on Kotest verion 5.02 console output is no longer visible during run.

Easiest example is setting a breakpoint on the row after a print statement.
Output after test is complete also appears below the test result instead of above as earlier.

**Comment by sksamuel** [comment]
Can you try 5.1.0 just to make sure it's still happening on latest version.

**Comment by hemfridsvagen25** [comment]
Yeas it happens on 5.1.0 as well. I discovered it there and downgraded until it worked. So last working version is 5.0.1

**Comment by sksamuel** [comment]
I can't seem to duplicate this. Eg with this test

![image](https://user-images.githubusercontent.com/743706/158039190-34e1557d-1989-434c-a5e1-644cd6558e8e.png)


I get this 
![image](https://user-images.githubusercontent.com/743706/158039205-dd59b6aa-5583-4329-ac96-afef9ab22375.png)

Clicking on a test shows the output associated with that test.

**Comment by hemfridsvagen25** [comment]
Hi
If you use this test below.  Run only test 2 in debug mode with a break point on the second print. And look at the console when paused at breakpoint you should see test 1.0 in the console.  in 5.01 it works but in 5.02 and later the console is empty until test is finished. 

class KotestTest:StringSpec() {
	init {
		"1" {
			println("test 1")
		}
		"2" {
			println("test 1.0")
			println("test 1.1")
			println("test 1.2")
		}
		"3" {
			println("test 3")
		}
	}
}

**Comment by sksamuel** [comment]
still struggling to duplicate. Will keep trying.

**Comment by hemfridsvagen25** [comment]
Hi after upgrade of IntelliJ to IntelliJ IDEA 2021.3.3  The problem has vanished.
Now everything seems to work as expected again.

**Comment by sksamuel** [comment]
Ok so must have been an intellij bug, good to know!.
