### ISSUE TITLE
Timing issues with Koin and Testcontainers

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#2824]
I have a Koin module which creates an instance of a client class based on system properties. One of the system properties depends on the dynamically mapped port that testcontainers assigns. I have tried to set the system properties in a beforeSpec block, but the Koin instance gets created before the beforeSpec block runs. How can I ensure that I am able to run code after the container has started but before Koin is instantiated?

**Comment by JoonasC** [comment]
Any ideas @sksamuel?

**Comment by sksamuel** [comment]
Can you give an example of what you would want to happen ?

**Comment by JoonasC** [comment]
Let's I have a client such as:
```kotlin
class Client(val host: String, val port: Int) {
...
}
```

Which I instantiate in a Koin module:
```kotlin
val clientModule = module {
    single {
        Client(System.getProperty("host")!!, System.getProperty("port")!!)
    }
}
```

And then I have a test class:
```kotlin
class Test: StringSpec(), KoinTest {
  override fun extensions() = listOf(KoinExtension(clientNodule))
}
```

**Comment by JoonasC** [comment]
Let's say I have a client such as:
```kotlin
class Client(val host: String, val port: Int) {
...
}
```

Which I instantiate in a Koin module:
```kotlin
val clientModule = module {
    single {
        Client(System.getProperty("host")!!, System.getProperty("port")?.toInt()!!)
    }
}
```

And then I have a test class:
```kotlin
class Test: StringSpec(), KoinTest {
    override fun extensions() = listOf(KoinExtension(clientModule))

    val client: Client by inject()

    init {
        val container = install(TestContainerExtension("server:version")) {
            withExposedPorts(75)
        }

        "test" {
            client.doSomething()
        }
    }
}
```

Attempting to set the system properties in a before spec block doesn't work because the Koin module gets initialized before it is called:
```kotlin
beforeSpec {
    System.setProperty("host", container.getHost())
    System.setProperty("port", container.getMappedPort(75))
}
```

How can I set the system properties after the container has started but before Koin initializes the client?

**Comment by sksamuel** [comment]
So the clientModule code is being executed straight away, because it's a val.
What we could do is make the koin extension support lazy setup.

For now, I would copy the extension https://github.com/kotest/kotest-extensions-koin/blob/master/src/commonMain/kotlin/io.kotest.koin/KoinExtension.kt and just make it setup your module in the intercept method.

**Comment by JoonasC** [comment]
Ok, thanks for the tip. I guess you can add a feature request tag then?

**Comment by JoonasC** [comment]
Btw, what exactly do you mean with "setting up a module"?

**Comment by sksamuel** [comment]
Yep, we can add that new feature.

For your 2nd question, move this code:

```kotlin
val clientModule = module {
    single {
        Client(System.getProperty("host")!!, System.getProperty("port")?.toInt()!!)
    }
}
```

inside the intercept method of the copy n paste extension.

**Comment by JoonasC** [comment]
Ok,  thanks.
