### ISSUE TITLE
docs about Conditional tests with Gradle are wrong

### ISSUE THREAD

**Issue by dobe** [kotest/kotest#2826]
hi!

at https://kotest.io/docs/framework/conditional/conditional-tests-with-gradle.html#kotest-specific-test-filtering the statements do not work, since an equal sign is missing. e.g:

```shell
gradle test -Dkotest.filter.specs 'com.somepackage.*'
```

should become:

```shell
gradle test -Dkotest.filter.specs='com.somepackage.*'
```

also the documented approach does not work because gradle (at least in v7.x) does not pass on system props to the test JVM  (see the discussion [here](https://stackoverflow.com/questions/21406265/how-to-give-system-property-to-my-test-via-gradle-and-d/21406600)). so at least some (not mentioned) gradle config tweaking is necessary to pass the system properties.

seeing this, i think it would actually be nice if kotest would use environment variables instead of system properties, since those are  passed automatically.

**Comment by sksamuel** [comment]
You can't pass the env vars in the command line as far as I know? So you would need to set them, then run. The problem with gradle not passing system properties is annoying.

**Comment by dobe** [comment]
calling the tests would work this way

```shell
KOTEST_FILTER_SPECS='com.somepackage.*' gradle test
```

 at least on *nix based systems

**Comment by sksamuel** [comment]
with export you mean ?

**Comment by sksamuel** [comment]
I've updated those docs.

**Comment by sksamuel** [comment]
And we already support them as env vars so I've added that to the docs as well.

**Comment by dobe** [comment]
see https://stackoverflow.com/questions/41183403/passing-environment-variables-to-a-process

**Comment by sksamuel** [comment]
Good to know.
