### ISSUE TITLE
Support annotation spec for JS tests

### ISSUE THREAD

**Issue by SerVB** [kotest/kotest#2832]
I see from the [documentation](https://kotest.io/docs/quickstart) that not all styles are supported for JS:

> Tests for Javascript cannot nest tests. This is due to the underlying Javascript test runners (such as Mocha or Karma) not supporting promises in parent tests, which is incompatible with coroutines and in Kotest every test scope is a coroutine. This is why the supported specs are limited to FunSpec, ShouldSpec and StringSpec.

![image](https://user-images.githubusercontent.com/20105593/154257587-e8fdfc59-899f-4193-b1bb-b8f1cec8f769.png)

The default kotlin.test for JS uses annotations but kotest doesn't support annotation spec for JS.

Is there any reason why? Looks quite similar. Would be handy to have annotation spec available when switching from kotlin.test to kotest.

**Comment by SerVB** [comment]
Still actual

**Comment by SerVB** [comment]
Still actual

**Comment by Kantis** [comment]
Think this could be a candidate for 6.0 @sksamuel ?

**Comment by sksamuel** [comment]
We'd need to see if annotations are available at runtime in JS land. They
might not be.

**Comment by sksamuel** [comment]
This won't be added to Kotest because we'd have to build a new compiler plugin to look for annotations vs the existing one.
