### ISSUE TITLE
Running Gradle `test` task doesn't propagate exceptions as test failures

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [kotest/kotest#2841]
Android project.
Gradle config:

Gradle version 7.2
Android Gradle plugin version 7.1.1
Kotlin version 1.6.10

```
tasks.withType(Test::class.java) { testTask ->
    testTask.useJUnitPlatform()
}

dependencies {
    val kotestVersion = "5.1.0"
    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-property:$kotestVersion")
    testImplementation("io.kotest.extensions:kotest-extensions-koin:1.1.0")
}
```

Running from Android Studio "Run test" gutter icon (with Kotest IntelliJ plugin installed) fails the test correctly by throwing an exception, as there are not mocked Android classes used in `LightColorTemperatureViewModel` under test:

```
android/graphics/Color
java.lang.NoClassDefFoundError: android/graphics/Color
	at com.myapp.uicomponents.colorlight.LightColorTemperatureViewModel$1.<init>(LightColorTemperatureViewModel.kt)
	at com.myapp.uicomponents.colorlight.LightColorTemperatureViewModel$1.<clinit>(LightColorTemperatureViewModel.kt)
	at com.myapp.uicomponents.colorlight.LightColorTemperatureViewModel.<init>(LightColorTemperatureViewModel.kt:81)
	at com.myapp.uicomponents.colorlight.LightColorTemperatureViewModelKotest$1$1$1.invokeSuspend(LightColorTemperatureViewModelKotest.kt:87)
```

Running the Gradle `test` task passes the same test!

```
./gradlew :myapp:uicomponents:color-light-detail:testDevDebug --tests LightColorTemperatureViewModelKotest

> Task :myapp:uicomponents:color-light-detail:testDevDebugUnitTest

com.myapp.uicomponents.colorlight.LightColorTemperatureViewModelKotest > when initial light values have temperature then emit correct light values PASSED

BUILD SUCCESSFUL in 10s
```

I could reproduce it with both `StringSpec` and `FunSpec`.

**Comment by lukasz-kalnik-gcx** [comment]
If I provide mocks for the Android dependencies, but make the test fail in some other way, e.g. by adding

```
0 shouldBe 1
```

then the failure is propagated correctly both when running the test using Gradle task as well as by clicking on the "Run test" icon.

**Comment by sksamuel** [comment]
Might be something to do with how android tests are setup with gradle
source sets

**Comment by lukaszkalnik** [comment]
Just to be clear: these are not instrumented Android tests. These are pure JVM unit tests. Only the classes under test have (in production code) some Android dependencies like this:

```
import android.graphics.color

class LightColorViewModel(
    val rgbToColorConverter: (Int, Int, Int) -> Int = Color::rgbToColor // this is the Android dependency
)
```

In tests I replace this Android dependency with a mocked function. However if I forget to replace it, the tests should fail with an exception because Android framework is not accessible in tests.

**Comment by sksamuel** [comment]
If it's not android but just uses an android dep, can you make a standalone
project that fails for us to take a look at ?

**Comment by lukasz-kalnik-gcx** [comment]
I have tried to create a minimum reproducible project, but then I don't observe this problem anymore... So there might be some more complex interdependencies at play.

**Comment by lukasz-kalnik-gcx** [comment]
I will get back to you if I see the problem again and can describe it in more detail. For now I will just close this issue.

**Comment by sksamuel** [comment]
Ok cool
