### ISSUE TITLE
Expose coroutines `TestDispatcher` inside the test

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [kotest/kotest#2842]
We usually inject a coroutines Dispatcher into our ViewModels:

```
class ViewModel(
    val coroutineContext: CoroutineContext = Dispatchers.Default
) {
    private val coroutineScope = viewModelScope + coroutineContext
    private val api: Api by inject()

    init {
        coroutineScope.launch {
            api.getUser()
            // ...
        }
    }
}
```

With coroutines 1.6, we test it like this:

```
class ViewModelTest : KoinTest {
    private val testScope = TestScope()
    private lateinit var api: Api

    @BeforeEach
    fun setUp() {
        api = mockk<Api> {
            every { getUser() } returns User(id = "123")
        }
    }

    @Test
    fun `api is called on init`() = testScope.runTest {
        val viewModel = ViewModel(testScope.coroutineContext)

        coVerify { api.getUser() } 
    }
}
```

This way the dispatcher used inside the `ViewModel` under test is directly connected to the `testScope` and any unfinished coroutines etc. will get reported as test failures.

Is it possible to achieve something like this with Kotest?

**Comment by sksamuel** [comment]
Does this help ? https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html

**Comment by lukasz-kalnik-gcx** [comment]
Unfortunately not, I already had a look at this.
The problem is I need a `TestScope` or `TestDispatcher` instance *inside* of the test body.
Setting `config(testCoroutineDispatcher = true)` only gives access to the `testCoroutineScheduler` inside the test, not the dispatcher.

**Comment by sksamuel** [comment]
You can always get the dispatcher inside any coroutine as it's in the
context.

**Comment by lukasz-kalnik-gcx** [comment]
Ok, I will try this. Thank you for your help!

**Comment by sksamuel** [comment]
Did you get this figured out ?

**Comment by lukasz-kalnik-gcx** [comment]
No, unfortunately we didn't migrate our project to kotest yet, but thanks for asking. I will close this issue.
