### ISSUE TITLE
Discrepancy in the documentation for @Tags annotation

### ISSUE THREAD

**Issue by YSakhno** [kotest/kotest#2843]
The current documentation [specifies](https://kotest.io/docs/framework/tags.html#marking-specs) that annotation `@Tags` receives a list of tag objects/classes (at least that what it looks in the examples). But [in the source code for version 5.1.0](https://github.com/kotest/kotest/blob/v5.1.0/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/annotation/Tags.kt) that annotation expects a list of `String`s.

This defeats the purpose of having tags as objects, and also removes the ability to quickly navigate to documentation for those tags listed as `String`s (you cannot click on a string in an IDE and navigate to the tag's declaration). Of course, no checking is done at compile time on the actual _existence_ of a tag when it is specified as a string either.

**Comment by sksamuel** [comment]
I think annotations can only include primitives and strings.

**Comment by sksamuel** [comment]
I have improved the docs for tags, thanks for the heads up.
