### ISSUE TITLE
defaultTestConfig deprecation

### ISSUE THREAD

**Issue by LimmaPaulus** [kotest/kotest#2844]
Hi!

I personally disagree with the decision to deprecate defaultTestConfig/defaultTestCaseConfig()

```kotlin
@Deprecated("These settings should be specified individually to provide finer grain control. Deprecated since 5.0")
open fun defaultTestCaseConfig(): TestCaseConfig? = null
```

I think it doesn't hurt to allow users to configure tests on coarse grain. Giving more options to user is a good thing on API like this.

My use case is that I have several integration tests I cannot run frequently because there are costs and rate limits associated with integrated services. I have decided to not run these tests on CI but only occasionally on my local machine (maybe not the best practice but haven't yet invented better). I control the execution of these tests with environmental variables. Currently, I have several test classes which are completely excluded in the "normal" test run. I don't see any benefit to configure dozens of tests cases individually instead of just switching off these classes completely.

**Comment by sksamuel** [comment]
Would tags achieve the same thing ?
Annotate those classes with an @ExpensiveTest tag and exclude those by default ?

**Comment by sksamuel** [comment]
https://kotest.io/docs/framework/tags.html

**Comment by LimmaPaulus** [comment]
Yes, this seems sufficient. I still see no reason to remove that another option, but that's not problem for me any longer.
