### ISSUE TITLE
shouldThrowWithMessage

### ISSUE THREAD

**Issue by nkiesel** [kotest/kotest#2847]
We often have tests where we expect a specific exception with a specific message to be thrown.  We currently use
```kotlin
    inline fun <reified T : Throwable> shouldThrowWithMessage(message: String, block: () -> Any?) {
        shouldThrow<T>(block).message shouldBe message
    }
```
I wonder if there is a better way or if this could be added to the standard matchers.

**Comment by sksamuel** [comment]
Happy to add another one.
I sometimes do

shouldThrow<Foo> { }.message.shouldBe("msg")

**Comment by pientaa** [comment]
I'll take that issue

**Comment by nkiesel** [comment]
Thanks!
