### ISSUE TITLE
FreeSpec seems to work with `-` in Leaf Tests

### ISSUE THREAD

**Issue by JesusMcCloud** [kotest/kotest#2848]
**Which version of Kotest are you using** 5.1.0

**Which version of Gradle are you using** 7.1.1

**Which version of Kotlin are you using** 1.6.10

FreeSpec tests work perfectly fine, even if the leaf tests contain an infix minus between the string and the lambda.<br>Why is this working?

Some more background: I was butting my head as to which test style to use in a project which involves multiple people in order to ensure that data-driven tests may never silently be discarded (only after I realised that I messed up myself).
Now the quick "fix" seems to mandate FreeSpec as project convention and just always use a dash/minus after the test name.

**Comment by sksamuel** [comment]
Kotest won't force you to "finish" the tests by having a non-minus leaf test.
I guess an option could be added to force that, but are you having an issue? In 5.x you shouldn't see data driven tests discarded, can you show an example of that ?

**Comment by JesusMcCloud** [comment]
To clarify: data-driven tests (`withData`) in non-minus leaf tests are silently discarded.

Everything is working fine and I do understand why it makes sense to distinguish between containers and tests (`before{Container,Each,Any}`, report generation, etc…), but the _FreeSpec_ docs are a bit unclear in this respect, since the implications of only using containers are not clearly communicated (as me creating this issue proves).

**Comment by sksamuel** [comment]
Do you have an example test?

**Comment by sksamuel** [comment]
So the issue was that we shouldn't allow withData inside leaf's at all, but it was binding to RootScope.
I've fixed that now, so you shouldn't see data test disappear.

**Comment by amccague** [comment]
> Kotest won't force you to "finish" the tests by having a non-minus leaf test. I guess an option could be added to force that.

I was looking for an issue that might discuss this, I have users that report forgetting to omit the `-` on a leaf. In practice the container fails if an assertion does but if it passes then the feedback starts to lack.

I was considering contributing it like `failOnEmptyContainer` - an equivalent to https://kotest.io/docs/framework/fail-on-empty-test-suite.html WDYT?

**Comment by amccague** [comment]
@sksamuel 

> Kotest won't force you to "finish" the tests by having a non-minus leaf test. I guess an option could be added to force that.

I was looking for an issue that might discuss this, I have users that report forgetting to omit the `-` on a leaf. In practice the container fails if an assertion does but if it passes then the feedback starts to lack.

I was considering contributing it like `failOnEmptyContainer` - an equivalent to https://kotest.io/docs/framework/fail-on-empty-test-suite.html WDYT?

**Comment by sksamuel** [comment]
Yeah I like that idea !
