### ISSUE TITLE
Add `CharSequence` matchers similar to Collection<*> matchers

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#2857]
Our collection matchers `forAll`, `forNone`, `checkAll` and others don't include `Charsequence`. It's only a type issue, as `CharSequence !is Collection<Char>`

The current workaround for this is turning your strings into lists via `toList`:

```
val string = "MyString"

val charList: List<Char> = string.toList()

charList.forAll { }

```

However, I do feel we should be able to just do:

```
val string = "MyString"

string.forAll { ... }

```

We've done similar compatibility changes for `Array`, `Sequence`, `Set`, having the matchers for each type, so this one should be justified.

### Use case:

My particular use case was matching that none of the chars in a string broke a specific property. Adding `toList` is an easy workaround, but at the same time, why do it?

**Comment by pientaa** [comment]
I'll implement it

**Comment by sksamuel** [comment]
awesome @pientaa
