### ISSUE TITLE
Type-specific `should`

### ISSUE THREAD

**Issue by spadger** [kotest/kotest#2858]
Hi,

(Verified with kotest 5.1.0 on JVM)

I don't know if this is even possible, but it could be useful to have an infix operator similar to `shouldBe` which doesn't allow upcasting?

e.g. 
* Make the compiler force me to ensure my 2 types are the same
* Stop me accidentally asserting `a.b.c.SomeEnum.SAME_VALUE shouldBe x.y.z.SomeEnum.SAME_VALUE`

☝️  The second point was entirely my fault, and what prompted this issue report

![Screenshot saying Expected: MODERATED, Actual: Moderated](https://user-images.githubusercontent.com/216748/157015416-81a36065-84da-4784-bff6-74bc336a89c5.png)

Ideally, in the screenshot below, `T` should be `Int`, but it is being upcast to `Any`
![Screenshot of type alias T being upcast to Any](https://user-images.githubusercontent.com/216748/157022162-f4c0468d-dae8-4fef-b5a0-47e84dd424dc.png)

**Comment by aSemy** [comment]
Hi, what do you think about using `shouldBeEqualToComparingFields` or `shouldBeEqualComparingTo`?

```kotlin
    1 shouldBeEqualComparingTo "asd" // ❌ Type mismatch.
    1 shouldBeEqualComparingTo 2 // compiles ✅
```

**Comment by spadger** [comment]
Umm, yep, works for me! Works for enums too. Thanks!
```
SomeEnum.ITEM_A shouldBeEqualComparingTo SomeEnum.ITEM_B // compiles ✅
SomeEnum.ITEM_A shouldBeEqualComparingTo DifferentEnum.ITEM_B // ❌ Type mismatch.
```
