### ISSUE TITLE
Combine multiple generators with an even distribution

### ISSUE THREAD

**Issue by CharlesG-Branch** [kotest/kotest#2865]
Consider something like this:
```
val foobar = listOf(
    Arb.negativeLong(),
    ....,
).reduce { acc, gen ->  
    acc.merge(gen)
}
```
Because of the way that the `merge` function is written earlier generators in the list will be exponentially less likely to be called. I've dealt with this in my own project with the following function:
```
fun <T> List<Gen<T>>.mergeAllGen(): Arb<T> = object : Arb<T>() {
    private val arbs = this@mergeAllGen.filterIsInstance<Arb<T>>()

    override fun edgecase(rs: RandomSource): T? =
        arbs.random(rs.random).edgecase(rs)

    override fun sample(rs: RandomSource): Sample<T> =
        when (val gen = this@mergeAllGen.random(rs.random)) {
            is Arb -> gen.sample(rs)
            is Exhaustive -> gen.toArb().sample(rs)
        }
}
```

If you run this sample you can see the impact is quite dramatic:
```
val sample = listOf(
    Arb.double(),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant("hello"),
)
println(sample.reduce { acc, gen -> acc.merge(gen) }.edgecases())
println(sample.mergeAllGen().edgecases())
```

I'm happy to add this + update the docs if there is a template PR I can go off of.

**Comment by sksamuel** [comment]
Without looking at the original, can you tl;dr on why it favors the earlier gens ?

**Comment by myuwono** [comment]
@CharlesG-Branch there is also `Arb.choice` that you might be interested to check out. Maybe the mergeAll function can just be an alias for that function

**Comment by sksamuel** [comment]
I'm not seeing the issue, I've added this test and it's ok.

      test("merge should distribute equally") {
         val ints = Arb.constant(0).merge(Arb.constant(1)).take(10000).toList()
         val zeros: Int = ints.count { it == 0 }
         val ones: Int = ints.count { it == 1 }
         val diff: Int = abs(zeros - ones)
         diff.shouldBeLessThan(500)
      }

Merge will pick equally between two arbs, but if one arb has more values then the other, you'll see more repeats in the smaller one.

**Comment by myuwono** [comment]
@sksamuel i think this only happens as soon as you chain merge arbs one after the other, i.e. `arbA.merge(arbB).merge(arbC)`. That's because as we evenly split left arb vs right arb, probabilistically we'll get 25% a, 25% b, and 50% c.

**Comment by sksamuel** [comment]
Oh I see, yes. That's exactly what we do.

**Comment by myuwono** [comment]
@CharlesG-Branch do you mind trying this? see if that's closer to the result that you'd expect?
```kotlin
val arbMerged = Arb.choice(
    Arb.double(),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant(0L),
    Arb.constant("hello"),
)
```

**Comment by CharlesG-Branch** [comment]
@myuwono That works for me. No need imho to add a `mergeAll` alias — maybe just add a note in the `merge` docs about if you're using it in a chain consider using `Arb.choice`.

I missed this because in the docs I assumed that [Generators List](https://kotest.io/docs/proptest/property-test-generators-list.html) referred to generating discrete things (e.g. strings, doubles, enums, etc) and that [Generator Operations](https://kotest.io/docs/proptest/generator-operations.html) would include "meta" generators. I see now that the first link has combinatorics.

**Comment by myuwono** [comment]
I see yes that's a good idea. I'll make that clear in the readme accordingly.
