### ISSUE TITLE
DslMarker not propagating properly in IDEA builds test tree incorrectly

### ISSUE THREAD

**Issue by BorzdeG** [kotest/kotest#2878]
kotest: 5.2.1
kotest plugin: 1.1.49-IC-213-EAP-SNAPSHOT
IDEA: 2021.3.2

The test starts through GRADLE run Configuration

sample code:
```kotlin
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.datatest.withData
import io.kotest.matchers.shouldBe

class DemoTest : DescribeSpec() {
	init {
		describe("desc - 0") {
			it("it - 0") {
				withData(
					1 to 1,
					1 to 2
				) { (x, y) ->
					x shouldBe y
				}
			}
		}
	}
}
```

![image](https://user-images.githubusercontent.com/2332528/158444640-1fbcd907-38dc-4082-9a44-e563df670052.png)

**Comment by sksamuel** [comment]
You can only put withData inside containers, so it's binding to the
describe level.
This is a bug in the sense that you shouldn't be able to create a test like
that.

**Comment by sksamuel** [comment]
This is giving an error in 5.2.1 now.
Can you confirm @BorzdeG

**Comment by BorzdeG** [comment]
@sksamuel Yes, the error persists. Published a demo project: https://github.com/BorzdeG/bugs-kotest-2878

**Comment by sksamuel** [comment]
It must be fixed in master because I can't duplicate.

![image](https://user-images.githubusercontent.com/743706/160309513-b5b34e7a-ddc4-412b-9fcb-65b29cc969c9.png)

I am going to release 5.2.2 so we can try against that.

**Comment by BorzdeG** [comment]
Upgrading the versions didn't fix the problem. Updated repository

**Comment by sksamuel** [comment]
@BorzdeG I have played with your repo and I don't understand.
The same test in kotest shows the red build. Inside your repo it's green.
The versions are identical and the code is the same.

**Comment by BorzdeG** [comment]
The problem seems to be in how the test report is generated: `build/test-results/test/TEST-demo.DemoTest.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="demo.DemoTest" tests="3" skipped="0" failures="1" errors="0" timestamp="2022-05-03T05:34:57" hostname="borz-mac.local" time="0.231">
  <properties/>
  <testcase name="(1, 1)" classname="demo.DemoTest" time="0.03"/>
  <testcase name="(1, 2)" classname="demo.DemoTest" time="0.003">
    <failure message="io.kotest.assertions.AssertionFailedError: expected:&lt;2&gt; but was:&lt;1&gt;" type="io.kotest.assertions.AssertionFailedError">io.kotest.assertions.AssertionFailedError: expected:&lt;2&gt; but was:&lt;1&gt;
	CUT_OUT
</failure>
  </testcase>
  <testcase name="it - 0" classname="demo.DemoTest" time="0.635"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```
