### ISSUE TITLE
shouldContainExactly should work with TreeSet

### ISSUE THREAD

**Issue by maxwell-carbon** [kotest/kotest#2879]
If you call `treeSet shouldContainExactly listOf("a", "b")`, that should work, but currently blows up[1] because Kotest doesn't treat TreeSets as ordered sets ([source](https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/eq/IterableEq.kt#L63)). They probably should be -- they have a consistent iteration order.

Side note, this issue was tricky to debug because the toString representation of the expected and actual values were identical, forcing me to step through the execution with a debugger.

Also, I believe this was previously working in Kotest 4.x.

**Which version of Kotest are you using**

5.1.0.

[1] Exception is thrown here: https://github.com/kotest/kotest/blob/45df11acd0310877af75eb5229b79bcaba2922ce/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/eq/IterableEq.kt#L71

**Comment by maxwell-carbon** [comment]
Internally there's an error message

```
Disallowed: Set can be compared only to Set
May not compare TreeSet with ArrayList
```
which would have helped, but the `containExactly` method discards that and generates its own unhelpful error message: https://github.com/kotest/kotest/blob/45df11acd0310877af75eb5229b79bcaba2922ce/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/containExactly.kt#L47

**Comment by Kantis** [comment]
Thanks for the excellent report @maxwell-carbon 😃
