### ISSUE TITLE
Global configuration for eventually

### ISSUE THREAD

**Issue by muellerml** [kotest/kotest#2891]
In our project we have a BDD test setup with Cucumber and kotest which performs some REST calls on our applications testing asynchronous behaviour. As the default timeout of 25 milliseconds for REST calls is quite low, we have to configure at each invocation of eventually the same delays again and again as there's no global configuration possibility. This sometimes even lead to networking issues as the request rate can be quite high, if we don't increase the delay.

Would it be possible to expose the default config for eventually via an Object that can be easily updated per test-suite?

**Comment by sksamuel** [comment]
Yeah I think that makes sense.

**Comment by muellerml** [comment]
In https://github.com/muellerml/kotest/commit/3042dcff026a809c413050da19876f89a5afe657 I added such an object. Would that already be enough or should a test be added as well?

I also thought about adding the possibility to configure those configuration values via System properties or similar but I guess at least for the interval property it's not straightforward to support all variations.

**Comment by Kantis** [comment]
Is the global object approach safe for parallelism?

**Comment by muellerml** [comment]
You are probably right that it would lead to problems with Kotlin/Native implementations/usages. I also receive the warning "With old Native GC, variable in singleton without @ThreadLocal can't be changed after initialization" from Kotlin plugin in IntelliJ.

Thanks for the hint, but now I have no idea how my initial issue would be solvable with the current structure of kotest.

**Comment by Kantis** [comment]
@muellerml a lot of project-wide/global configuration is performed using [AbstractProjectConfig](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt). Perhaps it can be extended with config for eventually?

**Comment by sksamuel** [comment]
Eventually is part of the assertions module, and project config is only for the test framework.

It might be nice to have options in project config that eventually could _optionally_ look at though.

**Comment by sksamuel** [comment]
What about allowing eventually to be configured via a data class.

`eventually(options) { }`

A tiny bit more work than just `eventually { }` that uses global options, but allows multiple configurations per project, and avoids any memory race conditions.

**Comment by muellerml** [comment]
A configuration via data class would definitely improve the situation on our side, although we still would need to ensure that the data class is everywhere used correctly.
However, this might be possible via linting and we could work around the kotest framework constraints that way.
