### ISSUE TITLE
Composable matchers for primitives

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2894]
Seeing https://github.com/kotest/kotest/issues/2845

Perhaps we could also extend it for composing primitive and collection matchers? In those cases, omitting extraction functions would be fine.

like: 
```kotlin
Matcher.compose<Int>(
  beLessThan(5),
  beEven()
)

Matcher.compose<String>(
 startsWith("John")
 endsWith("Doe")
)

Matcher.compose<List<*>>(
   haveLength(5),
   containInOrder(1, 2, 3)
)
```

What do you think?

**Comment by sksamuel** [comment]
Yep I think that's great.

**Comment by Kantis** [comment]
I just noticed that matcher's have `and` and `or` methods for composing like this 🙈
