### ISSUE TITLE
Support OS annotations in annotation spec

### ISSUE THREAD

**Issue by Avvessalom** [kotest/kotest#2898]
Hello. 
JUnit5 has an annotation for running tests under different operating systems

```jave
@EnabledOnOs({OS.WINDOWS, OS.MAC})
```
I would like to have the same possibility when using the Kotest annotation spec

**Comment by sksamuel** [comment]
There is `@EnabledIf` you can add to a spec.
https://kotest.io/docs/framework/conditional/spec-annotations-conditional-evaluation.html

Then if you want the OS constants, you can bring in apache commons lang which provides those.
