### ISSUE TITLE
Remove wrapping quotes from diff 

### ISSUE THREAD

**Issue by brizzbuzz** [kotest/kotest#2901]
Hey, can't thank you guys enough for all the work that has gone into Kotest.  

This is a pretty small bug, but I know at least for me the QoL improvement would be pretty huge.  

At the moment, when one compares a diff in Intellij, the result (for strings) gets wrapped in a set of quotes like so

<img width="871" alt="Screen Shot 2022-01-30 at 8 42 37 AM" src="https://user-images.githubusercontent.com/5607577/151702289-37ad22db-0696-4888-b927-22701a55d2fc.png">

This makes copying the result pretty cumbersome, as quite often you simply want to lift the entire diff out for some nice copy-pasta action.

**Comment by sksamuel** [comment]
Hmmm that might be nicer.
We do it so it's obvious when you have this:

`"1" shouldBe 1`

and it fails, you get

```
expected:<1> but was:<"1">
Expected :1
Actual   :"1"
```

![image](https://user-images.githubusercontent.com/743706/166119853-5c90d4fb-c26a-4640-9be2-70a3144ee692.png)

**Comment by sksamuel** [comment]
Without it, intellij gets confused and does this:

![image](https://user-images.githubusercontent.com/743706/166120251-452f6064-a44a-4e5c-9448-8420f69b3952.png)
