### ISSUE TITLE
Override parallelism in ProjectConfig cause Mockk setup coEvery failed

### ISSUE THREAD

**Issue by aids61517** [kotest/kotest#2905]
**Which version of Kotest are you using**
Kotest : 5.2.1 (Exception happened Kotest 5, but 4.6.3 is fine.)
MockK : 1.12.1 ~ 1.12.3 (haven't tested on old version)

I upgrade Kotest version from 4.6.3 in my Android project, and CI always failed.

After lots of testing, I found override `parallelism` in `ProjectConfig` is root cause. If `parallelism` greater than 1, `coEvery` would failed with lots of test cases.

Here is error message and a [demo repository](https://github.com/aids61517/KotestMockErrorDemo)
![image](https://user-images.githubusercontent.com/15688437/160540128-77325ce4-cf05-441d-9bc9-85235ff92fe9.png)

Test with ` ./gradlew test` on terminal or `testDebugUnitTest` in gradle tool
![image](https://user-images.githubusercontent.com/15688437/160540370-307fdc69-2153-49e0-865f-95be87469e89.png)

**Comment by sksamuel** [comment]
@LeoColman you used mockk a lot, do you know if it needs some setting to work properly when in parallel ?

**Comment by LeoColman** [comment]
Usually when mockk starts being an issue I disable everything else. I try to keep mocking to the least I can.

What I would try to do first is to set the isolation mode to InstancePerTest, if it's not already that way
