### ISSUE TITLE
Change documentations to recommend by default a `KotestConfig` instead of `ProjectConfig`

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#2910]
https://github.com/kotest/kotest/blob/f1c729d7de1150d30ee1806fe354887ce80777cd/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt#L29

### Small bugfix in KDocs
First, `AbstractProjectConfig` must be instantiated, therefore this must be changed to

`: AbstractProjectConfig()`

### Change in KDocs
For the line
https://github.com/kotest/kotest/blob/f1c729d7de1150d30ee1806fe354887ce80777cd/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/config/AbstractProjectConfig.kt#L29

We should change it to `KotestConfig`

### Change in docs

I think it's ok to keep `io.kotest.*.AbstractProjectConfig` as our class, but recommending the users to call it `KotestConfig` or `KotestProjectConfig` is more intuitive than looking at the root of the test package and seeing `ProjectConfig`

I think the only file that needs to be changed is 
https://github.com/kotest/kotest/blob/master/documentation/docs/framework/project_config.md

### Breaking changes

None. This is a documentation only change/discussion

**Comment by nor-ek** [comment]
Assign me

**Comment by nor-ek** [comment]
PR ->  https://github.com/kotest/kotest/pull/2918
