### ISSUE TITLE
Pitest fails to run Junit5/Kotest tests because it assigns unique id selectors

### ISSUE THREAD

**Issue by ffeltrinelli** [kotest/kotest#2913]
**Which version of Kotest are you using**
I'm upgrading kotest from 5.1.0 (where it works fine) to 5.2.2 (where I have the error described below).

**Description**

In #2862, kotest was updated to throw an exception if tests running with `kotest` engine have a unique id selector.

Unfortunately, this is exactly what [Pitest](http://pitest.org/) is doing:

```
PIT >> INFO : MINION : org.pitest.util.PitError: TestEngine with ID 'kotest' failed to discover tests
PIT >> FINE : MINION :      at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
PIT >> FINE : MINION :      at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
PIT >> FINE : MINION :      at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:88)
PIT >> FINE : MINION : Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
PIT >> FINE : MINION :      at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
PIT >> FINE : MINION :      at org.pitest.junit5.JUnit5TestUnit.execute(JUnit5TestUnit.java:88)
PIT >> FINE : MINION :      at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:49)
PIT >> FINE : MINION :      at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
PIT >> INFO : MINION :      at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
PIT >> FINE : MINION :      at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
PIT >> INFO : MINION :      at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
PIT >> FINE : MINION :      at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
PIT >> FINE : MINION :      at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:49)
PIT >> INFO : MINION :      at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:88)
PIT >> FINE : MINION :      ... 1 more
PIT >> FINE : MINION : Caused by: java.lang.RuntimeException: Kotest does not allow running tests via uniqueId
PIT >> INFO : MINION :      at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:119)
```

As you can see, `org.pitest.junit5.JUnit5TestUnit` [is actually assigning unique id selectors](https://github.com/pitest/pitest-junit5-plugin/blob/6b686f5f559e9306ea12cd58a9a1750b1b21f7f2/src/main/java/org/pitest/junit5/JUnit5TestUnit.java#L52).

Is there a way kotest can avoid this breaking behavior, at least when is run by Pitest?
Thanks in advance!

**Comment by sksamuel** [comment]
Are you using Pitest with junit5 and kotest mixed ?

**Comment by ffeltrinelli** [comment]
> Are you using Pitest with junit5 and kotest mixed ?

Yes, I'm using the [standard JVM/Maven setup](https://kotest.io/docs/quickstart#test-framework), with `maven-surefire-plugin` and `kotest-runner-junit5-jvm`, in which Kotest uses Junit5 as runner.

**Comment by sksamuel** [comment]
Right, but are you using JUnit tests in addition to Kotest tests ?
Because Pitest shouldn't be sending over the uniqueId with an engine selector of Kotest as that's not supported. I don't know where org.pitest.junit5.JUnit5TestUnit is coming into play ?

**Comment by ffeltrinelli** [comment]
Pitest is running with the [pitest-junit5-plugin](https://github.com/pitest/pitest-junit5-plugin) Maven plugin.
I don't have Junit5 tests, only Kotest tests.
My understanding is that Junit5 is used as the underlying runner both from the point of view of Kotest and Pitest.

**Comment by sksamuel** [comment]
Junit 5 is both a platform and a test engine.

Can you try the kotest pitest extension and not the junit one?

**Comment by ffeltrinelli** [comment]
I guess you are referring to this one: https://kotest.io/docs/extensions/pitest.html .
Thanks, I wasn't aware of it!

Looking at its docs, I'm having some difficulties to understand how to set it up with Maven.

As regards all the Pitest configurations, should I keep using the [Maven Pitest plugin](https://pitest.org/quickstart/maven/) (but without pitest-junit5-plugin), like this:

```
<plugin>
    <groupId>org.pitest</groupId>
    <artifactId>pitest-maven</artifactId>
    <version>1.7.6</version>
    <configuration>
        <targetClasses>...</targetClasses>
        <avoidCallsTo>...</avoidCallsTo>
        <coverageThreshold>...</coverageThreshold>
        ...        
    </configuration>
</plugin>
```

and then just adding the Pitest Kotest extension as dependency, like this:

```
<dependencies>
  ... the other dependencies on Kotest ... 
  <dependency>
    <groupId>io.kotest.extensions</groupId>
    <artifactId>kotest-extensions-pitest</artifactId>
    <version>1.1.0</version>
    <scope>test</scope>
  </dependency>
</dependencies>
```

?

**Comment by sksamuel** [comment]
That seems about right, just add the kotest pitest extension as a normal test dependency and configure it in kotest.

**Comment by ffeltrinelli** [comment]
Ok thanks a lot! I'll try it and report back here.

**Comment by ffeltrinelli** [comment]
It works like a charm, thanks! It even reduced the overall Pitest execution time of ~ 3x factor!

By the way, I didn't have to "configure it in kotest", the changes in the Maven pom.xml that I highlighted in my previous comment were enough.

The only drawback is that now I started having a lot of `PIT >> WARNING : Minion exited abnormally due to TIMED_OUT` logs, I didn't have any of these before. But they don't seem to harm, the final outcome of the PIT execution seems to be the same as before. Do you know what these warnings could be related to? Thanks again.

**Comment by ffeltrinelli** [comment]
I raised #2955 to improve the Pitest extension docs for Maven users :-)
