### ISSUE TITLE
Provide multiplatform implementations of `captureStandardOut`

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#2914]
I'm writing some tests using [Knit](https://github.com/Kotlin/kotlinx-knit/), and I'd like it to generate tests to work on as many platforms as possible 

Because Knit works best by showing and testing examples that use `println(...)`, the tests need to be able to capture stdout. 

There's a way of capturing stdout on JVM:

https://github.com/kotest/kotest/blob/b832d4941ecc45074bcd6dea3f24d16553f2fc21/kotest-extensions/src/jvmMain/kotlin/io/kotest/extensions/system/wireListeners.kt#L10-L23

Can the same method be made available on the Kotlin JS and Kotlin Native platforms?

Here's a StackOverflow question with answers of how to do this on Kotlin Native https://stackoverflow.com/q/57123836/4161471. I couldn't find any Kotlin JS examples, but it looks fairly simple in plain JS https://stackoverflow.com/q/9216441/4161471

**Comment by sksamuel** [comment]
Using those links you provided, we should be able to make captureStandardOut multiplatform.

**Comment by sksamuel** [comment]
The native implementation looks completed.

**Comment by vdshb** [comment]
Is it correct, that this issue was just staled and never implemented? I believe it's still a valid enhancement proposal.
