### ISSUE TITLE
Docs examples use null-safe accessors for matchers, which produces false positives in some situations

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#2917]
The docs have examples that use the null-safe accessor `?.`

https://kotest.io/docs/assertions/json-matchers.html#shouldcontainjsonkey

https://github.com/kotest/kotest/blob/b832d4941ecc45074bcd6dea3f24d16553f2fc21/doc/matchers/json.md?plain=1#L8

If the `json` variable is null then the assertion won't be called. I think that's a bit confusing to beginners, the docs probably shouldn't use null-safe accessors.

For example:

```kotlin
val responseBody: String? = null
responseBody?.shouldMatchJson("[1, 2, 3, 4]") // this assertion is never triggered
```

### Suggestion 

Change all the docs to remove `?.` from the call where it is not needed, or might be confusing

```markdown
`str.shouldMatchJson(json?)`
```

I didn't do a full search, I just saw this one page had many examples. All the docs should be checked.

### Additional points

1. Maybe the extension functions should be changed to extend nullable types? In this instance it would be correct to say "`null` doesn't contain the provided json"
2. Can the Kotest IntelliJ plugin provide an inspection to warn about "assertion might not be triggered"?

#### See also

> I’ve noticed some matcher functions handle nullable variables but other’s don’t ~ https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1640084172325700

**Comment by sksamuel** [comment]
I've removed remaining examples of this.
