### ISSUE TITLE
Support automatic binding of Enums 

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2937]
It would be nice if the property framework automatically bound enum types when generating arbs for data classes. Currently we have to manually provide the enum arb.

This gets very tedious with large structures containing many enums. :) 

## Current
```kotlin
enum class Suit { Diamonds, Clubs, Hearts, Spades }

data class Card(
  val symbol: String,
  val suit: Suit,
)

val card = Arb.bind<Card>(providedArbs = mapOf(Suit::class to Arb.enum<Suit>()).next()
```

## Desired
```kotlin
enum class Suit { Diamonds, Clubs, Hearts, Spades }

data class Card(
  val symbol: String,
  val suit: Suit,
)

val card = Arb.bind<Card>().next()
```

**Comment by sksamuel** [comment]
Yep seems like an oversight to not include that.
