### ISSUE TITLE
Create a SLF4J-compatible logging extension, which can be used to sniff logs 

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2942]
```kotlin
class MyTest : FunSpec(
  {
    val logs = install(LogSniffer) { minLevel = Level.INFO }

    test("check that logs are on correct level and contains id") {
       logs.forOne {
         it.level shouldBe Level.WARN
         it.message shouldContain "myId"
      }
    }
  }
)
```

Do you think it's worth adding as an extension (`kotest-extensions-logging`?)?

**Comment by jschneidereit** [comment]
There's [built in logging](https://github.com/kotest/kotest/blob/master/documentation/docs/framework/logging.md), all one needs to do is implement a `LogExtension` and wire it up to their chosen logging framework. 

Edit: after re-reading the original comment, perhaps I don't understand

**Comment by Kantis** [comment]
@jschneidereit i meant to monitor the logs of the production code. :) 

for instance:

```kotlin
class Greeter {
  fun sayHello(name: String) {
    if (name.startsWith("jim")) { logger.warn("Jim was here") }
    println("Hello $name")
  }

  companion object {
    val logger = LoggerFactory.getLogger(Greeter::class.java)
  }
}
```

test:
```kotlin
test("Warns when jim is here") {
   Greeter().sayHello("jim")
   logs.forOne {
     it.level shouldBe Level.WARN
   }
}
```

**Comment by jschneidereit** [comment]
Oh that's pretty cool 😎

**Comment by sksamuel** [comment]
I think this would be awesome.

**Comment by Kantis** [comment]
This turned out to be tedious as hell. 

SLF4J didn't provide any ways of intercepting logs. I tried writing a new SLF4J implementation which would record the logs, but realized later that it will clash with whatever other logging implementation is present on the classpath..

I think the most pragmatic way forward would be to limit this to adding support for Logback for now (seems to be widely used).

**Comment by sksamuel** [comment]
What about just saying this was a good idea that didn't work out :)

**Comment by sksamuel** [comment]
Can prob just file this under good idea and close it.
