### ISSUE TITLE
Inconsistent lifecycle hooks

### ISSUE THREAD

**Issue by obecker** [kotest/kotest#2959]
I'm using kotest 5.3.0

While understanding the available lifecycle hooks I experienced same unexpected behavior, which I believe should be fixed/improved.

Consider this example:
```kotlin
class LifecycleTest : DescribeSpec({

    describe("Lifecycles") {
        beforeContainer {
            println("beforeContainer")
        }
        afterContainer {
            println("afterContainer")
        }
        beforeEach {
            println("beforeEach")
        }
        afterEach {
            println("afterEach")
        }
        beforeSpec {
            println("beforeSpec")
        }
        afterSpec {
            println("afterSpec")
        }
        it("runs the test") {
            println("test")
        }
    }
})
```

Running this test prints
```
beforeEach
test
afterEach
afterSpec
```

1. Apparently `afterSpec` is called, but `beforeSpec` is not. I have seen the discussion in https://github.com/kotest/kotest/issues/2792, so I'm not sure if the pair `beforeSpec`/`afterSpec` should be called within a `describe` or not, but in any case it should be called consistently (both or none).
2. `beforeContainer`/`afterContainer` are not called (but they will be called when used on the top level). If this is intended then using these methods within `describe` should be an error (ideally a compile error, but a runtime error would work for me, too). The same would be true if `beforeSpec`/`afterSpec` must no be used within `describe`.

**Comment by sksamuel** [comment]
Some good observations thank you. 
1.I think beforeSpec should be forbidden inside any context, as the spec already exists at that point so makes no sense.
2. I think the beforeContainer semantics are that they are called on nested containers inside that container. We should clarify this. If what you want is just some code to run inside _that_ container, then just have code there. There some some chatter about this on this thread: https://github.com/kotest/kotest/issues/2792

**Comment by obecker** [comment]
Thanks for the clarification on `beforeContainer` - makes sense!
