### ISSUE TITLE
Add JsonSchema array support for minItems, maxItems

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2961]
See reference: https://json-schema.org/understanding-json-schema/reference/array.html#length

It should be possible to define a schema like:

```kotlin
jsonSchema {
  array(minItems = 2, maxItems = 100) { string() } 
}
```

**Comment by nor-ek** [comment]
can assign me

**Comment by nor-ek** [comment]
@Kantis PR https://github.com/kotest/kotest/pull/2974

I noticed such information in `schema.md`
```
Note that Kotest only supports a subset of JSON schema currently. Currently missing support for:

$defs and $refs
Recursive schemas
Parsing of schema composition
string.format
array.prefixItems,
array.contains,
array.items = false
array.maxContains
array.minContains
array.uniqueItems
enum
```
Can I work on them?

**Comment by Kantis** [comment]
Sure! Please split into smaller tasks,  raise an issue and write something short about how you're thinking to proceed and we can take it from there? 😃 thanks for helping out! 🙌

**Comment by nor-ek** [comment]
Done:
- https://github.com/kotest/kotest/issues/2979
- https://github.com/kotest/kotest/issues/2978
- https://github.com/kotest/kotest/issues/2977
- https://github.com/kotest/kotest/issues/2980 - not sure about this example if it's fine

**Comment by sksamuel** [comment]
@Kantis is this just waiting on https://github.com/kotest/kotest/issues/2961 ?

**Comment by sksamuel** [comment]
What's the latest with this one ?

**Comment by Kantis** [comment]
Sorry, the last item was closed with https://github.com/kotest/kotest/pull/3026 . All done ✅
