### ISSUE TITLE
shouldBeEqualToComparingFields and recursivity

### ISSUE THREAD

**Issue by PHaroZ** [kotest/kotest#2964]
Hi,

Since https://github.com/kotest/kotest/pull/2833 `shouldBeEqualToComparingFields` is recursive until a prop come from a packge with a name that starts with `java` or `kotlin`.
I understand that, in some case, this could be an improvment, but in some others this leads to breaking/incompatible changes.

An example :
```kotlin
import io.mockk.mockk

data class Organization(val aComplexObject: Any)
data class User(val name:String, val org:Organization)

val org : Organization = mockk()
User(name="foo", org=org) shouldBeEqualToComparingFields User(name="foo", org=org)
```
Now fails because `org.aComplexObject` is not mocked and the recursive comparision try to call it instead of relying on `org.equals`.

Is it possible to have a param to configure this recursivity (or a way to configure packages that could stop the recursivity ?) or another non recursive method ?

A the moment I use a workaround lilke that :
```kotlin
import io.kotest.matchers.equality.shouldBeEqualToUsingFields
import kotlin.reflect.KVisibility
import kotlin.reflect.full.memberProperties
import kotlin.reflect.jvm.isAccessible
import kotlin.reflect.jvm.javaField

infix fun <T : Any> T.shouldBeEqualToComparingFieldsLvl1(other: T) {
	val fields = this::class.memberProperties
		.asSequence()
		.onEach { it.isAccessible = true }
		.filter { it.javaField != null && it.visibility != KVisibility.PRIVATE }
		.sortedBy { it.name }
		.toList()
	shouldBeEqualToUsingFields(other, *fields.toTypedArray())
}
```
But it's not very clean to reproduce the logic contains in `io/kotest/matchers/equality/reflection.kt`.

Thanks for your work :+1:

**Comment by ashishkujoy** [comment]
PR added https://github.com/kotest/kotest/pull/3034

**Comment by ashishkujoy** [comment]
Fixed in master will available with next release.
