### ISSUE TITLE
Can't Install Intellij Plugin

### ISSUE THREAD

**Issue by veluxer62** [kotest/kotest#2965]
When I intall kotest plugin in Intallij IDEA, there is an error message as below

```
Plugin "Kotest" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'Kotest' (version '1.1.50-IC-2020.1') is not compatible with the current version of the IDE, because it requires build 201.* or older but the current build is IU-221.5080.210
```

<img width="973" alt="image" src="https://user-images.githubusercontent.com/59301541/167629810-0628a449-c948-4d60-9914-d36a0cf4499d.png">

Intellij version: `IntelliJ IDEA 2022.1 (Ultimate Edition)`

**Comment by kkann-allegro** [comment]
I managed to install it by downloading the snapshot version from https://plugins.jetbrains.com/plugin/14080-kotest/versions/stable

**Comment by sksamuel** [comment]
You can remove the plugin, restart intellij, and then add it and it will
work.
For some reason intellij doesn't always update the plugin when move between
intellij versions.
