### ISSUE TITLE
`shouldBe` fails for byte arrays wrapped in data classes

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#2971]
The following example fails. Not sure if this is intended?

```kotlin
      "Wrapped byte array compares" {
         data class Wobble(val bytes: ByteArray)
         Wobble(byteArrayOf(1, 2, 3)) shouldBe Wobble(byteArrayOf(1, 2, 3)) // 🔴
      }
```

Comparing the byte arrays directly works:
```kotlin
      "Byte array compares" 
         byteArrayOf(1, 2, 3) shouldBe byteArrayOf(1, 2, 3) // 🟢
      }
```

**Comment by sksamuel** [comment]
I think it's because equals in data classes don't use deep equals for
arrays.

**Comment by Kantis** [comment]
Would it be fine to add?

**Comment by sksamuel** [comment]
We'd have to custom handle all data classes via reflection. Seems a big
breaking change.

**Comment by Kantis** [comment]
I agree, big breaking change. Would it be wrong to consider them equal though?

Perhaps we could make it possible to opt-out from the deep equals handling..

**Comment by sksamuel** [comment]
Doesn't intellij give you a warning anyway if you have arrays in a data class ?
Seems a kotlin/java thing rather than a Kotest thing ?

**Comment by sksamuel** [comment]
What's your current thinking on this @Kantis
