### ISSUE TITLE
Property based testing: Make Arb.orNull() be able to shrink to null (automatically)

### ISSUE THREAD

**Issue by agile-jordi** [kotest/kotest#2976]
Property based testing shrinking in Kotest is really interesting to get simplified examples when we find a fail in our tests. Acording to the documentation, base `Arb` instances, like `Arb.string`, `Arb.int`, etc. already have shrinking implemented but you must provide shrinking explicitly for custom `Arb`s.

Interestingly enough, `bind` family of functions already provide a nice default shrinking that provides a nice default shrinking for custom `Arb` instances generated with `bind`. Following this line, it would be interesting for Kotest to provide a sane default shrinking when using other `Arb` combinators.

One such case is `Arb.orNull()` that now only provides the shrinks of the receiver `Arb`. This PR adds a new shrink child `null` to those shrinks. This causes that shrinking attempts to use `null` as a shrinked value, which is very convenient, in my experience.

If you want to consider this, I already submitted a PR with the implementation, in case it helps: https://github.com/kotest/kotest/pull/2975

Thanks in advance,
Jordi

**Comment by myuwono** [comment]
resolved in #2975
