### ISSUE TITLE
Add JsonSchema array support for unique

### ISSUE THREAD

**Issue by nor-ek** [kotest/kotest#2979]
According to task comment https://github.com/kotest/kotest/issues/2961#issuecomment-1128122006 it should be possible to do
```
jsonSchema {
  array(unique=true)) { string() } 
}
```
- https://json-schema.org/understanding-json-schema/reference/array.html#uniqueness

**Comment by Kantis** [comment]
We have a `beUnique()` matcher for Collections. Perhaps that could be used to delegate a bit? We use matchers  a bit for other Json primitives already

**Comment by nor-ek** [comment]
Could you show me an example? Btw. you can assign me.

**Comment by Kantis** [comment]
Here you can see usage with matchers:

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-json/src/jvmTest/kotlin/io/kotest/assertions/json/schema/SchemaWithMatcherTest.kt#L34

And validation:

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-json/src/commonMain/kotlin/io/kotest/assertions/json/schema/matchSchema.kt#L137

It's perhaps not very clean right now, but if we keep using the same pattern it should be easier to refactor later 😄

**Comment by nor-ek** [comment]
@Kantis So you suggest it should work like: 
```
         val abc = jsonSchema {
            array { string(beUnique()) }
         }
```

As I quickly checked it there is problem because `beUnique` returns `Matcher<Sequence<T>> ` instead of `Matcher<String>` .

**Comment by Kantis** [comment]
no I was thinking exactly what you wrote originally:

```kotlin
 val abc = jsonSchema {
    array(unique = true) { string() }
}
```

but that this could be implemented as:

```kotlin
fun JsonSchema.Builder.array(unique: Boolean  = false, typeBuilder: () -> JsonSchemaElement) =
   JsonSchema.JsonArray(
      matcher = if (unique) beUnique() else null, 
      typeBuilder()
   )
```

But it introduces some additional work, since you would have to rework parsing of the Json Arrays.. Perhaps that's inevitable though, as we keep adding stuff for arrays..

**Comment by nor-ek** [comment]
PR https://github.com/kotest/kotest/pull/2987
