### ISSUE TITLE
catchThrowable or similar

### ISSUE THREAD

**Issue by jlous** [kotest/kotest#2983]
I miss the "catchThrowable" feature in assertJ.

I like to keep a uniform "prepare, act, assert"-structure to my test code. 
KoTest forces me to assert before I act when dealing with exceptions.

I would like to do something like this:
```
"Fails if input is banned" {
    thingy.ban("wrong")

    val thrown = catchAny {
        thingy.doSometing("wrong")
    }
    
    thrown shouldNot beNull
    thrown shouldBe instanceOf MyException::class 
}
```

Aside from aesthetics, a nullable return value would also be extremely useful for evaluating both failing and successful cases with the same code, such as in tabular or nondeterministic tests. 

I could of course implement catchAny() independently of KoTest, but I feel i t would be a valuable addition to the standard toolbox.

**Comment by jlous** [comment]
I could of course implement catchAny() independently of KoTeEst, but I feel i t would be a valuable addition to the standard toolbox.

**Comment by Kantis** [comment]
You can use `shouldThrowAny` or `shouldThrow<T>` for this?

**Comment by jlous** [comment]
As implied in my post, there are two problems with those:
- They fail unconditionally if no exception is thrown, which limits utilty in some types of testing
- They require me to assert while or before I act, which is not my preferred style and IMO limits readability

**Comment by ashishkujoy** [comment]
Not sure if for that case we should add a function in kotest. Above usecase can be achieve using runCatching from kotlin std library.

```kotlin
"Fails if input is banned" {
    thingy.ban("wrong")

    val thrown = runCatching {
        thingy.doSometing("wrong")
    }.getOrNull()
    
    thrown shouldNot beNull
    thrown shouldBe instanceOf MyException::class 
}
``

**Comment by myuwono** [comment]
+1 to @ashishkujoy 's approach too if that's the style you'd prefer @jlous. Just another data point that there are matchers on `Result<T>` as well, so you can leverage that. 
```kotlin
test("Fails if input is banned") {

    thingy.ban("wrong")

    val result = runCatching { thingy.doSometing("wrong") }
    
    result.shouldBeFailureOfType<MyException>()
}
```
the matcher above also return `MyException` type when the assertion succeeds in case you want to continue with more sophisticated assertions on the exception.

**Comment by jlous** [comment]
Thanks, I didn't know about runCatching. That is exactly what I want.
Closing.
