### ISSUE TITLE
afterEach does not run if callbacks are not defined first in a DescribeSpec

### ISSUE THREAD

**Issue by moikarin** [kotest/kotest#2988]
**Which version of Kotest are you using**
io.kotest:kotest-runner-junit5:5.3.0
io.kotest:kotest-assertions-core:5.3.0

Documentation states that: "Note that the order of the callbacks in the file is not important."
https://kotest.io/docs/framework/writing-tests.html

However, this example does NOT run afterEach:

```
class NestedTestExamples : DescribeSpec({

    describe("an outer test") {

        beforeEach { println("Hello beforeEach") }
        // it works if you move afterEach() here.
        it("test A") {
            println("test A")
            1 + 2 shouldBe 3
        }

        it("test B") {
            println("test B")
            3 + 4 shouldBe 7
        }

        afterEach { println("Goodbye afterEach") }
    }
 })

```

Expected output:
 ```
    Hello beforeEach
    test A
    Goodbye afterEach
    Hello beforeEach
    test B
    Goodbye afterEach

```
Actual output:
```
    Hello beforeEach
    test A
    Hello beforeEach
    test B
```

If you define the lifecycle callbacks first, before the tests, we get the desired behavior.

**Comment by sksamuel** [comment]
I'm not sure we can do much about this. If the tests are first, then they are immediately executed.
We should clarify the docs though.
Or maybe even throw if you have an after each AFTER tests are defined.

**Comment by sksamuel** [comment]
We can't statically enforce this, but I think we can throw runtime errors if afterEach is defined AFTER a test is implemented.
