### ISSUE TITLE
Updated to Kotlin 1.7

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#2990]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by Kantis** [comment]
So updating to Kotlin 1.7 means we can't use Kotest 5.4 to test Gradle plugins for Gradle 7.4 or earlier. I think maybe we could hold off a bit?

**Comment by sksamuel** [comment]
I don't think we should do 1.7 at all for now.

**Comment by sksamuel** [comment]
Closing this, as we don't need any features from 1.7 and 5.3.2 works with 1.6 and 1.7 so we're good.
