### ISSUE TITLE
Gradle assertions for plugin authors

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [kotest/kotest#2992]
Some samples:

- Task outcome
  - `Result.hasSuccessOutcome()`
  - `Result.hasFromCacheOutcome()`
  - `TaskOutcome.shouldBeSuccess()`
  - `TaskOutcome.shouldBeFromCache()`
  - and so on
- Result output
   - `Result.shouldBeConfigurationCacheCompatible()`

**Comment by LeoColman** [comment]
Maybe this could be a different module, like we have for Ktor assertions https://github.com/kotest/kotest-assertions-ktor

**Comment by JavierSegoviaCordoba** [comment]
@LeoColman exactly, it is too specific to be added to the core assertions module.

**Comment by JavierSegoviaCordoba** [comment]
No stale

**Comment by sksamuel** [comment]
I'm going to close this as out of scope for the main kotest org. There's a lot of upkeep in keeping the compiler plugins up to date, and since I wouldn't use these plugins I can't commit to maintaining them.
I hope someone from the community could make a third party repo and add these.
