### ISSUE TITLE
unrestricted `suspendArbitraryBuilder` throws when there were suspend functions within the builder lambda

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest#2993]
**Which version of Kotest are you using**
5.3.0

## Context
A while back we introduced support to non-restricted suspend function to the arbitrary builders for building arbitraries. Unfortunately, the suspend arbitrary builder throws when there were suspend functions within the builder lambda. For instance this function fails:
```kotlin
context("suspend arbitrary builder with unrestricted continuation") {
   test("should build arb on the parent coroutine context") {
      val arb = withContext(Foo("hello")) {
         generateArbitrary {
            val hello = coroutineContext[Foo]?.value
            val world = arbitrary { "world" }.bind()
            val first = Arb.int(1..10).bind()
            val second = Arb.int(11..20).bind()
            delay(10.milliseconds) 
            withContext(Dispatchers.IO) {
               listOf(hello, world, first, second).joinToString(" ")
            }
         }
      }

      arb.generate(RandomSource.seeded(1234L)).take(4).toList().map { it.value } shouldContainExactly listOf(
         "hello world 2 20",
         "hello world 6 12",
         "hello world 7 19",
         "hello world 9 13"
      )
   }
}
```
This is because the suspensions were called from a blocking context, since both `Arb<A>.sample` and `Arb<A>.edgecase` is non-suspend. 

## Propositions
I observed we have several options to solve this:
1. option 1: make `generateArbitrary` return a new `SuspendArb<A>` which has both sample and edgecase functions as suspend. 
2. option 2: keep the status quo - make `generateArbitrary` return the old `Arb<A>`. Here we need to block the calling thread whenever sample and edgecase were called.
3. option 3: change sample and edgecase functions in `Arb<A>` to suspend - this will need to be done in a non-breaking way / through deprecation cycle.
4. option 4: we remove `generateArbitrary` in favour of the new actions as that natively support suspend.

**Option 1** would require additional support for `SuspendArb<A>` which will be transparent to end users, and result in a breaking change only for `generateArbitrary`. The downside is that kotest maintainers will need to duplicate all operations on `Arb<A>` to `SuspendArb`, that means map, flatMap, filter, bind, and even checkAll and forAll will need to be reimplemented for `SuspendArb<A>` which will be a lot of code duplications.. As well, it will be awkward for users if they want to mix-and-match both `SuspendArb<A>` and regular `Arb<A>` in `checkAll`. Possible but will be a bit annoying, e.g. something like `arb.toSuspendArb()` would be required..

**Option 2** would be the easiest to implement, and has the least breaking change. However, it would be the hackiest of all. The resulting Arb generated from `generateArbitrary` is unusable from JS tests. In retrospect it is still better than the current state.

**Option 3** would be the cleanest but it would be a major breaking changes, which makes it least attractive in the short term. This option will also means that operation like `Arb<A>.single()` or `Arb<A>.next()` will need to be suspend. In my opinion this is a good path forward in the long term, because in a sense "using an arb with a `randomSource`" should classify as a side-effectful operation. `checkAll` and `forAll` have already been rightfully suspend. With next and single being suspend, we can all of a sudden enforce randomSource with all calls to `next()` by propagating it through the coroutine context so that end users will be informed why their tests fail on which random seed, even though it was called from outside the checkAll context. 

**Option 4** would also make a lot of sense in my personal opinion. This is because `action` being stateful testing, is by typedef the `suspend` counterpart of property testing. The downside is obviously users lost all the convenience of arbitraries & their composable properties. We can no-longer mix-match arbitraries anymore. Users will also need to forgo the convenience of checkAll.. However, upside of this approach is that in some way adheres to the stateful testing concept. e.g. trying to set up database etc makes more sense within an action instead of an arb. However, this becomes clunky if we need to compose the output of the actions - which is in many (or rather, most of the) time required.

## Recommendation
Short term, I recommend we pursue option 2, with long term goal of option 3. Option 3 sounds like a path forward in the long term. However, I think that requires much more thinking and discussions. Although option 4 seemingly making sense, I'm afraid we are possibly mixing concerns by entangling suspend arb to action, which feels unpleasant.

discovered while reviewing and prototyping https://github.com/kotest/kotest/pull/2972

**Comment by sksamuel** [comment]
If we take option 3 and instead of adding suspend to edgecases and sample, we introduce new suspendable versions, deprecate the originals, and have the new ones point to the old ones by default. Then we could implement bind as easily as this perhaps?

```kotlin
interface GenerateArbitraryContext {

   /**
    * Returns the generated value of an arb.
    * This can either be a sample or an edgecase.
    */
   suspend fun <T> Arb<T>.bind2(): T
}

suspend fun <A> generateArbitrary2(configure: suspend GenerateArbitraryContext.(RandomSource) -> A): Arb<A> {

   return object : Arb<A> {
      suspend fun edgecase2(rs: RandomSource): A? {
         val context = object : GenerateArbitraryContext {
            override suspend fun <T> Arb<T>.bind2(): T {
               return edgecase(rs) ?: sample(rs).value
            }
         }
         return configure(context, rs)
      }

      suspend fun sample2(rs: RandomSource): Sample<A> {
         val context = object : GenerateArbitraryContext {
            override suspend fun <T> Arb<T>.bind2(): T {
               return sample(rs).value
            }
         }
         return configure(context, rs).asSample()
      }
   }
}
```
