### ISSUE TITLE
Nesting `When` under `When` in `BehaviorSpec` results in silently ignored tests

### ISSUE THREAD

**Issue by andrey-bolduzev** [kotest/kotest#3028]
As illustrated in the [sample project](https://github.com/andrey-bolduzev/kotest-when-when/blob/main/src/test/kotlin/demo/DemoTest.kt), doing something along the lines of:

```kotlin
class DemoTest : BehaviorSpec({

    Given("given") {
        When("top when") {
            When("bottom when") {
                Then("assertion") {
                    1 shouldBe 2
                }
            }
        }
    }
})
```

and the isolation mode set to `IsolationMode.InstancePerLeaf` results in all tests passing without execution.

If the isolation mode is left at the default, the outer `When` is ignored as not containing any tests/leafs, so also not great.

If I understand correctly, `When`s are not supposed to be nested under `When`s but it's something that is very easy to miss when writing or reviewing code, and you end up with silently broken test code.

Is it possible to mitigate this in any way?

**Which version of Kotest are you using**

5.3.0

**Comment by Kantis** [comment]
I think we can solve it by adding a `@DslMarker`. I can have a look :)

**Comment by Kantis** [comment]
So all spec scopes already have a `@DslMarker` in the form of [@KotestTestScope](https://github.com/kotest/kotest/blob/9fcf94066f462e9337db1e8153f39106edde277e/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/spec/KotestTestScope.kt), see [BehaviorSpecGivenContainerScope](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/spec/style/scopes/BehaviorSpecGivenContainerScope.kt#L30) for instance.

I checked out your repro (thanks a lot for providing!) and can confirm the problem exists outside the Kotest repo. I wonder if the retention type is insufficient to propagate to consumer sites? Trying to do a local build with altered retention type to see if it makes a difference..

**Comment by andrey-bolduzev** [comment]
Interesting. Just looking around other dependencies in a project, any marker annotation annotated with `@DslMarker` I can see uses the default retention (`RUNTIME`).

**Comment by Kantis** [comment]
I tried it out with every possible retention type, and still no luck.. Maybe something to do with how our stuff is packaged? Ktor also uses `@DslMarker` in a Kotlin multiplatform project and it's working there.. 🤔

**Comment by sksamuel** [comment]
I think we need the RUNTIME retention like @andrey-bolduzev says. We're using source so it works for us locally but not in other projects.

**Comment by sksamuel** [comment]
@Kantis I've taken the latest snapshot after merging this, and applied it to one of my projects, and tried the above snippet. The nested When is now correctly highlighted as invalid.

![image](https://user-images.githubusercontent.com/743706/173244002-74832256-b101-4aec-9bde-415d6a53f80c.png)

**Comment by Kantis** [comment]
Awesome! I must've done something wrong when building locally then 😄
