### ISSUE TITLE
Spec class annotation enhancements

### ISSUE THREAD

**Issue by jschneidereit** [kotest/kotest#3029]
- [x]  `@Ignored` should accept an optional reason and log it similar to `enabledIfOrReason`
- [ ]  `@EnabledIf` should accept multiple `EnabledCondition`s
- [ ]  `EnabledCondition` should have an optional reason and should be logged when `enabled` is evaluated and if it is false

**Comment by sksamuel** [comment]
@jschneidereit we'll be releasing 5.4 in the coming days for Kotlin 1.7 support.
If you want all this in 5.4 then add the PRs and we'll merge.

**Comment by jschneidereit** [comment]
Actually @sksamuel I think the second two items would be breaking changes because EnabledCondition is a `fun interface` - getting #3030 into 5.4 is enough for now

```kotlin
fun interface EnabledCondition {
   fun enabled(kclass: KClass<out Spec>): Boolean
}
```
