### ISSUE TITLE
SystemEnvironmentTestListener - Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible:

### ISSUE THREAD

**Issue by Marek00Malik** [kotest/kotest#3035]
**Which version of Kotest are you using**
KoTest - 5.3

Kotlin - 1.6.20

I'm getting the following error when trying to run this code line in a WordSpec test. 

```
class PublisherServiceTest : WordSpec() {

    private val pubSubService = install(TestContainerExtension(pubSubContainer)) {
        addExposedPort(8085)
    }
    private val address: String = "${pubSubService.host}:${pubSubService.firstMappedPort}"

    override fun listeners() = listOf(SystemEnvironmentTestListener("PUBSUB_TARGET", address)) //<<< FAILING HERE
    init {
        ...
    }
}
```
Error Message: 
` Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @309e345f`

This is directly thrown when in SystemEnviromentExtensions.kt line 99 is called:
```
classOfMap.getDeclaredField("m").asAccessible().get(systemEnv) as MutableMap<String, String>
```
method: getEditableMapOfVariables
```
@Suppress("UNCHECKED_CAST")
private fun getEditableMapOfVariables(): MutableMap<String, String> {
   val systemEnv = System.getenv()
   val classOfMap = systemEnv::class.java

   return classOfMap.getDeclaredField("m").asAccessible().get(systemEnv) as MutableMap<String, String>
}
```

Is there something I'm doing wrong?

**Comment by sksamuel** [comment]
Which version of the jdk ?

**Comment by Marek00Malik** [comment]
java 17

**Comment by sksamuel** [comment]
Looks like this stopped working in Java16 and there's no way to set the map anymore.

**Comment by Marek00Malik** [comment]
Can someone fix this?

**Comment by sksamuel** [comment]
Can't fix the JVM. They've just removed the functionality.
We will prob need to just remove this from Kotest.

**Comment by Marek00Malik** [comment]
this is bad/sad news... :( How can we configure Ktor then after it already started with a container on a random port?

**Comment by LeoColman** [comment]
From https://github.com/webcompere/system-stubs

> warning WARNING: JDK Compatibility. From JDK16 onwards, there are deeper restrictons on the ability to use reflection. Previous versions of this library, and others in the space, encounter an Illegal Reflective Access warning, or even a runtime error such as java.lang.reflect.InaccessibleObjectException when trying to manipulate the Map behind the system's environment variables.
> Consequently, this library now uses mockito-inline version 3.x to enable the interception of calls for reading environment variables. This requires consumers to both use a compatible version of Mockito AND be prepared for the inline implementation of Mockito mocks.
> Note: Groovy users may need Mockito >= 4.5.0 for compatibility.
> Where this isn't appropriate, the [v1.x](https://github.com/webcompere/system-stubs/tree/1.x) version of this will still work for Java versions below 16, and may also be co-erced into working with via the java https://github.com/stefanbirkner/system-lambda/issues/23#issuecomment-1007608124.
> The long-term plan for this library is to use more interceptors of system functions with Mockito where possible, unless a more direct route becomes available. While this library will continue to be built for Java 8 at the moment, in future it may also move to a higher base version. The v1.x branch will stay on Java 8.

**Comment by LeoColman** [comment]
They seem to still do it in some way, but bringing Mockito in.
It might be a possibility

**Comment by LeoColman** [comment]
https://github.com/webcompere/system-stubs/blob/main/system-stubs-core/src/main/java/uk/org/webcompere/systemstubs/environment/EnvironmentVariableMocker.java

https://github.com/webcompere/system-stubs/blob/main/system-stubs-core/src/main/java/uk/org/webcompere/systemstubs/environment/EnvironmentVariables.java

**Comment by LeoColman** [comment]
We do similar stuff with `CurrentInstantListener`, but using `mockk`.

**Comment by LeoColman** [comment]
Just tested with
openjdk 18.0.1 2022-04-19

And our code is still working. Can you help me reproduce, @Marek00Malik ?

**Comment by Kantis** [comment]
I added info here on how you can work around it: https://kotest.io/docs/extensions/system_extensions.html (see the blue info box)

**Comment by Marek00Malik** [comment]
Thanks @Kantis, will test this later today!

**Comment by sksamuel** [comment]
Closing, please reopen if issue persists.

**Comment by jmfayard** [comment]
@sksamuel I first raised #3112 which brought me here.

So I edited `gradle.properties`

```diff
-org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx4608M
+org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx4608M --add-opens=java.base/java.util=ALL-UNNAMED
```

I had a first issue `Overriding a variable when mode is set to SetOrError. Use another OverrideMode to allow this. Trying to set {FIXED_OTP=hi42}`

That's not a bug per se, but the fix was not obvious, it would be nice to mention it in the documentation
https://kotest.io/docs/extensions/system_extensions.html

```diff
-withEnvironment(OtpSource.FIXED_OTP, "hi42", , OverrideMode.SetOrOverride) {
+withEnvironment(OtpSource.FIXED_OTP, "hi42") {
         //
}
```

Alas that still fails

`java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @47089e5f`

https://scans.gradle.com/s/rqvdpgm2f5fq6/tests/:test/com.tignum.backend.core.health.SanityCheckerTest/fixed%20OneTimePassword%20can%20be%20enabled%20only%20in%20the%20local%20environment()?expanded-stacktrace=WyIwIl0&top-execution=1

**Comment by benkeil** [comment]
same issue...

**Comment by noraab** [comment]
For me, the only fix was to have the following in the `build.gradle.kts`:
```
tasks.test {
    jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED")
}
```

Adding the arguments to `gradle.properties` did not help.

**Comment by Kantis** [comment]
Thanks, I updated the docs. https://github.com/kotest/kotest/commit/29aac29f5948d32008954eca2f765c806badf294
