### ISSUE TITLE
Add semantics for "expected failures"

### ISSUE THREAD

**Issue by brucek** [kotest/kotest#3061]
I couldn't re-open the issue in #187 but this does have value, esp coming to Kotlin from other more developed ecosystems, so I'd like to reopen and reconsider this - key information copied here:

[sschuberth](https://github.com/sschuberth) Sometimes, esp. in TDD, it's convenient to add a test that is expected to fail at first, but will be fixed to succeed (e.g. by adding an implementation in the application) later on. In contrast to config(enabled = false) these tests should be executed but be clearly marked (e.g. in yellow) in the output to document them as "TODOs". The commit adding the implementation then typically also re-configures the test from an expected failure to a regular test that is expected to succeed.

[brucek](https://github.com/brucek) For what it's worth, my team is hitting the need for this capability as well.

The scenario:

we have a known code defect
we don't have time to actually fix it now
we can create a test case indicating the failure
...if we had the equivalent of pendingUntilFixed ([rspec](https://relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples) also does a good job of this) we can note the item to fix in the code, and be reminded of all such pending tech debt items every time we run the test suite.

It is also helpful in that if some other code causes the test to unexpectedly pass, I am notified (by a test suite failure), so I can go investigate and see if something unexpected happened, if it fixed the issue, etc.

Otherwise if I am not notified of the test passing immediately as a test failure, someone later might run the test, see it pass and assume it was properly fixed (which it may not have been).

**Comment by sschuberth** [comment]
I've reopened https://github.com/kotest/kotest/issues/187 to keep the discussion in a single place.
