### ISSUE TITLE
Allure Report Showing two tests in one suite when there is only one test

### ISSUE THREAD

**Issue by mattupstate** [kotest/kotest#3062]
`kotest:5.3.0`
`kotest-extensions-allure:1.2.0`

The `AllureTestReporter` extension seems to be buggy. Perhaps my configuration is out of the ordinary, though. When running [this test](https://github.com/mattupstate/acme/blob/acme-app-web-test-kotest/acme-app/acme-app-web-test/src/test/kotlin/com/acme/web/test/specs/EmailAndPasswordRegistrationWorkflowSpec.kt) I get the following output in the Allure Report when running the `allureServe` task:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/166176/174457669-23b99ce0-5f95-4319-9d6a-0f95cef265e1.png">

As an aside, it also appears this report doesn't play nice with test factories.

**Comment by pooja-choudhary13** [comment]
Facing same issue with kotest version 5.2.2 kotest-extensions-allure:1.1.1, any luck @mattupstate ?

**Comment by sksamuel** [comment]
@mattupstate where do you configure the kotest allure plugin so I can see how that's wired in.

**Comment by sksamuel** [comment]
Looks like in later versions they started adding junit platform by default, so that's generating test names in addition to the kotlin one.

https://github.com/allure-framework/allure-java/issues/739

**Comment by sksamuel** [comment]
I've asked the maintainer here: https://github.com/allure-framework/allure-java/issues/428

**Comment by mattupstate** [comment]
@sksamuel sorry for the slow reply. The Gradle config is [here](https://github.com/mattupstate/acme/blob/acme-app-web-test-kotest/acme-app/acme-app-web-test/build.gradle.kts) and the kotest config is [here](https://github.com/mattupstate/acme/blob/acme-app-web-test-kotest/acme-app/acme-app-web-test/src/test/kotlin/com/acme/web/test/AcmeAppWebTestConfig.kt)

Appreciate that you dug into the depths of this.
