### ISSUE TITLE
Tests containing escaped double quotes are not correctly filtered

### ISSUE THREAD

**Issue by edoardo-liotta** [kotest/kotest#3078]
Case: 
A test has an escaped double quote character

Expected:
When clicking the "Run test" button, such test should run

Actual:
the test filter adds the backslash character, thus the test is filtered out and won't run.

Example:
```
should("map delivery status 100 to \"PENDING_RETURN\"") {
 ...
}
```

console log:
`order mapping -- map delivery status 100 to "PENDING_RETURN" is excluded by test filter(s): Excluded by test path filter: 'order mapping -- map delivery status 100 to \"PENDING_RETURN\"'`

**Comment by Kantis** [comment]
Should be fixed in Kotest IntelliJ plugin 1.2.59 when it's available. Thanks for the report @edoardo-liotta
