### ISSUE TITLE
kotest 5.4.x-SNAPSHOT does not seem to work together with Spring 2.7.1

### ISSUE THREAD

**Issue by mor4thii** [kotest/kotest#3084]
Hi,

I have an issue w/ kotest:5.4.0-1038-SNAPSHOT (and all other SNAPSHOTs of 5.4.0, and 5.3.2, and 5.3.0)

I tried to update to Spring 2.7.1 today and I got the following error from maven:
`
Unresolved dependency: 'org.jetbrains.kotlinx:kotlinx-coroutines-bom:jar:1.6.3'
`

From what I was able to test, it works with Spring 2.7.0 and all kotest versions mentioned above. Also, it appears with both Kotlin v1.6.21 and v1.7.0. Spring 2.7.1 changed the coroutines version here: https://github.com/spring-projects/spring-boot/commit/4f6bc3c2e062f09473d2652eeb6d8a0489998bab
From what I can see, kotest and spring boot now depend on the same version of kotlin coroutines

I created a small example repository for observing this behaviour: https://github.com/mor4thii/spring-kotest-demo
It is based on a simple app generated by Spring initializr.

Now, I am not too familiar with issue reports (this is my first issue on github!), and in this case, I am not sure whether this issue applies to kotest or Spring Boot. Please feel free to point me in the right direction :)

**Comment by sksamuel** [comment]
I think probably the same thing as this? https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1656524779419449

**Comment by mor4thii** [comment]
Yeah, seems to be the same issue, but with quarkus.

**Comment by Kantis** [comment]
Jetbrains seem to be working on a fix.
Likely only affecting Maven builds.
https://github.com/Kotlin/kotlinx.coroutines/issues/3334

**Comment by mor4thii** [comment]
TYVM for linking this here.

**Comment by mor4thii** [comment]
I just wanted to report that with the 2.7.2 release of Spring (https://github.com/spring-projects/spring-boot/releases/tag/v2.7.2), the issue has been resolved. They use coroutines in v1.6.4, just as kotest does :)

**Comment by sksamuel** [comment]
Closing as fixed in latest spring release.
