### ISSUE TITLE
JSON objects with duplicated properties should fail validity and equality checks

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#3090]
**Which version of Kotest are you using**
5.3.2

I want to verify that a JSON object does not contain duplicated fields. However `shouldBeValidJson()` and `shouldEqualJson()` do not throw errors.

I would like an additional comparison flag added to `shouldBeValidJson()` and `compareJsonOptions { }` for verifying that properties are distinct.

```kotlin
import io.kotest.assertions.json.CompareMode
import io.kotest.assertions.json.FieldComparison
import io.kotest.assertions.json.PropertyOrder
import io.kotest.assertions.json.TypeCoercion
import io.kotest.assertions.json.compareJsonOptions
import io.kotest.assertions.json.shouldBeValidJson
import io.kotest.assertions.json.shouldEqualJson
import org.junit.jupiter.api.Test

class JsonTest {
    @Test
    fun `expect json with duplicated properties is invalid`() {
        """
            {
              "test": 123,
              "test": 456
            }
        """.trimIndent().shouldBeValidJson()
    }

    @Test
    fun `expect json with duplicated properties does not match de-duplicated object`() {
        """
            {
              "test": 123,
              "test": 456
            }
        """.trimIndent().shouldEqualJson(
            """
                {
                  "test": 456
                }
            """.trimIndent(),
            compareJsonOptions {
                propertyOrder = PropertyOrder.Strict
                fieldComparison = FieldComparison.Strict
            }
        )
    }
}
```

**Comment by Kantis** [comment]
It seems to be in line with the spec (multiple properties allowed), but I don't see any harm in adding an extra flag to make it stricter and disallow it. I think it makes most sense to have the default to current behaviour.

**Comment by Lysoun** [comment]
I've been looking into this issue. If I understand correctly, there are some assertions methods that take options (shouldEqualJson is one of them). Those options contain multiple flags to tune the behaviour. What should be done here is:
- add an option in `compareJsonOptions` not to allow duplicate properties
- add an option for `shouldBeValidJson` not to allow duplicate properties
 
Since there are no options yet available for `shouldBeValidJson`, I doubt that creating an object would be useful but what do you think? Did I correctly identify the changes that should be done, of course with their corresponding unit tests?

**Comment by Kantis** [comment]
> Did I correctly identify the changes that should be done

Yes, I think so

> Since there are no options yet available for shouldBeValidJson, I doubt that creating an object would be useful but what do you think? 

I think it's still worthwhile since it enables the syntax:

```kotlin

actual shouldBeValidJson {
  allowDuplicateProperties = false
  expected
}
```
as discussed here: https://github.com/kotest/kotest/issues/3161#issuecomment-1215835513

**Comment by Lysoun** [comment]
Ok, thank you for your answers.
Unfortunately kotlinx serialization does not intend to make a feature to fail serialization on duplicate keys (https://github.com/Kotlin/kotlinx.serialization/issues/1990) so I'll have to do the checks myself

**Comment by Lysoun** [comment]
I've been working on this check on the kotlinx serialization side (https://github.com/Kotlin/kotlinx.serialization/issues/1990). Once I'm done, it should be a piece of cake to use those checks in kotest 😄

**Comment by sksamuel** [comment]
Nothing we can do here until kotlinx serialization exposes this. So marking as externally blocked.

**Comment by sksamuel** [comment]
Closing as not planned since kotlinx serialization has no plans to add

**Comment by Lysoun** [comment]
The kotlinx serialization issue has been assigned to someone (on January 13th). There could be a chance that the issue will be addressed, allowing fixing the bug reported here on kotest
