### ISSUE TITLE
android unit test can't read file from resources

### ISSUE THREAD

**Issue by a-reznic** [kotest/kotest#3101]
io.kotest:kotest-runner-junit5:5.3.2

test/resources/test.json - exist

but code not found it
```
init {
        test("all tests") {

            val inputStream = javaClass.classLoader?.getResourceAsStream("test.json")

            println("result -> $inputStream")
        }
}
```
print result -> null

`--------------------------------`

if i run JUnit Test  this code works perfect.

    @Test
    fun `test file reading`() {
        val inputStream = javaClass.classLoader?.getResource("test.json")

        println("result -> $inputStream")
    }
result -> file:/Users/alex/xx/xx/xxxx/app/build/intermediates/java_res/developDebugUnitTest/out/test.json

**Comment by Kantis** [comment]
Related: https://stackoverflow.com/questions/42571324/kotlin-myclassclass-java-vs-this-javaclass

In this case, you're invoking `javaClass` inside a lambda passed to the test function, where the _interface_ `TestScope` is the receiver.  `object : {}.javaClass`, `MyTest::class.java` should both be enough to get a classloader you can use.
