### ISSUE TITLE
Incorrect encoding in console output with Java 18

### ISSUE THREAD

**Issue by RaySmith-ttc** [kotest/kotest#3108]
**Kotest**: 5.3.2
**IDEA**: 2022.1.3
**JDK**: 18.0.1.1
**Kotlin**: 1.7.10

### Test
```
class UnitTests : FreeSpec({
    "test" {
        val str1 = "hello"
        val str2 = "привет"
        println("$str1 $str2")
        str1 shouldBe str2
    }
})
```

### Output with Java 18.0.1.1
```
hello ������

expected:<"������"> but was:<"hello">
Expected :"������"
Actual   :"hello"
<Click to see difference>

io.kotest.assertions.AssertionFailedError: expected:<"������"> but was:<"hello">
    ...
```
### Output with Java 17.0.3.1 (or less)
```
hello привет

expected:<"привет"> but was:<"hello">
Expected :"привет"
Actual   :"hello"
<Click to see difference>

io.kotest.assertions.AssertionFailedError: expected:<"привет"> but was:<"hello">
    ...
```

I found the solution by adding VM parameters to test, but of course I would not want to add it to each individual test:
`-Dsun.stdout.encoding="UTF-8" -Dsun.stderr.encoding="UTF-8"`

**Comment by SonYoonSeok** [comment]
Hello, Just before, I tested it but it outputs correctly in jdk 18.0.2 and kotest 5.4.1 with Intellij.

**Comment by sksamuel** [comment]
This is likely because your console is not defaulting to UTF8. See the 1st answer here:  https://stackoverflow.com/questions/24803733/default-character-encoding-for-java-console-output
