### ISSUE TITLE
Testcase disappeared when succeed

### ISSUE THREAD

**Issue by mikucat0309** [kotest/kotest#3120]
### Environment

| Type | Tool |
| --- | --- |
| IDE | Android Studio Android Studio Chipmunk 2021.2.1 Patch 1 |
| Kotest IntelliJ Plugin | 1.2.59-IC-2021.2.3 |
| Kotest Testing | JUnit 5.3.2 |
| Build tool | Gradle |
| Language | Kotlin/Android |

### Sample FIles

https://gist.github.com/mikucat0309/3cbda88c82131fcc2c1965cf1af328f9

### Description

When I run below test, Gradle show no tests  
`No tests found for given includes: [at.mikuc.myapplication.ExampleUnitTest](filter.includeTestsMatching)`  
but after changing assertion to let it fail, Gradle show failed normally  
`expected:<4> but was:<3>`

```kotlin
init {
    coroutineTestScope = true

    Given("1 and 2") {
        When("plus") {
            var a = 1
            testCoroutineScheduler.currentTime shouldBe 0
            launch {
                delay(1000)
                a += 2
            }
            testCoroutineScheduler.advanceUntilIdle()
            a shouldBe 3 // testcase disappeared
            // a shouldBe 4 // testcase failed
        }
    }
}
```

**Comment by sksamuel** [comment]
Can you paste your gradle junit setup code.

**Comment by mikucat0309** [comment]
@sksamuel Sure
project gradle file, app gradle file and test source code have been upload to gist
https://gist.github.com/mikucat0309/3cbda88c82131fcc2c1965cf1af328f9

**Comment by sksamuel** [comment]
I think the issue is you don't have a Then block.

**Comment by mikucat0309** [comment]
Oh my fault, I should take a break. Thx!
