### ISSUE TITLE
And() cannot be nested in Then() block in BehaviourSpec

### ISSUE THREAD

**Issue by ctfaria2** [kotest/kotest#3124]
**Which version of Kotest are you using**
On upgrade from `5.3.2 -> 5.4.0`

**Description of issue**
After upgrading it is no longer possible to have an And() block inside a Then()

Silly example test

```
class MySpec: BehaviorSpec({
    Given("I have a number") {
        val number = 2

        When("I multiply the number") {
            val result = number * 5

            Then("The answer is correct") {
                result shouldBe 10

                And("something else should happen") {
                    true shouldBe true
                }
            }
        }
    }
})
```

Error presented is 

```
'suspend fun And(name: String, test: suspend BehaviorSpecWhenContainerScope.() -> Unit): Unit' can't be called in this context by implicit receiver. Use the explicit one if necessary
```

**Expected result**
Test should work as before

**Comment by sksamuel** [comment]
This was a bug previously. And should be a sibling of Then, and not a child. Then is a "final" test lambda and so cannot allow children.

**Comment by ctfaria2** [comment]
So, to clarify. The expectation would be 

```
Then("") { .. }
And("") { .. }
```

If that is the case, am happy for you to close this issue. We can re-work things.

**Comment by sksamuel** [comment]
Yep. Due to a bug/restriction in how Gradle works, we have to denote tests as "final" or not. And so it can't be entirely flexible.

**Comment by ravenblackdusk** [comment]
if you used this to have access to variables initialized in the `then` block you may workaround by using `lateinit var`

**Comment by gabfssilva** [comment]
It's a bummer that the only solution for this is using `lateinit var`s. I'm wondering how viable would it be to make a test return a value, something like:

```kotlin
class MySpec: BehaviorSpec({
    Given("I have a number") {
        val number = 2

        When("I multiply the number") {
            val result = number * 5

            val multipliedResult = Then("The answer is correct") {
                result shouldBe 10
                result
            }

             And("something else should happen") {
                  multipliedResult shouldBe 10
             }
        }
    }
})
```

This would be a huge major change tho.
