### ISSUE TITLE
Kotest Intellij IDE plugin does not respect system property configuration from Gradle test tasks

### ISSUE THREAD

**Issue by tonicsoft** [kotest/kotest#3125]
**Which version of Kotest are you using** 5.4

This issue is a follow up of https://github.com/kotest/kotest/issues/2765 and it's related issues. Please see https://github.com/tonicsoft/slow-kotest for an example project that demonstrates the issue. The README.md in that project explains the context.

When running tests from the Intellij GUI, using the functionality provided by the kotest plugin, system properties and environment variables defined in the gradle test task (example below) are not respected.

```
tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
    systemProperty("kotest.framework.classpath.scanning.config.disable", true)

}
```

**Comment by tonicsoft** [comment]
probably this belongs in the project dedicated to the plugin, and also it may be best addressed by https://github.com/kotest/kotest/issues/5413

**Comment by sksamuel** [comment]
This is best addressed by https://kotest.io/docs/next/intellij/intellij-properties.html

**Comment by tonicsoft** [comment]
Thanks, for me personally, this works and I consider this issue resolved.

However, I'll let you decide whether to close this issue or whether to leave it open. It's not quite the same as respecting the "run tests using" option (but may make no difference to anyone), and I don't know if there might be other use cases beyond system properties where respecting the gradle configuration may be important.

**Comment by sksamuel** [comment]
I will close this, because our medium term solution is that we're going to add a new gradle plugin that does all this properly, and doesn't rely on the broken Junit Platform implementation in gradle.
