### ISSUE TITLE
Jackson JsonNode comparisons are broken

### ISSUE THREAD

**Issue by TheSench** [kotest/kotest#3130]
**Which version of Kotest are you using**
`5.3.1`

When comparing two different `JsonNode`s, `shouldBe` is erroneously stating they are equal when they have different values at the same key.

Here's a simple test that reproduces this issue for me:
```kotlin
@Test
fun `it should return detect differences in values`() {
  val map1 = mapOf("test" to 1)
  val map2 = mapOf("test" to 2)
  val mapper = ObjectMapper()
  val jsonNode1 = mapper.valueToTree<JsonNode>(map1)
  val jsonNode2 = mapper.valueToTree<JsonNode>(map2)

  // Passes
  jsonNode1 shouldBe jsonNode2
  // Fails with:
  // expected:<"{"test":2}"> but was:<"{"test":1}">
  jsonNode1.toString() shouldBe jsonNode2.toString()
}
```

**Comment by sksamuel** [comment]
I guess this is because JsonNode is iterable, and so it's doing an iterable comparison.

@Kantis @ashishkujoy what do you think about dropping "is Iterable" from the checks, and only checking for Array / Collections, which is really our intent.

**Comment by ashishkujoy** [comment]
That might break the existing test for other folks, currently I don't remember why I have added Iterable EQ.

**Comment by broglep-work** [comment]
We are experiencing probably related issue when using vertx JsonObject. They are also Iterable and when they contain a complex property value (like a list), comparison fails. 

```
@Test
fun `to equal objects`() {
    val o1 = JsonObject(mapOf("test" to listOf(1, 2)))
    val o2 = JsonObject(mapOf("test" to listOf(1, 2)))
    o1.shouldBe(o2)
}
```

Outputs: 
```
Element differ at index: [0]
expected:<[io.vertx.core.json.JsonObject$Entry@66b34e9a]> but was:<[io.vertx.core.json.JsonObject$Entry@6452533b]>
Expected :[io.vertx.core.json.JsonObject$Entry@66b34e9a]
Actual   :[io.vertx.core.json.JsonObject$Entry@6452533b]
```

(Using kotest 5.4.1)

**Comment by Kantis** [comment]
Sounds like it has some unfortunate consequences. Perhaps you could try dropping the `is Iterable` and see what tests fail as a result to help remember why it was added @ashishkujoy ?

**Comment by ashishkujoy** [comment]
Apologies folks, I don't have bandwidth to pick this up.

**Comment by piotrb5e3** [comment]
Hi,

I checked, and dropping `is Iterable` causes some tests to fail.

Thee seems to a conceptual issue here. [Kotlin iterables](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-iterable/) are defined as:

> Classes that inherit from this interface can be represented as a sequence of elements that can be iterated over.

Java iterables do not have this assumption:
> Implementing this interface allows an object to be the target of the enhanced for statement (sometimes called the "for-each loop" statement).

**Comment by piotrb5e3** [comment]
Hi,

I checked, and dropping `is Iterable` causes some tests to fail.

There seems to a conceptual issue here. [Kotlin iterables](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-iterable/) are defined as:

> Classes that inherit from this interface can be represented as a sequence of elements that can be iterated over.

Java iterables do not have this assumption:
> Implementing this interface allows an object to be the target of the enhanced for statement (sometimes called the "for-each loop" statement).

So while it seems idiomatic in kotlin to compare iterables by their content, it probably should not be done, because at least on the JVM platform the implementation class does not make this assumption.

My advice would be to remove the `is Iterable` check and rely on default equality check for these cases, but this decision is probably up to maintainers.

**Comment by daviddenton** [comment]
> My advice would be to remove the `is Iterable` check and rely on default equality check for these cases, but this decision is probably up to maintainers.

I tend to agree here - keeping Iterable support would seem to be the riskier long-term option, as this issue is likely to keep coming up when it surprises people. 😄

**Comment by daviddenton** [comment]
Pinging to keep this open so at least it's visible for people to see. 🙃

**Comment by echo304** [comment]
I'm going to pick it up :)
