### ISSUE TITLE
WordSpec tests with withData not compiling anymore with 5.4.0

### ISSUE THREAD

**Issue by LeMimit** [kotest/kotest#3131]
**Which version of Kotest are you using**
I tried to update to version `5.4.0`.

I have some test using Data Driven testing feature. These tests are not compiling anymore with version `5.4.0`. 
I looked to the release note, it is may be related to the change: `Set runtime retention on dsl marker` (#3038)

Here is the error I got:

`suspend fun <T> ContainerScope.withData(nameFn: (QuantityConvert) -> String, first: QuantityConvert, second: QuantityConvert, vararg rest: QuantityConvert, test: suspend ContainerScope.(QuantityConvert) -> Unit): Unit' can't be called in this context by implicit receiver. Use the explicit one if necessary`

with the current test:

```kotlin
class QuantityTest : WordSpec({
    "Test" should {
        "be good" {
            withData(
                QuantityConvert(),
                QuantityConvert(),
            ) { (quantity, density, expectedConversion) ->
                // Test
            }
        }
    }
})
```

**Comment by sksamuel** [comment]
`withData` only ever worked with _container_ scopes, so in this case, your test is being bound to the `"Test" should` scope, and the "be good" is being ignored. In 5.4.0 this bug has been fixed so it doesn't just silently work incorrectly.

You can rewrite this as:

```kotlin
class QuantityTest : WordSpec({
    "Test" should {
            withData(
                QuantityConvert(),
                QuantityConvert(),
            ) { (quantity, density, expectedConversion) ->
                // Test
            }
    }
})
```

or

```kotlin
class QuantityTest : FreeSpec({
    "Test should" - {
        "be good" - {
            withData(
                QuantityConvert(),
                QuantityConvert(),
            ) { (quantity, density, expectedConversion) ->
                // Test
            }
        }
    }
})
```

**Comment by LeMimit** [comment]
Ohhh I get it now. I got a wrong definition for sooo long then.
I fixed my tests by using the good syntax. 👍🏻 

Thanks a lot for your answer and fixing the bug in `5.4.0`.

**Comment by sksamuel** [comment]
You should remove the "be good" as that was being ignored previously, or
switch to another spec style.
Data driven tests have to be placed inside a non terminal scope.
