### ISSUE TITLE
Mock server DSL

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3133]
I often use Kotest's mock server extensions for testing responses to external HTTP services, but the syntax is very Java-y. Consider adding a simple DSL wrapping the Mockserver DSL.

Eg,

before:
```kotlin
   MockServerClient("localhost", server.port)
      .`when`(
         HttpRequest.request()
            .withMethod("POST")
            .withPath("/myindex/_count")

      )
      .respond {
         HttpResponse.response()
            .withStatusCode(500)
            .withDelay(Delay.seconds(Random.nextLong(1, 5)))
      }
```

after:
```kotlin
   mockServer {
      post("foo") {
         queryParameter("foo", "bar") {
            delay(1000)
            HttpResponse(500, "foo")
         }
      }
   }
```

**Comment by Kantis** [comment]
I started doing something similar a while back, nothing too fleshed out but feel free to take inspiration (or copy everything).. https://github.com/Kantis/mockserver-kotlin

**Comment by Kantis** [comment]
I think your suggested DSL is nicer btw, so not sure if the link adds anything at all.. 😂

**Comment by pientaa** [comment]
Shouldn't this issue be moved to https://github.com/kotest/kotest-extensions-mockserver ?

Also - I'll take that issue if you don't mind

**Comment by pientaa** [comment]
@sksamuel is it still actual?
