### ISSUE TITLE
Nested spec hangs

### ISSUE THREAD

**Issue by ollis** [kotest/kotest#3134]
kotest : 5.4.0
kotlin: 1.6.21
ktor: 2.0.3

kotest hangs when I use nested spec styles in conjunction with [ktor](https://ktor.io/docs/testing.html)
Minimal example:
```kotlin
package no.norsktipping.customerservice.customersupportontactinformation

import io.kotest.assertions.ktor.client.shouldHaveStatus
import io.kotest.core.spec.style.FreeSpec
import io.ktor.client.request.*
import io.ktor.server.config.*
import io.ktor.server.testing.*

class FreeSpecTest : FreeSpec({

    "outer" - {
        "inner 1" {
            println("inner 1!")
        }
        testApplication {
            environment {
                config = MapApplicationConfig()
            }
            println("testApplication start")
            val notfound = client.get("/notfound")
            notfound shouldHaveStatus 404
            println("assert complete")
//            "inner 2" {
//                println("inner 2!")
//            }
            println("testApplication end")
        }
    }
})
```
This gives the following (expected) output: 
```
inner 1!
testApplication start
2022-08-01 12:04:48.499  INFO          --- [atcher-worker-1] ktor.test                                : Application started in 0.175 seconds. 
assert complete
testApplication end

```
But it hangs if I uncomment the "inner 2" block and the output changes to this:
```
inner 1!
```

**Comment by sksamuel** [comment]
My guess, without delving into it, is that the test application never
terminates, and so the coroutine is kept alive, and Kotest is waiting for
your test to complete (until it hits the default timeout).

**Comment by ollis** [comment]
Yes, so the issue/question is why the inclusion of an inner test ("inner 2") causes this behaviour?

**Comment by sksamuel** [comment]
`testApplication { }` starts a `BlockingEventLoop` dispatcher which doesn't free up the thread so that the inner2 block can run. So inner2 just sits there waiting to run, which in turn has suspended the test application from completing.

You're best off having testApplication as a leaf, or wrapping the whole thing in another context:

```

class FreeSpecTest : FreeSpec({

    "outer" - {
        "inner 1" {
            println("inner 1!")
        }
        withContext(Dispatchers.IO) {
        testApplication {
            environment {
                config = MapApplicationConfig()
            }
            println("testApplication start")
            val notfound = client.get("/notfound")
            notfound shouldHaveStatus 404
            println("assert complete")
            "inner 2" {
                println("inner 2!")
            }
            println("testApplication end")
        }
        }
    }
})
```

**Comment by ollis** [comment]
@sksamuel Thank you for the answer! It is not obvious for me why the dispatcher does not free up the thread, can you please elaborate? I would expect the thread that was started from runBlocking in testApplication to run the nested specs as well?

**Comment by sksamuel** [comment]
I don't know either, but my guess is the event loop dispatcher thing has special semantics.

**Comment by LeoColman** [comment]
I think this issue has nothing to do with Kotest itself.
I'll close it. Feel free to reopen it if you think it makes sense :)
