### ISSUE TITLE
Allow registering custom default Arb for your own types in checkAll/forAll

### ISSUE THREAD

**Issue by Rubydesic** [kotest/kotest#3136]
Currently `checkAll` and `forAll` use `defaultForClass` and `targetDefaultForClass` to get a hardcoded list of global default Arb for those classes.

I have some more types (like `Vector3d` from JOML) that I would like to register default generators for, but it doesn't seem possible.

----

Maybe the definition of  `checkAll` could be amended like this:

```kt
suspend inline fun <reified A> checkAll(
   config: PropTestConfig,
   noinline property: suspend PropertyContext.(A) -> Unit
): PropertyContext = proptest(
   Arb.default<A>(config),
   config,
   property
)
```

**Comment by sksamuel** [comment]
Your suggestion would work, also another option would be to allow you to register with the global store.

```kotlin
GlobalArbs.addDefault(myarb)
```

Or something
