### ISSUE TITLE
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.milliseconds-UwyO8pc(long)'

### ISSUE THREAD

**Issue by minzoovv** [kotest/kotest#3137]
I'm encontering the error  while running my kotest

My kotlin version is 1.7.10
I cannot figure out how cause this runtime error

```
'long kotlin.time.Duration$Companion.milliseconds-UwyO8pc(long)'
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.milliseconds-UwyO8pc(long)'
	at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor.intercept-0E7RQCE(SpecFinishedInterceptor.kt:25)
	at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor$intercept$1.invokeSuspend(SpecFinishedInterceptor.kt)
```

using Kotest Version : 5.4.1
and all 5.X.X version gives this error when I run the kotest test 

Is there any solution to resolve this error?

**Comment by SonYoonSeok** [comment]
I think it's because function Duration.milliseconds is deprecated. I'll modify it, and send PR Thanks.

**Comment by charleskorn** [comment]
Could you please try with Kotest 5.4.2? This issue should be fixed in that version.
