### ISSUE TITLE
Support for nested tests on JS target (again)

### ISSUE THREAD

**Issue by ptitjes** [kotest/kotest#3141]
Nested tests on JS target were working in 5.0.0. However, it seems to be broken in newer versions.

One of the good things of Kotest is the ability to have nested tests. However, nested tests not working on the JS target means that you're stuck to not using this feature as soon as you have a multiplatform Kotlin project that also targets JS (which is supposed to be a lot of projects). This is a feature that is tremendously useful to organize tests in big projects.

I have seen [here](https://github.com/kotest/kotest/issues/2453#issuecomment-911038589) that @sksamuel says:
> On JS it's not possible without changing Kotest in breaking ways.

However, nested tests are supported in (almost) all test runners in the JS world. So it would seem that the problem comes from Kotest design.

In addition, in some Slack discussion that I can't find again, @sksamuel said that the problem comes from intermediate (container) levels use suspending lambda. I am wondering why this is, as from my point of view, suspending lambdas only make sense for the content of individual tests and before/after hooks.

I also have seen that there is a [work-in-progress PR](https://github.com/kotest/kotest/pull/2957) on this subject.

@sksamuel could we please discuss what needs to (breaking) change in Kotest to support this?

**Comment by sksamuel** [comment]
The Javascript test runners don't support promises at the outer layer.

Eg in mocha,

```
describe("foo") {  <---- does not support promises
   test("bar") { <--- supports promises
    }
}
```

Therefore we cannot use coroutines anywhere but the final scope. Since kotest supports coroutines at every layer, the only way to make it work in JS land is to support flat tests only. Unless you can find a JS test runner that supports promises at every level of nesting.

The alternative would be to change kotest to not support coroutines anywhere but the final scope, and that would be a) a huge breaking change and b) reduce the functionality for anyone in JVM land.

**Comment by sksamuel** [comment]
It looks like https://github.com/substack/tape might supported nested async tests, so we could explore that for Kotest 6.0

**Comment by ptitjes** [comment]
@sksamuel I can't find anything in Tape's documentation about nested async tests (that also have the top levels async). Would you mind pointing something to me? I am not against trying to make an implementation.

Also, I understand that it would indeed be a huge breaking change. However, I am not sure to understand the interest of having the top levels being async too.
The only thing I can see would be to use asynchronous retrieval from a database to load metadata to build test cases. Is that it?

**Comment by sksamuel** [comment]
Aside from whether it's a good idea or not to have async parent tests, changing it now would break thousands of installs.

In tape it looks like a top level `test` comes with a callback `t` which can then fire more tests https://github.com/substack/tape#ttestname-opts-cb

**Comment by BenWoodworth** [comment]
Very much a hack, but I got this working which suits my needs, and should be easy to migrate over if/when nested JS test support is added: [FlatSpec.kt](https://gist.github.com/BenWoodworth/0fd0e463fdfc71c30f2a114da5c14672)

**Obligatory disclaimer**: use with caution. No guarantee it'll work in future releases, as using `FunSpec` in this way is almost certainly not supported. That being said though, feel free to use it, <ins>just leave the block comment</ins> for any future travelers who may be (mis)fortunate enough to stumble upon it :)

![image](https://user-images.githubusercontent.com/1829157/195756306-c9c11e36-e81c-4003-94ed-cb69419433d3.png)

**Comment by aSemy** [comment]
Maybe using kotlin.test could help with dynamic test registration on JS?

https://discuss.kotlinlang.org/t/kotlin-test-js-specifying-test-without-annotation/11280

> [piacenti](https://discuss.kotlinlang.org/u/piacenti) [Jan '19](https://discuss.kotlinlang.org/t/kotlin-test-js-specifying-test-without-annotation/11280/2)
> 
> I found a way to create the tests without the annotation and they work.
> Very quick and dirty:
> 
> ```kotlin
> import kotlin.test.Test
> import kotlin.test.assertTrue
> 
> @JsModule("kotlin-test")
> @JsNonModule
> external val kTest: dynamic
> 
> class TestJs {
> 
>   @Test
>   fun blah() {
>     kTest.kotlin.test.suite("package test", false) {
>       kTest.kotlin.test.suite("suit test", false) {
>         kTest.kotlin.test.test("test", false) {
>           assertTrue(true)
>         }
>       }
>     }
>   }
> }
> ```
> 
> But not perfect yet since karma seems to have the counts a bit messed up. I had 4 test before adding this code and then it went to 6 tests out of 4.
> ```
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 0 of 4 SUCCESS (0 secs / 0 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 1 of 4 SUCCESS (0 secs / 0.005 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 2 of 4 SUCCESS (0 secs / 0.006 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 3 of 4 SUCCESS (0 secs / 0.009 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 4 of 4 SUCCESS (0 secs / 0.01 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 5 of 4 SUCCESS (0 secs / 0.01 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 6 of 4 SUCCESS (0 secs / 0.01 secs)
> HeadlessChrome 72.0.3617 (Windows 10.0.0): Executed 6 of 4 SUCCESS (0.105 secs / 0.01 secs)
> ```
> 
> Making the test class an object gets rid of the additional duplicate tests generated by the code above
> 

I've fleshed this out and created a working example on Kotlin 1.8.10, JS IR browser

```kotlin
import kotlin.test.Test
import kotlin.test.assertTrue

@JsModule("kotlin-test")
@JsNonModule
external val kTest: dynamic

class TestJs {

  // some dummy service that we'll test
  class UsernameValidator {
    fun isValid(username: String?) = username!!.isNotBlank()
  }

  @Test
  fun passwordValidationTests() {
    // create an outer context
    context("Given a password validator") {
      val usernameValidator = UsernameValidator()

      // nest some inner contexts + tests
      context("When username is very long") {
        val username = "very long username ".repeat(100)
        test("Then expect validation passes") {
          assertTrue { usernameValidator.isValid(username) }
        }
      }
      context("When username is not blank") {
        val username = "foo bar"
        test("Then expect validation passes") {
          assertTrue { usernameValidator.isValid(username) }
        }
      }

      // tests + contexts can be dynamically added
      mapOf(
        "blank" to "   ",
        "null" to null,
      ).forEach { (failureReason, username) ->
        context("When username is $failureReason") {
          test("Then expect validation fails") {
            assertTrue { usernameValidator.isValid(username) }
          }
        }
      }
    }
  }
}

/** Test context - for nesting tests */
fun context(name: String, ignored: Boolean = false, contextBlock: () -> Unit) {
  kTest.kotlin.test.suite(name, ignored) {
    contextBlock()
  }
}

/** Execute a test */
fun test(name: String, ignored: Boolean = false, testBlock: () -> Unit) {
  kTest.kotlin.test.test(name, ignored) {
    testBlock()
  }
}
```

Example result:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/897017/218256800-42217012-9184-4c66-abba-298489b8aa59.png">

So the tests aren't nested, but kotlin.test will prepend the contexts to the test name.

**Comment by eygraber** [comment]
Is there any plan to support this anytime soon? I'm porting a JVM library to KMP and running into this issue when adding a js target. I'd hate to move away from kotest and there are hundreds of tests that are affected.

**Comment by sksamuel** [comment]
It's going to be added when we can build on top of compiler plugins stably. I am hoping that will be after Kotlin 2.0 is released.

**Comment by nickolay-kondratyev** [comment]
@sksamuel [suspend functions are added for KotlinJS export in Kotlin 2.3](https://kotlinlang.org/docs/whatsnew-eap.html#new-export-of-suspend-function-with-jsexport), does it help move forward on allowing nested tests in JS?

**Comment by sksamuel** [comment]
> [@sksamuel](https://github.com/sksamuel) [suspend functions are added for KotlinJS export in Kotlin 2.3](https://kotlinlang.org/docs/whatsnew-eap.html#new-export-of-suspend-function-with-jsexport), does it help move forward on allowing nested tests in JS?

I don't think so. The underlying issue is that karma etc don't support promises in their "describe" blocks.
