### ISSUE TITLE
shouldMatchJsonResource requires fields in order

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3145]
**Which version of Kotest are you using** 5.4.1

**Comment by sksamuel** [comment]
@Kantis thoughts on this ?

**Comment by Kantis** [comment]
Are you saying that

```kotlin
val a = """ { "a": 1, "b": 2 }"""
// b.json: """ { "b": 2, "a": 1 }"""

a.shouldMatchJsonResource("b.json") // fail?
```

`shouldEqualJson` would accept that difference, so I think `shouldMatchJsonResource` should too.

**Comment by Kantis** [comment]
I added a couple of tests here to check: https://github.com/kotest/kotest/commit/aa750b1e97402d948bbabde964b11f06edfb9361

Seems array order matters, and property order doesn't, which is in line with the [defaults for shouldEqualJson](https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-json/src/commonMain/kotlin/io/kotest/assertions/json/compare.kt#L71). Perhaps we could add some options to make it configurable though..

**Comment by sksamuel** [comment]
Ok we can close this, seems I was just being a muppet.
