### ISSUE TITLE
Is there any way to clear all mocks after each data testing?

### ISSUE THREAD

**Issue by progresivoJS** [kotest/kotest#3155]
### Problem

I want to clear mocks after each data testing.
The problem case is following.

```kotlin
forAll(
  row(..),
  row(..),
) { x, y ->
  sut.execute()
  verify { mockked.handle() }
}
```
In this case, verifying `mockked.handle()` may fail, because in this test function, single mockked instance is used.

### Ugly Solution
Currently, the second best solution is just to append `clearAllMocks()` after each data testing.
```kotlin
forAll(
  row(..),
  row(..),
) { x, y ->
  sut.execute()
  verify { mockked.handle() }
  clearAllMocks() // Ugly code.
}
```

Is there any idea for this problem?

FYI. I used mockk.

**Comment by progresivoJS** [comment]
I look through data-driven testing, and found some facts.

1. `forAll` style data-driven style is obsolete, and `withData` style was introducted after 4.5.0.
2. I cannot use `withData` style, because I currently use `AnnotationSpec`.
3. With `withData`, the same problem occurs.

**Comment by yongjoon-km** [comment]
How about using [PropTestListener](https://kotest.io/docs/proptest/property-test-config.html#proptestlistener) ?

**Comment by progresivoJS** [comment]
> How about using [PropTestListener](https://kotest.io/docs/proptest/property-test-config.html#proptestlistener) ?

I wish I want.
On my comprehension, [driven-driven testing](https://kotest.io/docs/framework/datatesting/data-driven-testing.html) and [property testing](https://kotest.io/docs/proptest/property-based-testing.html) is different feature in Kotest.

Is there any same thing with `PropTestListener` in data-driven testing ?

**Comment by sksamuel** [comment]
data-driven-testing gets mapped to actual tests, so you can use the regular beforeTest {} callback.
But not in annotation-spec.

**Comment by progresivoJS** [comment]
As you mentioned, I solved this problem, with `ShouldSpec` and `withData`, but not with `forAll`.
I think this detail should be mentioned in documentations.


```kotlin
beforeTest {
  clearAllMocks() // or Initialize mock newly.
}

context("...") {
  withData(X, Y, Z) { variable ->
    sut.execute()
    verify { mockked.handle() }
  }
}

```

**Comment by sksamuel** [comment]
Thanks, docs updated.

**Comment by progresivoJS** [comment]
Related commits:
- https://github.com/kotest/kotest/commit/185953655a606c2242216f4b6c50e42ea4f107ab
- https://github.com/kotest/kotest/commit/f638ee9ae7df2fe75fed92db10d256b558228075
