### ISSUE TITLE
shouldBe() / shouldNotBe() don't chain

### ISSUE THREAD

**Issue by jlous** [kotest/kotest#3170]
kotest 5.4.2

I'm testing some mapping and transformation code, and sometimes there can be some benefits to asserting against external test data in stead of hardcoded inline constants. But this carries the risk that the test data may be incomplete, outdated or corrupted, and you end up with a test that looks god but actually compares null to null, which might pass even if the relevant mapping code is faulty or missing entirely. 

To guard against this, i add a null check for the nullable feilds, and chaining is a clear and succinct way to do it:  
```
with(outboundEvent.data) {
    ...
    purpose.shouldNotBeNull() shouldBe src.purpose
```
(i use infix syntax for consistency with the rest of my test, and function syntax for the null check because I have to) 
This works fine, but my first attempt did not:
```
    purpouse.shouldNotBe(null) shouldBe src.purpouse
```
Apparently shouldtNotBe (and shouldBe) returns Unit, not T as all the chainable asserts.
Why this inconsistency?

**Comment by jmfayard** [comment]
`shouldBe` doesn't need to chain IMHO

Chaining is useful for `Person.birtyday.month.shouldBeGreaterThan(1).shouldBeLessThan(12)`

But if you already know `randomDice.shouldBe(4)`, what's the point in additional chaining?

`randomDice.shouldBe(4).shouldBePositive().shouldNotBe(5).shouldNotBe(3)`

You (should) already know exactly what 4 is!

>    purpose.shouldNotBeNull() shouldBe src.purpose

I would replace by simply 

```kotlin
src.purpose.shouldNotBeNull() // only if src.purpose is nullable
purpose shouldBe src.purpose
```

I think `shouldNotBe` should chain on the other hand

`Person.birtyday.month.shouldBePositive().shouldNotBe(0).shouldBeLessThan(12)`

**Comment by sksamuel** [comment]
And the 2nd last one can be `src.purpose.shouldNotBeNull() shouldBe purpose`

**Comment by jlous** [comment]
Yes, i know that chains can be broken into separate asserts, and I know that inverting the assertion to test on the expectation in stead of the actual technically does the same thing.
I could also do everything with assertTrue.

What I don't get is why prevent me from doing it the way that makes the most expressive and aesthetic sense to me.

**Comment by sksamuel** [comment]
I think he (and I) are agreeing with you on shouldNotBeNull. On the shouldBe, @jmfayard is arguing you know the exact instance anyway. Do you have an example of that case ?

**Comment by jlous** [comment]
Fair enough, the negative is the one I actually had use for.  But it feels odd to drop chaining when that is the norm. Unless there is a real tradeoff, of course. I was half expecting adding chaining to these would have unwanted repercussions.

**Comment by sksamuel** [comment]
If it literally has no impact, then yes I don't see the harm in changing it.
However I know in the past, Kotlin treated functions returning Unit differently from functions returning T. So if by changing this, we break anything where the last statement was a shouldBe is now not Unit, then we can't really do this.

**Comment by sksamuel** [comment]
See #3186
