### ISSUE TITLE
kotest artefacts for watchosX86 5.4.2 isn't published

### ISSUE THREAD

**Issue by i-walker** [kotest/kotest#3176]
the latest artefact for kotest-assertions-core-watchosx86 is 5.4.1 
https://search.maven.org/artifact/io.kotest/kotest-assertions-core-watchosx86/5.4.1/klib

Expected behaviour:
5.4.2 should exist too

**Comment by Kantis** [comment]
Fixed, https://repo1.maven.org/maven2/io/kotest/kotest-assertions-api-watchosx86/5.4.2/
