### ISSUE TITLE
Read/write Table data to a file format maybe CSV

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#3179]
Table testing is nice

```kotlin
val table: Table3<String, String, String> = table(
    headers("mavenDependency", "kotlinName", "versionName"),
    row("io.kotest:kotest-core", "Testing.kotest.core", "version.kotest"),
    row("io.kotest:kotest-assertions-arrow", "Testing.kotest.assertions.arrow", "version.kotest"),
)
table.forAll { mavenDependency, kotlinName, versionName ->
    listOf(mavenDependency, kotlinName, versionName).all { it.contains("kotest") } shouldBe true
}
```

The issue is my table contains 1000+ rows currently so I'm reinventing the wheel on how to read it from a text file / write it to a text file https://github.com/jmfayard/refreshVersions/blob/main/plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt

It would be really useful to have a simple way to read that data from a (CSV?) file

`fun File.readTable3<A,B,C>(headers: Headers3, map: Sometype -> Row3<A, B, C>) : Table<A,B,C>`

I can volunteer to implement that if you think the feature makes sense.

**CsvDataSource**

While researching for writing this ticket, I found out that there used to be a `CsvDataSource`class for this https://github.com/kotest/kotest/search?q=CsvDataSource&type=code

```kotlin
val source = CsvDataSource(javaClass.getResourceAsStream("/user_data.csv"), CsvFormat())

val table = source.createTable<Long, String, String>(
     { it: Record -> Row3(it.getLong("id"), it.getString("name"), it.getString("location")) },
     { it: Array<String> -> Headers3(it[0], it[1], it[2]) }
)
```

But it was removed in an apparently unrelated commit? https://github.com/kotest/kotest/pull/1457

**Comment by sksamuel** [comment]
This would be great - but I wouldn't want to introduce a CSV library dependency to the main framework.

I would do something like this:

Add an interface called `DataSource2|3|4|5` (or something), which exposes a method for return a list of tuples. Then add a new module to the build, `kotest-framework-datatest-csv` which implements those interfaces, and loads from a CSV file and returns the tuples to be used.

So the end user experience might be something like:

```kotlin
context("my tests") {
  withData(createCsvDataSource4("/resource.csv")) { a, b, c, d -> 
  }
}
```

Since the withData needs to know the type, I can't think of a way around having interfaces for each arity, each returning a TupleN type.

Thoughts ?

**Comment by jmfayard** [comment]
@sksamuel 
two questions:

1. how would type conversions from string work? I hacked something around, any thoughts?
https://github.com/jmfayard/my-kotlin-scripts/blob/49f49dda42c9d529d143c7494f2838c6c851f567/src/test/kotlin/kotest/DataSource.kt#L14-L52

2. how nasty is CSV parsing? in its simple version it seems trivial, but I can imagine there are a lot of hidden surprises. isn't it something we can do on our own? if not, any small library you would recommend?

**Comment by Kantis** [comment]
>     2. how nasty is CSV parsing? in its simple version it seems trivial, but I can imagine there are a lot of hidden surprises. isn't it something we can do on our own? if not, any small library you would recommend?

There's a few pitfalls afaik. Splitting `a,b,c` is simple, of course.. but if the `a,b` is supposed to be the _String_ a,b instead, you need to support quoting. `"a,b",c`, now the ambiguity is removed there.. But what if the text needs to contain a quote as well? 😉  

Perhaps you want to support having a header-row too. It should be excluded when running the tests, but which would greatly help when looking at and editing the CSV file.

**Comment by hakanai** [comment]
> There's a few pitfalls afaik. Splitting `a,b,c` is simple, of course.. but if the `a,b` is supposed to be the _String_ a,b instead, you need to support quoting. `"a,b",c`, now the ambiguity is removed there.. But what if the text needs to contain a quote as well? 😉

Not sure if joking, but if you want to write `a"b`, then you write `"a""b"`. That is well documented in RFC 4180, and far from the most annoying thing about the format.

Edge cases I am aware of from having implemented it a couple times in different languages:

1. Cases where the presence or absence of double quotes in the cell changes the meaning of the value:    - A pair of double quotes that is _not_ inside a quoted sequence is, of course, just an empty string. But having nothing in the cell is an empty string too, and some apps use this something like the difference between an empty string and null.
    - Sometimes, a number unquoted means a number, whereas quoted, it means a string.
    - Likewise, sometimes true, false, null (and uppercase versions of the same) mean the non-string value, but when you quote them, they mean the string.

2. Cases where the RFC doesn't document how to do it, so people go off in all directions:
    - There is no standard way to encode dates. One time, we tried to fix date formatting so that it behaved exactly like Excel and people could assume the CSV files would transfer between our app and Excel, but guess what? People don't like that, because they have these gigantic macros that were written by some savant years ago that nobody knows how to update, so when you change the output of anything, people immediately start crying.
    - In case the variance of the date format was bad enough, all the dates and times tend to be in local time too.
    - The encoding of the file may or may not be UTF-16LE, UTF-8, or a Windows local encoding, and the best chance you have of detecting it is the file having a BOM. If it doesn't have a BOM, good luck and have fun!
    - Sometimes there is an additional separator for packing multiple values into a single cell, like a colon, semicolon, vertical pipe. If you're dealing with dense data, this additional separator is your best friend, because the alternative is exploding your data into individual cells, or encoding it some other way.

3. Cases which the RFC documents things perfectly well, but people still screw up:
    - If you have a line like `a,b,c,,,,`, that is 4 empty cells after the `c` cell, not 3.
    - The escaping of double quote characters is _not_ by preceding them with a backslash, no matter how many online help pages say it's valid.
    - Single quotes are not really a valid substitute for double quotes either, but they have been seen in the wild.
        - (Then again, the goal isn't to support 100% of CSVs, is it, so you have it a lot easier than we had it.)

How to deal with the stuff:

- For a lot of the nonconformance stuff, you have an options object where you can specify:
    - supported quote characters
    - supported escape methods
    - file encoding (BOMless UTF-8 as default, obviously)
    - Instead of the options object being an explicit thing, it could be part of the builder used to create the reader perhaps?
    - Prepare an RFC4180 implementation which is preconfigured to follow the RFC to the letter.

- For converting strings to values
    - Some generic Parser<T> API?, copy how it's done for things like `checkAll(Arb.int(), Arb.string())`. The lambda parameters should just automatically match the type converters / parsers passed in.
    - Even this might be able to be done at the reader builder..?
    - You might want an additional overload where the caller provides conversion for an entire row to whatever data type they want.
    - You could push things like dates and times back on the user of the API, but lately we have seen a few bits and pieces getting standardised in Kotlin, and something like kotlin time `Instant` parser that only supports RFC 9557 / ISO 8601 formats would be really handy for some people.

- I agree that an option to have a header line would be useful, it's really handy when you want to insert a new column later.
    - The existing CSV reader APIs I have used generally returned row records as `List<String>`, but if you specified headers, it would let you get them as `Map<String, String>`. A bit like having named groups in a `MatchResult`, I suppose.
    - I think a builder might be a better option than that - the method to specify that a header is present could return a different builder interface, and the resulting reader could return different record types for each row.

The only bit I have never been all too keen on is, fallback behaviour when things are invalid. Maybe this is the one time where you could just say "screw it, fix the file"?

Other related stuff...

`kotest-assertions-table` has quite a bit of the solution already, right? You could divide this into two separate tasks:
1. A way to go from CSV to a table where all the cells are just strings
2. A tidy API to convert the string tables to typed tables. I'd hate to think how much crazy overloading is going to be going on in that one, but it would be the kind of thing that would be useful for inline string tables just as much as CSV. I mean, it's just two different ways to pack a string into a larger table structure.
