### ISSUE TITLE
regex.shouldMatchAll(validInputs).shouldNotMatchAny(invalidInputs)

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#3180]
Bonjour,

> Some people, when confronted with a problem, think: “I know, I'll use regular expressions.”   
> Now they have two problems. 

The famous quote correspond to an experience that has been too often true (I've programmed in Perl long ago).
But saying that Regex are bad per se is dogmatic and wrong. 
Instead I have a rule that regex are one of the possible way to parse data, and that there can be accepted **if and only if they come with the corresponding unit tests**

kotest does not have any Regex-related assertions AFAIK, would you like me to contribute some?

My custom matchers [look like this at the moment](https://github.com/jmfayard/my-kotlin-scripts/blob/a2025a10cf380424fa29beec0c3d74232ac4bb10/src/test/kotlin/kotest/KotestMatcher.kt#L51-L75)

```kotlin
@Test
fun `it's ok to use regex if and only if they come with unit tests`() {
    val regexUrl = Regex("^https?://(?:www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b[-a-zA-Z0-9()@:%_+.~#?&/=]*\$")
    val validUrls = listOf(
        "http://example.com",
        "https://api.github.com/v1/pull_request/7891?limit=3",
        "http://password@patrick:example.com/endpoint?a=bde#ab",
    )
    val invalidUrls = listOf(
        "contact@gmail.com",
        "ssh://my-computer.aws.com/etc/passwords",
    )
    regexUrl
        .shouldMatchAll(validUrls)
        .shouldNotMatchAny(invalidUrls)
}
```

**Comment by sksamuel** [comment]
Kotest has shouldMatch, shouldNotMatch, shouldContain and shouldNotContain, all of which accept Regex versions.

**Comment by sksamuel** [comment]
I think what we are missing is the the same thing with the parameters flipped, so:

`Regex.shouldMatch(str)`
`Regex.shouldNotMatch(str)`
`Regex.shouldMatchAll(strs)`
`Regex.shouldMatchNone(str)`

And a group extractor might be good.

`Regex.shouldMatchWithGroups(str, g1, g2)` or something ?

**Comment by jmfayard** [comment]
> Kotest has shouldMatch, shouldNotMatch, shouldContain and shouldNotContain, all of which accept Regex versions.

Good to know!

> I think what we are missing is the the same thing with the parameters flipped, so:

I think so too:

When using `person.uuid shouldMatch uuidRegex,` it feels like I am testing my **string** "person.uuid"

When using `uuidRegex.shouldMatch("123e4567-e89b-12d3-a456-426655440000")`, it feels like I am testing that my **regex** "uuidRegex".

> Regex.shouldMatchWithGroups(str, g1, g2) or something ?

Sounds good to me
