### ISSUE TITLE
@Tags doesn't work with inheritance.

### ISSUE THREAD

**Issue by progresivoJS** [kotest/kotest#3196]
Version: Kotest 5.4.2

##### `TagTest` is included in tests with `-Dkotest.tags=local` args.
It works as I expected.

```kotlin
@Tags("local")
class TagTest : ShouldSpec({
    should("test") {

    }
})
```

##### `TagTest` is _not_ included in tests with `-Dkotest.tags=local` args.
It doesn't work as I expected. What I expect is that it works well like the first example code.

```kotlin
class TagTest : LocalTest({
    should("test") {

    }
})

@Tags("local")
abstract class LocalTest(body: ShouldSpec.() -> Unit) : ShouldSpec(body)
```

**Comment by progresivoJS** [comment]
```kotlin
class TagTest : LocalTest({
    should("test") {

    }
})

abstract class LocalTest(body: ShouldSpec.() -> Unit) : ShouldSpec(body) {
    override fun tags(): Set<Tag> {
        return setOf(Tag("local"))
    }
}
```

I found that when I override `tags` method, It works well as I expected.
This `TagTest` is included in tests with `-Dkotest.tags=local` args.

There is a workaround, so I feel it is not critical bug.

**Comment by Kantis** [comment]
This feels like an anti-pattern to me.

Explicitly tagging the Spec and not inheriting behavior makes it clearer what's going on with it, what kind of spec it is, etc. So sticking with this I believe is best option:

```kotlin
@Tags("local")
class TagTest : ShouldSpec({
    should("test") {

    }
})
```

Potentially you could avoid duplication of the constant value across Specs, with risk of typos, by doing:
```kotlin
const val LOCAL = "local" // Define in KotestTags.kt or something, to make it clear what it's for.

@Tags(LOCAL)
class TagTest : ShouldSpec({
    should("test") {

    }
})
```

**Comment by progresivoJS** [comment]
Your suggestion, adding constant for the tag, is nice for me, but I partially agree with your opinion.
From my perspective, there's pros and cons for this pattern.

**Pros for this pattern.**
- I feel it's easier to forget to add `@Tags` than to use `LocalTest`, not `ShouldSpec`.
- I feel to add `@Tags` for tests is a little bit verbose.
- If I contain phase in a base class name like `LocalTest`, which is annotated with `local` tag, It can be expressive.

**Cons for this pattern.**
- As you mentioned, It's somewhat implicit.

**Comment by Kantis** [comment]
Thanks. I respect that it's a matter of taste and perhaps I was being too opinionated. :) 

I made a draft for this here: https://github.com/kotest/kotest/pull/3199

**Comment by progresivoJS** [comment]
Thank you for understanding, @Kantis !

**Comment by Kantis** [comment]
Tag inheritance can now be enabled  in Kotest 5.5, enjoy :)
