### ISSUE TITLE
Failed to run single test with multiline name

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [kotest/kotest#3203]
kotest - 5.4.2
kotest intellij plugin - 1.2.59-IC-222-EAP-SNAPSHOT
relates to - #1441

When I run the test by clicking "play" near the test name with multiline name, the test won't run.
I am able only to run tests for whole class. I assume that this is a bug in kotest intellij plugin, we should remove new lines from test name to fix this, right?

![image](https://user-images.githubusercontent.com/15987499/188637753-fcefa3f9-d882-4faf-b93b-575b69637408.png)![image2](https://user-images.githubusercontent.com/15987499/188637544-49bd89e2-b0b8-438f-95a9-b9c4e2b38722.png)

**Comment by p1729** [comment]
@LeoColman / @sksamuel  I would like to work on this. However, I would need your help to find the problematic code. I suspect an issue [here](https://github.com/kotest/kotest-intellij-plugin/blob/b8312037481de4850dbd5e6f8a37d72e33265049/src/main/kotlin/io/kotest/plugin/intellij/Test.kt#L20) 🤔 ? Also, how do we test the plugin
