### ISSUE TITLE
I am getting "Specs must have a public zero-arg constructor" in the integrationTest source set

### ISSUE THREAD

**Issue by ckosmowski** [kotest/kotest#3209]
Kotest version: 5.3.5.0

I cannot get kotest to work with my integrationTest source set. I have read several similar issues before as well as the according answers on StackOverflow. I made sure useJunitPlatform is active for the integrationTest sourceSet and all required dependencies are there.

This works perfectly in the integrationTest module
```kotlin
@MicronautTest(environments = ["it"])
@Property(name = "dpx.kafka.mock", value = "true")
class OverallProcessTest : AnnotationSpec() {
    @Test
    fun `noop test`() {
        true shouldBe true
    }
}

````
This does not work in the integrationTest module (only difference is the variable that should be injected). 
I am getting the error: "Specs must have a public zero-arg constructor"

```kotlin
@MicronautTest(environments = ["it"])
@Property(name = "dpx.kafka.mock", value = "true")
class OverallProcessTest (
    private val mockKafkaConsumerFactory: MockKafkaConsumerFactory
) : AnnotationSpec() {
    @Test
    fun `noop test`() {
        true shouldBe true
    }
}
````

However the exact same test works well if i copy it to the test module instead of integrationTest and uses the exact same framework mechanisms there.

**Comment by sksamuel** [comment]
Kotest cannot create a class without a zero arg constructor (as it wouldn't know what to pass in), so there has to be some extension doing that for you. In this case, it would seem the MicronautTest extension that does - so it's perhaps configured in one env and not the other.

**Comment by ckosmowski** [comment]
Thanks for the answer! It was actually necessarry to add an extension called "MicronautKotest5Extension" that seems to do exactly what you described, which i did weeks before for the test module but missed out for integrationTest.
