### ISSUE TITLE
kotest-assertions-arrow does mention the correct version

### ISSUE THREAD

**Issue by okarmazin** [kotest/kotest#3211]
[`kotest-assertions-arrow`](https://kotest.io/docs/assertions/arrow.html) does not mention the fact that its versioning is independent from the main Kotest libraries. One has to go to the [Maven repo](https://repo.maven.apache.org/maven2/io/kotest/extensions/kotest-assertions-arrow/) to find the current version.

**Comment by sksamuel** [comment]
Thanks for the heads up. Docs have been clarified.
