### ISSUE TITLE
Test spec not run with Kotest 5.5.0

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#3223]
We just [upgraded to Kotest 5.5.0](https://github.com/oss-review-toolkit/ort/pull/5897), and now it's not possible anymore to run all tests in a spec by pressing on the green "double play" button in the gutter; all test cases are ignored. Running individual test cases still works.

The log looks like

```
> Task :reporter:funTest
11:58:30.105 [Test worker @coroutine#1] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
org.ossreviewtoolkit.reporter.reporters.ExcelReporterFunTest > ExcelReporter should STARTED
org.ossreviewtoolkit.reporter.reporters.ExcelReporterFunTest > ExcelReporter should SKIPPED
BUILD SUCCESSFUL in 13s
42 actionable tasks: 19 executed, 8 from cache, 15 up-to-date
11:58:30: Execution finished ':reporter:funTest --tests "org.ossreviewtoolkit.reporter.reporters.ExcelReporterFunTest" -Dkotest.assertions.multi-line-diff=simple'.
```

**Comment by sschuberth** [comment]
Given that I get the same behavior when running via Gradle directly from the command line, this issue should probably be transferred to kotest/kotest.

**Comment by joni-** [comment]
We noticed similar behaviour after upgrading to 5.5.0. Running tests with `./gradlew test` works but targeting a specific spec with `./gradlew test --tests "com.foo..."` ignores the tests. Downgrading back to 5.4.2 fixed the issue.

**Comment by Kantis** [comment]
5.5.1 is on the way out with the fix.
