### ISSUE TITLE
Access to TestScope.backgroundScope

### ISSUE THREAD

**Issue by matejdro** [kotest/kotest#3226]
[Coroutines 1.6.4](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.6.4) introduces `TestScope.backgroundScope`.

Unfortunately, kotest only takes `coroutineContext` from TestScope, it does not expose TestScope anywhere, making new `backgroundScope` inaccessible.

Could this be exposed somewhere?

**Comment by sksamuel** [comment]
Using the coroutines `TestScope` looks handy, but also means plugging into the entire test machinery they provide. Might be easier to just provide the same `backgroundScope` functionality.

**Comment by matejdro** [comment]
Ideal thing from the user's perspective would be kotest's TestScope extending coroutines's TestScope. That way user gets all top-level extensions (such as `runCurrent` and `advanceTime`) and direct access to all current and future TestScope features (such as backgroundScope) automatically and since it would be the receiver, using them would be very ergonomical.

But I understand that actually implementing that would be messy, especially since `coroutineTestScope` can be turned off. Maybe it would be implemented even when `coroutineTestScope` is disabled, but all its methods would throw exception that they are not supported when disabled?

**Comment by matejdro** [comment]
This is still an issue

**Comment by sksamuel** [comment]
I like the idea of Kotest's TestScope extending the coroutine TestScope. It is experimental right now though I think, and Jetbrains will often change things that are marked as experimental. So perhaps once Kotlin 1.8 comes out we make this change then (and as part of Kotest 6.0) ?

**Comment by matejdro** [comment]
We can't outright extend it, because coroutine's TestScope is sealed. I've tried to create a compromise in the linked PR.

**Comment by sksamuel** [comment]
Yeah I saw that in your PR after I typed that comment out.
