### ISSUE TITLE
Incorrect number comparison in kotest 5

### ISSUE THREAD

**Issue by trourance** [kotest/kotest#3235]
There's an inconsistency between `shouldMatchJson` and `shouldEqualJson` in comparison of numbers written in scientific notation.

This one succeeds: `"1436712339.124" shouldEqualJson "1.436712339124E9"`
This one fails: `"1436712339.124" shouldMatchJson "1.436712339124E9"`

In kotest 4, both succeed.

**Comment by Kantis** [comment]
`shouldMatchJson` will using KotlinX serialization to parse expected and actual into `JsonElement`s and test them for equality. So I guess the inconsistency highlights a change in the underlying behaviour.

`shouldEqualJson` will by default do a "lenient" comparison (in the sense that we allow different formats if they represent the same _value_). See [NumberFormat](https://kotest.io/docs/assertions/json/content-json-matchers.html#parameters)

Should we  deprecate `shouldMatchJson` in favor of `shouldEqualJson`? They are both used for the same assertion ("json content should be.."), and `shouldEqualJson` has more customizability and better failure messages AFAIK.

**Comment by trourance** [comment]
But `shouldMatchJson` is more flexible regarding the position of the elements in the JSON structure, that's why we're using that one.

**Comment by sksamuel** [comment]
> Should we deprecate `shouldMatchJson` in favor of `shouldEqualJson`? They are both used for the same assertion ("json content should be.."), and `shouldEqualJson` has more customizability and better failure messages AFAIK.

I think we should probably do this in 5.5

**Comment by Kantis** [comment]
> But `shouldMatchJson` is more flexible regarding the position of the elements in the JSON structure, that's why we're using that one.

`shouldEqualJson` can be configured to ignore array order, and by default ignores property order. See [docs](https://kotest.io/docs/assertions/json/content-json-matchers.html#comparejsonoptions)

It could perhaps be made more convenient to use by allowing the alternate DSL (as dicussed in another issue) like,  
```kotlin
actualJson shouldEqualJson { 
  ignoreArrayOrder = true
  expectedJson
}
```

**Comment by trourance** [comment]
Excellent, I was not aware of that option. It will be a good substitute for our use cases, thanks.

**Comment by sksamuel** [comment]
shouldMatchJson  is now deprecated in favour of shouldEqualJson
