### ISSUE TITLE
Dependency `kotest-property` Not Available in BOM

### ISSUE THREAD

**Issue by akefirad** [kotest/kotest#3245]
**Which version of Kotest are you using**
`5.5.1`

I have to set the version for the dependency even though I imported the BOM file.

**Comment by sksamuel** [comment]
You can see kotest-property in the list:
https://search.maven.org/artifact/io.kotest/kotest-bom/5.5.1/pom

**Comment by sksamuel** [comment]
Your issue might have been because the entire bom was missing until Thursday.
