### ISSUE TITLE
Tests always ignored with Gradle 7.5.1 and Kotest 5.5.0 when running single test Class

### ISSUE THREAD

**Issue by miguelbaldi** [kotest/kotest#3249]
**Which version of Kotest are you using**
5.5.0

On Gradle 7.5.1, when running a single test class, the whole test is ignored:
`./gradlew --debug :app:test --tests "io.sample.gradle.kotest.MyTests"`
If I change do `kotest:4.6.4`, everything works.

Sample project: https://github.com/miguelbaldi/gradle-kotest

**Comment by myuwono** [comment]
@miguelbaldi try 5.5.1, i believe that was fixed in  #3223

**Comment by miguelbaldi** [comment]
Thank you @myuwono , 5.5.1 is working fine!
