### ISSUE TITLE
Gradle test regex are incorrectly applied

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest#3250]
# Context
`./gradlew test --tests A*` skipped all the tests in 5.5.1 - it used to work in 5.4.x.  The new modifications to kotest's Gradle Filter may have broken this functionality.

```
...AccountDetailsTest > json serialization/deserialization should round trip SKIPPED

AccountDetailsTest STANDARD_OUT

    ~~~ AccountDetailsTest ~~~
      + json serialization/deserialization should round trip: TestResult=Ignored(reason=json serialization/deserialization should round trip is excluded by test filter(s))
```

This is because Kotest's test filter was unable to translate that to correct path / classname / package name. 

# Potential Fix
Gradle supplies a well-formed regex to the engine that we can leverage to construct a regex object:
- `A*` becomes `\QA\E.*`
- `A*Test` becomes `\QA\E.*\QTest\E`
- `io.*.A*Test` becomes `\Qio.\E.*\Q.A\E.*\QTest\E`
- `io.*.A*Test.AccountDetails.fromString.*` becomes `\Qio.\E.*\Q.A\E.*\QTest.AccountDetails.fromString.\E.*`
- `io.*.A*Test.some test context.test name` becomes `\Qio.\E.*\Q.A\E.*\QTest.some test context.test name\E`

This means we can match the tests natively based on the complete path of tests.

**Which version of Kotest are you using**
5.5.1

**Comment by Kantis** [comment]
I think I probably broke this. Thanks for the detailed issue. I'll try to get some time to look into it this week.
