### ISSUE TITLE
timeout should be of type Duration? instead of Long? 

### ISSUE THREAD

**Issue by AnouarDoukkali** [kotest/kotest#3273]
**Which version of Kotest are you using**
version : 5.5.3

```
class TimeOutTest : StringSpec({
    timeout = 100.milliseconds //error: type Mismatch Type mismatch. Required:Long? Found:Duration
    "test case".config(timeout = 400.milliseconds) {
        println("hello world!")
    }
})
```

**Comment by Kantis** [comment]
Latest version of Kotest is 5.5.3. Are you sure you're on 1.22.0-RC2?

**Comment by AnouarDoukkali** [comment]
yes i'm sure, here's the dependencies update report:

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.43.0
 - io.gitlab.arturbosch.detekt:detekt-formatting:1.22.0-RC2
 - io.kotest:kotest-assertions-core-jvm:5.5.3
 - io.kotest:kotest-framework-datatest:5.5.3
 - io.kotest:kotest-property-jvm:5.5.3
 - io.kotest:kotest-runner-junit5-jvm:5.5.3
 - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.7.20
 - org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.7.20

**Comment by AnouarDoukkali** [comment]
sorry the 1.22.0-RC2 version was for Detekt plugin.  I'm using  5.5.3 version for Kotest

**Comment by AnouarDoukkali** [comment]
the same error is noticed for invocationTimeOut in Spec and Project Wide Settings :

```kotlin
class TimeOutTest:StringSpec({
    timeout = 100.milliseconds //error: type Mismatch
    invocationTimeout =100.milliseconds //error: type Mismatch
})

class ProjectWideSettings : AbstractProjectConfig() {

    override val invocationTimeout: Long? = 100.milliseconds  //error: type Mismatch
}
```

**Comment by Kantis** [comment]
I've been thinking about this one a bit. It would be nice to mark the old properties as deprecated and provide a migration path forward for users who already use the existing property. It's a bit unfortunate that the "desired name" is the same before and after this fix.

I wonder if we could simply add a deprecation notice for now on the current property, and replace them with durations in Kotest 6.0? Or should we just stick with the current implementation?

**Comment by AnouarDoukkali** [comment]
@Kantis timeout and invocationTimeout  in project level config ,spec config , and test config are all related  since each one override the one on top of it . I think it is best if they had all the most obvious type in kotest 6.0 to avoid problems
for example for the same duration :
```kotlin
timeout:Duration? = 100.nanoseconds 
timeout:Long?= // I wouldn't know what to put here 
```

**Comment by sksamuel** [comment]
We can't change it now without breaking everyone's tests. It's just a
historical artifact that kotest came out before durations existed.
