### ISSUE TITLE
switching kotest.framework.dump.config to false  in kotest.properties has no effect

### ISSUE THREAD

**Issue by AnouarDoukkali** [kotest/kotest#3275]
**Which version of Kotest are you using**
5.5.3

 **property kotest.framework.dump.config=false**  still print the configuration

---

Change [DumpConfigInterceptor](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/interceptors/DumpConfigInterceptor.kt#L26) to only dump config if `kotest.framework.dump.config` is set to `true` (ignoring case)

**Comment by Kantis** [comment]
How are you setting the property?

**Comment by AnouarDoukkali** [comment]
@Kantis in kotest.properties file

**Comment by Kantis** [comment]
Where did you put the file? Can you verify that it's actually in the build/target resource directory?

**Comment by Kantis** [comment]
Oh I just realized.. It's not a boolean property. Just by having the property exist the framework will dump the config. If you want to stop dumping just remove the property.

**Comment by sksamuel** [comment]
Maybe we should change it to be boolean ?

**Comment by AnouarDoukkali** [comment]
@sksamuel I think yes. since the documentation suggest to set the value to true

**Comment by Kantis** [comment]
Updated the original description with the required change.
