### ISSUE TITLE
NaN values in matchers are inconvenient, and inconsistent with other libraries

### ISSUE THREAD

**Issue by BenWoodworth** [kotest/kotest#3279]
**Which version of Kotest are you using**
Kotest 5.5.3

(I'm aware of #214, but I think this issue spans further than that)

In the simplest case, `NaN shouldBeExactly NaN` fails. And that's because Kotest checks `NaN != NaN`, which is false according to the IEEE standard.

## Use case / motivation
From a testing perspective though this is really inconvenient, especially when property testing and it's desirable to check that values are the *same*, not necessarily that they're "IEEE equal"

I've run into this twice so far when validating round-trip-serialization (value comes back the same as it went in), and when testing that a function delegates the call to another object with the same values. These tests both boiled down to this use case:

```kotlin
fun identity(value: Any): Any {
    return value
}

@Test
fun identity_with_doubles_should_return_the_same_value() = runTest {
    checkAll { double: Double -> // Property failed after 37 attempts. Arg 0: NaN
        identity(double)
            .shouldBeInstanceOf<Double>()
            .shouldBeExactly(double) // Caused by: NaN is not equal to expected value NaN
    }
}
```

## Other libraries
It's pretty commonplace to have an `assertAreTheSame(a, b)` as passing with both values being NaN, I assume for the same reasons I want to check that values are the same. For example:

kotlin.test: compares Doubles and Floats by `value.toBits()` ([in 1.7.20](https://github.com/JetBrains/kotlin/blob/v1.7.20/libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Utils.kt#L22-L52)):

junit 4: "[NaNs are considered equal](https://junit.org/junit4/javadoc/4.12/src-html/org/junit/Assert.html#line.539)"

junit 5: compares by Float.floatToIntBits ([in 5.9.1](https://github.com/junit-team/junit5/blob/r5.9.1/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java#L93-L95))

TestNG: Explicitly checks if both values are NaN, and considers them equal if they are ([in 7.6.1](https://github.com/cbeust/testng/blob/7.6.1/testng-asserts/src/main/java/org/testng/Assert.java#L675-L678))

### Boxed NaN
There's the awkward case of boxing. Boxed NaN equals itself even though a primitive NaN does not. And this is true for all Kotlin multiplatform targets:
```kotlin
val float = Float.NaN
val any = Float.NaN as Any

println("float: ${float == float}") // false
println("any: ${any == any}") // true
```

From [the Java docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#equals(java.lang.Object)):
> If [boxed floats] both represent Float.NaN, then the equals method returns true, even though Float.NaN==Float.NaN has the value false. 

### There are many different NaN values
From [this IBM page](https://www.ibm.com/docs/en/xcafbg/9.0.0?topic=SS3KZ4_9.0.0/com.ibm.xlf111.bg.doc/xlfopg/fpieee.html), there are large bit ranges of different NaN values with different semantics.

The other testing libraries I listed earlier consider any NaN to be the same as any other. `.isNaN` for junit 4 and testng, and `.toBits()` for junit 5 and kotlin.test (which consolidates all NaNs to a single canonicalized NaN value)

## Proposal
(I recognize that these are breaking changes)
- Keep `shouldBe` passing for any two (potentially different) NaN values (which it currently does since the inputs are boxed)
- Change `shouldBeExactly` to pass for NaN values
  - Potentially make it even stricter, using `.toRawBits()` so the bits have to be exactly equal. NaN values that don't have *exactly* the same bit representation fail
- Add a `beEqualTo` matcher that uses `==` for IEEE equality matching (like `shouldBeExactly` currently does), where NaN doesn't match 
- Keep all the other `...Equal...` matchers (e.g. `beLessThanOrEqualTo`, etc.) as they are

I'd love to open a PR for this. I just want to open an issue first and get feedback beforehand :)

**Comment by LeoColman** [comment]
I don't like having `shouldBe` passing for `NaN shouldBe NaN`, I also don't like it failing, as it's weird and inconvenient.

I like another option: Forbidding using `NaN shouldBe NaN` altogether. You must either use `double.shouldBeNaN()` or use actually-a-number to compare numbers.

We can start with keeping behavior and adding a warning to in the future failing the test pointing to the more appropriate matchers.


For the PropertyTesting problem, I think using `Arb.numericDouble` fits the use case, as you don't want `NaN` being generated for your comparison.

What do you think?

**Comment by sksamuel** [comment]
We could switch shouldBeExactly to allow nan == nan, to match other testing frameworks, and add a flag to revert behavior if desired by a user?

**Comment by BenWoodworth** [comment]
Sounds reasonable to me! Avoids bloating the API with too many ways to compare Floats. Plus we could even search codebases for that flag later on to see how widely it's used :)

**Comment by Kantis** [comment]
Would it be so bad to skip the flag initially? If someone wants the old behaviour they can raise an issue and we could add the flag then, after receiving that feedback.

**Comment by sksamuel** [comment]
Updated and flag added (was easy to just include the flag)
