### ISSUE TITLE
Property-based Testing: When an assumption always fails, the test runs indefinitely

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#3285]
When an assumption inside a `checkAll {}` always fails, the test keeps running indefinitely.

I expected that the test only runs 1000 times (since that is the default), and then fails because the percentage of 'skips' is greater than 50% (the default max discard)

Here is a dummy example, where the assume is hard coded to fail. However, it is relatively easy in real life to accidentally write an expression that always fails.

```kotlin
import io.kotest.property.Arb
import io.kotest.property.arbitrary.positiveInt
import io.kotest.property.assume
import io.kotest.property.checkAll
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test

class PBTAssumeTest {
    @Test
    fun `test assume true`(): Unit = runTest {
        checkAll(Arb.positiveInt()) { i ->
            println("${evals()}: $i")
            
            assume(false)
            
            // some assertions...
        }
    }
}
```

##### Versions

* Kotest 5.5.4
* Kotlin 1.7.21
* JUnit 5.8.2
* Kotlinx Coroutines 1.6.4

**Comment by sksamuel** [comment]
This is tricky because I originally had it so that assumptions would just filter out tests from the default number of invocations - and then people complained, and said that the invocations should be "tests that pass assumptions".

Maybe we just need a flag to config this, and default to the safe option.

**Comment by aSemy** [comment]
It's been a while since I looked at this, but I remember thinking that an additional counter would help, so there would be two counters:

* invocations
* failed tests

A failed test will increment both, but a failed assertion (a skipped test) will only increment 'invocations'. If either reach 1000, then the test will quit - but won't fail _unless_ the skip percentage is over 50%.
