### ISSUE TITLE
Ensure the CHANGELOG is up to date.

### ISSUE THREAD

**Issue by LouisCAD** [kotest/kotest#3286]
Hello, this page is constantly outdated: https://kotest.io/docs/changelog.html

It references version 5.5.0, but the latest version is 5.5.4.

Why isn't it updated right as the updated is deployed, or just before?

It's quite concerning to see an update, but no info on what it contains until you dig in the commit history.

**Comment by matejdro** [comment]
This appears to be up to date: https://github.com/kotest/kotest/releases

**Comment by Kantis** [comment]
Yeah, my bad. I forgot about that page, and I'm unsure if @sksamuel has some stuff to generate those notes. :) I'll try to update manually when I get some time..

**Comment by LouisCAD** [comment]
For refreshVersions, we maintain the changelog, and extract it automatically to put in the GitHub release:
https://github.com/jmfayard/refreshVersions/blob/077954fbd2e3ac821fbedba6a0e9fc23e1a714f1/Releasing.main.kts#L136-L143

**Comment by sksamuel** [comment]
I like to do it by hand because I like to ensure we cut out stuff that the
public isn't interested in (fixed typo in docs).
And then I make sure the contributors list is correct and has no
duplicates.

**Comment by LouisCAD** [comment]
That's what we do as well. The sync is done on the manually written changelog.
