### ISSUE TITLE
beforeEach/afterEach not working with data driven testing

### ISSUE THREAD

**Issue by marcogrcr** [kotest/kotest#3290]
**Which version of Kotest are you using?** 5.3.2

---

According to the [data driven testing docs](https://kotest.io/docs/framework/datatesting/data-driven-testing.html#callbacks) (emphasis added by me):

> If you wish to have before / after callbacks in data-driven tests, then you can use the standard `beforeTest` / `afterTest` support. Every test created using data-driven testing acts the same way as a regular test, so **all standard callbacks work as if you had written all the test by hand**.

When I use `beforeTest`/`afterTest` and `beforeContainer`/`afterContainer`, the callbacks are invoked as expected. However, when I use `beforeEach`/`afterEach`, the callbacks are not invoked as expected:

```kt
class DataDrivenCallbackTest : DescribeSpec({
  beforeTest {
    // EXPECTED: Invoked 4 times
    // ACTUAL: Invoked 4 times
  }
  beforeContainer {
    // EXPECTED: Invoked 1 time
    // ACTUAL: Invoked 1 time
  }
  beforeEach {
    // EXPECTED: Invoked 3 times
    // ACTUAL: Invoked 0 times
  }

  afterEach {
    // EXPECTED: Invoked 3 times
    // ACTUAL: Invoked 0 times
  }
  afterContainer {
    // EXPECTED: Invoked 1 time
    // ACTUAL: Invoked 1 time
  }
  afterTest {
    // EXPECTED: Invoked 4 times
    // ACTUAL: Invoked 4 times
  }

  describe("My container") {
    withData(
      "My test 1",
      "My test 2",
      "My test 3"
    ) {
      // test goes here
    }
  }
})
```

**Comment by aSemy** [comment]
I agree, it is confusing. I'm not sure why the distinction between 'dynamic' and 'test' is important. 

As a workaround you can try using `afterAny {}` or `beforeAny {}`.

Discussed in Slack

* https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1666788639534289
* https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1669322117072249

**Comment by mervyn-mccreight** [comment]
> I agree, it is confusing. I'm not sure why the distinction between 'dynamic' and 'test' is important.
> 
> As a workaround you can try using `afterAny {}` or `beforeAny {}`.
> 
> Discussed in Slack
> 
> * https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1666788639534289
> * https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1669322117072249

@aSemy 

I'm not sure whether I'm missing something, but as far as I can see this doesn't work well with nested `withData` usages, because you can't know inside the `beforeAny` if your `dynamic` instance is a leaf or not 🤔
