### ISSUE TITLE
Using NoSystemOutListener prevents single tests from being executed

### ISSUE THREAD

**Issue by koljakube** [kotest/kotest#3303]
It looks as if the messages printed by the plugin (about the skipped/ignored tests) are getting caught by the `NoSystemOutListener`, causing it to fail.

```
import io.kotest.core.spec.style.FreeSpec
import io.kotest.extensions.system.NoSystemErrListener
import io.kotest.extensions.system.NoSystemOutListener
import io.kotest.matchers.booleans.shouldBeFalse
import io.kotest.matchers.booleans.shouldBeTrue

class BugReportTest : FreeSpec() {
    override fun listeners() = listOf(NoSystemOutListener)
    init {
        "1" { true.shouldBeTrue() }
        "2" { false.shouldBeFalse() }
    }
}
```

Steps to reproduce:

1. Use the code above.
2. Click the double green arrows inside IDEA (run spec). Everything should work.
3. Click a single green arrow next to 1 or 2. The test will fail with `Exception in thread "main" io.kotest.extensions.system.SystemOutWriteException`
4. As a bonus, add the `NoSystemErrListener` to the listener list. Now running a single test will never finish, only showing `Exception: io.kotest.extensions.system.SystemErrWriteException thrown from the UncaughtExceptionHandler in thread "main"`

**Comment by LeoColman** [comment]
Reproduced on Kotest 5.8.0;
Doesn't happen when running with Gradle

**Comment by sksamuel** [comment]
Not sure how to tackle this really. Kotest needs to output to system out when using the intellij plugin in order for intellij to parse the test report. Perhaps we can disable/renable it in a smarter way.
