### ISSUE TITLE
Add BlockHound support

### ISSUE THREAD

**Issue by OliverO2** [kotest/kotest#3308]
[kotlinx\-coroutines\-debug](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-debug) supports a [BlockHound](https://github.com/reactor/BlockHound) integration. However, Kotest currently does not.

Using Kotest in conjunction with BlockHound is usually fine. The following issue is an exception. Kotest uses `ThreadPoolExecutor` by default in `FixedThreadCoroutineDispatcherFactory` (via `Executors.newSingleThreadExecutor().asCoroutineDispatcher()`), which briefly blocks for thread queue management:
* [BlockHound false positive in ThreadPoolExecutor\.execute · Issue \#3540 · Kotlin/kotlinx\.coroutines](https://github.com/Kotlin/kotlinx.coroutines/issues/3540)

If that's OK, I could prepare a PR with a `BlockHound` integration solving the above issue.

**Comment by sksamuel** [comment]
Feel free to raise a PR for us to look at. BlockHound seems reactor specific?

**Comment by OliverO2** [comment]
While BlockHound is a reactor project, it provides the same benefits with coroutines when used with the [kotlinx\-coroutines\-debug](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-debug) module:

It reports blocking calls from threads that are part of the coroutine thread pool and currently execute a CPU-bound coroutine computation. It helps to detect thread-blocking early, e.g. when calling a blocking I/O library function. In a case like this, one can decide whether to
* replace the call with a non-blocking one (using a coroutine-aware library), or
* schedule the calling coroutine to run on a separate I/O thread, or
* add an exception if the blocking is harmless.

I'll prepare a PR.
