### ISSUE TITLE
Maven Central artifacts of multiplatform-plugin-* moved to “legacy”?

### ISSUE THREAD

**Issue by SimplyMika** [kotest/kotest#3321]
Hi there,

I currently cannot test my Kotlin/Native project(s) with Kotest because of a strange quirk in your packaging that I don't understand. I was hoping you could shed some light on it.

## What I do
I start a new project with Kotest 5.5.4, using Kotlin 1.7.21 and Gradle (whatever the version). I'm targeting JVM, JS, Windows, MacOS, and Linux and I'm using `io.kotest:kotest-framework-engine:5.5.4` in `commonTest`, as your Quick Start Guide suggests.
When I try to build my project, Gradle complains that it cannot find `io.kotest:kotest-framework-multiplatform-plugin-js-jvm:5.5.4`.
## What I see
When checking the artifacts in Maven Central, that checks out – that artifact suddenly stopped at version `5.4.1` (which is not an option for me because of #3173.
Instead, the structure of several artifacts that start with `kotest-framework-multiplatform-plugin` seem to have changed:
`...-js`, `...-js-jvm`, `...-native`, and `...-native-jvm` all stopped at version `5.4.1`, and instead there are now the artifacts `...-legacy-native` and `...-legacy-native-jvm`. And they contain the versions `5.4.2` through `5.5.4`. Artifacts for JS seem to have just stopped releasing outright?

This is very strange to me, and it completely prevents me from using Kotest, unless I downgrade it to `<=5.4.1` *and* Kotlin to `<1.7.20`, which some projects don't allow me to do.

So my questions are:
Is this intentional?
If so, why?
And where is it documented? So that I can know where to find everything.
And lastly: What do I do now? Is there some other artifact I can use that doesn't have this issue? Or is it an issue with Maven Central? Or am I just doing things wrong?

I'd love to know what is going on, so I would really appreciate any reply on this!
Thanks

**Comment by sksamuel** [comment]
The compiler plugin adds those dependencies for you automatically, so you shouldn't have to add them.

**Comment by SimplyMika** [comment]
Ah, sorry if that wasn't clear: it adds the wrong ones. I only add the compiler plugin and 1 dependency in `commonMain`, but my project automatically depends on artifacts that don't exist in Maven Central. That's the issue, because it prevents me from building anything...

Sorry, I wrote so much in my post and yet failed to mention that.

**Comment by Kantis** [comment]
I think this is probably related https://github.com/kotest/kotest/pull/3107#issue-1301849119

**Comment by Nek-12** [comment]
How do I use multiplatform kotest with 5.5.4? No matter what I do, sync fails. Disabling js target doesn't help

**Comment by Nek-12** [comment]
Not stale

**Comment by shwaka** [comment]
I'm experiencing the same issue with Kotlin/JS.
I have created a reproducing repository [shwaka/kotest-with-kotlin-js-1.7](https://github.com/shwaka/kotest-with-kotlin-js-1.7).

See `README.md` in the repository for the usage.
(Just run `./gradlew jsTest` together with changing versions in `build.gradle.kts`)

**Comment by sksamuel** [comment]
This is a version mismatch. Taking the linked project and using 1.7.21 / 5.5.2, the tests compile.
For kotlin 1.8 you want Kotest 5.6.x
And for kotlin 1.9 you will need the upcoming 5.8 release.
