### ISSUE TITLE
Surefire Test Name Empty

### ISSUE THREAD

**Issue by nguyentommy86** [kotest/kotest#3322]
Background information:
Maven Version: 3.8.6
Kotlin Version: 1.7.20
Kotest Version: 5.5.4
Surefire Version: 3.0.0-M7

After upgrading from Kotest 4.6.4, the test names in the Surefire reports are now empty. 

Before (4.6.4): 
`<testcase name="should Profile client returns user profile" classname="<test context name>" time="0.005"/>`

After (5.x.x):
`<testcase name="" classname="com.example.testclass" time="0.006"/>`

Note:
The classnames before and after also changed. I had to redact it but in v4.6.4, it was the name of the test context, while v5.x.x, it was the actual classname/classpath of the test itself.

**Comment by nguyentommy86** [comment]
[kotest-demo-v4.zip](https://github.com/kotest/kotest/files/10279526/kotest-demo-v4.zip)
[kotest-demo-v5.zip](https://github.com/kotest/kotest/files/10279527/kotest-demo-v5.zip)

POCs

**Comment by Kantis** [comment]
I think you might need to setup the [JUnit XML reporter](https://kotest.io/docs/extensions/junit_xml.html). I haven't used it myself, so I can't give much direction on how to do so. There's a few [relevant hits](https://github.com/search?l=Maven+POM&q=kotest-extensions-junitxml-jvm&type=Code) from GitHub search that you could look at perhaps?

**Comment by nguyentommy86** [comment]
@Kantis I've tried using that, but it creates its own report, instead of overriding the Surefire report and output in the CLI.

**Comment by sksamuel** [comment]
Surefire uses the method name for the test name.
Since tests in Kotest are not methods, we cannot populate it.
You could need to use our own https://kotest.io/docs/extensions/junit_xml.html as linked to by @Kantis and then configure your downstream processes to use that. The formats are identical.
