### ISSUE TITLE
Where are the Android matchers?

### ISSUE THREAD

**Issue by christophehenry** [kotest/kotest#3325]
[Android matchers are still documented on kotest.io](https://kotest.io/docs/assertions/android-matchers.html) but are nowhere to be found on Maven central and [the repository is archived](https://github.com/kotest/kotest-android). I couldn't find any expalination as to why Android matchers have disappeared and where to find them.

**Comment by LeoColman** [comment]
@christophehenry 
We decided not to support Android 1st class on Kotest and thus archived the repository and stopped publishing. To still provide support I took ownership of those matchers and republished them. I also intend to keep maintaining the new library.


- Android documentation removed from Kotest docs
- Notice added to the archived `kotest-android` repository
- Repository https://github.com/LeoColman/kotest-android created with both an Android Runner and the same assertions from the archived repository
- My repository added to https://kotest.io/docs/assertions/matchers.html as part of the community provided matchers
