### ISSUE TITLE
how to mock stdin and stdout correctly?

### ISSUE THREAD

**Issue by scarf005** [kotest/kotest#3327]
studying competive programming with kotest. since the problems are evalutated with stdin and stdout, I've been using this mock to test my functions.

```kotlin
fun testSolution(input: String, output: String, fn: () -> Unit) =
    mock(input.trimIndent()) { fn() } shouldBe output.toOutput()


fun mock(input: String, block: () -> Unit): String =
    captureSystemOut { mockSystemIn(input, block) }

fun String.toOutput() = this.trimIndent() + '\n'

private fun mockSystemIn(input: String, block: () -> Unit) {
    val old = System.`in`
    System.setIn(input.byteInputStream())

    block()

    System.setIn(old)
}

private fun captureSystemOut(block: () -> Unit): String {
    val old = System.out
    val newOut = ByteArrayOutputStream()
    val printStream = PrintStream(newOut)

    System.setOut(printStream)
    System.out.flush()

    block()

    System.setOut(old)
    return newOut.toString()
}
```

however, with this approach, error messages aren't very helpful.
![image](https://user-images.githubusercontent.com/54838975/210168263-924178bc-549a-486f-bf3b-832cc06fdb66.png)

### Edit(2023-02-03)
resolved by catching exception stacktrace.  [see comment](https://github.com/kotest/kotest/issues/3327#issuecomment-1414483120) for details.

**Comment by aSemy** [comment]
Are you using JVM? Could you try using Kotest's implementation? https://github.com/kotest/kotest/blob/v5.5.4/kotest-extensions/src/jvmMain/kotlin/io/kotest/extensions/system/wireListeners.kt

**Comment by scarf005** [comment]
thank you. to clarify, kotest doesn't have mock functions for System.in and i'll have to implement it myself, right?

**Comment by scarf005** [comment]
also, it seems like [docs](https://kotest.io/docs/extensions/system_extensions.html) doesn't list kotest's implementation like `captureStandardOut` and `SystemOutWireListener`, is it meant to be used only internally?

**Comment by Kantis** [comment]
@scarf005 I think they're free to be used, since they're not marked `internal`. 

I also think your approach is probably as good as it gets, in case you want to keep using `readln()` etc in your implementations. Other ways could be to take an `InputStream` as input to your solution, like: 
```kotlin

fun main() {
   greet(System.`in`)
}

fun greet(inp: InputStream) {
   inp.bufferedReader().useLines { lines ->
      lines.forEach { println("Hello $it") }
   }
}
```

**Comment by scarf005** [comment]
```kt
import io.kotest.extensions.system.captureStandardOut

fun mock(input: String, block: () -> Unit): String =
    captureStandardOut {
        try {
            mockSystemIn(input, block)
        } catch (e: Exception) {
            e.cause?.stackTraceToString().let(::println)
        }
    }
```
[(original url)][original]

turns out that I didn't mock `System.err`. also, argument passed in to `block` parameter was type [`KFunction<*>`][kfunction], so it may be related. solved by catching exception stacktrace as string then printing it to stdout.

[original]: https://github.com/scarf005/baekjoon/blob/d73db6b9c14efb157f605637c7b5bd0161db2915/src/test/kotlin/utils/Mock.kt#L5-L12
[kfunction]: https://github.com/scarf005/baekjoon/blob/d73db6b9c14efb157f605637c7b5bd0161db2915/src/test/kotlin/utils/Runner.kt#L8-L17
