### ISSUE TITLE
shouldBeEqualToIgnoringFields does not check types of 'other' and 'this'

### ISSUE THREAD

**Issue by Byte27** [kotest/kotest#3330]
**Which version of Kotest are you using**
5.5.4

**Bug description**

```
import io.kotest.matchers.equality.shouldBeEqualToIgnoringFields
import org.junit.jupiter.api.Test

data class Sample(val field1: String, val field2: String)
class CompletelyDifferent(numberField: Int) {
    private val numberField: Int = numberField;
}

internal class MyTest {
    @Test
    fun `test passes, but should fail`() {
        val output = CompletelyDifferent(1)
        val expectedOutput = Sample("a", "b")

        output.shouldBeEqualToIgnoringFields(expectedOutput, Sample::field1)
    }
}
```

The above test passes, even though `output` and `expectedOutput` are instances of completely different classes.

To make the test fail if something wrong is returned, an additional assertion is needed:

```
        expectedOutput should beInstanceOf<Sample>()
        output.shouldBeEqualToIgnoringFields(expectedOutput, Sample::field1)
```

This reduces the simplicity and is something that you can easily forget to add (as you assume the second assertion covers this as well)

**Comment by LeoColman** [comment]
This is probably a breaking change and thus a system property making it "rollback to old behavior" seems necessary in the implementation
