### ISSUE TITLE
OkIO Assertions

### ISSUE THREAD

**Issue by mpetuska** [kotest/kotest#3331]
We already have very useful `java.io` assertions in kotest. Seeing as kotest assertions are available for KMP, it would be great to provide OkIO assertions as well.

**Comment by sksamuel** [comment]
What kind of assertions would you like to see for example ?

**Comment by mpetuska** [comment]
Pretty much all the same ones we currently have on java.io.File, just rebuilt on top of okio Path

**Comment by mpetuska** [comment]
Like File.shouldExist() or File.shouldBeExecutable() to name a few

**Comment by LeoColman** [comment]
I'd suggest adding that as an outside project and including it either in
https://kotest.io/docs/assertions/matchers#kotest-external-matcher-modules
Or 
https://kotest.io/docs/assertions/matchers#community-provided-matchers

I don't think it should be under the Kotest organization and maintenance
