### ISSUE TITLE
Talk about the kotlin style mock server DSL.

### ISSUE THREAD

**Issue by jaehyunup** [kotest/kotest#3333]
hi bro, 

Recently, I met a mock-server while actively implementing integrated tests.
As you said, I felt strongly that the mock-server syntax is very Java-y strongly.

Inspired by your comment, I'm creating and using mock-server extensions for kotlin. it's better to me
[issue#3133](https://github.com/kotest/kotest/issues/3133) Do you still think there is a need to improve?

![image](https://user-images.githubusercontent.com/38849685/212323792-07bf7e76-ea2c-4a56-bd4c-5bef456bb4e8.png)

**Comment by sksamuel** [comment]
There is a kotest httpstub extension you could look at.

**Comment by pientaa** [comment]
Is there any information about httpstub in kotest documentation? I could find only [about mock server](https://kotest.io/docs/extensions/mockserver.html) and I agree that DSL will be much more kotlin-like
