### ISSUE TITLE
Consider var collectionMode in ErrorCollectionMode rather that get+set

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3337]
The current code is

```kotlin
errorCollector.setCollectionMode(ErrorCollectionMode.Soft)
...
errorCollector.setCollectionMode(ErrorCollectionMode.Hard)
```

while it would be nicer to have

```kotlin
errorCollector.collectionMode = ErrorCollectionMode.Soft
...
errorCollector.collectionMode = ErrorCollectionMode.Hard
```

**Comment by sksamuel** [comment]
Is this in project config ?

**Comment by vlsi** [comment]
I expect it to use in a project code.

I guess I would need to have several `soft assertion blocks`, so I incline to something like

```kotlin
withSoftAssertions {
   ...
   ... 
   withHardAssertions {
     ....
   }
   ...
}
...
withSoftAssertions {
   ...
}
```

My system under test is working with several databases, so I need several asserts in a test. Some of the asserts are inherently soft (~nice to have, not a showstopper), and the asserts might be placed in a "test library/test framework/common test" code.

**Comment by sksamuel** [comment]
I mean where do you want to do errorCollector.collectionMode = ErrorCollectionMode.Soft

**Comment by vlsi** [comment]
Within the test code.
The tests are written with TestNG for historical reasons by the way.

**Comment by Kantis** [comment]
You can always use `assertSoftly { }` to create a soft assertion block

**Comment by vlsi** [comment]
assertSoftly throws all errors at the end, so it is impossible to have several assertSoftly blocks in the same test

**Comment by Kantis** [comment]
I checked and there's nothing really stopping us from using a `var` instead. But if we intend to be backwards compatible we will need keep the `get/set` methods as well, so I feel this would pollute the API for a very minor aesthetic gain.

**Comment by sksamuel** [comment]
Yeah I mean we can add both or just accept it was a poor decision but one with not much impact.

**Comment by sksamuel** [comment]
Going to close this as the minor aesthetic gain is not worth having a more convoluted API at this point.
