### ISSUE TITLE
Consider merging shouldBeWithin for LocalDateTime, ZonedDateTime, OffsetDateTime into Temporal

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3338]
Currently, `shouldBeWithin` has 3 overloads: `LocalDateTime`, `ZonedDateTime`, `OffsetDateTime`.

I would probably make sense to merge all of them into a single method: `shouldBeWithin(TemporalAmount, Temporal)`.

It would help adding `kotlin.time`-based APIs like `actual.shouldBeWithin(1.second, expected)`

**Comment by sksamuel** [comment]
Nice idea.

**Comment by Kantis** [comment]
+1! @vlsi do you want to contribute a PR as well?

**Comment by IvanPavlov1995** [comment]
Maybe I'm missing something, but I have some doubts regarding this approach. 
It may look simple from the first sight, but I think it is not so easy. How `LocalDateTime` can be compared to `OffsetDateTime`? `Temporal` does not extend `Comparable` so it's not easy to find a straightforward way to compare them. Even if we find a way to do that, IMO it won't be clear from the caller perspective.

**Comment by vlsi** [comment]
`LocalDateTime` seems to spoil the idea indeed.
`ZonedDateTime` and `OffsetDateTime` can be compared though.

**Comment by vlsi** [comment]
On the other hand, there are many implementations for `Temporal`.
For instance, `Instant`, and it is more-or-less fine to compare `Instant` with `OffsetDateTime` or `ZonedDateTime`.
There's `JapaneseDate` and `ThaiBuddhistDate`.

What if the method was receiving `Temporal`, and make it fail in the runtime should somebody attempt comparing incmparable classes?

**Comment by Kantis** [comment]
I'm leaning on  _not_ going forward with this since we can't compare all temporals
