### ISSUE TITLE
neverNullMatcher makes the failure messages obscure

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3345]
```kotlin
(null as? String?) shouldBe containADigit()
```

=>

```
Expecting actual not to be null
java.lang.AssertionError: Expecting actual not to be null
```

Frankly speaking, I expect the value to contain something like "expecting a string that contains a digit, however, null was given"

**Which version of Kotest are you using**

5.5.4

**Comment by vlsi** [comment]
A quick solution would probably be adding the following function, and deprecating the old one.
It will impact ~40 usages in kotest.

```kotlin
fun <T : Any> neverNullMatcher(clue: () -> String, t: (T) -> MatcherResult): Matcher<T?> {
}
```

WDYT?

A more involved approach might be something like
* https://github.com/kotest/kotest/issues/3343

**Comment by vlsi** [comment]
One of the ways out could be:
* Add `val description: String` to `Matcher`
* Fix `Matcher.and` so it merges the failure result with the descriptions of untested matchers
* Compose descriptions of the matcherrs being used. For instance, `neverNullMatcher(next: Matcher)` can be `notNull() and next`

**Comment by sksamuel** [comment]
I like the idea of 

```
fun <T : Any> neverNullMatcher(clue: () -> String, t: (T) -> MatcherResult): Matcher<T?> {
}
```

as a quick fix
