### ISSUE TITLE
Non complete junit report when using deep nested contexts

### ISSUE THREAD

**Issue by adecker89** [kotest/kotest#3347]
This is an extension of this issue https://github.com/kotest/kotest/issues/999.

Looks like there was a fix, but it does not account for test styles that allow for arbitrarily nested tests such as FreeSpec

Example:
```
class TestSpec : FreeSpec({
    "1" - {
        "2" - {
            "3" {

            }
        }
    }
})
```

Results in test name of "2 -- 3"

**Comment by sksamuel** [comment]
Completed by 3353
