### ISSUE TITLE
shouldBe should print class information when values do not match yet they have different types

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3349]
```kotlin
"test" shouldBe StringBuilder("test")
```

```
expected:<test> but was:<"test">
Expected :test
Actual   :"test"
```

There are two issues here:
1) Actual value is quoted while the expected is not quoted. It is confusing, and I guess it is yet another case for https://github.com/kotest/kotest/issues/3346
2) The values seem to be the same, so the assertion failure should highlight the values have different types

Here's the same with JUnit Jupiter: `org.junit.jupiter.api.Assertions.assertEquals("test", new StringBuilder("test"));`

```
org.opentest4j.AssertionFailedError: expected: java.lang.String@5a772895<test> but was: java.lang.StringBuilder@39fc6b2c<test>
Expected :test
Actual   :test
```

---

`org.junit.jupiter.api.Assertions.assertEquals(Integer.valueOf(42), Long.valueOf(42));`

=>

```
org.opentest4j.AssertionFailedError: expected: java.lang.Integer@3f9076e4<42> but was: java.lang.Long@98ab16d<42>
Expected :42
Actual   :42
```

On the other hand, `kotest` is just fine if the user compares `Integer` with `Long`

**Comment by sksamuel** [comment]
I'm not sure we can change the int vs long behavior now, as it could break millions of tests.
But clarifying the types when the failure occurs is a great idea, we should do that.

**Comment by vlsi** [comment]
>I'm not sure we can change the int vs long behavior now, as it could break millions of tests.

That can be done incrementally:

1) Introduce a property to flip to the new behaviour
2) After 6 months, start printing warnings that the behavior will change
3) After 12 months, flip the behaviour

If a test relies on "42 int being equal to 42 bigint" succeeds, that probably means the test misses a bug.

**Comment by sksamuel** [comment]
Yeah 42 int should never match 42 big int.
But int / long I'm on the fence.

Because sometimes you have a function returning a Long (say a userId) and in your tests you might just be using 1 as the userId, and your test might be user.userId shouldBe 1
Everyone would have to go through and do user.userId shouldBe 1L

So I think for short/int vs long, float vs double, I'm happy to keep the current behavior, but those should be the only exceptions.

**Comment by vlsi** [comment]
It does not hurt to use 1L in tests.
Kotlin does not automatically promote ints to long.
Try running `1==1L`

**Comment by sksamuel** [comment]
I'm not disagreeing that you're right, I'm just saying that changing this now, after 6 years of Kotest it not worth it in my opinion - for ints and longs. Perhaps as an opt in flag ?

For other stuff, like int / bigint, I think it is worth it.

**Comment by CLOVIS-AI** [comment]
> So I think for short/int vs long, float vs double, I'm happy to keep the current behavior, but those should be the only exceptions.

I would much rather have overloads for numbers to ensure code that makes no sense doesn't compile (e.g. `Int shouldBe BigDecimal`).

**Comment by sksamuel** [comment]
Addressed by https://github.com/kotest/kotest/commit/1bdf00ec142066c36f6742f70feb058c7cc908ef
