### ISSUE TITLE
shouldBe should compare types, and fail on mismatched types

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3350]
The following assertion fail:

```kotlin
"42 shouldBe 42L should fail" {
  java.lang.Integer.valueOf(42) shouldBe java.lang.Long.valueOf(42)
}
```

The assertion **succeeds** with kotest 5.5.4. I would expect that a regular comparison of `Int` and `Long` should fail.

A slight variation fails even with kotest 5.5.4 (the failure is expected by the way):

```kotlin
"42 shouldBe BigInteger(42) should fail" {
  42 shouldBe BigInteger("42")
}
```

```
expected:<42> but was:<42>
Expected :42
Actual   :42
```

The error message is cryptic, and I filed the following issue to improve it:
* https://github.com/kotest/kotest/issues/3349

**Comment by Kantis** [comment]
Feels like a huge thing to change, and something that has seen very little complaints over the years. Not sure about this one.. 

I agree that we should include type-information in the failures to make it more clear in cases where type matters.

**Comment by sksamuel** [comment]
@vlsi we can't do this, and it's been discussed a few times.

Basically, we need @OnlyInputTypes to be stable before we could do this, otherwise, we have to lock down one of the parameters, and then the actual and expected are no longer commutative.

**Comment by vlsi** [comment]
OnlyInputTypes is for compilation, while the types can be compared in runtime

**Comment by vlsi** [comment]
> Feels like a huge thing to change, and something that has seen very little complaints over the years. Not sure about this one..

Well, people rarely complain, and they either get wrong results (e.g. their tests pass without surfacing a bug) or they just start comparing the types on their own.

The sad thing is that `shouldBe` does **not** clarify when it passes, and when it fails.
For instance, does `a shouldBe b` require `a.equals(b) == true`? Does it require `b.equals(a) == true`? Does it require `a::class == b::class`?
I see nothing like that in the documentation. Of course, people do not complain when `shouldBe` behavior is unspecified and undocumented 😉
