### ISSUE TITLE
between(Double, Double, tolerance) produces misleading messages

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3355]
kotest 5.5.4

```kotlin
0.0.shouldBeBetween(1.0, 2.0, tolerance=0.0)
// 5.5.4 failure:  .0 should be bigger than 1.0
```

"should be bigger than 1.0" is only half of a story. The actual value should fit within 1..2 with 0.0 tolerance. Why does the error message hide that?

```kotlin
5.0.shouldBeBetween(1.0, 2.0, tolerance=0.0)
// 5.5.4 failure: 5.0 should be smaller than 2.0
```

Same thing: why only "smaller than 2.0" is printed?

```kotlin
1.0.shouldNotBeBetween(0.0, 2.0, tolerance = 0.0)
// 5.5.4 failure: 1.0 should not be smaller than 2.0 and should not be bigger than 0.0
```

Watch carefully: it suggests that the value should be both "not smaller than 2.0" and "not bigger than 0.0". I'm afraid that requirement is impossible to fulfill. Any value which is "not smaller than 2.0" is going to be bigger than 0.0, so both requirements are unsatisfiable.

**Comment by Kantis** [comment]
I agree it could be improved. How about something like this?

```kotlin
0.0.shouldBeBetween(1.0, 2.0, tolerance=0.0)
// suggested failure:  .0 is outside expected range [1.0, 2.0] (using tolerance 0.0)

1.0.shouldNotBeBetween(0.0, 2.0, tolerance = 0.0)
// suggested failure: expected 1.0 to be outside range [0.0, 2.0], but it was not. (using tolerance 0.0)
```

**Comment by vlsi** [comment]
This sounds much better
