### ISSUE TITLE
Kotlin multiplatform commonTest - skip platform

### ISSUE THREAD

**Issue by Burtan** [kotest/kotest#3357]
Hey,
I want to test image manipulation in a kotlin multiplatform project in the commonTest module. However, BitmapFactory of android needs mocking/roboelectric or an instrumented test. I have not found a way to implement this using commonTest. As this seems quite hard to implement. Is there a way to skip certain platforms using kotest in commonTest module?

**Comment by sksamuel** [comment]
Good idea - we could have some kind of annotation on the class, or modifier in test config which allows you specify which platforms to include (or exclude).

**Comment by Kantis** [comment]
Maybe a method on specs? Would be similar to how a lot of other test-config is handled. 

```kotlin
class MyJvmTest : FunSpec(
  {
     platforms(Platform.JVM)

     test("some jvm-specific test") {
       // ..
     }
  }
)
```

Could also be something that fits nicely in the Gradle plugin. Could be neat to have something similar to the Gradle [JVM test suite plugin](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html) where you can register new test suites, perhaps with the Kotest plugin you could configure which Kotlin targets the test suite applies to?

**Comment by sksamuel** [comment]
Yeah I like the idea of doing it in our own plugin when we finish that (waiting on compiler plugins to go stable first).
But specifying the platforms inside the spec seems like a great addition, and could do it on a per test too.
