### ISSUE TITLE
Kotest Pitest extension not compatible with Kotest version > 5.4.0 

### ISSUE THREAD

**Issue by roschwartz79** [kotest/kotest#3359]
**Which version of Kotest are you using**
5.4.0

I am integrating Pitest into my micronaut application that uses Kotest as the testing framework. I am using the following versions that are relevant to this issue:

Kotest 5.4.0
`io.kotest.extensions:kotest-extensions-pitest:1.1.0`
`io.micronaut.test:micronaut-test-kotest5:3.8.0`
`io.kotest:kotest-runner-junit5-jvm:5.4.0`

For my Pitest configuration, I am running Pitest version 1.8.1 as it was [pointed out](https://stackoverflow.com/questions/75242302/is-kotest5-compatible-with-pitest/75243398?noredirect=1#comment132788756_75243398) that the kotest pitest extension is only compatible with versions < 1.9.0.

For my [Pitest gradle plugin](https://gradle-pitest-plugin.solidsoft.info/) version I am using 1.9.0. The version of this plugin does not correspond to the version of Pitest running because I specify that in the plugin configuration.

When I move to `kotest version 5.3.2`, Pitest works as expected! With version 5.4.0 and above, I get the following error:

```
2:43:12 PM PIT >> FINE : MINION : java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
```
 I see there was a thread similar to this with a similar error about a Kotest Spring extension, see that [here](https://github.com/kotest/kotest/issues/3122). I wonder if there is a similar fix or a different regression that was introduced in Kotest 5.4.0 and above? For now I am getting by with 5.3.2 but upgrading to latest would be ideal!

**Comment by Kantis** [comment]
I think we just need to do a new release of the Pitest extension, built with the latest Kotest version. I think I fixed the publishing of snapshots there. Could you give the latest snapshot a try when it's available?

**Comment by Kantis** [comment]
Pitest 1.9 introduced a breaking change in the API used by the Kotest extension. There's a new snapshot build out which bumps Pitest compatibility to 1.9.0+

**Comment by Kantis** [comment]
Kotest-extensions-pitest 1.2.0 is out, which supports Kotest 5.5 and Pitest 1.9+

**Comment by Tyrannoseanus** [comment]
@Kantis you mentioned that 1.2.0 is "out" now? Where is that released? I can only see 1.1.0 in Sonatype Central linked from the extensions repo

https://central.sonatype.com/artifact/io.kotest.extensions/kotest-extensions-pitest/1.1.0/versions

**Comment by Kantis** [comment]
I must've forgot to release the artefacts. Fixing..

**Comment by glockbender** [comment]
@Kantis any news about release version with this fix?
