### ISSUE TITLE
Unify StringSpec, WordSpec and FreeSpec

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3386]
It's not really clear why we need both StringSpec and FreeSpec. I think we could just make StringSpec an alias for FreeSpec and allow using containers in it?

**Comment by sksamuel** [comment]
Once we move off gradle, we can get rid of the minus sign that's needed in free specs.
Maybe we wait for that ?

**Comment by Kantis** [comment]
Sounds like a good idea. :) Close this for the time being?

**Comment by sksamuel** [comment]
Can leave it open tagged to 6.0 ?

**Comment by sksamuel** [comment]
I'm not sure we can do this.
Free spec needs the minus so it knows what's a leaf and what's a container.
Otherwise for instance per leaf, it wouldn't know if it needs to make a new instance or not.
