### ISSUE TITLE
With gradle 7.6 and FreeSpec, minus(-) sign with innermost tests are not tested. (They were in gradle 6)

### ISSUE THREAD

**Issue by ShindongLee** [kotest/kotest#3390]
### Versions
Kotest 5.5.5
Gradle 7.6
Kotlin 1.8.10
Spring 2.5.14

### Problem
Recently we bumped gradle version 6.9.1 to 7.6

>The innermost test must not use the - (minus) keyword after the test name.

We know we should not put minus (-) signs into innermost tests (leafs), but we has been putting them, since with gradle 6.9.1, `./gradlew test` command still runs them.

But after upgarding gradle version 6.9.1 to 7.6, our test counts decreased a lot. We found that gradle skipped all innermost tests with minus signs. Now we want to remove all - keyword in innermost tests, but it is hard to find them because we have 1000+ tests in our project.

For example,

```kotlin
class Test : FreeSpec({
    "test" - {                      // minus keyword should not exist
        1 shouldBe 1
    }
})
```

1. This test is executed with `./gradlew test` command with gradle 6.9. 1 is 1, passed.
2. This test fails with gradle 7.6, when run by `./gradlew test --tests com.example.Test` command or manually executed with IDE button with following error message (as expected), only if the single test is executed.
```bash
* What went wrong:
Execution failed for task 'test'.
> No tests found for given includes: [com.example.Test](--tests filter)
```
I am okay with 1 and 2 But,

3. When I run `./gradlew test` command with gradle 7.6, this test is just ignored and gradle task succeeds with decreased test counts. (We expect fail or being tested)

Is there any way to fail the innermost tests with inappropriate minus sign so that we can find them and fix ? (or at least they can be just tested, how they were with gradle 6.9)

**Comment by Kantis** [comment]
@ShindongLee I don't believe we have anything that just does this out of the box. You could try adding an extension like this to catch them however?

```Kotlin
class WarnOnEmptyContainerExtension : BeforeContainerListener, AfterTestListener, AfterSpecListener {
   val emptyContainers = mutableSetOf<TestCase>()

   override suspend fun beforeContainer(testCase: TestCase) {
      emptyContainers.add(testCase)
   }

   override suspend fun afterTest(testCase: TestCase, result: TestResult) {
      testCase.parent?.let { parent ->
         emptyContainers.remove(parent)
      }
   }

   override suspend fun afterSpec(spec: Spec) {
      println("Warning: found empty containers")
      emptyContainers.forEach { println(" - ${it.descriptor.path().value}") }
   }
}
```

**Comment by Kantis** [comment]
You can register the extension globally by either adding a `KotestConfig`

```Kotlin
object KotestConfig : AbstractProjectConfig() {
   override fun extensions() = listOf(WarnOnEmptyContainerExtension())
}
```

or by adding `@AutoScan` on the extension class

**Comment by ShindongLee** [comment]
@Kantis Your configuration catches invalid tests.

```kotlin
class Test : FreeSpec({
    "valid test" {
        println("valid")
    }

    "invalid test" - {
        println("invalid")
    }
})
```

Without config,  we weren't able to catch that invalid tests are not running. 
![sc1](https://user-images.githubusercontent.com/46624511/218608961-50b30ccc-132f-4b25-bc87-c75beb0ff463.jpeg)

With config, we could catch them. 
![sc2](https://user-images.githubusercontent.com/46624511/218609218-d420cda0-c96f-4a55-809f-fe9a1f702d10.jpeg)

It would be nice they fail by default without config but still, you saved my day Thank you so much!

**Comment by ShindongLee** [comment]
@Kantis I think the configuration has some false alarms.

```kotlin
class Test : FreeSpec({
    "valid test" {
        println("valid")
    }

    "valid test2" {
        println("valid")
    }
})
```
For example, these tests are all valid, but outputs are:
```bash
valid
valid
Warning: found empty containers
```

But I somehow modified your code and used. Thanks.

**Comment by jwmaher** [comment]
Ran into the same issue and ended up going with a similar solution to the one put forward by @Kantis, been using it for a few weeks and haven't run into any issues 

```
class ErrorOnEmptyContainersExtension:
    BeforeContainerListener,
    AfterTestListener,
    BeforeSpecListener,
    AfterSpecListener
{
    private val specs: MutableMap<Spec, MutableSet<TestCase>> = mutableMapOf()

    override suspend fun beforeSpec(spec: Spec) {
        specs[spec] = mutableSetOf()
    }

    override suspend fun beforeContainer(testCase: TestCase) {
        specs[testCase.spec]
            ?.also { containers -> containers.add(testCase) }
    }

    override suspend fun afterTest(testCase: TestCase, result: TestResult) {
        testCase.parent
            ?.let { parent -> specs[parent.spec] }
            ?.also { containers -> containers.remove(testCase.parent) }
    }

    override suspend fun afterSpec(spec: Spec) {
        specs[spec]
            ?.takeIf { containers -> containers.isNotEmpty() }
            ?.also { emptyContainers ->
                fail("Found empty containers (https://kotest.io/docs/framework/testing-styles.html#free-spec): ${emptyContainers.testNames()}")
            }
    }

    private fun MutableSet<TestCase>.testNames() = joinToString(", " ) { container ->
        container.descriptor.path(includeSpec = false).value
    }

}
```

**Comment by Kantis** [comment]
Closing as not planned for now.
