### ISSUE TITLE
Comparing collections ignoring field(s) in any order

### ISSUE THREAD

**Issue by sherviiin** [kotest/kotest#3393]
I faced a case where I needed to have assertions which help me compare two collections, ignoring one or more fields, and ignoring the order of the items.
According to discussion that we had on slack ([here](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1673873913216489)), there are no assertion for this.
This PR adds `shouldContainAllIgnoringFields` which provides such a feature.

**Comment by sherviiin** [comment]
[PR link](https://github.com/kotest/kotest/pull/3394)

**Comment by sksamuel** [comment]
Completed by pr
