### ISSUE TITLE
Add support for value class / inline class

### ISSUE THREAD

**Issue by kylooh** [kotest/kotest#3396]
I have a problem on running test, which using value class as parameter.

Here is a simple version of my definition for business.
```kotlin
@JvmInline
value class Boxed(val name: String)

class Invoker {

    fun invokeValueClass(boxed: Boxed): String = boxed.name
}
```

Here is my test code.
```kotlin
val boxed = Boxed(name = "Test Object")
val invoker = spyk<Invoker> { Invoker() }

val result = invoker.invokeValueClass(boxed)
verify { invoker.invokeValueClass(eq(boxed)) } // This is where exception throws
```

Then I received exceptions like following:
> Verification failed: call 1 of 1: Invoker(#1).invokeValueClass-qPtyfO4(eq(Boxed(name=Test Object)))). Only one matching call to Invoker(#1)/invokeValueClass-qPtyfO4(String) happened, but arguments are not matching:
> [0]: argument: Test Object, matcher: eq(Boxed(name=Test Object)), result: -

The message shows, that mockk try using type eq(Boxed) to match (String). Any plan for value class supporting? Really appreciate, Thanks for reading, guys.

**Comment by Nek-12** [comment]
This is a kotest repository...

**Comment by Kantis** [comment]
Looks like you're having issues with mockk, not kotest. Closing this

**Comment by kylooh** [comment]
> Looks like you're having issues with mockk, not kotest. Closing this

Sorry for that. promise never again.
