### ISSUE TITLE
Kotest for Kotlin/JS seems  broken with newer versions of Kotlin + Gradle

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3400]
The [multiplatform example](https://github.com/kotest/kotest-examples-multiplatform) doesn't seem to work. Adding a failing test causes a gradle exception. When there's no failing tests, Gradle and IntelliJ seems to fail to pick up the tests being run.

1. I think we need to say what versions of Gradle + Kotlin that the current multiplatform stuff works for. 
2. I think we need to release support for Kotlin 1.7+ / Gradle 7.6+ with Kotest 5.6 (https://github.com/kotest/kotest/issues/3372 should help)

**Comment by SeekDaSky** [comment]
Probably linked to #3329

**Comment by Kantis** [comment]
I tried to dig into why Kotest 5.5.5, Gradle 7.6 and Kotlin 1.7+ is not playing well together. I think that JetBrains has changed the gradle plugin for Kotlin/JS at some point, from doing a single Mocha invocation to doing multiple ones (perhaps to run suites in parallel?). 

The way Kotest for JS works causes our tests to run on the first invocation which kotlin-test is now using for discovery, so there's no reporter attached, and the failure results in an exception. I guess the Gradle task doesn't expect failures on first invocation.

**Comment by CLOVIS-AI** [comment]
Are there any news on this? This is blocking Kotest adoption for me.

**Comment by sksamuel** [comment]
Kotest 5.6.1 is out which targets 1.8.
