### ISSUE TITLE
Can not compile with junit 5

### ISSUE THREAD

**Issue by Gazer** [kotest/kotest#3407]
**Which version of Kotest are you using**

5.5.5

**Problem**

After moving our Android project from JUnit 4 to JUnit 5 we started to see

> Duplicate class org.intellij.lang.annotations.Language found in modules annotations-13.0 (org.jetbrains:annotations:13.0) and kotest-common-jvm-5.5 (io.kotest:kotest-common-jvm:5.5.5)

After some digging, we found that [this](https://github.com/kotest/kotest/pull/3328/files) PR has a copy of the file provided by `org.jetbrains:annotations:13.0` and creates the error.

**Workaround**

Downgrading to kotest 5.5.4 fix the problem.

**Comment by Kantis** [comment]
Fixed by #3397 and will be available in next release
