### ISSUE TITLE
Test Output - broken link to 'project configuration' 

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#3408]
The link to 'project configuration' but it doesn't work.

https://kotest.io/docs/framework/test_output.html#project-config

https://github.com/kotest/kotest/blob/baf7861f06ad0664e38c8c4e6da0c38b184381de/documentation/versioned_docs/version-5.5/framework/output.md?plain=1#L13

 I'm not sure what the correct link should be...

**Comment by Kantis** [comment]
Should probably be `./project-config.html`, leading to https://kotest.io/docs/framework/project-config.html

**Comment by aSemy** [comment]
fixed in https://github.com/kotest/kotest/issues/3408
