### ISSUE TITLE
`kotest-common-macosarm64-5.5.5.klib` missing on maven central

### ISSUE THREAD

**Issue by idugalic** [kotest/kotest#3410]
I am using kotest 5.5.5.

By building my application on Mac arm 64 I get the message that it can not find:
`https://repo.maven.apache.org/maven2/io/kotest/kotest-common-macosarm64/5.5.5/kotest-common-macosarm64-5.5.5.klib`

**Comment by RyuNen344** [comment]
https://github.com/kotest/kotest/issues/3388

same problem

**Comment by dalewking** [comment]
Same problem here for iOS ARM 64. Downgrading to 5.5.4 is a workaround

**Comment by HylkeB** [comment]
Not sure if it is the same root cause, but since version 5.5.5 my kotlin multiplatform project no longer has a functioning autocomplete / intellisense / syntax highlighting in AndroidStudio. Downgrading to 5.5.4 solves it for me as well

**Comment by dalewking** [comment]
Pretty sure it is the same root cause. No surprising is what I noticed first

**Comment by LeoColman** [comment]
Closing as duplicate of #3388
