### ISSUE TITLE
idea: Matcher.and and Matcher.or could aggregate all messages

### ISSUE THREAD

**Issue by pientaa** [kotest/kotest#3411]
What do you think about changing implementation of `Matcher.and` and `Matcher.or` to something like that?

```kotlin
infix fun <T> Matcher<T>.and(other: Matcher<T>): Matcher<T> = Matcher {
   val first = this.test(it)
   val second = other.test(it)
   MatcherResult(
      first.passed() && second.passed(),
      { "(${first.failureMessage()} and ${second.failureMessage()})" },
      { "(${first.negatedFailureMessage()} or ${second.negatedFailureMessage()})" },
   )
}

infix fun <T> Matcher<T>.or(other: Matcher<T>): Matcher<T> = Matcher {
   val first = this.test(it)
   val second = other.test(it)
   MatcherResult(
      first.passed() || second.passed(),
      { "(${first.failureMessage()} or ${second.failureMessage()})" },
      { "(${first.negatedFailureMessage()} and ${second.negatedFailureMessage()})" },
   )
}
```
The message is aggregated then, so we know exactly what are the checked conditions.

It was mentioned in #3343 but there was much more requests for changes so I decided to create another issue for that.

I'm not sure if this is better or to create `Matcher.all()` and `Matcher.any()` instead, as @Kantis proposed in #3406

**Comment by sksamuel** [comment]
Is this still  required?

**Comment by pientaa** [comment]
@sksamuel actually not, this is redundant regarding recent changes (`Matcher.Companion.all`) and upcoming one (`Matcher.Companion.any` in #3431)
