### ISSUE TITLE
shouldBeEqualToComparingFields doesn't work for classes which has Map type fields

### ISSUE THREAD

**Issue by ktrueda** [kotest/kotest#3415]
I'd like to test the equality of a java class defined in a 3rd party library. The class doesn't override equals() method and has a Map<String, Foo> field.  Foo class doesn't override equals() method neither.

Then I wish shouldBeEqualToComparingFields works well. But it doesn't work.

This is a simple code of this issue.
```kotlin
class MyTest : FunSpec(){
   class Foo(val a: String)
   data class Bar(val a: Map<String, Any>)

   init {
      test("sample") {
         Bar(mapOf("a" to Foo("sammy"))) shouldBeEqualToComparingFields Bar(mapOf("a" to Foo("sammy")))
      }
   }
}
```

```
java.lang.AssertionError: Expected Bar(a={a=com.sksamuel.kotest.matchers.equality.MyTest$Foo@5dfb334d}) to equal Bar(a={a=com.sksamuel.kotest.matchers.equality.MyTest$Foo@3c27a046})
 Using fields: a
 Value differ at:
 1) a:
		Values differed at keys a
expected:<{
  "a" = com.sksamuel.kotest.matchers.equality.MyTest$Foo@3c27a046
}> but was:<{
  "a" = com.sksamuel.kotest.matchers.equality.MyTest$Foo@5dfb334d
}>
```

In my opinion, [this code](https://github.com/kotest/kotest/blob/8cb621603904cf8c19747d906d620bd84b6f1a26/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L597) should be fixed for Map type field.

**Comment by Kantis** [comment]
How do you propose fixing it?

**Comment by ktrueda** [comment]
This is just idea and need refactoring.

[This code](https://github.com/kotest/kotest/blob/c29a557ffaf146ce3b94a26d316ce232ca268217/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L597) can be changed like below.

```kotlin
  return fields.mapNotNull {
      val actual = it.getter.call(value)
      val expected = it.getter.call(other)
      val typeName = it.returnType.toString().replace("?", "")
      val heading = "${it.name}:"

      if(typeName.startsWith("kotlin.collections.Map")) {
         val actualMap = actual as Map<*, *>
         val expectedMap = expected as Map<*, *>
         val actualKeys = actualMap.keys.map { k->k.hashCode() }
         val expectedKeys = expectedMap.keys.map { k->k.hashCode() }
         val errorMessages = if(actualKeys != expectedKeys){
            listOf("key is different $actualKeys $expectedKeys")
         }else {
            actualMap.keys.flatMap { key ->
               val (errorMessage, _) = checkEqualityOfFieldsRecursively(
                  actualMap[key],
                  expectedMap[key],
                  config,
                  level + 1
               )
               errorMessage
            }
         }

         if (errorMessages.isEmpty()) {
            null
         } else {
            val innerErrorMessage = errorMessages.joinToString("\n") { msg -> "\t".repeat(level + 1) + msg }
            "$heading${"\t".repeat(level)}\n$innerErrorMessage"
         }
      } else if (requiresUseOfDefaultEq(actual, expected, typeName, config.useDefaultShouldBeForFields)) {
        (omitted)
```

This change pass a test below
```kotlin
class MyTest : FunSpec(){
   class Foo(val a: String)
   data class Bar(val a: Map<Any, Foo>)

   init {
      test("sample") {
         // key = a
         Bar(mapOf("a" to Foo("sammy"))) shouldBeEqualToComparingFields Bar(mapOf("a" to Foo("sammy")))
         Bar(mapOf("a" to Foo("tom"))) shouldBeEqualToComparingFields Bar(mapOf("a" to Foo("tom")))
         Bar(mapOf("a" to Foo("sammy"))) shouldNotBeEqualToComparingFields Bar(mapOf("a" to Foo("tom")))
         // key = b
         Bar(mapOf("b" to Foo("sammy"))) shouldBeEqualToComparingFields Bar(mapOf("b" to Foo("sammy")))
         Bar(mapOf("b" to Foo("tom"))) shouldBeEqualToComparingFields Bar(mapOf("b" to Foo("tom")))
         Bar(mapOf("b" to Foo("sammy"))) shouldNotBeEqualToComparingFields Bar(mapOf("b" to Foo("tom")))
         // key = a,b
         Bar(mapOf("a" to Foo("a"), "b" to Foo("b"))) shouldNotBeEqualToComparingFields Bar(mapOf("a" to Foo("a")))
         Bar(mapOf("a" to Foo("a"))) shouldNotBeEqualToComparingFields Bar(mapOf("a" to Foo("a"), "b" to Foo("b")))
         // int key
         Bar(mapOf(123 to Foo("sammy"))) shouldBeEqualToComparingFields Bar(mapOf(123 to Foo("sammy")))

      }
   }
}
```

I think we have to consider
- other collections like List
- collections defined in Java

**Comment by ktrueda** [comment]
@Kantis What do you think ?
Can I try this?

**Comment by Kantis** [comment]
I'm in favor of this. I haven't figured out any downsides to it yet. It would also address https://github.com/kotest/kotest/issues/3494

Like you say, I think it'd be wise to consider all standard collections. I think you can add simple checks like `actual is Map<*, *> and expected is Map<*, *>` to treat all types of maps by recursive descent, etc.

For `List/Array`: Considered equal if lengths are equal and each position contains an item which matches expected by comparing fields
For `Set`: Considered equal if sizes are equal and each item in actual has an item which matches in expected by comparing fields
For `Map`: considered equal if each entry in actual has a match in expected by comparing fields of key and value


Would really like if more people chimed in on this discussion before proceeding though. (or at least leaving some reaction to show what they think)

**Comment by zakhenry** [comment]
I'd add that we would get a lot more mileage out of comparing `Collection<T>` rather than cherry picking some descendants like Set & List etc. This does raise an interesting question though. Should `setOf(1,2,3)` be considered a match to `listOf(1,2,3)` with this change? I'd argue not, but it might make error reporting nicely tough
