### ISSUE TITLE
Kotest BOM is useless for Maven builds

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3417]
Since maven is unaware of multiplatform variants, the `kotest-assertions-core` defined in the Kotest BOM will _not_ be used to resolve `kotest-assertions-core-jvm` for a Maven build.

See slack conversation: https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1676568864598139

https://stackoverflow.com/questions/73914158/how-does-gradle-choose-actually-libraries-ending-with-jvm

KotlinX serialization seems to solve this by doing some shenanigans with the publication. Might be something we could copy. https://github.com/Kotlin/kotlinx.serialization/blob/4a7ada862186368d72086cf01c2359e118ee232c/gradle/publish-mpp-root-module-in-platform.gradle

**Comment by aSemy** [comment]
The KxS Gradle code adds the following to the POM

```xml
<dependencies>
  <dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>kotlinx-serialization-json-jvm</artifactId>
    <version>1.5.0-RC</version>
    <scope>compile</scope>
  </dependency>
</dependencies>
```

https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json/1.5.0-RC/kotlinx-serialization-json-1.5.0-RC.pom


Which should be ignored by Gradle, but will be respected by Maven.
