### ISSUE TITLE
assertSoftly should add a clue

### ISSUE THREAD

**Issue by CLOVIS-AI** [kotest/kotest#3418]
When writing a test like
```kotlin
val list = listOf(1, 2, 3)

assertSoftly(list) {
    it shouldContain 3
}
```

it is likely that the user is interested in the entire list in case the test fails. However, adding the entire list as a clue is quite verbose, making it harder to understand what the point of the test is:

```kotlin
val list = listOf(1, 2, 3)

assertSoftly(list) {
    withClue({ "Soft assertion: $it" }) {
        it shouldContain 3
    }
}
```

I think it would be beneficial if Kotest added the clue automatically when `assertSoftly` is called.

**Comment by CLOVIS-AI** [comment]
If this helps, I can contribute a PR that adds a call to `withClue` in `assertSoftly`

**Comment by sksamuel** [comment]
I think that's a good idea.
