### ISSUE TITLE
beforeSpec/asfterSpec is invoked even when test is filtered out by kotest.tags

### ISSUE THREAD

**Issue by jokoroukwu-sdc** [kotest/kotest#3419]
**Which version of Kotest are you using** 5.5.5
This appears to be the same issue as described in [#1516](https://github.com/kotest/kotest/issues/1516)

Here's a code snippet to reproduce the issue:

```
@Tags("do-not-run")
class ThisTestShouldNotRun : FunSpec({

    test("should not run") {

    }

    afterSpec {
        println("Should not run")
    }
})

@Tags("run")
class ThisTestShouldRun : FunSpec({

    test("should run") {
    }
})
```
When I run `gradle -Dkotest.tags=run test`   `Should not run` is printed out

**Comment by sksamuel** [comment]
This is just the way tags work - @tags adds the tags to all tests. I think you're probably wanting @RequiresTag.
See https://kotest.io/docs/framework/tags.html#tagging-a-spec

**Comment by sschuberth** [comment]
Interesting. Quoting the relevant part of the docs (emphasis mine):

> @Tags - will be applied to all tests in the class, however *this will only stop a spec from being instantiated if we can guarantee that no tests would be executed* (because a tag is being explicitly excluded).

So instead of `-Dkotest.tags=run` rather `-Dkotest.tags=!do-not-run` should be specified.

**Comment by sksamuel** [comment]
Right exactly.
Unfortunately the name @Tags isn't great. It does imply that Tags are controlling it, instead of applying those tags to nested tags.
If we can think of a better name, I am happy to deprecate and rename. Like @ApplyTagsToTests but better than that :)

**Comment by sschuberth** [comment]
A a side note, it's a bit confusing that [this comment](https://github.com/kotest/kotest/issues/1516#issuecomment-646984449) says that the same issue was fixed a few years ago, so this seemed like a regression, but it's probably more that the intended behavior changed since then.

**Comment by sksamuel** [comment]
Yeah, I think it's  likely I was confused about the behavior myself.
