### ISSUE TITLE
Conditional tests mention variables in an example that doesn't exist

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#3421]
The [Conditional tests](https://kotest.io/docs/framework/conditional/enabled-config-flag.html) page mentions 

> `isLinux` and `isPostgreSQL` in the example are just expressions (values, variables, properties, function calls) that evaluate to `true` or `false`. 

https://github.com/kotest/kotest/blob/0f07e00794ee61bc9cfa4cdb9c0ac9113cf570ca/documentation/docs/framework/conditional/config_enabled.md?plain=1#L32

But there is no example that contains `isLinux` or `isPostgreSQL`...

**Comment by pientaa** [comment]
It looks like there was `isLinux` and `isPostgreSQL` in documentation before, but it was replaced by `SystemUtils.IS_OS_LINUX`, so 

https://github.com/kotest/kotest/blob/0f07e00794ee61bc9cfa4cdb9c0ac9113cf570ca/documentation/docs/framework/conditional/config_enabled.md?plain=1#L32

can be simply removed
