### ISSUE TITLE
Matcher.all and Matcher.any

### ISSUE THREAD

**Issue by pientaa** [kotest/kotest#3431]
In #3406 @Kantis proposed a change `Matcher.compose(..)` -> `Matcher.all(m1, m2)` and `Matcher.any(m1, m2)`

**Comment by echo304** [comment]
@pientaa If you don't have resources to deal with it, can I take a look at this issue?

**Comment by pientaa** [comment]
thanks @echo304! I was busy recently, but I do have in mind bigger changes of `Matcher.compose(...)` which includes this task, too, so I will continue with this task in the next weeks

**Comment by pientaa** [comment]
@echo304 in #3406 there is already `Matcher.all`, so if you'd like to implement `Matcher.any`, feel free to do it

**Comment by echo304** [comment]
> @echo304 in #3406 there is already `Matcher.all`, so if you'd like to implement `Matcher.any`, feel free to do it

Ok, let me handle it.

**Comment by pientaa** [comment]
@echo304 do you need some help with this one?

**Comment by sksamuel** [comment]
I think this is covered by #3663

**Comment by pientaa** [comment]
@sksamuel actually,  `Matcher.all` is already implemented, but `Matcher.any` still need to be implemented. I'll do this if there is no response from @echo304

**Comment by sksamuel** [comment]
If you wanted to pick it up @pientaa it can go into 5.7

**Comment by pientaa** [comment]
@sksamuel check #3664
