### ISSUE TITLE
Make Matcher.all multi-platform

### ISSUE THREAD

**Issue by pientaa** [kotest/kotest#3432]
For now it works only on JVM, because initially it was based on reflection. But when #3406 is merged, we could use `Matcher.compose` on other platforms, too. Ofc reflection will still work only on JVM, but composing matchers like this should be possible on all platforms:

```kotlin
val passwordMatcher = Matcher.compose(
   containADigit(), contain(Regex("[a-z]")), contain(Regex("[A-Z]"))
)
```
I think that reflection-based compose can be changed to something like that because same signatures of functions probably won't work both on multiplatform and JVM

```kotlin
val matcherResult = Matcher.compose(
   havePropertyMatching(nameMatcher to Person::name),
   havePropertyMatching(ageMatcher to Person::age),
   havePropertyMatching(addressMatcher to Person::address)
)
```

**Comment by pientaa** [comment]
I updated the issue title because since #3406 this feature is renamed to `Matcher.compose.all`

**Comment by sksamuel** [comment]
Are you wanting to pick this up @pientaa ?

**Comment by pientaa** [comment]
@sksamuel yes, I can pick this up

**Comment by pientaa** [comment]
@sksamuel check #3663
