### ISSUE TITLE
Concurrency Mode docs appear to be out of date

### ISSUE THREAD

**Issue by xenomachina** [kotest/kotest#3434]
The [concurrency docs](https://kotest.io/docs/framework/concurrency.html#concurrency-mode) say:

> We can configure this feature by setting the configuration field `concurrencyMode` or the system property `kotest.framework.concurrency.mode`.

However, searching the entire kotest codebase, the only place I can find “concurrencyMode” is in the docs.

I also found this message from @sksamuel on [Slack](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1621344422010300?thread_ts=1621338171.001900&cid=CT0G9SD7Z):

> concurrencyMode was never released

So it looks like the docs are inaccurate.

**Comment by Kantis** [comment]
thanks @xenomachina for reporting 👍🏼
