### ISSUE TITLE
Spec tests are not being picked up when targeting iOS native

### ISSUE THREAD

**Issue by kirillzh** [kotest/kotest#3439]
Kotest: 5.5.4 or 5.5.5

I have spec tests in `commonMain` as well as `iosTest`. None of them are getting picked up when running and targeting iOS, for example running `gradle iosX64Test` with this test doesn't fail because test is not being ran:

```kotlin
class SomeTests : FunSpec({
  test("test") {
    error("fail!")
  }
})
``

 Converting tests to use Kotlin test engine seems to work though, running `gradle iosX64Test` fails as expected:

```kotlin
class SomeTests {

  @Test
  fun test() {
    error("fail!")
  }
}
```

I have a pretty standard configuration for this:
```kotlin
kotlin {
val targets = listOf(iosX64(), iosArm64(), iosSimulatorArm64())

sourceSets {
  val commonMain by getting
  val iosMain by creating {
    dependsOn(commonMain)
  }
  val commonTest by getting
  val iosTest by creating {
    dependsOn(commonTest)
    dependencies {
      implementation(kotlin("test-common"))
      implementation(libs.kmp.test.kotest.framework.engine)
    }
  }

  targets.forEach {
    it.compilations.getByName("main").source(iosMain)
    it.compilations.getByName("test").source(iosTest)
  }
}
```

**Comment by kirillzh** [comment]
I barely found out about `io.kotest.multiplatform` which needs to be applied to be able to run kotest tests targeting native. This doesn't seem to be documented anywhere?

**Comment by sksamuel** [comment]
Documented on the quickstart page: https://kotest.io/docs/quickstart
But I guess if you go straight to the framework pages its not obvious

**Comment by sksamuel** [comment]
I've added a new setup guide to the main docs to address this.
