### ISSUE TITLE
Property testing: DSL for more ergonomic tests?

### ISSUE THREAD

**Issue by BenWoodworth** [kotest/kotest#3445]
## Problem
I've been using the property testing library for a bit now, and it's great, but often feels clunky to write especially when more and more generators are used

Specifically because of the disconnect between (lambda) variables and where their generators are declared
```kotlin
import kotlinx.coroutines.test.runTest

// ...

@Test
fun example_property_test() = runTest {
    checkAll(
        Arb.string(),
        Exhaustive.mySpecialStrings(),
        Arb.float()
    ) { someString, specialString, someFloat ->
        // Assertions
    }
}
```

## Proposal
Slightly inspired by Jetpack Compose and its [`remember` delegate](https://github.com/android/snippets/blob/714b86bc8858ad6e3a788cf20d0968fc9b60c9d9/compose/snippets/src/main/java/com/example/compose/snippets/state/StateOverviewSnippets.kt#L73-L90), I'm envisioning something like this which takes advantage of Kotlin's expressive language features in a way that wouldn't be possible in QuickCheck with Haskell:
```kotlin
@Test
fun example_property_test() = runPropertyTest {
    val someString by generator { Arb.string() }
    val specialString by generator { Exhaustive.mySpecialStrings() }

    // ...some more setup?

    val someFloat by generator { Arb.float() }

    // Assertions
}
```

I originally pictured values being pulled in like this, which looks a lot nicer, but leads to unnecessary creation of arbs and takes away control from the DSL implementation:
```kotlin
val someString by Arb.string()
```

A `generator` delegate function would also be easy to extend in the DSL syntax, e.g. with:
```kotlin
// Desugars to:  `generator { Arb.default<String>() }`
val someString by arb<String>()

// or, equivalently:
val someString: String by arb()
```

## Implementation
There might be some considerations, like disallowing a property from being instantiated multiple times (e.g. in a loop), or maintaining parity with the values that  would be generated from seemingly equivalent `checkAll`/`forAll`/`proptest` usages. That's all possible to ensure at runtime though. I don't feel qualified to make those decisions though

If there's interest I'd love to put up a PR or a prototype. I'd just want feedback/ideas first, and to know if this is even desired :)

**Comment by myuwono** [comment]
Hey @BenWoodworth thank you for the recommendation. We did explore something similar prior in https://github.com/kotest/kotest/issues/2574#issue-1028289236

Back then I did manage to get it in some working state but I couldn't get shrinking to work. If there's a good idea there would love to hear it.

**Comment by BenWoodworth** [comment]
Ah, thanks for linking that. I poked through all the [property-testing labeled issues](https://github.com/kotest/kotest/issues?q=is%3Aopen+is%3Aissue+label%3Aproperty-testing) so missed that discussion. I'll read it later on when I get a chance!

**Comment by myuwono** [comment]
@BenWoodworth this might be of interest https://github.com/kotest/kotest/pull/3469 after we get this in perhaps there's better avenue to extend this to enable this feature.
