### ISSUE TITLE
How to specify execution timeout for tests?

### ISSUE THREAD

**Issue by lounres** [kotest/kotest#3448]
> MRE: https://github.com/lounres/kotest-test
> Kotlin: 1.8.20-RC
> Kotest: 5.5.5

If you launch the `jvmTest` task, then the [`normal test`](https://github.com/lounres/kotest-test/blob/master/src/commonTest/kotlin/com/lounres/kotestTest/Test.kt#L7-L9) will be tested successfully in less than 1 second, whereas [`bugged test`](https://github.com/lounres/kotest-test/blob/master/src/commonTest/kotlin/com/lounres/kotestTest/Test.kt#L10-L12) will be being tested forever. So I want to limit test execution time. To do this, I wrote [`KotestProjectConfig` object](https://github.com/lounres/kotest-test/blob/master/src/commonTest/kotlin/config.kt#L11-L14) with custom `timeout` implementation:
```kotlin
object KotestProjectConfig : AbstractProjectConfig() {
    override val timeout: Duration = 5.seconds
    override val parallelism: Int = 4
}
```

But nothing changes.

**Comment by lounres** [comment]
I just upgraded the MRE a bit. And here is a video of how the test is not stopped in 5 seconds.

https://user-images.githubusercontent.com/43728100/224392533-2b898957-8314-41f7-8a61-b9ebc616a00a.mp4

**Comment by Kantis** [comment]
Timeout works based on [cooperative cancellation](https://kotlinlang.org/docs/cancellation-and-timeouts.html#cancellation-is-cooperative) for coroutines. We have no mechanism to interrupt uncooperative threads. 

If you changed your bugged function to this it'll work (requires kotlinx-coroutines-core dep in main sourceset as well)
```kotlin

suspend fun buggedFunction(): Int = coroutineScope {
    var t = 1
    var count = 1000
    while (isActive) {
        if (count >= 0) {
            println(t)
            count--
        }

        if (t and 1 == 0) {
            t /= 2
        } else {
            t = t * 3 + 1
        }
    }
    t
}

```

Also, your configuration object _is_ found. I tested it by adding this override in `KotestProjectConfig` and you can find the print in the logs.
```kotlin
    override suspend fun beforeProject() {
        println("Hello from project config")
    }
```

**Comment by lounres** [comment]
Yeah, I see that the configuration is found and is used. Thanks!

Also, thanks for your description of what is going on! But actually I don't want to modify the function any bit (I want to change it only to remove bugs) because it's a public library function. (One can see it as a third-party not-suspendable function. So there is no way to make it cooperative and even suspendable.)

So, following your words, I assume that there is no way to stop a test with a function that takes forever to finish (because of an unexpected infinite loop in my use case).

**Comment by sksamuel** [comment]
You can use this on the JVM: https://kotest.io/docs/framework/timeouts/blocking-tests.html
Which will run the test on another thread and interrupt it.

**Comment by lounres** [comment]
Thanks a lot! Sorry for such silly question.
