### ISSUE TITLE
kotest-extensions-spring is missing in io.kotest:kotest-bom

### ISSUE THREAD

**Issue by Stefanqn** [kotest/kotest#3450]
several extensions are in the kotest-bom, yet `kotest-extensions-spring` [is missing in 5.5.5](https://central.sonatype.com/artifact/io.kotest/kotest-bom/5.5.5)

**Comment by Kantis** [comment]
Not sure if we want to do this? The BOM lifecycle is tied to the main project. The extensions have a separate release lifecycle, so there might be multiple versions of an extension released between each main project release.
