### ISSUE TITLE
`AbstractProjectConfig` is not picked up in KMP tests?

### ISSUE THREAD

**Issue by kirillzh** [kotest/kotest#3462]
Kotest 5.5.4

I have:
- multi-module KMP project, most of the modules have unit tests
- common `:testing` Gradle module that defines custom `AbstractProjectConfig` implementation that I want to share between all tests in the project

I was assuming Kotest would pick up the config at [runtime](https://kotest.io/docs/framework/project-config.html) but that doesn't seem to be happening. I tried adding the `:testing` module to tests and that doesn't seem to make a difference either. Is there anything I'm missing in my setup?

**Comment by kirillzh** [comment]
Even adding config along with test specs, in the same module as a spec, doesn't work:

```kotlin
class MyTests : FunSpec({
	test("foo") {}
})

class Config : AbstractProjectConfig() {
  init {
    error("fail!") // would expect tests to fail because of this?
  }
}
```

**Comment by kirillzh** [comment]
Oh interesting, looks like `Config` needs to be a singleton object:
```kotlin
object Config : AbstractProjectConfig() {
```

**Comment by OliverO2** [comment]
From kotlinlang Slack:
> Actually, auto-detection works just fine on non-JVM targets: For K/Js and K/Native you have to add the Kotest Gradle plugin to the build. This will then activate a compiler plugin, which in turn picks up `AbstractProjectConfig`.

Did this work in your case?

**Comment by kirillzh** [comment]
I think the actual issue that am I running into is that the isolation mode doesn't get picked up on K/N - I wanted to apply it in the global project config and assumed that maybe the project config itself wasn't working, turns out it's the isolation mode that doesn't get picked up, which is already filed here https://github.com/kotest/kotest/issues/3414.
