### ISSUE TITLE
Documentation Version Switcher Broken for Older Versions

### ISSUE THREAD

**Issue by avarun42** [kotest/kotest#3478]
On the Kotest docs website, the documentation version switcher in the top right is broken when viewing the docs for any version older than 5.5, as show below:
![image](https://user-images.githubusercontent.com/5677408/229565741-14dabc93-7431-4dd0-be49-2722457f5cc7.png)

There are a few different issues.
1. The switcher shows version 5.5 multiple times
2. Both version 5.5s link to the same place but only one is ever highlighted
3. The highlighted version and the displayed version number both say 5.5 when viewing the docs for any version older than 5.5

**Comment by Kantis** [comment]
Thanks! Fixed by https://github.com/kotest/kotest/commit/abaaa4a1ba926f0693e290277e997bf72d0daca6
