### ISSUE TITLE
Add support of Equality to all contain* matchers

### ISSUE THREAD

**Issue by neckbosov** [kotest/kotest#3480]
Currently only `contain` matcher supports passing custom `Equality` but other matchers (`containAll`, `containExactly`, `containExactlyInAnyOrder`, `containOnly`) are not, which is a bit confusing for me. I think it will be great to support it to make collections matching more flexible.

**Comment by pientaa** [comment]
I can take this one

**Comment by sksamuel** [comment]
Closing as 5.8.1 is being released with this change.
