### ISSUE TITLE
The `blockingTest` and `timeout` options have inconsistent behaviour and only work for sleeping threads.

### ISSUE THREAD

**Issue by Jadarma** [kotest/kotest#3484]
I was trying to implement a test that asserts a function can be computed within a given time frame.
However, it is not a suspending function, and as [mentioned in the documentation](https://kotest.io/docs/framework/timeouts/blocking-tests.html) the regular `timeout` config option does not work because of the cooperative nature of coroutines, and I tried to use `blockingTest` as instructed.

However, I was puzzled when the timeout mechanism did not seem to work at all for an infinite loop like `while(true)`, only for `Thread.sleep()` like in the example so I prepared a little sample to showcase it.

- **Kotest Version**: `5.5.5`
- **Platform**: JVM (Both JDK 11 and 17)
- **Expected Behavior**: All tests should time out with a `TestTimeoutException`.
- **Actual Behavior**: Depends, either no timeout or wrong exception thrown, see below.

```kotlin
import io.kotest.core.spec.style.FunSpec
import io.kotest.engine.test.interceptors.TestTimeoutException
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.delay
import kotlinx.coroutines.withTimeout
import kotlin.time.Duration.Companion.seconds

class InfiniteLoopDetectionTest : FunSpec({

    // ✅ Expected behavior because of non-blocking code, throws io.kotest.engine.test.interceptors.TestTimeoutException
    test("Non-blocking timeout").config(timeout = 5.seconds, blockingTest = false) {
        delay(10000)
    }

    // ⚠️ Test does stop but shows java.lang.InterruptedException instead of TestTimeoutException
    test("Blocking test with sleeping threads").config(timeout = 5.seconds, blockingTest = true) {
        Thread.sleep(10000)
    }

    // ⚠️ Tried ignoring that particular exception just to see what would happen.
    // Test does stop but shows the raw kotlinx.coroutines.TimeoutCancellationException instead of TestTimeoutException
    test("Blocking test with sleeping threads and correct error").config(timeout = 5.seconds, blockingTest = true) {
        runCatching { Thread.sleep(10000) }
    }

    // ❌ Does not time out at all, runs indefinitely.
    test("Blocking test with non-sleeping loop").config(timeout = 5.seconds, blockingTest = true) {
        while(true) {}
    }

    // ✅ A sanity check of manually emulating what I expect the blockingTest option to abstract away.
    // Expected behavior, throws io.kotest.engine.test.interceptors.TestTimeoutException
    test("Non-blocking thread with manually managed thread") {
        val infiniteThread = Thread { while(true) {} }
        val timeout = 5.seconds
        try {
            withTimeout(timeout) {
                infiniteThread.start()
                while(infiniteThread.isAlive) delay(100)
            }
        } catch (ignore: TimeoutCancellationException) {
            infiniteThread.interrupt()
            throw TestTimeoutException(timeout, testCase.name.testName)
        }
    }
})
```

Is this a bug, a misconfiguration issue, or am I misunderstanding the use of `blockingTest`?
Thank you!

**Comment by sksamuel** [comment]
It's just how interruption works on the JVM. You cannot interrupt a thread unless it is blocked, or itself checks the interrupted status flag.

A while(true) is just spin locking here. If you added a Thread.sleep(1) in the loop it would work. As would checking Thread.isInterrupted().

The blockingTest = true is designed to help catch user error, but there are limits to what it can do.

Some useful links:
https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#interrupt()
https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#interrupted()
https://stackoverflow.com/questions/3590000/what-does-java-lang-thread-interrupt-do
