### ISSUE TITLE
Question: Split project into three parts starting in 6.0

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3486]
Should we independently release assertions, framework and property modules starting with 6.0 to allow each to move at different speeds?

We could start with 6.0 on all three, and move assertions and property tests into new repos.

Pros:
* Faster build times.
* Support new versions of kotlin quicker (typically just framework needs to change)
* Allow each to release on their own cadence

Cons:
* Users may have come to expect the versions are in lock step

**Comment by Kantis** [comment]
I think there's some merit to keeping everything in a single project. 

We immediately discover when a change in framework causes issues with assertions/property testing, and either fix the assertions or revert the framework change before anything is released.

There's never any dependency mismatch issues between assertions/framework/prop modules. By splitting them up, we could potentially run into situations where there's a mismatch between depended-upon libraries.

**Comment by JavierSegoviaCordoba** [comment]
They can be different versions and has different publishing timing, but they can be on the same mono repo.

**Comment by ashishkujoy** [comment]
Running all test of kotest repo requires around 20 min and overall build time very high. I think there will be good improvement in development experiance by spliting repo.

**Comment by LeoColman** [comment]
We can also use git submodules instead of migrating to a different repository.
During the build we could detect what part was changed and run the build only on those

**Comment by Kantis** [comment]
This is what gradle excels at though. I very seldomly have to do a full build. Running a single test is quick, running just `jvmTest` is a couple of minutes at most, usually. Maybe we could check if Gradle would sponsor us with their premium features, like shared build caches etc.? It might make it easier for people who are involved less often as well.

Overall I think the compatibility management from having everything separate would be painful, both as contributors and for consumers. 

It would be nice to hear how the JUnit team has reasoned since they must've had similar thoughts at some point.

**Comment by aSemy** [comment]
Would it be possible to get a Gradle Build Cache instance for Kotest? Then the cache could be shared for all developers, even on a fresh checkout. 

There are plugins for using cloud providers, like GCP and AWS, to host build cache. There's a [Docker image](https://hub.docker.com/r/gradle/build-cache-node/) too, which has more options for controlling access and clean-up.

**Comment by aSemy** [comment]
There are a few other build-config fixes that will help improve build performance

- enable parallel builds. Currently this is disabled. 

   https://github.com/kotest/kotest/blob/ee33820b7d7f9382474853d7c0c75067600597ad/gradle.properties#L13

- enable configuration cache means faster project loading and sync in IDE, and also tasks will run in parallel within the same project. 

  This will require some prep work, as currently Kotest has some cross-project configuration, e.g. in [`kotest-framework-multiplatform-plugin-gradle/build.gradle.kts`](https://github.com/kotest/kotest/blob/ee33820b7d7f9382474853d7c0c75067600597ad/kotest-framework/kotest-framework-multiplatform-plugin-gradle/build.gradle.kts#L36-L68) (This might be blocked by Kotlin/Native, which I think currently has problems with config-cache.)


_Note that Maven Central doesn't like parallel uploads, so `--no-parallel` and `--no-configuration-cache` should be added to the publishing commands._

* Remove low-tiered Kotlin/Native targets. [Kotlin recently sorted the Kotlin/Native targets into tiers](https://kotlinlang.org/docs/native-target-support.html#tier-1). Dropping support might be controversial, but I think it's worth investigating.

**Comment by LeoColman** [comment]
> Dropping support might be controversial, but I think it's worth investigating.

I like the idea of dropping support. 
That would help with artifacts that get lost every now and then and artifacts that we fail to publish because Github doesn't support it.

Adding support to platforms depending on how Kotlin adds support to them is an interesting idea

**Comment by aSemy** [comment]
Could https://github.com/martinbonnin/vespene help with publishing?

> Avoiding split repositories during upload by [creating a staging repository](https://support.sonatype.com/hc/en-us/articles/213465868-Uploading-to-a-Staging-Repository-via-REST-API) before upload and uploading all files to this staging repository.

**Comment by sksamuel** [comment]
What I'd like to do is have different release cadences for the project.

**Comment by Kantis** [comment]
Let's go for it then 👍

**Comment by sksamuel** [comment]
I think the points others raised here have convinced me to keep it together.
And once we disable classgraph scanning by default in 6.0, the test suite will be way faster.
