### ISSUE TITLE
"shouldBeEqualToUsingFields" and "shouldBeEqualToComparingFields" does not work with lists.

### ISSUE THREAD

**Issue by DasOhmoff** [kotest/kotest#3492]
Hello 👋, thank you for this nice plugin and for your efforts! :)

We are trying to port our codebase over to kotlin and `kotest` from java and `assertj`. In order to do so, we need some way to compare two normal **_non data class objects_** with each other field by field, or property by property. Naturally, the kotest `shouldBeEqualToComparingFields` function seems a perfect fit for that.

But we ran in the following issue: when trying to compare the fields of two objects that contain a list, then the comparison does not work out. For example, the following test fails:
```kotlin
class Order(val id: Long)
class Person(val list: List<Order>)

@Test
fun test() {
  val person1 = Person(listOf(Order(0)))
  val person2 = Person(listOf(Order(0)))

  person1 shouldBeEqualToComparingFields person2   // ❌ test fails
} 
```

The test passes when using the following syntax with `AssertJ`:
```java
assertThat(person1).usingRecursiveComparison().isEqualTo(person2)   // ✔️ test passes
```

We would love to switch over to kotlin and kotest, this is one of the hurdles that is holding us back. Is there some way to fix this, maybe even some functionality that we missed?

By the way, we are using kotest version: 5.5.5

Thanks!

**Comment by ashishkujoy** [comment]
This is the intented behaviour shouldBeEqualToComparingFields works on fields. Elements of list are not its fields.

**Comment by DasOhmoff** [comment]
Ah ok. We assumed it would work that way, because the `shouldBeEqualToComparingFields` compares recursively and therefore the list items, which we assumed to be stored internally as an array field somehow, would be also compared. Seems like this is not the case.

So in that case, this "bug report" can be closed, we opened a question issue here instead: #3494
