### ISSUE TITLE
Kotest v5.6.1 has no artifacts for tvOS on maven central

### ISSUE THREAD

**Issue by MSDarwish2000** [kotest/kotest#3493]
I can confirm that Kotest v5.6.1 has no artifacts for tvOS on maven central by browsing the published files at [this link](https://repo1.maven.org/maven2/io/kotest/). 

This affects not only testing on tvOS targets but also affects publishing libraries that just use Kotest for testing. For example, when I updated my library to use Kotest v5.6.1, I've got this error while [publishing snapshot version](https://github.com/MayakaApps/Kache/actions/runs/4736276860/jobs/8407594302):

```
Execution failed for task ':kache:transformCommonMainDependenciesMetadata'.
> Could not resolve all files for configuration ':kache:tvosArm64TestCompilationDependenciesMetadata'.
   > Could not find io.kotest:kotest-assertions-core-tvosarm64:5.6.1.
     Required by:
         project :kache > io.kotest:kotest-assertions-core:5.6.1
```

I'm not sure why it is needed when publishing as Kotest is obviously a test dependency only, but it may be for metadata purposes.

**Comment by sksamuel** [comment]
Should be there now

**Comment by MSDarwish2000** [comment]
Thank you for the quick fix. I can confirm that the missing artifacts were added and the problem is solved.
