### ISSUE TITLE
Matchers for `decreasing` and `increasing` don't include sequences

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#3498]
`shouldBeMonotonicallyDecreasing`, `shouldBeMonotonicallyIncreasing` and the likes account for `List`, `Iterable` and `Array`. These matchers can also be applied to Sequences

**Comment by Kantis** [comment]
how does this differ from `shouldBeSorted`?

**Comment by LeoColman** [comment]
Good question.
Their implementation looks the same:

```
fun <T> sortedWith(cmp: (T, T) -> Int): Matcher<List<T>> = object : Matcher<List<T>> {
   override fun test(value: List<T>): MatcherResult {
      val failure = value.withIndex().firstOrNull { (i, it) -> i != value.lastIndex && cmp(it, value[i + 1]) > 0 }
      val snippet = value.joinToString(",", limit = 10)
      val elementMessage = when (failure) {
         null -> ""
         else -> ". Element ${failure.value} at index ${failure.index} shouldn't precede element ${value[failure.index + 1]}"
      }
      return MatcherResult(
         failure == null,
         { "List [$snippet] should be sorted$elementMessage" },
         { "List [$snippet] should not be sorted" })
   }
}
```

```
private fun <T> testStrictlyIncreasingWith(value: List<T>, comparator: Comparator<in T>): MatcherResult {
   val failure = value.zipWithNext().withIndex().find { (_, pair) -> comparator.compare(pair.first, pair.second) >= 0 }
   val snippet = value.print().value
   val elementMessage = when (failure) {
      null -> ""
      else -> ". Element ${failure.value.second} at index ${failure.index + 1} was not strictly increased from previous element."
   }
   return MatcherResult(
      failure == null,
      { "List [$snippet] should be strictly increasing$elementMessage" },
      { "List [$snippet] should not be strictly increasing" }
   )
}
```

**Comment by LeoColman** [comment]
I just got used to the `monotonicallyIncreasing` and `strictlyIncreasing` functions, but they seem to be just an alias to a `isSorted` indeed.

@sksamuel I think you originally developed these functions. What's your opinion on this?


For me, I'd say we deprecate the `increasing` / `decreasing` in favor of `sorted`. We can also create a permanent alias to them, but I think it's too much

**Comment by sksamuel** [comment]
Sounds like they're the same to me - as long as we have a
shouldbeSortedDesc option too.

**Comment by sksamuel** [comment]
I came to remove these, but strictly increasing is not the same as sorted.
So we can remove the monotonically ones, but then it might be nice to have the names in tests for clarity. I think we should just have the monotonic ones delegate to sort for the implementation.
