### ISSUE TITLE
Arbitrary for Date in JVM

### ISSUE THREAD

**Issue by Jacks0N23** [kotest/kotest#3503]
I saw at at [Generators List](https://kotest.io/docs/proptest/property-test-generators-list.html) there no Arb for Date in JVM
Could you add it?

**Comment by Kantis** [comment]
I think we can add this

**Comment by sksamuel** [comment]
Are we talking java.util.Date ?

**Comment by Kantis** [comment]
I assumed so. Is java.sql.Date much used?

@Jacks0N23 please clarify 😄

**Comment by Jacks0N23** [comment]
Yeah, sorry, for delay, of course I mean java.util.Date

**Comment by sksamuel** [comment]
PR welcome.
