### ISSUE TITLE
Changelog should make class moving into new module more prominent

### ISSUE THREAD

**Issue by XiangRongLin** [kotest/kotest#3510]
I just spent at least an hour chasing down why my build didn't work after bumping kotest from 5.5.4 to 5.6.1.
The reason was that a class got moved into a new module ([PR](https://github.com/kotest/kotest/pull/3470)) and in the changelog the move is "hidden" between all the other [improvements](https://kotest.io/docs/changelog.html#improvements-1), even though I now need to explicitly add the `io.kotest:kotest-extensions-now` dependency

**Comment by sksamuel** [comment]
This is a problem which we are addressing by adding in the API spec check which will determine, per module, if the public API changes.

Sorry that you got caught out by this.
