### ISSUE TITLE
Collection.shouldHaveSingleElement is missing  IntelliJ's Click to see difference 

### ISSUE THREAD

**Issue by matejdro** [kotest/kotest#3515]
When calling `.shouldHaveSingleElement(..)` on a collection, resulting error message is just printed in one very long line, without "Click to see difference" IntelliJ helper.

As a workaround, `.shouldHaveSize(1).first().shouldBe(...)` can be used instead, but is more verbose.

**Which version of Kotest are you using:** 5.5.4

**Comment by Kantis** [comment]
Can you provide an example of the output you're getting, and the output you wish you'd get?

**Comment by matejdro** [comment]
With the following data:

```kotlin
data class Product(
   val brand: String,
   val category: String,
   val description: String,
   val discountPercentage: Double,
   val id: Int,
   val images: List<String>,
   val price: Int,
   val rating: Double,
   val stock: Int,
   val thumbnail: String,
   val title: String
)

val firstProduct = Product(
   brand = "Pear",
   category = "Computers",
   description = "A computer for everyone",
   discountPercentage = 0.0,
   id = 1,
   images = emptyList(),
   price = 1000,
   rating = 4.5,
   stock = 10,
   thumbnail = "https://www.pear.com/thumbnail",
   title = "Pear Computer"
)

val secondProduct = Product(
   brand = "Pear",
   category = "Computers",
   description = "A computer for everyone",
   discountPercentage = 0.0,
   id = 1,
   images = emptyList(),
   price = 2000,
   rating = 4.5,
   stock = 10,
   thumbnail = "https://www.pear.com/thumbnail",
   title = "Pear Computer"
)
```


`listOf(firstProduct).shouldHaveSingleElement(secondProduct)` results in an output that is hard to compare:

![image](https://user-images.githubusercontent.com/507922/236449079-c464fc24-358a-4b90-abc2-af63b19b653f.png)

`listOf(firstProduct).shouldContainExactly(secondProduct)`, on the other hand provides much better output, allowing you to quickly spot the difference, including `<Click to see difference>` button:

![image](https://user-images.githubusercontent.com/507922/236449243-10ddd8dc-1b56-4b20-a63f-459a9998eaf2.png)

come to think of it, maybe `shouldHaveSingleElement` could just call `shouldContainExactly` under the hood? It seems like there are two methods that do the same thing.
