### ISSUE TITLE
Document which kotest extension I have to add to use current instant listeners (>= 5.6)

### ISSUE THREAD

**Issue by enolive** [kotest/kotest#3522]
It seems that with kotest 5.6, functions such as `withConstantNow` are no longer part of the core functionality, but moved to an extension module. While this is completely understandable, you should document it in https://kotest.io/docs/extensions/instant.html

As far as I understand, they are now a part of 

https://central.sonatype.com/artifact/io.kotest/kotest-extensions-now/5.6.1/overview

**Comment by Kantis** [comment]
Thanks 👍🏼
