### ISSUE TITLE
kotest-asssertions-klock needs iosSimulatorArm64 support

### ISSUE THREAD

**Issue by dalewking** [kotest/kotest#3527]
Current release does not support ios arm 64 simulator support, needed for using newer Macs

**Comment by sksamuel** [comment]
I cannot get our klock to build at the moment, I think something is up with the released klock dependencies.

**Comment by sksamuel** [comment]
I was checking back to see if klock had released this dependency, but it looks like klock has gone from their website. I wonder if it was discontinued?

**Comment by dalewking** [comment]
> I was checking back to see if klock had released this dependency, but it looks like klock has gone from their website. I wonder if it was discontinued?

It definitely was released with this support, but is no longer actively maintained. It was moved along with other libraries to a separate repo and there are many broken links. I highly recommend switching to Kotlinx DateTime

**Comment by sksamuel** [comment]
I tend to agree with you. I will close this and I'm going to archive the extension.
