### ISSUE TITLE
types of Char are not classified as platform stable

### ISSUE THREAD

**Issue by hughlunnon** [kotest/kotest#3533]
version 5.6.2 

the block in kotest-common/src/commonMain/kotlin/io/kotest/mpp/stable.kt
```
private val allPlatformStableTypes = setOf(
   String::class,
   Int::class,
   Long::class,
   Double::class,
   Float::class,
   Byte::class,
   Short::class,
   Boolean::class,
   Pair::class,
   Triple::class,
)
```
misses "Char", which means the code

```
    context("test something") {
        data class TestData(val input: String?, val expected: Char)
        withData(
            TestData("US", 'Y'),
            TestData("UK", 'N'),
            TestData(null, 'N'),
        ) { (input, expected) ->
           doSomething(input) shouldBe expected
        }
    }
```

gives lots of warnings like 
`Warning, type class kotlin.Char used in data testing does not have a stable toString()`

I think this is unintended - Char toString's just fine. Happy to raise a PR to fix, just wanted to check this was a bug and not intentional for some reason I don't see before I did so

**Comment by sksamuel** [comment]
Yeah its a miss. Pr welcome.

**Comment by hughlunnon** [comment]
PR [here](https://github.com/kotest/kotest/pull/3536)

**Comment by sksamuel** [comment]
nice :)
