### ISSUE TITLE
BeforeSpecListener not implemented as documented

### ISSUE THREAD

**Issue by zakhenry** [kotest/kotest#3534]
In the BeforeSpecListener docblock, it states 
```
    * This callback is only invoked if the spec has active tests. If all tests in a spec
    * are disabled, or the spec has no tests defined, then this listener will NOT be invoked.
```

however if you run the following test (lifted from `com/sksamuel/kotest/listeners/testlistener/instancepertest/BeforeSpecTest.kt`) with the modification that I've updated the expected count, and commented out the enabled specs:

```kotlin
package com.sksamuel.kotest.listeners.testlistener.instancepertest

import io.kotest.core.listeners.TestListener
import io.kotest.core.spec.IsolationMode
import io.kotest.core.spec.Spec
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.util.concurrent.atomic.AtomicInteger

class BeforeSpecTest : FunSpec() {

   val listener = object : TestListener {
      override suspend fun beforeSpec(spec: Spec) {
         counter.incrementAndGet()
      }
   }

   override fun isolationMode(): IsolationMode = IsolationMode.InstancePerTest

   companion object {
      private val counter = AtomicInteger(0)
   }

   init {

      register(listener)

      afterProject {
         counter.get() shouldBe 0
      }

      test("ignored test").config(enabled = false) {}
//      test("a").config(enabled = false) {}
//      test("b").config(enabled = false) {}
//      test("c").config(enabled = false) {}
//      test("d").config(enabled = false) {}
   }
}

```

I get a test failure:
`io.kotest.engine.extensions.ExtensionException$AfterProjectException: io.kotest.assertions.AssertionFailedError: expected:<0> but was:<1>
	at io.kotest.engine.project.ProjectExtensions.afterProject(ProjectExtensions.kt:34)`

From the docs I would expect there to be no beforeSpec run.

I believe the fix would be to check all the root tests and if they are all disabled, don't run the beforeSpec hook.

**Comment by zakhenry** [comment]
and besides, the original test doesn't add up

```
    * This callback is invoked just before the first test (or only test) is executed
    * for a Spec.
```

and yet it asserts the expected count should be 5 in the original test, when I would expect this hook to execute 0 or 1 times, based on the docblock at least.

Am I just missing some concept about the difference between a spec and a test?

**Comment by Kantis** [comment]
@zakhenry I think it's tied to [isolation mode](https://kotest.io/docs/framework/isolation-mode.html). `InstancePerTest` will instantiate the Spec once per test. For `IsolationMode.SingleInstance` I think it would be 0 or 1.

**Comment by zakhenry** [comment]
@Kantis ah you're right that does explain the count being 5, however the first point still stands that I would expect it to be zero when the tests are all ignored. Or perhaps the docs are wrong?

**Comment by Kantis** [comment]
I'm unsure, but I think it sounds like a bug. If all root tests are disabled then there's nothing to do for the spec and there's no reason to run `beforeSpec`. Not running `beforeSpec` in this case would also be in line with the documentation, so feels like it's not working as intended. Would appreciate some other maintainer's input on it before changing it however.

If you'd like we can create a draft with a test and try it on a few versions to see if this is a regression

**Comment by zakhenry** [comment]
Yea that sounds good thanks. The context for me is that I have a number of specs that use extensions that have `beforeSpec` hooks that do things like starting docker containers etc for integration testing. 

I'm setting up our tests to run end to end tests based on a tag that is added to these e2e tests, and want to run just these e2e tests in CI (on a runner without docker access) using the tag mechanism. The issue arises as the integration tests that do docker things are correctly being skipped, but their beforeSpec is running for no reason, and crashing out.

edit: digging into hooks deeper, I think I can achieve this using `beforeContainer` instead. This might make my extension restart slightly more often that i would prefer, but no big deal

**Comment by sksamuel** [comment]
This is definitely a bug based on the docs.

However, it is complicated to fix - because we have various dynamic ways of determining if a test is enabled, so it's rather convoluted to do this when the spec is instantiated.

For instance, you can use a function to determine if a test should run or not. We could run all the functions when the spec is created, but then you lose the ability to disable a test based on the result of a previous test.

I'm minded to say we adjust the docs to reflect the reality, and add another mechanism to do what the OP needs - something like a "beforeFirstTestInSpecListener" which is only fired when a test is really starting up.

Thoughts?

**Comment by Kantis** [comment]
I think that's a pragmatic solution. 🙂

**Comment by zakhenry** [comment]
Oh awesome thanks @sksamuel this will allow a nice cleanup to our tests that use leaf isolation
