### ISSUE TITLE
Jacoco 0% Test Coverage after updating from 5.6.1 to 5.6.2

### ISSUE THREAD

**Issue by piu130** [kotest/kotest#3535]
When updating kotest from `5.6.1` to `5.6.2` the `jacoco-maven-plugin` reports 0% test coverage.

I already went through the commits but did not find anything related to this problem. Do you see it?

I'll try to add a sample project when I have some free time.

**Comment by Kantis** [comment]
@piu130 any luck reproducing, or did you figure it out?

**Comment by piu130** [comment]
Hi @Kantis , I just tried bumping kotest again and it worked. I assume, there was some library upgrade that fixed it. Maybe it was the bump to Kotlin 1.9.0. Thanks for your help :)
