### ISSUE TITLE
Tests pass unexpectedly with background scope and multiple test containers

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#3537]
Kotest 5.6.2 

We encountered some weird Kotest behavior and it's unclear to us if it's a bug or we're doing something wrong. Basically when using coroutines' `runTest` and `backgroundScope`, if a job in `backgroundScope` fails, then all tests pass. However, this only happens if there's another parallel test container that has a job in `backgroundScope` that never ends. This is very surprising, as I thought `backgroundScope` would be properly cleaned up, and overall having a _dependency_ like this looks like a bug?

Here's repro code:

```kotlin
package com.repro

import io.kotest.core.spec.IsolationMode
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.runTest

class Repro : DescribeSpec() {

    override fun isolationMode() = IsolationMode.InstancePerLeaf

    init {
        describe("repro") {
            runTest(UnconfinedTestDispatcher()) {
                describe("tested expression") {
                    backgroundScope.launch { error("Error in background scope") }
                    // coroutineScope { launch { error("Error in non-background scope") } }

                    it("should not be reached?") {
                        Unit
                    }
                }

                describe("background scope here never ends") {
                    val neverEnds = backgroundScope.launch {
                        flow<Unit> { }.firstOrNull()
                    }

                    it("should fail") {
                        neverEnds.isCompleted shouldBe true
                    }
                }
            }
        }
    }
}
```

Things to try (the expected behavior is for these tests to fail):
* running this test as is will pass
* making the second `describe` an `xdescribe("background scope here never ends")` will not execute the second test, **but tests still pass**
* **removing the entire `describe("background scope here never ends")` block makes tests fail**
* swapping the describes with each other (changing the order) makes tests fail too
* Uncommenting `Error in non-background scope` line will make tests fail
* changing the isolation mode to `SingleInstance` will make tests fail

We tried to debug this but we're at a loss. I thought `InstancePerLeaf` should ensure that tests are pretty much independent, and I completely don't see where or what could swallow background scope errors, or why background scope would not propagate the errors as we expect.

(a note — we're trying to use Coroutines' `runTest` directly because back when Kotest didn't have support for background jobs we just created own abstractions and it felt reasonable to use _native_ APIs when possible, even within Kotest context. We also use the same extensions for non-Kotest tests, so it'd be nice to keep using `runTest`, unless it's inherently incompatible with Kotest)

**Comment by sksamuel** [comment]
I don't really know what UnconfinedTestDispatcher is meant to do, but if we remove that, it all works as expected.
I guess that there's some thread trickery going on and backgroundScope is not reporting the error up the chain properly.

I think you should be able to use runTest inside a Kotest test, but I wouldn't then nest further kotest contexts. I have no idea how it would all play together and it would probably end up going down a rabbit hole to figure it out.

**Comment by smworks** [comment]
Hi. I have a lot simpler test case:
```
class RandomClass {
    init {
        GlobalScope.launch {
            throw Exception("I am failing")
        }
    }
}

class RandomClassTest : FunSpec() {
    init {
        test("test should fail") {
            RandomClass()
        }
    }
}
```

This test passes successfully, yet in logs I can see "I am failing" exception. Can someone help me understand why it is not failing?

**Comment by OliverO2** [comment]
@smworks Two things here:

1. Your test function completes before `RandomClass` has launched its `GlobalScope` coroutine. When calling `launch`, you cannot always assume that it will start its job eagerly. See [CoroutineStart/DEFAULT](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-start/-d-e-f-a-u-l-t/):
    > If the CoroutineDispatcher of the coroutine context returns true from CoroutineDispatcher.isDispatchNeeded function as most dispatchers do, then the coroutine code is dispatched for execution later, while the code that invoked the coroutine builder continues execution.
2. The exception is thrown from a root coroutine in `GlobalScope`. This will never be caught by the coroutine invoking `RandomClass()`, so there is nothing for Kotest to detect. See [Exception propagation](https://kotlinlang.org/docs/exception-handling.html#exception-propagation).
 
 
To illustrate:

```
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext

class RandomClass {
    init {
        GlobalScope.launch {
            println("GlobalScope – about to fail")
            throw Exception("GlobalScope – I am failing")
        }
    }
}

fun main() = runBlocking {
    withContext(Dispatchers.Default) {
        try {
            RandomClass()
            println("main – past RandomClass")
//             delay(500)
//             println("main – past delay – no exception caught")
        } catch (throwable: Throwable) {
            println("main – caught $throwable")
        }
    }
}
```

[Running this on Playground](https://pl.kotl.in/RCoEoL2yz) will print:
```
main – past RandomClass
GlobalScope – about to fail
```

After removing the comments on `delay` and `println`, and [running this on Playground](https://pl.kotl.in/ajCMAb0n7), it will print:
```kotlin
main – past RandomClass
GlobalScope – about to fail
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" java.lang.Exception: GlobalScope – I am failing
	at RandomClass$1.invokeSuspend(File.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(2), "coroutine#2":StandaloneCoroutine{Cancelling}@47c9766b, Dispatchers.Default]
main – past delay – no exception caught
```

**Comment by sksamuel** [comment]
Closing as per O2s comments, not a kotest issue.
