### ISSUE TITLE
Update shouldEqualJson documentations and deprecation annotation

### ISSUE THREAD

**Issue by jogerj** [kotest/kotest#3543]
The [documentation ](https://kotest.io/docs/assertions/json/content-json-matchers.html#shouldequaljson)still refers to usage of `shouldEqualJson` even though this function is deprecated. 

In addition, the `@Deprecated` annotation should be updated with the appropriate `ReplaceWith` values to allow quick replacement in the IDE e.g.

```kotlin
@Deprecated(
    "Use shouldEqualJson which uses a lambda. Deprecated since 5.6. Will be removed in 6.0",
    ReplaceWith("this shouldEqualJson { options; expected }", ["io.kotest.assertions.json.equalJson"]),
)
fun String.shouldEqualJson(@KotestLanguage("json", "", "") expected: String, options: CompareJsonOptions) {
   this should equalJson(expected, options)
}
```

~~Why is this function deprecated anyways? is the `should equalJson` meant to be the replacement?~~

Edit: I just found `this shouldEqualJson { ... }`

**Comment by dhoepelman** [comment]
This is indeed confusing, especially as the signature of the replacement function is not very straightforward.

I guess this is the intended replacement?

```kotlin
"""{...}""" shouldEqualJson {
  fieldComparison = FieldComparison.Lenient
  """{...}"""
}
```

**Comment by Kantis** [comment]
It is. What were you using before? `shouldEqualSpecifiedJson`?

**Comment by dhoepelman** [comment]
Correct. We've replaced with our own extension, since we extensively used it.

In case others want it:
```kotlin
infix fun String.shouldEqualSpecifiedJson(other: String) =
    this shouldEqualJson {
        fieldComparison = FieldComparison.Lenient
        other
    }
```

**Comment by Kantis** [comment]
IMO we could keep that one. I'll undeprecate it in next release.

**Comment by sksamuel** [comment]
Part of upcoming 5.7
