### ISSUE TITLE
Add KProperty shouldHaveValue assertion

### ISSUE THREAD

**Issue by matejdro** [kotest/kotest#3547]
When comparing several fields from big data classes:

```kotlin
assertSoftly(myDataClass) {
    firstProperty shouldBe true
    secondProperty shouldBe false
    thirdProperty shouldBe 1
}
```

error messages would not be very helpful, it would never say in the error message what property exactly failed:

```
1) expected:<true> but was:<false>
	at ...
2) expected:<false> but was:<true>
	at ...
3) expected:<1> but was:<2>
	at ...
```

However, since we are comparing properties directly, we could do something like this instead:

```kotlin
assertSoftly(myDataClass) {
    ::firstProperty shouldHaveValue true
    ::secondProperty shouldHaveValue false
    ::thirdProperty shouldHaveValue 1
}
```

This could generate much more helpful error message, with property names included:

```
1) firstProperty
expected:<true> but was:<false>
	at ...
2) secondProperty
expected:<false> but was:<true>
	at ...
3) thirdProperty
expected:<1> but was:<2>
	at ...
```

Additionally, we could add `withValue` to get access to other properties, such as null checks:

```kotlin
::firstProperty.withValue { shouldBeNull() }
```

I propose something like this (and I can create a PR for it, if desired):

```kotlin
infix fun <T> KProperty0<T>.shouldHaveValue(value: T) {
    withClue(name) {
        eq(this.get(), value)?.let(errorCollector::collectOrThrow)
    }
}

inline fun <T> KProperty0<T>.withValue(block: T.() -> Unit) {
    withClue(name) {
        block(get())
    }
}
```

**Comment by Kantis** [comment]
I think this is neat for testing properties. Maybe we could call `withValue` -> `shouldMatch`, and `shouldHaveValue` could be implemented as just:

```kotlin
infix fun <T> KProperty0<T>.shouldHaveValue(value: T) {
    withClue(name) {
        this.get() shouldBe value
    }
}

```

Feel free to raise a PR :)

**Comment by sksamuel** [comment]
I think my PR might improve on this idea:
https://github.com/kotest/kotest/pull/3603

**Comment by matejdro** [comment]
Great, I will try to work on a PR for this and will submit it at some point.

#3603 seems like an overkill for me. I wouldn't want to have yet another compiler plugin that slows down the build even more than, when property system (my proposal above) can get us most of the way there without compiling overhead. But I see the appeal.
