### ISSUE TITLE
Matcher compose output incudes failure message for passed tests

### ISSUE THREAD

**Issue by SpyMachine** [kotest/kotest#3550]
I find the output behavior of Matcher.compose strange because it includes the failure message for tests that passed. It's unclear to me if that was the intended design or not but in my use case this is really confusing as I have many matchers composed and some of them are matching on longer strings so the output is already a bit verbose so this makes it really difficult to suss out where the actual error is.

You can technically workaround this by putting conditionals in the failure message functions at the cost of some extra newlines and some pretty ugly code.

Looking at the [code](https://github.com/kotest/kotest/blob/2661fd24bb4fd1f029730afc6e59087b7bf4d828/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/reflection/compose.kt#L16-L28) it seems like it would be very easy to filter out passed tests so that only failed tests failure messages show up. I suppose this could be optional if there's a good use case to keep failure message for passed tests.

I'll put up a PR, let me know what you think. (Edit: After reading contributing docs, I'll wait for feedback 😄)

**Comment by pientaa** [comment]
Yes, totally! @Kantis do you see any blockers?

**Comment by sksamuel** [comment]
@pientaa @SpyMachine see #3646
