### ISSUE TITLE
Unexpected execution order of lifecycle callbacks

### ISSUE THREAD

**Issue by mnonnenmacher** [kotest/kotest#3555]
I am using an extension to setup a database for each test. For this the `beforeEach` function of the extension must be called before the `beforeEach` function of the test classes, because the latter requires the database to be already setup.

My expectation would be that the lifecycle callbacks of the installed extension are always executed before the lifecycle callbacks of test class, but this actually depends on the way the extension is installed and the test class implements the callbacks which I find very unintuitive.

For example, these two variants work:

```kotlin
class MyTest : StringSpec({
    val dbExtension = extension(DatabaseExtension())
    
    beforeEach {
        dbExtension.doSomething()
    }
    
    ...
}
```

```kotlin
class MyTest : StringSpec() {
    private val dbExtension = DatabaseExtension()
    
    override fun extensions(): List<Extension> = listOf(dbExtension)

    override suspend fun beforeEach(testCase: TestCase) {
        dbExtension.doSomething()
    }
    
    ...
}
```

While this variant does not work:

```kotlin
class MyTest : StringSpec() {
    private val dbExtension = extension(DatabaseExtension())

    override suspend fun beforeEach(testCase: TestCase) {
        dbExtension.doSomething()
    }
    
    ...
}
```

The reason is the [following code block](https://github.com/kotest/kotest/blob/9d31ad7a46b5b706d587aad7d46d89344ea89a4e/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/TestExtensions.kt#L37-L44) which puts the test listeners of installed extensions after the test listener created for the overridden lifecycle functions:

```kotlin
fun extensions(testCase: TestCase): List<Extension> {
    return testCase.config.extensions +
        testCase.spec.extensions() + // overriding the extensions function in the spec
        testCase.spec.listeners() + // overriding the listeners function in the spec
        testCase.spec.functionOverrideCallbacks() + // spec level dsl eg beforeTest { }
        testCase.spec.registeredExtensions() + // added to the spec via register
        registry.all() // globals
} 
```

* In variant 1 both the extension and the `beforeEach` function are registered as extensions and are contained in `testCase.spec.registeredExtensions()`. The order is as expected because the extension is installed first.
* In variant 2 the order is as expected because the extension is contained in `testCase.spec.extensions()` and the test class callbacks are contained in `testCase.spec.functionOverrideCallbacks()`.
* In variant 3 the order is not as expected because the extension is contained in `testCase.spec.registeredExtensions()` but the test class callbacks are contained in `testCase.spec.functionOverrideCallbacks()`.

Is there a reason for this order or could `testCase.spec.functionOverrideCallbacks()` safely be moved below `testCase.spec.registeredExtensions()`? For my use case it seems that this would provide a more intuitive behavior.

**Comment by LeoColman** [comment]
@sksamuel @Kantis Do you know why we have this order for lifecycle callbacks?

**Comment by Kantis** [comment]
I'm not sure, but re-arranging might cause headaches for others.. Perhaps just removing the possibility to override stuff would make it more consistent?

**Comment by sksamuel** [comment]
Yeah we prob can't change ordering on people but can always add new more
defined things.

**Comment by sksamuel** [comment]
We probably need a flag to determine this behaviour. I don't think we can just move the order around now, as it will invariably break for someone else.

Some options:
- Add a priority ordering integer value to extensions?
- Add a global configuration setting which determines if installed comes before overrides ?

**Comment by LeoColman** [comment]
I like the global configuration option. It's been our weapon of choice for all these corner-ish use cases

**Comment by Kantis** [comment]
Shouldn't extension lifecycle hooks always run before their in-spec counterpart, no matter how they were registered? Feels like something we could fix in 6.0 

```kotlin
fun extensions(testCase: TestCase): List<Extension> {
    return testCase.config.extensions +
        testCase.spec.extensions() + // overriding the extensions function in the spec
        testCase.spec.listeners() + // overriding the listeners function in the spec
        testCase.spec.functionOverrideCallbacks() + // spec level dsl eg beforeTest { }  // swap this one with the line below and it should be good?
        testCase.spec.registeredExtensions() + // added to the spec via register
        registry.all() // globals
} 
```

**Comment by mnonnenmacher** [comment]
> Shouldn't extension lifecycle hooks always run before their in-spec counterpart, no matter how they were registered? Feels like something we could fix in 6.0

That was at least my expectation as a user of the library. I understand that you cannot easily change the order in a minor release, but if this could be fixed in a major release that would be great. It was quite difficult to figure out why tests started failing when switching from `override suspend fun beforeEach(testCase: TestCase)` to `beforeEach {}` when I expected this to be a no brainer.

**Comment by TerryQuiet** [comment]
I would like to be able to wrap specs hooks in the hooks I define in project config extensions.
Currently its: 
```
before spec in spec
before spec in listener
test execution
after spec in spec
after spec in listener
```

and what I want to achieve is 

```
before spec in listener // start logs collection per spec
before spec in spec
test execution
after spec in spec
after spec in listener // stop logs collection
```
edit: after looking around, I think my goal can be achievable via PostInstantiationExtension

**Comment by sksamuel** [comment]
I agree that extensions should run before callbacks defined inside the spec itself.
Let's change this behavior in 6.0
