### ISSUE TITLE
Not receiving a message as a successful test. How to do it?

### ISSUE THREAD

**Issue by kirinalexdev** [kotest/kotest#3558]
Hello. I have such a test case where not receiving a message is considered successful. Namely: I send a message to kafka for a service, and try to get it after some time. If the message is not received, then the test is passed. Right now I'm using Thread.sleep(5000) to pause before receiving. Maybe there is another, more correct way?

**Comment by LeoColman** [comment]
Could you show us a simple example of what you are trying to do?

**Comment by sksamuel** [comment]
Closing this, not enough info for us to possibly answer. Please provide a self contained failing test and re-open if you would like further help.
