### ISSUE TITLE
Out Of Range Edge Cases for Double Arbitrary

### ISSUE THREAD

**Issue by akefirad** [kotest/kotest#3561]
**Which version of Kotest are you using**
5.5.5

The documentation of Arb.double says:
> Returns an Arb that produces Doubles in range. The edge cases are `Double.NEGATIVE_INFINITY`, , `-1.0`, `-Double.MIN_VALUE`, `-0.0`, `0.0`, `Double.MIN_VALUE`, `1.0`, ClosedFloatingPointRange.endInclusive, `Double.POSITIVE_INFINITY` and `Double.NaN` which are only included if they are in the provided range.

But looking at the implementation, this is not entirely accurate:
```kotlin
fun Arb.Companion.double(
   range: ClosedFloatingPointRange<Double> = -Double.MAX_VALUE..Double.MAX_VALUE
): Arb<Double> = arbitrary(
   (numericEdgeCases.filter { it in range } + nonFiniteEdgeCases  + listOf(range.start, range.endInclusive)).distinct(),
   DoubleShrinker
) {
   it.random.nextDouble(range.start, range.endInclusive)
}
```

Is that a documentation bug or is there away to check wither `nonFiniteEdgeCases` are in the rage or not? Maybe include them only if the start and/or end of the rage is min and/or max values?

**Comment by Kantis** [comment]
How about adding a flag that lets you specify if `nonFiniteEdgeCases` should be included? In my opinion it would make sense to _not_ include them by default. @myuwono WDYT?

**Comment by sksamuel** [comment]
I think we should update the docs to reflect the reality, then add a flag to provide the behavior that it was thought it was doing.

**Comment by kshired** [comment]
@sksamuel 

There's a same issue at `Arb.Companion.float()`.  ( float() function doesn't use nonFiniteEdgeCases list when generating arbitrary values ) 


I'm gonna solve double and float function's problems by adding `includeNonFiniteEdgeCases: Boolean = false` flag and then update documentations. 

Can you this issue assign to me?

**Comment by sksamuel** [comment]
Yep assigned.
