### ISSUE TITLE
assertSoftly with single exception will not provide that exception's stack trace

### ISSUE THREAD

**Issue by matejdro** [kotest/kotest#3563]
Following code:

```kotlin
assertSoftly {
    errorCollector.collectOrThrow(AssertionError())
}
```

Will just print out a very unhelpful error message `java.lang.AssertionError: null`, with the stack trace pointing to a start of `assertSoftly` block.

If you remove `assertSoftly` block, proper stack trace will be printed instead, with actual location of the raised exception.

**Which version of Kotest are you using** `5.6.2`

**Comment by Kantis** [comment]
Why are you doing 
```kotlin
assertSoftly { 
  errorCollector.collectOrThrow(AssertionError()) 
}
``` 
instead of?
```kotlin
assertSoftly { 
  throw AssertionError() 
}
```

**Comment by matejdro** [comment]
This is just a smallest reproducing case. Of course real world would be something like this:

```
assertSoftly {
   if (...) {
      errorCollector.collectOrThrow(...) 
   }

   if (...) {
      errorCollector.collectOrThrow(...) 
   }

   if (...) {
      errorCollector.collectOrThrow(...) 
   }
}
```

If I were to throw, assertSoftly would stop at first exception, negating its whole purpose.

**Comment by Kantis** [comment]
Can you give a more detailed sample? Your if statements are likely better of as matchers.

**Comment by matejdro** [comment]
Here you go:

```kotlin
    @Test
    fun Demo() {
        assertSoftly {
            performSomeTaskWithResult(1).shouldBeSuccessWithStackTrace()
            performSomeTaskWithResult(2).shouldBeSuccessWithStackTrace()
            performSomeTaskWithResult(3).shouldBeSuccessWithStackTrace()
        }
    }

    /**
     * Variant of shouldBeSuccess that also records stack trace of the error, making it easier
     * to debug
     */
    fun Result<*>.shouldBeSuccessWithStackTrace() {
        if (isFailure) {
            val exception = requireNotNull(this.exceptionOrNull())
            errorCollector.collectOrThrow(exception)
        }
    }


    fun performSomeTaskWithResult(input: Int): Result<Unit> {
        // TODO actual production code that can return failed result
        return Result.failure(IOException())
    }
```

Whenever our production code returns an exception, we prefer to directly pass that exception to the testing framework to ensure its stacktrace gets printed out, allowing for easier debugging (developer can immediately see the causing stack trace, instead of just vague "Result should be success, but is failure"). Thus `shouldBeSuccessWithStackTrace` has been born.

If you comment out `assertSoftly` in the top test, everything works fine, full failure exception is printed to console. But if you add `assertSoftly` back, output becomes less useful.

Now, I understand that with multiple failures, `assertSoftly` can't do much (it can't really print multiple stacktraces), but it should at least print out stack trace if only a single thing failed (comment out second two `performSomeTaskWithResult()` calls and you still end up with fairly useless output).

**Comment by sksamuel** [comment]
I'm confused why you're using the error collector directly.
That should be internal to kotest.
Do you have a reason to do that and not just throw exceptions and let the internals handle it?

I'm trying to duplicate your error:

```kotlin
assertSoftly {
   1 shouldBe 2
}
```

Which gives me the proper error:
```kotlin
io.kotest.assertions.AssertionFailedError: expected:<2> but was:<1>
```

**Comment by matejdro** [comment]
If I just throw the exception, it will terminate assertSoftly block, negating its purpose. 

As far as I can tell, error collector is the only way of supplying custom exceptions to kotest? So there is no non-internal API for that.

**Comment by Kantis** [comment]
I believe it would be more correct to create an adapted matcher.

```kotlin
inline fun <reified T> beSuccessWithStackTrace() = object : Matcher<Result<T>> {
   override fun test(value: Result<T>): MatcherResult {
      return MatcherResult(
         value.isSuccess,
         { "Result should be a success but was a failure with exception ${value.exceptionOrNull()?.stackTraceToString()}" },
         { "Result should be a failure but was a success" }
      )
   }
}
```

Your demo should now work, no matter if a single or multiple assertions fail.

```kotlin
    @Test
    fun Demo() {
        assertSoftly {
            performSomeTaskWithResult(1) should beSuccessWithStackTrace()
            performSomeTaskWithResult(2) should beSuccessWithStackTrace()
            performSomeTaskWithResult(3) should beSuccessWithStackTrace()
        }
    }
```

@sksamuel should the `ErrorCollector` API be marked as `internal`?

**Comment by matejdro** [comment]
Doh, totally forgot about printing stack trace directly. Thanks for your help, you are right, the issue was on my side.
