### ISSUE TITLE
Toolchain versions

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3581]
We currently have releases set to 8 in some places, 11 in others. And we're using jdk 17 for compilation.

I think we should compile with the version we're releasing for,  to avoid mistakes creeping in. Are we ready to say JDK 17 is the min required version? Or should we stick with 11.

**Comment by Kantis** [comment]
I think we should probably release for 11 for a while longer, or WDYT? We configure the [jvmTarget here](https://github.com/kotest/kotest/blob/master/buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts#L37), but I suppose that that might break silently at some point. @lwasyl what's your opinion?

**Comment by lwasyl** [comment]
> I think we should compile with the version we're releasing for, to avoid mistakes creeping in.

I agree making sure things work on supported JDKs is important, although I'm not sure compiling with old JDK is the solution. For example, this wouldn't ensure things work on _newer_ JDKs.

As an alternative I can suggest to build using recent JDK and test support for older JDKs by running the tests with lower JDK toolchain. https://jakewharton.com/build-on-latest-java-test-through-lowest-java/ has a good overview of the process.

As for JDK 8 vs 11 vs 17 — I'm not sure to be honest. For maintained Android projects, JDK17 is already minimum (https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp). Gradle itself still supports JDK8, but I don't know of any good source that'd be useful to determine if people still actually use it.

**Comment by LeoColman** [comment]
To add my 2 cents:

I randomly smash Java versions until I get my Kotlin code to compile. So far, the easiest one to do that was Java 8. For a couple of years now I feel that Java 11 is beggining to become easier.  I didn't try much with 17.

From [Kotlin's FAQ](https://kotlinlang.org/docs/faq.html#which-versions-of-jvm-does-kotlin-target):
> By default, the Kotlin/JVM compiler produces Java 8 compatible bytecode. If you want to make use of optimizations available in newer versions of Java, you can explicitly specify the target Java version from 9 to 20.

I think we should stick to Kotlin's default.

[Kotlin is also using JDK 8 as their toolchain](https://github.com/JetBrains/kotlin/blob/e8e8a26cd146109482c0de307b1830358b562a70/kotlin-native/build-tools/build.gradle.kts#L65)

**Comment by lwasyl** [comment]
> I randomly smash Java versions until I get my Kotlin code to compile. So far, the easiest one to do that was Java 8. For a couple of years now I feel that Java 11 is beggining to become easier. I didn't try much with 17.

Can you elaborate on some of the problems you're facing? I've been using JDK17 to build Kotlin projects with no issues whatsoever, and I'm very curious why code wouldn't even _compile_. On the contrary, I only had issues with using libraries/modules compiled with higher target than the Kotlin code.

> I think we should stick to Kotlin's default.

For target bytecode, for sure a default Kotlin target won't hurt :+1: 

> [Kotlin is also using JDK 8 as their toolchain](https://github.com/JetBrains/kotlin/blob/e8e8a26cd146109482c0de307b1830358b562a70/kotlin-native/build-tools/build.gradle.kts#L65)

I wouldn't go as far as seeing this as endorsement or recommendation to use JDK8 when building Kotlin projects — Kotlin does support new JDKs and has explicit APIs to set target bytecode level. It might as well be that updating such a big project as Kotlin simply takes time.

I'll step out of the discussion as I'm not a maintainer here and as a library consumer any decision will not affect me. I'll just reiterate that with the available tooling, there is no reason whatsoever to use old JDKs to build the project:
 - set the toolchains to highest working JDK/highest LTS release to be conservative. This way you'll benefit from years of improvements in the JDK
 - set the target java version to lowest supported JDK, so either 8 or 11, to not force consumers to use newer JDKs. This will also make sure you're not using unsupported APIs
 - set up CI to execute tests using JDKs you want to support, which should be free given the project is open-source. This will make sure the previous steps work as expected and consumers on JDK 8 can use the library, without locking yourselves to JDK8 tooling

If the last steps fails, then it should either mean you found a bug in JDK or in Kotlin compiler, I hope that both are at this point not very likely :crossed_fingers:

**Comment by LeoColman** [comment]
> Can you elaborate on some of the problems you're facing? I've been using JDK17 to build Kotlin projects with no issues whatsoever, and I'm very curious why code wouldn't even compile. On the contrary, I only had issues with using libraries/modules compiled with higher target than the Kotlin code.

Usually when my PC has more than one Java version things get messy. Gradle chooses one JDK, IntelliJ chooses another and my terminal is set to a third one. After fixing and syncing these versions the experience is smooth. However, I've ran into this issue with way too many projects and on more than one computer to dis-consider the possible impact to future contributors

**Comment by sksamuel** [comment]
Yeah I agree with the theory. Set build jvm highest you can, set the release version lowest you want to support.
But we just run into problems in practice, and I'm tired of constantly battling the bugs in gradle and kotlin multiplatform.
Latest issue:
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option
JVM 1.8 isn't even specified anywhere.

**Comment by sksamuel** [comment]
I finally have this working reliably, by removing the toolchain. More buggy gradle stuff I guess.
Going to close this.
