### ISSUE TITLE
Pleasant mechanism for ignoring/skipping a test from within the test code.

### ISSUE THREAD

**Issue by tonicsoft** [kotest/kotest#3582]
Kotest provides this feature already:

```kotlin
val disableDangerOnFridays: EnabledIf = { !(it.name.startsWith("danger") && isFriday()) }

"danger Will Robinson".config(enabledIf = disableDangerOnFridays) {
  // test here
}

"safe Will Robinson".config(enabledIf = disableDangerOnFridays) {
 // test here
}
```

However, I personally find the syntax quite cumbersome compared to one of the ways that Junit has achieved the same thing with their concept of "assumtions":

```kotlin
@Test
fun dangerWillRobinson() {
    assumeTrue(isFriday())

    // test here
}
```

Not that in the junit case, the assumption can be added or removed by adding/deleting a line with no additional formatting changes or line breaks/joins required, where as the kotest version requires the insertion of the `config` function in the chain. Depending on the length of your test name this will also require a bit of formatting and is generally a bit of a pain (I've assumed that 99.9% of tests are not using the `config` function already and it has to be added just to use `enabledIf`).

Furthermore, the machanism that makes the Junit version work is by throwing a special exception called `TestAbortedException` I think. This makes it very extensible since it's just plain old code, nothing fancy like annotations that have to be processed later. There is no obvious way to extend the kotest version to develop a custom DSL for conditional test execution.

Note that `Tag`s suffer from a similar syntax issue. In order to add tags to a test the syntax is also a bit cumbersome.

```kotlin
"danger Will Robinson".config(tags = setOf(Tag1, Tag2)) {
  // test here
}
```

However, that's beside the point of this feature request.

It would be nice to have a way to dynamically skip/ignore tests by pasting a single line of code, on a new line with no other formating changes required. Junit's mechanism via a special exception has always worked well for me in the past but perhaps there are other ways that the config syntax can be improved. For example by bypassing the `config` function:

```kotlin
"danger Will Robinson"
    .enabledIf(disableDangerOnFridays))
    .tags(Tag1, Tag2) {
  // test here
}
```

or (using BehaviorSpec as example this time):

```kotlin
then("name").config(enabledIf = foo, tags = bar) {
}
//becomes
then(
    "name",
    enabledIf = foo,
    tags = bar
) {
}
```

I appreciate this might be a case of personal preference and you have to be opinionated about your API and can't please everyone so thanks for your time in reading this if you got this far.

**Comment by Kantis** [comment]
https://github.com/kotest/kotest/pull/3587 should make it possible to use `TestAbortedException`, as long as you're writing JVM tests.

I also think it could be neat with some option to write assumptions within a test like you mentIoned. I'm not sure it needs to be via the config syntax. For instance, when writing a test to delete a user, we might want to run some code that creates the user. If that fails, we probably have some other tests that are failing, so we want our delete test to just pass.

```kotlin
class UserTests : FreeSpec({
  "Creating a user works" {
    createUser().shouldBeSuccess()
  }

  "Deleting a user works" {
    val user = assume { createUser() } // failure here flags test as skipped
    deleteUser(user).shouldBeSuccess()
  }
})
```

We could add our own exception which the engine recognises to implement this. I'm not sure if we have any other good ways to do this. A test currently always just returns `Unit`, and the absence of exceptions is interpreted as a successful test.

**Comment by tonicsoft** [comment]
Thanks for this. If I read the code in your PR correctly, `TestAbortedException` was actually intended to be handled already and this is more like a bug report than a new feature request?

**Comment by Kantis** [comment]
You could say that, at least for JVM targets. I think providing a convenient API for aborting/skipping a test which is multiplatform compatible is a valid enhancement though.

**Comment by sksamuel** [comment]
@tonicsoft See my PR for proposed feature.
