### ISSUE TITLE
Improve documentations on beforeEach, beforeAny and beforeTest

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#3594]
Ref: https://app.slack.com/client/T09229ZC6/CT0G9SD7Z/thread/CT0G9SD7Z-1690386549.761999 

What's the difference between beforeTest, beforeEach and beforeAny? I've read the documentation but I'm still confused.

https://kotest.io/docs/framework/lifecycle-hooks.html

---

I think I figured it out - correct me if I'm wrong. beforeTest has the same usage as beforeAny and is invoked at the start of both a container and a test, whereas beforeEach is invoked only before a test. To illustrate:

```
class MyTest : FreeSpec({
    "container1" - {
        "test1" {
            println("test1")
        }
    }

    beforeAny { println("beforeAny $it") }
    beforeEach { println("beforeEach $it") }
})
```

In the above, the beforeAny (or beforeTest) is invoked twice: once for the container and once again for the test. On the other hand, beforeEach is invoked only once, for the test.

---

We should improve the documentation to make the differences between lifecycle hooks more explicit and less dependent on experimenting

**Comment by pientaa** [comment]
@LeoColman take a look at #3698 please. If you think it should be fixed in already released versions of documentation, I can apply it there, too. Also, if you don't like the way I fixed it, share your suggestions, please

**Comment by reevn** [comment]
Hey everyone 👋. I just saw this in the changelog and was a bit confused at the added documentation. For reference, here's the [original PR](https://github.com/kotest/kotest/pull/1589) that added `beforeContainer`, `beforeEach`, and `beforeAny` (`beforeTest` already existed, but we chose to completely replace it with `beforeAny` to bring more consistency to it. There's not really a good reason why it shouldn't be deprecated).

In #3698, the following two additional sections were added to the documentation:

1:
```
To understand all callbacks correctly
it's important to have a good understanding of
possible `TestType` values:

- `Container` - a container that can contain other tests,
- `Test` - a leaf test that cannot contain nested tests,
- `Dynamic` - can either be a container or a test
and is used when tests are added dynamically
via functionality such as property tests or data tests.
```

2:
```
Notice that as far as `beforeAny` and `beforeTest` are just another name for the same functionality,
`beforeEach` is different. Each of `beforeAny` and `beforeTest` will be invoked before any `TestType.Test`,
whereas `beforeEach` will be invoked before both `TestType.Container` and `TestType.Test`.
The same applies to `afterAny`, `afterTest` and `afterEach`.
```

There's a problem in the 2nd section: The second sentence should be the other way around: `beforeAny` is called for both `TestType.Container` and `TestType.Test`, while `beforeEach` is only called for `TestType.Test`.

Additionally, the first sentence is already present directly on the original documentation for `beforeTest`:

```
|beforeTest| <SNIP> <br/><br/>This callback has the same behavior as `beforeAny`.|
```

The same goes for the whole added section actually. The functionality is already described directly on each callback documentation:

```
|beforeContainer|Invoked directly before each test with type `TestType.Container` is executed

|beforeEach|Invoked directly before each test with type `TestType.Test` is executed

beforeAny|Invoked directly before each test with any `TestType` is executed
```

While the new section that explains what `TestType`s there are is a good idea imo, but to me it looks like the second section just repeats what is already in the documentation in a currently incorrect way. If there is some information missing in the documentation for each callback, I think it would be a better idea to extend the docs exactly in the relevant parts.

Any thoughts? @LeoColman @pientaa
