### ISSUE TITLE
Arb.list<T> taking a Gen<Int> which determines it's size, and Gen<T> for elements

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3595]
Currently we need to determine the size of the list up front

```kotlin
Arb.list(Arb.item(), 0..20)
```

But suppose that we have some more complex requirement on the size of the list, tying the size to other properties. In these cases it might be nice to be able to do:

```kotlin
Arb.list(Arb.item(), Arb.numberOfItems())
```

**Comment by Kantis** [comment]
WDYT @myuwono, is this something you would solve in some other way?

**Comment by myuwono** [comment]
Yeah this is nice @Kantis !! 🙌 

Usually I see devs solve this with the `arbitrary { }` builder e.g.

```kotlin
val arbFooList: Arb<List<Foo>> = arbitrary {
  val lowerBound = Arb.int(0..5).bind()
  val upperBound = Arb.int(lowerBound..50).bind()
  Arb.list(arbFoo, lowerBound.. upperBound).bind()
}
```

It's always good to have the other option using arb.

**Comment by lexa-diky** [comment]
Possible implementation: https://github.com/kotest/kotest/pull/3618. 
If you are ok with it, I'l add tests and proper documentation
