### ISSUE TITLE
Support wasm target

### ISSUE THREAD

**Issue by vdshb** [kotest/kotest#3598]
WASM is a new experimental target from JetBrains from 1.8.20. They a planning to move from JS to WASM eventually. 

The support would be especially beneficial for library authors whoes common tests are depending on kotest, but who want to support the new platform. 

I, myself, primarily interested in support for kotest-assertions.

**Comment by sksamuel** [comment]
I've played about with adding this but we are blocked on https://github.com/Kotlin/kotlinx.coroutines/issues/3713

**Comment by eygraber** [comment]
Should be coming soon with https://github.com/Kotlin/kotlinx.coroutines/pull/3849

The other kotlinx libraries are being released with wasm support!

**Comment by vdshb** [comment]
@sksamuel I suppose coroutines 1.8.0  release is solving most blockers

**Comment by Nek-12** [comment]
Hello, any progress on this?

**Comment by OliverO2** [comment]
I'm on it as we speak.

**Comment by vdshb** [comment]
As I can see it is not in the latest release. Is it possible to make a release with WASM target included? Any timeline?

**Comment by OliverO2** [comment]
Did you consider trying a [snapshot release](https://kotest.io/docs/quickstart#snapshots)?

**Comment by vdshb** [comment]
Didn't know about it. Thanks for mention.

**Comment by OliverO2** [comment]
@vdshb Happy to help.

If you try the Wasm target from a snapshot, I'd appreciate it if you'd file an issue in case of problems, or post positive experiences here.
