### ISSUE TITLE
Arb.stringPattern generates incorrect examples OR the docs are wrong and Generex isn't used anymore

### ISSUE THREAD

**Issue by Spirarel** [kotest/kotest#3607]
**Which version of Kotest are you using**
5.6.2

Code to reproduce:
```kotlin
class StringPatternExample : FreeSpec({
    val regexPattern = """^[A-Za-z]+[\h\-_–—:]\d+"""
    fun regexGen() = Arb.stringPattern(regexPattern)

    "Arb.stringPattern generates invalid regex" {
        checkAll(regexGen()) {
            it shouldMatch regexPattern
        }
    }
})
```
Example output
<img width="1062" alt="Screenshot 2023-08-03 at 9 36 30 AM" src="https://github.com/kotest/kotest/assets/10119394/a977f0a0-474b-4795-8786-7dbca001223d">

## Thoughts
Clearly `\h` is not being handled correctly. Digging into the source, it looks like there's been an undocumented move away from generex to RgxGen which doesn't support the, expected, Java Regex tokens.

**Comment by sksamuel** [comment]
Yep, generex hasn't been updated since 2017, so we moved to RgxGen. I've updated the docs, thanks for spotting it.
