### ISSUE TITLE
Data-Driven Testing with Concurrent Execution

### ISSUE THREAD

**Issue by PabloLec** [kotest/kotest#3608]
Hello,

I'm opening this issue primarily to pose a question, but it could potentially evolve into a feature request if the behavior is not natively available. 
I have a Spec that takes a significant amount of time to execute, most of which is spent in eventually blocks waiting for API responses. I'd like to set up this spec in a data-driven testing fashion, similar to what can be found in the documentation:

```
withData(
    PythagTriple(3, 4, 5),
    PythagTriple(6, 8, 10),
    PythagTriple(8, 15, 17),
    PythagTriple(7, 24, 25)
  ) { (a, b, c) ->
    isPythagTriple(a, b, c) shouldBe true
  }
```

Firstly, I don't believe it's possible to instantiate Specs inside a withData.
I could trigger the logic of my Spec via a function to use it within withData, but in that case, I wouldn't be able to take advantage of concurrency.
I could manually set a number of threads for execution, but this would conflict with the global concurrency management, which is not what I'm looking for.

Specifically, I would like to know if it's natively possible to take advantage of Kotest's concurrency in data-driven tests? I want to be able to use withData without having to create as many Specs as I have data to test.
Or alternatively, do you see a way to achieve parallel execution with concurrency management with withData, in the same way as with multiple Specs?

**Comment by sksamuel** [comment]
You can activate per test concurrency, which will work if your data tests are top level (not nested inside other contexts).

**Comment by sksamuel** [comment]
Here is a working example:

```
class ParallelDataTest : FunSpec() {

   private fun isPythagTriple(a: Int, b: Int, c: Int): Boolean = a * a + b * b == c * c

   override fun concurrency(): Int = 4

   init {

      withData(
         PythagTriple(3, 4, 5),
         PythagTriple(6, 8, 10),
         PythagTriple(8, 15, 17),
         PythagTriple(7, 24, 25),
      ) { (a, b, c) ->
         delay(1000)
         isPythagTriple(a, b, c) shouldBe true
      }
   }
}
```
