### ISSUE TITLE
BlockHound extension documentation went missing

### ISSUE THREAD

**Issue by OliverO2** [kotest/kotest#3609]
It got removed from `documentation/sidebars.js` in commit cefaabb026928adfb7bfbb70c767659876796e2b.

**Comment by LeoColman** [comment]
It was removed accidentally 🤦🏻 
Thanks for the heads-up! I'll fix it :)

**Comment by LeoColman** [comment]
Fixed in 45df9ae04e0d3077c3732d8c7ed6947eeae24d7f

**Comment by OliverO2** [comment]
Cool. Thanks! :)
