### ISSUE TITLE
Property testing seed is missing on reports.

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [kotest/kotest#3612]
Kotest 5.6.2 on a KMP project which supports all targets by Kotlin 1.9.0, except the deprecated ones.

I am not sure if this problem exist on JVM projects too, as I haven't tried there.

Expected to be there on the file and if possible show it on the cli logs.

**Comment by sksamuel** [comment]
Do you mean in the gradle ouptut or in the junit xml reports?

**Comment by sksamuel** [comment]
@JavierSegoviaCordoba

**Comment by JavierSegoviaCordoba** [comment]
I think it was in Gradle outputs

**Comment by sksamuel** [comment]
Fixed in 6.0 permutation tests.
