### ISSUE TITLE
Nested tags not working with Behavior style

### ISSUE THREAD

**Issue by Chrylo** [kotest/kotest#3616]
**Which version of Kotest are you using**
5.6.2
Android Studio Giraffe

The following tag definition does not seem to work. The tags are completely ignored:

```
val Integration = NamedTag("Integration")
val XTag = NamedTag("X")
val YTag = NamedTag("Y")

class Test : BehaviorSpec({
    tags(Integration) // Works

    given("A Test") {
         `when`("trying to to do") {
               and("X") {
                    tags(DoXTag) // Does not work

                    then("It should return not null") {
                        Assertions.assertNotNull(x)
                    }
                }

                and("Y ") {
                    tags(DoYTag) // Does not work

                    then("It should return not null").config(tags = setOf(Y)) { // Does not work
                        Assertions.assertNotNull(y)
                    }
                }
             }
        }
```

`./gradlew test -Dkotest.tags="Integration & X"` // Does not work
`./gradlew test -Dkotest.tags="Integration"` // Works
`./gradlew test -Dkotest.tags="X"` // Does not work
`./gradlew test -Dkotest.tags="Y"` // Does not work

Since the Integration Tag is working I expect that the forwarding of the systemProperties works correctly:
```
Project.gradle.kts

subprojects {
    tasks.withType<Test> {
        val systemPropertiesMap = HashMap<String, Any>()
        System.getProperties().forEach { key, value ->
            systemPropertiesMap[key.toString()] = value.toString()
        }
        systemProperties = systemPropertiesMap
    }
}
```

**Comment by Chrylo** [comment]
I tried to follow this documentation: https://kotest.io/docs/framework/tags.html

**Comment by suside** [comment]
They does not work on 5.7.2 with Describe style either:
```kt
object ExampleSpec : DescribeSpec({
  describe("test") {
    it("should pass").config(tags = setOf(NamedTag("example"))) {
      println("Hello, world!")
    }
    it("should fail") {
      throw Exception("This test failed!")
    }
  }
})
```
and ` ./gradlew test -Dkotest.tags="example"` fails on second test

**Comment by sksamuel** [comment]
This is actually as expected.
The nested tests are not evaluated until the outer tests are executed, so it can't know what tags are being registered later. That exists in case you want to exclude child tests.

So in the first example, `given("A Test")` only has the tag `Integration` and thus is not executed when you ask for `Integration & X`.

Open to suggestions on how to clarify this.

**Comment by sksamuel** [comment]
Closing as expected behavior.
