### ISSUE TITLE
`Arb.offsetDateTime` (Ideally) Should Be Based On `Instant`

### ISSUE THREAD

**Issue by akefirad** [kotest/kotest#3617]
Looking at the implementation
```kotlin
fun Arb.Companion.offsetDateTime(
   minValue: LocalDateTime = LocalDateTime.MIN,
   maxValue: LocalDateTime = LocalDateTime.MAX,
   zoneOffset: Arb<ZoneOffset> = zoneOffset()
): Arb<OffsetDateTime> = Arb.bind(
   localDateTime(minValue, maxValue),
   zoneOffset
) { time, offset -> time.atOffset(offset) }
```
it seems more useful if the method accepts `min` and `max` as `Instant` and not `LocalDateTime`. The reason (at least in our case) is that when we're working with `OffsetDateTime` values, (often) we're interested in the moment in time (which cannot be represented by types like `LocalDateTime`) and the above implementation makes it hard to use the method. An example would be all "give me a stream of `OffsetDateTime` values in future". For that reason we had to write our own version of the above method:
```kotlin
fun offsetDateTime(
  minValue: Instant = Instant.MIN,
  maxValue: Instant = Instant.MAX
  zoneOffset: Arb<ZoneOffset> = zoneOffset()
): Arb<OffsetDateTime> = Arb.bind(
  instant(minValue, maxValue),
  zoneOffset,
) { t, o -> t.atOffset(o) }
```

**Comment by sksamuel** [comment]
Fixed in 5.7
