### ISSUE TITLE
Running kotest standalone from inside Spring Boot application fails to find specs

### ISSUE THREAD

**Issue by cloudshiftchris** [kotest/kotest#3631]
Kotest 5.6.2

Packaging up a set of e2e tests inside a Spring Boot app, which is deployed/executed as a JAR file.  The nature of Spring Boot bundling is to have a launcher and a specific JAR layout that includes classes, libs etc.

When run from IDE (not packaged into a JAR) Kotest locates test specs; when executed from the jar (`java -jar MyJar.jar`) kotest does not find any specs.

Kotest is launched via `io.kotest.engine.launcher.main(kotestArgs)`

Tracked the problem down to class path scanning that excludes nested JARs (`disableNestedJarScanning`):

```
ClassGraph()
         .enableClassInfo()
         .enableExternalClasses()
         .ignoreClassVisibility()
         .disableNestedJarScanning()
```

Stub code to reproduce that (below) finds specs in the JAR:

```
        val specs = ClassGraph()
            .enableClassInfo()
            .enableExternalClasses()
            .ignoreClassVisibility()
       //     .disableNestedJarScanning()
            .scan()
            .getSubclasses(Spec::class.java.name)
            .map { Class.forName(it.name).kotlin }
            .filterIsInstance<KClass<out Spec>>()
```

Any specific reason why nested JARs are not scanned?  Any option to enable this?

**Comment by cloudshiftchris** [comment]
The contents of a Spring Boot jar are laid out as below.

<img width="310" alt="image" src="https://github.com/kotest/kotest/assets/75175039/37a84020-88b1-4223-8dff-9b86b2ac2185">

**Comment by sksamuel** [comment]
Can certainly add an option, I've never seen tests run from a jar before.
