### ISSUE TITLE
Timeout's no longer being applied

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3672]
See https://github.com/oss-review-toolkit/ort/blob/5bd616f052557f20280c3c758dd5acb889f8aba2/plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt#L567-L580

@OliverO2 I wonder if this is related to the thread changes ?

**Comment by sksamuel** [comment]
@sschuberth

**Comment by OliverO2** [comment]
I'm unfamiliar with that toolkit. Could you give me a tl;dr on what it does in this case and what went wrong?

**Comment by sschuberth** [comment]
@OliverO2, no need to be familiar with OSS Review Toolkit specifics, I guess. All I can say right now is that in the [PR that upgrades Kotest from 5.6.2 to 5.7.0](https://github.com/oss-review-toolkit/ort/pull/7443), we start to see [java.lang.AssertionError: Expected exception kotlinx.coroutines.TimeoutCancellationException but no exception was thrown.](https://github.com/oss-review-toolkit/ort/actions/runs/6054838796/job/16436599586?pr=7443#step:4:6611).

**Comment by OliverO2** [comment]
Is there a small reproducer I could try?

**Comment by sschuberth** [comment]
> Is there a small reproducer I could try?

Not from my side, but @sksamuel mentioned [he noticed this himself](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1693669505934769?thread_ts=1693603681.032919&cid=CT0G9SD7Z), so he might have.

**Comment by sschuberth** [comment]
@OliverO2, this seem to do:

            shouldThrow<TimeoutCancellationException> {
                withTimeout(1000) {
                    Thread.sleep(5000)
                }
            }

`Expected exception kotlinx.coroutines.TimeoutCancellationException but no exception was thrown.`

**Comment by OliverO2** [comment]
I'll try.

**Comment by sksamuel** [comment]
I think you'll need blockingTest = true if you're using thread.sleep.
That's always been the case.

Doesn't explain why your test is now failing in your project through.

**Comment by OliverO2** [comment]
> I think you'll need blockingTest = true if you're using thread.sleep.

Thought so, too.

**Comment by OliverO2** [comment]
There is no `TimeoutCancellationException` unless the coroutine inside `withTimeout` contains at least one suspension point.

This works:
```kotlin
         shouldThrow<TimeoutCancellationException> {
            withTimeout(1000) {
               Thread.sleep(5000)
               delay(1)
            }
         }
```

`withTimeout`'s description says
> Implementation note: how the time is tracked exactly is an implementation detail of the context's CoroutineDispatcher.

So one suspect would be a change in the type of `Executor` used. Needs further investigation.

**Comment by OliverO2** [comment]
Tried a standalone experiment outside Kotest: Same result. kotlinx.coroutines will not detect the timeout without a suspension point.

```kotlin
import kotlinx.coroutines.* // ktlint-disable no-wildcard-imports

fun main(): Unit = runBlocking {
    withContext(Dispatchers.IO) {
        try {
            withTimeout(1000) {
                Thread.sleep(5000)
                // delay(1)
            }
            println("no timeout detected")
        } catch (t: Throwable) {
            t.printStackTrace()
        }
    }
}
```

**Comment by OliverO2** [comment]
Additional information for reference:

1. If `withTimeout` is used on a blocking or CPU-bound coroutine without suspension points, such a coroutine will not be interrupted. (Canceling is always cooperative and requires a suspension point.)

    For example, this code will always run for two seconds:

    ```kotlin
    withTimeout(1000) {
        launch {
            Thread.sleep(2000)
        }
    }
    ```

2. In order to time-limit a blocking test with Kotest, you can configure the `blockingTest` and `timeout` parameters. Kotest will then run the test on a dedicated thread and will forcefully shut down such thread when the configured `timeout` expires.

3. My recommendation would be to avoid mixing thread management with coroutines like so:
    * Launch blocking coroutines on `Dispatchers.IO` or `Dispatchers.IO.limitedParallelism()` – even in tests.
    * Wait for their results asynchronously in (other) non-blocking coroutines, which respond to cancellation, including `withTimeout`.
    * Consider using the [Dispatcher views API](https://blog.jetbrains.com/kotlin/2021/12/introducing-kotlinx-coroutines-1-6-0/#dispatcher-views-api).
