### ISSUE TITLE
Running a single test with a `JSONObject` in an Android module throws a `Stub!` error

### ISSUE THREAD

**Issue by steliosfran** [kotest/kotest#3677]
Tried with both Kotest 5.6.2 and 5.7.1

Considering the following spec on an Android project:
```Kotlin
package com.example

import io.kotest.core.spec.style.BehaviorSpec
import org.json.JSONObject

class SampleTest : BehaviorSpec() {
    init {
        Given("A") {

            Then("B") {
                JSONObject()
            }
        }
    }
}
```

Running the whole suite works.

Running just the Given or the Then fails with the following error:
```Kotlin
Stub!
java.lang.RuntimeException: Stub!
	at org.json.JSONObject.<init>(JSONObject.java:81)
	at com.example.SampleTest$1$1.invokeSuspend
```

After some investigation, I think I may have found the cause, although I still don't know why it's happening only when running a single test.

The `Stub!` error message indicates that it's trying to run the `JSONObject.class` of the Android SDK, not the Java's JSON library ([link](https://mvnrepository.com/artifact/org.json/json)) which we are importing in tests.

My guess is that this happens because both classes have the same package name `org.json` which creates this conflict. Additionally, the issue only happens if this test is on an Android module. In a Java/Kotlin module, this individual test will run properly since there isn't any conflict with the `JSONObject` of the Android SDK.

However the question still remains, how can it run the whole suite but not the individual test?

**Comment by LeoColman** [comment]
Unfortunately we have no official support on Android.
I'd recommend asking a question on StackOverflow or coming to our slack and see if someone has the knowledge to help you!
