### ISSUE TITLE
Cannot get rid of warning "Kotest autoscan is enabled"

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#3680]
**Which version of Kotest are you using**
5.7.1

Upgrading to 5.7 from 5.6 gave me this new warning. Well, I hate it to have to turn OFF features I do not want or use - why is this not the other way around?

All of the documentation regarding this auto scan is misleading as it is completely unclear where and how to set the properties to disable this behaviour.

Because I use Gradle AND IntelliJ Plugin, I though a `kotest.properties` file is the way to go - so I added that file. But: where should the file be located? This is not documented at all. So, I tried on project root, next to my build.gradle.kts and then I also tried resources folder (under src/test). With no luck. The warning remains, the feature seems to be enabled.

Please document WHERE to put that file so it is seen. Thanks!

**Comment by Zordid** [comment]
So, it needs to be in src/main/resources ... this info would be helpful

**Comment by sksamuel** [comment]
5.7.2 removes this warning also @Zordid

**Comment by sksamuel** [comment]
I've clarified docs.
