### ISSUE TITLE
Maven central has version 5.7.2, but kotest releases/docs have only 5.7.1

### ISSUE THREAD

**Issue by jsyrjala** [kotest/kotest#3682]
Maven Central has version [5.7.2](https://search.maven.org/artifact/io.kotest/kotest-bom/5.7.2/pom) available since 2023-09-05.

But [releases page](https://github.com/kotest/kotest/releases) currently has 5.7.1. Likewise [the changelog](https://kotest.io/docs/changelog.html) has only 5.7.1.

Just wandering if 5.7.2 is a valid release?

**Comment by sksamuel** [comment]
Thanks for pointing that out. I've updated the changelog.
