### ISSUE TITLE
differences in large maps aren't printed out

### ISSUE THREAD

**Issue by hughlunnon** [kotest/kotest#3683]
**latest**

if you use kotest to compare large maps, it will correctly error when they aren't the same, but not print out (in a nice way) what the difference is. This is due to the limtis set in MapEqKt - eg

```
private fun print(map: Map<*, *>?): Printed {
   if (map == null) return null.print()
   if (map.isEmpty()) return Printed("{}")
   val indentation = "  "
   val newLine = "\n"
   return Printed(map.toList()
      .joinToString(
         separator = ",$newLine",
         prefix = "{$newLine",
         postfix = "$newLine}",
         limit = 10
      ) { "$indentation${it.first.print().value} = ${it.second.print().value}" }
   )
}
```

changing the limit of 10, either removing it, setting it very high, or allowing it to be configurable would massively improve the devex. 

I'm happy to raise a PR with any of these solutions, would like suggestions on which is preferably by the project team first

**Comment by sksamuel** [comment]
If we want to make it configurable that would work (by system property) or global var.
I don't think we should change the default of 10 as it will change for everyone.

**Comment by hughlunnon** [comment]
I'd normally agree with not changing default framework behaviour, but is there any reason that someone would not want all not-matching conditions to be logged?

**Comment by sksamuel** [comment]
If you have 20000000 of them or something.
I guess we could increase the limit a bit too.
But ultimately should be configurable.

**Comment by sksamuel** [comment]
5.8.1 will bump to 100 and add a configuration value for any limit you want.
