### ISSUE TITLE
Add context container to BehaviorSpec

### ISSUE THREAD

**Issue by jcthenerd** [kotest/kotest#3685]
Something that other BDD frameworks have that helps with readability of tests is a way to add a context for a group of tests. It would be nice to bring this into the BehaviorSpec by including a `Context` container as a root level above `Given`. This could provide a concise summary of what the test is doing before dropping into the specifics in the various Given, When, and Then containers. Something like:
```Kotlin
Context("testing filters in the remove expected items") {
  Given("valid item") {
    And("invalid item") {
      When("filter is called") {
        Then("Only valid should be present") {
        }
      }
    }
  }
}
```

**Comment by jcthenerd** [comment]
I am willing to make the PR to add this as well.

**Comment by sksamuel** [comment]
Is this used in other BDD frameworks?
I am happy if you want to raise a PR. We would need to add the logic to the intellij plugin too (copy n paste).

**Comment by jcthenerd** [comment]
Yes, in Spock this is added by using a string for the function name and in cucumber they have a `scenario` that wraps the rest of the behavior test.

**Comment by jcthenerd** [comment]
Corresponding PR to add this to kotest https://github.com/kotest/kotest/pull/3737.
