### ISSUE TITLE
How to run tests in transaction while testing SpringBoot apps?

### ISSUE THREAD

**Issue by bvn13** [kotest/kotest#3686]
What is the approach to run kotest tests inside a transaction while testing SpringBoot app?
Being used JUnit I just put `@Transactional` on test class - that did things done. But not using kotest.

**Comment by sksamuel** [comment]
Did you install the spring extension? @bvn13

**Comment by bvn13** [comment]
Hm... we don't.
Will it be enough?
```
@ExtendWith(SpringExtension::class)
```

**Comment by sksamuel** [comment]
Yes that would be enough. Can you confirm? Please re-open if you continue to have issues.
