### ISSUE TITLE
Custom nameFn for FreeSpec Segfaults on iOS Target

### ISSUE THREAD

**Issue by JesusMcCloud** [kotest/kotest#3687]
**Which version of Kotest are you using**
Kotest 5.6, Kotest 5.7

We ran into [issues with long file names resulting from a FreeSpec](https://github.com/a-sit-plus/kmm-vc-library/actions/runs/6048016515/job/16412582541). In trying to work around it, we introduced s custom `nameFn`. [Now the build process segfaults](https://github.com/a-sit-plus/kmm-vc-library/actions/runs/6076389986/job/16484305024).

Our code is [open source](https://github.com/a-sit-plus/kmm-vc-library) so it can be directly investigated (clone recursively!). Nevertheless, I am of course happy to gather and provide any information here to help identifying and fixing the underlying cause of this issue.

Whatever we can do ourselves to narrow down and/or fix this issue, we are happy to do!

**Comment by sksamuel** [comment]
I'm not sure how much I can help, as I don't have a mac.
So, is it this test that fails?
https://github.com/a-sit-plus/kmm-vc-library/blob/223c2fdb358dc2fae1f856c3ab97d90750c865ad/vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopIsoProtocolTest.kt#L22
If so, where are you using withData ?

**Comment by JesusMcCloud** [comment]
You are right! I was sloppy looking at the reason for the failure. Sorry!

It is segfaulting somewhere else. I'm closing this issue and we'll investigate internally.
