### ISSUE TITLE
Comparing lists of data classes in more detail

### ISSUE THREAD

**Issue by AlexCue987** [kotest/kotest#3688]
when every element of a list has many fields, figuring out what exactly is different is time-consuming and error-prone. I have code that makes it easier and faster. For instance, in the following example element [0, 1, 2] in expected match elements [1, 2, 3] in actual, and the mismatched elements in actual have very similar ones in expected:

```Mismatch:
actual[0] = SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123457)

Match:
expected[0] == actual[1]: SpaceShip(name=Millennium Falcon, description=Han Solo's ship, range=10, capacity=10, serialNumber=123456)
expected[1] == actual[2]: SpaceShip(name=Ghost, description=seen in Rogue One, range=10, capacity=10, serialNumber=Unknown)
expected[2] == actual[3]: SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123456)

Mismatch:
expected[3] = SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123356)
actual[4] = SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123457)

Possible matches:

actual[0] = SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123457) 
is similar to
expected[2] = SpaceShip(name=CR90 corvette, description=Blockade Runner, range=10, capacity=10, serialNumber=123456)

"name" = CR90 corvette
"description" = Blockade Runner
"range" = 10
"capacity" = 10
"serialNumber" expected: 123456,
 but was: 123457
```

would it make sense to add this matching to kotest?

**Comment by LeoColman** [comment]
I believe this would be valuable, yes.
Even if we have to add a lot more test cases, having a clear vision of assertion failures is great!

My only concern is if adding this kind of matching may break how IDEs display AssertionErrors. Other than that, I'd say go for it! :D

**Comment by AlexCue987** [comment]
> I believe this would be valuable, yes. Even if we have to add a lot more test cases, having a clear vision of assertion failures is great!
> 
> My only concern is if adding this kind of matching may break how IDEs display AssertionErrors. Other than that, I'd say go for it! :D

This is a very interesting point about different IDEs. I'm only using my matcher in Intellij, which displays mismatches in red, just like all the output from any Kotest matchers. But we should be able to solve this problem when/if it arises.

Can you assign me to this issue?

**Comment by sksamuel** [comment]
Asigned

**Comment by AlexCue987** [comment]
https://github.com/kotest/kotest/pull/3796

**Comment by sksamuel** [comment]
@AlexCue987 this was completed in https://github.com/kotest/kotest/pull/4235 ?

**Comment by AlexCue987** [comment]
yes
