### ISSUE TITLE
Conflict between the Kotest plugin and the ability to create new test classes in a java project.

### ISSUE THREAD

**Issue by thxwelchs** [kotest/kotest#3689]
Hi I tried the function of creating a new test class with the Kotest plugin enabled, but it doesn't work properly.

Please check if this is a bug.

IntelliJ IDEA 2023.2 (Ultimate Edition)

Build #IU-232.8660.185, built on July 26, 2023

Kotest Plugin: 1.3.69-IC-232-EAP-SNAPSHOT

https://youtrack.jetbrains.com/issue/IDEA-331585

**Comment by sksamuel** [comment]
I am able to create a class:

```class Wibble {}```

Then using the shortcut I can create both a Kotest test and a unit test.
I am using intellij IntelliJ IDEA 2022.3.3 (Ultimate Edition).

Can I get a walk through or video of exactly the steps you are taking and is it junit or kotest or both tests that cannot be created ?

**Comment by thxwelchs** [comment]
Maybe this is a conflict with another plugin, but I have a video for you.

![Sep-19-2023 13-35-11](https://github.com/kotest/kotest/assets/38197077/d533d7e5-60cc-4752-ac6a-e51f384e71da)

![Sep-19-2023 13-31-44](https://github.com/kotest/kotest/assets/38197077/5011e8b4-7296-4202-95db-e4ee1d0eb323)

**Comment by thxwelchs** [comment]
@sksamuel

**Comment by thxwelchs** [comment]
I think only JUnit Test

**Comment by sksamuel** [comment]
Thanks for the video @thxwelchs

**Comment by kshired** [comment]
@sksamuel 
I have a same issue at 2023.2.4

**Comment by sksamuel** [comment]
I am still unable to duplicate this. I have tried a java file, a kotlin file, creating for both junit5 and kotest and it always works.

Can I get a sample project that you guys are using that you see the issue on ?

**Comment by sksamuel** [comment]
I think I can duplicate this now.

**Comment by sksamuel** [comment]
I have a fix going out. Once jetbrains approve it please let me know if its good for you all.

**Comment by sksamuel** [comment]
Latest plugin now available. Please reopen issue if still issues

**Comment by thxwelchs** [comment]
I also checked and I think this is fixed, thank you so much

Can you explain what the problem was?

**Comment by sksamuel** [comment]
There's a bug in intellij. I have filed a ticket
https://intellij-support.jetbrains.com/hc/en-us/community/posts/15040678418450-How-to-choose-when-to-apply-TestGenerator

In the meantime I hacked a workaround.
