### ISSUE TITLE
Update kotest-extensions-koin to koin 3.5.0

### ISSUE THREAD

**Issue by Slava-Miligoulo-Target** [kotest/kotest#3695]
When upgrading koin and troubleshooting we wanted to check if updating kotest-extensions-koin would help address https://github.com/InsertKoinIO/koin/issues/1656.  

The core issue looks to be related koin, but have the update to kotest-extensions-koin PR available.

PR - https://github.com/kotest/kotest-extensions-koin/pull/31

**Comment by sksamuel** [comment]
Ran PR but its failing. comment added on koin repo.

**Comment by Slava-Miligoulo-Target** [comment]
The issue may be related to build target (linxuArm64) missing?  It looks like the workflow changed between the release and now.

Last commit successful run (without linuxArm64) - https://github.com/kotest/kotest-extensions-koin/actions/runs/5988313995
Most commit recent run before my changes (throws missing linuxArm64 error)- https://github.com/kotest/kotest-extensions-koin/actions/runs/6043740172

Release workflows I don't think I saw linuxArm64. https://github.com/kotest/kotest-extensions-koin/actions/runs/6018082701/job/16325636200

If linuxArm64 is added to targets, it'd also be required to be added on the Koin side.

**Comment by sksamuel** [comment]
Koin extensions 1.3.0 is now released that works with Koin 3.5
