### ISSUE TITLE
MockServer extension fails on disabled tests

### ISSUE THREAD

**Issue by Burtan** [kotest/kotest#3697]
**Which version of Kotest are you using**
5.7.2

Hey, 
I just updated from 5.6.1 to 5.7.2 and I realized one of my disabled tests is failing. It is due to the mockserver-extension.
Have a look at this minimal example. Thanks!

https://github.com/Burtan/mock-server-fail

**Comment by sksamuel** [comment]
I've fixed the issue and released 1.3.0. of the mockserver extension.
I've confirmed it works against your repo.
