### ISSUE TITLE
Embedded Kafka archived

### ISSUE THREAD

**Issue by fletchgqc** [kotest/kotest#3701]
The Github embedded Kafka extension repository has been archived https://github.com/kotest/kotest-extensions-embedded-kafka. Why? Is it no longer developed, or has it moved? Please add an explanation to that page. I'm wondering whether to start using it and its archived status is rather disconcerting.

**Comment by OliverO2** [comment]
Done via https://github.com/kotest/kotest-extensions-embedded-kafka/commit/31a758677cd61ff6f2f5600f28c540bf8c0d688a
