### ISSUE TITLE
Matcher shouldBeSortedDescending variant

### ISSUE THREAD

**Issue by jool** [kotest/kotest#3704]
Hi,

I noticed there is a matcher `shouldBeSorted` which verifies that a collection is sorted in ascending order, but not a straight forward `shouldBeSortedDescending` equivalent.

There seems to exist two matchers for collections sorted in descending order:
* `shouldBeMonotonicallyDecreasing` - `listOf(10, 8, 8, 6).shouldBeMonotonicallyDecreasing()`
* `shouldBeStrictlyDecreasing` - `listOf(10, 8, 6).shouldBeStrictlyDecreasing()`

None of these are documented as far as I can tell and it is uncertain if they are officially supported. Are they?

`list.reverse().shouldBeSorted()` is a valid, supported alternative and perhaps adding a `shouldBeSortedDescending` and `shouldBeSortedDescendingBy`, `...` would be a bit bloaty?

**Comment by sksamuel** [comment]
They are both supported yes.

I think we could add shouldBeSortedDescending and shouldBeSortedDescendingBy even if they just delegate. There are a lot of matchers and we try to make finding the one you want easy.
