### ISSUE TITLE
LoadProjectConfigFromClassname does not support object based custom config

### ISSUE THREAD

**Issue by fvito** [kotest/kotest#3706]
Using kotest: 5.6.1

In my project, I have a custom config that extends `AbstractProjectConfig` as mentioned by the docs
Something like this
```
object KotestProjectConfig : AbstractProjectConfig() {
    override val isolationMode: IsolationMode
        get() = IsolationMode.InstancePerLeaf
}
```
I'm also disabling the autoscan for config file and using `kotest.framework.config.fqn=com.example.kotest.KotestProjectConfig
`  to specify the FQN of my kotest project config class

There seems to be an issue with the `loadProjectConfigFromClassname` as it fails to instantiate the object (I suspect its this [call](https://github.com/kotest/kotest/blob/2f38e9f3110e29d45131bd46e1c80ea4a02b916e/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/config/loadProjectConfigFromClassname.kt#L12))

The error I receive is this
```io.kotest.engine.config.LoadProjectConfigFromClassnameKt cannot access a member of class com.example.kotest.KotestProjectConfig```

I did however notice that the auto scan class (`applyConfigFromAutoScan`) calls a different method (`instantiateOrObject`) which, judging by name supports both class and object config files

In the meantime I've changed my config from object to class

Sorry if this has been reported already, my searching did not provide any existing issues about this

**Comment by sksamuel** [comment]
Thanks for bug report, will be fixed in the upcoming 5.7.3 release
