### ISSUE TITLE
Kotest starts contexts for each outer Spec scope and doesn't shut them down with IsolationMode.InstancePerTest causing leak

### ISSUE THREAD

**Issue by Spikhalskiy** [kotest/kotest#3711]
We are using Kotest 5.7.2 with Micronaut. Our tests leak threads and memory, not all application contexts created are getting closed. 

Our simple test looks the following way:

```
@MicronautTest
class SimpleTest @Inject constructor(
    private val application: EmbeddedApplication<*>,
) : BehaviorSpec({

    given("an instance of our application") {
        `when`("we check whether the app is running") {
            then("the app should be running") {
                application.isRunning.shouldBeTrue()
            }
        }
    }
})
```

Our project also has the following ProjectContext:

```
object ProjectConfig : AbstractProjectConfig() {
    override val isolationMode = IsolationMode.InstancePerTest

    override fun extensions() = listOf<Extension>(
        MicronautKotest5Extension,
    )
}
```

Our app has `ServerStartupEvent` and `ServerShutdownEvent` listeners.

For the simple test above, ServerStartupEvent listener will be called 3 times with 3 different contexts. Only one of them is getting stopped after (the last one). 

Here is a [log file](https://github.com/kotest/kotest/files/12741664/stacktraces.zip) that has the following structure:

```
ServerStartupEvent, identityHashCode of one of the beans: 133307322
<stacktrace> 
ServerStartupEvent, identityHashCode of one of the beans: 1323948792
<stacktrace>
ServerStartupEvent, identityHashCode of one of the beans: 128884134
<stacktrace>
ServerShutdownEvent, identityHashCode of one of the beans: 128884134
<stacktrace>
```

This log is produced by dumping stacktraces inside the startup and shutdown listener. It's clear that 3 different contexts are getting started for a single test and only one of them is getting shut down at the end.

## Behavior for other spec variations

```
@MicronautTest
class SimpleTest @Inject constructor(
    private val application: EmbeddedApplication<*>,
) : ShouldSpec({
    context("app") {
        should("be running") {
            application.isRunning.shouldBeTrue()
        }
    }
})
```

causes 2 contexts to be created and 1(the last one) to be shutdown

```
@MicronautTest
class SimpleTest @Inject constructor(
    private val application: EmbeddedApplication<*>,
) : ShouldSpec({
   should("app be running") {
       application.isRunning.shouldBeTrue()
   }
})
```

leads to 1 context being created and 1 shutdown.
So it looks like Kotest with `IsolationMode.InstancePerTest` unnecessarily creates an app context for each outer Spec scope ("context", "given", "when") and doesn't shut them down when the test is finished.

## Reproduction

Running `./gradlew build` in [kotest-micronaut-test-app.zip](https://github.com/kotest/kotest/files/12743184/kotest-micronaut-test-app.zip) will demonstrate the issue leading to 3 context starts and only 1 shutdown, see STDOUT.

## Versions

Kotest: 5.7.2
Micronaut Platform 4.1.2

**Comment by sksamuel** [comment]
This is because you have set the mode to instance per test in your config.
If you want a single instance to only be created for the inner most nodes, then use instance per leaf.
Each time a new class is created, micronaut is creating a new context.

**Comment by Spikhalskiy** [comment]
@sksamuel Ok, interesting. I didn’t realize that with “instance per test” it’s expected that Kotest will create an environment for the outer scopes. It’s not super obvious from the name of the mode. Thank you for pointing it out.

Irrespectively of that, all the contexts that kotest initializes, kotest should close, and not just abandon. It looks like the contexts created for outer nodes get abandoned without triggering the right lifecycle methods at the moment. 

This leads to users like us have a resource leak and an unavoidable OOM/out of open files/connections/etc with larger amount of test classes in the test set when using  BehavioralSpec or ShouldSpec with “context” as explained in the issue.

Does this part look valid?

**Comment by sksamuel** [comment]
Yes, but I think we need to fix that in the micronaut test extension, which is part of the micronaut project. I will make a PR to that project.

**Comment by sksamuel** [comment]
I noticed in your test project you also had to suppress the not used warning for project config. That's must be a bug in the intellij kotest plugin which I will fix.

**Comment by Spikhalskiy** [comment]
@sksamuel Amazing, makes sense. Thank you, Sam. Looking forward for these!

**Comment by sksamuel** [comment]
Closing this as the PR was merged into Micronaut.
