### ISSUE TITLE
Support arrays in checkAll / forAll

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3722]
https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1696350321521309

**Comment by kshired** [comment]
@sksamuel I think I can fix this issue. Can you assign to me?

**Comment by sksamuel** [comment]
Done

**Comment by kshired** [comment]
@sksamuel 

I think we cannot support `checkAll<Array<T>>`, `Arb<Array<T>>`, because of type erasure and variance of Array.
Instead, we can provide `checkAll(Arb.array(Arb.string())`, `Arb.array(Arb.string())`.

What do you think about this?

**Comment by sksamuel** [comment]
I think that will work.

**Comment by sksamuel** [comment]
Actually I thought Array's don't suffer from type erasure?

**Comment by kshired** [comment]
Oh that was my misunderstanding
