### ISSUE TITLE
More support for ranges

### ISSUE THREAD

**Issue by AlexCue987** [kotest/kotest#3736]
Examples:
* `(0..2) shouldOverlapWith (1..3)`
* `(2..3) shouldBeIn (1..4)`
* `(0..1) shouldNotOverlapWith (2..3)`
* `(4..5) shouldNotBeIn (1..3)`

should support both ClosedRange and OpenEndRange.

I'd like to do it if this feature is needed.

**Comment by mirageoasis** [comment]
I think add support shouldBeIn range would be hard. But maybe creating new function can be solution.

**Comment by AlexCue987** [comment]
> I think add support shouldBeIn range would be hard. But maybe creating new function can be solution.

got it. how about this `(2..3) shouldBeInsideOf (1..4)`

**Comment by mirageoasis** [comment]
> > I think add support shouldBeIn range would be hard. But maybe creating new function can be solution.
> 
> got it. how about this `(2..3) shouldBeInsideOf (1..4)`

think we have to specify which type we should accept only range? or other list types

**Comment by mirageoasis** [comment]
if maintainer says yes maybe I can add method to support this proposal

**Comment by AlexCue987** [comment]
> > > I think add support shouldBeIn range would be hard. But maybe creating new function can be solution.
> > 
> > 
> > got it. how about this `(2..3) shouldBeInsideOf (1..4)`
> 
> think we have to specify which type we should accept only range? or other list types

only ranges. It does not make sense for lists

**Comment by sksamuel** [comment]
What about

```
(0..2) shouldIntersect (1..3)
(2..3) shouldBeWithin (1..4)
```

**Comment by AlexCue987** [comment]
> What about
> 
> ```
> (0..2) shouldIntersect (1..3)
> (2..3) shouldBeWithin (1..4)
> ```

let's use these function names

**Comment by sksamuel** [comment]
Assigned to you

**Comment by mirageoasis** [comment]
I think there should be some careful approaches about ranges since it has backward range

**Comment by mirageoasis** [comment]
> I think there should be some careful approaches about ranges since it has backward range

and think we need to add support for until 
or maybe can I get until feature assigned?

**Comment by sksamuel** [comment]
> I think there should be some careful approaches about ranges since it has backward range

backwards or forwards, still comprises a set of numbers, so within should be fine.

**Comment by LeoColman** [comment]
I'd also enforce that we should try to go for an strictly correct mathematical definition.

Sets theory is very well defined, ie
- A set within a set
- An open ended range
- A close ended
- etc

**Comment by sksamuel** [comment]
I will release 5.8.1 from what is on main in a few days, then whatever comes after will move to 5.9 which is will be kotlin 1.9+

**Comment by AlexCue987** [comment]
implemented only intersect https://github.com/kotest/kotest/pull/3792
