### ISSUE TITLE
Kotest plugin version 1.3.70-IC-2023.2  causes tests in custom spec to no longer have green triangles

### ISSUE THREAD

**Issue by rei-paypay** [kotest/kotest#3740]
Hello there.

I just updated the Kotest plugin for IntelliJ to version `1.3.70-IC-2023.2` and now our custom spec functions can no longer be run via the green triangles. Specifically, tests using this spec no longer display the green triangle.

Right-clicking on each test case still shows the `Run` and `Debug` options, and both seem to work as normal. However, right-clicking on the class itself no longer shows those options.

This is a simplified version of the spec we are using
```
open class BaseIntegrationTestSpec(body: DescribeSpec.() -> Unit = {}) : DescribeSpec(body) {
  // some configs
}
```

Can someone please help out here? Thank you.

**Comment by rei-paypay** [comment]
Hello there.
Any updates on this?

**Comment by sksamuel** [comment]
Does your BaseIntegrationTestSpec still define tests in the same way, using describe and it blocks ?

**Comment by rei-paypay** [comment]
@sksamuel 
Sorry for the late response.
Yes, we use `BaseIntegrationTestSpec` similarly to `DescribeSpec`. The former is just a simple subclass of the latter.
Here is the code itself:
```
open class BaseIntegrationTestSpec(body: DescribeSpec.() -> Unit = {}) : DescribeSpec(body) {
  override fun extensions(): List<Extension> = listOf(
    SpringExtension,
    SpringRestTemplateExtension,
  )

  override fun isolationMode(): IsolationMode = IsolationMode.SingleInstance
  override fun timeout(): Long = 5.minutes.inWholeMilliseconds
}
```
And here is an example of how we are using the class:
```
class KafkaExtensionSpringTest : BaseIntegrationTestSpec({
  val kafkaContainer = install(TestContainerExtension(KafkaContainer())) as KafkaContainer

  describe("KafkaExtension") {
    it("should clean messages") {
      // stuff
    }
  }
})
```

**Comment by sksamuel** [comment]
can you try the latest plugin that was just released. This should be fixed.

**Comment by rlewanczyk** [comment]
I have the same problem with kotest plugin `1.3.72-IC-2023.2` with spring integration tests using `ShouldSpec`

**Comment by 1Mark** [comment]
> I have the same problem with kotest plugin 1.3.72-IC-2023.2 with spring integration tests using ShouldSpec

I have the exact same problem.

**Comment by sksamuel** [comment]
> I have the same problem with kotest plugin `1.3.72-IC-2023.2` with spring integration tests using `ShouldSpec`

Are you using shouldspec directly or with an intermediate class ?

**Comment by 1Mark** [comment]
> > I have the same problem with kotest plugin `1.3.72-IC-2023.2` with spring integration tests using `ShouldSpec`
> 
> Are you using shouldspec directly or with an intermediate class ?

Yeah I'm using an intermediate class. Although after setting test source root  in intellij the issue went away.

**Comment by Kantis** [comment]
@rei-paypay please re-open if this is still an issue with the latest plugin version
