### ISSUE TITLE
Performance regression with Kotest 5.7.x classpath scanning

### ISSUE THREAD

**Issue by easimon** [kotest/kotest#3746]
Since Kotest 5.7, classpath scanning for Extensions and Config has become very slow, adding multiple minutes to a test run.

This does NOT seem related to #3670 

## Tested Kotest versions

5.6.2 vs. 5.7.2

## Note 

Since it is not a public project where I noticed the issue first, I can't give access to the sources. 
I also did not (yet) check on any other project yet, if that issue is reproducible there as well. I will add this if I find a public reproducer.

## Description

I have a small/medium sized Spring Boot Application, using Maven as a build tool. The project does not have any Kotest specific configuration (no `AbstractProjectConfig`, no `kotest.properties`). 

Prior to Kotest 5.7, this setup went well, and also auto-registered the `SpringAutowireConstructorExtension`, which we use heavily for injecting beans in Spring integration tests. 

Now, with Kotest 5.7.2, Maven makes a large pause during test startup (see below).

Executing `./mvnw test` makes a pause of multiple minutes between the `TESTS` banner and actually executing tests in Kotest 5.7.2. When using Kotest 5.6.2 (everything else the same), the pause is only a few seconds. See example logs below.

It seems to be depending on the size of the project (or amount of dependencies, or tests...?), but the pause makes the major contribution to the total runtime of `./mvnw test`. In one project, the pause is 8 minutes of about 11 total execution time, in the other it is about 3:30 of 4:30 minutes.

## Workaround 

I found, that, if I disable the classpath scanning by adding a `kotest.properties` like below, and add a ProjectConfig to register the `SpringAutowireConstructorExtension` manually, the pause vanishes. If I set one of the flags to false, the pause is approximately half as long.

So it seems the classpath scanning feature (which itself predates 5.7) has received a major performance regression in 5.7.

```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=my.path.to.KotestConfiguration
```
 
## Details

Timed output of `./mvnw test | ts` using 5.7.2

```
Oct 26 13:44:36 [INFO] --- surefire:3.2.1:test (default-test) @ ... ---
Oct 26 13:44:37 [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
Oct 26 13:44:37 [INFO] 
Oct 26 13:44:37 [INFO] -------------------------------------------------------
Oct 26 13:44:37 [INFO]  T E S T S
Oct 26 13:44:37 [INFO] -------------------------------------------------------
Oct 26 13:48:04 [INFO] Running ... (first test class name)
```

Timed output of `./mvnw test | ts` using 5.6.2

```
Oct 26 13:56:31 [INFO] --- surefire:3.2.1:test (default-test) @ ... ---
Oct 26 13:56:31 [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
Oct 26 13:56:31 [INFO] 
Oct 26 13:56:31 [INFO] -------------------------------------------------------
Oct 26 13:56:31 [INFO]  T E S T S
Oct 26 13:56:31 [INFO] -------------------------------------------------------
Oct 26 13:56:37 [INFO] Running ... (first test class name)
```

**Comment by andersflemmen** [comment]
We have observed similar problems, with the worst case adding about 7 extra minutes to the execution time.

**Comment by LeoColman** [comment]
I imagine this also applies to 5.8.x*?
Could you guys confirm?

**Comment by easimon** [comment]
I can confirm -- the same issue is there with 5.8.0

**Comment by easimon** [comment]
Not as large as in other projects, but I can notice a slowdown in https://github.com/easimon/tado-exporter as well (which severely suffers coverage / does not have a lot of tests). 

With kotest 5.6.2, a `./mvnw clean test` takes around 17 seconds on my machine, with kotest 5.8.0 it takes > 30 seconds. The main difference is due to the pause when starting tests in the `tado-exporter` subproject.

```
Nov 10 12:06:20 [INFO] -------------------------------------------------------
Nov 10 12:06:22 [INFO] Running click.dobel.tado.exporter.client.auth.AuthClientIntegrationTest
```
(5.6.2, two seconds between the lines)

vs.

```
Nov 10 12:03:52 [INFO] -------------------------------------------------------
Nov 10 12:04:06 [INFO] Running click.dobel.tado.exporter.client.auth.AuthClientIntegrationTest
```
(5.8.0, 14 seconds between the lines)

times were added by piping it through `ts` from `moreutils`, i.e. `./mvnw clean test | ts`.

**Comment by sksamuel** [comment]
TIL about `ts`

**Comment by sksamuel** [comment]
I can see a similar difference on the `tado-exporter` project. Not quite as drastic - 22s vs 30s, but enough that I should be able to nail this down.

**Comment by sksamuel** [comment]
In 5.7 we added jar scanning. This is enabled by default, but we should have left it disabled by default.
In 5.8.1 I will revert this to being disabled by default.
In the meantime, you can add the following system properties to your build:

```
kotest.framework.discovery.jar.scan.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
```

Or if you use spring, just

```
kotest.framework.discovery.jar.scan.disable=true
```

**Comment by easimon** [comment]
When setting `kotest.framework.discovery.jar.scan.disable=true`, kotest fails to instanciate the `AuthClientIntegrationTest`, with both kotest 5.6.2 and kotest 5.8.0, because of a missing no-arg-constructor. So the setting seems to have an effect prior to 5.7.x...?

So it seems, disabling that setting disables a component required to start Spring (Boot) tests / inject their dependencies.

I do not completely understand what exactly kotest is scanning for when using the following settings, what exactly I miss when disabling them, and how to replace that. Do you have a pointer to read on that?

```
kotest.framework.classpath.scanning.config.disable=true|false
kotest.framework.classpath.scanning.autoscan.disable=true|false
kotest.framework.discovery.jar.scan.disable=true|false
```

And lastly: Is it possible to get more verbose log output in the kotest startup phase, so I can see what exactly takes so long?

**Comment by sksamuel** [comment]
Q1. For spring if you want to disable autoscan you need to add the spring extension. See the docs for multiple ways you can do that.
Q2. For debugging, export KOTEST_DEBUG=true before you execute gradle or mvn

**Comment by easimon** [comment]
Sorry for all the questions -- but then I think I still don't understand:

- With kotest 5.6.2 and no additional kotest.properties configuration or ProjectConfig, the tests started quickly, and automatically picked up the Spring Extension where necessary
- Starting with 5.7.0, the classpath scanning feature has gotten a lot slower. The exact runtimes seem related to classpath size (not sure), and go into the minutes for some projects
- The scanning feature itself seems to have been there prior to 5.7, otherwise the Spring tests should have failed previously as well

So: while adding the explicit configuration and deactivating the various classpath scanning options removes the startup pause: The automated classpath scanning used to work well (and quickly) and were a welcomed feature which now comes with a major tradeoff. I still wonder what made it so slow with 5.7, and if it could not be "fixed" in a way that does not require explicit configuration. 

I will try if I can find something by adding KOTEST_DEBUG=true.

**Comment by masarykadam** [comment]
@easimon I have found workaround which allows you to use constructor injection in tests while disabling auto-scanning.
Paste following lines into `kotest.properties` file:
```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.discovery.jar.scan.disable=true
kotest.framework.config.fqn=com.your.package.KotestConfig
```

Next create abstract project configuration as follows:
```kt
package com.your.package

import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.extensions.Extension
import io.kotest.extensions.spring.SpringAutowireConstructorExtension

class KotestConfig : AbstractProjectConfig() {
	override fun extensions(): List<Extension> = listOf(SpringAutowireConstructorExtension)
}
```
Tested with Kotest 5.7.2.
Hope it helps!

**Comment by andersflemmen** [comment]
@sksamuel Any estimate for when 5.8.1 will be released?

**Comment by andersflemmen** [comment]
@sksamuel Any estimate for when 5.8.1 will be released?

**Comment by fgaule** [comment]
Any news about this issue?

**Comment by sksamuel** [comment]
@fgaule did you turn off the scanning as mentioned higher in the thread as a workaround.
In 6.0 scanning will be gone.

**Comment by fgaule** [comment]
Hi @sksamuel,

I wanted to share that the workaround was successful with just the following two configurations:
```
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=com.your.package.KotestConfig
```

I spent quite a bit of time discovering this issue, so I was wondering if there is an expected release date for v6.0. It would be really helpful to know.

Thank you!

**Comment by sksamuel** [comment]
You can try the latest 6.0 snapshot today if you feel brave :)
The version links are in the main github readme.
