### ISSUE TITLE
`NoSuchMethodException` using kotest with Kotlin 1.9.20 

### ISSUE THREAD

**Issue by nicolasfara** [kotest/kotest#3749]
Kotest version: `5.7.2`

When testing a multiplatform project with Kotlin 1.9.20, the following exception is raised on native targets: https://gradle.com/s/a4yrzjcg7ph3u (here the gradle build scan)

Reproducible build: https://github.com/nicolasfara/Template-for-Kotlin-Multiplatform-Projects/

**Comment by idugalic** [comment]
I have the same issue https://github.com/fraktalio/fmodel/pull/245

**Comment by kshired** [comment]
5.8.0 released
