### ISSUE TITLE
Behavior of `collection.shouldHaveSingleElement { block }` doesn't match the documentation

### ISSUE THREAD

**Issue by m-burst** [kotest/kotest#3754]
I am using Kotest 5.7.2.

The documentation for `collection.shouldHaveSingleElement { block }` states:

> Asserts that the collection only contains a single element and that the element matches the given predicate.

However, the implementation actually checks that the collection has single element matching the predicate (but may have other elements):

```kt
fun <T> singleElement(p: (T) -> Boolean): Matcher<Collection<T>> = object : Matcher<Collection<T>> {
   override fun test(value: Collection<T>): MatcherResult {
      val filteredValue: List<T> = value.filter(p)
      return MatcherResult(
         filteredValue.size == 1,
         { "Collection should have a single element by a given predicate but has ${filteredValue.size} elements: ${value.print().value}" },
         { "Collection should not have a single element by a given predicate" }
      )
   }
}
```

**Comment by kshired** [comment]
The first time this feature added, documentation was `Asserts that the collection contains a single element by a given predicate.`.

But wrongly changed at #2830

**Comment by mirageoasis** [comment]
can I get this issue assigned?

**Comment by LeoColman** [comment]
Go for it @mirageoasis !

**Comment by LeoColman** [comment]
@Kantis Ping as author of #2830
