### ISSUE TITLE
Add infix modifier to beIn matcher

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#3755]
https://github.com/kotest/kotest/blob/faf6a59f247ef09442459b7e41cfc683ac5829c4/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/bein.kt#L55

This function and any other applicable functions in the same class should be infix when possible

**Comment by kshired** [comment]
@LeoColman 
As I understand it, if a parameter is vararg or has a default value, you can't add an infix modifier, right?

**Comment by LeoColman** [comment]
Can't we have a version of the function that is not vararg?

**Comment by sksamuel** [comment]
The infix version would only work with a range, not a var arg list.

**Comment by LeoColman** [comment]
I don't remember if I had a specific use case in mind.
Let's see if I find it again :)
