### ISSUE TITLE
Access the coroutine TestScope

### ISSUE THREAD

**Issue by CLOVIS-AI** [kotest/kotest#3760]
Kotest version: 5.7.1

The KotlinX.Coroutines.Test library introduces a special coroutine scope, `TestScope`. It is the entrypoint to many special features, including virtual time and background jobs.

Kotest allows configuring a test to run in `TestScope`, however, there is no way to access `TestScope` itself.
Most of the functionality is available through the coroutine context, but not all. Additionally, this makes it impossible to call test helpers from other libraries that have a `TestScope` receiver.

Kotest should provide a way to access the `TestScope` inside a test.

**Comment by sksamuel** [comment]
5.8.1 will have the extension val `coroutineTestScope` which exposes this.

**Comment by CLOVIS-AI** [comment]
Perfect, thanks!

**Comment by CLOVIS-AI** [comment]
Do you have an estimation of when 5.8.1 will be released?

**Comment by CLOVIS-AI** [comment]
Hey, is there any information on when 5.8.1 will be released?

**Comment by sksamuel** [comment]
5.8.1 has been released!
