### ISSUE TITLE
Updating Kotest breaks Mockk

### ISSUE THREAD

**Issue by binkley** [kotest/kotest#3762]
Apologies that I'm not on Slack.
I'm unsure who's issue this might be, or if it is mine, and how to resolve.

The interaction is Kotest and Mockk.
I have a personal project (https://github.com/binkley/kotlin-dice) that is using Kotest 5.5.5 (clearly not latest) and Mockk 1.13.8 (latest).
When I updated my dependency to Kotest 5.x where x>5, I get build breakage for Mockk. As you can see from the below output, I'm using Maven.
**The only change is updating Kotest**.

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.20:test-compile (test-compile) on project kotlin-dice: Compilation failure: Compilation failure:
[ERROR] /home/binkley/src/kt/kotlin-dice/src/test/kotlin/hm/binkley/dice/testing.kt:[6,11] Unresolved reference: mockk
```

My Kotest dependencies are:
- kotest-runner-junit5-jvm - 5.5.5 (out of date)
- kotest-assertions-core-jvm - 5.5.5 (out of date)

My Mockk dependencies are:
- mockk - 1.13.8 (latest)

I took a look into `dependency:tree` for Maven, and Kotest does not use Mockk.
This project is on JDK 11, and I'm working on moving it to JDK 21 (there's another dependency--unrelated--which holds me back).

**Comment by sksamuel** [comment]
Can you try 5.8.x just so we're on the latest.

**Comment by binkley** [comment]
@sksamuel Yep, good idea.
It's part of me refreshing the deps for my project, and moving to JDK 21.
I'll post again when I get Kotest updated.
