### ISSUE TITLE
Unable to run tests with kotest-intellij-plugin in integration test module

### ISSUE THREAD

**Issue by kkojot** [kotest/kotest#3778]
Using:

- kotest **kotest-runner-junit5:5.8.0**
- kotest-intellij-plugin **1.3.71-IC-2023.2**
- intellij **2023.2.5 Ultimate Edition**

To reproduce the issue:

1. create new kotlin/gradle project
2. add module **kotest**
3. add build.gradle to kotest like below:
```groovy
plugins {
    id "org.jetbrains.kotlin.jvm"
}

repositories {
    mavenCentral()
}

sourceSets {
    intTest {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

configurations {
    intTestImplementation.extendsFrom implementation
    intTestRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    intTestImplementation 'io.kotest:kotest-runner-junit5-jvm:5.8.0'
    testImplementation 'io.kotest:kotest-runner-junit5-jvm:5.8.0'
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests.'
    group = 'verification'

    testClassesDirs = sourceSets.intTest.output.classesDirs
    classpath = sourceSets.intTest.runtimeClasspath
    shouldRunAfter test

    useJUnitPlatform()

    testLogging {
        events "passed"
    }
}

check.dependsOn integrationTest
```

4. add sample test to **test** and **inTest** like below:
```
└── src
    ├── intTest
    │   └── kotlin
    │       └── MyTests.kt
    └── test
        └── kotlin
            └── MyTestes2.kt
```
I can easly run testes from `MyTestes2.kt` with little triangle next to test name but in `MyTests.kt` in intTest no traingle is visible. The only way to run those testes is using gradle command
```
./gradlew :kotest:integration --tests MyTests --info
```

**Comment by Kantis** [comment]
Haven't investigated the cause for this, but have you considered to simply register your integration test suite using the `jvm-test-suite` plugin from gradle? It would look something like

```
@Suppress("DSL_SCOPE_VIOLATION")
plugins {
    // other plugins...
   `jvm-test-suite`
}

testing {
   suites {
      val test by getting(JvmTestSuite::class) {
         useJUnitJupiter()
      }

      // Gradle determines name of test suite by the name of the variable
      val integrationTest by registering(JvmTestSuite::class) {
         testType.set(TestSuiteType.INTEGRATION_TEST)
         dependencies {
           implementation(libs.kotest)
           // etc
         }
     }
  }
}
```

I have zero issues running tests in such a source set, so it seems odd that it wouldn't work properly in your case unless something is missing in your setup

**Comment by kkojot** [comment]
My code above of creating `intTest` module for integration test comes from official gradle documentation https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests 

The `jvm-test-suite` plugin is mentioned there either and I used your code to create `integrationTest` module. It seems to be a better way because `kotest-intellij-plugin` sees the tests now and I can run each of them directly from my IDE. Thanks :)

**Comment by Kantis** [comment]
@kkojot great to hear!

As mentioned on that page, you most likely have to flag the source set as a test sourceset as well. 

>If you are working with the IntelliJ IDE, you may wish to flag the directories in these additional source sets as containing test source rather than production source as explained in the [Idea Plugin](https://docs.gradle.org/current/userguide/idea_plugin.html#sec:idea_identify_additional_source_sets) documentation.

If you didn't do that, I think that would explain why you didnt see the kotest actions

**Comment by kkojot** [comment]
Yeah, that did the trick also. 

All I had to do is right click on the `kotlin` folder in my `intTest` module and mark it as `Test Sources Root`. Now `kotest-intellij-plugin` sees all of the tests. Thanks again.
