### ISSUE TITLE
Inaccurate Description of BehaviorSpec in Version 5.8

### ISSUE THREAD

**Issue by jinia91** [kotest/kotest#3790]
I've noticed that the description of BehaviorSpec in Kotest version 5.8 seems to be inaccurate. 

According to this pull request [kotest/kotest#3737](https://github.com/kotest/kotest/pull/3737), the context scope was applied to BehaviorSpec. 
However, this change is actually part of the 5.9 milestone, not 5.8.

but 5.8 doc include this change. 
https://github.com/kotest/kotest/blob/master/documentation/versioned_docs/version-5.8/framework/styles.md#behavior-spec

It need to be rollback for preventing any misunderstanding.

Thank you!

**Comment by Kantis** [comment]
Thanks for the report @jinia91 , and sorry for causing the confusion. As mentioned in the PR, 
> 5.8 docs were cut from master 2 weeks after 5.8.0 release went out, so some changes made it into the docs that are not actually present in 5.8.
