### ISSUE TITLE
Unable to fully define a `DescribeSpec` test with a multiline description that invokes the `TestWithConfigBuilder#config` method

### ISSUE THREAD

**Issue by klawson88** [kotest/kotest#3795]
### Expected Behavior
The successful execution of a`DescribeSpec` test with multiline description that invokes the `TestWithConfigBuilder#config` method.

### Current Behavior
Failure of a`DescribeSpec` test with multiline description that invokes the `TestWithConfigBuilder#config` method, due to the test not being "fully defined".

### Context
A `DescribeSpec` test with a multiline description, that invokes the `TestWithConfigBuilder#config` method, fails with the following exception: 

```
java.lang.IllegalStateException: Test was not fully defined: [DescribeSpecContainerScope] -- prevents test from executing
```

### Steps to Reproduce
**Minimal reproducible example**
```kotlin
package com.example

import io.kotest.core.NamedTag
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.booleans.shouldBeTrue

class KoTestMultilineTestNameWithConfigBugSpec: DescribeSpec({
    val fooTag = NamedTag("foo")

    describe("Multiline tagged test name") {
        it("""prevents test
            | from executing""".trimMargin()).config() {
            true.shouldBeTrue()
        }
    }
})
```

### Your Environment
- **Build tool:** Gradle 8.5
- **Kotest version:** 5.8

**Comment by LeoColman** [comment]
What exactly is your use-case for a test with multiple-lines in its name?
