### ISSUE TITLE
Project-level config is not working for iOS target

### ISSUE THREAD

**Issue by OSemenovBoyarka** [kotest/kotest#3804]
**Which version of Kotest are you using**
`Kotest version is 5.8.0`
`Kotlin version is 1.9.20`
Project is shared Kotlin Multiplatform Mobile library consumed by Android and iOS applications.

**The issue**
It appears [Project-Level Config](https://kotest.io/docs/framework/project-config.html) is not supported on non-JVM targets (I've tested iOS only).
Android target picks up config properly while iOS completely ignores it. 

Not sure if that is not implemented yet, but looking to [this commit](https://github.com/kotest/kotest/pull/3718/commits/9aa15479095ff9feb91bd342da5b31eb689aa62d#diff-edd794ce49369e5b45d9c8951fd3d3b4dba7b4dd15de00e633ba9e7d218eca06R36) it seems so. 

Are there any plans to add support of that feature or at least updating documentation to clearly state that?

**Comment by OSemenovBoyarka** [comment]
It appears to work if I change `AbstractProjectConfig` subclass from `object` to `class`

**Comment by LeoColman** [comment]
So do you think we should just document it as such @OSemenovBoyarka?
As I understand, you made it work with a simple change to the definition, right?

**Comment by OSemenovBoyarka** [comment]
@LeoColman yep, that is true, simple change made that work. I think clearly highlighting it in documentation should fix the problem. 

Also documentation lack information of which project config features are working with JVM targets only (ones I've faced - `AutoScan` and `isolationMode` are applied to JVM only).

**Comment by sksamuel** [comment]
Updated docs to specify class and marked in javadoc which options are jvm only.
