### ISSUE TITLE
enhance shouldContainExactlyInAnyOrder, or create another matcher?

### ISSUE THREAD

**Issue by AlexCue987** [kotest/kotest#3807]
using `shouldContainExactlyInAnyOrder` for lists of elements with many fields, it is not immediately clear what exactly is different:
```
listOf(sweetGreenOnion, sweetGreenApple, sweetRedApple) shouldContainExactlyInAnyOrder listOf(sweetGreenApple, sweetRedApple, sweetGreenPear)
Collection should contain [Fruit(name=apple, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet), Fruit(name=pear, color=green, taste=sweet)] in any order, but was [Fruit(name=onion, color=green, taste=sweet), Fruit(name=apple, color=green, taste=sweet), Fruit(name=apple, color=red, taste=sweet)]
```

So I wrote a matcher that outputs the following for the same two collections:
```
Element in expected, but not in actual:
Fruit(name=pear, color=green, taste=sweet), count=1

Element in actual, but not in expected:
Fruit(name=onion, color=green, taste=sweet), count=1

Possible Matches:
 expected: Fruit(name=apple, color=green, taste=sweet), 
  but was: Fruit(name=onion, color=green, taste=sweet), 
  distance: 0.67,
  fields:
  name expected: apple, but was: onion
  color = green
  taste = sweet

 expected: Fruit(name=pear, color=green, taste=sweet), 
  but was: Fruit(name=onion, color=green, taste=sweet), 
  distance: 0.67,
  fields:
  name expected: pear, but was: onion
  color = green
  taste = sweet
```

It also handles duplicates as follows:
```
            val expected = listOf(sweetGreenApple, sweetRedApple)
            val actual = listOf(sweetGreenApple, sweetRedApple, sweetRedApple)

Count mismatch:
Fruit(name=apple, color=red, taste=sweet)
  expectedCount=1
  actualCount  =2
```

Do we want to add the matcher to kotest? If yes, should it be a new matcher, or improved existing `shouldContainExactlyInAnyOrder`?

**Comment by LeoColman** [comment]
I'd say it makes sense to have this kind of matcher.

It doesn't seem to be easy to implement and test 😅 

Improving the existing `shouldContainExactlyInAnyOrder` seems the best approach to me. If and only if the behavior is kept the same and we are only changing loggers. 

If the behavior changes, we can create a new matcher and deprecate `shouldContainExactlyInAnyOrder`, but I wish you luck on finding a name for that 😂

**Comment by LeoColman** [comment]
And the way you are displaying fields it seems that you'll be using reflection for that. If this matcher is not for JVM only, I don't know how you could do that.

**Comment by AlexCue987** [comment]
For non-JVM, we can still improve `shouldContainExactlyInAnyOrder` as follows:
```
Element in expected, but not in actual:
Fruit(name=pear, color=green, taste=sweet), count=1

Element in actual, but not in expected:
Fruit(name=onion, color=green, taste=sweet), count=1

Count mismatch:
Fruit(name=apple, color=red, taste=sweet)
  expectedCount=1
  actualCount  =2
```
because we don't need reflection for that.
For JVM, we can improve even more, adding:
```
expected: Fruit(name=pear, color=green, taste=sweet), 
  but was: Fruit(name=onion, color=green, taste=sweet), 
  distance: 0.67,
  fields:
  name expected: pear, but was: onion
  color = green
  taste = sweet
```

And that could be a separate matcher. Unless we can implement the same function `describeSimilarItems` which will return an empty string non-JVM, and the description above for JVM. WDYT?

**Comment by sksamuel** [comment]
@AlexCue987 @LeoColman what do you think we should do here ?

**Comment by AlexCue987** [comment]
this is done
