### ISSUE TITLE
LocalDate generator fails if minDate and maxDate are equal

### ISSUE THREAD

**Issue by jedesroches** [kotest/kotest#3829]
When using the `localDate` generator, the following exception occurs if `minDate` and `maxDate` are equal:

```
Random range is empty: [0, 0).
java.lang.IllegalArgumentException: Random range is empty: [0, 0).
[... stack trace]
```

The exception comes from the code here:

https://github.com/kotest/kotest/blob/ce6b4feddf5364f3c6a9992d086c5229c50b046d/kotest-property/src/jvmMain/kotlin/io/kotest/property/arbitrary/dates.kt#L64C5-L64C5

A minimal example to reproduce the bug:

```kotlin
class BugExample : DescribeSpec({
  val failingGenerator : Arb<LocalDate> = Arb.localDate(minDate = LocalDate.MIN, maxDate = LocalDate.MIN)
  describe("The above generator") {
    it("Fails") {
      forAll(failingGenerator) { true }
    }
  }
})
```

And a more concrete example of real-world code that can make this happen, when the date generated by the first generator is equal to the default `minDate` :

```kotlin
class BugExample2 : DescribeSpec({
  val orderedDatesGenerator: Arb<Pair<LocalDate, LocalDate>> =
    Arb.localDate().flatMap { laterDate: LocalDate -> Arb.localDate(maxDate = laterDate).map { earlierDate -> Pair(earlierDate, laterDate) } }
  describe("The above generator") {
    it("sometimes fails, if laterDate is the default minDate") {
      forAll(failingGenerator) { true }
    }
  }
})
```

I'm not completely sure what the best way to address this is. Maybe before calling random, check if the range is empty and in that case return a constant ?

**Comment by jedesroches** [comment]
Thinking about this, I see the following ways to deal with the problem:
- Make it clear in the documentation that this is an open-ended range. This leaves the user with the problem of dealing with the first Arb generating `LocalDate.MAX` when trying to build several ordered dates. It might also be worth it to throw an exception with a more explicit error message in that case.
- Checking if `minDate` and `maxDate` are equal and in that case build a constant generator for that date, maybe with a warning for the user.

I'm happy to make a PR with either.

**Comment by LeoColman** [comment]
> Checking if minDate and maxDate are equal and in that case build a constant generator for that date, maybe with a warning for the user.

I like this option better


What I'm questioning now is if it should give a warning to the user or if we should consider it part of normal behavior (and thus no warning).

Or even a third option: Disableable warnings. We have plenty of "System Property Booleans" around.


----

I'd say start with a pull request without a warning - fix the issue - then we can think again.


Nice catch @jedesroches !
