### ISSUE TITLE
Allow calling any { } without being inside a suspend context

### ISSUE THREAD

**Issue by TWiStErRob** [kotest/kotest#3834]
I'm trying to translate this Hamcrest line to kotest:

```kotlin
assertThat(myMap, either(not(hasKey(myKey))).or(not(instanceOf(HashMap::class.java))))
```
and I found `any { }`, but I cannot call it like:
```kotlin
val myMap = mapOf("a" to 1, "b" to 2)
any {
	myMap shouldNotContainKey "c"
	myMap shouldNot beInstanceOf<HashMap<*, *>>()
}
```
because any is not a normal function:
https://github.com/kotest/kotest/blob/ce6b4feddf5364f3c6a9992d086c5229c50b046d/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/any.kt#L17

The problem here being `any` must necessarily be inside a `suspend` context

**Comment by TWiStErRob** [comment]
(I also couldn't find the docs for this function, I have a feeling it should be listed here: https://kotest.io/docs/assertions/inspectors.html)

**Comment by LeoColman** [comment]
I think what you're looking for here is [Soft Assertions](https://kotest.io/docs/assertions/soft-assertions.html)

Your example would be converted to

```
val myMap = mapOf("a" to 1, "b" to 2)


assertSoftly(myMap) {
  it shouldNotContainKey "c"
  it shouldNot beInstanceOf<HashMap<*, *>>()
}

```

You can also achieve similar result with the default Kotlin `with` or other scope functions:

```
with(myMap) {
   it shouldNotContainKey "c"
   it  shouldNot beInstanceOf<HashMap<*, *>>()
}
```

**Comment by TWiStErRob** [comment]
Those have different semantics:

| Result | any | assertSoftly | with<br> = statements |
|--------|--------|--------|-------|
| pass + pass | pass | pass | pass |
| pass + fail | pass | fail | fail |
| fail + pass | pass | fail | fail |
| fail(1) + fail(2) | fail(1+2) | fail(1+2) | fail(1) |

**Comment by Kantis** [comment]
@TWiStErRob are you not testing using a Kotest spec? I think all Kotest TestScopes are suspending, so you should be able to invoke a suspending function just fine.

If not, couldn't you simply wrap your assertion with `runBlocking`? E.g.
```kotlin
val myMap = mapOf("a" to 1, "b" to 2)
runBlocking {
  any {
    myMap shouldNotContainKey "c"
    myMap shouldNot beInstanceOf<HashMap<*, *>>()
  }
}
```

**Comment by TWiStErRob** [comment]
@Kantis Please read the title and consider reopening.

I'm not using coroutines, because I'm testing plain old functions. Why would I fire up coroutines + dispatcher + scope and all that jazz (and complication), when all I need is a simple assertion?

Also I'm not using a Kotest Spec, I'm using JUnit 5. Those are providing the same features, right? And the assertions should be independent of the test runner.

**Comment by sksamuel** [comment]
any {} requires a coroutine context because that's where it stores the state of failed assertions. You don't need any dispatcher, scope etc, to create one, you can just use runBlocking{} around your test. This is in fact how kotlin's own test support does anything to do with advanced testing. Kotest provides this by default, but you're using junit so runBlocking is the way to go.
