### ISSUE TITLE
gradle test output includes fully qualified test name

### ISSUE THREAD

**Issue by flyingfishflash** [kotest/kotest#3837]
This is question only - 

I'm not sure if this is related to gradle or kotest, but when test names nested below two levels always output the fully qualified test method name, rather than just the method name:

My example uses DescribeSpec, but others are the same.

Not sure if it's possible to output _non_ fq method name?

eg: 
```kotlin
    context("/lists/$id") {
      describe("delete") {
        it("list is deleted") {
          // test here
        }
```

results in this output:

```
net.flyingfishflash.loremlist.domain.lrmlist.LrmListControllerTests > /lists/1 > delete > net.flyingfishflash.loremlist.domain.lrmlist.LrmListControllerTests.list is deleted PASSED
```

**Comment by Kantis** [comment]
I agree it's ugly. I think it's just the default gradle test logger. If you switch to https://github.com/radarsh/gradle-test-logger-plugin you'll get more readable output.

**Comment by flyingfishflash** [comment]
@Kantis Thanks for the tip, I was unaware of that plugin, but indeed it looks promising!

**Comment by sksamuel** [comment]
Yep it's just the way gradle does it by default. Closing as @Kantis' advice is the way to go.
