### ISSUE TITLE
SpecSystemExitListener uses a terminally deprecated method in `java.lang.System`

### ISSUE THREAD

**Issue by moddyfire** [kotest/kotest#3841]
I get this message when using `SpecSystemExitListener`

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by io.kotest.extensions.system.SpecSystemExitListener (file:/Vols/vol5/cache_nobackup/users/moddyt/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-extensions-jvm/5.5.4/7fea36f77b078e3ab680a81602228894a885b847/kotest-extensions-jvm-5.5.4.jar)
WARNING: Please consider reporting this to the maintainers of io.kotest.extensions.system.SpecSystemExitListener
WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by LeoColman** [comment]
We'll probably have to find a new way to do it, similar to what we've done with previous JVM deprecations

Thanks @moddyfire !

**Comment by Kantis** [comment]
Seems that there has been no replacement defined yet.. Relevant reading:
https://bugs.openjdk.org/browse/JDK-8199704
https://stackoverflow.com/a/71150677/2477486

**Comment by moddyfire** [comment]
I hope (assume) they won't deprecate it until they decide on a replacement

**Comment by sksamuel** [comment]
Closing as there is nothing we can do until the JVM is updated with a replacement.
