### ISSUE TITLE
Don't deprecate non-smart-cast-based version of shouldBeInstanceOf

### ISSUE THREAD

**Issue by languitar** [kotest/kotest#3843]
Version of `shouldBeInstanceOf` etc. accepting a block of code as argument are marked for deprecation. However, smart casts are not always usable across module boundaries (https://discuss.kotlinlang.org/t/what-is-the-reason-behind-smart-cast-being-impossible-to-perform-when-referenced-class-is-in-another-module/2201/2). Therefore, I sometimes have to resort to the deprecated versions accepting a block to avoid a compiler error. Therefore, these methods should not be deprecated.

**Comment by sksamuel** [comment]
Good observation thanks. Undeprecated in 5.8.1
