### ISSUE TITLE
Gradle plugin `io.kotest.multiplatform` breaks project configuration

### ISSUE THREAD

**Issue by hezean** [kotest/kotest#3850]
**Which version of Kotest are you using**

5.8.0

```kotlin
plugins {
    kotlin("multiplatform") version "1.9.20"  //<-- https://kotlinlang.org/docs/multiplatform-hierarchy.html#default-hierarchy-template
    id("com.android.library") version "8.2.1"
    id("io.kotest.multiplatform") version "5.8.0"
}

kotlin {
    /* Unresolved reference: androidTarget */
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
    }

    sourceSets {
        /*
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Project.dependencies(configuration: DependencyHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
         */
        commonTest.dependencies {
            implementation(libs.bundles.kotest)
        }
    }
}
```

Hi, I'm trying to use Kotest in my KMM project (android & iOS target), but adding the kotest multiplatform in the shared module would break the Gradle build.

As for not using `android()`:

<img width="899" alt="Screenshot 2024-01-28 at 15 29 25" src="https://github.com/kotest/kotest/assets/49837965/333e2e2a-2088-46fa-95f5-169dfa4f897c">

<details>
<summary>Build Output</summary>
<pre>
> Configure project :shared
w: Missing 'androidTarget()' Kotlin target in multiplatform project 'shared (:shared)'.
The Android Gradle plugin was applied without creating a corresponding 'android()' Kotlin Target:

```
plugins {
    id("com.android.library")
    kotlin("multiplatform")
}

kotlin {
    androidTarget() // <-- please register this Android target
}
```

e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:8:5: Unresolved reference: androidTarget
e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:9:9: Unresolved reference: compilations
e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:10:13: Unresolved reference: kotlinOptions
e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:11:17: Unresolved reference: jvmTarget
e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:28:20: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Project.dependencies(configuration: DependencyHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
e: file:///Users/hezean/Downloads/MyApplication/shared/build.gradle.kts:31:20: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Project.dependencies(configuration: DependencyHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl

FAILURE: Build failed with an exception.

</pre>
</details>

To reproduce, just create a new KMP project and add the kotest plugin: [kotest-kmp-reproduce-minimal.zip](https://github.com/kotest/kotest/files/14071428/kotest-kmp-reproduce-minimal.zip)

Note: Someone raised the same issue in [slack channel](https://slack-chats.kotlinlang.org/t/16136675/has-anyone-had-success-using-kotest-in-a-kotlin-multiplatfor#837164f2-9449-4c1f-8047-da33a16c4a1f) but didn't receive enough attention. It would be great if a patch could be released to enable us using the new hierarchy template.

**Comment by ericksli** [comment]
Did you add the plugin into `plugins` in the root level build.gradle.kts?

Something like this:

```kotlin
plugins {
    alias(libs.plugins.kotest) apply false
}

```

**Comment by hezean** [comment]
> Did you add the plugin into `plugins` in the root level build.gradle.kts?
> 
> Something like this:
> 
> ```kotlin
> plugins {
>     alias(libs.plugins.kotest) apply false
> }
> ```

Ohhhh it works, thanks for saving my life!!
I'm new to kmp. While I tried some other stuff to fix it, I just forgot to do so
