### ISSUE TITLE
Kotest doesn't compare JAXBElement properly

### ISSUE THREAD

**Issue by hlarsonhlarson** [kotest/kotest#3855]
**Which version of Kotest are you using**
5.8.0

When using shouldBeEqualToComparingFields for JAXBElement fields doesn't compare properly. Because the JAXBElement is marked as built in, but it doesn't have equals method by default

**Comment by Kantis** [comment]
Should [this](https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L618) be changed to only types starting with `java.` or `kotlin.`? Was it actually desired to have all `kotlinx` and `javax` types included?
