### ISSUE TITLE
TestNG runner support

### ISSUE THREAD

**Issue by harveyives** [kotest/kotest#3862]
Hey! 

I have a large set of TestNG based projects that would benefit greatly from the use of Kotest. However, I am currently struggling to utilise it as we rely on the formatting of the TestNG reports.

I'm curious if there are any plans to implement a TestNG runner for Kotest? I see it was mentioned in the [changelog](https://kotest.io/docs/changelog.html#version-30x---march-29-2018) a few years ago.

**Comment by LeoColman** [comment]
An extension to generate the output in the same format as TestNG seems feasible

**Comment by Kantis** [comment]
AFAIK there are no plans to add a TestNG runner. 

I think we should keep this issue open for a while to see how requested it is. If it doesn't have enough support to add to Kotest directly, I think it could be added as a 3rd party extension. Let me know if you want pointers in getting started with that.

**Comment by sksamuel** [comment]
I don't think this would ever happen. It's hard enough trying to get kotest to run on JUnit successfully given how much more flexible Kotest is, and we've put a ton of effort into that. Trying to do the same with TestNG is going to require a ton of bandwidth for a project that's way less popular than JUnit.

Outputting in testng format though seems entirely feasible and relative quick.

**Comment by sksamuel** [comment]
Closing this as part of 6.0 we are adding a non junit runner.
