### ISSUE TITLE
withData in StringSpec tests

### ISSUE THREAD

**Issue by Fleshgrinder** [kotest/kotest#3869]
It seems as if `withData` cannot be used in `StringSpec` tests, unless one accepts that each individual case gets its name assigned automatically. The following, which should work, doesn't compile, because Kotlin cannot infer the correct types.

```kotlin
class DataTest : StringSpec({
    "what this test tests" {
        withData(
            "a" to 1,
            "b" to 2,
            "c" to 3,
        ) { (first, second) ->
            // fails with runtime error
        }
    }

    withData(
        { (first, second) -> "$first <> $second" },
        "a" to 1,
        "b" to 2,
        "c" to 3,
    ) { (first, second) ->
        // doesn't compile, type inference issues
    }
})
```

The `@BuilderInference` would fix the second issue:

```kotlin

@OptIn(ExperimentalTypeInference::class)
@BuilderInference
fun <T> RootScope.withData( // ...
```

**Comment by Kantis** [comment]
Re: 1st issue. I believe you should be unable to invoke `withData` from within a leaf scope. 

You could switch to `FreeSpec` which is similar to `StringSpec` but allows nesting and create a container scope, like:
```kotlin
class DataTest : FreeSpec({
    "what this test tests" - {
        withData(
            "a" to 1,
            "b" to 2,
            "c" to 3,
        ) { (first, second) ->
        }
    }
}
```

IMO we should try to add a `@DslScopeMarker` to prevent code in 1st example from compiling.


Re 2nd issue: Will have to read up what that does.. I'm not sure it's a good idea to force opt-in to use withData in root scope?
A workaround could be to use a named param for the 1st argument. 

```kotlin
class DataTest : StringSpec({
        withData(
        nameFn = { (first, second) -> "$first <> $second" },
        "a" to 1,
        "b" to 2,
        "c" to 3,
    ) { (first, second) ->
    }
}
```

**Comment by Fleshgrinder** [comment]
This is what I added to my fixtures:

```kotlin
// https://github.com/kotest/kotest/issues/3869
@file:OptIn(ExperimentalTypeInference::class)

package com.fleshgrinder.kotest

import io.kotest.common.ExperimentalKotest
import io.kotest.core.names.TestName
import io.kotest.core.spec.style.StringSpec
import io.kotest.core.spec.style.scopes.ContainerScope
import io.kotest.core.spec.style.scopes.addTest
import io.kotest.core.test.TestType.Dynamic
import kotlin.experimental.ExperimentalTypeInference

@BuilderInference
@OptIn(ExperimentalKotest::class)
fun <T> StringSpec.withData(
    name: (T) -> String,
    params: Array<out T>,
    test: suspend ContainerScope.(T) -> Unit,
) = params.forEach { addTest(TestName(name(it)), false, null, Dynamic) { test(it) } }

@BuilderInference
inline fun <reified T> StringSpec.withData(
    noinline name: (T) -> String,
    param: T,
    vararg params: T,
    noinline test: suspend ContainerScope.(T) -> Unit,
) = withData(name, arrayOf(param, *params), test)

```

The `@file:OptIn(ExperimentalTypeInference::class)` is only required in this file, not in my tests, if that's what you are afraid of.

Having a `@DslMarker` would help to ensure that one doesn't try to use it from within a test, absolutely.

And, yes, using `nameFn = { "" }` also resolves the issue.

**Comment by Kantis** [comment]
I'm more afraid of the experimental type inference to be dropped / broken in some upcoming Kotlin version, at which point we would have to drop the feature (breaking change) or lock our users to a certain Kotlin version. Or could that not happen?

Do you know how long it's been around and if there are any fopen YouTrack tickets discussing it?

**Comment by Fleshgrinder** [comment]
[It's used in the standard library](https://github.com/search?q=repo%3AJetBrains%2Fkotlin+%40BuilderInference+language%3AKotlin&type=code&l=Kotlin), I even added functions to it using it. The annotation is for sure going to be dropped at some point, but only because K2 is going to be intelligent enough on its own without it.

**Comment by Kantis** [comment]
Ok, I think we could add it. Wdyt @sksamuel ?

**Comment by sksamuel** [comment]
I'm in favor, if we can get it to work. I tried adding 

```
@OptIn(ExperimentalTypeInference::class)
@BuilderInference
```

To all the withData functions and could not get the 2nd example to compile.
I believe it is still getting confused between the nameFn version and the version that takes var args.

**Comment by sksamuel** [comment]
Might be related to the ticket I filed at https://github.com/kotest/kotest/issues/3901

**Comment by sksamuel** [comment]
StringSpec allows data tests at the top level. I've created a PR to add a test to verify in code.
https://github.com/kotest/kotest/pull/4556

It doesn't allow nested data tests because string spec doesn't have context blocks. That is by design - flip to FreeSpec if you need that.

We can't add the functions above, because kotlin does not have advanced enough type inference to make it work.

Notably, it cannot distinguish between:

```
fun <T> RootScope.withData(
   first: T,
   vararg rest: T,
   test: suspend ContainerScope.(T) -> Unit
) = withData(nameFn, listOf(first) + rest, test)
```

and

```
fun <T> RootScope.withData(
   nameFn: (T) -> String,
   first: T,
   vararg rest: T,
   test: suspend ContainerScope.(T) -> Unit
) = withData(listOf(first) + rest, test)
```

For this to work we need the internal  annotations @Exact or @OnlyInputTypes to be exposed, which have been pending for years.
