### ISSUE TITLE
Private Test Classes

### ISSUE THREAD

**Issue by Fleshgrinder** [kotest/kotest#3879]
JUnit supports execution of private Kotlin test classes. For some reason IntelliJ dropped support for that, although it supported it in the past. 😝 The Kotest IntelliJ plugin supports private Kotlin test classes (all the necessary gutter icons are drawn), but Kotest with the JUnit runner fails. It complains that it cannot find any tests with that name.

Now, this could be a bug report for the Kotest IntelliJ plugin, just asking for not drawing the gutter icons when the class is private. Like IntelliJ does it since a while for JUnit. I'm not asking for that, because I believe that test classes should be private. They shouldn't show up in auto-completion, and they shouldn't be reusable.

**Comment by Kantis** [comment]
I don't understand what you're asking for. Could you clarify?

**Comment by Fleshgrinder** [comment]
```kotlin
private class MyTest : StringSpec({
    "this should be runnable" {}
})
```

Currently the kotest IntelliJ plugin shows the run icons in the gutter next to `MyTest` and `"this should be runnable"` but clicking them results in an error where it complains that it cannot find the tests to execute.

**Comment by Fleshgrinder** [comment]
@sksamuel many thanks. ❤️
