### ISSUE TITLE
shouldBeEqualToComparingFields breaks with a typealias of a Java type

### ISSUE THREAD

**Issue by AlexLamaison-UnlikelyAI** [kotest/kotest#3880]
Using Kotest 5.8.

When using `shouldBeEqualToComparingFields` on an object with a field that is a Kotlin `typealias` to a Java/Kotlin type such as a `HashMap`, the test fails with an `IllegalArgumentException` because Kotest hasn't noticed that it's a Java type and is trying to recurse into.  

The problem is that [the `typeName` calculated here](https://github.com/kotest/kotest/blob/deb8d2a9000fa8eecec3185701ef2943cdaef528/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L584) is the name of the alias, not the name of the underlying type, and so [the check here](https://github.com/kotest/kotest/blob/deb8d2a9000fa8eecec3185701ef2943cdaef528/kotest-assertions/kotest-assertions-core/src/jvmMain/kotlin/io/kotest/matchers/equality/reflection.kt#L618) fails to halt recursion.

**Comment by Kantis** [comment]
Would you like to contribute a test and/or fix?

**Comment by AlexLamaison-UnlikelyAI** [comment]
This test triggers the behaviour if you step through it with a debugger but the test doesn't actually fail.  It's happily recursing into a Map and I can't reproduce what it didn't like about that before.  But it doesn't match the documented behaviour either way.

```
import io.kotest.matchers.equality.FieldsEqualityCheckConfig
import io.kotest.matchers.equality.shouldBeEqualToComparingFields
import org.junit.jupiter.api.Test

typealias MyMap = Map<String, String>

class ReproTest {

  data class Widget(val things: MyMap, val ignoreMe: String)

  @Test
  fun test() {
    val widget = Widget(mapOf("a" to "b"), ignoreMe = "blah")
    widget.shouldBeEqualToComparingFields(
        Widget(mapOf("a" to "b"), ignoreMe = "foo"),
        FieldsEqualityCheckConfig(propertiesToExclude = listOf(Widget::ignoreMe)))
  }
}
```
