### ISSUE TITLE
EventuallyConfiguration should allow capturing only the lastError

### ISSUE THREAD

**Issue by almozavr** [kotest/kotest#3889]
### Problem

- Android Studio works really badly with a long Assertion Error stacktrace (you actually could see some un-decrypted string);
- Long stacktrace increases risk of OutOfMemoryError.

### Solution
- Add to `EventuallyConfiguration` new `includeFirst: Boolean = true` option, so we could turn it off. Really, most of the time we don't care about the first error - if tests fails, we probably want to know the last one. 
- Also some optimization could be done by comparing first and last error at `buildFailureMessage` -> if those are equal, there is no need to duplicate them in a stacktrace.

**Comment by Kantis** [comment]
> * Add to `EventuallyConfiguration` new `includeFirst: Boolean = true` option, so we could turn it off. Really, most of the time we don't care about the first error - if tests fails, we probably want to know the last one.

I think this sounds like a nice addition

> * Also some optimization could be done by comparing first and last error at `buildFailureMessage` -> if those are equal, there is no need to duplicate them in a stacktrace.
Might be tricky, because even it it's the same exception type, the stack trace might be completely different? 

If you want to contribute, please do these additions as separate PRs

**Comment by kin4496** [comment]
>Also some optimization could be done by comparing first and last error at buildFailureMessage -> if those are equal, there is no need to duplicate them in a stacktrace.
Might be tricky, because even it it's the same exception type, the stack trace might be completely different?

Is it okay to just compare first error message and last error message?

**Comment by Kantis** [comment]
> Is it okay to just compare first error message and last error message?

I think we should test the type, message and type of cause (if present), just to be safe
