### ISSUE TITLE
`retry` does not retry all exceptions

### ISSUE THREAD

**Issue by martin-tarjanyi** [kotest/kotest#3928]
It looks like Kotest's [retry](https://kotest.io/docs/assertions/retry.html) block only retries assertion related errors and exceptions which **exactly** has `Exception` class. For example `RuntimeException` or `NullPointerException` are not retried. Is this intentional?

The documentation of the function says: 
> This will treat any Exception as a failure, along with [AssertionError].

Related code:
https://github.com/kotest/kotest/blob/23b0629c192e3f9aa47cb2b3bf634ed60411d343/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/Retry.kt#L81

**Comment by LeoColman** [comment]
Should probably be `instanceOf`, I think you are right.

It doesn't need to be exactly `Exception`, but the class you passed.

I agree it should be Class and Subclasses.

**Comment by pshevche** [comment]
Is there any chance we can have this released? @kin4496 prepared a PR with a change that looks pretty straightforward. This would make the retries so much more powerful.

**Comment by pshevche** [comment]
Thank you, team 🙏
