### ISSUE TITLE
`Dispatchers.setMain(coroutineContext[CoroutineDispatcher])` executes coroutines continuously

### ISSUE THREAD

**Issue by lukaszkalnik** [kotest/kotest#3932]
Kotest 5.8.1

I have an Android ViewModel, which executes a coroutine containing a `while(true)` loop. When I try to run the coroutine using `coroutineContext[CoroutineDispatcher]` available in test scope, it just runs forever without ever stopping or even respecting the `delay` inside the loop.

However, when I create a custom `StandardTestDispatcher` with a `TestCoroutineScheduler` instance, the test stops at the coroutine and waits for commands like `TestCoroutineScheduler.advanceTimeBy()` to move forward.

Example:
```kotlin
class MyViewModel : ViewModel() {

    init {
        viewModelScope.launch {
            var counter = 0
            while (true) {
                println("Loop ${counter++}")
                delay(1000)
            }
        }
    }
}

@OptIn(ExperimentalStdlibApi::class, ExperimentalCoroutinesApi::class)
class MyViewModelTest : StringSpec({
    coroutineTestScope = true

    "runs correctly" {
        // StandardTestDispatcher executes the `while(true)` loop in MyViewModel only once and continues the test
        val testScheduler = TestCoroutineScheduler()
        Dispatchers.setMain(StandardTestDispatcher(testScheduler))

        MyViewModel()
        println("test 1; MyViewModel created")
        testScheduler.advanceTimeBy(2000)
        println("test 1; after advanceTimeBy")
    }

    "never finishes" {
        // The dispatcher from coroutineContext executes the `while(true)` loop continuously and without waiting for the delay
        // The test never finishes
        Dispatchers.setMain(coroutineContext[CoroutineDispatcher]!!)

        MyViewModel()
        println("test 2 finished") // Never comes this far
    }
})
```

**Comment by Kantis** [comment]
can you try enabling `coroutineTestScope`?

```kotlin
    "never finishes".config(coroutineTestScope = true) {
        // The dispatcher from coroutineContext executes the `while(true)` loop continuously and without waiting for the delay
        // The test never finishes
        Dispatchers.setMain(coroutineContext[CoroutineDispatcher]!!)

        MyViewModel()
        println("test 2 finished") // Never comes this far
    }
```

**Comment by lukaszkalnik** [comment]
Isn't it enough that it's enabled for the whole spec, do I need to additionally enable it for every test as well?

**Comment by Kantis** [comment]
No you don't. My bad, didn't see you had it enabled already.

**Comment by lukaszkalnik** [comment]
My suspicion is, Kotest uses `UnconfinedTestDispatcher` under the hood, which executes coroutines eagerly.
Generally `StandardTestDispatcher` is recommended by the coroutines team for testing.

**Comment by Kantis** [comment]
We use the [runTest](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html) function to [launch the test](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/interceptors/TestCoroutineInterceptor.kt). According to docs there it will execute eagerly and skip delays, which seems a bit undesired if we also want to provide access to the `testCoroutineScheduler` (as documented [here](https://kotest.io/docs/framework/coroutines/test-coroutine-dispatcher.html)) to allow control of time etc...

Do you suggest we should launch the test body in a new coroutine using the `StandardTestDispatcher` instead of using `runTest`?

**Comment by lukaszkalnik** [comment]
The docs say that `runTest` skips delays, but not that it executes eagerly.

**Comment by lukaszkalnik** [comment]
At least the [migration guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#replace-runblockingtest-with-runtestunconfinedtestdispatcher) suggests that `runTest` uses `StandardTestDispatcher`.

**Comment by Kantis** [comment]
It does, but it also advances time until idle, which is never the case with your sample.. Try executing your test with `runTest` directly and you should see the same issue

**Comment by lukaszkalnik** [comment]
You're right, I could reproduce the same behavior using `runTest` in JUnit. Turns out I didn't understand how `runTest` works.

```
import org.junit.jupiter.api.Test

class MyViewModelTest {

    val testScheduler = TestCoroutineScheduler()
    val testDispatcher = StandardTestDispatcher(testScheduler)

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun `runs correctly`() = runTest {
        Dispatchers.setMain(testDispatcher)

        MyViewModel()
        println("test 1; MyViewModel created")
        this@MyViewModelTest.testScheduler.advanceTimeBy(2000)
        println("test 1; after advanceTimeBy")
    }

    @OptIn(ExperimentalStdlibApi::class, ExperimentalCoroutinesApi::class)
    @Test
    fun `never finishes`() = runTest {
        Dispatchers.setMain(coroutineContext[CoroutineDispatcher]!!)

        MyViewModel()
        println("test 2 finished") // Never finishes
    }
}
```

Thank you for your explanations!

**Comment by lukaszkalnik** [comment]
A side note: as explained in this [Slack conversation](https://kotlinlang.slack.com/archives/C1CFAFJSK/p1710418238075109?thread_ts=1710409370.270789&cid=C1CFAFJSK), actually why the test never finished was because I never canceled `viewModelScope` and the `while (true)` loop ran forever.

The solution is to inject `backgroundScope` into `MyViewModel()` for tests, to replace `viewModelScope`. Also then there's no need to call `Dispatchers.setMain()`.
