### ISSUE TITLE
kotest-assertions-ktor: Fix failure message

### ISSUE THREAD

**Issue by n0900** [kotest/kotest#3946]
**Which version of Kotest are you using**
2.0.0

This issue is a reference to https://github.com/kotest/kotest-assertions-ktor/pull/24

Fix failure message in `src/commonMain/kotlin/io/kotest/assertions/ktor/client/response.kt` haveHeader function to match
`src/jvmMain/kotlin/io/kotest/assertions/ktor/testApp.kt` haveHeader function.

See also https://github.com/kotest/kotest-assertions-ktor/pull/2

**Comment by sksamuel** [comment]
Fixed by https://github.com/kotest/kotest-assertions-ktor/pull/24
