### ISSUE TITLE
`shouldContain` always matches against `null` map value

### ISSUE THREAD

**Issue by hertzsprung** [kotest/kotest#3959]
kotest 5.8.1

The following succeeds when it should fail:
```kotlin
mapOf("foo" to "bar") shouldContain ("baz" to null)
```

due to https://github.com/kotest/kotest/blob/92091b869f3a8649cb9f6eed292222a0cd899cab/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/maps/matchers.kt#L10

**Comment by AlexCue987** [comment]
I can take care of that. Thank you for calling it out!

**Comment by AlexCue987** [comment]
the PR to fix it: https://github.com/kotest/kotest/pull/3965
