### ISSUE TITLE
Link `table_driven_testing.md` file to `sidebar_label`

### ISSUE THREAD

**Issue by dineshbhagat** [kotest/kotest#3964]
**_Non critical_**

Not working:
[table_driven_testing.md](https://github.com/kotest/kotest/blob/92091b869f3a8649cb9f6eed292222a0cd899cab/documentation/docs/assertions/table_driven_testing.md) is added under assertions section, but it is not browsable from https://kotest.io/docs/assertions.

<img width="543" alt="image" src="https://github.com/kotest/kotest/assets/3823705/2d50cab0-c67c-4f16-9f06-d2ed6f214f99">

Working:
We can search and land to the page: https://kotest.io/docs/assertions/table_driven_testing/#define-a-table-in-code

<img width="563" alt="image" src="https://github.com/kotest/kotest/assets/3823705/5eac9edf-e4c4-41f6-85c3-619f469324ff">

Is `datatesting` section appropriate for `table_driven_testing.md` ? 
I think it is similar to https://kotest.io/docs/framework/datatesting/data-driven-testing.html ?

**Comment by sksamuel** [comment]
That feature is long deprecated. Will update docs.
