### ISSUE TITLE
containExactly* assertions don't respect given verifier

### ISSUE THREAD

**Issue by AlexLamaison-UnlikelyAI** [kotest/kotest#3970]
**Which version of Kotest are you using**

Using Kotest 5.8.0.

`containExactly` and `containExactlyInAnyOrder` takes a verifier parameter, but doesn't respect it in the matching logic.  For example, the first two of these tests fail when they should pass:
```
class ContainIgnoringFieldsTest {

  data class Foo(val a: Int, val b: String)

  @Test
  fun testAnyOrder() {
    listOf(Foo(1, "a"), Foo(2, "b")) should
        containExactlyInAnyOrder(
            listOf(Foo(3, "a"), Foo(4, "b")), Equality.byReflectionIgnoringFields(Foo::a))
  }

  @Test
  fun test() {
    listOf(Foo(1, "a"), Foo(2, "b")) should
        containExactly(
            listOf(Foo(3, "a"), Foo(4, "b")), Equality.byReflectionIgnoringFields(Foo::a))
  }

  @Test
  fun testAll() {
    listOf(Foo(1, "a"), Foo(2, "b")) should
        containAll(listOf(Foo(3, "a"), Foo(4, "b")), Equality.byReflectionIgnoringFields(Foo::a))
  }
}
```

**Comment by AlexCue987** [comment]
yes - I've noticed that too: 
https://github.com/kotest/kotest/issues/3840

as a result of the discussion there, we should take out custom verifier.
What do you think?

**Comment by AlexLamaison-UnlikelyAI** [comment]
It would be better to remove the custom verifier than to leave things as they are.  But it would be really nice if there was a way to support custom verification with these assertions.  We use custom verifiers a lot because our domain objects contain randomly generated IDs and we want to exclude those for testing

**Comment by AlexCue987** [comment]
> It would be better to remove the custom verifier than to leave things as they are. But it would be really nice if there was a way to support custom verification with these assertions. We use custom verifiers a lot because our domain objects contain randomly generated IDs and we want to exclude those for testing

Makes sense. I'm working on a fix, keeping the signature as is.

**Comment by AlexCue987** [comment]
the fix only for `containExactlyInAnyOrder` - the other matcher `containExactly` clearly has issues, will be fixed separately
https://github.com/kotest/kotest/pull/3976

**Comment by AlexCue987** [comment]
fixed
