### ISSUE TITLE
In `isolationMode = InstancePerTest`, `afterSpec` is not called after mid-level containers

### ISSUE THREAD

**Issue by lukaszkalnik** [kotest/kotest#3975]
Koin 3.5.6
Kotest 5.8.1

I'm using `isolationMode = SingleInstance`. I use Koin in my prod/test code. The test specs implement `KoinTest` and add a custom Koin extension

```
class KoinKotestExtension : BeforeSpecListener, AfterSpecListener {

    override suspend fun beforeSpec(spec: Spec) {
        stopKoin()
        startKoin { modules(testModule) }
        MockProvider.register { kClass -> mockkClass(kClass) }
    }

    override suspend fun afterSpec(spec: Spec) {
        stopKoin()
    }
}
```

With `isolationMode = InstancePerTest`, when I run at least 2 test classes (specs) at once, one of them runs and the other one fails with "KoinApplication has not been started". When I run each class separately, then the tests pass.

However, when I change the `isolationMode` to `SingleInstance`, then the tests pass, regardless if I run both specs together or each of them separately.

**Comment by lukaszkalnik** [comment]
After analyzing, looks like `InstancePerTest` is not a good `isolationMode` for the use case with starting/stopping Koin anyway.
In `InstancePerTest`, when having nested containers, `afterSpec` is not always called before the next call to `beforeSpec`. That's probably why Koin is not stopped/started properly.
`beforeSpec` is called before every container/leaf test, but `afterSpec` is only called after a leaf test and a top-level container (not after mid-level containers). Then after a top-level container has finished, there are multiple `afterSpec` calls for the mid-level containers it contained.

This test:
```
class SampleTest : FreeSpec({

    isolationMode = InstancePerTest

    beforeSpec {
        println("beforeSpec")
    }

    afterSpec {
        println("afterSpec\n")
    }

    "container 1" - {
        println("container 1")
        "container 1.1" - {
            println("container 1.1")
            "leaf 1.1.1" {
                println("leaf 1.1.1")
            }
            "leaf 1.1.2" {
                println("leaf 1.1.2")
            }
        }
    }

    "container 2" -{
        println("container 2")
        "leaf 2.1" {
            println("leaf 2.1")
        }
    }
})
```

prints:

```
beforeSpec
container 1
beforeSpec
container 1
container 1.1
beforeSpec
container 1
container 1.1
leaf 1.1.1
afterSpec

beforeSpec
container 1
container 1.1
leaf 1.1.2
afterSpec

afterSpec

afterSpec

beforeSpec
container 2
beforeSpec
container 2
leaf 2.1
afterSpec

afterSpec
```

**Comment by lukaszkalnik** [comment]
Ah, I think I understand now.
`InstancePerTest` creates multiple nested specs out of containers and leafs. Then the behavior makes sense.

**Comment by OliverO2** [comment]
Thanks for sharing your experience!
