### ISSUE TITLE
Assertion JSON shouldcontainjsonkeyvalue should support filter results as value

### ISSUE THREAD

**Issue by anthraxn8b** [kotest/kotest#3980]
If using the "shouldcontainjsonkeyvalue" (https://kotest.io/docs/assertions/json/content-json-matchers.html#shouldcontainjsonkeyvalue
) function with a path containing a filter, the returned value of the json path is always a list.
It seems as if "shouldcontainjsonkeyvalue" does not expect this behavior.

Example:
DATA:
`[
{"name":"name_I_am_looking_for", "status":"HEALTHY"},
{"name":"name_I_am_NOT_looking_for", "status":"UNHEALTHY"}
]`
PATH:
`$[?(@.name=='name_I_am_looking_for')].status`
VALUE:
`["HEALTHY"]`

This value seems not to be expected and cannot be handled by the assertion.

Interesting question: How can I handle the resulting array / define an array that will match? (sorting,...)

If this functionality is already present, please tell me how :-)

UPDATE 1:

Kotest version: 5.8.1

Code used:
```
val eventuallyConfig = eventuallyConfig {
    initialDelay = 60.seconds
    duration = 30.seconds
    interval = 1.seconds
}

test("Healthchecks successful") {
    testApplication {
        environment {
            config = ApplicationConfig("application.conf")
        }
        eventually(eventuallyConfig) {
            var response = client.get("/liveness")
            var responseBodyAsText = response.bodyAsText()
            responseBodyAsText.shouldContainJsonKeyValue(
                "\$[?(@.name=='some_name_i_look_for')].status",
                "Healthy"
            )
        }
    }
}
````
(I tried with values like "Healthy" and "[\"Healthy\"]"...)

**Comment by mirageoasis** [comment]
can you tell me the version of kotest you are using?
and code you are using in this example

I assume you want to code like this

what you want
```kotlin
val data = """
    [ {"name":"name_I_am_looking_for", "status":"HEALTHY"}, {"name":"name_I_am_NOT_looking_for", "status":"UNHEALTHY"} ]
""".trimIndent()
val path = """
    ${'$'}[?(@.name=='name_I_am_looking_for')].status
""".trimIndent()

data.shouldContainJsonKeyValue("$[?(@.name=='name_I_am_looking_for')].status", "HEALTHY")
```

instead of
```kotlin
val data = """
    [ {"name":"name_I_am_looking_for", "status":"HEALTHY"}, {"name":"name_I_am_NOT_looking_for", "status":"UNHEALTHY"} ]
""".trimIndent()
val path = """
    ${'$'}[?(@.name=='name_I_am_looking_for')].status
""".trimIndent()

data.shouldContainJsonKeyValue("$[?(@.name=='name_I_am_looking_for')].status", listOf("HEALTHY"))
```

**Comment by anthraxn8b** [comment]
@mirageoasis, should I use "listOf("Healthy")? I'll try it! Give me a second...

A second later...
Well! This seems indeed to work! THX!!!
Maybe it would not be a bad idea to add such an example in the documentation - just for kotest-noobs like me... ;-)

**Comment by mirageoasis** [comment]
> @mirageoasis, should I use "listOf("Healthy")? I'll try it! Give me a second...
> 
> A second later... Well! This seems indeed to work! THX!!! Maybe it would not be a bad idea to add such an example in the documentation - just for kotest-noobs like me... ;-)

seems like your point makes sense maybe I can improve code to support single element

**Comment by mirageoasis** [comment]
@anthraxn8b 
well while I was looking around the kotest code 

implementation code was like

```kotlin
      val passed = value != null && try {
         JsonPath.parse(value).read(path, T::class.java) == t
      } catch (e: PathNotFoundException) {
         false
      } catch (e: InvalidPathException) {
         throw AssertionError("$path is not a valid JSON path")
      }
```

and this JsonPath.read only returns Java Array 

I think it would be helpful to raise Error if type other then collection comes in to prevent confusion like your case

and also fix the docs

**Comment by anthraxn8b** [comment]
@mirageoasis, do not overcomplicate it! ;-)
I just did not understand / know the right way to go.
Therefor maybe it makes sense to improve the docs.

**Comment by mirageoasis** [comment]
think fixing is unnecessary
look here
[link](https://goessner.net/articles/JsonPath/)

```kotlin
jsonData.shouldContainJsonKeyValue("\$[0].status", "HEALTHY")
```
when I wrote code like this it passed the test

which means problem lies in JsonPath query not this `shouldContainJsonKeyValue`.

**Comment by anthraxn8b** [comment]
@mirageoasis, jpath does it absolutely right. It is defined that in case a filter is used, a list of elements is returned.
