### ISSUE TITLE
Arb.list fails within edge cases in case of null values 

### ISSUE THREAD

**Issue by oliverblaha** [kotest/kotest#3981]
Test case: `Arb.list(Arb.constant(null), 1..100).edgecases().forAll { }`

Expected: Passes and generates lists of null with a variable length.
Actual: `java.util.NoSuchElementException: Collection is empty.` in collections.kt, Line 108.

Note: This passes if the lower boundary is set to `0`.

Currently, edge cases returning null will lead to the conclusion "there is no edge case for this arb" and subsequently fall back to use a random value. If this is null, too, then the particular edge case for the list is ignored. However, this is not only incorrect (either the edge case or the random value might actually be null), but causes no edge case to be left; therefore the random selection of edge cases fails with "Collection is empty."

I'll submit a PR to address this.

**Comment by oliverblaha** [comment]
Fixed in 5.9.0.

**Comment by Kantis** [comment]
Change being reverted due to performance impact. In 6.0 we will change the `Arb.edgecase(rs: RandomSource)` function to return a `Sample<A>?` which lets us handle the nested nullability problem (`null` can currently symbolize both the absence of an edgecase, and the `null` edgecase)

**Comment by oliverblaha** [comment]
That's a pity, as this will cause some tests to break again :(
Do you have any example that illustrates the performance impact?

**Comment by oliverblaha** [comment]
Ah - found the reported issue; I like addressing the nullability issue. However, how about going back to previous behavior, but with a workaround for the failing test issue?

What happened was: if the result was null, it would be treated as "there is no edge case", leading to an index exception.
We could relatively easily work around that: if the list of edge cases is empty (which then would cause the exception), just return a list with a single null value. Not perfect, but beats throwing an exception.

(Edit: obviously this shall be a temporary workaround until 6.0, assuming the latter will still take a while.)

**Comment by Kantis** [comment]
Could you draft a PR to show what you mean? I'll create a separate issue for addressing nullability

**Comment by oliverblaha** [comment]
Hi @Kantis, sorry for the delay.
If drafted a PR that shows what I meant (although it's not actually returning a list with a single null, but simply null instead).

This still passes the new regression test, as well as the tests I wrote for the original issues.
Still needs a proper solution for edge-case-nullability though.
