### ISSUE TITLE
`eventually` without customization never runs test method

### ISSUE THREAD

**Issue by bddckr** [kotest/kotest#3988]
Using Kotest `5.8.1`, the following test
```kotlin
class MyTestClass {
    @Test
    fun myTestMethod() = runTest {
        eventually {
            error("Whoops!")
        }
    }
}
```
(running in JUnit 4 - Android project)

immediately fails with
```
java.lang.AssertionError: Block failed after 0ms; attempted 0 time(s)
```

The test block is never run, and the output is really just the above, giving no further details about what went wrong.

---

I've dug into this and believe the issue is that the `duration` of the default `EventuallyConfig` is set to `INFINITE`:
https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L118
which is then added to the start time:
https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L208
which results in an overflow, I believe. The result is that the check against the end time is immediately failing
https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L245

---

While I initially wanted to raise this as a documentation issue only, I do wonder whether a `duration` of `INFINITE` should be handled specifically to mean "retry forever". Currently it basically results in "attempt not even once". To clarify: While the default value could simply be changed, I'm instead suggesting that `EventuallyControl` should be changed to allow retrying forever.

**Comment by mirageoasis** [comment]
I agree I think we have to change 
https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L245

or maybe

https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L208

can I write code this issue?

**Comment by Kantis** [comment]
@mirageoasis I think we could solve it by changing https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L208

to 
```kotlin
val end = maxOf(Long.MAX_VALUE, start + config.duration.inWholeMilliseconds) // prevent overflow
```

I think we could also reconsider using `infinite` duration for `eventually` as a default for 6.0

**Comment by mirageoasis** [comment]
> @mirageoasis I think we could solve it by changing
> 
> https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L208
> 
> to
> 
> ```kotlin
> val end = maxOf(Long.MAX_VALUE, start + config.duration.inWholeMilliseconds) // prevent overflow
> ```
> 
> I think we could also reconsider using `infinite` duration for `eventually` as a default for 6.0

well that case only end up fixing end to Long.MAX_VALUE so I don't think it will be helpful

instead I suggest using code something like this

```kotlin
fun addSafely(a: Long, b: Long): Long {
    val sum = a + b
    if (a > 0 && b > 0 && sum < 0) {
        return Long.MAX_VALUE
    } else if (a < 0 && b < 0 && sum > 0) {
        return Long.MIN_VALUE
    } else {
        return sum
    }
}

```
kind of prototype code

**Comment by Kantis** [comment]
Will `start` ever be negative?

**Comment by mirageoasis** [comment]
> Will `start` ever be negative?

if `config.duration.inWholeMilliseconds` value is 5
```kotlin
val end = maxOf(Long.MAX_VALUE, start + 5)
```
and end value will be `Long.MAX_VALUE` which I think will cause error

**Comment by mirageoasis** [comment]
> Will `start` ever be negative?

instead I suggest other solution

https://github.com/kotest/kotest/blob/4ad80702f12c2de9c938ee1909dc42f128fb6534/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/assertions/nondeterministic/eventually.kt#L245

instead fixing `hasAttemptRemaing` method

like if end value is already minus it makes while infinite loop

what about my idea?

**Comment by Kantis** [comment]
Feel free to publish a draft for further discussion :)

**Comment by mirageoasis** [comment]
@Kantis I wrote draft for this!
#4018
