### ISSUE TITLE
add the ability to generate assertions off of actual instances

### ISSUE THREAD

**Issue by AlexCue987** [kotest/kotest#3999]
I've developed a small library that generates kotest assertions and mocks off of actual data:
https://github.com/AlexCue987/kotests-mockks-generator

It does not publish to Maven yet.
Is there any appetite to add it to kotest org?

**Comment by LeoColman** [comment]
I'm not sure it should be incorporated to the core code.

It would need maintenance to something we try the best we can to avoid: bringing mocking dependencies in.

I think it should be kept as an external library. In that case we could also add it to one of external libraries in assertions

**Comment by AlexCue987** [comment]
> I'm not sure it should be incorporated to the core code.
> 
> It would need maintenance to something we try the best we can to avoid: bringing mocking dependencies in.
> 
> I think it should be kept as an external library. In that case we could also add it to one of external libraries in assertions

Fair enough. I can remove all things related to mocking elsewhere, so that this small library deals with kotest and nothing else. Would it address your concerns, @LeoColman ?

**Comment by sksamuel** [comment]
The idea to derive kotest assertion is great, but not the mocking bit.
As @LeoColman says we want to keep mocking out. 

Can you describe a bit more about how it would work without the mocking part? I read your readme, which is nicely detailed, but couldn't quite separate out the mocking from the non mocking bit.

**Comment by AlexCue987** [comment]
This version of the library does not mention any mocks at all. And its only dependency is reflection:

https://github.com/AlexCue987/kotest-generators

WDYT @sksamuel @LeoColman ?

**Comment by sksamuel** [comment]
I'll close this as I don't want to increase scope on kotest as its already a giant project.
