### ISSUE TITLE
Revert WithData to testContainer level

### ISSUE THREAD

**Issue by maxtar** [kotest/kotest#4003]
**Please describe the feature you'd like to see including any solutions in mind if you have any**
Before 5 version kotest have ability writing steps in withData section. For example:

```kotlin
"Test withData" - {
  withData(
    listOf(
      PythagTriple(3, 4, 5),
      PythagTriple(6, 8, 10),
    )
  ){ (a, b, c) ->
   "Do something" {
       ...
    }
   "Check isPythagTriple" {
       isPythagTriple(a, b, c) shouldBe true
    }
  }
}
```

But in 5.8 version this code drop error `suspend infix operator fun String.invoke(test: suspend FreeSpecTerminalScope.() -> Unit): Unit' can't be called in this context by implicit receiver. Use the explicit one if necessary`

Please revert to old behaviour. It's more usable.

**Comment by Kantis** [comment]
Duplicates https://github.com/kotest/kotest/issues/3901

**Comment by maxtar** [comment]
@Kantis is it really the same that #3901? I'm talking about withData body, but in #3901 mentioned arguments.

**Comment by Kantis** [comment]
If you make sure there's at least two arguments to `withData`, does it not work?

```kotlin
"Test withData" - {
  withData(
      PythagTriple(3, 4, 5),
      PythagTriple(6, 8, 10),
  ){ (a, b, c) ->
   "Do something" {
       ...
    }
   "Check isPythagTriple" {
       isPythagTriple(a, b, c) shouldBe true
    }
  }
}
```

**Comment by maxtar** [comment]
Nope. The same error
