### ISSUE TITLE
Performance Degradation in 5.9.0 compared to 5.8.1

### ISSUE THREAD

**Issue by panphg** [kotest/kotest#4016]
### Description

Version 5.9.0 has introduced a performance degradation compared to version 5.8.1 when using a generator for a data structure with nested lists.

I have set up a small repository that reproduces this issue: https://github.com/panphg/kotest-performance
It contains a small Kotlin project with a single test [PerformanceTest](https://github.com/panphg/kotest-performance/blob/main/src/test/kotlin/PerformanceTest.kt). Using the gradle commands below, the test can be run with Kotest 5.8.1 and 5.9.0.

When run with Kotest 5.8.1, the test runs in a few seconds. When run with 5.9.0, the test runs for a long time (minutes, if not hours).

To run the test with Kotest 5.8.1, execute:
```bash
./gradlew test -Dversion=5.8.1
```

To run the test with Kotest 5.9.0, execute:
```bash
./gradlew test -Dversion=5.9.0
```
### Expected Behaviour
The test should finish in seconds when run with 5.9.0, as it does when run with 5.8.1.

**Comment by Kantis** [comment]
Possibly related to https://github.com/kotest/kotest/pull/3982. I think it was the only change related to property testing in 5.9

**Comment by panphg** [comment]
This might be the culprit. [Replacing](https://github.com/kotest/kotest/pull/3982/files#diff-07978b8f35a89840ce619edfba9841ebde2bd601673e949b9261e7e41c60a1d2R99) `gen.edgecase(rs)` with `gen.edgecases()` increased the amount of generated values by a factor of 100, the default value for the argument iterations. And calling `gen.edgecases()` twice and then twice again a couple of lines below certainly didn't help either. Maybe using `gen.edgecases(iterations = 1)` instead already fixes the performance issues, but I'm not sure about the implications of a change like this.

Our build uses lots of generators and went from taking about 6min with Kotest 5.8.1 to timing out after more than 2 hours with 5.9.0.

**Comment by Kantis** [comment]
@myuwono @sksamuel I think the correct thing to do would be to add a wrapper around the [edgecase function's](https://github.com/kotest/kotest/blob/19ce4d3b4712ed04c23d9aad7ce56c064caaa503/kotest-property/src/commonMain/kotlin/io/kotest/property/Gen.kt#L103) result. E.g. it should return either `Edgecase<A>?` or simply a `Sample<A>?`.That way we can distinguish between the lack of an edgecase, i.e.`null` result, vs the null edgecase

Should we revert #3982 for now and try to address this with a breaking change in 6.0?

**Comment by sksamuel** [comment]
Yeah I think so. We can't have the poor performance. 6.0 should be the next release once kotlin 2.0 is stable.

**Comment by myuwono** [comment]
Yeah I agree, the current edgecase function is problematic due to the nested nullability problem as you rightly pointed out.. Sam and I did discuss about fixing the return type in the past I believe it will be a good idea.

**Comment by OliverO2** [comment]
> 6.0 should be the next release once kotlin 2.0 is stable.

My testing with Kotlin 2.0 release candidates suggests that Kotest 5.9.0 will most probably work just nicely with Kotlin 2.0.
