### ISSUE TITLE
afterSpec but not beforeSpec is called when all tests are filtered out

### ISSUE THREAD

**Issue by ulrikrasmussen** [kotest/kotest#4022]
**Which version of Kotest are you using**
5.8.0

**Description**
Consider the following test:
```kotlin
class ListenersTest : StringSpec({
    beforeSpec { println("beforeSpec") }
    afterSpec { println("afterSpec") }
    beforeEach { println("beforeEach") }
    afterEach { println("afterEach") }

    "!test" {}
})
```

When I run `ListenersTest`, it prints only
```
afterSpec
```

**Expected behavior**
I would expect that it either prints nothing or prints
```
beforeSpec
afterSpec
```

**Comment by Kantis** [comment]
I agree, it's inconsistent. Ideally I think it shouldn't run neither `beforeSpec` nor `afterSpec`.

**Comment by Kantis** [comment]
Related history https://github.com/kotest/kotest/issues/3534
