### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.kotest.core.test.Description$Test io.kotest.core.test.TestCase.getDescription()' in kotest-extensions-koin

### ISSUE THREAD

**Issue by iirekm** [kotest/kotest#4028]
I followed the instructions at: https://kotest.io/docs/extensions/koin.html

I get the error as in the title.

Gradle:
```
implementation("io.insert-koin:koin-test:3.5.6")
implementation("io.kotest:kotest-extensions-koin:4.4.3") {
    exclude(group = "org.koin")
}
```

Either kotest-extensions-koin doesn't work with any recent kotest, or the documentation is not up to date.

**Comment by iirekm** [comment]
Temporary workaround: copy the `KoinListener.kt` to own project, and replace `description.isRootTest()` with `isRootTest()`

**Comment by Kantis** [comment]
You're using wrong dependency. Change to `io.kotest.extensions:kotest-extensions-koin:1.3.0`
