### ISSUE TITLE
'withEnvironment' must be used within leaf

### ISSUE THREAD

**Issue by sgc109** [kotest/kotest#4036]
kotest 5.5.5
JVM 11
Using Gradle for 'Build and run' and 'Run tests' on Gradle Projects configurations in IntelliJ.

I'm using `withEnvironment` wrapping `test` block without `context` container in FunSpec.
Following test fails.
```kotlin
class TestClass : FunSpec() {
  init {
      withEnvironment("key", "value") {
          test("test") {
              System.getenv("key").shouldNotBeNull()
          }
      }
  }
}
```

**Comment by sgc109** [comment]
Oh I've realized that I should use `withEnvironment {}` block inside of the leaf. 
According to the official documentation, it seems like there is no test block between `withEnvironment` and the actual code reading the environment variable, but I feel it's a little bit ambiguous.
What about extending the functionality of `withEnvironment {}` that can wrap the test block, or clarify more the usage example on the official documentation?

**Comment by sksamuel** [comment]
I've clarified the docs. Thanks for pointing it out.
