### ISSUE TITLE
Power-assert for better failure message formatting

### ISSUE THREAD

**Issue by kirillzh** [kotest/kotest#4044]
[Power assert](https://kotlinlang.org/docs/power-assert.html) is a Kotlin compiler plugin for printing nicely diagrammed failure messages in tests. From the lib's readme:

Given following code:
```kotlin
val hello = "Hello"
assert(hello.length == "World".substring(1, 4).length)
```

Normally the assertion message would look like:
```kotlin
java.lang.AssertionError: Assertion failed
	at <stacktrace>
```

With [kotlin-power-assert](https://github.com/bnorm/kotlin-power-assert/) included, the error message for the previous example will be transformed:
```kotlin
java.lang.AssertionError: Incorrect length
assert(hello.length == "World".substring(1, 4).length)
       |     |      |          |               |
       |     |      |          |               3
       |     |      |          orl
       |     |      false
       |     5
       Hello
	at <stacktrace>
```

Use case in relation to kotest: https://github.com/bnorm/kotlin-power-assert/issues/65#issuecomment-1582065946

YT talk: https://www.youtube.com/live/G8pS1FzZlhk?si=Wt-QlGxxIuX83ZOh&t=17600

**Comment by AlexCue987** [comment]
Can you clarify what changes in kotest are you requesting?

**Comment by OliverO2** [comment]
@AlexCue987 There is already an ongoing discussion on [kotlinlang Slack](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1717034415006099?thread_ts=1707420378.970499&cid=CT0G9SD7Z). We'll have to look at integrating this with the Clue infrastructure and look at how to best combine power-assert output with existing matchers.

**Comment by sksamuel** [comment]
I've got it working out of the box. We only need to make a small change to kotest to support it.
https://github.com/kotest/kotest/discussions/3952
