### ISSUE TITLE
Documentation: System properties must be configured in test tasks (e.g. Kotest-specific test filtering)

### ISSUE THREAD

**Issue by writtmeyer** [kotest/kotest#4061]
**Which version of Kotest are you using**
`kotest 5.9.0`

Use the [kotest sample kmp project](https://github.com/kotest/kotest-examples-multiplatform) and change the toml file to the newest versions:
```
[versions]
kotlin = "2.0.0"
coroutines = "1.8.1"
kotest = "5.9.0"
```

Then run `./gradlew check -Dkotest.filter.specs='io.kotest.examples.mpp.data*'` on the command line.

**Expected:**
Only test in io.kotest.examples.mpp.data are executed.

**Actual:**
All tests are executed.

**Possible workaround with limitations:**
Use the normal gradle filtering `./gradlew :jvmTest --tests 'io.kotest.examples.mpp.data*'` - which as the kotest documentation states itself is clumsy. Quoting the [docs](https://kotest.io/docs/framework/conditional/conditional-tests-with-gradle.html): "To avoid the limitations with Gradle's `--tests` support, Kotest offers its own flags which are provided via system properties or environment variables."

**Comment by OliverO2** [comment]
IIRC, passing system properties to the main Gradle task usually does not work with tests. Gradle forks another JVM for the test runner and fails to pass system properties.

If you add the following line [right here](https://github.com/kotest/kotest-examples-multiplatform/blob/d10048811f75b1797e78731816a10e9f10fc74fd/build.gradle.kts#L84-L85):

```kotlin
    systemProperty("kotest.filter.specs", "io.kotest.examples.mpp.data*")
```

Does that work?

**Comment by writtmeyer** [comment]
You're right. That works. Also actually export the environment variable. So this is more of a gradle issue then.
Nevertheless [your docs](https://kotest.io/docs/framework/conditional/conditional-tests-with-gradle.html) probably should be updated.

**Comment by OliverO2** [comment]
> Nevertheless [your docs](https://kotest.io/docs/framework/conditional/conditional-tests-with-gradle.html) probably should be updated.

Agreed.
