### ISSUE TITLE
Cannot use provided arbs for properties as is described in documentation

### ISSUE THREAD

**Issue by jedesroches** [kotest/kotest#4064]
Hello and thank you for your work on this great framework! The following problem has been found using kotest 5.9.

I am trying to use the capability described in [the provided arbs docs](https://kotest.io/docs/proptest/reflective-arbs.html#provided-arbs) and the compiler is unhappy, saying no `bind` function matches, and in particular none of the three reflective functions match

```kotlin
public inline fun <reified T : Any> Arb.Companion.bind(providedArbs: Map<KClass<*>, Arb<*>> = ...): Arb<TypeVariable(T)> defined in io.kotest.property.arbitrary
public fun <T : Any> Arb.Companion.bind(providedArbs: Map<KClass<*>, Arb<*>>, kclass: KClass<TypeVariable(T)>): Arb<TypeVariable(T)> defined in io.kotest.property.arbitrary
public fun <T : Any> Arb.Companion.bind(providedArbs: Map<KClass<*>, Arb<*>>, kclass: KClass<TypeVariable(T)>, type: KType): Arb<TypeVariable(T)> defined in io.kotest.property.arbitrary
```

The minimal reproducible example is the one in the docs, which will not compile:

```kotlin
data class User(
  val name: String,
  val password: String,
  val age: Int,
)

// in some spec
context("Some tests with an arbitrary user") {
  checkAll(Arb.bind<User> {
    bind(User::name to Arb.string(1..10))
    bind(User::password to Arb.string(24..80)) // binds a specific property to an arb
    bind(Int::class to Arb.int(0..100))  // binds a type to an arb
  }) { user ->
    // ...
  }
}
```

As a workaround, one can use manual `Arbs` and data class `copy` mechanisms, but it is a bit cumbersome, and the docs should hopefully reflect if this is possible or not.

Please ask any questions if you need more information :)

**Comment by Kantis** [comment]
@jedesroches I just tried to reproduce the problem and it looks like it's accepted in my project. Can you ensure you have proper imports added etc?

<img width="1021" alt="image" src="https://github.com/kotest/kotest/assets/316857/7ec05165-0723-492d-b100-1774d8eef53d">

If you can reproduce the error, please share a small sample

**Comment by jedesroches** [comment]
Absolutely my fault, we were using kotest version 5.8 in the project and this was added in 5.9. Thank you for your time and sorry for not checking that before ><

**Comment by Kantis** [comment]
No worries, it happens to everyone 😃  Glad it's working
