### ISSUE TITLE
Missing Module in 5.9.1

### ISSUE THREAD

**Issue by robertfmurdock** [kotest/kotest#4065]
Looks like some of the native modules didn't get published correctly. Seeing this error:

`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':libraries:kotest-example:compileKotlinIosX64'.
> Could not resolve all dependencies for configuration ':libraries:kotest-example:kotlinCompilerPluginClasspathIosX64Main'.
21 actionable tasks: 6 executed, 15 up-to-date

Publishing build scan...
   > Could not find io.kotest:kotest-framework-multiplatform-plugin-embeddable-compiler:5.9.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/kotest/kotest-framework-multiplatform-plugin-embeddable-compiler/5.9.1/kotest-framework-multiplatform-plugin-embeddable-compiler-5.9.1.pom
     Required by:
         project :libraries:kotest-example
`

**Comment by Kantis** [comment]
Only the gradle plugin has been successfully published so far. Having some issues with Maven central, but will hopefully be ready soon. 🤞🏼

**Comment by Kantis** [comment]
Should be ready now
