### ISSUE TITLE
Reimplement or remove buildConfigDocs task

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#4066]
`buildConfigDocs` was added 4 years ago, but it is non-functional and not properly configured.

https://github.com/kotest/kotest/blob/7b4fe302109915a9c3d465ab35af82cacb1aefce/kotest-framework/kotest-framework-api/build.gradle.kts#L43-L49

- It is supposed to update `config_props.md` files, but it's not triggered by anything.
  (Replace `mustRunAfter()` with `dependsOn()`)
- It does work in the configuration phase.
  (Add a `doLast {}` block)
- Should properly register Task inputs/outputs.

It was commented out as part of https://github.com/kotest/kotest/pull/4062#discussion_r1627318862

It should probably just be deleted.

**Comment by Kantis** [comment]
I'd say most users refer to the cut docs for the current version. These are generated as part of minor/major releases using [this script](https://github.com/kotest/kotest/blob/master/documentation/cut-docs.sh). Perhaps it makes more sense to update `config_props.md` automatically as part of that?

**Comment by aSemy** [comment]
Yes, that makes sense. But, now that I think about it, it would probably make more sense to generate a Dokka HTML site?

**Comment by sksamuel** [comment]
If it's been broken for 4 years I'll just remove it. We can update manually, which might not be perfect, but can't be worse than a no-op script :)
