### ISSUE TITLE
Help using reflective provided arbs

### ISSUE THREAD

**Issue by jedesroches** [kotest/kotest#4094]
Hello again and thank you for this amazing library! I am trying to use the [provided arbs](https://kotest.io/docs/proptest/reflective-arbs.html#provided-arbs) and must be doing something wrong, because the generated cases do not correspond to what I specify. Here are some examples that I have found surprising:

1. Using an enum and Arb.constant

```kotlin
enum class Liveness { Alive, Dead }
data class Cell(val liveness: Liveness)

describe("A live cell") {
  checkAll(Arb.bind<Cell> {
    Cell::liveness to Arb.constant(Liveness.Alive)
  }) { cell ->
    cell.liveness.shouldBe(Liveness.Alive)
  }
}
```

This fails, generating random samples amongst Alive and Dead (e.g., for 5 cases, `Cell(liveness=Dead), Cell(liveness=Dead), Cell(liveness=Alive), Cell(liveness=Alive), Cell(liveness=Alive)`). This also fails if I change the key in provided arbs from `Cell::liveness` to `Liveness::class`.

I have also tried a simpler example without the enum class to try and figure out where the issue came from, and found that

```kotlin
data class Foo(val bar: String)
describe("Foo fails") {
  checkAll(Arb.bind<Foo> {
    Foo::bar to Arb.string(1, Codepoints.az())
  }) { foo ->
    foo.bar.shouldHaveLength(1)
}
```

also fails. Printing the samples gives some nicely random strings, like `Foo(bar=;!&D7Hi8.yzdDlwf*v7FWUuMp,"_Sy~=DNH-M$nmOZR)wN``XQ)`.

What have I missed ? I have tried looking at the code for `bind` but my kotlin is not fluent enough yet to figure out what is wrong... Thank you for your time and any help you can give!

**Comment by Kantis** [comment]
@jedesroches you need to use the `bind` function, currently you're just defining a pair that's not used for anything.

E.g.

```kotlin
enum class Liveness { Alive, Dead }
data class Cell(val liveness: Liveness)

describe("A live cell") {
  checkAll(Arb.bind<Cell> {
    bind(Cell::liveness to Arb.constant(Liveness.Alive))
  }) { cell ->
    cell.liveness.shouldBe(Liveness.Alive)
  }
}
```

**Comment by jedesroches** [comment]
Thank you!
