### ISSUE TITLE
Test Case Config example shows deprecated symbols

### ISSUE THREAD

**Issue by OliverO2** [kotest/kotest#4108]
https://kotest.io/docs/framework/testcaseconfig.html documents the following deprecated symbols:
* `val defaultTestConfig`
* `fun defaultTestCaseConfig()`
* `class TestCaseConfig`

Also, for `val defaultTestConfig`, the deprecation hint is not useful:
```
These settings should be specified individually to provide finer grain control
```

It remains unclear what to use instead.

**Comment by aSemy** [comment]
Related: https://github.com/kotest/kotest/issues/4066
