### ISSUE TITLE
Publish Kotest Multiplatform Gradle Plugin to Maven Central

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#4131]
`io.kotest.multiplatform` is published to GPP https://plugins.gradle.org/plugin/io.kotest.multiplatform, but not Maven Central https://search.maven.org/search?q=kotest%20gradle.

#### Motivation

I want to use the latest version of `io.kotest.multiplatform` for dogfooding. However, GPP doesn't host snapshot versions, so it's not possible.

Publishing to Maven Central is quite popular. Maven Central tends to be slightly more stable and reliable than GPP.

#### Suggestion

This should be easy to implement: apply `kotest-publishing-conventions` to `kotest-framework-multiplatform-plugin-gradle` subproject.

**Comment by OliverO2** [comment]
Yep. Would also fix #4012, right?

**Comment by aSemy** [comment]
Yes! This issue is a dupe of #4012
