### ISSUE TITLE
Test Names aren't used Verbatim

### ISSUE THREAD

**Issue by Fleshgrinder** [kotest/kotest#4137]
I'm using the latest version of Kotest and am noticing that test names aren't used verbatim. Maybe there's a technical limitation here, but the string usage suggests that tests can be named anything, whereas in reality they cannot.

<img width="782" alt="Shows how test names are being altered by Kotest." src="https://github.com/kotest/kotest/assets/1059453/79ba7ce8-2263-4038-a821-33977a2499d0">

```kotlin
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class TestNaming : FunSpec({
    test("what about parenthesis ()") { true shouldBe true }
    test("other stuff 🙈 {} [] -–— works fine") { true shouldBe true }

    context("prefix") {
        test("prefixes - the context eats the prefix") { true shouldBe true }
    }
})
```

At least for me it's unexpected that parenthesis are being swallowed. Especially because they're very useful to disambiguate different overloads. Even more unexpected is that contexts eats common prefixes from the tests that are nested within.

Like the title states, I would expect that test names are taken verbatim without any alterations, if possible. If not possible the Kotest plugin should warn about problematic codepoints and include an explanation (or a link to an explanation) why they cannot be used.

**Comment by sksamuel** [comment]
It's a bug in intellij. But kotest should filter them out or something as a workaround.
