### ISSUE TITLE
Add locale Arb for jdk17

### ISSUE THREAD

**Issue by ravenblackdusk** [kotest/kotest#4154]
Apparently in jdk17 some locales have changed and java forcefully converts the old locales to the new ISO, which make my tests fail. As a workaround I'm doing `Arb.locale().filterNot { it.startsWith("in") || it.startsWith("ji") || it.startsWith("iw") || it.startsWith("no") }`
Maybe we could add another locales function to `Arb` that contains only jdk17 compliant locales.

**Comment by sksamuel** [comment]
Would be it sufficient to just filter out ones that are not in jdk17?

**Comment by ravenblackdusk** [comment]
@sksamuel for my use case its fine, however note that Hebrew and Yiddish are right to left languages and might be of special interest.
