### ISSUE TITLE
Ability to Group Tests Without Affecting Execution Order

### ISSUE THREAD

**Issue by Fleshgrinder** [kotest/kotest#4162]
We have the ability to group tests in a container (e.g., `FunSpec.context`). However, doing so forces the tests to be executed sequentially. It would be nice to have the ability to group tests without affecting their execution order, solely for source code organization. Sticking with `FunSpec` it could just be named `group` and act as a prefix provider for the test names grouped together, and another execution point in the gutter of the editor.

```kotlin
class Some {
    fun f() {}
    fun g() {}
}

class SomeTest : FunSpec({ // gutter ▶️
    group("e") {           // gutter ▶️
        test("a") {}       // gutter ▶️
        test("b") {}       // gutter ▶️
    }

    group("f") {           // gutter ▶️
        test("a") {}       // gutter ▶️
        test("b") {}       // gutter ▶️
    }

    group("g") {           // gutter ▶️
        test("a") {}       // gutter ▶️
        test("b") {}       // gutter ▶️
    }
})
```

`e a`, `e b`, `f a`, `f b`, `g a`, and `g b` are executed in any order as configured for the entire project or spec, just as if they were added as individual tests to the root spec. The grouping isn't tied to any symbols (e.g., the `e` group), they're just test name prefixes that can be chosen freely.

I chose `a` and `b` for all tests, because currently this exact code with a custom `group` function doesn't work with the IntelliJ plugin, because it complains that the there are duplicate tests in the spec.

**Comment by AlexCue987** [comment]
IMO tests should execute in any order; they should not depend on or be affected by any side effects of other tests. To accomplish that we can use isolation: `override fun isolationMode() = IsolationMode.InstancePerTest` as well as `beforeTest/afterTest` methods.

**Comment by Fleshgrinder** [comment]
I think you misread the request or commented on the wrong issue. The idea of the grouping is exactly that the tests execute in any order, unlike it's the case today with contexts that force sequential execution.

**Comment by AlexCue987** [comment]
responding to the following in the original post: "It would be nice to have the ability to group tests without affecting their execution order" - IMO the order in which tests are executed should not be a concern at all. because tests should not depend on side effects from other tests. what am I missing?

**Comment by Fleshgrinder** [comment]
Context affects the execution order by forcing tests to be executed sequentially. The ask for grouping is to **NOT** do that, but leave the order to whatever was configured globally. Be it the sequential default, random, or whatever.

Context is nice whenever you need control over order, but most of the time, the order doesn't matter. Having random execution with maximum parallel/concurrent execution results in better tests and a suite that executes faster overall.

However, visually grouping of related tests in source code would still be nice. Hence, grouping.

**Comment by sksamuel** [comment]
The difficulty in doing this is that the nested tests are not discovered until the outer scope is executed. Then it's just much easier to run them in place. The current ordering rules only apply to top level tests anyway, as those are known statically.

The alternative would be to add them to another runner, and have that just executed them in whatever order they are added. But since we don't care about the order, enforcing a "discovery" order might be a lot of work with edge cases for not much benefit ?

**Comment by AlexCue987** [comment]
> The difficulty in doing this is that the nested tests are not discovered until the outer scope is executed. Then it's just much easier to run them in place. The current ordering rules only apply to top level tests anyway, as those are known statically.
> 
> The alternative would be to add them to another runner, and have that just executed them in whatever order they are added. But since we don't care about the order, enforcing a "discovery" order might be a lot of work with edge cases for not much benefit ?

I have a different idea - does kotest allow to execute all tests in a class in every possible order, all the permutations, to expose side effects and tests depending on order of execution? If not, should we add this feature?

**Comment by Fleshgrinder** [comment]
Whenever `test` is called, it registers the test in the `Spec`. I was thinking more along the lines of overloading that with `group` and adding the prefix, and then calling `test` (which might be that of another group or the spec). Basically, keeping it static; could be desugared with a compiler plugin too.

Of course, having actual grouping like we get it with context in the output would be even nicer than prefixing. Don't know if that's possible...

Everything else that's needed to make this work should be in the IntelliJ plugin. Clicking on the `group` gutter icon would use a prefix test filter (e.g., `group("foo")` in `MyTest` executes `MyTest.foo *`) and the uniqueness inspection needs to take surrounding groupings into account. 

It's really just about source code layout and ergonomic execution. I wouldn't want any runtime impact.

**Comment by sksamuel** [comment]
I think I understand better now. A grouping could just immediately run the nested code to embed the tests. I think that would be possible to work. However, it's going to add _yet another set of options_ to an already complex DSL. In hindsight. 

To support this we'd also need to update the intellij plugin, and all the other places the structure is used. We'd also need to make sure it works for the different test isolation modes. And all that code is already very complicated. I'm going to close this as won't do as I don't think the complexity warrants the benefit. You can always just split test by class which is the common grouping on the JVM.

Thank you for taking the time to write this up though.

**Comment by Fleshgrinder** [comment]
Bummer, but thanks for considering.
