### ISSUE TITLE
io.kotest.assertions.fail() doesn't cooperate with assertSoftly

### ISSUE THREAD

**Issue by rafagapa** [kotest/kotest#4170]
Kotest version: 5.9.1

I was surprised to see that `assertSoftly` won't collect other assertion errors if `fail()` throws an error.

E.g.:
```
import io.kotest.assertions.assertSoftly
import io.kotest.assertions.fail
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class Test : StringSpec ({

    fun myCustomCheck(): Boolean = true

    "There should be two errors collected" {
        assertSoftly {
            if (myCustomCheck()) {
                fail("should fail")
            }
            1 shouldBe 2
        }
    }
})
```
would end up with:
```
should fail
```
whereas I would expect something like:
```
The following 2 assertions failed:
1) should fail
2) expected:<2> but was:<1>
```

I find using `fail()` very convenient for custom checks that not necessarily are good candidates for custom matchers.

**Comment by AlexCue987** [comment]
I got it

**Comment by AlexCue987** [comment]
In fact, this is working as designed - `fail()` is not supposed to respect the context of `assertSoftly`

**Comment by rafagapa** [comment]
Thanks a lot for looking into it.
How do I know that it "is not supposed to respect the context of `assertSoftly`", is it in a documentation or is there another discussion that I'm not aware of?

**Comment by AlexCue987** [comment]
> Thanks a lot for looking into it. How do I know that it "is not supposed to respect the context of `assertSoftly`", is it in a documentation or is there another discussion that I'm not aware of?

Fair enough - I'll make sure the docs reflect this, so reopening this thing.

**Comment by rafagapa** [comment]
Aahh, I've just noticed the return type of `fail()` is `Nothing`. It's supposed to terminate immediately no matter if soft assertions are enabled or not. Quite useful for cases where further checks make little sense if previous ones failed. It makes a lot of sense to me now.

**Comment by sksamuel** [comment]
@AlexCue987 can you add a note to the assertSoftly page ?

**Comment by AlexCue987** [comment]
> @AlexCue987 can you add a note to the assertSoftly page ?

sure thing

**Comment by AlexCue987** [comment]
> @AlexCue987 can you add a note to the assertSoftly page ?

https://github.com/kotest/kotest/pull/4267/files

**Comment by AlexCue987** [comment]
closing, behavior documented
