### ISSUE TITLE
Spec concurrency seems to mess up with containers

### ISSUE THREAD

**Issue by rafagapa** [kotest/kotest#4172]
Kotest version: 5.9.1

I've been experimenting with `concurrency` (which is a great feature BTW) and I have noticed that it messes up with the parents (containers) of tests:
```
import io.kotest.core.spec.style.FreeSpec

@OptIn(io.kotest.common.ExperimentalKotest::class)
class Test : FreeSpec ({
    concurrency = 3
    "group" - {
        "A" {}
        "B" {}
    }
    "C" {}
})
```
results in hierarchy:
![image](https://github.com/kotest/kotest/assets/30666431/8283f924-f039-4557-ae28-58f4e319c799)
Without altering `concurrency`, the hierarchy is as expected:
![image](https://github.com/kotest/kotest/assets/30666431/997b1423-8edb-4431-b8e2-a87b5ec3ef02)

**Comment by sksamuel** [comment]
I am unable to duplicate this. Does it happen frequently or just very rarely?

**Comment by rafagapa** [comment]
I'm sorry for bothering You. It must have been a transient problem with Idea, probably? I cannot reproduce it anymore either :see_no_evil:

**Comment by OliverO2** [comment]
Closing for now. We can reopen if required.
