### ISSUE TITLE
Intercept disabled tests

### ISSUE THREAD

**Issue by kozlov-aa** [kotest/kotest#4179]
I would like to add to the report a list of tests that were disabled.

Is it possible to write an extension that intercepts disabled tests?

**BeforeEachListener** or **BeforeTestListener** callback won't be invoked if test is disabled.

**Comment by sksamuel** [comment]
You can write a TestInterceptor. Would that do what you want ?

**Comment by kozlov-aa** [comment]
@sksamuel  I tried to create a listener for disabled tests in #4210
