### ISSUE TITLE
IntelliJ plugin incompatible with the K2 compiler

### ISSUE THREAD

**Issue by strindberg** [kotest/kotest#4261]
**Which version of Kotest are you using**
5.8.1

When activating the (beta) K2 mode in a recent version of IntelliJ (2024.2), the Kotest plugin is de-activated with the message: "Plugin is incompatible with the Kotlin plugin in K2 mode".

It would of course be nice to be able to use the plugin in K2 mode, which will be the default within a couple of months.

**Comment by sksamuel** [comment]
Kotest 6.0 (which we're working on) will be 2.0+ only.

**Comment by osoykan** [comment]
@sksamuel Will there be a snapshot or RC version before rolling out the 6.0? I would like to participate the early usage of it.

**Comment by rzukowski-equinix** [comment]
> Kotest 6.0 (which we're working on) will be 2.0+ only.

Hello, when the 6.0 is planned to be released?

**Comment by cloudshiftchris** [comment]
IntelliJ 2024.2 has landed, with beta support for K2 mode - which unfortunately latest kotest plugin is incompatible with.

**Comment by sksamuel** [comment]
tracking this over here: https://github.com/kotest/kotest/issues/5366

**Comment by sschuberth** [comment]
Here's the link to the migration guide: https://blog.jetbrains.com/platform/2024/09/migrating-your-kotlin-plugin-to-k2-mode/

**Comment by sksamuel** [comment]
We can close this out now the K2 plugin has been out for a while.
