### ISSUE TITLE
Property testing: Support named generators

### ISSUE THREAD

**Issue by edgao** [kotest/kotest#4279]
Currently (afaict) there's no way to assign a name to a generator. When a test fails, you get some output like this:
```
Property test failed for inputs

0) 0
1) 0
```

It would be cool to be able to write something like `Arb.int(0..5, name = "row")`, and get output like this:
```
Property test failed for inputs

0) row = 0
1) column = 0
```

(I'm using junit as my test runner, maybe this works out of the box with the kotest runner?)

(I'm also happy to take a stab at implementing this, if I can get a pointer at the right file(s) to modify. Seems like [this](https://github.com/kotest/kotest/blob/97c97d7a78be35f57ecaa085dbfa2e4b688f64ea/kotest-property/src/commonMain/kotlin/io/kotest/property/internal/test.kt#L91) might be a good starting point?)

**Comment by breader124** [comment]
Hey, I'll try to work on this enhancement

**Comment by sksamuel** [comment]
The new property test framework in 6.0 supports this, so will mark as closed.
When 6.0 is released, the docs will show how it works.
