### ISSUE TITLE
Exhaustive property testing: Support skipping N test cases

### ISSUE THREAD

**Issue by edgao** [kotest/kotest#4280]
(I might just not be using kotest-property correctly - very possible that pebkac!)

When running an exhaustive property test via forAll, it seems tricky to debug a failed test case. For example:
```kotlin
forAll(
  Exhaustive.int(0..5),
  Exhaustive.int(0..5),
) { row, column ->
  // do something that fails on row=3, column=3
}
```

Other than creating a new test for specifically the failed case, I don't think there's a great way to run it in isolation? Something like this would be nice (since kotest already prints out a nice `Property failed after 18 attempts` message):
```kotlin
forAll(
  PropTestConfig(skipExhaustiveIterations=18),
  ...
) {...}
```

(also happy to take a stab at implementing this. Seems like [proptest.kt](https://github.com/kotest/kotest/blob/master/kotest-property/src/commonMain/kotlin/io/kotest/property/internal/proptest.kt) is the right file to modify?)

**Comment by sksamuel** [comment]
Have you tried using the seed ?

**Comment by edgao** [comment]
hm, I thought I tried that and it still executed all the previous test cases. can try again next week

**Comment by edgao** [comment]
am I using the seed wrongly? My process was:

Added `testImplementation 'io.kotest:kotest-property:5.9.1'` to my build.gradle, then ran a test like this:
```kotlin
    // not sure if it matters: this is junit's annotation org.junit.jupiter.api.Test
    @Test
    fun demo() {
        runBlocking {
            forAll(
                Exhaustive.ints(0..4),
                Exhaustive.ints(0..4),
            ) { row, column ->
                logger.info { "Running with $row, $column" }
                row != 3 || column != 3
            }
        }
    }
```
Which failed as expected:
```
    java.lang.AssertionError: Property failed after 19 attempts
    Repeat this test by using seed 41085330395708674
    Caused by AssertionFailedError: expected:<true> but was:<false>
```

So I plugged in the seed and reran:
```kotlin
    // intellij shows a warning without this annotation?
    @OptIn(ExperimentalKotest::class)
    @Test
    fun demo() {
        runBlocking {
            forAll(
                PropTestConfig(seed = 41085330395708674),
                Exhaustive.ints(0..4),
                Exhaustive.ints(0..4),
            ) { row, column ->
                logger.info { "Running with $row, $column" }
                row != 3 || column != 3
            }
        }
    }
```

But it still ran through all 19 iterations. I'd like to _only_ run the failed iteration (e.g. so that I can set a breakpoint directly in the relevant code, without needing to fiddle with conditional breakpoints).

(also, after further thought - isn't the purpose of Exhaustive that it _doesn't randomize in any way? I.e. the seed is expected to do nothing?)

**Comment by sksamuel** [comment]
I understand. What we need is like a skipToN(17) option
