### ISSUE TITLE
-0.0 shouldBe 0.0 should not throw AssertionFailedError

### ISSUE THREAD

**Issue by flemming-n-larsen** [kotest/kotest#4319]
**Which version of Kotest are you using**
5.9.1

**Description**
I am using kotest to check the results of calculations with doubles.
Sometimes the result is -0.0. When I compare it against 0.0 like this:
```
val result = -0.0 // -0.0 is the result of calling some mathematical function but set to -0.0 to force the issue.
result shouldBe 0.0
```
Simplified, this test fails:
```
-0.0 shouldBe 0.0
```
But it should pass.

It seems that kotest does not regard -0.0 as being the same as 0.0 with the `shouldBe` method (and perhaps other similar methods) even though -0.0 and 0.0 are considered equals in Kotlin, i.e. `-0.0 == 0.0` is `true` (following the IEEE 754 standard).

**Comment by AlexCue987** [comment]
Same. TY for noticing. Needs fixing.
