### ISSUE TITLE
Review web docs / Remove obsolete kotest-assertions-collections

### ISSUE THREAD

**Issue by okarmazin** [kotest/kotest#4353]
Hello, as I understand collection assertions are now part of core. Indeed, the artifact cannot be resolved at version 5.9.0.

[The web documentation](https://kotest.io/docs/assertions/matchers) should be reviewed and updated. I don't know if `kotest-assertions-collections` is the only obsolete package there. It misled me into thinking I needed the collections artifact.

**Comment by AlexCue987** [comment]
makes sense, feel free to fix it, good luck
