### ISSUE TITLE
Adopt uniform wording and textual representation of ranges/intervals

### ISSUE THREAD

**Issue by okarmazin** [kotest/kotest#4362]
Matcher messages and KDocs containing ranges are all over the place. Round parens are used for representing closed intervals - should be square brackets. The word "inclusive" is not used consistently - either let it be everywhere, or nowhere. Sometimes intervals are spelled out, other times they use mathematical notation.

Almost everywhere the intervals are closed - except for JVM datetime comparisons, which are open. But the matcher functions have identical names.

Here are a few examples for `shouldBeBetween`:

- Verifies that the given integer is between a and b inclusive.
- "$value should be between ($a, $b)"
- "$value should be between ($lower, $upper) inclusive"
- "$value is between ($from, $to)"
- Asserts that this is between [a] and [b]

`shouldBeIn(range)` is similar.

--------------------

The wording of both Kdoc and matcher messages should be uniform and predictable.
With the understanding that changing matcher messages is a potentially breaking change, here's one possible variant to start the discussion:

Use the proper mathematical notation everywhere, reinforced with words "inclusive" and "exclusive" after the interval. Some people may not know what the different brackets mean.
- [Kdoc] Verifies that the given integer is between `[a, b]` (inclusive, inclusive)
- [Matcher] "$value should be between [$a, $b] (inclusive, inclusive)"

**Comment by LeoColman** [comment]
Was this implemented in #4369 ?
