### ISSUE TITLE
Change timeout value for the constantly timeouting test on macOS runner

### ISSUE THREAD

**Issue by okarmazin** [kotest/kotest#4380]
There's a test called `"maintain performance fixed by https://github.com/kotest/kotest/issues/4016".config(timeout = 2.seconds)`.

This test keeps timeouting on the macOS runner all the time, keeping unrelated PRs from getting merged. Whether the test passes is a matter of luck - it probably depends on the current load of GitHub's macOS runner at the time.

The macOS runner is just slower in general TBH.

I propose that the timeout value be changed to 2.5 - 3 seconds such that the test maintains its function (keeping an eye out on performance regressions) without impacting unrelated PRs.

Kotest's CI pipeline runs for about 1 hour, which makes this false positive failure especially egregious. It wastes hours of time.

**Comment by sksamuel** [comment]
agreed, lets change it
