### ISSUE TITLE
Use semver prerelease format

### ISSUE THREAD

**Issue by Mahoney** [kotest/kotest#4397]
The latest releases have version `6.0.0.M1`. This isn't valid [semver](https://semver.org/); it should be `6.0.0-M1`.

(It's stopping me filtering it out of suggested dependency updates using the `com.github.ben-manes.versions` gradle plugin.)

**Comment by sksamuel** [comment]
Ok noted. Next release will be 6.0.0-M2.
Thanks.

**Comment by Mahoney** [comment]
Cheers, sorry for the terseness of the original post.
