### ISSUE TITLE
Logo icon for intellij plugin is low resolution / poor quality

### ISSUE THREAD

**Issue by irismessage** [kotest/kotest#4416]
In the sidebar. See screenshot 
<img width="83" alt="image" src="https://github.com/user-attachments/assets/11ae6753-63ff-4200-9e05-ec16b521dfa2">

**Which version of Kotest are you using**
1.3.13-IC-2024.1.1

IntelliJ 2024.2.3

**Comment by irismessage** [comment]
<img width="83" alt="image" src="https://github.com/user-attachments/assets/985aca75-c2b0-43d1-b70c-87391b3b649e">

Weird, seems fine now. Was it fixed or was it just on my machine? My intellij version hasn't changed although I did clear a bunch of caches for unrelated reasons. I didn't mention I'm on macos sonoma 14.7 23H124.
I'm not quite sure anyway why the icon is on the left side by default instead of the right bar where custom tools usually park themselves

**Comment by LeoColman** [comment]
My guess would be a caches smaller version of the image.

If the issue happens again, feel free to open a new one :)
