### ISSUE TITLE
Assertion of JSON object field value fails due to implicit type of expected value

### ISSUE THREAD

**Issue by Reversean** [kotest/kotest#4448]
I'm using **kotest-assertions-json 6.0.0.M1** with Jackson as serializer and some Spring Boot test libraries.

I have following test case:

```kotlin
@JsonTest
class ValueJsonTests {

    @Autowired
    lateinit var objectMapper: ObjectMapper

    @Test
    fun `Should serialize double`() {
        val value: Any = 0.46479126999899145    // definitely Double
        objectMapper
            .writeValueAsString((Foo(value)))   // serialized as {"value":0.46479126999899145}
            .shouldContainJsonKeyValue(Foo<*>::value.name, value)   // fails here
    }
}

data class Foo<T : Any>(val value: T)
```

**Expected behavior:** test passes.

**Actual behavior:** test fails when trying to assert corresponding json-object-field value with `value` variable.

```
Value mismatch at 'value':
Expected :0.46479126999899145
Actual   :0.46479126999899145
<Click to see difference>

java.lang.AssertionError: Value mismatch at 'value': expected:<0.46479126999899145> but was:<0.46479126999899145>
	at com.spbpu.content.table.check.ValueJsonTests.Should serialize double(ValueJsonTests.kt:122)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

It looks like `Matcher` reads the float-value from json as a `BigDecimal` and tries to convert it to the same type as the expected value, but because here `value` variable type is `Any`, it can't convert it to the required type (`Double`) and fails.

**Comment by AlexCue987** [comment]
I'll take a look, TY for reporting.

**Comment by AlexCue987** [comment]
this works against the latest code in master branch:

```kotlin
   "bug fix" {
      """{"value":0.46479126999899145}""".shouldContainJsonKeyValue("value", 0.46479126999899145)
   }
   "bug fix2" {
      """{"value":0.46479126999899145}""".shouldContainJsonKeyValue(Foo<*>::value.name, 0.46479126999899145)
   }
```

feel free to reopen this issue if it comes up again in the next release

**Comment by Reversean** [comment]
@tobinibot apologize, apparently I expressed myself not quite correctly. The point is that the test will fail if the type parameter of `shouldContainJsonKeyValue` has an implicit type (i.e. `Any`).

Here's my working example that I used as a starting point when trying to catch the bug (it doesn't always fail, so I listed what I listed first):

```kotlin
@JsonTest
class ValueJsonTests {

    @Autowired
    lateinit var objectMapper: ObjectMapper

    @ParameterizedTest
    @EnumSource(DataType::class)
    fun `Should serialize Foo`(type: DataType) {
        val value = randomValue(type)   // value is Any
        objectMapper
            .writeValueAsString((Foo(value)))
            .shouldContainJsonKeyValue(Foo<*>::value.name, value)   // it's equivalent of shouldContainJsonKeyValue<Any>(...) call, so it fails
    }
}

data class Foo<T : Any>(val value: T)

enum class DataType {
    Boolean,
    Float,
    Int,
    String
}

private val chars = ('a'..'z') + ('A'..'Z') + (0..9)
private fun randomValue(type: DataType) = when (type) {
    DataType.Boolean -> nextBoolean()
    DataType.Float -> nextDouble()
    DataType.Int -> nextInt()
    DataType.String -> (0..15).map { chars[nextInt(chars.size)] }.joinToString("")
}
```


I did a little research: here function `randomValue` returns result of type `Any`, so when `shouldContainJsonKeyValue` is called it consumes `Any` as a type parameter `T`, and it will then try to convert the read data (it read it initially as `BigDecimal`) to `T`.

**Comment by Reversean** [comment]
I have also prepared [PR](#4455). The solution I propose is to use a `value` variable class instead of a type parameter class inside `containJsonKeyValue` function to further extract the value from the json. Maybe I missed something and it's not a very good solution, so you're welcome to criticize.
