### ISSUE TITLE
Delete Temporary Directory Only if Test Passes

### ISSUE THREAD

**Issue by solonovamax** [kotest/kotest#4460]
Currently, the method to create a temporary directory can either always delete the directory, or never delete the directory.

there is no option to only delete the temporary directories if the test passes. This would be useful, as the temporary directory is often times helpful for understanding why a test failed.

Possibly a candidate for #3918. #2792 would be incredibly useful for adding this.

**Comment by sksamuel** [comment]
This is a good idea for 6.0
