### ISSUE TITLE
BeforeTest/AfterTest use different threads than the actual test

### ISSUE THREAD

**Issue by Burtan** [kotest/kotest#447]
Hi,
it seems that BeforeTest and AfterTest functions are running on different threads than the actual test. This is problematic for some frameworks like GAE and Objectify. Is it possible to make them all run on the same thread?

**Comment by Burtan** [comment]
Any release date?

**Comment by sksamuel** [comment]
I'll merge this back into 3.1.x along with the fix for #413 and release 3.1.11.

**Comment by Burtan** [comment]
Any estimation for a new release version?
