### ISSUE TITLE
More Comprehensive Stable Identifiers

### ISSUE THREAD

**Issue by solonovamax** [kotest/kotest#4470]
It would be nice if more classes has stable identifiers, as defined in these three places:
- https://github.com/kotest/kotest/blob/17d1b3b189fe4d804f1d3c6ce14280f724b0f168/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/datatest/Identifier.kt#L7-L17
- https://github.com/kotest/kotest/blob/17d1b3b189fe4d804f1d3c6ce14280f724b0f168/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/datatest/StableIdentifiers.kt#L47-L54
- https://github.com/kotest/kotest/blob/17d1b3b189fe4d804f1d3c6ce14280f724b0f168/kotest-common/src/commonMain/kotlin/io/kotest/mpp/stable.kt#L8-L84

I think that the following classes are good candidates for having stable identifiers:
- `Map<K, V>` where `K` and `V` have stable identifiers
- `Unit`
- `Array<E>` where `E` has a stable identifier
- `BooleanArray`, `ByteArray`, `CharArray`, `ShortArray`, `IntArray`, `LongArray`, `FloatArray`, and `DoubleArray`
- `List<E>` where `E` has a stable identifier
- `Uuid`
- `Duration`
- `UByte`, `UShort`, `UInt`, and `ULong`\*
- `Regex`
- `KClass<*>`

\*unsure if these get boxed to `Byte`, `Short`, `Int`, and `Long`, respectively. I'm like 75% sure they don't, but haven't tested this.

**Comment by AlexCue987** [comment]
clearly unsigned numerics have  ranges of possible values that are different from their signed counterparts. such as `byte in -128..127` and `uByte in 0..255`

**Comment by solonovamax** [comment]
> clearly unsigned numerics have  ranges of possible values that are different from their signed counterparts. such as `byte in -128..127` and `uByte in 0..255`

yeah I know, I'm just unsure if they're unboxed as, for example, `Byte`, or left in a boxed class, such as `UByte`

**Comment by solonovamax** [comment]
> clearly unsigned numerics have  ranges of possible values that are different from their signed counterparts. such as `byte in -128..127` and `uByte in 0..255`

yeah I know, I'm just unsure if they're unboxed as, for example, `Byte`, or left in a boxed class, such as `UByte`

**Comment by solonovamax** [comment]
something I noticed with the change:
The following are not added as having stable identifiers
- `Map<*, *>`
- `List<*>`
- `Set<*>`
- `Collection<*>`
- `Array<*>`

those would all be extremely convenient to have, especially the list one. (of course, assuming all the elements of the list have a stable identifier)

if for some reason they're not natively stable, then they can each just be sorted before being transformed to a string.
