### ISSUE TITLE
Missing many `Float` matchers

### ISSUE THREAD

**Issue by solonovamax** [kotest/kotest#4471]
There are many matchers for `Float` that are missing, which `Double` has.

here is a non-comprehensive list of the missing matchers:
- `shouldBeNegativeInfinity`/`shouldBePositiveInfinity` and their inversions
- `shouldBePositive`/`shouldBeNegative` and their inversions
- `shouldBeMultipleOf`
- `infix fun Float.plusOrMinus(tolerance: Percentage)`

**Comment by AlexCue987** [comment]
would you mind filling these gaps?

**Comment by solonovamax** [comment]
> would you mind filling these gaps?

I might if I get time to do it & remember to do it
