### ISSUE TITLE
Compile time checks on assertions

### ISSUE THREAD

**Issue by detomarco** [kotest/kotest#4476]
**Which version of Kotest are you using**
5.9.1

I'm in the middle of a big refactoring where I also need to change type of many variables from UUID to string.

I noticed that kotest doesn't raise any compile time error for this kind of assertions
```kotlin
UUID.randomUUID() shouldBe "string"
"string" shouldBe 123
```

This leads to lots of failing tests which could be fixed at compile time.

**Comment by LeoColman** [comment]
I don't think it's possible to raise compile-time warnings as the runtime typing system cannot help us, and we don't have enough information during compile-time to infer everything needed for `shouldBe`. Would you have any suggestions on how to tackle this?

**Comment by detomarco** [comment]
Looking at the source code
```kotlin
public infix fun <T, U : T> T.shouldBe(expected: U?): T {
    ....
}
```
in my understanding the idea was that U should extend T, so users would be able to do something like

```kotlin
open class Animal {}
class Cat: Animal() {}

val animal = Cat()
val cat = Cat()

animal shouldBe cat
```
which in teory is a cool feature.
 
But, for some reasons, kotlin does not throw a compile time error when U does NOT extend T (e.g. `"string" shouldBe 123`, string does not extend number).

Am I missing something?

If my assumption is correct and kotlin has some limitations to throw compile errors, I would propose to drop this "extends" thing and define the method just like

```kotlin
public infix fun <T> T.shouldBe(expected: T?): T {
    ....
}
```

The example above will become

```kotlin
animal.shouldBeTypeOf<Cat>()
animal shouldBe cat  
```

**Comment by detomarco** [comment]
Is it possible to replicate the same behavior of kotlin-test assertions?

In kotlin-test this assertion throws compile error
``` kotlin

assertEquals(UUID.randomUUID(), "String")
```

Error:
`Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.`

**Comment by LeoColman** [comment]
> Is it possible to replicate the same behavior of kotlin-test assertions?

I don't think so, no.

On this overload in kotlin-test it functions just as Kotest does when comparing 2 Anys

https://github.com/JetBrains/kotlin/blob/eb6e6b7b526f06ff72b56de3c7949d91f84d50e6/libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt#L712

```
public fun assertEquals(message: String?, expected: Any?, actual: Any?): Unit {
    assertTrue({ messagePrefix(message) + "Expected <$expected>, actual <$actual>." }, actual == expected)
}
```

While this overload which uses typing that works similar to your description https://github.com/JetBrains/kotlin/blob/eb6e6b7b526f06ff72b56de3c7949d91f84d50e6/libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt#L62 

```
public fun <@OnlyInputTypes T> assertEquals(expected: T, actual: T, message: String? = null) {
    asserter.assertEquals(message, expected, actual)
}
```

It expects 2 objects of type T, while our shouldBe is a lot different, and cannot pinpoint bad type comparisson during compile-time

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/matchers/should.kt
