### ISSUE TITLE
shouldContainExactlyInAnyOrder for nullable types should handle actual being null

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#4494]
**Which version of Kotest are you using**
5.9.1

The following fails, but I would expect it to pass 
```kotlin
val actual: List<Int>? = null
actual.shouldContainExactlyInAnyOrder(null) // fails
```

**Comment by OliverO2** [comment]
Wouldn't it make more sense to make this fail at compile time? I mean, how can a non-container (`null`) be tested for containing anything at all?

**Comment by AlexCue987** [comment]
Can you explain why that test should pass?

**Comment by Kantis** [comment]
My line of reasoning was 
> When there are no expectations, and there is no list, then the absence of both can be considered to fulfill the condition

I recently learned that there's actually a term for this called [Vacuous truth](https://en.wikipedia.org/wiki/Vacuous_truth) which is actually even [used in the Kotlin standard library](https://github.com/JetBrains/kotlin/blob/36754735b40177d2e1d1c1c2d7ef1bef687b1eab/libraries/stdlib/common/src/generated/_Collections.kt#L1733) in a similar context (`emptyList<Int>().all { it > 5 } // -> true`)

However, it is made impossible by the fact that we have nested nullability issues at play here.

`listOf(1,2,3) shouldContainExactly null` might mean that we have no expectations if we use the method with this signature:
```kotlin
infix fun <T> Iterable<T>?.shouldContainExactly(expected: Iterable<T>?) // We actually don't currently support nullability on expected here..
```

But it also collides with 
```kotlin
infix fun <T> Iterable<T>?.shouldContainExactly(vararg expected: T)
```

Where `null` would then refer to an element in actual, and not constitute the entire expectation..

Anyway.. I think we can close this since it's not possible to support this use-case without introducing ambiguity.
