### ISSUE TITLE
Allow defining tags as meta annotations

### ISSUE THREAD

**Issue by Grannath** [kotest/kotest#4501]
We recently started tagging integration tests as such to allow us to only run them when we have the time and resources to do so. That's easy enough to do with `@Tags("integration")`. The same tests also need a bunch of annotations for Spring, which can be gathered in a custom annotation.

```Kotlin
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(...)
annotation class IntegrationTest
```

This saves a huge amount of copy paste, and makes refactoring and extending integration tests much easier.

What's missing is the `@Tags` annotation. It has to be on the class itself and not on a custom annotation. We could use the `tags()` method on the spec, which would at least mean we have an `object`, not a String value. But it still means another point of possible mistakes.

I'd be willing to improve this myself, if there is a chance to have it merged. I'd propose to check how other projects like Spring handle the annotation lookup and add a similar utility to Kotest. Look on the spec itself first, then on it's annotations, then superclasses and then their annotations, something like that.

**Comment by AlexCue987** [comment]
have you considered using this annotation. would it solve your problem:

```kotlin
/**
 * Attach to a [io.kotest.core.spec.Spec], and the referenced [EnabledCondition] will be
 * instantiated and the [enabledIf] function invoked.
 *
 * Implementations of [EnabledCondition] must contain a no-arg constructor as they will
 * be created via reflection.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
annotation class EnabledIf(val enabledIf: KClass<out EnabledCondition>)
```
