### ISSUE TITLE
Kotest Plugin Icon is nearly invisible when the IDE is using a non-dark theme.

### ISSUE THREAD

**Issue by andriesfc** [kotest/kotest#4530]
plugin version: kotest 1.3.86-243-EAP-SNAPSHOT

Somewhere is white icon on almost white theme:

<img width="120" alt="image" src="https://github.com/user-attachments/assets/63d21a1d-602f-4187-9c79-751a5cf3f708">

Can it be fixed? Pls.

**Comment by sksamuel** [comment]
I've improved it. Once jetbrains approve it, you can upgrade inside intellij.
