### ISSUE TITLE
shouldNotMatch with Regex

### ISSUE THREAD

**Issue by Pitel** [kotest/kotest#4531]
There is a `shouldMatch(regex: Regex)`, but there is no `shouldNotMatch(regex: Regex)`, only `shouldNotMatch(regex: String)`. Resulting in a tests like `"asdf" shouldNotMatch myRegex.pattern`.

**Comment by AlexCue987** [comment]
I got it

**Comment by AlexCue987** [comment]
https://github.com/kotest/kotest/pull/4538

**Comment by AlexCue987** [comment]
fix merged
