### ISSUE TITLE
When using Data Driven Testing, separate rows are not treated as separate tests

### ISSUE THREAD

**Issue by wroblisko** [kotest/kotest#456]
Hi,
I found out that this is probably not working as expected. When using Data Driven Testing, methods like before/afterTest are not called for every row of each test. 

```kotlin
import io.kotlintest.Description
import io.kotlintest.data.forall
import io.kotlintest.shouldBe
import io.kotlintest.specs.StringSpec
import io.kotlintest.tables.row

class TestSpec : StringSpec() {

    var myMock = 10

    init {
        "myMock should be equal 10" {
            forall(
                row("first test"), row("second test")
            ) { sum ->
                //expect
                myMock shouldBe 10

                //side effect
                myMock = 11
            }
        }
    }

    override fun beforeTest(description: Description) {
        //like resetting mocks between tests
        myMock = 10
    }
}
```

The same story is with overriding method isInstancePerTest. I would expect that new instance of class will be created for every row for every test.

The main usecase for this is resetting mocks after every test.

I hope that this is a bug,
Maciej

**Comment by Kerooker** [comment]
I'm not sure if this is a bug, but I'll give you an alternative for now, it's the way I am used to do this kind of tests:

```

class Playground : FreeSpec() {
    
    var myMock = 10
    
    override fun beforeTest(description: Description) {
        myMock = 10
    }
    
    init {
        forall(
            row("First Test"),
            row("Second Test")
        ) { sum ->
            
            "myMock should be equal 10 when sum is $sum" {
                myMock shouldBe 10
                
                myMock = 11
            }
            
        }
    }
}

```

Again, I'm not sure if this is a bug. I just never had to deal with it that way

**Comment by sksamuel** [comment]
`forall` and other things like that are not part of the "test system", they just run inside a test. For them to work like you want, we'd have to promote them to be a spec themselves, which I'm happy to do if we can come up with suitable syntax.

**Comment by wroblisko** [comment]
Thanks for replies. I understand the cause of the problem, but from user perspective every row should be treated as separate test. Some frameworks (e.g. Spock @Unroll) even create separate test entries for each data row. 

It would be great if this would work like this in Kotlin Test. Otherwise using mocks is really error-prone.

**Comment by Kerooker** [comment]
@wroblisko The problem here is that by default, table rows are not starting their own test scenario. I believe that for now you can use it the way I suggested, until we come up with something strictly for Table Testing.

Do you have a suggestion on how you'd want to write them?

**Comment by wroblisko** [comment]
The workaround is great - actually I imagined it to work this way. Maybe it's good idea to make this an example when showing Table Testing.

**Comment by crazyk2** [comment]
I'm vote for opening this issue or open related.
TestNG example
```kotlin
import org.testng.annotations.*

class TestNGExample {

    @BeforeSuite
    fun beforeSuite() {
        println("BeforeSuite")
    }

    @AfterSuite
    fun afterSuite() {
        println("AfterSuite")
    }

    @BeforeClass
    fun beforeClass() {
        println("BeforeClass")
    }

    @AfterClass
    fun afterClass() {
        println("AfterClass")
    }

    @BeforeMethod()
    fun beforeMethod() {
        println("BeforeMethod")
    }

    @AfterMethod(alwaysRun = true)
    fun afterMethod() {
        println("AfterMethod")
    }

    @Test(dataProvider = "dataProvider")
    fun test(data: String) {
        println(data)
    }

    @DataProvider
    fun dataProvider(): MutableIterator<Array<String>> {
        val testData: ArrayList<Array<String>> = arrayListOf()

        val case1 = arrayOf("data one")
        val case2 = arrayOf("data two")

        testData.add(case1)
        testData.add(case2)

        return testData.iterator()
    }
}
```

Output result 
```
BeforeSuite
BeforeClass

BeforeMethod
data one
AfterMethod

BeforeMethod
data two
AfterMethod

AfterClass
AfterSuite
```
And idea show cases 
![image](https://user-images.githubusercontent.com/12140191/77348962-5e486900-6d4b-11ea-92a8-a178acf8371f.png)

JUnit 5 Example
```kotlin
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
internal class JUnitExample {

	@BeforeAll
	fun beforeAll(){
		println("BeforeAll")
	}

	@AfterAll
	fun afterAll(){
		println("AfterAll")
	}

	@BeforeEach
	fun beforeEach() {
		println("BeforeEach")
	}

	@AfterEach
	fun afterEach() {
		println("AfterEach")
	}
	
	@ParameterizedTest(name= "Number {0} Is odd?")
	@ValueSource(ints = [1, 3, 5])
	fun  isOdd_ShouldReturnTrueForOddNumbers(number: Int) {
		assertTrue(isOdd(number))
		println(number)
	}

	fun isOdd(number: Int): Boolean {
		return number % 2 != 0
	}
}
``` 
Output
```
BeforeAll

BeforeEach
1
AfterEach

BeforeEach
3
AfterEach

BeforeEach
5
AfterEach

AfterAll
```
Idea shows
![image](https://user-images.githubusercontent.com/12140191/77350324-61445900-6d4d-11ea-8a86-879cc943750b.png)

**Comment by crazyk2** [comment]
Or just add feature to roadmap and I will subscribe to updates

**Comment by sksamuel** [comment]
You can just put the test definition inside the forAll loop.

```kotlin
class Eg : FunSpec({

  forall(
      row(2, 3, 3),
      row(0, 0, 0),
      row(4, -1, 4),
      row(-2, -1, -1)
  ) { a, b, max ->
     test("the max of $a and $b should be $max") {
        Math.max(a, b) shouldBe max
     }
  }

})
```

(just typed it out with compiling).

**Comment by crazyk2** [comment]
Yes it works.  Thank you.
