### ISSUE TITLE
Feature Request: Make chaining possible for extension variants

### ISSUE THREAD

**Issue by mervyn-mccreight** [kotest/kotest#4589]
As described [here](https://kotest.io/docs/assertions/custom-matchers.html#extension-variants) the usual way extension variants are implemented throughout the kotest core assertions is that they allow chaining multiple assertions.

This is useful for e.g. chaining multiple assertions on one test-subject in an easy way.

Is there something Ktor specific that speaks against this for `HttpResponse` and/or `TestApplicationResponse`?

**Comment by mervyn-mccreight** [comment]
I'd be happy to work on this, I just wanted to clarify whether this is wanted or not before putting effort into it 😄

**Comment by Kantis** [comment]
I think this could be useful , feel free to open a PR
