### ISSUE TITLE
Add detailed Allure docs

### ISSUE THREAD

**Issue by Demitsuru** [kotest/kotest#460]
Good time of the day. I am facing an issue creating allure-results. I have a multi-module Gradle project and I have got captured only one Skipped test. Is there a guide how to make Allure working with KotlinTest? I have noticed the extension which helps customise the report. Thank you in advance. Here is the parent build.gradle:

`buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath "io.qameta.allure:allure-gradle:2.5"
    }
}

plugins {
    id 'java'
    id "org.jetbrains.kotlin.jvm" version "1.2.71"
    id 'io.qameta.allure' version '2.5'
}

apply plugin: 'kotlin'
apply plugin: 'io.qameta.allure'

allure {
    version = '2.7.0'
    aspectjweaver = true
    autoconfigure = true

    resultsDir = file('build/allure-results')
    reportDir = file('build/allure-results')
    allureJavaVersion = '2.7.0'

    useJUnit5 {
        version = '2.7.0'
    }
    downloadLink = 'https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip'
}

allprojects { project ->

    apply plugin: 'io.qameta.allure'

    allure {
        version = '2.7.0'
        aspectjweaver = true
        autoconfigure = true

        resultsDir = file('allure-results')
        reportDir = file('allure-results')
        allureJavaVersion = '2.7.0'
        useJUnit5 {
            version = '2.7.0'
        }
    }

    test {
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed", "standardOut", "standardError"
        }
    }
}

import io.qameta.allure.gradle.task.AllureReport

task allureAggregatedReport(type: AllureReport) {
    resultsDirs = subprojects.allure.resultsDir
}

repositories {
    jcenter()
}

subprojects {
    group 'com.<name>.<name>'

    apply plugin: 'java'
    apply plugin: "kotlin"
    apply plugin: 'idea'
    apply plugin: 'com.<name>.test-acceptance'
    apply plugin: 'com.<name>.junit5'
    apply plugin: 'com.<name>.repos'
    apply plugin: 'maven-publish'

    versioning { allowOverride = true }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
        kotlinOptions.jvmTarget = "1.8"
    }

    compileKotlin.kotlinOptions.jvmTarget = "1.8"
    compileTestKotlin.kotlinOptions.jvmTarget = "1.8"

    kotlin.experimental.coroutines 'enable'

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath "com.<name>.gradle.plugin:gradle-avro-plugin:0.14.1"
            classpath "io.qameta.allure:allure-gradle:2.5"
        }
    }

    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'http://packages.confluent.io/maven/'
        }
    }

    ext {
        arrow_version = '0.7.3'
        kotlin_version = '1.2.71'
        kotlintest_version = '3.1.10'
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
        implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
        implementation "io.arrow-kt:arrow-core:$arrow_version"
        implementation "io.arrow-kt:arrow-data:$arrow_version"
        implementation "io.arrow-kt:arrow-syntax:$arrow_version"
        implementation "io.arrow-kt:arrow-instances-core:$arrow_version"
        implementation "io.arrow-kt:arrow-instances-data:$arrow_version"
        testImplementation "io.kotlintest:kotlintest-runner-junit5:$kotlintest_version"
        testImplementation "io.kotlintest:kotlintest-assertions-arrow:$kotlintest_version"
        testImplementation "io.kotlintest:kotlintest-extensions-allure:$kotlintest_version"
        testImplementation(
                'org.junit.jupiter:junit-jupiter-api:5.2.0'
        )
        testRuntimeOnly(
                'org.junit.jupiter:junit-jupiter-engine:5.2.0'
        )
        testCompile "io.qameta.allure:allure-gradle:2.5"
    }

    configurations {
        compile.exclude group: "org.slf4j", module: "slf4j-log4j12"
        compile.exclude group: "log4j", module: "log4j"
    }

    test {
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed", "standardOut", "standardError"
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.2'
    distributionType = Wrapper.DistributionType.ALL
}`

**Comment by michaeloa** [comment]
Did you figure this out?

**Comment by sksamuel** [comment]
Docs have been updated.
