### ISSUE TITLE
Running with "Test Impact Analysis"

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#505]
First of all, sorry, this is more a question than an issue or anything else, but I'm curious whether someone has already tried combining kotlintest with https://github.com/rpau/junit4git? I'm not saying I'm expecting it not to work, but I wanted to know about any previous experience before I spend the time to give it a try.

**Comment by Kerooker** [comment]
Interesting.
Never heard of it! I'm not even sure how it would work with KotlinTest

**Comment by sksamuel** [comment]
Might be a good idea for a feature for 3.3 ?

**Comment by Kerooker** [comment]
Maybe.
But I'm not sure if many people use that Junit4git. There are very few stars in Github and very few forks.

I'm afraid to put too much effort into adding this feature and nobody using it after all :x

**Comment by sksamuel** [comment]
Should be easy enough to add though.

**Comment by sschuberth** [comment]
> Never heard of it!
> But I'm not sure if many people use that Junit4git.

See, @Kerooker, how could you use it if you (and other people) have never heard of it 😉 More seriously, you indeed need to know what you're looking for to find this sort of thing, or you need to be following [Martin Fowler's blog](https://martinfowler.com/articles/rise-test-impact-analysis.html). But the idea makes absolute sense to pursue, IMO.

Anyway, my hope indeed is that it's easy to use with kotlintest. Note that I'm not necessarily asking for adding generic Test Impact Analysis support to kotlintest. I'm rather interested to see what it takes to make the existing junit4git project work smoothly with kotlintest.

**Comment by sksamuel** [comment]
That project can't work as it uses JUnit specific stuff.

**Comment by sschuberth** [comment]
Well, and so does kotlintest (if using `kotlintest-runner-junit5`), or? Ideally, I would have expected it to "just work" when using both `kotlintest-runner-junit5` and `junit5git` artifacts. If that's not the case for whatever reason, what would be the path to a potential implementation? A new `kotlintest-runner-junit5`?

**Comment by sksamuel** [comment]
Don't forget there's junit5 platform and junit5-jupiter. The latter is what you use if you're writing junit tests, and what provides things like the junit test rules or whatever they're called now.

**Comment by sschuberth** [comment]
@Kerooker, please always add a rationale when closing issues.

**Comment by LeoColman** [comment]
Oh, this one was by mistake.

I'll reopen, sorry
