### ISSUE TITLE
Latest IDEA Compatibility

### ISSUE THREAD

**Issue by straxess** [kotest/kotest#5358]
Last version of plugin has no 2024.2 support. (See range)
![image](https://github.com/user-attachments/assets/c2d77764-2000-4ac4-b20f-dd35f7afe1ff)
https://plugins.jetbrains.com/plugin/14080-kotest-plugin-intellij/versions

**Comment by VahidGarousi** [comment]
Do we have any updates on this issue?

**Comment by straxess** [comment]
> Do we have any updates on this issue? 

New 2024.2.1 version of IDEA

**Comment by theHacker** [comment]
For the new 2024.3 EAP, there is K2 enabled by default.

![grafik](https://github.com/user-attachments/assets/aca58f19-a7ff-434a-a05b-eb38d9ddc400)

JetBrains's blog has information about that:
- https://blog.jetbrains.com/idea/2024/09/intellij-idea-2024-3-eap/#k2-mode-enabled-by-default
- https://kotlin.github.io/analysis-api/migrating-from-k1.html

**Comment by sksamuel** [comment]
2024.2 and 2024.3 have been released, waiting on jetbrains approval.
