### ISSUE TITLE
Gutter icon runs Kotest spec with Gradle instead of Kotest runner configuration

### ISSUE THREAD

**Issue by bliessens** [kotest/kotest#5363]
I have a Gradle project in IntelliJ with Kotest tests. 

In the editor window on the Kotest spec, when clicking the "Run" gutter icon the spec is executed with the Gradle runner.

Contrarily, launching the Kotest spec with the keyboard short Ctrl+Shift+R (on mac) runs the spec with a Kotest run configuration

**Comment by sksamuel** [comment]
This is configurable in intellij settings

![image](https://github.com/kotest/kotest/assets/743706/1fb58853-0079-4135-ae15-7cff628f82dd)

**Comment by bliessens** [comment]
Thanks
