### ISSUE TITLE
The icon is blurry

### ISSUE THREAD

**Issue by tin-trinh** [kotest/kotest#5364]
The icon look blurry on IntelliJ side bar 

<img width="255" alt="Screenshot 2024-04-26 at 13 35 09" src="https://github.com/kotest/kotest/assets/86760644/12e2189c-49ae-47f4-9888-be78c8e1bfc1">

**Comment by sksamuel** [comment]
linux or mac ?

**Comment by sksamuel** [comment]
Looks like they increased it to 22x22 in the new UI, because the guidelines still say 13x13.
