### ISSUE TITLE
`Run '{TestObjectName}` will not work unless cursor is at start of line of class definition

### ISSUE THREAD

**Issue by scarf005** [kotest/kotest#5392]
## To reproduce

![_05](https://user-images.githubusercontent.com/54838975/210173140-1f24890a-45ba-46a0-a9c1-7412fce48116.png)
1. find the `test shortcut` to run test (in this case `Ctrl + Shift + F10`)

![_03](https://user-images.githubusercontent.com/54838975/210173138-399d48a5-6149-4ea4-99dc-4c37e5983a9c.png)
2. pressing `test shortcut` will not work.  pressing `test shortcut`  inside test body will not work, either.

![_04](https://user-images.githubusercontent.com/54838975/210173139-0038aa00-b679-498f-a87d-1c50e108aa6d.png)
3. pressing `test shortcut` will work.

it's frustrating because of constant cursor moving.

**Comment by sesamzoo** [comment]
In case of a `class SomeTest` the test shortcut will work only when the text cursor is in the range "before the 'c' of class" and "before the second 's' of class".

**Comment by Kantis** [comment]
IntelliJs [RunLineMarkerContributor](https://github.com/JetBrains/intellij-community/blob/0a2503ad9c52b8f494d1aaf390e303e5a6951e3f/platform/execution-impl/src/com/intellij/execution/lineMarker/RunLineMarkerContributor.java#L21) only allows us to contribute this info for a single PSI element, and the action is attached to that element. There's no such element that encompasses both the keyword and identifier (and supertype), so we have to settle for either having it on `class/object` or the name itself.
