### ISSUE TITLE
micronaut-test-resources is not supported

### ISSUE THREAD

**Issue by mf-guse** [kotest/kotest#5395]
I use the kotest plugin a lot in my daily business and it helps me a lot!

Unfortunately the plugin does not support micronaut-test-resources as this framework needs tests to be started by gradle, see https://github.com/micronaut-projects/micronaut-test-resources/issues/120

A testproject can be found in https://github.com/mf-guse/micronaut-test-resources-test.

If you run the test using the kotest plugin the required Docker Testcontainer is not started. Run the test using Gradle, it is started.

Do you see any chance to let the plugin support micronaut-test-resources?

**Comment by mmwinther** [comment]
I have just run into this same issue. It would be resolved if we could delegate test running in IntelliJ to Gradle like what is possible with Junit. Any chance this can be looked at?

**Comment by sksamuel** [comment]
That's the plan for 6.0.0 @mmwinther
