### ISSUE TITLE
Improvements: see the specs/tests in "File structure"

### ISSUE THREAD

**Issue by rolintoucour** [kotest/kotest#5396]
Hi,

Using the menu "Navigate -> File structure", it would be nice if specs / tests could appear here.

Comparing to JUnit where each test is a method (and easy to find using the "File Structure"), it would be easier to have this functionality to search for tests.

**Comment by sksamuel** [comment]
I think this is just part of intellij looking for methods in a class. And since kotest is not method based, it can't appear here.
There doesn't appear to be a way to hook into that functionality.

**Comment by sksamuel** [comment]
This is in the next build.
