### ISSUE TITLE
Intellij does not recognize dynamic strings

### ISSUE THREAD

**Issue by edeesis** [kotest/kotest#5397]
When defining a test name (in my case we're using DescribeSpec), we're unable to run the blocks with dynamic strings, causing us to have to run the entire test class.

```kotlin
class Test : DescribeSpec({
  describe(123.toString()) {
    it("test") {
      "str" shouldBe "str"
    }
  }
})
```

You lose gutter icons as well. You still have it on it `test` level but if you try to use that one, it'll not find the test.

![image](https://user-images.githubusercontent.com/1738038/198741163-75f99301-bbf8-4189-86e4-17a1bab9d4e2.png)

**Comment by Kantis** [comment]
I don't think there's much we can do about this. How would this case work, for instance?

```kotlin
class Test : DescribeSpec({
  describe(Random.nextLong().toString()) {
    it("test") {
      "str" shouldBe "str"
    }
  }
})
```

The gutter icons generate a run configuration with a test-filter matching the name of the test.. I the name of the test is not a String literal, we can't know for sure what it'll be.

**Comment by sksamuel** [comment]
Yep, nothing we can do here.
The best we could do is add a warning / highlight that says "dynamic test names cannot be run automatically" ?

**Comment by edeesis** [comment]
What if the string was a [const](https://kotlinlang.org/docs/properties.html#compile-time-constants) in an object definition? Not sure if that changes anything.

**Comment by edeesis** [comment]
If it helps, my use case is to put function references directly in the describe blocks for refactor-safety:

```
describe(LineItemFinder::all.name) {
```
Could the describe function take a function reference?

**Comment by sksamuel** [comment]
It could work with anything that is statically resolvable in the PSI representation that Intellij uses.
