### ISSUE TITLE
Support for IntelliJ 2022.3 EAP

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5400]
IntelliJ just launched another new EAP.

![image](https://user-images.githubusercontent.com/7399011/192018388-e004b8e6-027a-4f95-9313-3a897c7b4c2a.png)

Interestingly IntelliJ complains about incompatible plugin, but if you click "Enable Plugin", it still seems to work.
It even looks ok in their completely new UI:

![image](https://user-images.githubusercontent.com/7399011/192020267-9f0dd7ab-8e99-4202-9174-509acc7e5347.png)

**Comment by sksamuel** [comment]
A 223 specific plugin has been released pending jetbrains approval.
