### ISSUE TITLE
Error running on WSL2

### ISSUE THREAD

**Issue by pacdouglas** [kotest/kotest#5402]
Hi!

I can't run using the IntelliJ on Windows with all environments set to WSL2, it doesn't happen if I use a simple test with JUnit.

Error running 'FakeTempGisModelTest': Cannot run program "\\wsl$\Ubuntu\home\pac\.asdf\installs\java\adoptopenjdk-8.0.345+1\bin\java" (in directory "\\wsl$\Ubuntu\home\pac\git\avangrid-e3\avangrid-model"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by DragonString** [comment]
I have got the same issue

**Comment by pearlzzi98** [comment]
wow,,, I have got the same issue too

**Comment by Tetrahedrite** [comment]
Still doesn't work with WSL :(

**Comment by CXwudi** [comment]
A workaround could be that running the junit 5 instead of running them as kotest

See https://github.com/kotest/kotest/issues/5416#issuecomment-1200103433
