### ISSUE TITLE
Support Bazel

### ISSUE THREAD

**Issue by nikunjy** [kotest/kotest#5404]
This plugin works amazing with gradle. Is it possible to extend this to get it to work with Bazel. 

Plugin already does the heavy lift of identifying the specs and test. 

If it could be easily extended to pass custom arguments to a bazel invocation it would work. So if you click on a test it would run 

bazel test //blah --test_arg=kotest.filter.spec=Foo* 

I can make our bazel launcher support whatever arguments via kotest launcher but don't know where to start on extending this plugin. Is this something that is doable or very non trivial.

**Comment by nikunjy** [comment]
If we end up landing the PR https://github.com/kotest/kotest/pull/3200 referenced in https://github.com/kotest/kotest/issues/2416

We can select single tests and run them in bazel but don't know how it will get wired to the bazel invocation from the IDE. I am thinking if there is a way to make it so that this plugin doesn't care about the underlying runner and provides it to be pluggable.

**Comment by nikunjy** [comment]
Pinging the author @sksamuel  
I am happy to extend this plugin. But want to hear your thoughts if this even makes sense for the plugin.

**Comment by sksamuel** [comment]
@nikunjy Happy to evaluate a PR :)

**Comment by nikunjy** [comment]
Is it possible to write a rough architecture of code for this @sksamuel  and some other guidance on `CONTRIBUTING.md` on how to best test/debug this plugin. 
Would really help me and I think many others who might be interested in contributing to this codebase. 

I know you are busy but can't hurt to ask 😄
