### ISSUE TITLE
`Jump to source` is not available in the `Run` view

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#5405]
Bonjour,

## What?

If possible, support `Jump to source` for `SomeKotestSpec` in the `Run` view

## Why?

When a test fails, I can currently:
- `Jump to source` from the `Run` view the relevant test if it's a `PlainJunitTest`
- do the same from the `Kotest` view if it's a `SomeKotestSpec`
- but I can't `Jump to source` to a test  inside `SomeKotestSpec` from the normal `Run` view

In a project that has a mix of Junit tests and KotestSpecs this is a bit uncovenient to have two different ways to jump to a failing test

## How to reproduce?

With this code

```
class PlainJunitTest {
    @Test
    fun `2+2 shouldBe 5`() {
        2+2 shouldBe 5
    }
}

class SomeKotestSpec : FunSpec({

    test("2+2 shouldBe 5") {
        2 +2 shouldBe 5
    }
}
```

this works for PlainJunitTest but not SomeKotestSpec 

<img width="819" alt="my-kotlin-scipts_–_SomeKotestSpec_kt__my-kotlin-scipts_test__et_New_Issue_·_kotest_kotest-intellij-plugin" src="https://user-images.githubusercontent.com/459464/183817506-c7d79b00-1c83-4e20-a8d7-0231bd8959a2.png">

this works for SomeKotestSpec but not PlainJunitTest

<img width="473" alt="my-kotlin-scipts_–_SomeKotestSpec_kt__my-kotlin-scipts_test__et_DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/459464/183817550-5bfeb6f8-c7fd-4556-b30e-90aaa8ea5b3b.png">

## Caveat

I understand this might not work in all cases, like tests where the name are dynamic, and that's probably why the kotest view is needed. But much of my nice tests use static names and it would be already great if that works in this simple case.

**Comment by sksamuel** [comment]
this is a very old ticket but would just like to reply, in 6.1 this works at all levels - if you use the gradle plugin and ide plugin.
