### ISSUE TITLE
Support running on non-local envrionment

### ISSUE THREAD

**Issue by CXwudi** [kotest/kotest#5416]
Hi, 

Thanks for maintaining this convience plugin. It would be great if I can configure the run configuration to let a particular kotest run in docker or WSL2, similar to how Junit test in Intellij can be ran in docker or WSL2 as shown below
![image](https://user-images.githubusercontent.com/17377423/168955518-75ab4a5b-5113-48ea-8ff1-73bd4f24ed91.png)

**Comment by sksamuel** [comment]
Is this an intellij screenshot ?

**Comment by CXwudi** [comment]
Yes, I think this functionality appears since a 2021 version intellij

**Comment by CXwudi** [comment]
I think this is the same cause, so I didn't create a separate issue

But when I open a project stored in WSL2
![image](https://user-images.githubusercontent.com/17377423/181878408-6940b782-7fd8-4d38-b1d1-723428b169a4.png)
and run a test by clicking the run button. it show that kotest can not run as it is not a Win32 process
![image](https://user-images.githubusercontent.com/17377423/181878153-ff07669d-22ca-4b8a-a91d-8aff2c5d7887.png)

On the other hand, if I right-click a folder and click run test. It works fine (but I guess it works because running test from folder let IntelliJ tries to run through JUnit 5, whereas the run button that the plugin creates is actually running the kotest through the plugin)
![image](https://user-images.githubusercontent.com/17377423/181878305-77574f0f-812e-4dc1-8c35-f9872b97612b.png)
