### ISSUE TITLE
Support for IntelliJ 2022.1

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5422]
Hi,

IntelliJ started EAP for 2022.1, however the plugin only supports up to 2021.3.
Will there be a new version of the Kotest plugin?

Thank you! :D

**Comment by sksamuel** [comment]
Yep we can update the builds.

**Comment by sksamuel** [comment]
2022.1 build is published (takes a couple of days for jetbrains to approve it in the marketplace).
