### ISSUE TITLE
The test does not work when using AnnotationSpec @nested.

### ISSUE THREAD

**Issue by sasuke0209** [kotest/kotest#5425]
In Kotest 5.0.0, @Nested is now supported in AnnotationSpec, but when I use it I cannot run tests.
I wrote a test as follows, but the Run Test button is not displayed.

```kotlin
internal class ServiceTest : AnnotationSpec() {
  
    @Nested
    inner class functionTest {
        @Test
        fun nomalScenario() {      // Run Test does not appear.
            ...
        }
    }
}
```

Do you have any plans for support?

Environment
- Intellij IDEA 2021.3

**Comment by sksamuel** [comment]
Yep we plan to support this.
