### ISSUE TITLE
Feature Request: Test Result doesn't navigate to the test

### ISSUE THREAD

**Issue by busches** [kotest/kotest#5427]
When running tests via IntelliJ and you double click a test from the test result, it does not navigate to the test in the file. Junit tests do this. It's especially nice when a test fails and you want to quickly navigate to it. Instead you have to click the test, then find the line in the stacktrace to navigate to the test.

**Comment by sksamuel** [comment]
The classname should work right ?
The test name navigation is fixed in 5.0 currently (needs that intellij release that I rolled back mind)

**Comment by busches** [comment]
Classname seems to collapse in intellij. Test name right now takes to the top of the `describe` when using `DescribeSpec` which isn't that helpful.

**Comment by sksamuel** [comment]
Can you try in 5.0 with latest plugin

**Comment by sksamuel** [comment]
Been looking at this. It should work if you run tests from the plugin. If you're using gradle, you're hitting a gradle bug which doesn't support nested tests that are not methods.

**Comment by busches** [comment]
I upgraded the plugin this morning and the behavior is slightly better as if I have the following:

```
it("test 1") {
} <--- cursor goes here when test 2 failed

it("test 2"){
}
```

Ideally it'd go to the assert that failed in test 2 though.

Not sure what you mean by via the plugin, I'm running it via intellij's gutter. I did try changing  `Run tests using: IntelliJ IDEA` and as `Gradle`, both have the same behavior of going to the test above it that I described above.

**Comment by sksamuel** [comment]
The assertions capture a stack trace so you should be able to go directly
to the line via the stack. That information isn't carried through to the
test location hints. I suppose it _could_ be in theory, but might prove
tricky trying to determine which frame of the stack to use.

**Comment by busches** [comment]
That's what we do now, but the stacktraces are often quite long, so this is
quite a drawback.

**Comment by sksamuel** [comment]
We thought about adding some kind of configurable "stack trace cleaner".
So you could say like, only keep com.mycompany + next 5 lines, or something
like that.

Also intellij is supposed to collapse stack traces on certain package
names, like io.kotest.

https://github.com/kotest/kotest-intellij-plugin/blob/master/src/IC-213/resources/META-INF/plugin.xml#L82

**Comment by busches** [comment]
This still doesn't with and one of the main reasons I won't convert all projects over to kotest.

**Comment by sksamuel** [comment]
Remind me how you're running your tests.

**Comment by busches** [comment]
Via intellij. Same behavior using gradle or intellij to run them.

**Comment by sksamuel** [comment]
It won't work via gradle because gradle is broken in respect to location reporting.
It should work via intellij though - if you're running with the plugin and not just running gradle inside intellij.

**Comment by busches** [comment]
Running via the normal test runner inside intellij.

**Comment by sksamuel** [comment]
Do you have this set to gradle:

![image](https://user-images.githubusercontent.com/743706/151730668-f9a09ec0-0283-4539-b394-e63eb9c44a30.png)

**Comment by arekolek** [comment]
Closed as completed, but it still doesn't work for me. Is it possible to click on test result, like you can with junit?

junit:
<img width="796" height="334" alt="Image" src="https://github.com/user-attachments/assets/1b20b88d-6cdb-4f2c-8351-d85a638e63a2" />

kotest:
<img width="805" height="291" alt="Image" src="https://github.com/user-attachments/assets/560e5639-94ee-40a4-8216-a51e2822859b" />

There's "jump to source" when using Junit, and also you can just double click to do that.

**Comment by sksamuel** [comment]
Yes, but you need to ensure you're on Kotest 6.1+ and have the Kotest Gradle plugin applied.
Then you have jump to source at all levels.

**Comment by Faltenreich** [comment]
@sksamuel This does still not work with Kotest 6.1.11 (including Gradle Plugin) and IDE Plugin 6.1.13-2025.3.2. Right-clicking a test in Android Studio Panda 3 (2025.3.3 Patch 1) shows a context menu with "Nothing here" and double-clicking a test does nothing.

**Comment by wissenstein** [comment]
Hi! Kotest in my project has version 6.2.1. ItelliJ IDEA plugin for Kotest has version 6.1.18-2026.1.1
Navigation to the test source does not work anymore in my project. When I click on a leaf in the test result tree, nothing happens if the test is successful, and only the stack trace appears in the pane near to the tree, if the test has failed, but I ain't get navigated to the source code of the failed test.
It would be nice to get to the place in the source code, where the test is, which is represented via the leaf in the test result tree.

**Comment by Faltenreich** [comment]
@sksamuel This does work now for us with version 6.2.3. 🥳
