### ISSUE TITLE
Kotest Plugin Incompatible with Android Studio Arctic Fox

### ISSUE THREAD

**Issue by claytonStasenko** [kotest/kotest#5429]
Hello! There seems to be an issue with installing the Kotest plugin on newer versions of Android Studio [seemingly on Arctic Fox, but I can't say for sure]. Whenever I try to install the plugin I get the below error

![image](https://user-images.githubusercontent.com/58704239/137557566-78726a3b-31b7-44eb-9f60-1cc21ebd995e.png)

Here is my Android Studio install information:
![image](https://user-images.githubusercontent.com/58704239/137557601-4c3983b5-24f2-4551-97c8-c2725c921fc9.png)

Please let me know if there's anything you can do to help. Appreciate your time!

**Comment by sksamuel** [comment]
This might help https://github.com/kotest/kotest/issues/5445

**Comment by claytonStasenko** [comment]
Thanks for your help @sksamuel! I did not have the plugin installed previously, and initially when I tried invalid and restart I got the same error, but deleting the .idea and .gradle directories at the root of my project before invalidating and restarting did the trick!

feel free to close this issue. thanks again
