### ISSUE TITLE
Incompatable with IntelliJ IDEA build version 211+

### ISSUE THREAD

**Issue by duruer** [kotest/kotest#5432]
![image](https://user-images.githubusercontent.com/3341936/136964719-53d2f9f3-a153-4ac6-8085-fe45d8b4971a.png)

Can't even install the plugin with the latest IntelliJ IDEA.

**Comment by sksamuel** [comment]
See https://github.com/kotest/kotest/issues/5445

**Comment by duruer** [comment]
Oh alright, closing the issue

**Comment by sksamuel** [comment]
Not sure why it happens but only happens to a couple of people.
