### ISSUE TITLE
Plugin incompatible with Android Studio(base on Intellij 2020.3.1)

### ISSUE THREAD

**Issue by fightyz** [kotest/kotest#5434]
When [kotest-extensions-robolectric](https://github.com/kotest/kotest-extensions-robolectric) is used in the unit test, then use the @RobolectricTest annotation in the unit test:
```kotlin
@RobolectricTest
class RobolectricTest: FunSpec({
    context("test kotest robolectric plugin") {
        test("nested test") {
            1 + 1 shouldBe 2
        }
    }
})
```
If you start to run the `context` function from the run icon provided by **kotest-intellij-plugin**:
![image](https://user-images.githubusercontent.com/1697504/135093595-83c3a063-b7b0-495a-b57d-9c3cabb5b0cc.png)

**kotest-intellij-plugin** automatically uses kotest run configuration:
![image](https://user-images.githubusercontent.com/1697504/135093694-c67fb46d-15e1-49aa-8e1d-c937d106ac29.png)

The result will be a test failure (Test passed 0), and the test name will not be displayed in the test report:
![image](https://user-images.githubusercontent.com/1697504/135093768-55e84cdc-00f6-4585-8793-24aa21832f80.png)

However, if the unit test is run from the run icon at the class name, it is successful:
![image](https://user-images.githubusercontent.com/1697504/135093854-e40ed326-09d1-433d-b873-5c4fc87ab565.png)

Android Studio automatically uses gradle run configuration:
![image](https://user-images.githubusercontent.com/1697504/135093926-80b6676a-e262-438e-b808-a98c505612e6.png)

The test results are also normal:
![image](https://user-images.githubusercontent.com/1697504/135094228-f5ec6681-276c-4b7f-ae0b-8b6a18d269e9.png)

Therefore, I think that **kotest-intellij-plugin** may not have good compatibility with Android Studio.

### My Context:
Android Studio：2020.3.1 for Mac：
![image](https://user-images.githubusercontent.com/1697504/135094414-0517b758-f3ac-4a64-8129-148e59bbc56f.png)

```groovy
testImplementation("io.kotest:kotest-runner-junit5-jvm:4.6.3")
testImplementation("io.kotest:kotest-assertions-core-jvm:4.6.3")
testImplementation("io.kotest.extensions:kotest-extensions-robolectric:0.4.0")
testImplementation("org.jetbrains.kotlin:kotlin-reflect:1.5.10")
testImplementation("org.robolectric:robolectric:4.6.1")
```

**Comment by jschneidereit** [comment]
I've noticed that on IJ on mac in the last few days actually. Can you try editing the all test run configuration to include `--tests "*"` and see if that helps short term? I noticed that was the difference between using the gutter icon and the main Gradle test target

**Comment by fightyz** [comment]
> I've noticed that on IJ on mac in the last few days actually. Can you try editing the all test run configuration to include `--tests "*"` and see if that helps short term? I noticed that was the difference between using the gutter icon and the main Gradle test target

The problem now is that when I start the unit test from the `context` function, Android Studio will automatically use "kotest run configurations". And in its configuration window:
![image](https://user-images.githubusercontent.com/1697504/135114445-444cff39-b9b5-471a-b9ac-6d61fd3b0af8.png)

I tried adding the `--tests "*"` parameter to the three input boxes of "VM options", "Program arguments" and "Environment variables", but none of them worked, and the unit test would still fail or even report an error.

It doesn't make sense to set `--test "*"` in Gradle run configurations, because gradle test can already run successfully.
![image](https://user-images.githubusercontent.com/1697504/135114969-b17568f6-f6de-4aa9-ba51-f4e021a3c8aa.png)

**Comment by jschneidereit** [comment]
Oh I see, I guess there are two issues here then 🤔 I'll open one for mine

**Comment by fightyz** [comment]
The problem is still there with `1.1.49-IC-2020.3` in Android Studio:
![image](https://user-images.githubusercontent.com/1697504/144243102-d25799b1-a194-4783-a951-7f9c5e90baa0.png)
