### ISSUE TITLE
Does not install on IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by guillaumeagile** [kotest/kotest#5436]
the installation from IDEA says that only version 201.*   is supported
IDEA is already up to version 212 !!!
![pb plug kotest intellij 2021-09-23 160422](https://user-images.githubusercontent.com/197786/134522145-29ba7afd-fa2c-48b9-8f4e-7dc33eccdb11.png)

**Comment by guillaumeagile** [comment]
It works when installing from the ZIP only

**Comment by sksamuel** [comment]
Seems to be a known problem when updating intellij.
You need to remove the plugin, restart, then add it back again.
See https://github.com/kotest/kotest/issues/5445
