### ISSUE TITLE
Need version of plugin compatible with Intellij Idea 2021.2.1

### ISSUE THREAD

**Issue by pe4enko** [kotest/kotest#5437]
Need version of plugin compatible with Intellij Idea 2021.2.1
Thanks.

**Comment by sksamuel** [comment]
There is a build compatible with 2021.2.1
What error are you seeing ?

![image](https://user-images.githubusercontent.com/743706/131506542-db6a9bd7-272e-4c17-a009-2c8a757d6c1d.png)

**Comment by pe4enko** [comment]
![image](https://user-images.githubusercontent.com/822445/131508813-daaa69fa-1625-45e5-8805-75c2de2f6195.png)

**Comment by pe4enko** [comment]
![image](https://user-images.githubusercontent.com/822445/131508906-4cbbef1a-cd45-4fdd-adeb-398761f0b682.png)

**Comment by sksamuel** [comment]
I've seen this before where intellij gets confused. The solution is to remove the plugin, then go to invalidate caches and restart, and then once restarted add the plugin and it should pick up the right version.

**Comment by pe4enko** [comment]
You are right, thanks!

**Comment by sksamuel** [comment]
Glad it worked :)

**Comment by ilya40umov** [comment]
BTW, for me it has only worked after I manually removed `kotest-intellij-plugin` from `disabled_plugins.txt` (lives in `~/.config/JetBrains/IntelliJIdea2021.2` on Linux).
