### ISSUE TITLE
Plugin needs to updated for the newest IDE

### ISSUE THREAD

**Issue by lambdakilo** [kotest/kotest#5439]
Kotlin Version: 1.5.20
Kotest Version: 4.6.0
Kotest Plugin Version: 1.1.36-IC-2021.1
Intellij Version: IU-211.7628.21

The exact error message is in the picture when trying to install Kotest IntelliJ Plugin from the plugin section in IntelliJ IDEA.

![image](https://user-images.githubusercontent.com/31825085/126941848-74338e18-4f1c-45c3-b7fd-3eefe93ff08d.png)

**Comment by sksamuel** [comment]
Possibly a duplicate of https://github.com/kotest/kotest/issues/5445

**Comment by lambdakilo** [comment]
Good point! This might be a duplicate but Clearing file system cache, Local History and downloaded shared indexes didn't do the trick for me.
https://www.jetbrains.com/help/idea/invalidate-caches.html
Any way to debug this error message?

**Comment by sksamuel** [comment]
Did you remove the plugin before clearing the cache ?/
Basically you have a version installed for an older intellj and it hasn't upgraded.
You can see here we build for your version of intellij (211.76) https://github.com/kotest/kotest-intellij-plugin/blob/master/build.gradle.kts#L58-L59

**Comment by lambdakilo** [comment]
Like addressed in the issue kotest/kotest#5445 I can't remove the plugin if I have not installed it yet.

I tried to search for the plugin manually according to [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000524244-Disable-Uninstall-plugin-without-launching-Idea) thread but there was no folder for the plugin Kotest or anything alike.

It's almost like only these lines are being used
```kotlin
   plugin.PluginDescriptor(
      since = "201.6487",
      until = "201.*",
      sdkVersion = "IC-2020.1",
      sourceFolder = "IC-201",
      deps = listOf("java", "org.jetbrains.plugins.gradle", "org.jetbrains.kotlin:1.3.72-release-IJ2020.1-5")
   ),
```

instead of the [lines](https://github.com/kotest/kotest-intellij-plugin/blob/master/build.gradle.kts#L36-L42) you brought up
```kotlin
      since = "211.6693.111", // this version is 2021.1
      until = "212.*",
```

This makes me wonder on which conditions are these lines called and can we somehow do something about it.

**Comment by lambdakilo** [comment]
The issue perished when updated to IntelliJ IDEA [build 212](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.2+latest+builds).

Closing the issue.

**Comment by sksamuel** [comment]
Ok i had missed that you had not even installed the plugin in the first
place! I thought you were upgrading intellij from an earlier version with
an earlier version of kotest plugin.

Anyway I'm glad it's working now!
