### ISSUE TITLE
`ShouldNotBeTrueInspection` false positive

### ISSUE THREAD

**Issue by mateuszkwiecinski** [kotest/kotest#5440]
Kotest: 4.6.1

## Repro steps:
Given following code:
```
	val someVariable: Boolean? = null
	someVariable shouldNotBe true
```

IDE shows a warning and suggests a replacement that will fail the test
![image](https://user-images.githubusercontent.com/36954793/126760984-82c58078-b436-4129-9048-3d1ffa6df93a.png)

## Use-case
In my specific case I want to verify if google's `LiveData` instance doesn't have specific value. I don't care if it is false or null - I consider that an implementation detail. I assumed making an `shouldNotBe true` is a valid way of checking that but IDE shows a warning with an invalid fix hence this issue.

**Comment by sksamuel** [comment]
@Kantis we talked about just removing this inspection.

**Comment by Kantis** [comment]
Do you prefer that over using type-analysis to determine if LHS of expression is nullable and in that case disable warning? I'm fine either way. I'll remove for now if we are unsure?

Type resolution uses intellij build caches. Not sure if that's something we could/should use..
https://github.com/kotest/kotest-intellij-plugin/blob/32972bc3bb91f49aa6f332b1d8086115109019e6/src/main/kotlin/io/kotest/plugin/intellij/inspections/ShouldBeWithUnequalTypesInspection.kt#L45-L50

**Comment by sksamuel** [comment]
I think the OP has a good point that the inspection just doesn't work.

**Comment by sksamuel** [comment]
So yeah I would just remove it and we can play with the types for the shouldBe analysis.
