### ISSUE TITLE
`%1 is not a valid Win32 application` when running with WSL backend

### ISSUE THREAD

**Issue by Strum355** [kotest/kotest#5442]
`22:37	Error running 'AnalyzerTest: basic test': Cannot run program "\\wsl$\Arch\home\noah\.cache\coursier\jvm\adopt@1.11.0-11\bin\java" (in directory "\\wsl$\Arch\home\noah\Sourcegraph\lsif-kotlin\semanticdb-kotlinc"): CreateProcess error=193, %1 is not a valid Win32 application`

Repro repo can be found [here](https://github.com/Strum355/lsif-kotlin/), with the particular test file located [here](https://github.com/Strum355/lsif-kotlin/blob/nsc%2Fkotest-failure/semanticdb-kotlinc/src/test/kotlin/com/sourcegraph/semanticdb_kotlinc/test/AnalyzerTest.kt). Gradle is configured to use the Java distribution in WSL.

Let me know if you need any more specific information 🙂

**Comment by franzvezuli** [comment]
Thanks for reporting, just came here to say the same. I flip between OSX and Windows (using WSL) often, and would be great to have the ability to run a single unit test in Windows.

Also related, I had to update to IntelliJ 2021.2 EAP because of this issue as well: https://youtrack.jetbrains.com/issue/KTIJ-11628#focus=Comments-27-4918500.0-0

**Comment by sksamuel** [comment]
Is this only happening with Kotest?

**Comment by franzvezuli** [comment]
> Is this only happening with Kotest?

I don't run that many plugins, but I can verify that IntelliJ 2021.2 EAP with Kotlin on Windows (WSL2) works with JUnit. But I really like Kotest! For now compiling and running tests through the command line works, just not in the idea. Again, only an issue with Windows using WSL2

**Comment by buzoherbert** [comment]
I have the same issue, does anyone know if there is a fix for using this plugin and WSL?

**Comment by msttmms** [comment]
Hello everyone, I am experiencing the same issue.

**Comment by pacdouglas** [comment]
Hello! I have got the same issue...

**Comment by DragonString** [comment]
Hello, I have got the same issue too..

**Comment by talhademir4** [comment]
Hello! I have got the same issue...

**Comment by meechew** [comment]
The latest update to PHPstorm caused this error to pop up for all attempts to run any PHP code in WSL with PHPstorm.
