### ISSUE TITLE
Unable to run single test

### ISSUE THREAD

**Issue by ltennstedt** [kotest/kotest#5443]
It's not possible to run a single test from the editor or from the test results the run pane. The gutter Icons are not shown for contexts and tests (FunSpec).

Kotlin version: 1.5.10
Kotest version: 4.6.0
JUnit Jupiter version: 5.7.2
JUnit Platform version: 1.7.2
IntelliJ IDEA version: 2021.1.2 (Ultimate Edition)
Kotlin Plugin version: 211-1.5.10-release-891-IJ7142.45
Kotest Plugin version: 1.1.36-IC-2021.1
Gradle version: 7.1
JDK: Azul Zulu 8.54.0.21-CA-linux64 (OpenJDK 1.8.0_292b10)
OS: Ubuntu 20.04 LTS

![editor](https://user-images.githubusercontent.com/27898583/122670555-fa695600-d1c2-11eb-80a7-97d33f207eea.png)

**Comment by sksamuel** [comment]
This is exactly what the plugin is used for. Try using a class instead of an object and see if that fixes it ?

**Comment by ltennstedt** [comment]
This fixes the problem. Gutter icons are shown and I can run a single test. Thanks.

**Comment by sksamuel** [comment]
The plugin should support objects too so I'll leave this open.
