### ISSUE TITLE
Run single FunSpec from gutter icon does not work in custom source set

### ISSUE THREAD

**Issue by mkotsbak** [kotest/kotest#5446]
From https://github.com/kotest/kotest/issues/5457#issuecomment-789794020 in kotest/kotest#5457.

Running a whole test from the gutter icon works, but nothing happens when clicking on a single test within the class.

Using version 1.1.36-IC-2020.3.

**Comment by sksamuel** [comment]
Just to clarify you can see the green icons but they do nothing?

**Comment by mkotsbak** [comment]
Yes, I see them, they are clickable and it changes run configuration, but nothing happens.

**Comment by sksamuel** [comment]
Can you take a screen grab of the run config ?

**Comment by mkotsbak** [comment]
Hmm, I cannon reproduce this with project `kotest-examples/kotest-examples-jvm` from https://github.com/kotest/kotest

**Comment by mkotsbak** [comment]
Here is config failing:

![image](https://user-images.githubusercontent.com/296523/117151848-bdcfcf80-adb9-11eb-9938-0972848f81e1.png)

In one test interestingly "debug" and "coverage" config worked, but not normal run. "Run" button is probably disabled because it runs or Intellij thinks it runs, but there is nothing in "run" tab.

**Comment by sksamuel** [comment]
Can you try removing the quote marks from the test name and seeing if that
makes a difference?

**Comment by mkotsbak** [comment]
You mean 'kind'? Same without, but I think I have narrowed it down to parts of the codebase where we use a separate integration testing source set. Where we don't, it actually works now :)

**Comment by sksamuel** [comment]
ohhhh
