### ISSUE TITLE
Does plugin support custom spec?

### ISSUE THREAD

**Issue by Jacks0N23** [kotest/kotest#5449]
I have custom spec — AllureBehaviorSpec.
Could I run my spec through this plugin?

**Comment by sksamuel** [comment]
Does allure spec extend one of the other specs?
It looks for the spec classes on the classpath and also for the structure they define.
If you have a custom structure then no it won't.

**Comment by Jacks0N23** [comment]
Yes, I have Spec extended from DslDrivenSpec and written in BehaviorSpec style but with custom actions for allure

**Comment by sksamuel** [comment]
Right, so it only looks for classes extending one of the concrete spec
styles (that's easy enough to update though).
But it does have hard coded rules to look for certain layouts - is your
behavior spec layout the same?

**Comment by Jacks0N23** [comment]
yeah, I have similar classes, but with name *Context instead of Scope, like: GivenContext, WhenContext
and their content also similar to Behavior's one
