### ISSUE TITLE
Failing kotest assertion seems to not be correctly propagated to test results in IntelliJ

### ISSUE THREAD

**Issue by bjpe** [kotest/kotest#5450]
Hi everyone, 

I'm not sure if this is the right project, so I also reported it under https://github.com/kotest/kotest/issues/2192.

We a have project with Java and Kotlin code, and both have JUnit and kotest tests (we are migrating from Java to Kotlin). When we execute all tests in IntelliJ using the context menu action Run 'All Tests', we observed the following irritating behaviour:
* Both JUnit and kotest tests are executed (good)
* A failing JUnit assertion marks the test class and the entire test executed as failed (good)
* A failing kotest assertion does not mark the test class and the entire test executed as failed (bad)

I just created https://github.com/bjpe/kotest-bug as an example code base, and the test execution results looks as follows:
![image](https://user-images.githubusercontent.com/449704/113974537-5ec07e80-983e-11eb-8aa7-8fff7a6094e3.png)

What we would expect is that kotest.FailingKotestTest is marked as failed as well. Strangely, if I open the same result via the "Test History" option, the result is as expected:
![image](https://user-images.githubusercontent.com/449704/113974786-c8d92380-983e-11eb-915c-9ff650c30295.png)

I'm using IntelliJ 2021.1 with kotest plugin 1.1.30-IC-211-EAP-SNAPSHOT. If you need more details, please give me a hint.

Kind Regards,
Björn

**Comment by sksamuel** [comment]
Not an issue with the plugin - replied on the other ticket.
