### ISSUE TITLE
BehaviorSpec tests must be run from class level, or always pass

### ISSUE THREAD

**Issue by sarinarw** [kotest/kotest#5451]
Using each green arrow shown in the below image to run the test, all pass (which they should not), except for the `class`-level run.
<img width="450" alt="Screen Shot 2021-03-11 at 11 55 57 AM" src="https://user-images.githubusercontent.com/9454101/110841296-f55f4700-8262-11eb-91af-2bf0a619036c.png">

Code for reference:
```
class KotestTest3 : BehaviorSpec({
    given("a broomstick") {
        When("I sit on it") {
            then("I should be able to fly") {
                true shouldBe false
            }
        }
    }
})
```

Repro Steps:
1. Create Kotlin+Gradle project using:
```
    testImplementation("io.kotest:kotest-runner-junit5:4.3.1")
    testImplementation("io.kotest:kotest-assertions-core:4.3.1")
```
2. Create file with above test
3. Run at each level (then/when/given/class)

**Comment by dajulia3** [comment]
I've noticed the same behavior with DescribeSpec.

**Comment by sksamuel** [comment]
David did you try the latest plugin version 34?

**Comment by sksamuel** [comment]
@sarinarw I cannot duplicate this on the latest versions.

I am using 4.4.3 and the latest intellij plugin. At each level I get:

![image](https://user-images.githubusercontent.com/743706/116788530-bb930b80-aa6f-11eb-9a96-64a186135af6.png)

Would you be able to try the latest versions to see if it works for you ?

**Comment by sksamuel** [comment]
Closing because cannot duplicate.
