### ISSUE TITLE
Tool window: After jumping to a test, caret is replaced

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5454]
Reproduce:
- Open Kotest Tool Window
- Single-click on a test
  - -> Caret jumps to the test
- Click to set the caret somewhere else
- Type one character
  - -> Character will be displayed as expected.
  - -> After that the caret however will be positioned back to the test's name ❌ 

Screencast:
https://user-images.githubusercontent.com/7399011/105196042-7e97ae80-5b3b-11eb-985d-a3401e45e11b.mov

---
Plugin version: 1.1.24-IC-2020.3
IntelliJ version: Build #IU-203.7148.40, built on January 19, 2021

**Comment by enolive** [comment]
Affects me as well. Observed it both on my Windows and Linux machine with several versions of IntelliJ 2020.x

**Comment by sksamuel** [comment]
This is fixed in the latest version of the plugin. It usually takes Jetbrains 1-2 working days to approve the release - so hopefully by close of business Monday it will be in the marketplace, if not then Tuesday.

**Comment by sksamuel** [comment]
And thanks for the bug report @theHacker @enolive
