### ISSUE TITLE
Gutter icon "interpolated name" is shown in Diff view

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5455]
When opening a Diff window, normally there aren't any "play" icons in the gutter to run tests.
The question-mark icon (Text: `Tests with an interpolated name cannot be run by the plugin.`) is still shown in Diff view.

I believe it should be removed there.

**Screenshot**
![kotest-plugin-issue119](https://user-images.githubusercontent.com/7399011/104716893-d04dcc80-5728-11eb-87e8-77811b48bff7.png)

---
Plugin version: 1.1.24-IC-2020.3
IntelliJ version: Build #IU-203.6682.168, built on December 29, 2020

**Comment by theHacker** [comment]
\*activity* 🤨

**Comment by sksamuel** [comment]
Ticket pinned.

**Comment by sksamuel** [comment]
Fixed in latest plugin release.
