### ISSUE TITLE
context in describe spec doesn't run single tests

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#5457]

**Comment by lwasyl** [comment]
Sample code
```kotlin
package com.example

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe

class SampleSpec : DescribeSpec() {

    init {
        describe("foo") {
            describe("bar") {
                context("baz") {
                    it("fizzbuzz") {
                        2 shouldBe 4
                    }
                }
            }
        }
    }
}

```
1. run test at line with `it` with gutter icon
2. Test path in the configuration is `foo -- bar -- fizzbuzz`, ignoring `context` block

**Comment by DarkFelex** [comment]
Can confirm exactly the same issue with `BehaviorSpec`.

**Comment by mkotsbak** [comment]
Looks like same problem with FunSpec too.

**Comment by sksamuel** [comment]
There is an update pending approval with jetbrains that fixes this for Describe and Fun Specs.

BehaviorSpec will be fixed in the update after that.

**Comment by sksamuel** [comment]
BehaviorSpec is fixed in the latest plugin too. Any further issues please reopen or file another ticket.

**Comment by mkotsbak** [comment]
Ok, opened kotest/kotest#5446 for FunSpec.
