### ISSUE TITLE
Intellij reacting very slow in larger WordSpec

### ISSUE THREAD

**Issue by tekener** [kotest/kotest#5461]
In my team all of us are expiring slow autocompletion, import fixes, closing curly braces finding, etc. in a kotest file using WordSpec and having around 12 tests.

When i deactivate the kotest plugin it is getting better.
I am currently running on 2020.3 beta because i thought this problem might has been fixed there but it is still there.
Does somebody else has the same sluggish behaviour? 

Thank you

**Comment by sksamuel** [comment]
Have you tried kotlin plugin 1.4.20. They seem to have fixed a lot of speed issues in the latest release.

**Comment by tekener** [comment]
Hi @sksamuel,
tried the new 1.4.20 plugin the last days and it is much better now.
