### ISSUE TITLE
plugin output gets messed up when tests run in parallel

### ISSUE THREAD

**Issue by christophsturm** [kotest/kotest#5463]
when I run the testsuite of my https://github.com/christophsturm/r2dbcfun project in idea the test runner output has multiple problems: 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1999/98965795-c0d4bc00-250a-11eb-9cf3-fe7c4aee425c.png">

test contexts seem to be mixed up, and also the spinner that indicates that the test is still running does not disappear. The total test time is also not displayed correctly.

**Comment by sksamuel** [comment]
This should be fixed in 4.4
