### ISSUE TITLE
<Click to see difference>

### ISSUE THREAD

**Issue by PhilipDukhov** [kotest/kotest#5466]
When I run tests with JUnit and a test fails, there's a clickable line `<Click to see difference>`, it opens Comparison Failure window. I miss that when work with your plugin, would be cool to have it.

**Comment by sksamuel** [comment]
Should be there already, do you have sample code ?

**Comment by PhilipDukhov** [comment]
sure, check it out: https://github.com/PhilipDukhov/KotestTest

**Comment by enolive** [comment]
I am having the same problem.

After some investigation, it seems that the kotest runner does not seem to handle java.lang.AssertionError with a preformatted message which the junit runner seems to automagically parse and present a diff dialog.

reproduction test:

```kotlin
class ApplicationTests(
) : FunSpec({
  test("will show diff dialog link in junit runner, but not in kotest") {
    throw AssertionError("expected: true but was: false")
  }
})
```

Sadly this means that many default assertions will not produce a diff dialog option in the kotest test runner.

A convenient way that always works would be to use opentest4j`s AssertionFailedError(message, expected, actual) which many assertion libraries use if available (kotest as well, for instance when using shouldBe).

```kotlin
  test("will show diff dialog link both in junit runner and kotest") {
    throw AssertionFailedError("expected: true but was: false", true, false)
  }
```

I don't have a clue how to implement this using kotest`s MatcherResult that is used in most matchers as it does not transport the actual and expected values.

**Comment by orange-buffalo** [comment]
I am also facing this issue. For instance, when a test has JSON assertion:
```
"{}".shouldMatchJsonResource("/my/json/resource");
```
It fails without "Click to see difference":
```
expected:<{}> but was:<{"context_of_resource"}>
```
It makes it extremely hard to work with larger strings like JSON.

@sksamuel, would you like me to prepare a full-fledged reproducer project or is the problem clear?

**Comment by Kantis** [comment]
I believe this is mostly fixed since a long while. It could be missing on a case-by-case basis. If it's failing, it's most likely a bad matcher which needs to be fixed. Feel free to open issues in the main kotest repo for it if you find more problems. (I verified that `shouldMatchJson` and `shouldMatchJsonResource` are both showing the `show diff` option)

**Comment by comm1x** [comment]
The issue still actual for Kotest 5.6.0, 5.9.0. No button see the difference. But JUnit works fine

Kotest shouldBeEqual:

<img width="1767" height="132" alt="Image" src="https://github.com/user-attachments/assets/64066f34-fb55-48b3-82db-1c414fff2a3e" />

JUnit assertEquals:

<img width="1806" height="220" alt="Image" src="https://github.com/user-attachments/assets/90abf21b-0fba-471b-8362-f88c501d25e3" />

**Comment by sksamuel** [comment]
It's an issue in the framework not the plugin actually.
If you update Kotest to 6.0 it's fixed in most places (might be some obscure matchers that are not yet migrated but all the shouldBe stuff is migrated).
