### ISSUE TITLE
Run test icon dissapears when @DisplayName is used

### ISSUE THREAD

**Issue by codenamite** [kotest/kotest#5469]
When having a test without the @DisplayName annotation - there is a green run button next to the test class name:

![Without @DisplayName](https://i.ibb.co/C0nmztK/kotest1.png)

But using the @DisplayName annotation, the button dissapears:

![Without @DisplayName](https://i.ibb.co/Qr2LJMT/kotest2.png)

It is a little bit annoying, in this case I can just run the only context I have declared, but having multiple contexts makes this irritating a bit ;)

**Comment by sksamuel** [comment]
There is a new plugin release pending approval by Jetbrains (they have to approve each upload) that will fix this.
Should be approved by Tuesday.

**Comment by sksamuel** [comment]
Fixed in latest plugin.

![image](https://user-images.githubusercontent.com/743706/96523860-606c9a80-123c-11eb-816d-66a1e5e1b434.png)
