### ISSUE TITLE
Adding annotations to a test prevents the test from running

### ISSUE THREAD

**Issue by Zefz** [kotest/kotest#5471]
```
class SampleTest : BehaviorSpec()
```
Works fine.

```
@Category(UnitTest::class)
class SampleTest : BehaviorSpec()
```
Cannot be run with kotest as an individual test. (gutter icon disappears and right click context menu does not work anymore). This seems like a regression since this worked before I updated the kotest plugin.

**Comment by sksamuel** [comment]
What is @Category

**Comment by Zefz** [comment]
A JUnit feature. It's the same as `@Tag`.

But the type of annotation is irrelevant, it will fail as long as you add any annotation.

**Comment by sksamuel** [comment]
Ok. I assume there are tests inside the class and you're talking about the
green play icon at the test level and not the class level ?

**Comment by Zefz** [comment]
Yes that is correct.

Test cannot be run (gutter icon missing):
![image](https://user-images.githubusercontent.com/1359524/96218491-1d34d200-0f85-11eb-9d9f-82c06a888b92.png)

Commenting away the annotation fixes the issue. Test can be run:
![image](https://user-images.githubusercontent.com/1359524/96218646-7866c480-0f85-11eb-8c93-5d44551efa20.png)

**Comment by Zefz** [comment]
Note that just running the Given step below does not work either. Then it will run only the Given block (and not the sub When/Then levels) and nothing else in the test.

**Comment by theHacker** [comment]
I can confirm this issue also for tests using Micronaut.
If a test class has `@MicronautTest` the test icon in the gutter is missing.
Commenting the annotation, the icon re-appears.

The issue is introduced with a plugin update.
Just saw my colleague updating Kotest plugin to 1.1.19-IC-2020.2. After the update, the icons were missing.

IntelliJ versions 2020.2.2 (202.7319.50) and the new EAP4 (203.4818.26).

**Comment by sksamuel** [comment]
Yep I can confirm the bug is any annotation stops the parent class lookup
from working.

Fix is to manually install the previous version of the plugin.

**Comment by sksamuel** [comment]
There is a new plugin release pending approval by Jetbrains (they have to approve each upload) that will fix this.
Should be approved by Tuesday.

**Comment by sksamuel** [comment]
Fixed in the latest plugin release.

![image](https://user-images.githubusercontent.com/743706/96523832-4df26100-123c-11eb-8472-0d95195ea367.png)
