### ISSUE TITLE
Kotest plugin does not detect custom or inherited test specs

### ISSUE THREAD

**Issue by Zefz** [kotest/kotest#5472]
The kotest plugin does not detect tests that use from custom or inherited specs. Minimal example:

```
class ScenarioSpec : BehaviorSpec()
```

`MyUnitTest : ScenarioSpec() // Not detected by kotest`

I cannot run MyUnitTest as an individual test (no right click context menu) and no icons are shown in the gutter. This issue also affects users creating their own custom specs when using this plugin.

I would expect kotest to detect and work with any test that inherits from the `Spec` abstract class.

**Comment by sksamuel** [comment]
There is a new plugin release pending approval by Jetbrains (they have to approve each upload) that will fix this.
Should be approved by Tuesday.

**Comment by sksamuel** [comment]
The new plugin has been released and this is working now
![image](https://user-images.githubusercontent.com/743706/96523762-2ac7b180-123c-11eb-923e-f12f6c0376a9.png)
