### ISSUE TITLE
Navigate -> Go to Test Subject doesn't work in specs

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#5477]
Normally the `navigate -> go to test (subject)` shortcut (cmd + shift +T) works differently in project sources and in tests:
 - in project sources the shortcut navigates to the test for given class
 - in test, the shortcut navigates to the tested class

With Kotest's IJ plugin navigation _to the test_ works. But when pressing cmd + shift + T inside the spec, I'm only offered to go _to the same test_ only, and the tested class is not a choice. Correct behavior would be not show the spec class at all and instead offer to the tested class (I think IJ infers it from the test class name), and navigate to that class immediatelly if there's only one candidate

**Comment by sksamuel** [comment]
Does your test class and the normal class have the same name but with Test on the end ?

**Comment by lwasyl** [comment]
They have the same name but with `Spec` suffix, not `Test`, but when I rename the test to `<TestedClass>Test` the behavior is still wrong

**Comment by sksamuel** [comment]
I cannot duplicate this. I have PropsPreprocessor and PropsPreprocessorTest and using ctrl shift T I can hop between them.

**Comment by olaforest** [comment]
This issue seemed to be fix in the previous version of kotest's IntelliJ plugin, but in the latest version seemed to have regressed. I see the exact behavior described above by @lwasyl with StringSpec and FreeSpec.

**Comment by huehnerlady** [comment]
I can confirm with version `1.1.20-IC-2020.2` I experience the same behaviour as described above with DescribeSpec

**Comment by sksamuel** [comment]
I've fixed this in master. If someone(s) are willing to test, let me know which version of intellij you are using and I will upload a build for that version.

**Comment by sksamuel** [comment]
I will close this since this has been fixed in the last release. If anyone is still having issues, please reopen.
