### ISSUE TITLE
Command line is too long

### ISSUE THREAD

**Issue by coreORB** [kotest/kotest#5479]
Android Studio version: 4.0.1 (based probably on Intellij 2019.3.3)
kotest version: 4.2.3
kotest plugin version: 1.1.16-IC-2019.3

Then I try to run any test in my main bigger project, I'm getting the error:
![obraz](https://user-images.githubusercontent.com/6077897/92406131-854af980-f137-11ea-8c62-c52da7330c30.png)

I've tried doing same thing on newly created project and it's working as expected.
Maybe adding "shorten command line" option to Kotest run configuration will solve this issue?

**Comment by sksamuel** [comment]
Can you show me the command line? I wonder if your classpath is huge.
If you need to obfuscate you can.

**Comment by coreORB** [comment]
It's not showing any output in run window. I've tried to google where to view it, but no luck.
Could you tell me where I can find it?

**Comment by sksamuel** [comment]
Does it work if you choose the shorten option?

**Comment by coreORB** [comment]
This option is not available for me for Kotest:
![obraz](https://user-images.githubusercontent.com/6077897/92413823-25158100-f152-11ea-8b9f-f256d610d1cc.png)

but it is for JUnit:
![obraz](https://user-images.githubusercontent.com/6077897/92413875-59893d00-f152-11ea-9aef-d0b432d12b73.png)

**Comment by sksamuel** [comment]
I have a build that fixes this if you want to test it locally ?
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip](https://github.com/kotest/kotest-intellij-plugin/files/5256189/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip)
You would need to remove your existing plugin first and restart and install this one manually from the settings -> plugins -> cog icon.

**Comment by coreORB** [comment]
Thank you for quick, new build.
Unfortunately, I cannot install it. The message is "Plugin 'kotest' is incompatible with this installation". 
I'm using Android Studio version 4.0.1. When I click Help -> IntelliJ IDEA Help, it redirects me to https://www.jetbrains.com/help/idea/2019.2/installation-guide.html, so I assume it's based on IntelliJ 2019.2.
Would it be possible to prepare plugin compatible with this version?

**Comment by sksamuel** [comment]
[Uploading kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip…]()
Try this

**Comment by coreORB** [comment]
Unfortunately, the link is wrong. Could you paste new one?

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip](https://github.com/kotest/kotest-intellij-plugin/files/5261401/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip)

Strange, try this one.

**Comment by coreORB** [comment]
I was able to test it today and it's working with both "JAR Manifest" and "classpath file". Thank you! 👍

**Comment by sksamuel** [comment]
Great, I'll cut an official release this weekend.

**Comment by sksamuel** [comment]
Fixed in the version that's pending release.
