### ISSUE TITLE
Running a "FreeSpec" causes "Test framework quit unexpectedly" error

### ISSUE THREAD

**Issue by Obirah** [kotest/kotest#5481]
When I run any "FreeSpec" (no matter if it's nested or not) from IntelliJ (no matter if it's the whole spec or a single test), I get a "Test framework quit unexpectedly" error with the following versions:

OS: MacOS 10.15.6
Java: 14
IntelliJ: 2020.2.1
KoTest: 4.2.2
KoTest Plugin: 1.1.16-IC-2020.1

Running the same "FreeSpec" from gradle works without any problems, so I guess it must have something to do with the plugin.

On the contrary, when I run a "StringSpec" from IntelliJ everything works as expected.

If I downgrade KoTest to 4.2.0.RC2, running the "FreeSpec" from IntelliJ works again.

**Comment by sksamuel** [comment]
Can you paste me the end of the classpath string.
Should look something like this:
io.kotest.engine.launcher.MainKt --spec
com.sksamuel.kotest.assertions.AssertionCounterFreeSpecTest --testpath
container should not need to have an assertion --reporter teamcity

**Comment by Obirah** [comment]
Sure, here you go: `io.kotest.engine.launcher.MainKt --spec de.db.dbcs.dpp.BugSpec --reporter teamcity`

**Comment by sksamuel** [comment]
That looks fine, shouldn't cause the Test framework quit unexpectedly error.
Are you sure there's no earlier versions of kotest floating about in the
build ?

**Comment by Obirah** [comment]
Yeah, I'm pretty sure. I did both a `./gradlew clean` and `./gradlew build --refresh-dependencies`. Also deleted the build directory of the project and deleted the IntelliJ run configurations and let them be recreated.

Is there any other spot that requires cleanup I might be missing?

**Comment by sksamuel** [comment]
No, I don't think it's cleanup. This error might happen if your test was
throwing an error at instantiation time.

Can you do something like

class Foo : FreeSpec() {
init {
   "a" - {
      "b" { }
   }
}
}

And see what happens on that test ?

**Comment by Obirah** [comment]
This results in the same "Test framework quit unexpectedly" error. Also, it doesn't matter which part of the test I execute - I tried all three possibilities:

`io.kotest.engine.launcher.MainKt --spec de.db.dbcs.dpp.Foo --reporter teamcity`
`io.kotest.engine.launcher.MainKt --spec de.db.dbcs.dpp.Foo --testpath a --reporter teamcity`
`io.kotest.engine.launcher.MainKt --spec de.db.dbcs.dpp.Foo --testpath a -- b --reporter teamcity`

**Comment by huehnerlady** [comment]
HI, I have the same problem, I use 
intellij 2020.2.1 
kotest plugin 1.1.16-IC-2020.1
kotest: 4.2.0
Java 14
kotlin 1.4.0
OS: MacOS 10.15.5

**Comment by sksamuel** [comment]
Try 4.2.2 Ruth.

**Comment by huehnerlady** [comment]
@sksamuel it is as @Obirah says, same problem, with 4.2.0.RC2 it works, from 4.2.0.RC3 upwards it does not work anymore

running with gradle all versions work though, so I agree it seems to be the plugin

**Comment by huehnerlady** [comment]
@sksamuel will this be fixed soon? This is a very very irritating error...

**Comment by huehnerlady** [comment]
@Obirah can you try 4.2.3?
Just came out moments ago. I tried it and so far I do not have that problem anymore :)

**Comment by Obirah** [comment]
Ah cool, everything works, yes. Thank you for the information. :)

**Comment by sksamuel** [comment]
Yay.
