### ISSUE TITLE
Plugin doesn't recognize scoped callbacks introduced in Kotest 4.2

### ISSUE THREAD

**Issue by reevn** [kotest/kotest#5487]
With Kotest 4.2 new scoped callbacks like `beforeEach`/`afterEach` were introduced.

The plugin doesn't recognize these callbacks in the plugin window like it does for `beforeTest`/`afterTest`.

The plugin window should also show these new callbacks:
- `beforeContainer`/`afterContainer`
- `beforeEach`/`afterEach`
- `beforeAny`/`afterAny`

**Comment by sksamuel** [comment]
Yes good catch (the tool window right).

**Comment by sksamuel** [comment]
Fixed in latest plugin.
