### ISSUE TITLE
VM params are not saved in run configurations

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#5488]

**Comment by Phil-87** [comment]
A bit more info - if anything is entered in the "VM options" field it is lost when IntelliJ is closed. This field is also not being saved when using the "Store as project file" option.

**Comment by sksamuel** [comment]
Fixed in master.

**Comment by sksamuel** [comment]
Please try 1.1.9 plugin.

**Comment by Phil-87** [comment]
This is working correctly now.
