### ISSUE TITLE
[MAC] Intellij shortcut CTRL+shift+R does not work as expected

### ISSUE THREAD

**Issue by huehnerlady** [kotest/kotest#5490]
There are different ways to use the shortcut `CTRL + SHIFT + R` in intellij:

I tested this using the FreeSpec of kotest

1. Inside a test - should just run this test ✅ 
1. Inside a nested test -> should run all tests inside this nested test ✅ 
1. inside the init block -> should run all tests ❌  This does seem to ignore the shortcut
1. outside the init block inside the test class -> should run all tests in this class ❌  This does seem to ignore the shortcut

Observations, not necessarily unexpected behaviour:
* There is no arrow next to the init block, but next to the main class and all test, incl. nested tests:
![image](https://user-images.githubusercontent.com/12533979/88402542-8e704900-cdcb-11ea-8a49-f9081372cce4.png)

* running the nested test using the error on the side works as expected

* Running tests using the error at class level works as expected
![image](https://user-images.githubusercontent.com/12533979/88402041-d93d9100-cdca-11ea-8391-9c88b4c6dd93.png)

* `CTRL + R` after using working shortcut or the arrow next to tests works in every case as expected 

Any chance you can look at this issue and fix it? Being used to this behaviour from JUnit and spock tests this feels not as smooth as I expected it to feel as I always have to scroll all the way up to run all tests :)

**Comment by lwasyl** [comment]
Still relevant
