### ISSUE TITLE
 Kotest plugin shouldn't require console dependency in build to run tests

### ISSUE THREAD

**Issue by jonbarksdale** [kotest/kotest#5494]
Before the kotest plugin, I could run my tests from the IDE without the console dependency.  After the kotest plugin, I can only run them if I manually configure a run configuration to use gradle or junit. 

Requiring a build dependency for an IntelliJ plugin couples your build to your IDE - that's just bad. 

At a minimum, the tests should run with gradle/junit if the console jar is not present, even if there is reduced functionality. 
Ideally, the console jar would either be packaged with the plugin, or offer to download and cache the console jar for the user, similar to how IntelliJ works with gradle versions, or other libraries that are version specific.

For perspective, adding new dependencies is not trivial for my company, as each dependencies graph needs to be imported into our non maven build system. It's not fun, don't recommend.  I've done it for Kotest, but I see no reason I should need to do it for console.

**Comment by sksamuel** [comment]
Downloading the dependencies in the plugin would be nicer than adding it to the build.

**Comment by sksamuel** [comment]
The latest plugin no longer requires console dependency. In fact console has gone away entirely.
