### ISSUE TITLE
re-run action bugs

### ISSUE THREAD

**Issue by zeitlinger** [kotest/kotest#5497]
using the following code and the latest kotest (updated today)

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.core.spec.style.StringSpec
import io.kotest.data.forAll
import io.kotest.data.headers
import io.kotest.data.row
import io.kotest.data.table
import io.kotest.matchers.shouldBe


class DataTestingTest : FreeSpec() {
   init {
      "numbers should add up to ten" - {
         forAll(table(
             headers("a", "b"),
             row(5, 5),
             row(4, 6),
             row(3, 7)
         )) { a, b ->
            "$a + $b shouldBe 10" - {
               a + b shouldBe 10
            }
         }
      }
   }
}
```

# first bug

1. click right on `5 + 5 shouldBe 10`
2. click create ...
3. get the following screenshot
4. what should be in testpath: `numbers should add up to ten -- 5 + 5 shouldBe 10` (test execution is fine when I do it manually)

![image](https://user-images.githubusercontent.com/2832627/86217644-0f974000-bb80-11ea-9a04-004014a64339.png)

# second bug

right clicking on any other node (Test Results, DataTestingTest, numbers should add up to ten) does allow to re-run

This example has no re-run action at all

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe


class DataTestingTest : FreeSpec() {
    init {
        "run re-run action possible here" {
            1 + 2 shouldBe 4
        }
    }
}
```

**Comment by sksamuel** [comment]
In your first bug, the final inner tests should not be created with the minus sign after the string.

**Comment by sksamuel** [comment]
In the second bug, by re-run, do you mean in the test results window ?

**Comment by zeitlinger** [comment]
> In your first bug, the final inner tests should not be created with the minus sign after the string.

1. the result is the same with `"$a + $b shouldBe 10" {`
2. it's a bit confusing that the `-` makes such a difference. Maybe the "wrong" version should not compile (just thinking out loud)

**Comment by zeitlinger** [comment]
> In the second bug, by re-run, do you mean in the test results window ?

yes

![image](https://user-images.githubusercontent.com/2832627/88545278-0e402280-d01b-11ea-8e2d-d1a99e2aeffc.png)
