### ISSUE TITLE
Repeated errors reported when opening test files in project that uses v3.3.3 of Kotlintest

### ISSUE THREAD

**Issue by lgtout** [kotest/kotest#5498]
After installing the latest version of Kotest IntelliJ plugin, when I open a project that uses Kotlintest v3.3.3, I get 2 or 3 errors in Android Studio's Event Log each time I open a file that contains tests.

My expectation would be that the plugin might 
(1) Not report this error, since some users will want to remain on earlier versions of Kotlintest for all sorts of reasons. 
(2) If reporting the error, would only do so once per project per IDE run, not multiple times per test file.

![47_degrees_building_functional_android_apps_workshop____dev_47_degrees_building_functional_android_apps_workshop__-_____sampleapp_src_test_java_com_fortyseven_sampleapp_Exercise5_kt__sampleapp_](https://user-images.githubusercontent.com/364799/86084262-37d45100-ba51-11ea-886c-00df2e544e68.gif)

**Comment by sksamuel** [comment]
The plugin requires kotest 4.1 as the readme states.

**Comment by lgtout** [comment]
@sksamuel 
That's fine.  But one message is enough, right?  Why spam the event log?  

And why do so when all the developer has done is open a file that contains Kotest tests?  Why not wait until the developer actually tries to run a test using Kotest?  After all, opening a file doesn't necessarily mean the developer intends to run it.  Or that, if the developer wants to run it, they intend to use the Kotest plugin to do so.

And wouldn't it be better for the plugin to be resilient enough to allow for cases where the developer can update to 4.1 in some projects, but (for whatever reason) can't do so on other projects?  

I often open up multiple projects with dependencies on wildly varying versions of the same library.  That's more the norm than the developer being able to enforce minimum versions of libraries in projects that he/she may not even own.

Don't get me wrong.  These are clearly not serious issues.  Kotest is awesome!  And if the IDE plugin were only half as good as it is I would still be happy to use it.

**Comment by sksamuel** [comment]
I see what you mean now. Just because the plugin in installed doesn't mean you're working on a 4.1 kotest project, or even a kotlin project at all.

I'll fix this and release 1.0.4.

**Comment by sksamuel** [comment]
1.0.4 has been submitted to Jetbrains for approval (note 1.0.3 is also awaiting approval so you might get two updates in short succession).

**Comment by lgtout** [comment]
Awesome!  Thanks @sksamuel!
