### ISSUE TITLE
False-positive "Classes must have a zero arg constructor to be instantiated by Kotest" with Micronaut

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5500]
The inspection should not complain about a class with non-zero-arg constructor, when it is annotated with `@MicronautTest` (`io.micronaut.test.annotation.MicronautTest`).

Micronaut will handle the magic of creating the test instance and injecting the required beans.
See https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html#kotest

**Comment by sksamuel** [comment]
Fixed in 1.0.3 pending approval in the plugins store.
