### ISSUE TITLE
Type inference on shouldBe for maps

### ISSUE THREAD

**Issue by georgeVasiliu** [kotest/kotest#5501]
Hello everyone,

Maybe this could be marked as an improvement or such a thing, but I noticed when using the plugin and trying to run some tests that it failed at compile. The error was a type inference error, more specifically the ...environment shouldBe emptyMap() :

![image](https://user-images.githubusercontent.com/26601265/84648831-3c0b5500-af0e-11ea-837d-b63006e4e9eb.png)

![image](https://user-images.githubusercontent.com/26601265/84648951-66f5a900-af0e-11ea-8775-e9945f7f58cb.png)

Setting the type on the emptyMap() receiver fixes this issue :

![image](https://user-images.githubusercontent.com/26601265/84649032-81c81d80-af0e-11ea-9e59-339cd5621d22.png)

However, I imagine it could easily figure out the type of the expected map based on the input, as you can see below the type of the value is set explicit and properly in the class itself:

![image](https://user-images.githubusercontent.com/26601265/84649420-2ba7aa00-af0f-11ea-8274-b7fd9a5cc17c.png)

But the IDE will complain that it's redundant (as it's greyed out), so it's a little bit of confusion there, whether the map should have the explicit type or not set. This is not a real problem, it's just a little bit annoying and in the long term people would be tempted to alt+enter and remove the <String,String> and then they would get the compile error on tests. :)

Any possible solution I could take over my side ? (besides setting the type on the map as I did that already). If not, could this be filed as an improvement/something be done about it?

**Comment by sksamuel** [comment]
I think this is because the new type interference is enabled in intellij but not in gradle.

**Comment by sksamuel** [comment]
This seems to be fine in kotlin 1.4
