### ISSUE TITLE
Wrong Suffix: Appends *KtTest to the file name instead of *Test

### ISSUE THREAD

**Issue by overfullstack** [kotest/kotest#5512]
Steps:
- Place cursor or function or class, press option+enter and choose "Create test"
- Select kotest for Testing Library.
- The default test class file name has a wrong suffix.

Please find the screenshot attached. This is performed on a function named "searchInRotatedSorted2"
Expected default test file name: "SearchInRotatedSorted2Test"
<img width="650" alt="Screen Shot 2020-05-06 at 9 07 37 PM" src="https://user-images.githubusercontent.com/13434911/81197701-3735b600-8fde-11ea-9ea6-5c00558a4a9b.png">

**Comment by sksamuel** [comment]
I think the problem is in intellij, because when it's picking up the classname of your function. When functions are compiled to jvm bytecode, they get this KT suffix.

What happens if you choose another test framework like junit?

**Comment by overfullstack** [comment]
You are right! this only happens with kt files with top-level functions, and it make sense, as they get converted to class files with `Kt` suffix. Closing this issue. Thanks.
