### ISSUE TITLE
Wrong test high lightening on clicking test name in Intellij test report window

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#5514]
Please refer this screen recording posted on kotest-dev slack channel.
https://kotlinlang.slack.com/files/US5P96JFJ/F012C2676DD/kotest-plugin-2.mov

**Comment by sksamuel** [comment]
This should be fixed now with the latest plugin. Can you confirm.

**Comment by ashishkujoy** [comment]
Latest 1.0.3 version is not available in intellij marketplace, I will build it locally and try out.

**Comment by sksamuel** [comment]
It's pending approval by jetbrains. I imagine tomorrow.

**Comment by ashishkujoy** [comment]
Its still same. On clicking the failed test name in run window, it highlights previous test. However, kotest tool window points to the correct test.

**Comment by sksamuel** [comment]
I find this sometimes works and sometimes doesn't.

**Comment by sksamuel** [comment]
I think this only happens for kotest tests itself, because we strip out io.kotest from stack traces, which of course breaks things inside kotest itself.

**Comment by ashishkujoy** [comment]
In that case I think we can close this issue.
