### ISSUE TITLE
Support kotest 4.0.0

### ISSUE THREAD

**Issue by netvl** [kotest/kotest#5524]
Currently this plugin does not know about `io.kotest` classes, making it unusable with the latest `4.0.0-BETA1` release - you can't run individual tests, for example, and have to use native JUnit 5 test facilities which don't work well with kotest.

**Comment by sksamuel** [comment]
Yes, there is work to upgrade this before 4.0 final.

**Comment by rackdon** [comment]
Any update about the state of this task?

**Comment by sksamuel** [comment]
Do you want to try the beta ?

**Comment by qoomon** [comment]
Sure

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-0.90.14.zip](https://github.com/kotest/kotest-intellij-plugin/files/4499926/kotest-plugin-intellij-0.90.14.zip)

Latest build attached. You need to install this in intellij plugins manually. Click the gear icon when you're in the plugins screen.

I've added docs on the features of the plugin to the main readme here:
https://github.com/kotest/kotest-intellij-plugin

**Comment by sksamuel** [comment]
![image](https://user-images.githubusercontent.com/743706/79696490-a8d1de00-8242-11ea-8f1a-c27efb6765ab.png)

**Comment by sksamuel** [comment]
Any feedback?

**Comment by rackdon** [comment]
Until the moment, everything works well. If I encounter any problem I'll write that here.
Thank you very much for the beta

**Comment by qoomon** [comment]
Same here, works as expected. Great job.

**Comment by sksamuel** [comment]
I'm surprised it's been that simple :)

**Comment by nlochschmidt** [comment]
I tried this as well, with IntelliJ 2020.1, kotest 4.0.3 in the project and kotest-runner-console-jvm:4.1.0.251-SNAPSHOT as described in the README.
Worked perfectly for the last couple of hours 👍

_Edit: Anyone reading this later, don't mix the versions like I did. Use the snapshot versions for libs and runner and keep them in the same exact version._

**Comment by sksamuel** [comment]
Great.

**Comment by rackdon** [comment]
It fails with the last Kotest version `4.0.4` and `kotest-runner-console-jvm:4.1.0.259-SNAPSHOT`. 
Doesn't compile the tests correctly to run it inside Intellij

**Comment by sksamuel** [comment]
Please use 4.1.0.259-SNAPSHOT for everything.
4.0.4 introduces some internal changes so that's probably why.

**Comment by rackdon** [comment]
Tested with 4.0.5 and 4.1.0.268-SNAPSHOT -> Everything works but takes a lot of time to compile the tests again and appear the run/debugg button in the left side

**Comment by sksamuel** [comment]
Forget the 4.0.x deps, as they're not meant to be used with the plugin. Use only the latest snapshot.

Can you give me more details / screenshot on what you mean by "appear the run/debugg button in the left side"

**Comment by rackdon** [comment]
Without buttons
<img width="195" alt="image-without-buttons" src="https://user-images.githubusercontent.com/9605759/80344396-ce28a280-8867-11ea-8441-31487bd459a3.png">

with buttons
<img width="167" alt="image-with-buttons" src="https://user-images.githubusercontent.com/9605759/80344422-d680dd80-8867-11ea-9f8e-90a7eaf0ae81.png">

**Comment by sksamuel** [comment]
@rackdon can you try with all your dependencies set to the latest snapshot rather than just the console runner? Also what spec type are you using here.

**Comment by rackdon** [comment]
My previous comment was with both possibilities, only the console runner as latest or all the dependencies as latest and the result is the same in both cases. 
On the other hand, I use StringSpec

**Comment by sksamuel** [comment]
There are tests for gutter icons that are passing on string spec. And it
works for me if I try. You're on 0.90.16 ?

**Comment by rackdon** [comment]
Icons appear, the problem is that takes a lot of time to happen (in comparison with kotest-runner-console-jvm:4.1.0.251-SNAPSHOT).
If you refer to Kotest-plugin version with 0.90.16, not, I'm on 0.90.14 (the version which you shared with us in this issue). There is no versions of the plugin in the marketplace so I can't update it

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-0.90.17.zip](https://github.com/kotest/kotest-intellij-plugin/files/4546328/kotest-plugin-intellij-0.90.17.zip)

Can you try this version and also make sure you're on the kotest snapshot for all kotest deps.

Thanks.

**Comment by rackdon** [comment]
I have the same problem
<img width="149" alt="Captura de pantalla 2020-04-28 a las 16 36 46" src="https://user-images.githubusercontent.com/9605759/80500441-83458280-896e-11ea-8cd9-87031d86499b.png">

def kotest_version = "4.0.5"
My deps are 
	testImplementation 'io.kotest:kotest-runner-console-jvm:4.1.0.269-SNAPSHOT'
	testImplementation "io.kotest:kotest-extensions-spring-jvm:$kotest_version"
	testImplementation "io.kotest:kotest-assertions-arrow-jvm:$kotest_version"
	testImplementation "io.kotest:kotest-runner-junit5-jvm:$kotest_version"
	testImplementation "io.kotest:kotest-assertions-core-jvm:$kotest_version"
	testImplementation "io.kotest:kotest-property-jvm:$kotest_version"

**Comment by sksamuel** [comment]
You're not using the same version for all kotest dependencies. I don't know
if that would help but 4.0.5 shouldn't be mixed with a snapshot.

**Comment by rackdon** [comment]
the only one that is different is `kotest-runner-console-jvm`. I thought that library was  independent from the other

**Comment by sksamuel** [comment]
They're all kind of dependent

**Comment by rackdon** [comment]
As I can't use Kotest snapshot libraries (excepting kotest-runner-console-jvm) in the work, what I've done is establish all the libraries (including kotest-runner-console-jvm) to 4.0.5 version and everything works perfectly. I don't have compilation delays in the tests (as I had before) and all the buttons appears. The only difference is that now also appears the option to run the tests through JUnit (as you can see in the following snapshot), but doesn't matter in my case
<img width="452" alt="Captura de pantalla 2020-04-29 a las 7 10 17" src="https://user-images.githubusercontent.com/9605759/80562692-be849780-89e8-11ea-91a0-5a1b4fa4dd06.png">

**Comment by sksamuel** [comment]
In 4.1.x that unit thing is gone FYI.

**Comment by sksamuel** [comment]
Please use the 1.0.0 kotest plugin from the plugin store, alongside 4.1.0
