### ISSUE TITLE
Error in scoping for output

### ISSUE THREAD

**Issue by bbaldino** [kotest/kotest#5529]
The following test class:
```
class ScopeTest : ShouldSpec() {
    override fun isolationMode(): IsolationMode? = IsolationMode.InstancePerLeaf

    init {
        "scope1" {
            "scope2" {
                should("scope3") {

                }
                should("scope4") {
                    
                }
            }
        }
    }
}
```
when run with the kotlintest plugin (version `3.3.0.11`), looks like this:
![image (1)](https://user-images.githubusercontent.com/4016469/69083076-3e4c1600-09f6-11ea-8e59-4b2d254b4076.png)

But if I delete the kotlintest run configuration and run it with the junit runner, it looks as expected:
![image (2)](https://user-images.githubusercontent.com/4016469/69083110-4dcb5f00-09f6-11ea-98f3-a1d896956fd4.png)

**Comment by sksamuel** [comment]
This is fixed in the new kotest plugin.
