### ISSUE TITLE
Include system environment variables by default

### ISSUE THREAD

**Issue by gigaSproule** [kotest/kotest#5530]
I've just been bashing my head against the wall as to why my test kept throwing an `IOException` with Access Denied when trying to create a temp file. It was trying to create a file under `C:\Windows` because the system environment variables weren't being included as part of the run configuration. By simply checking `Include system environment variables`, the files were being created under `C:\Users\username\AppData\Local\Temp` correctly.

**Comment by LeoColman** [comment]
Closed as per kotest/kotest-intellij-plugin#28
