### ISSUE TITLE
Running single test runs all tests in class

### ISSUE THREAD

**Issue by tony19** [kotest/kotest#5533]
Despite the fix for kotest/kotest#5554, it's still not possible to run a single test for the following test styles:

 * AnnotationSpec
 * DescribeSpec
 * ExpectSpec
 * WordSpec

For the styles that do allow single test runs, if you pick the wrong menu option, you lose the ability to run single test runs afterward (until IDE restart).

## Steps to reproduce (Bug 1)

 1. From Android Studio 3.5, install `kotlintest-intellij-plugin` 3.3.0.11.
 2. Clone the repo at https://github.com/tony19-sandbox/kotlintest-issue.
 3. Open `./app/src/test/java/com/github/tony19/kotlintestissue/FeatureSpecTest.kt` from that repo.
 4. Click the green play icon next to the second scenario/test (`and should be tasty`) to open a context menu. Pick `Run 'FeatureSpecTest'` > `FeatureSpecTest: and...` (2nd option) from the menu.

#### Expected behavior

Only the selected test runs.

#### Actual behavior

All tests from the suite run.

## Steps to reproduce (Bug 2)

 1. From Android Studio 3.5, install `kotlintest-intellij-plugin` 3.3.0.11.
 2. Clone the repo at https://github.com/tony19-sandbox/kotlintest-issue.
 3. Open `./app/src/test/java/com/github/tony19/kotlintestissue/FreeSpecTest.kt`
 4. Click the green icon next to the second test to open a context menu. Pick `Run FreeSpecTest` > `FreeSpecTest: String...` (2nd option).
 5. Click the green icon again, but pick `Run 'FreeSpecTest'` > `FreeSpecTest` (1st option).
 6. Click the green icon again.

#### Expected behavior

The nested context menu to access the single test run (`Run FreeSpecTest` > `FreeSpecTest: String...`) should still be available.

#### Actual behavior

The nested context menu to access the single test run (`Run FreeSpecTest` > `FreeSpecTest: String...`) is no longer available.

## Versions

 * macOS Mojave 10.14.6
 * Android Studio 3.5
 * `kotlintest-intellij-plugin` 3.3.0.11

**Comment by tony19** [comment]
Please reopen

**Comment by sksamuel** [comment]
This should be fixed now in 4.1.1 and plugin 1.0.2

**Comment by tony19** [comment]
Confirmed. Thanks
