### ISSUE TITLE
Unable to run individual tests

### ISSUE THREAD

**Issue by blackmichael** [kotest/kotest#5535]
Currently my team is unable to run individual tests within our spec, regardless of which spec we use. Attempting to use the plugin to run the individual test only shows the options for running the entire spec class:
![Screen Shot 2019-08-07 at 12 13 15 PM](https://user-images.githubusercontent.com/18149766/62643226-1b956600-b90d-11e9-9805-307f317f0301.png)

I'm using plugin `kotlintest` `v3.3.0.11` on IntelliJ Ultimate Edition 2019.2. Please let me know if there's any additional information to provide and I'll try to respond quickly - if we cannot resolve this, then my team will likely move away from using kotlintest.

**Comment by LeoColman** [comment]
Delete your junit config

**Comment by blackmichael** [comment]
@Kerooker I'm not sure I follow. We don't have anything specific to JUnit in our project besides in our `build.gradle` file where we have
```
test {
  useJUnitPlatform()

  testLogging {
    showStandardStreams = Boolean.valueOf(project.gradleTestShowStandardStreams as String)
    exceptionFormat = project.gradleTestExceptionFormat
  }

  afterSuite { desc, result ->
    if (!desc.parent) {
      println "\nTest result: ${result.resultType}"
      println "Test summary: ${result.testCount} tests, " +
              "${result.successfulTestCount} succeeded, " +
              "${result.failedTestCount} failed, " +
              "${result.skippedTestCount} skipped"
    }
  }
}
```

**Comment by LeoColman** [comment]
Sorry.

You ran with junit once, right? That creates a run config. If you remove
it, things will show up again as individual tests

**Comment by blackmichael** [comment]
@Kerooker Ah I see what you're saying now! That seems to have worked. Do you think there's any way the plugin could avoid this?

**Comment by LeoColman** [comment]
Only if we deny all JUNIT execution. We haven't decided on that yet
