### ISSUE TITLE
Template and Run/Debug  configuration lost after closing IntelliJ

### ISSUE THREAD

**Issue by fsonntag** [kotest/kotest#5539]
When running tests over KotlinTest, I need to provide VM options. Some I keep in the Templates, some I want to store in only specific configurations.

Nevertheless, they don't seem to survive the current session, i.e. after restaring IntelliJ the VM options of the Template and of the specific configurations are gone.

This does not happen with configurations of other types, e.g. JUnit though.

Is there anything I'm missing though?

**Comment by sksamuel** [comment]
I thought I had fixed that in the latest version. If not I will fix it.

**Comment by fsonntag** [comment]
Thanks for the quick reply, that would be great. I saw that the latest plugin version is `3.3.0.11`, while there's already kotlintest `3.3.2`. Maybe the plugin was just not updated in the Marketplace?

**Comment by sksamuel** [comment]
I'm not keeping the numbers in exact sync. 3.3.0.11 is the latest.
