### ISSUE TITLE
Make it possible to jump between test specs using a shortcut

### ISSUE THREAD

**Issue by molaachir** [kotest/kotest#5545]
In IntelliJ, it is possible to jump between methods using the alt + Down arrow shortcut. When using JUnit, this is a very useful feature, as you can easily jump between tests. All KotlinTest specs are located within the init block, though, making it hard to jump through specific tests you've written. It would be great if alt + down arrow would navigate between tests the same way it navigates between methods. Especially for screen reader users (visually impaired developers), this would be a god send, as it takes very long to scroll through longer test files now.

**Comment by sksamuel** [comment]
How does this work - if you are anywhere in the test it takes you to the next one? Or do you have to be at the test name level, or ..?

**Comment by molaachir** [comment]
If you are anywhere in the test, it should take you to the next one, yes. That makes Jumping through tests when you can't use a mouse much, much faster and more convenient.

**Comment by sksamuel** [comment]
This is included in the latest plugin. Default hotkeys are alt p and alt n

**Comment by molaachir** [comment]
Cool, thank you.
