### ISSUE TITLE
Support "Jump to Source" on test executions

### ISSUE THREAD

**Issue by xcq1** [kotest/kotest#5550]
I have a feature request, not only from myself but also from a co-worker who tried kotlintest for the first time and had one major complaint:

For someone who's quite used to navigating tests from the "Run Test View" it is quite irritating that the kotlintest test executions do not support the "Jump to Source"/"Show Source" on double click or from the context menu:
![image](https://user-images.githubusercontent.com/789282/53413496-68732900-39cc-11e9-9479-ae7abb611b32.png)

This is how the context menu looks for a JUnit test:
![image](https://user-images.githubusercontent.com/789282/53413732-154da600-39cd-11e9-8829-f13d4f0eecec.png)

This navigation helps a lot when you're pinpointing some locations in the source, e.g. why a test case failed, and quickly want to return to the actual test case.

**Comment by sksamuel** [comment]
This is now present as per 3.3.0.10 plugin update.

**Comment by sksamuel** [comment]
3.3.0.10 is now released compiled against KotlinTest 3.3.0
This is the first "release" version of both.
Please make sure you have upgraded both and you should be good to go!
(It might take a day before Jetbrains approve the plugin release)

**Comment by xcq1** [comment]
Yay for the quick implementation!
However I was not entirely precise enough; if you run "Jump to source" on a method:
- kotlintest now jumps to the correct file. 👍 
- JUnit jumps not only to the correct file, but also positions the cursor on the method/test case definition (a great relief in test files with 500+ lines)

Can this be done as well?

**Comment by sksamuel** [comment]
I've add this as well now. You can build from source and install the built jar directly (easy enough to do in plugins -> cog -> install from disk) or you can wait for 3.3.0.11 which will be early next week.

**Comment by xcq1** [comment]
Very nice. :)
I can hardly wait, so thanks for the hint. But when I try to run a test with the built jar I keep getting "Error running 'XYTest': io/kotlintest/runner/console/KotlinTestConsoleRunner" without any further info. Guess I'll just have to be patient.

**Comment by sksamuel** [comment]
You have to use the gradle task called buildPlugin not just build, so you
if run that you will get a zip in distributions. That's what you install.

**Comment by xcq1** [comment]
Ah thanks, it's always the dumbest mistakes.
The fix works great.

**Comment by sksamuel** [comment]
Great.
