### ISSUE TITLE
Running one test case runs multiple tests with similar name

### ISSUE THREAD

**Issue by xcq1** [kotest/kotest#5552]
Consider the following example:
```
class Test : StringSpec({
    "Test case" {
        println("1")
    }

    "Test case two" {
        println("2")
    }

    "Test case two point one" {
        println("2.1")
    }
})
```
Clicking on "Test case" works fine and only launches the first test:
![image](https://user-images.githubusercontent.com/789282/53103201-72f57480-352d-11e9-90d9-f8a329b32f2e.png)

If I click on the run icon next to "Test case two", it actually launches these:
![image](https://user-images.githubusercontent.com/789282/53103129-4e999800-352d-11e9-8f7b-2e4fef3c098a.png)

If I click on the run icon next to "Test case two point one", it actually launches all of them:
![image](https://user-images.githubusercontent.com/789282/53103181-66711c00-352d-11e9-8771-6f177f7d10b0.png)

**Comment by sksamuel** [comment]
I know why it's doing it, I'll have to be cleverer in my logic :)
Good spot and thank you for creating the issue.

**Comment by sksamuel** [comment]
I believe this is fixed in my local code, but it will require another KT release and then a plugin release.

**Comment by sksamuel** [comment]
This should be fixed in 3.3.0.8 (waiting on jetbrains to approve).

**Comment by xcq1** [comment]
Can confirm it works for me :)

**Comment by sksamuel** [comment]
Cool. 3.3.0.9 will be significantly better too with auto test creation.
