### ISSUE TITLE
Running single test runs all tests in class

### ISSUE THREAD

**Issue by xcq1** [kotest/kotest#5554]
Hi there, thanks for this plugin, I think it's a really great idea because it eases migration and allows for easier debugging.

However I just installed 3.3.0.6 in IntelliJ Build #IU-182.4892.20 and if I launch a single test context via the new run icons at the side it always launches all the tests of the StringSpec class, not only the one I clicked.

**Comment by sksamuel** [comment]
Ok. Which version of kotlin test itself ?

**Comment by xcq1** [comment]
I originally had the problem with 3.1.11, but updating to 3.2.1 does not help either.

**Comment by sksamuel** [comment]
The plugin is only compatible with 3.3.0+
Try 3.3.0-RC2 but for that you will need 3.3.0.7 which is pending update.

**Comment by xcq1** [comment]
Well sorry, I didn't realize the project is still that cutting edge.
I'll retry once I get 3.3.0.7. Maybe it would help to have a compatible version number in the Readme.

**Comment by sksamuel** [comment]
Yes it should be clearer. I'll add to the readme and the plugin docs.
It's a bit "ad hoc" until 3.3.0 is released and then they'll sync up nicely.

**Comment by xcq1** [comment]
I have now updated to:
- IntelliJ #IU-183.5429.30
- Plugin 3.3.0.7
- `testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.3.0-RC2'`
but I still have the same issue.
Do I maybe need another dependency?

**Comment by sksamuel** [comment]
I believe this is the same issue as in kotest/kotest#5553

**Comment by xcq1** [comment]
Yes, you're right. I tested first to run the entire class which led to the issue. If I go in and manually delete the JUnit launch config it uses the correct one. I don't think this is very intuitive though, because as soon as I run the entire class as JUnit, it always wins against the kotlintest run config.

By chance I have found another issue: If there are two test cases where one name is contained in the other one (e.g. "A Test" and "A Test with longer name") and you launch the shorter one, it appears to launch both tests:
![image](https://user-images.githubusercontent.com/789282/53101613-6b809c00-352a-11e9-9628-d07488a5bd7d.png)
If you want, I can open this as a separate issue.

**Comment by sksamuel** [comment]
Please do. I appreciate the feedback.

**Comment by sksamuel** [comment]
3.3.0.10 is now released compiled against KotlinTest 3.3.0
Please make sure you have upgraded both and you should be good to go!
(It might take a day before Jetbrains approve the plugin release)

**Comment by xcq1** [comment]
Looks awesome, thank you

**Comment by dmitry-oshurkov** [comment]
I have ver 3.3.0.11 and this behavior is not fixed.
