### ISSUE TITLE
Timezone Extension

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#587]
What do you think about adding something like this: https://junit-pioneer.org/docs/default-locale-timezone/

**Comment by LeoColman** [comment]
I think it's great!

**Comment by LeoColman** [comment]
The only point would be where to add it. Probably just a function to execute before a test, and we would have to clear it afterwards

**Comment by sksamuel** [comment]
A TestCaseExtension that does it before every test and resets it after every test ?

**Comment by LeoColman** [comment]
Might be good.
It's a very specific scenario, but a pain in the ass to test. I like it

**Comment by LeoColman** [comment]
These were merged as per #609
