### ISSUE TITLE
feature request: enhancements to data-driven testing

### ISSUE THREAD

**Issue by danwallach** [kotest/kotest#589]
I've been looking to port some work I've done from Java to Kotlin, and I've been looking at porting my tests from JUnit5 and QuickTheories to do everything with KotlinTest. I'm really enjoying what I've seen so far, and I have several suggestions for how data-driven testing is handled.

**forAll vs. forall**
Currently, there's a `forAll` operator for doing property-based testing, a `forall` operator for doing data-driven testing, and then another `forAll` when using tables. Just the adjacency of these two names is a potential source of confusion. Perhaps just use `forAll` everywhere? 

**forall rows vs. table vs. lists**
Consider the following code:
```kotlin
"toLowerCase doesn't change strings that are already lowercase" - {
    "row notation" {
        forall(row("a"), row("charlie"), row("zed00zed"), row("")) {
            it.toLowerCase() shouldBe it
        }
    }

    "table notation" {
        val stringTable = Table1(Headers1("Whatever"), listOf("a", "charlie", "zed00zed", "").map { row(it) })
        stringTable.forAll {
            it.toLowerCase() shouldBe it
        }
    }
}
```

When you're using "row notation", you have a a lot of calls to the row constructor. Seems less than beautiful. With "table notation", you can at least start from a list of whatever and then map it to a list of rows, but this is still less than beautiful. Possible suggestions:

- Create a variant on `forall` that takes a `List<Row>` as a parameter rather than the `vararg` version.
- Create a variant on `forall` that knows about some standard tuple type outside of KotlinTest (perhaps from Arrow?), so `Row` isn't necessary.
- Consider a variant on `Table` that doesn't require a `Header`.
- Consider a variant on `Table` that does the mapping internally.

If you make the front-end for creating tables really beautiful, then you could kill off "row notation" entirely and do everything with `Table.forAll`, e.g.:
```kotlin
// hypothetical alternative
listOf("a", "charlie", "zed00zed", "").toTable1().forAll { it.toLowerCase() shouldBe it }
```

**Something analogous to JUnit5's TestFactory**
In some Java work that I've done, I've used `@TestFactory`, where your test method returns `List<DynamicTest>`, each of which has a string name and a lambda that's executed. Most of the examples you'll find online are things that KotlinTest would do with `forall` and one row per test, but I've found `@TestFactory` handy when you want to write a "test suite" of some sort when you've got three different implementations of the same interface and you want to write your test cases once.

All you write, when doing this, is regular Java code that returns `List<DynamicTest>` with no annotations. Then, you invoke that from one or more tests with the `@TestFactory` annotation, getting a separate list of tests for each implementation you want to test, and the test runner will execute them independently.

I don't see any obvious way to do this in KotlinTest, but I've found it very useful.

**Comment by LeoColman** [comment]
Thanks a lot for your time to post this issue! We can bring some discussion into this.

About table testing, I believe you didn't see some of the custom constructs for Table, and I admit maybe they're not very well documented now, but you can do:

```
listOf("a", "charlie", "zed00zed", "").forAll { XXX }
listOf(Bar("Foo", "Bar", "Baz"), Bar("Foo", "Boo", "Too")).forAll { (first, second, third) -> 
        XXX
}
```

You don't really need tables for this.

About the other comments, I'll get to them in a moment

**Comment by sksamuel** [comment]
For the factory, can you give me a very simple example? I'm pretty sure you could it by just declaring the tests dynamically, for example.

```kotlin
class A : FreeSpec({
"dynamic test" - {
 for (impl in impls) {
  "testing $impl" {
    // test here
  }
 }
}
})
```

**Comment by sksamuel** [comment]
We should rename for forAlls to be all forall (which I prefer like Scala) or forAll (like Kotlin).

**Comment by danwallach** [comment]
Here's a non-trivial example for testing binary trees in Java. This is an excerpt from a student assignment in a class that I teach ([Rice Comp215](https://comp215.blogs.rice.edu)). I give them a (mostly) working unbalanced binary tree implementation and they have to implement from scratch a probabilistically balanced treap. Both the "tree" and "treap" implement the same functional `ITree` interface. You'll also see `IList` in here, which is our own list class.

```java
/**
 * Static methods useful for testing Trees, Treaps, or anything else that implements ITree.
 * Typically you pass these the empty tree that's used for subsequent work.
 */
class TreeSuite {
  private final String name;
  private final ITree<String> emptyStringTree;

  /**
   * Not for external use. See {@link #allTreeTests(String, ITree, boolean, int, int, int)}
   */
  private TreeSuite(String name, ITree<String> emptyStringTree) {
    this.name = name;
    this.emptyStringTree = emptyStringTree;
  }

...

  void testInorder() {
    var testVectorList = List.of("Charlie", "Eve", "Bob", "Alice", "Dorothy");
    var tree = emptyStringTree.insertList(testVectorList);

    StringBuilder result = new StringBuilder();
    tree.inorder(result::append);

    assertEquals("AliceBobCharlieDorothyEve", result.toString());
  }

  void testSize() {
    var testVectorList = List.of("Charlie", "Eve", "Bob", "Alice", "Dorothy");
    var tree = emptyStringTree.insertList(testVectorList);

    assertEquals(emptyStringTree.size(), 0);
    assertEquals(tree.size(), 5);
  }
...

  /**
   * Produces a list of JUnit5 "dynamic tests" for a given implementation of {@link ITree}. This can
   * be returned from a JUnit5 {@link org.junit.jupiter.api.TestFactory}.
   *
   * @param name Name of the algorithm (e.g., "Treap")
   * @param emptyStringTree An empty tree of String
   * @param randomized If a tree is randomized, then we shouldn't run certain equality tests
   * @param ninserts for the tree depth test, how many sequential inserts to conduct
   * @param maxDepthString expected maximum depth for the depth test on a tree of strings
   */
  public static IList<DynamicTest> allTreeTests(
      String name,
      ITree<String> emptyStringTree,
      boolean randomized,
      int ninserts,
      int maxDepthString) {
    TreeSuite suite = new TreeSuite(name, emptyStringTree);

    return List.of(
        dynamicTest(name + " insert simple", suite::testInsertSimple),
        dynamicTest(name + " remove simple", suite::testRemoveSimple),
        dynamicTest(name + " greater than", suite::testGreaterThanSimple),
        dynamicTest(name + " less than", suite::testLessThanSimple),
...
        dynamicTest(
            name + " equals",
            () -> {
              if (!randomized) {
                suite.testEquals();
              }
            })
        );
}
```
The broad idea is that you call `allTreeTests` and it hands you back a list of tests, with some variation, since for example "equality" isn't particularly meaningful on a probabilistically balanced tree. 

When you want to actually use it, the code (using JUnit5) looks something like this:

```java
public class TreeTest {
  /** Run the full test suite on a vanilla binary tree. */
  @TestFactory
  public IList<DynamicTest> testSuite() {
    // insert 1000 sequential numbers, expected maxDepth <= 1001
    return TreeSuite.allTreeTests(
        "tree", Tree.makeEmpty(), false, 1000, 1001, 30); 
  }
}
```
And this:
```java
public class TreapTest {
  /** Run the full test suite on a randomized treap. */
  @TestFactory
  public IList<DynamicTest> testSuite() {
    // insert 1000 sequential numbers, expected maxDepth <= 30
    return TreeSuite.allTreeTests(
        "treap", Treap.makeEmpty(), true, 1000, 30, 30);
  }
}
```

When you run `TreeTest` or `TreapTest` in IntelliJ, it's smart enough to show you each of the individual tests as passing or failing, and will suitably teleport you to the lines where the assertions fail when you click on them. By the end of the semester, we actually have four separate implementations of the `ITree` interface, and all four implementations can be exercised by the same `TreeSuite` of code.

So, I guess what I'd like to see in KotlinTest would be some way of having a *parametric test* where I can write down what looks like a regular KotlinTest, except the header rather than just saying `class Whatever : FreeSpec({` and diving right in, it takes some parameters and then I can extend it elsewhere and specify the parameters, write extra tests, etc.

**Comment by danwallach** [comment]
Oh, and one problem with having an extension method like `Collection<T>.forAll`: it can be messy to mix and match with Arrow, which also has a `forAll` extension method. I don't have any special answer here. You could certainly declare `forAll` to be an extension method on `Collection<T>` inside of `TestContext`, keeping it from being visible elsewhere, but if somebody wants to use Arrow's `forAll` side-by-side, you still get the same issues.

Maybe there's something to be said for having a `toTable` method of some kind.

**Comment by danwallach** [comment]
Update on "parameterizing" my tests. It seems I can fake up what I want using inheritance.

```kotlin
open class ListTheories(val generator: Gen<List<String>>) : FreeSpec({
    "sorting works on shuffled inputs" {
        forAll(generator) {
            it.sorted() == it.shuffled().sorted()
        }
    }

    "sorting is idempotent" {
        forAll(generator) {
            it.sorted().sorted() == it.sorted()
        }
    }
})
```

In this case, I can create subclasses of `ListTheories` using different generators that I might want to test out, and each subclass is detected and run independently. This isn't quite the same thing as saying "give me a list of tests", but it gets the job done. I guess the question is whether this represents "idiomatic" use of KotlinTest or whether you've got other ideas of how it could/should be done.

Caveat: This "class extension" hack works correctly in IntelliJ, but when you run it from Gradle (5.1.1) you get this:
```
UnknownClass > executionError FAILED
    java.lang.IllegalArgumentException
```
I'm guessing this is related to the class wanting a parameter as part of its constructor and the test runner not being smart enough to say "wow, I'll just skip that".

**Comment by sksamuel** [comment]
I think work on this is similar to work we'll need to do for #598

**Comment by sksamuel** [comment]
In 4.0 (in master) we now support composable specs using something exactly like junit's test factory which covers this use case.

So you can do,

```kotlin
val tests = funSpec {
  test("foo") {}
}

class MySpec : FunSpec({
  include(tests)
  test("another test") { }
}
```

And of course the tests val, could be a function and parameterized.
