### ISSUE TITLE
Clarify the docs for the "invocations" config option

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#591]
From reading [this](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#test-case-config) it's unclear to me whether a test with e.g. `invocations = 3` will always be run 3 times, or only tried up to 3 times until a test run succeeds.

Also, supposing the test is always run 3 times in my example, what is the behavior if some runs fail and some succeed? Is it enough for a single run to succeed to make the test succeed, or do e.g. the majority of runs have to succeed in order to make the test succeed?

**Comment by LeoColman** [comment]
Invocations = 3 will always run 3 times.
If 1 out of 3 fails, the test will fail. All must succeed for the test to be a pass.

**Comment by LeoColman** [comment]
I will update the docs to reflect this

**Comment by sschuberth** [comment]
> All must succeed for the test to be a pass.

Ah, thanks. I was reading the current "Useful if you have a non-deterministic test and you want to run that particular test a set number of times" exactly the other way around: Instead of guarding against "false positives", i.e. a test succeeded although it shouldn't, I though the purpose is to give the test another change to succeed if it failed before.

**Comment by LeoColman** [comment]
Let's take an example of a test that fails:

```
class Foo : FreeSpec() {

  val counter = AtomicInteger(0)

  init {

    "Foo".config(invocations = 5) {
      val currValue = counter.incrementAndGet()

      if (currValue > 3) {
        fail("Oh no!")
      }
    }

  }
}
```

The "non-deterministic" `counter.increment()` will fail at some of the invocations, therefore the test will fail

**Comment by sksamuel** [comment]
> > All must succeed for the test to be a pass.
> 
> Ah, thanks. I was reading the current "Useful if you have a non-deterministic test and you want to run that particular test a set number of times" exactly the other way around: Instead of guarding against "false positives", i.e. a test succeeded although it shouldn't, I though the purpose is to give the test another change to succeed if it failed before.

The aim is for those tests that fail every now and then and you have to keep rerunning them to get a failure. By putting invocations = 20 you can flush them out sooner.
