### ISSUE TITLE
Add `And` scope to `BehaviorSpec` Then

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#594]
Any scope inside a `Spec` must either be a `TestType.Test` or `TestType.Container`. A scope cannot be both.

There is a possibility to use `TestType.CONTAINER_AND_TEST`, however, [Gradle is bugged](https://github.com/gradle/gradle/issues/4912), and doesn't work with it.

For this reason, we cannot have `Then -> And -> Then` in behavior Spec, because `Then` might be a test and a Container.

As we can't choose both right now, it's unsupported.

I'm keeping this open, because when (if?) gradle fixes the linked issue, we'll be able to add this feature.

**Comment by sksamuel** [comment]
Gradle 6 supports CONTAINER_AND_TEST but what was the bug that required this ?

**Comment by LeoColman** [comment]
I don't remember what was the bug.
It was an issue with finalizing the tests, if I remember correctly

**Comment by sksamuel** [comment]
I'm closing this because behavior spec is already complex enough.

**Comment by dragneelfps** [comment]
Would it be possible to reopen this? I know behavior spec is complicated, but from user perspective this feature would be very helpful.

**Comment by jumpstreet13** [comment]
I tried And in Then scope on my project and all worked like a charm. 
 There were updates ?
<img width="802" alt="Screenshot 2022-08-08 at 17 39 03" src="https://user-images.githubusercontent.com/19886384/183444080-3343cca7-6024-4761-a5a3-7e6ea4624a8c.png">
