### ISSUE TITLE
Documentation for test filtering via gradle

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#597]
Gradle has many options for filtering tests. I'd like to see some documentation on how users can apply this to kotlintest, as well as setting up custom test tasks that only run a subset of tests.
(Both class based filtering and package based filtering)

**Comment by LeoColman** [comment]
Should we add support for Maven as well? I don't like maven, but maybe users still use it

**Comment by sksamuel** [comment]
Yes. Both gradle and maven should have options for test filtering which will manifest themselves as filters in the discovery request of the test engine.

**Comment by sksamuel** [comment]
As part of a recent commit I overhauled our support of junit platform selectors / filters.
This means the following gradle documentation now applies directly to kotest.

I've added a section into our documentation that introduces this and then links to the gradle documentation.
