### ISSUE TITLE
[F] reuse specs, allow generic specs

### ISSUE THREAD

**Issue by robstoll** [kotest/kotest#598]
I am opening this feature request due to a slack discussion. I am not a kotlintest user, so bare with me. As far as I understood, it is currently not possible to reuse specs. I would like to be able to write generic specs. Say you have Strategy A, B and C all implementing MyStrategy. 
- ideally you only need to write one spec and all strategies can reuse it.
- it should also be possible to reuse a generic spec several times in a concrete spec. 
- in case kotlintest does not allow the same test name several times (or only keep one, because the test name is put into a Map :grin:) special care has to be taken. So depending on how kotlintest is implemented, the reuse of a spec should include a prefix for the test or similar to circumvent this problem

**Comment by LeoColman** [comment]
The discussion we had in Kotlinlang's Slack brought us to a hello world example of you composing specs would work.

This was asked a little while back, in #399 but nothing was very discussed over there.

The discussion we had brought us to a central point: Sometimes, behavior is the same between methods or inherited classes, and I might not want to reimplement the same test over and over. For example:

```
interface SumCalculator {
  fun add(first: Int, second: Int): Int
}

interface SubtractionCalculator {
  fun subtract(first: Int, second: Int): Int
}

class SumOnlyCalculator : SumCalculator {
  override fun add(first: Int, second: Int): Int = first + second
}

class SubtractionOnlyCalculator : SubtractionCalculator {
  override fun subtract(first: Int, second: Int): Int  = first - second

}

class ComplexCalculator : SumCalculator, SubtractionCalculator {
  override fun add(first: Int, second: Int): Int = first + second
  override fun subtract(first: Int, second: Int): Int = first - second
}

```

It's obvious that a lot of the code here should do the same thing, but there's not a very good way to do it.

One possibility is to add extension functions to Specs, and then reutilize code there, and we came up with the following to do it:

```

fun AbstractStringSpec.testSumCalculations(sumCalculator: SumCalculator) {
  "should sum correctly" {
    sumCalculator.add(1, 2) shouldBe 3
  }
}

fun AbstractStringSpec.testSubtractCalculations(subtractionCalculator: SubtractionCalculator) {
  "should subtract correctly" {
    subtractionCalculator.subtract(2, 1) shouldBe 1
  }
}

class SumOnlyCalculatorTest : StringSpec({
  testSumCalculations(SumOnlyCalculator())
})

class SubtractOnlyCalculatorTest : StringSpec({
  testSubtractCalculations(SubtractionOnlyCalculator())
})

class ComplexCalculatorTest : StringSpec({
  val target = ComplexCalculator()

  testSumCalculations(target)
  testSubtractCalculations(target)

})

```

Although it does its job, this isn't a good syntax, nor is it pretty to use.


What could be a syntax to do this kind of Composition?

**Comment by sksamuel** [comment]
I've just read up on the slack conversation. 

Of course, the major stumbling block to just defining various tests in several superclasses and inheriting them is that we can't have multiple inheritance. 

At the moment users can't define tests in an interface because the parent Spec containers are classes (as they use instance fields for state).

So I have two potential solutions to offer.

The first is to create some "junit style" test factory support. We allow users to create tests in some "factory" and then compose those factories into a test class. For example.

```
interface AdditionCalculator {
  fun add(first: Int, second: Int): Int
}

interface SubtractionCalculator {
  fun subtract(first: Int, second: Int): Int
}

class AdditionOnlyCalculator : AdditionCalculator {
  override fun add(first: Int, second: Int): Int = first + second
}

class SubtractionOnlyCalculator : SubtractionCalculator {
  override fun subtract(first: Int, second: Int): Int = first - second
}

class ComplexCalculator : AdditionCalculator, SubtractionCalculator {
  override fun add(first: Int, second: Int): Int = first + second
  override fun subtract(first: Int, second: Int): Int = first - second
}

class SubtractionCalculatorTests(private val calculator: SubtractionCalculator) : FunSpecFactory {
  init {
    generate {
      test("a calculator should subtract if it's to be any use to anyone") {
        assertAll { a: Int, b: Int ->
          calculator.subtract(10, 3) shouldBe a - b
        }
      }
    }
  }
}

class AdditionCalculatorTests(private val calculator: AdditionCalculator) : FunSpecFactory {
  init {
    generate {
      test("a calculator should add if it's to be any use to anyone") {
        assertAll { a: Int, b: Int ->
          calculator.add(10, 3) shouldBe a + b
        }
      }
    }
  }
}

class AdditionOnlyCalculatorTest : FunSpec() {

  private val calculator = AdditionOnlyCalculator()

  override fun compose() = listOf(
      AdditionCalculatorTests(calculator)
  )
}

class SubtractionOnlyCalculatorTest : FunSpec() {

  private val calculator = SubtractionOnlyCalculator()

  override fun compose() = listOf(
      SubtractionCalculatorTests(calculator)
  )
}

class ComplexCalculatorTest : FunSpec() {

  private val calculator = ComplexCalculator()

  override fun compose() = listOf(
      AdditionCalculatorTests(calculator),
      SubtractionCalculatorTests(calculator)
  )
}
```

Let's not get bogged down in syntax initially, as there's many ways we can do this and the above is just an off the cuff example.

The second solution, and one I'd have to do a bit more work to investigate, is to change the parent Spec containers to be interfaces. All the public fields that people override are already functions defined in an interface `Spec`. I was very careful to avoid exposing the user to a non-interface, so the fact that the concrete parents of `FunSpec` etc are classes _should_ not generate breaking changes to a user if we change the abstract spec parent to be interfaces.

Once we do that, we can then introduce two ways of creating a test. One is to define tests directly in the constructor body (the current way, either init block or constructor param), and the second would be to wire in interfaces which themselves IFunSpec. For example.

```
interface SubtractionCalculatorTests : IFunSpec {

  val calculator: SubtractionCalculator

  override fun init() {
    test("a calculator should subtract if it's to be any use to anyone") {
      assertAll { a: Int, b: Int ->
        calculator.subtract(10, 3) shouldBe a - b
      }
    }
  }
}

interface AdditionCalculatorTests : IFunSpec {

  val calculator: AdditionCalculator

  override fun init() {
    test("a calculator should add if it's to be any use to anyone") {
      assertAll { a: Int, b: Int ->
        calculator.add(10, 3) shouldBe a + b
      }
    }
  }
}

class AdditionOnlyCalculatorTest : FunSpec(), AdditionCalculatorTests {
  override val calculator = AdditionOnlyCalculator()
}

class SubtractionOnlyCalculatorTest : FunSpec(), SubtractionCalculatorTests {
  override val calculator = SubtractionOnlyCalculator()
}

class ComplexCalculatorTest : FunSpec(), AdditionCalculatorTests, SubtractionCalculatorTests {
  override val calculator = ComplexCalculator()
  override fun init() {
    super<AdditionCalculatorTests>.init()
    super<SubtractionCalculatorTests>.init()
  }
}
```

I believe I can get this to work although it might require some not so elegant trickery behind the scenes. The one thing that stands out immediately as a problem that we need to solve is that interfaces cannot have init blocks themselves. So where do you define tests? Well we can create our own "init" function in the interface, which the user can override to define their tests (and the framework will invoke that for you), but the problem is with multiple interfaces, kotlin requires you to "resolve the diamond", so in the complex calculator example above I've had to override init and call both the parent inits. Not very nice.

Some food for thought anyway @Kerooker @robstoll @anyoneelsewhoisinterested

**Comment by robstoll** [comment]
I would go for a composition approach

**Comment by sksamuel** [comment]
They both are :)

One is composing at the class level, another is composing at at the function level.

**Comment by robstoll** [comment]
I see, you have another definition of composition than I have :)
I would go for the first approach which does not rely on extending an interface

**Comment by LeoColman** [comment]
I think we can kind of mix both of the approaches. Interfaces and Composition, but without changing the current implementation for the final user.

```
class AddOnlyCalculator : StringSpec(), ComposedSpec<AdditionCalculatorTest> {

    override fun buildTarget() = AdditionCalculator()

}

class ComplexCalculator : StringSpec(), ComposedSpec<AdditionCalculatorTest>, ComposedSpec<SubtractionCalculatorTest> {

    val target = ComplexCalculator()

    override fun buildTarget(): AdditionCalculator = target

   override fun buildTarget(): SubtractionCalculator = target

}

```

(Nevermind the syntax, just throwing an example out)

And then in a `ComposedSpec` we would define how tests would work using `buildTarget`. 

Thoughts?

**Comment by sksamuel** [comment]
Let's target this feature for 3.4.

**Comment by sksamuel** [comment]
Ok dudes this is a potential implementation of composability / dynamic tests. 
All code is on this branch:
https://github.com/kotlintest/kotlintest/tree/feature/compose
 
First, I've added a class hierarchy that we want to test. Just a pretend collections library called Kollections (see what I did there).

`interface Kollection<T>` and two implementations - `KStack<T>` and `KQueue<T>`. These just delegate to the JDK versions but are used to indicate how we might want to test different strategy implementations.

Then we define dynamic tests using a function that returns a `TestFactory`.
In this case it is a top level function but it could just as easily be a member function.

```kotlin
fun kollectionTests(k: Kollection<String>): TestFactory = TestFactory {

  test("adding an element to a kollection") {

    val k1 = k.add("alice")
    k1.size() shouldBe 1
    k1.contains("alice") shouldBe true

    val k2 = k1.add("bob")
    k2.size() shouldBe 2
    k2.contains("bob") shouldBe true

    k.contains("charlie") shouldBe false
    k1.contains("charlie") shouldBe false
    k2.contains("charlie") shouldBe false
  }

  test("removing an element from a kollection") {

    k.remove("alice") shouldBe false

    val k1 = k.add("alice")
    k1.contains("alice") shouldBe true
    k1.size() shouldBe 1

    k1.remove("alice") shouldBe true
  }
}
```
Note each dynamic test is defined using the test keyword.
This test factory returns two tests which are generic to all kollections.
Then we can include these tests into a concrete spec using the keyword `from`.
For example, `from(kollectionTests(stack))`

So we can combine these generic tests with tests specific to a single implementation inside a Spec like this - using `FunSpec` for `KStack`

```kotlin
class StackTestUsingFunSpec : FunSpec() {

  private val stack = KStack<String>()

  init {

    test("a stack should add elements LIFO") {
      val s = stack.add("david").add("eve")
      s.iterator().asSequence().toList() shouldBe listOf("david", "eve")
    }

    from(kollectionTests(stack))
  }
}
```

And the same thing for a `KQueue` using `StringSpec`

```kotlin
class QueueTestUsingStringSpec : StringSpec() {

  private val queue = KQueue<String>()

  init {

    "a queue should add elements FIFO" {
      val q = queue.add("david").add("eve")
      q.iterator().asSequence().toList() shouldBe listOf("eve", "david")
    }

    from(kollectionTests(queue))
  }
}
```

One open question at the moment is how to generate dynamic tests for the different spec styles - in this case I have made it work for `StringSpec` and `FunSpec`, both of which allow tests to be defined at the top level. But say you wanted to use `WordSpec` this wouldn't work, as there tests must be nested inside a `should` block. 

One solution might be to have a separate TestFactory instance for each spec style (or one per type - eg one for the top level style specs (like here), and one for nested specs). Another solution might be to just limit this to top level supporting specs only.

Please give me your feedback and be brutal if you don't like it. 
Tagging users who have indicated interest in this feature @robstoll @Kerooker @alphaho @danwallach.

**Comment by LeoColman** [comment]
I dislike `from`. I think that perhaps it would be better to add the test as a member function of Spec, so

```
override fun listeners() = ...
override fun extensions() = ..
override fun isolationMode() = ...

override fun inheritedTests() = ...
```

**Comment by LeoColman** [comment]
(i don't like the name inheritedTests too, but my point is that I think it's better to have it outside of `init`)

**Comment by LeoColman** [comment]
About the test factory, maybe we could have something similar to

```
class MyTestFactory(foo: Foo) : TestFactory<FreeSpec> {

override fun FreeSpec.createTestes() {  // We could make it generic and use the extension functions to setup the DSL, perhaps

}

}

```

**Comment by sksamuel** [comment]
If you make TestFactory a supertype you extend from, then you force people to put tests inside a class. My way it's just a function that can be located anywhere.

The reason for having from() is that you can nest it within other scopes if you want and you can have more than one in a single test class.

**Comment by LeoColman** [comment]
You can use an object declaration that can also be located anywhere. But perhaps the function can still contain a <T> and use it, maybe inline/reified

**Comment by sksamuel** [comment]
Yes that's true. But then what's wrong with the syntax I proposed?
As for "from" I'm open to changing it as per feedback. So far it's just me and you lets see if others have opinions too.

**Comment by LeoColman** [comment]
Then nothing is wrong. I didn't dislike the syntax for the TestFactory, I just wanted to propose a way to do it for all Specs. Perhaps suggesting a class gave you the impression I didn't like a function

**Comment by sksamuel** [comment]
Oh ok I see.

We could have WordSpecTestFactory .. and so on.
Or we could use a single TestFactory and it _inserts_ the tests into wherever you place `from` (or call it something else).

Eg,

```
class Demo : WordSpec({
   "some scope" should {
     from(factory)
  }
})
```

Then it inserts them into that scope. Each spec knows how to handle "from" (or whatever its called).

**Comment by danwallach** [comment]
A quick side-look at JUnit5 might be relevant here. You can declare an individual test:
```java
@Test
public void testWhatever() {
    ...
    assertEquals(foo, bar);
}
```
Or you can declare a `TestFactory` that returns any `Iterable<DynamicTest>`:
```java
@TestFactory
List<DynamicTest> testSomethingElse() {
    return List.of(
        dynamicTest("thing1", () -> { ... assertEquals(foo, bar) ... }),
        dynamicTest("thing2", () -> { ... assertEquals(foo, bar) ... }),
        dynamicTest("thing3", () -> { ... assertEquals(foo, bar) ... }),
       ...);
}
```
You should probably come up types similar to `DynamicTest` and `TestFactory`. So, when I use your proposed `TestFactory { ... test(name) { body } ... }` syntax, that should probably return something of type `Iterable<DynamicTest>`, which I can then manipulate like any other list (maps, filters, etc.). Exactly how you then bring those DynamicTests back into a test environment where they're executed is up to you.

**Comment by sksamuel** [comment]
@danwallach
do you think its better to return a list of some test type, rather than say
what I did, where you just build the tests up inside a function?

**Comment by danwallach** [comment]
I'd suggest that the builder DSL you've invented should return `Iterable<DynamicTest>` or equivalent. And then you need someplace where you can cause one of those iterables to be evaluated.

**Comment by LeoColman** [comment]
I particularly think that JUnit5's syntax is a little bit verbose

**Comment by danwallach** [comment]
JUnit has to suffer from dealing with the general verbosity of Java. I'm not going to defend their syntax, just the high-level idea. The `TestFactory` DSL you're proposing looks a bit like syntactic sugar for the JUnit5 `List.of(...)` construction above, which is great. My recommendation, for what it's worth, is to create an analogous concept to `DynamicTest` (i.e., a tuple of a name and a lambda that will run assertion tests with your favorite Hamcrest or whatever matcher), using your DSL to make lists of these tests, and having some other mechanism to evaluate them.

**Comment by sksamuel** [comment]
Isn't that exactly what I've done in the code I've shown ?

The `test` method inside the `TestFactory` creates a `DynamicTest` instance. These are added to an internal list in the test factory. Call `test` as often as you like with a different name and lambda. Then this factory instance can be added to any spec you want.

**Comment by danwallach** [comment]
My only recommendation is that your `TestFactory` have some sort of `getTests()` method that returns the internal list, or maybe just have `TestFactory` be a typealias for `List<Something>`. Make it easy to go back and forth between lists of tests and test factories. 

As to the specific `from(TestFactory)` syntax, I'd encourage you to flip it around so it's a method on the test factory.

**Comment by sksamuel** [comment]
The TestFactory can easily expose as a list.
I can't flip the syntax around for `from` because each spec needs to know how to add the tests its in own "style".

**Comment by LeoColman** [comment]
I think we can add a generic to that

**Comment by sksamuel** [comment]
This is now supported in master (for 4.0 release) via the new test factory functionality.
