### ISSUE TITLE
Question: Bang and Focus outside of StringSpec

### ISSUE THREAD

**Issue by JustinTullgren** [kotest/kotest#605]
Hi,

Are bang and focus only supported in StringSpec? I like bang over `.config(enabled = false)` but it doesn't appear to work with the BehaviorSpec at the `given` level. I have not tried other specs, however. 

This doesn't appear to work:
```
given("!An ignored test") {
  `when`("executed") {
    then("it does not run") {
    }
  }
}
```

Thanks!

**Comment by LeoColman** [comment]
You're correct. This should work at `given` spec.

**Comment by LeoColman** [comment]
@sksamuel 

This is likely because `Given` is prefixed with `Given: XXXX`, thus `!` won't go to the beggining of the test.

This is likely to happen with any test that prefixes with anything.

Working on a fix.

**Comment by JustinTullgren** [comment]
Wow fast turn around! No rush on my part but thanks!

**Comment by LeoColman** [comment]
I was looking at issues and yours popped up :P

**Comment by LeoColman** [comment]
Oops.

**Comment by dave08** [comment]
I think this might be slightly related (towards the end...), although here we're talking top-level, and there I was asking for inner levels too, I wonder if already dealing with this, maybe the whole thing could be addressed?: https://github.com/kotlintest/kotlintest/issues/329

**Comment by LeoColman** [comment]
Probably not. Bang and Focus are not really related

**Comment by dave08** [comment]
Bang works for deeper levels on all test types? I know, focus is a seperate issue... I was just wondering if such a `!2:` or something hack would be needed, or just a simple `!` on the scope or test in the deeper level.

**Comment by LeoColman** [comment]
I don't think it does for all test types for the same reason

**Comment by LeoColman** [comment]
@JustinTullgren 

Fix was merged to master.

**Comment by JustinTullgren** [comment]
Thanks @Kerooker !
