### ISSUE TITLE
Make "condensed" multi-line diffs configurable

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#607]
While it's nice that https://github.com/kotlintest/kotlintest/issues/402 was implemented, there are cases where we'd like to turn off that feature, e.g. to accept actual results as the new expected results. Can we maybe have a system property that toggles the "condensed" multi-line diff, turning it off by default for backwards compatibility with most past releases?

**Comment by sksamuel** [comment]
@kerooker lets add this along with the bang fix, and make that 3.2.2

**Comment by LeoColman** [comment]
@sksamuel Should we include the other non-breaking minor changes as well?

**Comment by sksamuel** [comment]
Which one was that again.

**Comment by LeoColman** [comment]
All PRs with an exception of `Contracts`, and commits to master that you made (I'll have to look at them to see if any implementation changed):

#506 #603 #606 #608 #609 

And maybe
#543 and #613 if they're ready with this one

These are all the PRS created/merged after `3.2.1` was released
