### ISSUE TITLE
Arrow Extension - null support

### ISSUE THREAD

**Issue by evanbennett** [kotest/kotest#611]
In https://github.com/kotlintest/kotlintest/blob/master/kotlintest-assertions-arrow/src/main/kotlin/io/kotlintest/assertions/arrow/either/matchers.kt, should all uses of `Any` be `Any?` to support nullable types?

**Comment by sksamuel** [comment]
Makes sense. Would you like to make a PR ?

**Comment by evanbennett** [comment]
Sure.
