### ISSUE TITLE
Arrow Extension - `should beRight` lambda expression support

### ISSUE THREAD

**Issue by evanbennett** [kotest/kotest#612]
To test the returned value of an `Either` I am using:
```
val either = passwordColumn.loadType(com.google.gson.JsonPrimitive("73^pickles"))
either.shouldBeRight()
val password = (either as Either.Right<Password?>).b
password.shouldNotBe(null)
password!!.hashedPassword.shouldNotBe(null)
password.useExistingValue.shouldBe(false)
```

It would be nicer to be able to use lambda expression support, such as:
```
passwordColumn.loadType(com.google.gson.JsonPrimitive("73^pickles")).shouldBeRight {
	it.shouldNotBe(null)
	it!!.hashedPassword.shouldNotBe(null)
	it.useExistingValue.shouldBe(false)
}
```

Note: `passwordColumn.loadType(...)` returns `Either<ValidationError, Password?>`.

**Comment by evanbennett** [comment]
I have looked into the code, and come up with:
```
fun <B> Either<Any?, B>.shouldBeRight(checkB: (B) -> Unit) = this should beRight(checkB)
// fun <B> Either<Any?, B>.shouldNotBeRight(checkB: (B) -> Unit) = this shouldNot beRight(checkB)
fun <B> beRight(checkB: (B) -> Unit) = object : Matcher<Either<Any?, B>> {
	override fun test(value: Either<Any?, B>): Result {
		return when (value) {
			is Either.Left -> Result(false, "Either should be Right(...) but was Left(${value.a})", "")
			is Either.Right -> {
				checkB(value.b)
				Result(true, "", "")
			}
		}
	}
}
```
My feeling is that this should not be negatable, because I do not see how to negate `checkB`.

**Comment by sksamuel** [comment]
How about we do it even better by using contracts.

@Kerooker you are the contract man. What do you think about doing something like

```
a.shouldBeRight()
// contract to say a is now anInstanceOf[Right]
a.someRightOnlyOp()
```
?

**Comment by LeoColman** [comment]
Unfortunately contracts cannot be used to infer type with generics yet
https://youtrack.jetbrains.com/issue/KT-28298

We had this exact same issue at #602.

We can wait on this feature (I do believe it's going to be supported, as per https://github.com/Kotlin/KEEP/issues/139#issuecomment-436897878 and it's answer) or add the lambda as a current workaraound

**Comment by sksamuel** [comment]
I think we can add the lambda, then also add the contract version later.

**Comment by sksamuel** [comment]
We should add the lambda version for now ?

**Comment by sksamuel** [comment]
Partial implementation added via #834

**Comment by LeoColman** [comment]
Can this be closed?

**Comment by sksamuel** [comment]
Yep
