### ISSUE TITLE
Reflection Matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#614]
Would it be useful to have matchers like `a.shouldHaveMethod("foo")` and `a.shouldHaveAnnotation("foo")` and so on.

**Comment by LeoColman** [comment]
These kind of things would be great if we could assert on the annotation too.

For example

```
@Table(name = "Foo")
class Klass {

}


Klass.shouldHaveAnnotation<Table>("Foo")  // Foo would be the first parameter. Annotation classes c an't be instantiated
```

**Comment by LeoColman** [comment]
Or something similar

**Comment by sksamuel** [comment]
```
klass.shouldHaveAnnotation<Foo>() { foo -> 
 ...
}
```

**Comment by LeoColman** [comment]
That's way better

**Comment by LeoColman** [comment]
One more matcher we would add a lambda to.

I don't think it's a big problem

**Comment by sksamuel** [comment]
I think it could be a new pattern we could use to great effect.

Anything where we are testing a type, we allow the type to be used in the lambda.

`a.shouldBeAnInstanceOf<Foo>() { foo ->  }`
`a.shouldHaveType<Foo>() { foo ->  }`
`aTry.shouldBeSuccess<Success>() { success ->  }`

**Comment by LeoColman** [comment]
But then, is `should` the right keyword here?

I suppose a more correct way would be to add an `and` matcher of some sort

```
a.shouldBeInstanceOf<Foo>().andShould { foo -> }
```

**Comment by sksamuel** [comment]
What does the `andShould` give us over just accepting a lambda?

**Comment by LeoColman** [comment]
I believe that `shouldBeX` looks like a "terminal" operation, and it doesn't seem to be a lambda operation.

But I don't mind

**Comment by sksamuel** [comment]
I'm happy to discuss alternative nomenclature. Or as you say allow chained
matchers.

**Comment by faogustavo** [comment]
Does the development of this issue worth? Because annotations are not "business rules" to be validated on the test.

**Comment by sksamuel** [comment]
It's still useful, you may be testing a framework, like I am doing at the
moment.

**Comment by faogustavo** [comment]
Okay. I can do this issue this weekend.

**Comment by sksamuel** [comment]
awesome

**Comment by faogustavo** [comment]
@sksamuel @Kerooker I already created these matchers:

| Reflection |     |
| ---------- | --- |
| `kclass.shouldHaveAnnotations()` | Asserts that the class has some annotation | 
| `kclass.shouldHaveAnnotations(n)` | Asserts that the class has exactly N annotation | 
| `kclass.shouldBeAnnotatedWith<T>()` | Asserts that the class is annotated with the given type |
| `kclass.shouldBeAnnotatedWith<T> { block }` | Asserts that the class is annotated with the given type, and then, runs the block with the annotation | 
| `kclass.shouldHaveFunction(name)` | Asserts that the class have a function with the given name | 
| `kclass.shouldHaveFunction(name) { block }` | Asserts that the class have a function with the given name, and then, runs the block with the function|
| `kfunction.shouldHaveAnnotations()` | Asserts that the function has some annotation | 
| `kfunction.shouldHaveAnnotations(n)` | Asserts that the function has exactly N annotation | 
| `kfunction.shouldBeAnnotatedWith<T>()` | Asserts that the function is annotated with the given type |
| `kfunction.shouldBeAnnotatedWith<T> { block }` | Asserts that the function is annotated with the given type, and then, runs the block with the annotation | 
| `ktype.shouldBeOfType<T>()` | Asserts that the KType has the type T |

Do you know others that can be useful?

**Comment by sksamuel** [comment]
A.shouldHaveMemberProperty.

Also the  above that takes a lamba of KProperty to Unit

A.shouldHavePrimaryConstructor { constructor-> }

**Comment by sksamuel** [comment]
KFunction.shouldHaveReturnType<T>

**Comment by faogustavo** [comment]
Okay, 'til now, I created the following matchers:

| Reflection |     |
| ---------- | --- |
| `kclass.shouldHaveAnnotations()` | Asserts that the class has some annotation | 
| `kclass.shouldHaveAnnotations(n)` | Asserts that the class has exactly N annotation | 
| `kclass.shouldBeAnnotatedWith<T>()` | Asserts that the class is annotated with the given type |
| `kclass.shouldBeAnnotatedWith<T> { block }` | Asserts that the class is annotated with the given type, and then, runs the block with the annotation | 
| `kclass.shouldHaveFunction(name)` | Asserts that the class have a function with the given name | 
| `kclass.shouldHaveFunction(name) { block }` | Asserts that the class have a function with the given name, and then, runs the block with the function |
| `kclass.shouldHaveMemberProperty(name)` | Asserts that the class have a member property with the given name | 
| `kclass.shouldHaveMemberProperty(name) { block }` | Asserts that the class have a member property with the given name, and then, runs the block with the function | 
| `kfunction.shouldHaveAnnotations()` | Asserts that the function has some annotation | 
| `kfunction.shouldHaveAnnotations(n)` | Asserts that the function has exactly N annotation | 
| `kfunction.shouldBeAnnotatedWith<T>()` | Asserts that the function is annotated with the given type |
| `kfunction.shouldBeAnnotatedWith<T> { block }` | Asserts that the function is annotated with the given type, and then, runs the block with the annotation | 
| `kfunction.shouldHaveReturnType<T>()` | Asserts that the function returns the given type |
| `kproperty.shouldBeOfType<T>()` | Asserts that the property is of the given type |
| `kcallable.shouldHaveVisibility(visibility)` | Asserts that the member have the given visibility |
| `kcallable.shouldBeFinal()` | Asserts that the member is final |
| `ktype.shouldBeOfType<T>()` | Asserts that the KType has the type T | 

In my TODO List I still have those:
- [x] kclass.shouldBeSubtypeOf<T>()
- [x] kclass.shouldBeData()
- [x] kclass.shouldBeSealed()
- [x] kclass.isCompanion()
- [x] kclass.shouldHavePrimaryConstructor()
- [x] kclass.shouldHaveVisibility(visibilty)
- [x] kfunction.shouldBeInline()
- [x] kfunction.shouldBeInfix()
- [x] kproperty.shouldBeConst()
- [x] kproperty.shouldBeLateInit()
- [x] kcallable.shouldBeOpen()
- [x] kcallable.shouldBeAbstract()
- [x] kcallable.shouldBeSuspend()
- [x] kcallable.shouldHaveParameters(listOf<String>()) // Names of parameters
- [x] kcallable.shouldBeCalledWith(listOf<KClass>()) // Types of parameter
- [x] kcallable.shouldHaveParameterWithName(name) // also accept lambda
- [ ] kparameter.shouldBeOfType<T>()
- [ ] kparameter.shouldBeOptional()
- [ ] kparameter.shouldBeVararg()
- [ ] kparameter.shoudBeAtIndex(index) // check the position of the parameter

**Comment by sksamuel** [comment]
Looks good.

**Comment by sksamuel** [comment]
We can include this in 3.4 which we will release in the next few days, if it's ready @faogustavo

**Comment by faogustavo** [comment]
> We can include this in 3.4 which we will release in the next few days, if it's ready @faogustavo

I've been a little bit busy these last days. I'll open the PR to you start the review but there are a few methods missing.

**Comment by sksamuel** [comment]
That would be great, we can merge what's ready.
