### ISSUE TITLE
ShouldBeAssignableTo

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#615]
Potential matcher: `a.ShouldBeAssignableTo<T>`

Would throw if a is not a subtype of T.

**Comment by faogustavo** [comment]
@sksamuel @Kerooker `a.shouldBeInstanceOf<T>()` doesn't work in this case?

**Comment by sksamuel** [comment]
I think my idea was that a was a type rather than an instance.

**Comment by sksamuel** [comment]
Actually `shouldBeInstanceOf` is exactly the same :)
Closing.

**Comment by sksamuel** [comment]
My bad I meant like `Cat.shouldBeAssignableTo<Animal>()`.
So reopening and implementing.

**Comment by faogustavo** [comment]
@sksamuel can't we use the reflection methods?

```kotlin
Cat::class.shouldBeSubtypeOf<Animal>()
```

or

```
Animal::class.shouldBeSupertypeOf<Cat>()
```

**Comment by sksamuel** [comment]
Absolutely of course! Closing my PR.
