### ISSUE TITLE
Could not find method test()

### ISSUE THREAD

**Issue by jeremad** [kotest/kotest#622]
I probably do something wrong, however I have been stuck on this one for a while now.

I set up an empty project to reproduce my issue myproject/build.gradle:
```
buildscript { 
    ext.kotlin_version = '1.3.20' 
    repositories { 
        google() 
        jcenter()  
    } 
    dependencies { 
        classpath 'com.android.tools.build:gradle:3.3.0' 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" 
    } 
} 
 
allprojects { 
    repositories { 
        google() 
        jcenter() 
    } 
} 
 
task clean(type: Delete) { 
    delete rootProject.buildDir 
} 
```

And I follow the documentation in myproject/app/build.gradle:
```
apply plugin: 'com.android.application' 
apply plugin: 'kotlin-android' 
apply plugin: 'kotlin-android-extensions' 
 
android { 
    compileSdkVersion 28 
    defaultConfig { 
        applicationId "com.example.myapplication" 
        minSdkVersion 15 
        targetSdkVersion 28 
        versionCode 1 
        versionName "1.0" 
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner" 
    } 
    buildTypes { 
        release { 
            minifyEnabled false 
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' 
        } 
    } 
} 
 
test {
    useJUnitPlatform()
}

dependencies { 
    implementation fileTree(dir: 'libs', include: ['*.jar']) 
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" 
    implementation 'com.android.support:appcompat-v7:28.0.0' 
    testImplementation 'junit:junit:4.12' 
    androidTestImplementation 'com.android.support.test:runner:1.0.2' 
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2' 
    testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.2.1' 
} 
```

And When I try to build I get the following error: (--stacktrace --debug --info are not very helpful)
```
Could not find method test() for arguments [build_61tpwz9zzo2o2j2cb2rqxat9d$_run_closure1@1c5c85d4] on project ':app' of type org.gradle.api.Project.
```

I use gradle 4.10.3 and android studio 3.3

Anything I'm doing wrong?

**Comment by sksamuel** [comment]
I think your test deps go in the deps block not the test block. The test
block is for configuring test behaviour.

**Comment by LeoColman** [comment]
Can you show us some of the test code you made, please?

**Comment by jeremad** [comment]
Yes indeed, I pasted the wrong example. I edited:
```
- testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.2.1' 
+ useJUnitPlatform()
```
I still have the same issue.
I don't have any test code, it's an empty project!

**Comment by jeremad** [comment]
I think the problem is really about creating the "test" block. If I remove it, it does build.

**Comment by LeoColman** [comment]
Oh, I see.

I think that the `test` block must be at the parent `build.gradle`, not at `app` build.gradle.

But I'm not completely sure

**Comment by jeremad** [comment]
I tried that, same error :/

Thanks you for you help, BTW

**Comment by jeremad** [comment]
BTW, for a more extensive explanation:
I ran into this trying to migrate from kotlintest 2 -> 3, everything went fine... except that tests were marked as passed while they did not run. So I tried to follow the doc, and BOOM.

**Comment by LeoColman** [comment]
That's bad!
Which version of gradle are you using?

**Comment by jeremad** [comment]
4.10.3

**Comment by LeoColman** [comment]
I think that the `test` task is from the `java` plugin, could you try to apply it, please?

**Comment by jeremad** [comment]
Now that gets interesting:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> The 'java' plugin has been applied, but it is not compatible with the Android plugins.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by jeremad** [comment]
It seems that other projects made it work with android, without the `test` section, looking into that

**Comment by jeremad** [comment]
OK, there is no point to let this issue open, I made it work, just not in command line, I may open another issue about this today

**Comment by RishuKS** [comment]
Hi @jeremad ,
I am also facing the same issue not able to create test in build.gradle. When i have created test in another way than error is not showing but my test is not getting executed. could you please help me how you resolved this issue.
Go through this link to find more details about my problem [https://stackoverflow.com/questions/56454564/not-able-to-execute-testng-xml-file-from-gradle-command-line]

Thank you.

**Comment by jeremad** [comment]
Did you check out https://github.com/kotlintest/kotlintest#gradle
I updated the documentation following my trouble.

Basically you should add `testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.3.2'` in the `dependencies` section, and this:
```
android {
  ...
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
```

**Comment by jeremad** [comment]
However it does not look like you are using kotlin test

**Comment by kumarrishu** [comment]
Hi @jeremad,

**Comment by kumarrishu** [comment]
After adding this ->

android {
 testOptions {
            unitTests.all {
                useJUnitPlatform()
            }
        }
}

 **I am getting error**
Could not write standard input to Gradle Test Executor 85.
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:52)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jeremad** [comment]
I cannot help you more, you're in the wrong repository

**Comment by robotsquidward** [comment]
If it's okay I'm just going to leave this here for the next person who stumbles on this thread doing the same thing as me.

I was using this [SO Thread](https://stackoverflow.com/questions/3963708/gradle-how-to-display-test-results-in-the-console-in-real-time) about how to display pretty-er Gradle test outputs. They use the [`test`](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering) block to set up testing options for better Gradle logs:

```gradle
test {
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
    }
}
```

Which I think is a root project configuration, but I was having the same issue in my root build.gradle.  I'm not sure if this is an issue with the Android gradle setup, but I was able to do what @jeremad suggested and included my configuration in the `android` block under `testOptions`

```gradle
android {
    // ...
    testOptions {
        unitTests.all {
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
            }
        }
    }
}
```

**Comment by Miha22** [comment]
```java
android {
   testOptions {
          unitTests.includeAndroidResources = true
          unitTests.all {
              useJUnitPlatform()
              reports {
                  junitXml.enabled = true
                  html.enabled = false
              }
              testLogging {
                  events "passed", "skipped", "failed"
  
                  // to run JUnit 3/4 tests:
                  testImplementation("junit:junit:4.12")
                  testRuntime("org.junit.vintage:junit-vintage-engine:5.7.0")
              }
          }
      }
}
```
