### ISSUE TITLE
System Environment extensions

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#623]
In the line of #524, we should allow configuration for System Environment Variables (which are differente from System Properties).

It's not trivial to do, because `System.getenv()` returns an immutable map, which can't be appended to.

The library [System Rules](https://stefanbirkner.github.io/system-rules/) does it with a JUnit rule, specifically in [this class](https://github.com/stefanbirkner/system-rules/blob/master/src/main/java/org/junit/contrib/java/lang/system/EnvironmentVariables.java).

I believe we could do something similar, and in the same pattern as `System Properties` (#524), with a Extension and helper methods.

**Comment by sksamuel** [comment]
And a security manager extension too.
We should make a module with extensions, or shove them in core.

**Comment by LeoColman** [comment]
I think shoving them in core is better.
Unless we make the Junit5 runner module depend on a new module, which I'm fine with too..

I've created #624 and #625 for f urther discussion on these

**Comment by sksamuel** [comment]
Yeah I wouldn't make it a module the user has to add in manually, but maybe for separation of code we can have a kotlintest-extensions module.

**Comment by LeoColman** [comment]
I agree

**Comment by sksamuel** [comment]
We have a lot of features for 3.3 now.
Did you test intellij plugin?

**Comment by LeoColman** [comment]
@sksamuel 
One thing that is scaring me a little bit about these extensions:
What if I develop for parallel testing?

For instance, if I need environment to be X in this test, Y in another test and they're both ran in parallel?
If this happen, the variable will be in an inconsistent state. The same goes for System Property extension.

I think user should know this, but should we warn in any way about this?

**Comment by sksamuel** [comment]
We could possibly have the extension throw an exception if parallelism is enabled, because yes its a race condition. They would be able to use project level only.

**Comment by LeoColman** [comment]
What do you mean using project level only?
Only `beforeProject` and `afterProject`?

Perhaps I can use it `beforeTest`, but I have to guarantee that no other test is using it. How to verify if parallelism is enabled?

**Comment by sksamuel** [comment]
The extension can check Project.parallelism

**Comment by LeoColman** [comment]
And if project is parallel we deny it's usage in tests, and allow usage in project only?

**Comment by sksamuel** [comment]
Exactly.

**Comment by LeoColman** [comment]
I don't think I'll be able to deny execution based on parallelism. I can't verify if I'm running as a ProjectExtension or as a TestCaseExtension or just inside a test with `withEnvironment`. How could we solve this? With a warn only?

**Comment by dave08** [comment]
Maybe a little dirty, but a global `var isCurrentRunInParalell` with an AtomicBoolean? @Kerooker

**Comment by LeoColman** [comment]
That won't work, as I still won't know if I'm in a Project Extension or Test Extension

**Comment by dave08** [comment]
That could be a second atomic value... :see_no_evil: @Kerooker. I mean, since you just need to know what is currently running... but then I don't really know the internals, so I guess it might not be possible anyways...

**Comment by LeoColman** [comment]
I think we just need to check if `withSystemEnvironment` is currently running. We don't need to care about project parallelism if it's never used in parallel.

It will become a race condition, however.
I'll add a commit that does what I'm thinking for you and @sksamuel to review

**Comment by sksamuel** [comment]
Just put this inside the intercept method.

```kotlin
 if (Project.parallelism() > 1)
            throw RuntimeException("This extension can only be used when parallelism is 1")
```

```kotlin
override suspend fun intercept(testCase: TestCase,
                                   execute: suspend (TestCase, suspend (TestResult) -> Unit) -> Unit,
                                   complete: suspend (TestResult) -> Unit) {
        if (Project.parallelism() > 1)
            throw RuntimeException("This extension can only be used when parallelism is 1")
        withSystemProperties(props) {
            execute(testCase) { complete(it) }
        }
    }
```

**Comment by sksamuel** [comment]
No one will want to use this project wide, otherwise, you might as well just set the system property in your build file.

**Comment by sksamuel** [comment]
For things like Locale, where you might want to use it project wide, just create two versions - `LocaleTestCaseListener` and `LocaleProjectListener`.

In fact, I would change the implementation from a TestCaseExtension to a TestCaseListener, because we do not need to intercept the test cases and listeners are much simpler.
Then the `LocaleTestCaseListener` checks for parallelism and the LocaleProjectListener does not.

Feel free to change the names, as listener is probably not quite right, extension is a better name, but the wrong implementation.

**Comment by LeoColman** [comment]
There's also the possibility that the test is multi-thread, and one shouldn't use withEnvironment twice. I'm thinking of something like

1. If I'm not running, enter running mode
2. If I'm in the running mode, nobody else can enter it
3. When I leave the running mode, it's up for grabs again.

Similar behavior to how threads enter a critical section.

If I implement listener, wouldn't it be a little weird for the user to use an `Extension` in a `listeners()`?

**Comment by sksamuel** [comment]
Extension and Listener are just ways to extend KotlinTest. Use extension if you want to change the way tests are reported back to KT, or filter tests. Otherwise use listeners.

If we use Listener then you can have two implementions - one overriding beforeTest, and one overriding beforeProject.

The project one doesn't need to test for parallelism.

The only thing we need to care about re: race conditions is to synchronise access to the system properties map, then it will be fine. If you have this running mode thing, you'll block anything else trying to run that needs it.

**Comment by LeoColman** [comment]
I want to block anything else trying to run. It will only block anything executing `withEnvironment`, it won't block `System.getenv()`

**Comment by LeoColman** [comment]
And with blocking I mean crashing if, and only if, anything else tries to run `withEnvironment`

**Comment by LeoColman** [comment]
I understand `Extension` and `Listener`, but I don't want to call a `Listener` "extension"

**Comment by sksamuel** [comment]
If parallelism is 1 then it doesn't matter does it.
If it's > 1 people can fuck with it anyway by doing the same thing as
withEnv but in their own code.
I don't think we need to babysit people.

**Comment by sksamuel** [comment]
I agree with you on the naming, that's why I'm going to rely on you to come
up with a better name :)

**Comment by LeoColman** [comment]
Will people always know that their environment is screwed because it's a race condition? Shouldn't we even warn if the user brainfarts?

**Comment by LeoColman** [comment]
I think that calling it `SystemEnvironmentTestListener` and are both OK.

We're listening for a test start, and then we're executing something when it does. (starts/finishes). We're not exactly extending the test.

I believe it's up to how you word the sentence, as we could say we're extending the test by modifying the environment.

I'll keep the name cited above, and modify the code to use TestListeners instead of TestExtensions

**Comment by sksamuel** [comment]
Those names are good.
