### ISSUE TITLE
Security Manager extension

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#624]
In the line of #524 and #623, we should have a Security Manager extension.

The library [System Rules](https://stefanbirkner.github.io/system-rules/) does it with a JUnit rule, specifically in [this](https://github.com/stefanbirkner/system-rules/blob/master/src/main/java/org/junit/contrib/java/lang/system/ProvideSecurityManager.java) class.

We can do something similar, and in the same pattern of `System Properties` (#524) and `System Environment Variables` (#623), with an extension and helper methods.

**Comment by sksamuel** [comment]
One thing I'd like to think about is project level vs spec level extensions.

Maybe you want to override security manager for a single spec. Or maybe for the entire test suite. Currently we don't offer that.
