### ISSUE TITLE
Rework extensions

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#625]
We were discussing in #623 about reworking how extensions work, either creating a separate module or shoving all extensions in core.

Let's discuss a little bit on what we should do in this matter

**Comment by LeoColman** [comment]
I'm on the line of reducing dependencies users must add to the most. Unless there are big/heavy extensions, I don't think there's any problem in shoving them into the core module, or make the core module depend on it, as a separate module.

**Comment by sksamuel** [comment]
I think maybe a kotlintest-extensions module, but that's brought in by the runners automatically.

**Comment by LeoColman** [comment]
I think it's good.
We separate the code to another module, and with this separation we also bring it's tests to this modularity, making things a little bit clearer for future developers to contribute.

However, I'm kinda scared that everything get it's own module, and we have a bazillion modules. I don't really think that's a problem, as responsibilities will be very well split, but can it get confusing?

**Comment by LeoColman** [comment]
We do have a `kotlintest-extensions` module, we should just refactor it in some way to include all of them at once.

Things to remember is refactor the documentations on `Spring Extensions`, `Allure Extensions` and the likes

**Comment by sksamuel** [comment]
We have submodules of it. The spring and allure ones you might want to keep separate if there are additional deps. But for modules with no deps they might as well be brought in automatically.

**Comment by LeoColman** [comment]
Makes sense
