### ISSUE TITLE
Test folder and android studio

### ISSUE THREAD

**Issue by jeremad** [kotest/kotest#626]
In my android project:
* I successful migrated test classes from kotlintest 2 to kotlintest 3.2
* I can run test classes individually
* I could run the whole test directory with kotlintest 2
* Now when I try to run the test directory:
```
Process finished with exit code 0
Empty test suite.
```

It's basically the same issue when I try to run the tests with gradle, It used to work with former version, but now it does nothing.

**Comment by jeremad** [comment]
I got the end of that, it's a small issue in the documentation, I'll made a PR adding an small android section

**Comment by LeoColman** [comment]
Great one!
Thanks!
