### ISSUE TITLE
new behavior spec without parentheses

### ISSUE THREAD

**Issue by leoxs22** [kotest/kotest#634]
Scalatest has a syntax like this:

 ```
 "Chuck Norris" when {
     "hit by a truck" should {
          "be ok" in {
                //test code
           }

          "destroy the truck" in {
               //test code
          }
      }
}
```

I'll try to code it if someone can confirm that this could be a good adittion. I think that this syntax is cleaner than the BehaviorSpec, providing the same functionallity.

**Comment by LeoColman** [comment]
I'd be glad to take a look in your code!
However, some things we should make sure of: BehaviorSpec will keep existing. How can we find a name for this kind of spec?

**Comment by sksamuel** [comment]
@leoxs22 what is this spec called in scalatest ?

**Comment by leoxs22** [comment]
@sksamuel in Scala it seems to be called WordSpec 
http://www.scalatest.org/at_a_glance/WordSpec

Maybe we could add it as an extension of the WordSpec, since it's similar but with more nested operations. If that nesting it's just optional, it could be a part of the same spec.

So, you can just use the "should" keyword, but if the test requires it, you can use the keywords "when" and "in".

I have to check if it's possible to do that while maintaining backward compatibility. If not, we can call it ExtendendWordSpec, or something like that.

So, "should" would be mandatory, but "when" and "in" would be optional.

**Comment by leoxs22** [comment]
I've run some tests and it seems to work as expected when using the 3 functions.

![image](https://user-images.githubusercontent.com/9098977/52249372-879d0000-28d1-11e9-99b8-4abdd6b02a43.png)

![image](https://user-images.githubusercontent.com/9098977/52249377-8f5ca480-28d1-11e9-842e-48acc82000a5.png)

I still have to work in allowing only to use "should", and keeping the functionality of the "config" function in all the contexts, but at least I now know that I can code it :smile:

**Comment by sksamuel** [comment]
So we already have a WordSpec.
It doesn't have the "when" syntax - I've been using ScalaTest since 2011 and I never realised word spec supported that :joy: 
So we could just add that to the existing word spec.

As for "in" - when I first wrote KotlinTest I made the conscious decision to avoid the use of In. I don't think it should be added now.

**Comment by leoxs22** [comment]
Nice, so I'll delete the support for "In", and write some tests

**Comment by sksamuel** [comment]
yes please, and if we don't have lowercase when, can we add that in backticks?
