### ISSUE TITLE
Required flag for test invocations

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#641]
By default, if we have invocations > 1 then all must pass. We could add a new flag, required, which allows the user to say that some are allowed to fail. Eg,

```kotlin
"some flakey test".config(invocations = 10, required =7) { }
```

In this scenario, only 7 are needed to pass.

**Comment by LeoColman** [comment]
Isn't this somewhat against testing? Doesn't this kinda throws on our face that the code is bugged if we need to use it?

**Comment by sksamuel** [comment]
I suppose my idea was if you were doing some integration test against an
external service that wasn't always working 100%.

**Comment by LeoColman** [comment]
I see. I would usually mock the external service in this kind of scenario, and when it's supposed to fail I would mock the failure answer, and test for that.


But, I mean, this doesn't hurt anybody. The only thing I think should happen is that this parameter must be placed at the end, and not near `invocations`. Or else this may break some old builds that don't use this parameter and don't use named arguments

**Comment by sksamuel** [comment]
I was thinking of deprecating invocations and replacing it with a function.
In other words moving the logic _out_ of the engine and into the test itself. There's actually no reason it needs to be in the engine.
```kotlin
test("some fun spec test") {
  repeat(5) {
    // test
  }
}
```

And then we can combine `invocations`, `required`, `retry`, `threads` all into a single powerful command.

```kotlin
test("another test") {
  repeat(10).retry(backoff(4)).required(4) {
  // test  
  }
}
```

Or

```kotlin
test("another test") {
  repeat(10) {
    retry(simple(3)) {
       // test  
    }
  }
}
```

**Comment by LeoColman** [comment]
That seems cool!

Em sáb, 16 de fev de 2019 20:57, Stephen Samuel <notifications@github.com
escreveu:
