### ISSUE TITLE
Tests are broken with Gradle 5+

### ISSUE THREAD

**Issue by almozavr** [kotest/kotest#645]
Android build with unit tests fails to run with following exceptions:
```
Received a completed event for test with unknown id '5.278'. Registered test ids: '[5.1, :app:testDebugUnitTest]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '5.278'. Registered test ids: '[5.1, :app:testDebugUnitTest]'
	at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
	at sun.reflect.GeneratedMethodAccessor279.invoke(Unknown Source)
	...
```
It seems to be very similar to this issue: https://github.com/gradle/gradle/issues/6453#issuecomment-415780499 Also this linked workaround helps (but useless in mid/big project).

Gradle `4.10.3` works flawlessly.

My failed env:
```
Gradle 5.2.1
Kotlintest 3.2.1
Android Plugin 3.3.1
```

**Comment by LeoColman** [comment]
I don't think there's too much we can do about it...

Gradle unfortunately have a lot of bugs that screw us :/

**Comment by LeoColman** [comment]
The only alternative I see is for you to disable parallelism, as Gradle cannot run with more than 1 thread

**Comment by LeoColman** [comment]
I'll try to take a look if this is an issue on our side

**Comment by almozavr** [comment]
@Kerooker thanks for the feedback! Provided Gradle issue seems to be fixed and I wonder if there is new Gradle API for you to utilize 🤔

**Comment by LeoColman** [comment]
As far as I remember, we don't really use Gradle's API. We use JUnit Platform, and gradle integrates with it. Maybe @sksamuel have some more info on this

**Comment by sksamuel** [comment]
Yeah gradle integrates with Junit5 Platform (badly) and then things like KotlinTest and other test frameworks utilise Junit5 Platform.

If you want to parallelize the tests, have you tried the option from within KotlinTest itself, rather than from within Gradle ?

**Comment by almozavr** [comment]
@sksamuel actually, I believe parallel test execution is by-default gradle feature, so we don't "use" any special setup to parallelized test runner. Our gradle file is very basic:
```
android {
...
  testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
}

dependencies {
  testImplementation "io.kotlintest:kotlintest-runner-junit5:$kotlinTestVersion"
}
```
And `gradle.properies` (which I don't think take part in this issue):
```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4608M
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=true
android.enableBuildCache=true
```

The "helping" config is about to put `forkEvery=1` which so far as I know forks the whole process for every testing class (which makes build 2x slower).
```
testOptions {
        unitTests.includeAndroidResources = true
        unitTests.all {
            useJUnitPlatform()
            systemProperties['junit.jupiter.execution.parallel.enabled'] = true
            maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
            forkEvery = 1
        }
    }
```

I wonder if this issue could occur because of outdated junit-platform dependencies? Also I can see a similar problem with TestNG in linked issues: https://github.com/gradle/gradle/issues/7878

**Comment by LeoColman** [comment]
I think what @sksamuel meant is that you can [configure parallelism within kotlintest](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#parallelism)

**Comment by almozavr** [comment]
@Kerooker thanks for the link. Unfortunately `parallelism` config doesn't give reasonable speed up with gradle's `forkEvery = 1`

**Comment by LeoColman** [comment]
I don't think we have too many options here then.
Gradle integrates badly with JUnit Platform, and I don't think there's anything we can do about it from our side :/

**Comment by almozavr** [comment]
Got it. Sad sad sad. Then close the issue on will. Anyway, thanks for all your feedback

**Comment by LeoColman** [comment]
If you're willing to, give some love to our parallelism, maybe they'll work for you even if the suite is a little bit slower.

Maybe it has got faster since your last try, and may be able to compete with `forkEvery`

**Comment by LeoColman** [comment]
Thanks for reporting this!

**Comment by almozavr** [comment]
Guys, don't know what you've done, but `3.3.0-RC3` works great with gradle `5.2.1` 🥇

**Comment by sksamuel** [comment]
I upgraded the main build to gradle 5, so getting it to work with that must
have fixed it for you too :)

**Comment by elect86** [comment]
I also had the same issue after jumping from Gradle 5.0 to 5.2.1

Fixed with the workaround

```
test {
      systemProperties['junit.jupiter.execution.parallel.enabled'] = true
      maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
      forkEvery = 1
}
```
