### ISSUE TITLE
Fake/Sample/Test data generator

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#649]
What do you think about offering data generators?
A bit like:
https://github.com/moove-it/fakeit
https://github.com/DiUS/java-faker
@Kerooker

**Comment by LeoColman** [comment]
I"m very for it!
I recently read [this article](https://blog.kotlin-academy.com/creating-a-random-instance-of-any-class-in-kotlin-b6168655b64a), and I was thinking of suggesting it this morning.

**Comment by sksamuel** [comment]
We could use them with generators too.
