### ISSUE TITLE
Adding KotlinTest runner prevents tests from running

### ISSUE THREAD

**Issue by j-h-a** [kotest/kotest#650]
In Android Studio, Adding this line:
`testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.2.1'`
to gradle prevents tests from being found in a suite.
Right clicking on the test module and choosing run comes back with "no tests were found".

Note: This also prevents any normal JUnit tests from running as well.

To reproduce, create a new empty project in Android Studio, using AndroidX. Add the KotlinTest dependencies and then try to run the tests from the IDE. Note: The tests can still be run by selecting individual files to run, it's only when the whole suite is run that no tests are found.

**Comment by LeoColman** [comment]
Perhaps a duplicate of https://github.com/kotlintest/kotlintest/issues/626 ?

**Comment by j-h-a** [comment]
It looks like the same issue, yes, but it's not fixed. I always had both of those sections in my gradle file, as I started using KotlinTest after that PR was merged - so that update was the documentation I used.

I think it initially worked, but since the latest Gradle/Android Studio update it doesn't any more. I don't understand how gradle works yet as I'm very new to it, so I have no idea what's going on or why this is a problem, or even where the problem is, but if the tests can't be run from gradle on CI then they are useless... I really like KotlinTest so I want to use it but this is a show-stopper if I can't figure out how to fix it :(

**Comment by LeoColman** [comment]
Just to eliminate the obvious, have you tried deleting all `build` and `out` folders?

If the tests are ran in individual files, are they running when you do `./gradlew clean test`?

**Comment by j-h-a** [comment]
They seem to run from the command line, yes. Thanks for the obvious tips because I had no idea how to run it from gradle command line. Although there is no output, I had to go digging for the html report. However it still doesn't run from AndroidStudio.

I've only been doing Android for two weeks so like I said I have no idea where this issue lies. However I think that the kotlintest-runner is being called from Android Studio, because I see the `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".` warning/error. It just can't find the tests.

**Comment by LeoColman** [comment]
We had some problems with running suites a while back. 

Personally, I usually execute a single class when I'm writing the test, and when building the APK I execute all the tests via `gradlew test`. I've had issues running the whole suite even when using JUnit. Android Studio/Android Development can be crappy sometimes.

I'd recommend you always run tests with gradle, and execute individual tests via the IDE while you're developing them.

**Comment by j-h-a** [comment]
Ok thanks. It sounds like this is an AndroidStudio issue then (maybe), although I was able to reliably trigger it by adding the `testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.2.1'` line, and make it work again by commenting out that line (The normal JUnit tests would run again).

**Comment by LeoColman** [comment]
You have to just be careful, because I think that Android Instrumentation tests cannot run with JUnit 5.

**Comment by LeoColman** [comment]
I think that your issue is due to android studio integration with JUnit Platform. AFAIK there's none.
