### ISSUE TITLE
Better toString with automatic support for Show for classes

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#662]
Possibly something along the lines of this:
https://github.com/npryce/hamkrest/blob/master/docs/describe.md
http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#custom-representation

We could use Show from Arrow.
https://arrow-kt.io/docs/apidocs/arrow-typeclasses/arrow.typeclasses/-show/index.html

**Comment by sksamuel** [comment]
I've done this already. Need to add docs for it @Kerooker

**Comment by xeruf** [comment]
@sksamuel Is it possible to create a custom Show implementation and have Kotest use it?

**Comment by sksamuel** [comment]
@xerus2000 at the moment they are hard coded because I am not sure of a way to have discovery that works on MPP.

**Comment by xeruf** [comment]
well, how about registering it in a `ProjectConfig` or `ProjectListener#beforeProject`?

**Comment by sksamuel** [comment]
Can't use those as they are framework specific and assertions works outside
of kotest too.
But the general idea is a good one - we can allow registration on some kind
of Shows object.

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/issues/2021
