### ISSUE TITLE
forAll and forNone matchers on collections

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#664]
We have forAll and forNone _inspectors_ but they're not as easily found as assertion methods.
Maybe it's worth having simple versions like this

`names.forNone(_.isEmpty())`
`users.forAll(_.isActive())`

**Comment by LeoColman** [comment]
I think we've had this discussion about having the same matchers twice in a way. We concluded it would be somewhat confusing.

But I rather have the syntax on the collection itself, rather than having the collection as the first argument

**Comment by sksamuel** [comment]
We should add extension methods for inspectors then.

**Comment by LeoColman** [comment]
So we'll have both options referring to the same assertion?

I don't have any problems to that. Let me try to find our discussion on why we didn't like this possibility

**Comment by sksamuel** [comment]
So, 

this

`fun <T> forSome(array: Array<T>, f: (T) -> Unit) = ...`

can be

`fun Collection<T>.forSome(f: (T) -> Unit) = ...`

And we can also add

`fun Collection<T>.forSome(f: (T) -> Boolean) = ...`

Which is a simpler inline style that doesn't require further matchers.

**Comment by LeoColman** [comment]
I was looking at this, because I'm implementing them... I see that perhaps we already have the implementation?

https://github.com/kotlintest/kotlintest/blob/master/kotlintest-assertions/src/main/kotlin/io/kotlintest/inspectors/Inspectors.kt

It doesn't include boolean, but the rest is included. Is this correct?

**Comment by sksamuel** [comment]
Oh yes seems we do :+1:
