### ISSUE TITLE
between matcher for dates

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#665]
`mydate.isBetween(date1, date2)`

**Comment by LeoColman** [comment]
With this you mean Java's Date?

**Comment by sksamuel** [comment]
Yes, LocalDate, Instant, etc

**Comment by LeoColman** [comment]
Oh, ok. So not including the deprecated `java.util.Date`

**Comment by sksamuel** [comment]
No

**Comment by LeoColman** [comment]
We should have a matcher

`beBetween` for all the types, and a `shouldBeBetween`/`shouldNotBeBetween` for all types aswell.

**Comment by LeoColman** [comment]
Should we add a tolerance value?

**Comment by sksamuel** [comment]
don't need a tolerance on dates I don't think.

**Comment by LeoColman** [comment]
If we don't add tolerance, the user will have some hassle when using things like `LocalDateTime.now()`, as this exact now may be a little bit different from the `now` in some time from here.

Are we ok with that?

**Comment by sksamuel** [comment]
Well you can't really use now() for testing can you.
And if you have tolerance, how much tolerance? If it's a day your tests
will fail after a day. If it's a month they'll start failing after a month.
So it doesn't really work.

**Comment by LeoColman** [comment]
Sometimes you're testing thing likes

"And the creation date should be now", because inside that testing code you use `now()` and such. But I guess it doesn't make sense for `between`

**Comment by sksamuel** [comment]
Yes I see. Maybe then it would be useful I agree, so we could add something
like that.

`date.isApprox(now())`

**Comment by LeoColman** [comment]
Closed as per #694
