### ISSUE TITLE
Comparator matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#668]
We should support isLessThan, isGreaterThan on any type which supports comparable.

**Comment by LeoColman** [comment]
What should we do about comparables that already have those functions? For example Double, Int, Long...

**Comment by LeoColman** [comment]
Leaving the overload is bad because it causes confusion. The comparison is exactly the same, not even the message will change

**Comment by LeoColman** [comment]
What we can do on an `equal` case?

For example

`BigDecimal equals BigDecimal` isn't necessarily the same answer as `BigDecimal compareTo BigDecimal`.

How would we handle those cases? (`shouldBe` isn't enough)

**Comment by sksamuel** [comment]
Did you finish this ?

**Comment by LeoColman** [comment]
Bumping for discussion purposes.
There are some cases we didn't decide what to do

**Comment by sksamuel** [comment]
We don't need to worry about equals. We can just do what compareTo guarantees - less than, greater than.

**Comment by LeoColman** [comment]
I'm afraid that some matchers will become ambiguous.
```
1.0 shouldBeLessThan 1.1
```

Should it use the `Comparable` matcher or the `Double` matcher?

**Comment by LeoColman** [comment]
Also, what should we do about the current comparable matchers?

https://github.com/kotlintest/kotlintest/blob/master/kotest-assertions/src/commonMain/kotlin/io/kotest/matchers/comparables/ComparableMatchers.kt

Probably just enhance them, right?

**Comment by sksamuel** [comment]
I think we use Comparator where possible and deprecate the older ones.
