### ISSUE TITLE
Add support for PiTest

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#680]
There is a PiTest plugin for JUnit5.

@boazy has created a PR to add support for dynamic tests to this plugin, so it would work for KotlinTest (and I guess other frameworks liek it). In the absence of this PR being merged (or maybe even if it is), is it worth adding PiTest support as a KotlinTest extension.

https://github.com/pitest/pitest-junit5-plugin/pull/22

**Comment by boazy** [comment]
Thanks for directly addressing this issue! :+1:

I will keep the original PR for now in case other dynamic test frameworks need it.
