### ISSUE TITLE
Java files compiled with version 55

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#685]
Hey! I've been trying the new release to see if it's everything OK.

Not sure if this has something to do with this release, but when using the 3.3.0-RC2 version, I get this error:

`java.lang.UnsupportedClassVersionError: org/junit/jupiter/api/condition/EnabledIfSystemProperty has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

It doesn't happen when using the 3.2.1

It runs the tests anyway, it just appear as an initialization error, but it counts as a failed test:

![image](https://user-images.githubusercontent.com/9098977/52974290-c043db80-339f-11e9-80e1-acd8b773c910.png)

I've tried doing a mvn clean test, but it doesn't make any difference

Let me know if you need more information

_Originally posted by @leoxs22 in https://github.com/kotlintest/kotlintest/issues/628#issuecomment-464861959_

**Comment by leoxs22** [comment]
Maybe it's related to this answer?

https://stackoverflow.com/a/44263437

It says that the target and source tags should be inside a compileJava block, and not in the root

**Comment by sksamuel** [comment]
I've got it to work by adding the same flags to the java submodule.

**Comment by sksamuel** [comment]
I've released 3.3.0-RC3. Please give that a go and let me know (it will take 10 minutes to appear on maven central).

**Comment by mindhaq** [comment]
> I've released 3.3.0-RC3. Please give that a go and let me know (it will take 10 minutes to appear on maven central).

For me, this solved the problem.
