### ISSUE TITLE
new extension - algo benchmark

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#691]
Would be nice to say something like

```kotlin
test("some test name") {
  shouldBeLinear(1, 10, 100, 1000) { n ->
    runAlgo(n)
  }
}
```

```kotlin
test("some test name") {
  shouldBeQuadratic(1, 10, 100, 1000) { n ->
    runAlgo(n)
  }
}
```

**Comment by LeoColman** [comment]
Ok, so I was thinking on how to do this guy

I didn't find anything about benchmarking algorithms.

I think that perhaps our starting point can be something like

```
shouldBeLinear(Gen.int()) {  intList: List<Int> ->
    runAlgo(intList)
}
```

```
shouldBeLogarithmic(myUserGen) { userList: List<User> ->
     executeInserts(userList)    // This will guarantee that user insertion will be in logarithmic complexity    
}
```

and we can validate that against many common algorithms, just to be sure.

What do you think?

**Comment by sksamuel** [comment]
Yeah I think that's great.

But maybe,

shouldBeLinear {
}

And it comes with built in values - 2 4 8 16 32 64 etc and each time we
double, the time taken should be roughly double right (with some kind of
approximation allowed).

Maybe you can do

shouldBeLinear(iterations) {

}

and iterations is the power of 2.

**Comment by LeoColman** [comment]
I was thinking that we should use the user's generator, and not just give
them an integer.

**Comment by sksamuel** [comment]
I see what you're saying.
We will need to pass an int in to the system so the user can use that as
the number of items or whatever.

**Comment by LeoColman** [comment]
With a generator we  can take any amount we want, instead of premade. But i
guess the amount may be customizable
