### ISSUE TITLE
Feature spec not enabling focus

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#699]
When trying to use FeatureSpec, it's impossible to focus a test.

This is likely due to the way we setup the test code:

```addTestCase(createTestName("Feature: ", name)```

we don't allow for F: to be placed before Feature

**Comment by sksamuel** [comment]
Good spot. We need to detect the F: and move it before the Feature.
Same for !
And same for every spec that has a prefix!

**Comment by LeoColman** [comment]
I think that for Bang we already do this

**Comment by Kerooker** [comment]
I'll fix it in a quickie!

**Comment by LeoColman** [comment]
Fixing really soon.
