### ISSUE TITLE
Extension for mutation testing

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#702]
http://pitest.org/

Mutation testing is a rising testing methodology, and is supported by the library PiTest.

We should include an extension to enable mutant testing

**Comment by sksamuel** [comment]
Like this ? 
https://github.com/kotlintest/kotlintest/tree/master/kotlintest-plugins/kotlintest-plugins-pitest

**Comment by LeoColman** [comment]
Oh lol.

Yes, I think exactly like this. Oops.

**Comment by sksamuel** [comment]
It definitely needs a blog post writing about it though !
And adding to the 3.3 changelog #697

**Comment by LeoColman** [comment]
Is it documented anywhere?

**Comment by LeoColman** [comment]
I don't think it is. Might be important to know how to use it

**Comment by sksamuel** [comment]
Do you want to do that or me ?

**Comment by LeoColman** [comment]
I think it's better if you do it.

I have no idea how Pitest work, nor how KT integrated with it (I didn't even know we had lol)

**Comment by sksamuel** [comment]
I just did it one day last week. Never used PiTest myself but the
integration was easy.
