### ISSUE TITLE
Data Driven tests don't work with coroutines

### ISSUE THREAD

**Issue by PCasafont** [kotest/kotest#707]
As of 3.3.0, when trying to use `forAll(table, fn)` in Spec coroutine scope it will not compile as there are no suspend versions of the data driven utility functions.

**Comment by LeoColman** [comment]
Can you show us an example of a code that should compile?

**Comment by PCasafont** [comment]
My apologies. I am using FreeSpec and trying to add child specs inside a forall which exists within a parent spec. Example:

```
class Test : FreeSpec({
	"operations test" - {
		forall(
				row(1, 2, 3, -1),
				row(2, 3, 5, -1)
		) { a, b, c, d ->
			"addition" {
				a + b shouldBe c
			}
			"subtraction" {
				a - b shouldBe d
			}
		}
	}
})
```

**Comment by LeoColman** [comment]
Yes, that's incorrect. I'll be working on a fix right away

**Comment by LeoColman** [comment]
@sksamuel 
I don't see an easy alternative here.

We can make all the functions suspend, and assume that all the tests that will call them are going to be suspended anyways, but this would break individual functions that are not suspend, and will break the behavior from https://github.com/kotlintest/kotlintest/pull/633#issuecomment-459904472

We can drop the support for special parameter name, and let them be `a`, `b`, `c` and make the functions inlined. They can't be inline right now because `testfn` is used with `reflect()`, and it would make inlining impossible. If we drop the `reflect` capability, we will be able to inline it, and it will work in a suspended context
```
fun <A> forall(vararg rows: Row1<A>, testfn: (A) -> Unit) {
  val params = testfn.reflect()?.parameters?.mapNotNull { it.name } ?: emptyList()
  val paramA = params.getOrElse(0) { "a" }
  table(headers(paramA), *rows).forAll { a -> testfn(a) }
}
```

**Comment by LeoColman** [comment]
The second alternative is ok-ish, because we have `table(xx).forAll`, that use the same approach, with named parameters.

**Comment by sksamuel** [comment]
I don't think we should change `forall` to be inline, as the whole benefit of this variation is that you get the parameter names automatically derived. Better if we change `table(xx).forAll` to be inlined, then the original example could written in that style.

We could also add copies of these functions into a new .suspend package, where the functions are all marked as suspend, so you can use them in this situation.

**Comment by LeoColman** [comment]
> the whole benefit of this variation is that you get the parameter names automatically derived

I imagined that.

However, having copies of functions don't seem very optimal, even if it works. Are there many scenarios that this might happen in the future?

**Comment by sksamuel** [comment]
I think we only use reflection in this way in this particular function.

**Comment by PCasafont** [comment]
What about having suspend versions of all the data driven functions in a different package?

**Comment by sksamuel** [comment]
Thats what i suggested too. Probably an easy solution.

**Comment by PCasafont** [comment]
Oops sorry, I don't know how I managed not to get that from your discussion.

I guess that's the safest way to do it for now, leaving any further major changes for the next major version release.

**Comment by LeoColman** [comment]
The thing of adding to a different package is keeping two points of maintenance, and that's not very nice

**Comment by PCasafont** [comment]
You could also inline most of the functions except those giving trouble, which can be duplicated as suspend versions. That will reduce the amount of duplication.
