### ISSUE TITLE
Folder ".kotlintest" created on every run

### ISSUE THREAD

**Issue by xeruf** [kotest/kotest#720]
Whenever I run my tests, a ".kotlintest" folder containing an empty "spec_failures" file is created in my project root. I really dislike behaviour like this and don't really understand why the file is created at all if it is empty in the end.
If you have to create it, please at least put it somewhere in the "build" folder.

**Comment by sksamuel** [comment]
We should move it to the build folder, and not write it at all if it's empty.
In the meantime, you can disable it with `-Dkotlintest.write.specfailures = false`

**Comment by sksamuel** [comment]
I think for 3.3.2 we should revert the default behavior on this to be disabled.

**Comment by sksamuel** [comment]
This has been fixed in 3.3.2 @Xerus2000

**Comment by henrik242** [comment]
@sksamuel @Kerooker  How can I set the path for `.kotlintest`.  I'd like it to be in the `build` folder.

**Comment by sksamuel** [comment]
You can't, yet. You can tun it off though.

**Comment by xeruf** [comment]
I have tried  3.3.3 and 3.4.0, concretely `testImplementation("io.kotlintest", "kotlintest-runner-junit5", "3.4.0")`. Running `./gradlew test` still generates `.kotlintest` folders.

PS: @sksamuel just a little github tip: Instead of referencing the issue in the title, you can write "fixes #720" into the commit message and the issue will automatically be closed once the commit is merged ;)

**Comment by LeoColman** [comment]
More on that: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by xeruf** [comment]
This is still not working!

**Comment by sksamuel** [comment]
What version ?

**Comment by xeruf** [comment]
latest, as linked in the Readme

**Comment by xeruf** [comment]
Okay, seems to be working fine now, thanks :+1:
