### ISSUE TITLE
beforeTest() / afterTest() not run between test invocations

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#721]
I'm unable to tell from the docs whether this works as designed, but I observed in kotlintest 3.3.1 that a test with `invocations` > 1 does not have its `beforeTest()` / `afterTest()` called in between invocations. Which in my case makes the second invocation fail as `afterTest()` does some required clean-up of a temporary directory which must not exist when the test starts.

Could you please clarify what the intended behavior is / whether this is a bug, and if it's not a bug / works as intended, guide my to which is the proper way to clean-up between test invocations without duplicating too much code? In particular, would the introduction of `beforeInvocation()` / `afterInvocation()` be an option?

**Comment by sksamuel** [comment]
beforeInvocation() / afterInvocation is a great name for what I've struggled to come up with a name for in the past.

However I'm undecided if invocations should move out of the test case completely and into a helper function, which could also be used for threads, retries and timeout.

```kotlin
test("my test") {
  invocations(3).retry(2) {
     // some test
  }
}
```

The upside is that it greatly simplifies the implementation.
The downside is you can't hook into a listener.

**Comment by sschuberth** [comment]
I take your answer as a "it currently works as designed" 😉 As for how to implement a `beforeInvocation()` / `afterInvocation()`, I'm undecided and will leave that to you 😁

**Comment by LeoColman** [comment]
> The downside is you can't hook into a listener.

Prehaps the code `invocations(3)` could delegate to a part that registers every invocation to be processed by the listeners. It could be a little bit hackish, but I think it might work

**Comment by sksamuel** [comment]
Ok in the latest snapshot I have replaced invocations with replay(k, n).

eg

```
      replay(times = 10, threads = 3) {
      }
```

And they accept listeners which are just functions.
```
      replay(10, 3, before = {  }, after = {  }) {

      }
```

**Comment by sksamuel** [comment]
I actually reverted this and added beforeInvocation / afterInvocation to TestListener.
