### ISSUE TITLE
Add type inference for `shouldNotBe`

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#724]
```
val result = func(): String?
result shouldNotBe null
result as String
result.startsWith("...") shouldBe true
```

Having to cast result as String all the time wouldn't be necessary with `shouldNotBe null`.

**Comment by LeoColman** [comment]
Not possible, because only one condition in the contract is possible. There's no way to say "If bar == null then this != null".

The only alternative to this right now is to use `this.shouldNotBeNull()` if that's the intended behavior.

**Comment by sksamuel** [comment]
I don't know anything about contracts yet, but what's the difference ?

**Comment by LeoColman** [comment]
Contracts only have some behaviors. We can't use an arbitrary boolean as a behavior, such as `if b is null`

**Comment by LeoColman** [comment]
Not yet, at least
