### ISSUE TITLE
New matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#731]
set.shouldBeSingleton()
list.shouldBeSingleton()

**Comment by Kerooker** [comment]
Just shouldBeSingleton?

**Comment by LeoColman** [comment]
Isn't it shorter to say `set.size shouldBe 1` or `set shouldHaveSize 1`?

**Comment by LeoColman** [comment]
Idk in which scenarios one would use "Oh, exactly at this point of code, the set should be a singleton". Do you know if this has any use cases?

**Comment by sksamuel** [comment]
I was writing some tests that assert that a generated id is idempotent. I
do it by running the code several times and asserting that the set of the
outcomes has size 1.

**Comment by sksamuel** [comment]
It's just an alias for hasSize(1).

**Comment by LeoColman** [comment]
This is also similar to `shouldHaveSingleElement`

**Comment by sksamuel** [comment]
Oh yeah I guess that's the same thing.

**Comment by sksamuel** [comment]
Singleton is what Java calls it though so could be nice ot have an alias.

**Comment by LeoColman** [comment]
`shouldHaveSingleElement` also requires an element, so I guess we want to say "I don't care which element, I just want one"
