### ISSUE TITLE
eventually should handle AssertionError by default

### ISSUE THREAD

**Issue by codyoss** [kotest/kotest#753]
Is there a good reason that kotlintest `eventually` does not handle AssertionError by default. I was reading another issue #145 and it seemed like it was talked about, but there was no clear reason to why this was not adopted...

To re-state what was said there, it would be nice to write:
```kotlin
    "find the 1000 number" {
        val iterator = (1..1000).iterator()
        eventually(2.seconds) {
            iterator.next() shouldBe 1000
        }
    }
```

instead of:
```kotlin
    "find the 1000 number" {
        val iterator = (1..1000).iterator()
        eventually(2.seconds, AssertionError::class.java) {
            iterator.next() shouldBe 1000
        }
    }
```

To me I can't think of too many use cases where I would not want to do an assertion in that block, thoughts?

**Comment by sksamuel** [comment]
Yes, it seems a bit silly that the first case is not handled.

**Comment by codyoss** [comment]
In that case, I think I will take a stab at an implementation...

**Comment by sksamuel** [comment]
Please do!
