### ISSUE TITLE
Public internal classes

### ISSUE THREAD

**Issue by nomisRev** [kotest/kotest#755]
Hi,

I ran into an issue today where my code conflicted with `KotlinTest` due to internals being public. [NamedThreadFactory](https://github.com/kotlintest/kotlintest/blob/1678cb5292097fce6f01aaae5fa3cee1960dcd1b/kotlintest-runner/kotlintest-runner-jvm/src/jvmMain/kotlin/io/kotlintest/runner/jvm/internal/NamedThreadFactory.kt)

Given that it's located in an internal package I assume this should also be internal and perhaps some others.

If you're interested in a PR let me know and I'll create one tonight 👍 

👏 nice work on KotlinTest

**Comment by sksamuel** [comment]
PR welcome !
