### ISSUE TITLE
Intellij : is it possible to run a single method of a spec ?

### ISSUE THREAD

**Issue by christopheblin** [kotest/kotest#756]
When you run a spec file in intellij and the spec file has multiple tests, is it possible to run only one of them ?

This is possible with a classical JUnit test, but it does not seem to work with kotlintest ...

This is very annoying when you have a dozen of tests and only one of them is failing because you can not assign a breakpoint easily :(

![Capture d’écran 2019-04-30 à 13 59 42](https://user-images.githubusercontent.com/11044877/56960181-47f05800-6b50-11e9-951c-2c59b6411c6c.png)

**Comment by LeoColman** [comment]
It's possible, yes.

However, for that you have to use KotlinTest IntelliJ Plugin, which is available in [Jetbrains Repository](https://plugins.jetbrains.com/plugin/11585-kotlintest)

**Comment by christopheblin** [comment]
I've just installed the plugin and I correctly see buttons to launch a single test.

However, when I click on a single test, it still launches all the tests and stops on breakpoints in other tests.

Please see attached screenshot

![Capture d’écran 2019-04-30 à 14 19 34](https://user-images.githubusercontent.com/11044877/56961156-4e340380-6b53-11e9-99a0-55ed5653adc6.png)

**Comment by christopheblin** [comment]
BTW, when I click the button it says "Run TmpSpec" whereas I would expect something like "Run TmpSpec should fail" ...

Do you have any idea ?

**Comment by christopheblin** [comment]
Ah ok I think I found a strange bug (well this is something I can not explain).

Here is a screenshot of another spec where I can effectively choose to debug only one of the test

Whereas the TmpSpec still does not provide me this option ...

I've tried to use "inner tests" in the TmpSpec but it does not change anything.

Other classes have the same problem, I do not manage to identify what is different from one class where it works to another where it does not ...

**Comment by christopheblin** [comment]
Ah OK, I've finally found the problem !

If you already have a jUnit configuration for a test, it will not propose to run with kotlintest plugin !

That is why it works on some classes (the one without a configuration) and not on other classes (the one with an existing configuration)

So I will close this issue, sorry for bothering you :)

**Comment by LeoColman** [comment]
You're not bothering at all, really!

This issue shows that you're interested in our project and doing your best to work with it! It actually flatters me to know that you took your time to come here and open an issue to understand how things work!

Glad we could help. If you find any weird behavior with the plugin (it was recently launched), please let us know by creating an issue in the[ plugin's repository](https://github.com/kotlintest/kotlintest-intellij-plugin)
