### ISSUE TITLE
Can extensions disable or skip a testcase?

### ISSUE THREAD

**Issue by jameskleeh** [kotest/kotest#760]
I'd like to skip or disable a test case in an interceptor 

`fun beforeTest(testCase: TestCase)`

The `testCase.config` is final so I can't change it in the interceptor. Is there some other means of doing so?

**Comment by jameskleeh** [comment]
Sorry for the noise, looks like its not possible with a listener, but I need to use a TestCaseExtension

**Comment by LeoColman** [comment]
Yes. Usually listeners are to act after action.
With an extension you can actually change the action.


Don't worry about the noise! We're here to help XD

**Comment by sksamuel** [comment]
Yes listeners are passive only. Extensions are active.
