### ISSUE TITLE
Enhance DescribeSpec with xMethods

### ISSUE THREAD

**Issue by dmstocking** [kotest/kotest#763]
It would be awesome to be able to do Jasmine/Mocha tests with nested `describe`. I don't know if this would just be a change to the `DescribeSpec` or its own thing. The change is quite small none the less. It would also be nice to have `xdescribe` and `xit` to disable tests.

```
class CalculatorTest: WhateverSpec({
    describe("A calculator") {
        describe("addition") {
            it("returns the sum of its arguments") {
                assertEquals(3, Calculator().add(1, 2))
            }
        }
    }
    xdescribe("Skipped test") {
        it("should not run this") {
            throw Exception()
        }
    }
})
```

**Comment by sksamuel** [comment]
I think this is great to add.
And I like the idea of x to disable too.

**Comment by sksamuel** [comment]
This will be added to 4.0

**Comment by sksamuel** [comment]
Maybe we enhance DescribeSpec or maybe we add MochaSpec.

**Comment by sksamuel** [comment]
Completed in master for 4.0
