### ISSUE TITLE
Can't use forAll inside a given or when

### ISSUE THREAD

**Issue by gabrielittner** [kotest/kotest#765]
E.g.
```
given("some stuff") {
	listOf(...).forAll {
        `when`("something happens") {
		     //...
         }
    }
}
```
This will result in `Suspension functions can be called only within coroutine body`.

**Comment by LeoColman** [comment]
I'll close this as a duplicate of #717.

I'm working on it.

Thanks for the report!

**Comment by gabrielittner** [comment]
Thank you and sorry for the duplicate, missed the other issue.
