### ISSUE TITLE
Snapshot testing.

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#777]
Maybe some inspiration here:
https://github.com/Karumi/KotlinSnapshot

**Comment by sksamuel** [comment]
https://ro-che.info/articles/2017-12-04-golden-tests

**Comment by krzema12** [comment]
@sksamuel could you share a reason why you decided to not imolrment it in kotest?

**Comment by krzema12** [comment]
Discussion: https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1675945289526739?thread_ts=1675945289.526739&cid=CT0G9SD7Z

**Comment by Kantis** [comment]
Perhaps we could list some desired use-cases here? I think it would be nice to be able to use various matchers for snapshot testing.. (For instance testing JSON equality, partial JSON equality, testing JSON Schema and so on)

Sshould we have explicit methods for every matcher, or should snapshot testing take a matcher as argument?

**Comment by krzema12** [comment]
@Kantis I thought about the very basic use case in scope of the first iteration, which is dumping an object/collection and then exact comparison. Other marchers may be a good idea in the next iterations to enable checking of structures that contain some non-determinism, e. g. various order of elements - is that your intent?

**Comment by Kantis** [comment]
Sounds good. Still, as can be seen in the [linked tool](https://github.com/Karumi/KotlinSnapshot) for snapshot testing, there's a lot of nuance. (How do we serialize? Should private properties matter? How can the user tweak these serialization options?)

I also think there's a possibility here to add really good tooling. A previous workplace used snapshot testing, and if you ran a snapshot test in an interactive environment (e.g. if it detected intelliJ) it would pull up a diff view of the failure and let you choose whether to overwrite the snapshot interactively. I think that would be a really neat feature to add along the line :) 

I've also been mulling whether we can somehow make matchers snapshot-aware. E.g. if we somehow added a middleware in testing where you could call a `Matcher<T>` with a `Snapshot<T>` which would load the snapshot and test it, and handle failures, overwrites, interactivity, etc..

**Comment by nedtwigg** [comment]
- https://github.com/kotest/kotest/pull/3870###
