### ISSUE TITLE
withClue: Clues should be nestable

### ISSUE THREAD

**Issue by lenalebt** [kotest/kotest#783]
Consider this case (taken from the tests):

```
      withClue("clue outer:") {
        shouldThrow<AssertionError> {"1" shouldBe "2" }.message shouldBe "clue outer: expected: \"2\" but was: \"1\""
        withClue("clue inner:") {
          shouldThrow<AssertionError> {"3" shouldBe "4" }.message shouldBe "clue inner: expected: \"4\" but was: \"3\""
        }
        shouldThrow<AssertionError> {"5" shouldBe "6" }.message shouldBe "clue outer: expected: \"6\" but was: \"5\""
      }
```
The error message from the inner clue does not contain the outer clue, as in it is: `"clue inner: expected: \"4\" but was: \"3\""` and imho should be along the lines of `"clue outer: clue inner: expected: \"4\" but was: \"3\""`.

Sometimes it is very helpful when you get more information about what exactly went wrong in your test case. We're using a similar approach in our tests that allows nesting clues, which really helps seeing what exactly failed.
This is most useful in more complicated integration tests. The clue in these cases would not be a simple string, but an object (e.g. the complete http response of a service where we checked the status code):

```
val httpResponse = doSomething()
httpResponse.asClue {
  it.status.shouldBe(307)
  it.header.location.asClue { header ->
    header.isPresent.shouldBe(true)
    header.get().shouldContain("http://")
  }
}
```
Would you be open for a PR in that direction?

**Comment by sksamuel** [comment]
Yes, very much open to a PR. I think this is a great idea.
