### ISSUE TITLE
withConstantNow only mock the NoParameterNowFunction

### ISSUE THREAD

**Issue by kelly-yinn** [kotest/kotest#790]
I used the `Current instant listeners` to test the `now value` in my test code.

And I declared as following:
```
override fun listeners() = listOf(
        ConstantNowTestListener(now)
    )
```

But I found that if the call is `ZonedDateTime.now(zoneId)` not  `ZonedDateTime.now()`, what I obtained is not the `fixed now value`.

By analyzing the source code, I found it seems that we just mock the `no parameter now function`.  
So in order to be consistent with my test code. I first call `ZonedDateTime.now()` and then convert it according to the given `zoneId`. 

So I think maybe it would be better to mock more `now function`.

**Comment by LeoColman** [comment]
This makes sense.

Would you like to make a pull request?

**Comment by kelly-yinn** [comment]
Thanks for your reply. 

I'd like to have a try and make a pull request.

**Comment by LeoColman** [comment]
Great!
Let me know if you have any troubles with it!

**Comment by kelly-yinn** [comment]
Hi, so sorry for my late reply. 
I have created a pull request: https://github.com/kotlintest/kotlintest/pull/798. 

And I mocked `now(zoneId)` for 3 classes: `ZonedDateTime`, `OffsetDateTime` and `LocalDateTime`, also I put the reasons why I did not mocked the `now(zoneId)` for other classes in the PR description.

There may some errors，typos  and ugly code exist for my lack of experience, so sorry for that and wait for your feedbacks.

**Comment by sksamuel** [comment]
@Kerooker any idea on this one ?

**Comment by LeoColman** [comment]
I think this was depending on the PR, but I think it was not completely done and now is distant from the master branch

**Comment by sksamuel** [comment]
I think it was that you can't use now(zoneId) with the listener.

**Comment by LeoColman** [comment]
Yes, that was the feature request

**Comment by kelly-yinn** [comment]
Yes, it was that we can't use `now(zoneId)` and `now(clock)` with the listener. Let me have a try on Sunday :)
