### ISSUE TITLE
Map matcher should{Not}Contain support for Pairs

### ISSUE THREAD

**Issue by rses** [kotest/kotest#791]
At the moment, the most terse map matcher is of the form:

```kotlin
map.shouldContain("key", "value")
```

It would be nice to add support to be more fluid by using `Pair` to say:

```kotlin
map shouldContain ("key" to "value")
```

This is a very small fix which I can create a PR for, but just checking if this is something that will be accepted.

**Comment by LeoColman** [comment]
I Agree with you!

This should be added, and if you're interested in making a PR, go for it! We'll be very happy to assist you with anything if you need :)
