### ISSUE TITLE
Eventually should allow configuration for space between requests

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#793]

**Comment by matheusmessora** [comment]
Based on Awailitiy, this is called Pooling.
Also, should be great if we create a default configuration from Duration and Pooling. 
At the moment, `eventually` calls a while(true) method.

**Comment by sksamuel** [comment]
Yeah we must improve eventually. I looked at awatility and it seems to be basically the same as our eventually.

I think what we need to support are different durations, different polling methods, and what awaitility calls conditional evaluation listeners. https://github.com/awaitility/awaitility/wiki/Usage#condition-evaluation-listener

Happy for anyone to pick up this or I can tackle it.

**Comment by matheusmessora** [comment]
I'll try to work on that

**Comment by LeoColman** [comment]
We're here to help if needed.

**Comment by matheusmessora** [comment]
The actual eventually receives all the data inside the method parameters. For a non-breaking change, we can add more parameters with default values.

My suggestion is to create a "new" eventually. Maybe _`eventual`_ returning a factory with customizable methods. Similar to awaitility.
This will improve the extensibility of the _eventual_ function.
The polling interval by the default is already configured. 

The result could be something like this:
`eventual() { 1 == 1 }` 

`eventual().during(ofSeconds(2)) { 1 == 1}`

`eventual().during(2).ignoreExceptions() { 1 == 1}`

`eventual().ignoreExceptions(IOException.class) { 1 == 1}`

What do you guys think?

**Comment by LeoColman** [comment]
Perhaps we can use the `eventually` construct, but deprecating the current `eventually` in favor of the builder alternative, and remove it in the future.

But I believe that using a `builder` is too much Javalistic, and we should come up with a better DSL for it (I don't have any suggestions yet :P)

**Comment by matheusmessora** [comment]
Do you have a example of a good one?
_PS: I came from Java. Don't judge me_

**Comment by sksamuel** [comment]
eventually(polling = exponential(8), delay = 4.seconds, ..... and so on) {

}

Then you can do

eventually {

}

If you're happy with the defaults.

And it's 100% backwards compatible.

**Comment by LeoColman** [comment]
I liked your example, @sksamuel

**Comment by sksamuel** [comment]
I would like to see this in 3.4 so I can pick this up if it's stalled.
