### ISSUE TITLE
Around advice in the spec DSL

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#794]
```kotlin
class MyTest : WordSpec() {
  private val manager = ...
  override fun aroundTest(test: () -> TestResult) { 
    manager.transaction.begin()
    test()
    manager.transaction.commit()
  }
}
```

**Comment by sksamuel** [comment]
@Kerooker  ?

**Comment by LeoColman** [comment]
Perhaps this can be implemented as an extension?

**Comment by sksamuel** [comment]
Yes, we just need to make Spec itself have a `aroundTest` and `aroundSpec` method which create an extension and register it. No-op by default. Like we do for the other spec methods which just delegate as a listener.

**Comment by LeoColman** [comment]
Do we want to add more things to the spec class?

I believe this can be delegated to a listener that has a `beforeTest` and `afterTest`, without the need to add another construct. What do you think?

**Comment by sksamuel** [comment]
Can it?

**Comment by LeoColman** [comment]
Similar to the `constantNow` listeners, it runs beforeTest and afterTest, isn't that what we kinda want?

**Comment by sksamuel** [comment]
Yes, but it's the ability to keep a variable in scope.

val a = A()
runTest
a.stop()

**Comment by LeoColman** [comment]
I think we can do that with listeners, can't we?

**Comment by sksamuel** [comment]
Now without creating the variables outside of the before / after scopes.

**Comment by sksamuel** [comment]
This can be easily done with the new DSL.

**Comment by sksamuel** [comment]
Question/todo: add extension callbacks to the new DSL like the other callbacks.

**Comment by sksamuel** [comment]
I had a little play with this:

eg

```kotlin
   aroundTest { runtest ->
      println("Starting test")
      runtest {
         println("After test")
      }
   }
```

**Comment by sksamuel** [comment]
Now in master.
