### ISSUE TITLE
Before/After Test

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#795]
At the moment, we call all the before tests first, then all the after tests.
I think this should change.

**Comment by LeoColman** [comment]
What would you change it to?

**Comment by sksamuel** [comment]
before/after before/after before/after

**Comment by LeoColman** [comment]
I don't think that's possible, as we need all befores to be run before,
right? Not possible to ever run a after test before a beforeTest

**Comment by sksamuel** [comment]
I'm not sure, but if you think about top level tests, it makes sense for
the after test to complete before the next test's before test.
Otherwise you might as well just be using before/after spec.

**Comment by LeoColman** [comment]
I believe that's how we run it already, isn't it? One beforeTest will trigger per test, right?

**Comment by sksamuel** [comment]
Let's say I want a transaction per test.

beforetest {
startTx
}

afterTest {
commitTx
}

At the moment it will call startTx for all tests before any are committed,
meaning the tx manager throws an exception.

**Comment by LeoColman** [comment]
I see. Yeah, it makes sense.
Could this be due to isolation mode? I usually fix stuff by messing with isolation hahha

**Comment by sksamuel** [comment]
Isolation mode definitely works, but it's still confusing.

**Comment by sksamuel** [comment]
Added test to confirm the order in master.
