### ISSUE TITLE
KotlinTestEngine does not obey JUnit5 extension points

### ISSUE THREAD

**Issue by lenalebt** [kotest/kotest#799]
Hi together,
I am currently trying to use Kotlintest together with Micronaut (https://docs.micronaut.io/latest/guide/index.html). Micronaut has some integration with JUnit5, and I am able to run tests with JUnit5.

However, I'd like to use Kotlintest. Digging on why it does not work correctly, I stumbled upon the `KotlinTestEngine` and as far as I understand, it does not emit the callbacks defined here: https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order-overview

Is that on purpose? I think this is what breaks Micronaut integration.

JUnit5 docs say (https://junit.org/junit5/docs/current/user-guide/#extensions-supported-utilities): "TestEngine and Extension authors are encouraged to use these supported methods in order to align with the behavior of the JUnit Platform."

In see that not all of the concepts match 100%, but I think it would be beneficial to nevertheless emit the default JUnit5-Callbacks.

**Comment by lenalebt** [comment]
This is how the micronaut integration works: https://github.com/micronaut-projects/micronaut-test/blob/master/test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java

As you can see, they make heavy use of the callback mechanisms of JUnit5. I could not see any of that in https://github.com/kotlintest/kotlintest/blob/master/kotlintest-runner/kotlintest-runner-junit5/src/main/kotlin/io/kotlintest/runner/junit5/KotlinTestEngine.kt

**Comment by sksamuel** [comment]
I think we can add those interfaces pretty easily. Let's target this for 3.4

**Comment by lenalebt** [comment]
Sounds good for me. I can work around some of the limitations for some time by manually creating application contexts etc :)
