### ISSUE TITLE
use contracts for arrow matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#802]
shouldBeLeft() { left -> }
shouldBeRight() { right ->

@Kerooker would this work or does it need generic contracts?

**Comment by LeoColman** [comment]
This likely needs the generic contracts.
But what would this be for? To infer Right type, for example?

**Comment by LeoColman** [comment]
Or to infer that there's no right if left returns?

**Comment by sksamuel** [comment]
For example,

```
val either: Either<String, Long> = ...
either.shouldBeRight() 
// after this the contract states its now a right.
either.b.shouldHaveLength(10) // b is a property only on "rights"
```

Do we need generic contracts for this ?

**Comment by sksamuel** [comment]
I'll put this in 3.4 for now as it's quite exciting to me, but it could go to 3.5 if needed.

**Comment by sksamuel** [comment]
Added contracts for Try as well.
