### ISSUE TITLE
Generate junit report even when no tests

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#809]
Our Jenkins job requires a junit test report or the build files.
Switching to KotlinTest and the build fails. We need to make sure we generate a report in the same way junit does.

**Comment by LeoColman** [comment]
Interesting...
I use KotlinTest + Jenkins, and I usually manually check results from JUnit

Never had a problem with that. Can you explain a little more what is going on?

**Comment by sksamuel** [comment]
```exception in build: hudson.AbortException: No test report files were found. Configuration error?
[Pipeline] echo
currentBuild.result is: FAILURE
[Pipeline] echo
currentBuild.getPreviousBuild().result is: FAILURE```

**Comment by sksamuel** [comment]
But it does generate something.
```
Finished generating test XML results (0.001 secs) into: /home/ec2-user/workspace/memphis_master-TDRZQV2SQWYAZJ4GL7DENUSI3XAIFRB3HH4IRQUOIRZUSHEVLVDA/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.017 secs) into: /home/ec2-user/workspace/memphis_master-TDRZQV2SQWYAZJ4GL7DENUSI3XAIFRB3HH4IRQUOIRZUSHEVLVDA/build/reports/tests/test```

I assume this is the gradle junit5 platform task doing this. I guess junit jupiter does something extra that the build here looks for.

**Comment by sksamuel** [comment]
`junit '**/build/test-results/test/*.xml'` from jenkins pipeline

**Comment by sksamuel** [comment]
So the bug is that having no tests doesn't generate a test report file.
It should probably generate the file but have count=0 in the XML.

**Comment by sksamuel** [comment]
This was not a bug, just that the junit5 platform support was not setup.
