### ISSUE TITLE
Add matchers for Throwables

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#810]
Throwables are usually tested regarding the message they'll display, the exception that caused them, and perhaps the stacktrace(this may be rarer.)

I usually see code like

```
try {
    foo()
} catch(e: Exception) {
    e.message shouldBe "Foo"
}
```

Of course, this can be reduced to testing with a `shouldThrow` of some sort. But the point is, these matchers are always in the exact format.

So I propose

```
thrown shouldHaveMessage "foo"
thrown shouldBeCausedBy otherException
```

Maybe other matchers will fit here (such as `localizedMessage`), but I think these are essential.

**Comment by sksamuel** [comment]
What is "thrown" in this case ?

**Comment by LeoColman** [comment]
Sorry, it's the thrown exception.

Simple use case:
```
val foo: Exception = createException()
foo. shouldHaveMessage "foo"
```

**Comment by sksamuel** [comment]
Well it doesn't hurt to add them.

What about also,

someFunc(1,2).shouldThrow {
  it.message shouldBe "some msg"
  ...
}

**Comment by LeoColman** [comment]
I don't think that's a valid syntax. The function would already be executed, wouldn't it?

**Comment by sksamuel** [comment]
Yes good point I'm being stupid

**Comment by LeoColman** [comment]
It could be an extension to a function, and then 

```
::myfunction.shouldThrow()
```

but that seems odd hahha

**Comment by LeoColman** [comment]
But I liked the idea of having access to the throwable inside the lambda
It's currently `() -> Unit`

**Comment by sksamuel** [comment]
Yeah but it's a bit pointless if you already have the exception. Then you
might as well just do exception.message.shouldBe ""

**Comment by sksamuel** [comment]
Are we going to do anything on this or leave it ?

**Comment by LeoColman** [comment]
I think it was merged, no?

Em sáb, 13 de jul de 2019 13:43, Stephen Samuel <notifications@github.com>
escreveu:

**Comment by sksamuel** [comment]
Ok. I know there was two.
