### ISSUE TITLE
ShouldThrow matchers should allow testing for message and cause

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#811]
I said something about this at #810, but it can be a different issue.

I usually see code used with `shouldThrow` being used in this fashion:

```
val throwable = shouldThrowAny { foo() }

throwable.message shouldBe "fooBar"
```

We should come up with a syntax to allow the `shouldThrow` matchers (all of them, of course) to explicitly test for the message.

An idea would be to optionally receive a message parameter:

```
shouldThrowAny(message = "fooBar") { foo() }
```

But I don't like this approach.

What I usually see is also
```
shouldThrowAny {
foo()
}.message shouldBe "fooBar"
```

But I don't know if it's descriptive enough.

Thoughts? @sksamuel

**Comment by sksamuel** [comment]
I tend to do the latter. 

```
shouldThrow { 
  foo() 
} withMessage "fooBar"
``` ?

**Comment by sksamuel** [comment]
```
shouldThrowWithMessage("wibble") { 
  // test
}
```

or simplyy

```
shouldThrow("wibble") { 
  // test
}
```

Even
```
shouldThrow(
  {  test here },
  { block with exception as receiver here }
)
```

Or
```
shouldThrow {
  // test
}.assertException {
  // exception as receiver here
}
```

But I'm not sure what we have is that bad.

**Comment by faogustavo** [comment]
Why not just keep the same "syntax" and just add some throwable matchers?
Playing with the lib, I built those:

| Throwables / Exceptions | |
| ---- | --- |
| `throwable.shouldBeOfType<T>()` | Asserts that the throwable is of type T. |
| `throwable.shouldBeExactlyOfType<T>()` | Asserts that the throwable is **exctly** of type T. |
| `throwable.shouldHaveMessage(message)` | Asserts that the throwable message is the same of the given one. |
| `throwable.shouldHaveCause()` | Asserts that the throwable have a cause. |
| `throwable.shouldHaveCause { block }` | Asserts that the throwable have a cause, and pass it as parameter to the block |
| `throwable.shouldHaveCauseOfType<T>()` | Asserts that the throwable have a cause and it is of type T. |
| `throwable.shouldHaveCauseOfExacltyType<T>()` | Asserts that the throwable have a cause and it is **exaclty** of type T. |

And to test, I just use the same existing syntax like this :point_down: 
```
shouldThrowAny { 
    throw FileNotFoundException("this_file.txt not found") 
} shouldHaveMessage "this_file.txt not found"

shouldThrowAny { 
    throw CompleteTestException() 
}.shouldHaveCauseOfType<FileNotFoundException>()

Result.failure<Any>(FileNotFoundException("this_file.txt not found"))
    .exceptionOrNull()!! 
    .shouldBeOfType<FileNotFoundException>()
```

If they are OK, I can open a PR with them.

**Comment by LeoColman** [comment]
We suggested that earlier.

If you're ok with doing this, feel free to PR these matchers! They'll be really helpful!
