### ISSUE TITLE
Figure out why kotlintest brings in logging to other projects

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#816]
Everytime I start a new project, I get loads of kotlintest logging.
Now, simply having the logging statements shouldn't matter. Something is bringing in a logging configuration and I think it's KT. Although the log4j dependencies are only in test scope.

**Comment by sksamuel** [comment]
Same issue as this, although I'm not using spring boot.
https://github.com/kotlintest/kotlintest/issues/394

**Comment by LeoColman** [comment]
Perhaps the user's configuration isn't blocking KotlinTest, and we should add a config to explicitly block it?

**Comment by sksamuel** [comment]
I've created a blank project with no other deps and it still happens. So it's either KotlinTest to blame or something KT brings in.

**Comment by sksamuel** [comment]
Fixed by removing log4j from the project.
