### ISSUE TITLE
Some new matchers to add

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#817]
Pair.shouldBePair(x,y)
File.isSymbolicLink
Path.isSymbolicLink
File.shouldHaveParent
Path.shouldHaveParent
Number.shouldHaveRoot

The URI matchers should also work on URLs. I'll make another ticket covering that.

**Comment by LeoColman** [comment]
I'll split this is some isues, so contributors can tackle one at a time, ok?

**Comment by sksamuel** [comment]
Absolutely.

**Comment by sksamuel** [comment]
Plus add anymore you think of.

**Comment by LeoColman** [comment]
Sure xD

**Comment by faogustavo** [comment]
Was this task split? I've almost done all of them.

**Comment by sksamuel** [comment]
I guess add the pair one. The root one can probably be left. @faogustavo

**Comment by faogustavo** [comment]
We can close this now, right?

**Comment by LeoColman** [comment]
I think so, yes.

BTW, @faogustavo 
feel free to join us at kotlinlang.slack.com
We are in channels #kotlintest and #kotlintest-devs
