### ISSUE TITLE
ShouldBeZero matcher

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#819]
`Int`, `Double`, `Long`, (...) should have a special matcher to verify if it's zero.

This matcher should also have an opposite, to verify it's not zero.

```
myInt.shouldBeZero()
myDouble.shouldNotBeZero()
```

Special cases to pay attention to: `Double.NaN` and `Double.POSITIVE_INFINITY`/`Double.NEGATIVE_INFINITY`.

These can be added to the `kotlintest-assertions` module. There can be a matcher for each numeric type, or a `Number` matcher that match them all.

An example on how to start the `isZero` method:

```
fun Number.isZero(): Boolean {
  return when(this) {
    is Double -> this == 0.0    // Verification for NaN
    is Float -> this == 0.0     // Verification for NaN
    else -> this.toLong() == 0L
  }
}
```

**Comment by sksamuel** [comment]
This could go in either 3.4 or 3.5 depending on time.
