### ISSUE TITLE
New matchers for BigDecimal: isZero, precision, scale, positive, negative

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#821]
We have many matchers for Numeric types, but not any matcher for BigDecimals.

We should include some, in a new package: `io.kotlintest.matchers.bigdecimal`, in the `kotlintest-assertions` subproject.

Some matchers that should be included (don't forget to add the negated version):

```
bigDecimal.shouldBeZero()

bigDecimal shouldHavePrecision 15

bigDecimal shouldHaveScale 30

bigDecimal.shouldBePositive()

bigDecimal.shouldBeNegative()
```

among others, if you find it necessary.

Remember to update the documentation as well, to add a new section: BigDecimals
https://github.com/kotlintest/kotlintest/blob/master/doc/matchers.md

And, of course, add the necessary tests for the new functions.

**Comment by wevnasc** [comment]
I am working on it.
