### ISSUE TITLE
field extraction based matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#822]
AssertJ has the ability to run assertions against arbitrary fields that you don't know at compile time.

So something like,

`any.shouldHaveFieldValue("field", "value")`

We can extract a type too

```kotlin
any.extractProperty<T> {  t ->
  t.shouldHave....
}```

**Comment by mikezx6r** [comment]
Here's docs for recursive comparison. https://assertj.github.io/doc/#assertj-core-recursive-comparison

**Comment by LeoColman** [comment]
Wouldn't this make your test very dependant on the implementation?

Explicitly typing the field to the test doesn't seem a very good practice IMO

**Comment by sksamuel** [comment]
It might not be the preferred approach but it's quite popular in assertJ so we should offer it as well. A use case is testing code that works reflectively.

**Comment by mikezx6r** [comment]
If you decide to implement this feature, I'd suggest focusing on the Recursive Comparison. This does use reflection and is very helpful for verifying conversion/DTO transformation code.

Create the expected object, execute the test code, and then compare the actual object to the expected. Any fields that don't match will be flagged. Additionally, can ensure all fields are non-null (if that's a requirement) and various other things.

This is the main functionality used IMO. Android apps may not do this, but back-end code tends to have a lot of conversions, and this helps make testing a bit easier.

**Comment by sksamuel** [comment]
I think it's a great feature. I'm 100% in support.

**Comment by sksamuel** [comment]
I think the recursive comparison is more covered in #826 actually.

**Comment by sksamuel** [comment]
This is now in 4.0 snapshot.
