### ISSUE TITLE
Multi-line-string comparison for file contents

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#823]
AssertJ performs multi-line string comparison on file contents automatically.
Can KotlinTest do the same ?

**Comment by sksamuel** [comment]
So, in other words, File("foo").shouldHaveContent(File("other")) should use the multi-line-string comparison output if they are both text files.

**Comment by sksamuel** [comment]
This could be 3.5 depending on how we do time wise.

**Comment by imanushin** [comment]
```File("foo").shouldHaveContent(File("other"))```

I have a bit complex behavior:
1. Comparison should ignore line ending. E.g. both files should be splitted by ```\n\r```
2. Comparison should be line by line, e.g. in happy path it is better to avoid whole files into the memory (and split doubles the memory required)
3. All lines should be trimmed. E.g. ```\t123``` is the same with ```123 ```
4. All empty lines should be ignored.
5. The [Longest common subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) algorithm should be applied. In this case, if files A is file B plus 3 lines in the beginning, then only these three lines are different, not all lines.
6. Error output should be compatible with IDE
7. Comparison result should be trimmed (for case, when just several lines were changed)

Why it is needed: my services generates html/json/xml (all of them). And I'd like to compare pretty-printed result with golden states.

Unfortunately, I found [this method only](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/internal/Files.html#assertSameContentAs(org.assertj.core.api.AssertionInfo,%20java.io.File,%20java.nio.charset.Charset,%20java.io.File,%20java.nio.charset.Charset)), which is the closest one.

I'll try to return later and implement all these options...

**Comment by sksamuel** [comment]
For Json, you could use our json matchers willwhich will compare ignoring
pretty printing.

**Comment by imanushin** [comment]
@sksamuel, yes, agree. However html golden state comparison needs patching for me for now.

**Comment by sksamuel** [comment]
Added in master.
