### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by reckter** [kotest/kotest#824]
Is there a reason that this project is using 2 instead of 4 spaces? 
And have you considered using a linter? https://ktlint.github.io is a good, no configuration one, that follows the Kotlin coding convention. 

I just wanted to contribute, but that 2 spacing rule really threw my IntelliJ and myself way of. Auto formatting is throwing a fit with the project files sadly :/

**Comment by LeoColman** [comment]
@sksamuel May answer you due to why we chose this

But as a tip, you can customize IntelliJ style warnings per project on it's settings, that way it won't complain about 2 space indentation and will correct that for you

**Comment by sksamuel** [comment]
I was a Scala developer for 8 years and picked the style up there. Don't you think it's much nicer?
Even if not, you can just ignore it, feel free to submit a PR with 4 spaces, I don't mind.

**Comment by reckter** [comment]
I think it always looks a bit cramped to the left, and following the coding standard of the language helps others conteibute. Ktlint is a great way to enforce these rules very easily.

Just my two cents :)

**Comment by sksamuel** [comment]
You mean four cents :)

**Comment by mirageoasis** [comment]
@LeoColman 
can I ask why this issue has been closed?
while looking around code I found some code does not follow kotlin code convetion
example) [link](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas)

if we add ktlint config on this project it would be more helpful to follow conventions of kotlin
