### ISSUE TITLE
New date matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#828]
We should make sure we have matchers for all the parts of a date.

Like 

`date.shouldHaveMinute(1)`
`date.shouldHaveDayOfWeek(3)` and so on

**Comment by wevnasc** [comment]
I will work on that. 👍

**Comment by sksamuel** [comment]
Hi,. Are you still working on this ?

**Comment by wevnasc** [comment]
yes, but lack a little work to finish.

**Comment by Inego** [comment]
There's a PR merged in July, but the issue is still not closed.

**Comment by LeoColman** [comment]
That's true. Time to close this

Thanks, @Inego !
