### ISSUE TITLE
Launching coroutine in test lambda does not attach to the correct scope

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#830]
Seems like its not handled so the test doesn't complete properly.

**Comment by LeoColman** [comment]
This seem critical.

I think the reason is tge same as before failing. I'll look into it.

We should release a fix ASAP

**Comment by sksamuel** [comment]
Agreed.
I've commented on your other fix, so once that's addressed and this, lets
release 3.3.3

**Comment by sksamuel** [comment]
Ok so this only happens if you're using the intellij kotlintest plugin.
If you're using the junit one it's fine.

**Comment by sksamuel** [comment]
Seems to fail for


```
test("foo") {
  launch {
    error("boom")
  }
}
```

The test should pick up failures in the nested coroutine.

**Comment by sksamuel** [comment]
This is a wider bug in that any launched coroutines don't attach to the scope of the text executor. Fixed now in master.
