### ISSUE TITLE
Add print statement for config

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#841]
To make it clear project config was discovered

**Comment by faogustavo** [comment]
The configs you say is the `TestCaseConfig` or the `AbstractProjectConfig`?

**Comment by sksamuel** [comment]
ProjectConfig.

Something like:

"Config discovered.....<details>"

**Comment by faogustavo** [comment]
Can be something like this?

![image](https://user-images.githubusercontent.com/7588480/60400476-83a49f80-9b4a-11e9-8ce5-1ebc52eb8a4e.png)

**Comment by sksamuel** [comment]
Looks awesome.
I would make the true or false or single value ones on the same line though
to avoid taking up too much space.
