### ISSUE TITLE
Configurable location of .kotlintest dir

### ISSUE THREAD

**Issue by kdabir** [kotest/kotest#849]
From the source,  it looks like the [current location](https://github.com/kotlintest/kotlintest/blob/88afb914d145f1e1244c779358cd05ab1e040038/kotlintest-runner/kotlintest-runner-junit5/src/main/kotlin/io/kotlintest/runner/junit5/JUnitTestRunnerListener.kt#L112) is relative to CWD .

Ideally, `.kotlintest` dir should be created inside build directory so that it can get cleaned when we run the build tool's `clean` task. As this is junit runner which might not have context of Gradle/Maven build dirs, hence the path of `.kotlintest` dir should be made configurable.

**Comment by LeoColman** [comment]
Agreed!

**Comment by LeoColman** [comment]
I ran some tests on this, and it seems that resolving the build directory works every time. For now I didn't impleement configurability. Do you think this is very necessary?

**Comment by sksamuel** [comment]
By default it will write into the project root, not the build dir.

**Comment by sksamuel** [comment]
This is now configurable in 4.0.
