### ISSUE TITLE
new KTor matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#855]
response.shouldHaveCookie("name", "value")

**Comment by faogustavo** [comment]
We already have this. I think we can close this issue.

**Comment by LeoColman** [comment]
Good catch.
https://github.com/kotlintest/kotlintest/blob/6f1ea06cf61d72ff12d95b1aec8931110f7fe7be/kotlintest-assertions/kotlintest-assertions-ktor/src/main/kotlin/io/kotlintest/assertions/ktor/ResponseMatchers.kt#L47
