### ISSUE TITLE
Discovering Test failed in Android Project

### ISSUE THREAD

**Issue by sockeqwe** [kotest/kotest#856]
Hi,
I'm pretty sure I messed up something in my configuration of my android app but I couldn't find out yet what the problem could be.

If I start a `BehaviorSpec` from my (jvm) tests (not android instrumentation tests) I get the following error:

> org.junit.platform.launcher.core.DefaultLauncher handleThrowable
> WARNUNG: TestEngine with ID 'kotlintest' failed to discover tests
> java.lang.RuntimeException: Method isLoggable in android.util.Log not mocked. See http://g.co/androidstudio/not-mocked for details.
> 	at android.util.Log.isLoggable(Log.java)
> 	at org.slf4j.impl.AndroidLoggerAdapter.isLoggable(AndroidLoggerAdapter.java:543)
> 	at org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:537)
> 	at org.slf4j.impl.AndroidLoggerAdapter.debug(AndroidLoggerAdapter.java:195)
> 	at io.kotlintest.runner.junit5.KotlinTestEngine.discover(KotlinTestEngine.kt:45)
> 	at io.kotlintest.runner.junit5.KotlinTestEngine.discover(KotlinTestEngine.kt:25)
> 	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
> 	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
> 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
> 	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:52)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

I'm using the latest version of kotlin test and have also configured it as I did in other projects (android libraries) before and there it works seamlessly. My config looks like this:

```gradle
apply plugin: "de.mannodermaus.android-junit5"

android {
  ... 
  testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
}

dependencies {
    // (Required) Writing and executing Unit Tests on the JUnit Platform
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.4.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.4.2"

    // (Optional) If you need "Parameterized Tests"
    testImplementation "org.junit.jupiter:junit-jupiter-params:5.4.2"

    // (Optional) If you also have JUnit 4-based tests
    testImplementation "junit:junit:4.12"
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine:5.4.2"

    testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.3.2'
}
```

Any idea where I could start looking at or how to debug it?

**Comment by faogustavo** [comment]
change the library implementation from junit5 to junit4.

```   
testImplementation 'io.kotlintest:kotlintest-runner-junit4:3.3.2'
```

**Comment by sockeqwe** [comment]
Yea, it seems that this solves the prbolem, thanks. 
However, now I face another problem that the test is actually crashing somehow silently while setting up things but somehow makes the `BehaviorSpec` as not ran. I can actually attach a debugger to my BehabiorSpec and step throught it, but I havent fully figured out why and where it crashes. Any idea how to start?

**Comment by sksamuel** [comment]
Does it work with other specs, like FunSpec or WordSpec ?

**Comment by sockeqwe** [comment]
Update it seems that the tests are actually executed (all kind of tests like BehaviorSpec, Funpec, WordSpec ...)  but the result somehow doesn't get propagated properly. I.e. if a WordSpec has an assertion that fails, the whole test task in gradle still passes ... Have to look deeper into it but I guess it's not related to this project (kotlin-test) ...

Thanks for your help

**Comment by micHar** [comment]
I had the same problem and followed the advice to change to `kotlintest-runner-junit4`, but I also end up with unresolved tests `Tests passed: 0 of 1 test`.
Why should we change to junit4 anyway?

**Comment by sockeqwe** [comment]
Jfyi I wasnt able to solve this issue yet.

Michał Klimczak <notifications@github.com> schrieb am Di., 23. Juli 2019,
15:14:

**Comment by micHar** [comment]
Does anyone have a working configuration for android?

**Comment by henryqwe** [comment]
What's the current status of this issue? Using junit4 compiler along with `BehaviorSpec` it makes each brace as single test
