### ISSUE TITLE
beforeProject / afterProject in TestListener is confusing

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#859]
These methods won't be invoked in a test listener, so they should be in some kind of project listener.

**Comment by alladywek** [comment]
small example:

```
class A : StringSpec() {

    override fun listeners(): List<TestListener> = listOf(object : TestListener {
        override fun beforeProject() {
            println("before project")
        }

        override fun afterProject() {
            println("after project")
        }
    })

    init {
        "test1" {
            println("test")
        }
    }
}

// will print:
// test
```

**Comment by LeoColman** [comment]
I removed the bug label, I don't think this is a bug.

It's confusing tho xD

**Comment by LeoColman** [comment]
How to deprecate this without breaking client code?

Currently, any user is implementing project listeners using the TestListener.

**Comment by sksamuel** [comment]
Maybe just deprecate it from TestListener and then add a new
ProjectListener.

**Comment by sksamuel** [comment]
Added ProjectListener
