### ISSUE TITLE
Test time is being wrongly reported

### ISSUE THREAD

**Issue by leoxs22** [kotest/kotest#868]
Hello!

I was looking at the test times, and I find that the time reported at the right, using Intellij, is not the real time the test took

![image](https://user-images.githubusercontent.com/9098977/60457688-ff6a1f00-9c12-11e9-96c9-3d0b34bce5e2.png)

In this case, I did a repeat(100000) of something that reads a file, and it took about 10 minutes, but the time reported is only 17ms.

You can easily achieve the same result adding 

`delay(10000)`

in some test.

**Comment by sksamuel** [comment]
This is because the only way to make nested tests work with gradle is to
"start" them just before you "end" them.
So the times are all off.

If we do it the way JUnit5 framework says you should, gradle will complain.
So intellij suffers also.

**Comment by leoxs22** [comment]
And there isn't any way to override that value?

Maybe at least marking it with 0ms, to make it obvious that it's not a real measurement.

I'll see if I can find something to fix that. Let me know if you have any clue about where is Junit reporting this value.

**Comment by sksamuel** [comment]
I think intellij calculates it itself.
The solution is to not use junit anymore, which is coming in the future.

**Comment by leoxs22** [comment]
Sorry, I didn't understand. It's correctly reported in the console doing an mvn test, it just shows the wrong value in Intellij, not so bad, then.

Thanks!

(Can be closed as won't fix, I think)
