### ISSUE TITLE
shouldHaveLength should show the length on failure

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#869]
Currently it will say

java.lang.AssertionError: qwerty should have length 32

**Comment by faogustavo** [comment]
Can you describe a little bit more, please? With the description you provided, it seems that the issue is already OK.

**Comment by sksamuel** [comment]
It doesn't show the length of the string that was incorrect.

**Comment by faogustavo** [comment]
Like this: `java.lang.AssertionError: hello should have length 32, but instead was 5`?

**Comment by sksamuel** [comment]
Yep.
