### ISSUE TITLE
Add documentation for JSON matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#872]
We have nice json matchers in the json module so instead of doing:

`myAvroSchema shouldBe """{"type":"record","name":"Foo","namespace":"com.sksamuel.avro4k.schema"}"""`

We can do

`myAvroSchema.shouldMatchJson("""{"type":"record","name":"Foo","namespace":"com.sksamuel.avro4k.schema"}""")`

Which will allow the json to be formatted differently, as long as the contents are the same.

We should document this as we don't mention it anywhere!

**Comment by jesuswasrasta** [comment]
Hello! I'm a KotlinTest newcomer, and I'd like to contribute as an excuse to learn it better 😊
Where's the correct place where to document this, the [matchers.md](https://github.com/kotlintest/kotlintest/blob/master/doc/matchers.md) maybe?

**Comment by sksamuel** [comment]
Yeah you could add to that page or add another new page and link to it.
