### ISSUE TITLE
"Run Context Configuration" command in AS runs whole test class instead of single test

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#883]
I have this simple class with two tests:

```kotlin
class StringSpecExample : StringSpec({
    "maximum of two numbers" {
        forall(
            row(1, 5, 5),
            row(1, 0, 1),
            row(0, 0, 0)
        ) { a, b, max ->
            max(a, b) shouldBe max
        }
    }

    "maximum of two numbers2 " {
        forall(
            row(1, 5, 5),
            row(1, 0, 1),
            row(0, 0, 0)
        ) { a, b, max ->
            max(a, b) shouldBe max
        }
    }
})
```

Now in normal JUnit4 tests, when I have cursor placed inside a test method and press shortcut for `Run Context Configuration`, only that one test runs. If I the cursor is within the class but not the test, all tests in class run.

With KotlinTest, regardless of cursor position, all tests in the class are executed. Here's what searching for `Run context configuration` shows in JUnit tests:

![image](https://user-images.githubusercontent.com/3951580/60960977-68d0e880-a30b-11e9-974e-fd2075a2a260.png)

And here's the result for KotlinTest:

![image](https://user-images.githubusercontent.com/3951580/60961018-7f773f80-a30b-11e9-8014-6806c572ccbf.png)

I believe the correct behavior would be similar to that in JUnit tests, where cursor placement influences context configuration

**Comment by LeoColman** [comment]
I moved this to the plugin repository, as I think this is more related to there.

To run single tests you must use KT's plugin, as Junit doesn't have this integration for platforms other than junit itself.

If you believe this is actually related to this repository, let me know and I can reopen
