### ISSUE TITLE
Add support to Spring Boot's TestExecutionListener

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#886]
Spring Boot defines an API for test execution listener. It seems to be similar to ours, but KT is not working with them at the current state.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/TestExecutionListener.html

An example of this feature can be found at @Sql, at this guide:
https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testcontext-executing-sql-programmatically

**Comment by sksamuel** [comment]
I don't understand what they do. Are we supposed to add a KotlinTestExecutionListener, or is KT meant to invoke the current TestExecutionListeners?

**Comment by LeoColman** [comment]
I think the latter.

It seems that one can register some listeners to Spring, and it will do something to execute them. As stated in that link, 

>Note that not all testing frameworks support all lifecycle callbacks defined in this API.

We should be one of the frameworks that does.

I'm figuring out how they're executed now.

We would just need to add their behavior to our SpringListener

**Comment by tibtof** [comment]
Do you need help with this? I also need this feature and I would happily contribute.

**Comment by sksamuel** [comment]
@tibtof I think this is just about done, but there's plenty of other issues if you'd like to contribute again :)

**Comment by LeoColman** [comment]
Once we merge this, it would be awesome if  you could validate it in your usage. As I said, I couldnt validate many scenarios

**Comment by LeoColman** [comment]
If you can test with master snapshot it would be great, @tibtof

**Comment by tibtof** [comment]
@Kerooker I'll do my best to test this in the following week. I'll let you know of my findings.
