### ISSUE TITLE
Lack of LocalTime assertions

### ISSUE THREAD

**Issue by alladywek** [kotest/kotest#889]
I faced with problem that kotlintest doesn't have assertions for LocalTime class

**Comment by LeoColman** [comment]
What kind of assertions do you suggest for LocalTime?

Em seg, 15 de jul de 2019 08:14, Abbas Abbasov <notifications@github.com>
escreveu:

**Comment by alladywek** [comment]
```
LocalTime.shouldBeAfter(LocalTime)
LocalTime.shouldBeAfter(LocalTime)
LocalTime.shouldBeAfter(LocalTime)
LocalTime.shouldBeAfter(LocalTime)
```

**Comment by alladywek** [comment]
```
LocalTime.shouldBeAfter(LocalTime)
LocalTime.shouldBeBefore(LocalTime)
LocalTime.shouldBeBetween(LocalTime)
LocalTime.shouldHaveSameSecondsAs(LocalTime)
LocalTime.shouldHaveSameHoursAs(LocalTime)
LocalTime.shouldHaveSameMinutesAs(LocalTime)
LocalTime.shouldHaveSameNanosAs(LocalTime)
```
and their versions with `Not`, they are the similar as from `io.kotlintest.matchers.date`

**Comment by LeoColman** [comment]
Great matchers!

Do you want to do it? We are open to prs!

If you are not, no worries, we can take it from here

Em seg, 15 de jul de 2019 10:10, Abbas Abbasov <notifications@github.com>
escreveu:

**Comment by alladywek** [comment]
I can do it

**Comment by sksamuel** [comment]
We could add this to 3.4 if it's ready in the next couple of days !

**Comment by alladywek** [comment]
> We could add this to 3.4 if it's ready in the next couple of days !

I think I will do it today/tomorrow

**Comment by sksamuel** [comment]
When you do this @alladywek can you add them in a seperate file `localtime.kt` inside the date folder. Thanks.

**Comment by alladywek** [comment]
> When you do this @alladywek can you add them in a seperate file `localtime.kt` inside the date folder. Thanks.

yeah, I saw your message after PR =) I will change it.
