### ISSUE TITLE
io.kotlintest.Result conflicts with kotlin.Result

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#898]
Kotlin's `kotlin.Result` class is being resolved without an import. So for example copy-pasting sample custom matcher fails, because IDE doesn't prompt for import, and implictly uses Kotlin's Result.

Since the library is dedicated for Kotlin language, perhaps it'd make sense to rename `io.kotlintest.Result` to e.g. `TestResult` or `AssertionResult` to avoid the clash. It's not a big problem right now, but as inline classes graduate from experimental, I expect more usages of `kotlin.Result`, and the issue might become annoying

**Comment by sksamuel** [comment]
This is a good point.

It's a breaking change for anyone who uses custom matchers though. Perhaps we do it and bump to version 4.0.

Or maybe we do it in 3.4 (releasing in the next few days) and deprecate Result buying us some time.

**Comment by lwasyl** [comment]
+1 for introducing an alias and deprecating the current Result right away.

With that perhaps there are other changes to Result that were suggested at some point? One pain point (to me) is having to specify both `failure` and `negated failure` messages. ~Also the messages are evaluated eagerly, which is less flexible than providing them in functions for example.~ (edit: they're not 🤦‍♂️)

**Comment by sksamuel** [comment]
Please, feed back as much as you can so I can make all the improvements at
once for the 3.4 release.

**Comment by sksamuel** [comment]
Ok so in 3.4 Result is now MatcherResult, and it explicitly allows functions to keep them lazy.

**Comment by fsonntag** [comment]
I realized that `io.kotlintest.Result` is now replaced with `MatcherResult`
It would be great to update the docs, as it is explicitly used there for writing custom matchers

**Comment by sksamuel** [comment]
Yes good spot.
