### ISSUE TITLE
Our collection matchers don't work on arrays

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#900]

**Comment by LeoColman** [comment]
Should we just go ahead and create an overload for arrays as well?

**Comment by sksamuel** [comment]
Yes.

**Comment by LeoColman** [comment]
Can't the user just go `arr.toList()` tho?

**Comment by sksamuel** [comment]
Costly operation and you could say why bother with loads of our convenience
matchers if that's the case.

**Comment by LeoColman** [comment]
I see.
I'll just create overloads that call toList then

**Comment by sksamuel** [comment]
asList might be better

**Comment by LeoColman** [comment]
You're right
