### ISSUE TITLE
New collection matcher

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#901]
collection.shouldExist { t -> } 

If the lambda returns true for at least one element then the test passes.

Is a more convenient version of

collection.any { t -> } shouldNotBe null

**Comment by alladywek** [comment]
Good feature
What about this version of name:
`collection.shouldHaveElement { e -> ... }`
`collection.shouldNotHaveElement { e -> ... }` or something like this.

I mean that `collection should exist` sounds a little confused, what do you think ?

**Comment by LeoColman** [comment]
We literally already have this matcher xD

```
infix fun <T> Collection<T>.shouldExist(p: (T) -> Boolean) = this should exist(p)
```

and the implementation is exactly as you described
```
      value.any { p(it) },

```

This at least shows that the matcher is a good idea hahah

We can discuss if we want the alternative name @alladywek suggested

**Comment by sksamuel** [comment]
We could add an alias or rename to shouldHaveOneElement { t -> }, shouldHaveAtLeastOneElement { t -> }, kind of like the inspectors.
