### ISSUE TITLE
Allow nested `describe` blocks in DescribeSpec

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#902]
In RSpec it's allowed to nest `describe` blocks. It's be nice to be able to nest `describe` blocks in DescribeSpec as well, but right now it's not possible. Is there any technical limitation to this or it's a deliberate decision?

I wanted to add a `describe` alias on `DescribeScope`, but the library `describe` is resolvable anyway and the tests fail in runtime

**Comment by LeoColman** [comment]
This is a deliberate decision, however I don't see any reason to not allow this.

Currently you can use 

describe -> context -> context -> ... -> it

No real issue to disallow
describe -> describe -> ...

I'll add this.
