### ISSUE TITLE
Tagging tests as success when all child failed

### ISSUE THREAD

**Issue by leoxs22** [kotest/kotest#903]
When a child fails, it doesn't tag it's parent as a failure

![image](https://user-images.githubusercontent.com/9098977/61543396-c0f9a000-aa19-11e9-9329-3ef2b5924430.png)

I think this may be related to the last release 3.3.3, I don't think it happened before

**Comment by LeoColman** [comment]
This is actually intended as per junit specification. I'm not a big fan of this either, but we can revert it @sksamuel

**Comment by LeoColman** [comment]
This was last discussed in #807 , which seems to have introduced this behavior

**Comment by sksamuel** [comment]
I'm not a fan of it either, but that's the JUnit spec.
What does junit itself do if you have nested tests ?

**Comment by LeoColman** [comment]
JUnit doesn't have nested tests
It's the API that allows nested tests, and it says that we should do it this way, so I have no idea

**Comment by LeoColman** [comment]
We used to work ok when disrespecting this specification.
Have we had any bugs in this? Or did we chose to follow the contract just because?

**Comment by sksamuel** [comment]
Junit has inner tests

**Comment by LeoColman** [comment]
Hmm.. I've never seen it then

**Comment by LeoColman** [comment]
I'm only used to @Test

**Comment by sksamuel** [comment]
We can just ignore the junit spec. I don't suppose it matters.

**Comment by sksamuel** [comment]
Please try 3.4.1 @leoxs22
