### ISSUE TITLE
Add support for Micronaut

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#911]
Inspired in [this stackoverflow question](https://stackoverflow.com/questions/56754723/how-to-use-micronauttest-with-kotlintest-to-inject-beans-while-testing-in-kotl), 

I think we should support micronaut. It's getting bigger every day, and we have support for Spring. Shouldn't be too hard to use Micronaut in the same way.

**Comment by LeoColman** [comment]
And it actually already support us lol
https://github.com/micronaut-projects/micronaut-test/tree/master/test-kotlintest

**Comment by sksamuel** [comment]
That's cool !

Lets link in our docs.

A new page on di frameworks?

**Comment by LeoColman** [comment]
Micronaut is not exactly a DI framework, it's a general purpose web app framework, just like spring

**Comment by LeoColman** [comment]
But yes, we should link it somewhere

**Comment by sksamuel** [comment]
This is done right ?

**Comment by LeoColman** [comment]
yep
