### ISSUE TITLE
New feature: add string generator from regexp

### ISSUE THREAD

**Issue by Jiehong** [kotest/kotest#912]
Hello,

It would be very convenient if a generator was present that would provide strings from a regular expression, something like `Gen.string(regexp: String)` for example, or from `Gen.string(regexp: Regex)`.

Currently, we have to define our own generator based on something like https://www.baeldung.com/kotlin-random-alphanumeric-string.

**Comment by LeoColman** [comment]
Good suggestion!

We should probably take in a regex instead of a string tho

**Comment by sksamuel** [comment]
How would you implement this ?
Generate random strings until they match ?
Or parse the regex yourself to try and generate strings that match it? Seems like both approaches would be problematic.

**Comment by LeoColman** [comment]
I think there are ways to do this
https://stackoverflow.com/questions/22115/using-regex-to-generate-strings-rather-than-match-them

**Comment by sksamuel** [comment]
Ok, this looks good:
https://github.com/mifmif/Generex

**Comment by BurstX** [comment]
BTW, Microsoft created a CLI tool to generate strings that match one or more regexes https://www.microsoft.com/en-us/download/details.aspx?id=52296
