### ISSUE TITLE
shouldBe doesn't support ByteArray

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#913]
It might not support other primitive array types either.

**Comment by LeoColman** [comment]
Ok, so here's the thing:

`shouldBe` works correctly, but `shouldNotBe` doesn't.
They're not exact opposites

**Comment by LeoColman** [comment]
I'm working on a fix

**Comment by sksamuel** [comment]
It was shouldBe that I was using.

**Comment by LeoColman** [comment]
Hmm.. I just tested shouldBe, it is comparing ByteArray correctly

**Comment by sksamuel** [comment]
Ok we can close this until I can find another failing case.

**Comment by LeoColman** [comment]
There aresomething to fix in these guys tho

**Comment by LeoColman** [comment]
Their string representation doesn't have all cases, and shouldNotBe doesn't work for these primitives arrays either

**Comment by sksamuel** [comment]
Ok cool.
