### ISSUE TITLE
Constant Random Listener

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#919]
Sometimes we have code that depends on a random number generator. These tests can be non-determininstic, as they might instantiate a new random object or get numbers from the Kotlin's Random Object.

What if we were able to test these randomized data with a listener for that?

**Comment by sksamuel** [comment]
Need a way of creating a random source with a particular seed, then the
numbers will be consistent, rather than changing the nextInt, methods, etc.

**Comment by LeoColman** [comment]
Yes

**Comment by sksamuel** [comment]
So is there anything for us to do here, as anyone using Random can just do Random(123) to create a random with the seed.

**Comment by LeoColman** [comment]
And then pass that random into the class constructor, as to be injected (as it should be, I suppose)? Perhaps that works

**Comment by sksamuel** [comment]
We've got random in the Gens as per my PR. Other than that you can just make a Random in your own code. So there's nothing left to do here right ?

**Comment by sksamuel** [comment]
This is a duplicate of #815
