### ISSUE TITLE
Add infix modifier to arrow matchers

### ISSUE THREAD

**Issue by Jiehong** [kotest/kotest#921]
Hello,

It would be nice to be able to use arrow matchers just like the rest of matchers in kotlintests. For example:

```kotlin
val x = Either.left("value")
x shouldBeLeft "expected"
```

instead of:

```kotlin
val x = Either.left("value")
x.shouldBeLeft("expected")
```

But this isn't possible due to the missing `infix` modifier on Arrow matchers.

**Comment by LeoColman** [comment]
Agreed!
Do you want to do it?

**Comment by faogustavo** [comment]
@sksamuel I think we can close this one now.
