### ISSUE TITLE
Missing spring dependencies: build still succeeds

### ISSUE THREAD

**Issue by mindhaq** [kotest/kotest#925]
When I have a spring test, where one of the dependencies of the service under test cannot be resolved, the test is not failing. A stacktrace is being printed, but the build, in the end, still says "build successful".

This can be worked around when using a previous version of `maven-surefire-plugin`, before 2.22.0.

I created a small example project where this can be seen.

https://github.com/mindhaq/kotlintest-demo

Initial commit is in a state where the build with `./mvnw test` fails, as expected.

When the version of `maven-surefire-plugin` is changed in the pom.xml to a newer version (current spring boot parent defines 2.22.2), the build is not failing.

In a real-world project it even seems like no other tests after the failing one are started at all.

**Comment by mindhaq** [comment]
To clarify, I tested if this happens with a JUnit test as well, but this only happens with a kotlintest test.

**Comment by LeoColman** [comment]
I'm not very good with maven. Any ideas, @sksamuel ?

**Comment by mindhaq** [comment]
Using kotlintest 3.3.3, the test fails with an error as expected.

Being that the most recent version when I filed the bug, I feel a bit silly now.

**Comment by LeoColman** [comment]
Happens with all of us every now and then.

Thanks for the report!
