### ISSUE TITLE
Duplicate class org.junit.platform.commons.annotation.Testable found in modules junit-platform-commons-1.4.0.jar (org.junit.platform:junit-platform-commons:1.4.0) and kotlintest-core-3.3.0.jar (io.kotlintest:kotlintest-core:3.3.0)

### ISSUE THREAD

**Issue by cepages** [kotest/kotest#927]
Hi I'm new in Android and I'm trying to run some test.

But when I try to use kotlintest I get the following error:

```
Duplicate class org.junit.platform.commons.annotation.Testable found in modules junit-platform-commons-1.4.0.jar (org.junit.platform:junit-platform-commons:1.4.0) and kotlintest-core-3.3.0.jar (io.kotlintest:kotlintest-core:3.3.0)
```

This is my dependencies in gradle:

```
def grpcVersion = '1.22.1' // CURRENT_GRPC_VERSION
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:preference-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'org.nield:kotlin-statistics:1.1.3'
    implementation 'org.tensorflow:tensorflow-android:+'
    implementation 'com.android.support:multidex:1.0.3'

    implementation "org.jetbrains.anko:anko-commons:0.10.8"

    compileOnly "javax.annotation:jsr250-api:1.0"//This fixes the problem with Generated symbols

    // You need to build grpc-java to obtain these libraries below.
    implementation "io.grpc:grpc-okhttp:${grpcVersion}" // CURRENT_GRPC_VERSION
    implementation "io.grpc:grpc-protobuf-lite:${grpcVersion}" // CURRENT_GRPC_VERSION
    implementation "io.grpc:grpc-stub:${grpcVersion}" // CURRENT_GRPC_VERSION
    implementation 'com.google.code.gson:gson:2.8.5'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    //Testing framework
    androidTestImplementation 'io.kotlintest:kotlintest-runner-junit5:3.3.0'

    //Mocking framework
    androidTestImplementation "io.mockk:mockk:1.9.3"
}
```

Thanks

**Comment by LeoColman** [comment]
This seems to be a problem in which 2 libraries are loading the same dependency.
Espresso is probably also bringing junit in, and their versions must be mismatching.

If you comment out espresso, does it work again? If it does, you'll have to exclude JUnit from one of the dependencies through an `exclude` block

**Comment by cepages** [comment]
Removing Espresso didn't work. But I think I found where the dependency is. This is part of what I get when I run the dependency tree in gradle:

```
....

debugAndroidTestCompileClasspath - Compile classpath for compilation 'debugAndroidTest' (target  (androidJvm)).
+--- android.arch.core:core-testing:1.1.1
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.mockito:mockito-core:2.7.6
|    +--- android.arch.core:runtime:1.1.1
|    |    +--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    \--- android.arch.core:common:1.1.1
|    |         \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
+--- io.kotlintest:kotlintest-runner-junit5:3.3.0

....
```

I think `android.arch.core:core-testing:1.1.1` is importing `jUnit` too. 

I tried to exclude it with:

```
    androidTestImplementation 'android.arch.core:core-testing:1.1.1' {
        exclude module: "jUnit"
    }
```

But it seems doesn't work. I'm doing something wrong with `gradle` or I'm following the wrong clue

**Comment by LeoColman** [comment]
Sometimes gradle just doesn't collaborate with Android.
Sometmes clearing the whoe gradle cache helps in these kinds of issues, specially with android

**Comment by LeoColman** [comment]
Could you try that and report back?

**Comment by cepages** [comment]
Yeah, how can I clear the gradle cache? If it's doing `gradlew clean` I tried that and it didn't work

**Comment by LeoColman** [comment]
I usually first try `invalidate and restar`, if that doesn't work I delete project's .gradle. If that doesn't work,I delete the global gradle's cache. 

One of these usually does that trick for android and me

**Comment by cepages** [comment]
Sorry when you mean `invalidate` what do you mean:

`./gradlew invalidate` ?

I assume when you mean restart. you mean restart Android Studio. isn't it?

What you mean with delete project's gradle, you mean removing the `build` directory?

Sorry, I don't have a wide experience with gradle.

**Comment by LeoColman** [comment]
I meant invalidate and restar, and action from android studio.

The project's gradle: there is a folder with all dependencies called `.gradle` in your project (perhaps the default view doesn't show it).

There's also the `.m2` folder in your (usually, for linux) `/home`, which also keeps dependencies.

You can also try reimporting the project, if it's in a `Github` or `Bitbucket` of some sort

**Comment by LeoColman** [comment]
The thing is that gradle sometimes screws us up A LOT. I myself have troubles with it everytime I change something in my `build.gradle`.

**Comment by LeoColman** [comment]
You said that Android is bringing JUnit with it. Perhaps your exclude statement is wrong?

If you want, take a look at [this project](https://github.com/Kerooker/rpg-npc-generator) I'm developing Android + KotlinTest with it, and everything is working flawlessly so far

**Comment by LeoColman** [comment]
I'm now getting to the bottom of this issue.

It seems that we're actually defining that class inside KotlinTest, and that is causing these compatibility issues with Espresso, because it brings JUnit platform dependencies to the classpath. 

I'll mark this as a bug and investigate further

**Comment by LeoColman** [comment]
Please try with the snapshot build that was just generated

**Comment by lwasyl** [comment]
Fyi until 3.5 is available the snapshot with fix for this is `3.5.0.2421-SNAPSHOT`

**Comment by cepages** [comment]
@Kerooker sorry for my delay replaying. 

I took other solution for this, but I'm happy to give it a go.

I tried, but I guess I don't know how to use the `3.5.0.2421-SNAPSHOT`

I tried replacing the current `kotlintest` dependency for:
```
    //Testing framework
    androidTestImplementation 'io.kotlintest:kotlintest-runner-junit5:3.5.0.2421-SNAPSHOT'
    testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.5.0.2421-SNAPSHOT'
```

I guess this is not the way to do it because I get:

`ERROR: Failed to resolve: io.kotlintest:kotlintest-runner-junit5:3.5.0.2421-SNAPSHOT`

Thanks

**Comment by sksamuel** [comment]
3.4.1 has this fix.
