### ISSUE TITLE
empty matcher against Map

### ISSUE THREAD

**Issue by temp-impl** [kotest/kotest#928]
Hi, is there `Map<K, V>.shouldBeEmpty()`?

If not, please add.

**Comment by sksamuel** [comment]
Probably quicker to add the feature than open an issue :)

**Comment by faogustavo** [comment]
We don't have matchers for Map. Maybe we should think to add others too.

**Comment by LeoColman** [comment]
We do have matchers for maps tho https://github.com/kotlintest/kotlintest/blob/master/doc/matchers.md

But we're always open to new matchers!
