### ISSUE TITLE
forAll displays all errors at once, even when they are too many

### ISSUE THREAD

**Issue by Jiehong** [kotest/kotest#929]
Hello,

Today, using `forAll` can be a bit annoying, as it displays all failing cases at once.

Example

```kotlin
forAll(Gen.string().take(1000)) {
    it shouldBe "lovely"
}
```

You'll get the following output:

```
java.lang.AssertionError: 0 elements passed but expected 1000

The following elements passed:
--none--

The following elements failed:
<empty string> => expected: "lovely" but was: ""
(900 more lines)
```

When this happens, the output should only provide a few failing examples, and not all the 1000 examples (would be worse if more were requested).

It's sort of like "shrinking" the possible values for which it doesn't work, and it would make it a bit more user-friendly.

**Comment by sksamuel** [comment]
Fixed in master.

`-Dkotlintest.assertions.output.max=20` now supported
