### ISSUE TITLE
Inspectors are bugged when the message is very big

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#938]
When using inspectors in a big collection that have a lot of failing cases, the tests will stay green and won't fail.

```
class Foo : FunSpec() {

    init {
        test("safd") {
            List(100_000) { it }.forAll {
                it shouldBe -1
            }
        }
    }
}
```

The above test results in 100_000 failing lines, and it will pass.

If we change the condition to a much smaller case, such as 
```
test("safd") {
            List(100_000) { it }.forAll {
                it shouldBeLessThan 99000
            }
        }
```

The test will fail as intended, and the message will be displayed.

I checked that the inspector get to the point of throwing the exception, but nothing seems to happen.

If I `try catch` the test and `printStacktrace`, it prints a big message, but the test won't fail.

My initial guess is that the JVM is failing to throw exceptions with gigantic messages, but I didn't dig a lot into it yet.

This might be related to #930 as it shortens exception messages.

**Comment by sksamuel** [comment]
This is fixed in 4.0. Added test to check.
