### ISSUE TITLE
Deprecate non extension versions of inspectors

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#941]

**Comment by LeoColman** [comment]
What if people want to merge matchers? Should that be disallowed?

**Comment by sksamuel** [comment]
Oops I meant to say inspectors not matchers !!!!!

**Comment by sksamuel** [comment]
I don't think there's any point in polluting the namespace with `forSome(col) { }` when you can do `col.forSome { }`

**Comment by LeoColman** [comment]
Ah, inspectors. Make sense
