### ISSUE TITLE
New matcher: should be truthy

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#943]

**Comment by LeoColman** [comment]
Do we have truthy types in Kotlin?
We can't evaluate arbitrary expressions as boolean

**Comment by sksamuel** [comment]
At work we have "yes" "no" "1" "0" as boolean values in a database.
I thought it might be handy to support `"yes".shouldBeTruthy()`

**Comment by LeoColman** [comment]
I see.

I'm just not sure where we should stop on this.

"true" and "false" seems correct as well.

**Comment by gustavo-valvassori-codeminer42** [comment]
Are there any more conditions than theses below? (Always ignoring case)

| Condition | Acceptable values |
| --- | --- |
| shouldBeTruthy | `Yes`, `y`, `1`, `true` |
| shouldBeFalsy | `No`, `n`, `0`, `false` |

**Comment by sksamuel** [comment]
I think that's acceptable.

**Comment by LeoColman** [comment]
Make sure that it's case insensitive, so `YES` == `yes` == `Yes`

**Comment by LeoColman** [comment]
But I'm afraid of somethings...

In JS, a date is truthy, for example. "37" is truthy

While `NaN` is falsy, `""` is falsy

How should we deal with these?

**Comment by sksamuel** [comment]
We don't have to do what JS does.

**Comment by sksamuel** [comment]
@gustavo-valvassori-codeminer42 the cases you listed are good.
