### ISSUE TITLE
Gen.file(dir)

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#947]
A generator that provides random files from a directory

fun Gen.Companion.file(dir) : Gen<File> ...
fun Gen.Companion.file(dir, recursive: Boolean) : Gen<File> ...

**Comment by ashishkujoy** [comment]
@sksamuel  As of now all gens are in commonMain, where we don't have access to java modules.
Which means this implementation will need to be in jvmMain. But that would look odd.

**Comment by sksamuel** [comment]
Not all gens are in common. Quite a few JVM specific ones are in jvmMain
