### ISSUE TITLE
New Name For Project

### ISSUE THREAD

**Issue by napperley** [kotest/kotest#948]
The project name **Kotlin Test** for many Kotliners is mistaken for **kotlin.test**, which is a Kotlin testing library developed by JetBrains. As a result when a person does a Google search for **kotlin test** the **kotlin.test** link appears first, with the link to **Kotlin Test** appearing in second position, which is causing issues (eg fewer people know about the project which hinders the project's uptake). Even though the names of both projects (kotlin.test and Kotlin Test) aren't the same they are close enough to cause confusion for many people.

I propose renaming the project to use a distinctive name that meets the following criteria:

1. Easy to spell
2. Can be pronounced easily
3. Name appears at the top (*preferred*) or near the top in a web search
4. No other testing library uses the name or has a name that is similar

**Comment by napperley** [comment]
One suggestion for a new project name is **Konfirm**. In a sentence (aka marketing slogan), "When a Kotliner wants to check if the software they develop works they **Konfirm** it".

**Comment by LeoColman** [comment]
There are many issues with this possibility.

One that I can think of right now is package naming. Changing the framework name may lead to many clients code breaking when they try to update, as `io.kotlintest` won't exist anymore.

Another one that I can think right now is that although the name may be similar, [Kotlin Census 2018](https://www.jetbrains.com/research/kotlin-census-2018/#libraries) stablished that around 11% of Kotlin users use KotlinTest already, and that number probably increased in 2019. Changing the project's name will render these users unable to find KotlinTest as easily as it happens today

**Comment by sksamuel** [comment]
I think the package name issue isn't as problematic as it could be, as we're now working towards a 4.0 release and given that we're going to be changing things for MPP support, it could all be part of that upgrade cycle.

**Comment by sksamuel** [comment]
By the way, we can add typealiases for all the old classes to the new ones if we change the package names.

**Comment by sksamuel** [comment]
Some other suggestions along with Konfirm.

Scrutiny
KUnit
PowerTest
Inspect (or Inspeckt)
Kola
Kappa
Kayak
Kabab
Kanvas
Kaiser

**Comment by sksamuel** [comment]
What about "Jenner". 
![46695166](https://user-images.githubusercontent.com/743706/63644168-28091500-c6a8-11e9-87e8-c612c5ade4a6.jpeg)
A doctor from the 18th century.

**Comment by sksamuel** [comment]
Another option: Buggy.

**Comment by LeoColman** [comment]
Kover / TestKover / Koverer / Koverage / ~something related to Cover but K instead of C~

**Comment by sksamuel** [comment]
I quite like KUnit, Buggy, Kaiser or Konfirm.

**Comment by LeoColman** [comment]
I like Konfirm and KUnit.
Kaiser is not related to testing/kotlin
Buggy doesn't seem to be something for Kotlin, but I like it too

**Comment by sksamuel** [comment]
Buggy is just a play on the fact that testing libraries help find bugs.

**Comment by sksamuel** [comment]
Jasmine isn't related to testing, neither is Karma or Mocha.

**Comment by sksamuel** [comment]
Shall we keep it simple - kunit ?
@napperley @Kerooker

**Comment by LeoColman** [comment]
Well, KUnit is a thing already, although completely unrelated
https://google.github.io/kunit-docs/third_party/kernel/docs/

**Comment by LeoColman** [comment]
Searching for "Testing X with KUnit" could provide two very different results, so I vote against it

**Comment by sksamuel** [comment]
Yes ok agreed.

KCheck ?

**Comment by LeoColman** [comment]
KCheck is fine

The only think I found when searching for it was [this empty GH repository](https://github.com/fmoctezuma/kcheck) and some other small non-related stuff.

People will pronounce it KaCheck in portuguese tho

**Comment by sksamuel** [comment]
It's a bit uninspiring.

**Comment by mindhaq** [comment]
As an end-user, I like Kaiser and Konfirm.
As a hobby-cook, I like Koriander :)

I agree on KCheck not being very inspiring.

**Comment by dave08** [comment]
Why not just KTest, that way you don't steer too far away from the current name. It's  easier to connect that to the old name, for those that were used to it, and all the review sites that referred to it. It doesn't feel like a new project, but the same one everybody likes currently :)

**Comment by sksamuel** [comment]
There's a lot of merit to what dave just said.

**Comment by sksamuel** [comment]
The best we came up with (completely new) are Contest and Canyon and TickTack.

**Comment by sksamuel** [comment]
I think we've settled on Kotest.
As @dave08 suggested, it's good to have something similar to what we already have, and ktest already exists as several projects.
