### ISSUE TITLE
Move `kotlintest-assertions` tests to its module

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#949]
As the assertion module grows, having tests for it all over the place is making it difficult for new contributors to find where to place those tests.

As we don't depend on KotlinTest itself to run them (as we do with Core and Runners), we can easily move these tests closer to the source code they test

**Comment by sksamuel** [comment]
We do use kotlintest to test them right? I guess as all the compiling is done first, the runner would be available to use in the test stage.

**Comment by LeoColman** [comment]
That's what I  meant, yes

I remember we had this discussion earlier, and you said that the only test that actually required being in a different module was the runners/core

The Assertions can be in the same module and they'll run fine.

When we finish migration to MPP, I can move the tests over there

**Comment by sksamuel** [comment]
Assertions are done for now so you could migrate over.
