### ISSUE TITLE
Scoped `beforeEachTest` closure

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#952]
Some BDD-style frameworks allow for defining a closure that will be called just before each test. In KotlinTest there is `fun beforeTest(testCase: TestCase)` that we can override, but it's global for all test cases in spec, and not scoped. This means we can't access data defined in the context for example.

Such scoped beforeEachTest concept is available e.g. in [Ginkgo as `JustBeforeEach`](http://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach). In KotlinTest the closest I came to achieving this behavior is with following code:

```kotlin
abstract class BaseTest(block: BaseTest.() -> Unit) : DescribeSpec() {
    private val testActions = mutableListOf<() -> Unit>()

    init {
        block()
    }

    override fun beforeTest(testCase: TestCase) {
        if (testCase.type == TestType.Test) testActions.forEach { it() }
    }

    fun beforeEachTest(block: () -> Unit) {
        testActions += block
    }
  
    override fun isolationMode(): IsolationMode = IsolationMode.InstancePerLeaf
}

class ExampleTest : BaseTest({
    describe("Some class") {
        var state: Int? = null
        lateinit var stateResult: String

        beforeEachTest {
            stateResult = checkNotNull(state).toString()
        }

        context("given context state is 4") {
            state = 4

            it("should result in `4`") {
                stateResult shouldBe "4"
            }

            describe("some other state") {
                lateinit var otherState: String
                lateinit var otherStateResult: String

                beforeEachTest {
                    otherStateResult = otherState + stateResult
                }

                context("given other state is `a`") {
                    otherState = "a"

                    it("should result in `a4`") {
                        otherStateResult shouldBe "a4"
                    }
                }

                context("given other state is `b`") {
                    otherState = "b"

                    it("should result in `b4`") {
                        otherStateResult shouldBe "b4"
                    }
                }
            }
        }
    }
})
```

Key highlights: each `context` block only sets context state, and assertions verify something derived from it. `beforeEachTest` closure captures translation from the context to the tested state. Such tests are more readable, especially with certain patterns like reactive programming (we can set state in `context` and emit it in `beforeEachTest` closure)

Major disadvantage from rolling this out manually like above is that:
 - I have to declare `BaseTest` for all my test cases
 - I'm not sure how OK it's to derive from `DescribeSpec` (e.g. would something change when I use more complex setups, listeners, extensions, will IJ plugin work? etc). 
 - I'm not sure if there wouldn't be any threading-related gotchas

Some points for discussion:
 - I haven't given it much thought how it'd play with other isolation modes (should be fine but I don't use them so I might be missing something)
 - `beforeEachTest` is up for debate (Ginko uses `justBeforeEach` for example)
 - It might be confusing to declare both _context state_ and the resulting state side by side. I'm not sure what the alternative would be here
 - Would such feature even be in scope for KotlinTest?

Another thought: perhaps it could be implemented more generally by allowing some meta-data  for spec elements? Current example implementation primarily stems from the fact that it's the only way to share data from `context` block to the test case. However I'm not certain of how practical this approach would be, since the spec class would still miss extension point for defining `beforeEachTest` function.

**Comment by lwasyl** [comment]
One thing I forgot to mention: `beforeEachTest` isn't required to create some state, instead it can change the overall state of the system. The particular issue that I was experiencing was more pronounced in tests that used RxJava:

```kotlin
class RxClass(source: Observable<Int>) {

    var currentState: Int? = null

    init {
        source.subscribe { currentState = it + 100 }
    }
}

class RxTest : BaseTest({
    describe("RxClass") {
        val sourceSubject = PublishSubject.create<Int>()
        val sut = RxClass(sourceSubject)

        describe("emissions") {
            var emittedValue: Int? = null

            beforeEachTest {
                sourceSubject.onNext(checkNotNull(emittedValue))
            }

            context("given emitted value is 4") {
                emittedValue = 4

                it("should have 104 as current state") {
                    sut.currentState shouldBe 104
                }

                context("given 5 is then emitted") {
                    emittedValue = 5

                    it("should have 105 as current status") {
                        sut.currentState shouldBe 105
                    }
                }
            }

            context("given emitted value is 6") {
                emittedValue = 6

                it("should have 106 as current state") {
                    sut.currentState shouldBe 106
                }
            }
        }
    }
})
```

**Comment by sksamuel** [comment]
Can you do something like:

```
class RxClass(source: Observable<Int>) {

    var currentState: Int? = null

    init {
        source.subscribe { currentState = it + 100 }
    }
}

class RxTest : BaseTest({
    describe("RxClass") {
        val sourceSubject = PublishSubject.create<Int>()
        val sut = RxClass(sourceSubject)

        describe("emissions") {
            var emittedValue: Int? = null

            context("given emitted value is 4") {
                emittedValue = 4

                sourceSubject.onNext(checkNotNull(emittedValue))

                it("should have 104 as current state") {
                    sut.currentState shouldBe 104
                }

                context("given 5 is then emitted") {
                    emittedValue = 5

                    sourceSubject.onNext(checkNotNull(emittedValue))

                    it("should have 105 as current status") {
                        sut.currentState shouldBe 105
                    }
                }
            }

            context("given emitted value is 6") {
                emittedValue = 6

                sourceSubject.onNext(checkNotNull(emittedValue))

                it("should have 106 as current state") {
                    sut.currentState shouldBe 106
                }
            }
        }
    }
})
```

**Comment by lwasyl** [comment]
I could, but the point is to not repeat `sourceSubject.onNext(checkNotNull(emittedValue))` as it can get quite error-prone and unwieldy. Also the aim is to make tests read a bit more in declarative way.
That said I understand such particular feature would not be in scope of the library. In that case I'd still consider how to enable such extensions, such as being able to store scoped metadata during test execution
