### ISSUE TITLE
JDBC ResultSet matchers

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#961]
`ResultSet.shouldHaveColumnCount(n)`
`ResultSet.shouldContainColumn(label)`
`ResultSet.shouldHaveColumn(k, label)`

Any others we can think of.

**Comment by arunvelsriram** [comment]
I would like to work on this.

**Comment by sksamuel** [comment]
Please do!

**Comment by sksamuel** [comment]
See https://github.com/joel-costigliola/assertj-db#readme

**Comment by arunvelsriram** [comment]
Is this still relevant? As @sksamuel pointed out `assertj-db` is already providing assertions for databases.

**Comment by sksamuel** [comment]
assertJ won't do extension matchers because it's not a kotlin library.

**Comment by simonenkoi** [comment]
@sksamuel do you have any ideas on how API should look like for values assertions?
Should it be something like
```kotlin
resultSet shouldHaveColumn "name" {
   { it shouldBe "Hewson" }
   { it shouldBe "Evans" }
   { it shouldBe "Clayton" }
   { it shouldBe "Mullen" }
}
```
where the every lambda calls next value from ResultSet (analogue from https://github.com/joel-costigliola/assertj-examples/blob/master/assertions-examples/src/test/java/org/assertj/examples/db/TableAssertionExamples.java)

**Comment by sksamuel** [comment]
One option:

`resultset.shouldHaveColumn("name") { it shouldBe listOf(....) }` 

just pull back all the rows at once. This is a test, so I think that's fine, and then the lambda parameter is a collection, so then all the standard collection matchers work for no extra work.

**Comment by dragneelfps** [comment]
Anyone working on it? Status? Asking cuz I would like to work on it.

**Comment by sksamuel** [comment]
Please do.
