### ISSUE TITLE
Gen.combine with probabilistic choices

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#968]
Gen.combine(Gen.a, Gen.b) should take an element from a or b's gen each time, until the base case is reached.

Gen.frequency(0.1 to Gen.a, 0,2 to Gen.b) to specify the probability distribution.

**Comment by EarthCitizen** [comment]
@sksamuel Is this the same as #974 ? If not, what is the difference?

**Comment by sksamuel** [comment]
I can't quite remember. Maybe weighted is exact and this is generating
random values in a range and picking the element that falls in the range.
