### ISSUE TITLE
exhaustive generation option for property testing

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#969]
GenerationMode.AUTO - uses exhaustive mode where possible, otherwise defaults to random.
GenerationMode.RANDOM - forces random mode
GenerationMode.EXHAUSTIVE - forces exhaustive or throws an exception

**Comment by LeoColman** [comment]
Exhaustive as in use all possibilities?
I think some gens wouldn't work that way, right?

**Comment by sksamuel** [comment]
Basically if you say Gen.ints(0, 100) to generate random ints from 0 to
100, and then you ask for 200 tests to run, and you use random generation,
then you might never get 85 or 33. You might get 77 eight times.
In this case you should get 0 to 100 two times. That's better.
When you ask for Gen.ints() and 1000 tries, then it has to be random.

**Comment by LeoColman** [comment]
Then it's not exactly generating, right? It's just a sequence

**Comment by LeoColman** [comment]
Maybe a randomized sequence, but it's not entirely random

**Comment by EarthCitizen** [comment]
This sounds very related to #971, unique modifier.

**Comment by sksamuel** [comment]
Unique is different but related. So if you had `Gen.int().unique()` (or however we do it) then it would be 1000 unique random values for example.

But the idea of exhaustive mode is that if you say `Gen.int().filter { it < 500 }` and you ask for GenerationMode.EXHAUSTIVE then it shouldn't use random values because you might not get all 500. In fact you probably wouldn't. You might get the number 3 ten times, but never the number 453 for example.

**Comment by sksamuel** [comment]
Under the current design of Arbitraries and Progressions we don't need an exhaustive flag anymore so closing this. Will reopen if we go back to it.
