### ISSUE TITLE
Sentence generator

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#970]
Generates sentences by randomly putting together n words with a period.

**Comment by LeoColman** [comment]
Probably important to also add punctuation, capital cases, names, numbers, apostrophe, etc

**Comment by sksamuel** [comment]
Yep. Could be loads of variants.

**Comment by faogustavo** [comment]
@sksamuel  @Kerooker have you seen the [FakeIt](https://github.com/moove-it/fakeit) lib? Maybe it will help with a lot of points that you want.

**Comment by sksamuel** [comment]
Not sure this gen is that using, closing.
