### ISSUE TITLE
Unique modifier for Generators

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#971]
Filters out any value previously seen.

**Comment by EarthCitizen** [comment]
@sksamuel What should happen when unique values have been exhausted?

**Comment by sksamuel** [comment]
I think cycle back around again.

**Comment by LeoColman** [comment]
I think throwing an exception is better.
Cycling back again won't guarantee uniqueness

**Comment by EarthCitizen** [comment]
One concern is that this could be fairly resource intensive for `Gen.int().unique()`.

**Comment by LeoColman** [comment]
There could be a timeout configuration of some sort, but idk

**Comment by sksamuel** [comment]
I don't think unique should mean guarantee of no cycles just that if the
search space is larger than requested number then guaranteed unique.

**Comment by LeoColman** [comment]
I don't think we can guarantee that the search space is larger than requested number even if we want to allow cycles

**Comment by atmikev** [comment]
I've put up what I'm assuming is a naive implementation of `unique()`. Let me know what you think / where it could improve.
