### ISSUE TITLE
Flat map Gen for dependencies

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#972]
You might have a Gen for start index, and then want a gen for end index which must be > than start. So you need to be able to use an existing Gen to create further Gens (maps and flat maps).

**Comment by LeoColman** [comment]
Don't we have map and flatmap?

**Comment by sksamuel** [comment]
I don't think we have flatMap.

**Comment by EarthCitizen** [comment]
@sksamuel Can you create a code example based on your first comment of the use of `flatMap` if it existed?

**Comment by EarthCitizen** [comment]
Looks like `flatMap` was implemented and this should be closed?

**Comment by sksamuel** [comment]
Yep.
