### ISSUE TITLE
Add samples Generator

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#973]
Gen.samples(vararg xs :X) will take 1 or more Xs and then loop around providing those (starting from the beginning again once the end is reached).

**Comment by LeoColman** [comment]
So
`Gen.samples(1, 2, 3, 4, 5)` would lead to `[1, 2, 3, 4, 5, 1, 2, 3, 4, ...]`?

**Comment by sksamuel** [comment]
Yes

**Comment by LeoColman** [comment]
Closed as per #983
