### ISSUE TITLE
Weight choose Generators

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#974]
Add variations on Gen.choose, Gen.enum and so on that allows the weights to be specified.

**Comment by LeoColman** [comment]
I think [this class](https://github.com/thomasnield/kotlin-statistics/blob/master/src/main/kotlin/org/nield/kotlinstatistics/Random.kt#L111)  from [Kotlin Statistics](https://github.com/thomasnield/kotlin-statistics) might help.

I had to implement a weighted random distribution recently, and I used that

**Comment by sksamuel** [comment]
Wouldn't work cross platform but we could borrow implementations.

**Comment by LeoColman** [comment]
The implementation itself seems very mpp-friendly

**Comment by sksamuel** [comment]
Yes but they'd have to make the entire project mpp or we can copy n paste.

**Comment by EarthCitizen** [comment]
An easy way of doing this might be like this:

Say we have this map of weights and gens:
```
mapOf(1 to gen1, 5 to gne5, 3 to gen3)
```
If then another list is created based on the weights:
```
listOf(1, 5, 5, 5, 5, 5, 3, 3, 3)
```
Then choose a random integer between 0 and listOfWeights.size - 1 for the lookup key.

Might not give a mathematically correct result, but I believe it would serve what is requested.

**Comment by EarthCitizen** [comment]
Perhaps an easy way to do this would be the following:

Say we have a list of weights and gens:
```kotlin
val weightedGens = listOf(Pair(1, genA), Pair(3, genB), Pair(5, genC))
```
Then we create a list of indexes from above repeated by weight:
```kotlin
val repeatIndexes = listOf(0, 1, 1, 1, 2, 2, 2, 2, 2)
```
Then, we choose a random number between 0 and repeatIndexes size - 1 to select an element from repeatIndexes, and use that index to look up a gen from weightedGens.

This might not be mathematically correct, but I believe it would give the desired functionality. If it needed to work with negative numbers as well, there would need to be some offset trickery.
