### ISSUE TITLE
Add documentation for `shouldBeEqualIgnoringField`

### ISSUE THREAD

**Issue by LeoColman** [kotest/kotest#979]
Our reflection matchers don't have documentation besides Javadocs.

https://github.com/kotlintest/kotlintest/blob/master/kotlintest-assertions/src/jvmMain/kotlin/io/kotlintest/matchers/equality/reflection.kt

**Comment by ashishkujoy** [comment]
Done in [PR](https://github.com/kotest/kotest/pull/1296)
