### ISSUE TITLE
Possible error in shouldNotThrowAny

### ISSUE THREAD

**Issue by Zefz** [kotest/kotest#981]
Should not `shouldNotThrowAny` return the value in the block instead of Unit?

e.g
```
var foo: Bar = shouldNotThrowAny {
            Bar()
        }
```

While `shouldNotThrowAnyUnit` should return an Unit. Maybe I am misunderstanding something, but currently these two functions behave the same?

**Comment by sksamuel** [comment]
Yeah that's a bug, it should return T for () -> T.

**Comment by sksamuel** [comment]
Fixed in master.
