### ISSUE TITLE
autoClose can't be used when using Abstract*Spec.() -> Unit

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#987]
When writing test by providing closure in the spec constructor doesn't allow for using `autoClose` function:

```kotlin
class Test : DescribeSpec({
  describe("") {
      // autoClose() not available
  }
})
```

Is it inteded? If yes, what's the preferred workaround for this?

**Comment by sksamuel** [comment]
We need a DSL version. I'll add this to 4.0.

**Comment by sksamuel** [comment]
Current master (4.0) now allows this:

```kotlin
class AutoCloseDslTest : FunSpec({
   val closeme = AutoCloseable {
   }
   autoClose(closeme)
   test("auto close with dsl method") {
   }
})
```
