### ISSUE TITLE
Add map.shouldHaveSize assertion

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#990]

**Comment by sksamuel** [comment]
I don't believe we have this currently.

**Comment by verkhovin** [comment]
Should not we close it yet? :)

**Comment by LeoColman** [comment]
Sure thing!
I suggest closing issues when commiting https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by verkhovin** [comment]
> Sure thing!
> I suggest closing issues when commiting https://help.github.com/en/articles/closing-issues-using-keywords

Ok. Did not know. Thank you!
