### ISSUE TITLE
Flexible version of shouldHaveSize assertion

### ISSUE THREAD

**Issue by verkhovin** [kotest/kotest#998]
What do you think about implementing alternative to shouldHaveSize assertion, which applies as parameter something like `preidcate: (Int) -> Boolean` instead of `size: Int`?

In client's code it can looks like:
```kotlin
myMap shouldHaveSize { it > 5 } //true if myMap.size more than 5 obviously 
```

Maybe it is very rare case when you need this, so need somebody's opinion.

**Comment by LeoColman** [comment]
I think that in this case we should either use

`col.size shouldBeGreaterThan 5`

Or
`col.shouldHaveSizeGreaterThan 5`

Having a predicate imo is confusing

**Comment by verkhovin** [comment]
Sounds reasonable. But it seems there is no such methods for Map now?

**Comment by verkhovin** [comment]
Sounds reasonable.
