### ISSUE TITLE
Non complete junit report when using FunSpec

### ISSUE THREAD

**Issue by asm0dey** [kotest/kotest#999]
When I'm using FunSpec only inner-most tests are being written in test report while I expect whole path to be writtent as test name or maybe some grouping will exist.

For example in case of 

```kotlin
class MyTests : FunSpec({
	context("a test group") {
		test("String length should return the length of the string") {
			"sammy".length shouldBe 5
			"".length shouldBe 0
		}
	}
})
```
Only 

```xml
  <testcase name="String length should return the length of the string" classname="MyKTest" time="0.009"/>
```
will be written while context part may (and sould) have some meaningful context. 

It makes reports harder to read, harder to understand and harser to find failing tests

**Comment by LeoColman** [comment]
Perhaps we should include the entire thing in the report? Not sure how to do it yet tho

**Comment by asm0dey** [comment]
@Kerooker I believe that it could solve issue :) 
Second solution would be using hierarchy of test suites

**Comment by piotrgwiazda** [comment]
I'm not sure if JUnit XML Report support nested tests. It's flat. And as far as I can see JUnit 5 still does not have built-in support for advanced reporting as [here](https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-reporting).

I'd suggest having a flag in project configuration to switch between "flatten" tests in the report vs current leaf-only reporting. By the flatten names I mean something like [Describle]/[It] and [Context]/[Test] etc. 

Right now as a workaround I'm implementing own `AbstractSpec` that takes the name from the context and adds as a prefix.

Additionally, support for Cucumber, Serenity or Allure-style reports would be great!

**Comment by sksamuel** [comment]
We have an allure module already.

**Comment by asm0dey** [comment]
@sksamuel how can I find documentation on allure+maven+kotlintest setup?

**Comment by asm0dey** [comment]
I think that @piotrgwiazda's proposal makes great sense. But anyways I'm sure that authors of framework do read test reports. Could you please share how do you read reports?

**Comment by piotrgwiazda** [comment]
Allure reporting worth taking a look! May be used as a UAT sign-off document for a specific version.

However, flattening JUnits will be useful as well. Tools from Jenkins to Azure DevOps Pipelines automatically read these XML reports and gives you nice analytics and trends of build throughout last 7/14/30 days etc.

**Comment by asm0dey** [comment]
Still can't find any info on how to setup allure with kotlintest

**Comment by asm0dey** [comment]
Further activity is here. Still want this feature.

**Comment by sksamuel** [comment]
So the solution is for us to add a custom reporter that writes out an XML file in JUnit format but with every "level" flattened.

**Comment by asm0dey** [comment]
Still interested in this

**Comment by asm0dey** [comment]
Steel need it :)

**Comment by sksamuel** [comment]
Fixed in master. You will need to specify the build dir when you setup the tests in gradle like this: https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-junitxml/build.gradle.kts#L47

Additionally, you will need to add the JUnitXmlReporter as a listener manually, rather than using AutoScan, similar to this: https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-junitxml/src/jvmTest/kotlin/com/sksamuel/kotest/ProjectConfig.kt

When doing this second step, you are able to specify if you want container tests to be included in the output, and whether you want the full test path or just the final component to be used as the name.
